### ISSUE TITLE
(Question) Is it possible to only get facet counts for filter

### ISSUE THREAD

**Issue by jd-0001** [typesense/typesense#100]
## Description

Hi, I wish you are safe and healthy during this tough time. As typesense is great for filtering items, this is also common for developer to display available items they can search in their website(which can be achieved using facet counts).

The problem is I have 3 dropdowns where I have to query typesense 3 times to only get available items in all three dropdowns. So, when we query using typesense it also returns items which requires some resource of system. So, Is it possible to somehow(maybe we can set per_page to 0) only get facet counts and not find items in dataset?

## Steps to reproduce

None

## Expected Behavior

typesense doesn't query items when we only want facet count.

## Actual Behavior

I dont know if typesense try to query items when we set items per page to 0

**Comment by kishorenc** [comment]
Yes, this will be possible in the next release (hopefully by next week). I will update this thread when that's ready.

**Comment by jd-0001** [comment]
It's always great to hear from you buddy @kishorenc :blush:

**Comment by kishorenc** [comment]
👍 Btw, I also had a rethink on https://github.com/typesense/typesense/issues/81 -- I understand that having items not being strictly ordered on the UI will look a bit odd, so going to expose the underlying text match score as a special field that can be used in the `sort_by` parameter. 

This way, you can say something like `sort_by=price:desc,_match_score:desc` to ensure that a list of items are strictly ordered first by price and then by match score. Ofc, the issue I mentioned about this resulting in items with less relevancy remains, but will leave that discretion to the developer.

**Comment by kishorenc** [comment]
v0.12 has landed and has support for `max_hits` parameter. Set it to `0` during query to ensure that only facet counts are returned.

**Comment by jd-0001** [comment]
Hi, @kishorenc I tested your latest TypeSense executable and also version 0.13.0 but even if I use `max_hits` parameter I get hits in response along with `facet_counts` :thinking: 

Here's my Query(Python):
![Screenshot from 2020-06-16 18-13-28](https://user-images.githubusercontent.com/47495003/84775665-1e68e900-affd-11ea-9ec2-ca9ee9728bfb.png)

**Comment by kishorenc** [comment]
Sorry this parameter was removed in 0.13.0. You can now just use `per_page=0`. We removed it since it was redundant. It was mentioned in the change log.
