### ISSUE TITLE
Support for (only) indexing nested fields in an array of objects using dot notation.

### ISSUE THREAD

**Issue by David5280** [typesense/typesense#1006]
## Description

I am currently trying to set up typesense using the firebase extension.  We're monitoring one collection and want to index certain fields, some of which are nested in an array of objects. I specify `field1` in the `Firestore Collection Fields` input, and in my schema I try to reference `field1.nested1.nested2`.  Again, this value has this shape: 
`field1: {
  nested1: [ ... { nested2: <value> } ]
}`.  
When items are saved to firebase, I see 
`Error: Request failed with HTTP code 404 | Server said: Field field1.nested1.nested2 not found.`
in the firebase logs

Related thread about this issue: https://github.com/typesense/typesense/issues/227#issuecomment-1219117094
Related slack thread: https://typesense-community.slack.com/archives/C01P749N8HL/p1683566890758039

## Steps to reproduce

- Setup a firebase collection with some values.  One of these values should be an array of objects, each object containing a string value.
- Create a new typesense collection, and in the schema, try to reference this nested string value directly using dot notation (e.g. `fields: { "name": "field1.nested1.nested2", "type": string[] }`)` 
- Install the typesense extension onto your firebase collection.  Put `field1` in the `Firestore Collection Fields` input
- Once installed, add some data to this firebase collection.  Data is expected to index into typesense.
- Data is not indexed, see error in firebase logs instead: `Error: Request failed with HTTP code 404 | Server said: Field field1.nested1.nested2 not found.`

## Expected Behavior

The data should be indexed to typesense, and I should be able to target the nested field in my search query.

## Actual Behavior

No data is indexed to typesense, and firebase logs produce the following error: 
`Error: Request failed with HTTP code 404 | Server said: Field field1.nested1.nested2 not found.
    at ApiCall.customErrorForResponse (/workspace/node_modules/typesense/lib/Typesense/ApiCall.js:226:21)
    at ApiCall.performRequest (/workspace/node_modules/typesense/lib/Typesense/ApiCall.js:118:48)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)`

## Metadata

**Typesense Version**:
Typesense v0.24.1

**OS**:
macOS Ventura 13.3.1

**Comment by kishorenc** [comment]
I've fixed a related issue in 0.25 RC build recently. Can you please try against that: `typesense/typesense:0.25.0.rc27`.

Here's a snippet I tried that works on 0.25: https://gist.github.com/kishorenc/786f9e8bb5ed0e51d3adce421503ec89

NOTE: Ensure that you've enabled nested fields in the schema.

**Comment by jasonbosco** [comment]
@David5280 If you can email your Typesense Cloud Cluster ID to support at typesense dot org we can upgrade your cluster to this RC build.

**Comment by David5280** [comment]
Thanks!  Done.

**Comment by David5280** [comment]
I'm getting the same error when attempting this on `typesense/typesense:0.25.0.rc27`.

Firebase cloud functions error:
`Error: Request failed with HTTP code 404 | Server said: Field field1.nested1.nested2 not found.
    at ApiCall.customErrorForResponse (/workspace/node_modules/typesense/lib/Typesense/ApiCall.js:226:21)
    at ApiCall.performRequest (/workspace/node_modules/typesense/lib/Typesense/ApiCall.js:118:48)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)`

**Comment by jasonbosco** [comment]
@David5280 `v0.4.x` and earlier versions of the Firebase extension pre-flattened fields before sending the data over to Typesense in a way that did not work well with nested fields in v0.24 of Typesense Server.

So could you update your Firebase extension to v1.x, which will then show you a new option in the configuration screen called "Flatten nested fields". Could you set that to "No" and then run a backfill into your Typesense collection?

**Comment by David5280** [comment]
![Screenshot 2023-05-11 at 12 20 59 PM](https://github.com/typesense/typesense/assets/46681659/a5dbd3e1-8d9b-4344-95ba-0713566130d4)

It appears to think that it's up to date.. I'm trying to find a way to force it to update through the firebase console.  Will update here.

**Comment by David5280** [comment]
I could install v1.x only through the link on the [readme](https://github.com/typesense/firestore-typesense-search), and was notified that v1.x isn't fully published on firebase yet, just FYI.

**Comment by jasonbosco** [comment]
Hmm, that's alert seems to be new. Will take a look.

**Comment by David5280** [comment]
I think this is working for me at the moment, still verifying but it's looking good.

**Comment by David5280** [comment]
I haven't had any issues on `typesense/typesense:0.25.0.rc27` and extension version `1.0.1`, thank you!
