### ISSUE TITLE
content-value has the wrong value using nodejs client (axios)

### ISSUE THREAD

**Issue by devbrains-com** [typesense/typesense#101]
## Description
I'm using the javascript library (yarn add typesense) and getting 400 Bad Request from Webservers checking the content-length (Google Cloud Run). I figured out, its coming from the wrong content-length added by the axios client.

## Steps to reproduce

1. Run the docker image in Google Cloud Run
2. Create a collection
3. query it (await client.collections("companies").documents().search(searchParameters))

## Expected Behavior

Search Results and a status code 200

## Actual Behavior

Error 400 (Bad Request) and no search results

## Metadata

**Typsense Version**: 0.3.0 (javascript library, nodejs)

**OS**: windows 10

**Comment by kishorenc** [comment]
@devbrains-com Can you please try against the latest version of the JS client and v0.12.0 of Typesense (both release yesterday)? Will be happy to troubleshoot further if the issue still persists.

**Comment by kishorenc** [comment]
Closing this for now. Feel free to reopen an issue on the [JS repo](https://github.com/typesense/typesense-js) if needed.
