### ISSUE TITLE
Upsert action breaks nested fields

### ISSUE THREAD

**Issue by sashahohloma** [typesense/typesense#1011]
## Description

When working with nested fields, I noticed that a partial update duplicates fields that were not specified during the update. This happens with any update action: upsert, update, emplace; also when updating in batches or one document at a time

## Steps to reproduce

Create index
```json
{
    "name": "products",
    "enable_nested_fields": true,
    "fields": [{
        "name": "product_id",
        "type": "int32",
        "index": false,
        "sort": false,
        "optional": true
    }, {
        "name": "name",
        "type": "string",
        "index": false,
        "optional": true
    }, {
        "name": "brand",
        "type": "object",
        "index": true,
        "sort": false,
        "optional": true
    }, {
        "name": "brand.id",
        "type": "int32",
        "index": true,
        "sort": false
    }, {
        "name": "brand.name",
        "type": "string",
        "index": false,
        "sort": false,
        "optional": true
    }]
}
```

then create document with command: `collections/products/documents?action=emplace`
```json
{
    "id": "b4db5f0456a93320428365f92c2a54ce15df2d0a",
    "product_id": 63992305,
    "name": "Chips",
    "link": "http://wicked-uncle.biz",
    "brand": {
        "id": 34002,
        "name": "Hodkiewicz - Rempel"
    }
}
```
then try to update any field of document with command: `collections/products/documents?action=emplace`
```json
{
    "id": "b4db5f0456a93320428365f92c2a54ce15df2d0a",
    "brand": {
        "name": "Rempel"
    }
}
```

## Expected Behavior

Document keeps original structure after partial updating
```json
{
    "id": "b4db5f0456a93320428365f92c2a54ce15df2d0a",
    "product_id": 63992305,
    "name": "Chips",
    "link": "http://wicked-uncle.biz",
    "brand": {
        "id": 34002,
        "name": "Rempel"
    }
}
```

## Actual Behavior

All unupdated nested fields will move on root level with dot notation naming
```json
{
    "brand": {
        "name": "Rempel"
    },
    "brand.id": 34002,
    "id": "b4db5f0456a93320428365f92c2a54ce15df2d0a",
    "link": "http://wicked-uncle.biz",
    "name": "Chips",
    "product_id": 63992305
}
```

**Typesense Version**:
typesense/typesense:0.24.0
typesense/typesense:0.25.0.rc27

**Comment by kishorenc** [comment]
Thank you so much for reporting this issue @sashahohloma. I'm able to reproduce and already looking into what's happening here.

**Comment by kishorenc** [comment]
@sashahohloma 

Putting aside the fact that flattened fields are showing up in response, what do you think should be the correct behavior for the various update actions (emplace, upsert, update)?

For example, given a document with an existing nested field `person` with properties `name`, `age` and `address`, what should happen when I import a document with 2 out of those 3 fields with new values and 1 field entirely missing. 

Should we treat it as a partial update (i.e. ignore the missing field) or treat it as deletion of the missing field? Should the behavior be different given action mode of update, emplace and upsert? I would like to hear your thoughts here.

**Comment by kishorenc** [comment]
IMO, the behavior should be similar to how we treat fields on a non-nested document. Here's how that works:

```
upsert: deletes missing field
emplace: missing field is not deleted
update: missing field is not deleted
```

**Comment by kishorenc** [comment]
@sashahohloma 

I've a fix in `typesense/typesense:0.25.0.rc29` Docker build -- can you please give that a shot? Behavior is exactly how you've described above.

**Comment by muneebshahid** [comment]
Thank you for the fix. Any idea when this will be available for typesense cloud?

**Comment by kishorenc** [comment]
@muneebshahid 

You can schedule an upgrade from within Typesense Cloud (just mention 0.25 RC as the version). Or email support with ClusterID and we can run the upgrade.
