### ISSUE TITLE
Geosearch OSS not working

### ISSUE THREAD

**Issue by leobispo** [typesense/typesense#1013]
## Description

Geosearch on OSS version is returning Bad Request

## Steps to reproduce

Install the open source version and execute these steps:

https://typesense.org/docs/0.24.1/api/geosearch.html#searching-within-a-radius

(Tested on Cloud and it is working as expected)

## Expected Behavior

Return data

## Actual Behavior

Returned Bad Request

## Metadata

**Typesense Version**: 0.24.1

**OS**: Linux

**Comment by jasonbosco** [comment]
We actually run the same binaries we publish open source on Typesense Cloud as well!

Could you use [this script](https://gist.github.com/jasonbosco/7c3432713216c378472f13e72246f46b), change it to your schema, with a few sample documents and the exact search query which is returning Bad request for you, along with the output of each command?

**Comment by leobispo** [comment]
There is no Geopoint in this script. Could you please add the geopoint as well?

**Comment by jasonbosco** [comment]
That was just a reference script. If you can just share a standalone script like that, based on the queries you're sending to Typesense, that would help debug this faster.

**Comment by leobispo** [comment]
```sh
export TYPESENSE_API_KEY=xyz

curl -k "http://localhost:8108/collections" -X POST \
      -H "Content-Type: application/json" \
      -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{
        "name": "places",
        "fields": [
          {"name": "title", "type": "string" },
          {"name": "points", "type": "int32" },
          {"name": "location", "type": "geopoint"}
        ],
        "default_sorting_field": "points"
      }'

curl "http://localhost:8108/collections/places/documents" -X POST \
        -H "Content-Type: application/json" \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
        -d '{"points":1,"title":"Louvre Museuem", "location": [48.86093481609114, 2.33698396872901]}'

curl -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
"http://localhost:8108/collections/places/documents/search?q=*&query_by=title&\
filter_by=location:(48.853,2.344,5.1 km)&sort_by=location(48.853, 2.344):asc"
```

result:

{"message": "A collection with name `places` already exists."}{"id":"2","location":[48.86093481609114,2.33698396872901],"points":1,"title":"Louvre Museuem"}Bad Request

```
ubuntu@ip-10-60-5-116:~$ dpkg -l | grep typese
ii  typesense-server                     0.24.1                            amd64        Typesense Server
```

**Comment by leobispo** [comment]
Some more info:

I installed the version on my Mac machine and it is working as expected. So I am assuming is something on the .deb package

**Comment by jasonbosco** [comment]
This is actually a [URL-encoding issue](https://stackoverflow.com/questions/296536/how-to-urlencode-data-for-curl-command). I'll update the docs, but if you use this code snippet it works for me:

```shell
curl -G -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
  --data-urlencode 'q=*' \
  --data-urlencode 'query_by=title' \
  --data-urlencode 'filter_by=location:(48.853,2.344,5.1 km)' \
  --data-urlencode 'sort_by=location(48.853, 2.344):asc' \
'http://localhost:8108/collections/places/documents/search'
```

**Comment by leobispo** [comment]
Worked

**Comment by jasonbosco** [comment]
Thank you for confirming. I've updated the docs.
