### ISSUE TITLE
Feature Request: Use vector_distance on sort_by

### ISSUE THREAD

**Issue by Persitz** [typesense/typesense#1022]
## Description

It would be useful to be able to use the **vector_distance** on the **sort_by**.
Examples of uses:
- Custom ranking, using for instance the techniques in: https://typesense.org/docs/guide/ranking-and-relevance.html#tie-breaking-based-ranking
- Shuffle the results of similar vector_distance so very similar results are not so close to each other.

**Comment by jasonbosco** [comment]
This is now supported in `0.25.0.rc61`.
