### ISSUE TITLE
Create and import fails in JS bindings for object writes with booleans

### ISSUE THREAD

**Issue by toddtarsi** [typesense/typesense#1025]
## Description

Import fails with parse errors for plain JS objects

## Steps to reproduce

Try and import this json object via the JS bindings:

```
[{
  id: '1',
  boolean: false
}]
```

This error started occurring approximately 1 week ago, and import and create appear to be non-functional.

## Expected Behavior

Import succeeds

## Actual Behavior

RequestMalformed: Request failed with HTTP code 400 | Server said: Bad request.

Looking closer at Typesense server logs, I see this:

Exception while calling handler documents:import
Raw error: regex_error

I tried manually collapsing to a JSONL string, validating with chatgpt, and uploading after it got a pass, and it still failed.
I feel like the metadata parsing is broken on the server or there is some requirement here I've been missing.

## Metadata

**Typesense Version**: 0.23 latest rc, but updated to 0.25 latest rc, and issue still occurs
**Typesense Client Version**: 1.2.2, but also occurs on 1.5.3

**OS**: Mac OSX

**Comment by toddtarsi** [comment]
This appears to crash on create and import on my Mac M1. I think it has to be Mac M1 specific because otherwise our production servers would be down.

**Comment by toddtarsi** [comment]
Actually, this crashes on our CI as well. I have no idea why production is still functional.

**Comment by toddtarsi** [comment]
Hm, so I am not sure we're writing that boolean to typesense yet in production. That might be why its started detonating the pipeline elsewhere first.

**Comment by toddtarsi** [comment]
Oh. Adding a boolean field to the schema resolves this issue. Very easy workaround haha. Nevermind me!

**Comment by jasonbosco** [comment]
I just tried running [this code snippet](https://github.com/typesense/typesense/issues/1025#issuecomment-1553252981) on `0.24.1` (mac binary installed via homebrew) on an M1, and it doesn't seem to crash for me:

```
Request #1684430438255: Performing POST request: /collections
Request #1684430438255: Nodes Health: Node 0 is Healthy
Request #1684430438255: Updated current node to Node 0
Request #1684430438255: Attempting POST request Try #1 to Node 0
Request #1684430438255: Request to Node 0 was made. Response Code was 201.
Request #1684430438274: Performing POST request: /collections/example-collection-1684430438254/documents/import
Request #1684430438274: Nodes Health: Node 0 is Healthy
Request #1684430438274: Updated current node to Node 0
Request #1684430438274: Attempting POST request Try #1 to Node 0
Request #1684430438274: Request to Node 0 was made. Response Code was 400.
(node:31239) UnhandledPromiseRejectionWarning: RequestMalformed: Request failed with HTTP code 400 | Server said: Bad request.
```

In the Typesense logs I see:

```
I20230518 12:20:37.518203 317739008 raft_server.h:60] Peer refresh succeeded!
W20230518 12:20:38.271165 323641344 field.cpp:482] Collection schema cannot contain a field with name `id`. Ignoring field.
E20230518 12:20:38.278743 323641344 batched_indexer.cpp:227] Exception while calling handler documents:import
E20230518 12:20:38.278788 323641344 batched_indexer.cpp:228] Raw error: One of *?+{ was not preceded by a valid regular expression.
I20230518 12:20:48.246973 299495424 raft_server.cpp:546] Term: 11, last_index index: 642, committed_index: 642, known_applied_index: 642, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 16482
I20230518 12:20:48.247170 317739008 raft_server.h:60] Peer refresh succeeded!
```

But it still doesn't crash... 🤔

**Comment by toddtarsi** [comment]
This is me using poor terminology. I'm sorry, I should have said fail, not crash.

**Comment by jasonbosco** [comment]
Ahh got it! 

I just noticed this in the schema:

```
{
        name: '*',
        type: 'auto',
        facet: false,
      },
```

It should be

```
{
        name: '.*',
        type: 'auto',
        facet: false,
      },
```

You want to change `*` to `.*`, since the former is not a valid regex.

**Comment by toddtarsi** [comment]
@jasonbosco - Oh wowie! I had no idea! Our auto field thing has been wrong this whole time. Thank you very much! I'd be happy to close but I'll leave it to you.
