### ISSUE TITLE
How to rank/sort by date closest to now?

### ISSUE THREAD

**Issue by mbrimmer83** [typesense/typesense#1026]
## Description

How to rank/sort by date closest to now? Recency boost?

## Steps to reproduce

Example: we have events and those events have dates on which the events are held. In our search results, we want to boost the events that are upcoming. The events a year or two away are still relevant in the search but less so than the event that is happening in two weeks. How can this be done? I don't see anything in the docs indicating this is possible.

## Metadata

**Typesense Version**: latest

**OS**: linux

**Comment by jasonbosco** [comment]
You could use [Optional Filtering](https://typesense.org/docs/0.24.1/api/search.html#sorting-based-on-conditions) for this.

So something like:

```
sort_by: _text_match(buckets: 10):desc,_eval(event_starts_at:>start_unixtimestamp && event_starts_at:<end_unixtimestamp ):desc
```

You'd set `start_unixtimestamp` and `end_unixtimestamp` dynamically when you do the search query, to the timeframes you want to boost up.

**Comment by mbrimmer83** [comment]
Ok, so the further away the timestamp gets from the timestamp values you set at query time the lower the bucket it is placed in, thus the lower the ranking?

**Comment by jasonbosco** [comment]
The `buckets` parameter is more to force a text match score tie between adjacent records. 

So Typesense will first rank the results as usual in descending order of text relevance, then divide this result set into 10 buckets where within each bucket the text match score is forced into a tie, so the next `_eval` field is used to break the tie. 

In this case, the _eval will evaluate to true for all events within the range you specify, and so those will get boosted up. 

As you keep changing the time range you send to the query, it will boost the records within that "recent" timeframe.

**Comment by mbrimmer83** [comment]
Awesome, thanks for the super quick response, going to try this out.
