### ISSUE TITLE
Encode filters into signed API key

### ISSUE THREAD

**Issue by RyanBertrand** [typesense/typesense#103]
Is there anyway to sign API keys with filters encoded so we can use the client side queries without going through our API to restrict data to the account. 

Thanks!

**Comment by kishorenc** [comment]
There is no way to do that but it's definitely in the roadmap.

**Comment by jasonbosco** [comment]
We just released support for API Key Management in Typesense v0.13. Here's how you embed filters into scoped API keys: https://typesense.org/docs/0.13.0/api.html#generate-scoped-search-key

**Comment by RyanBertrand** [comment]
Nice! I will check it out next week. Thank you!
