### ISSUE TITLE
Good news: I finally have a preview build that contains support for indexing and searching on nested fields!

### ISSUE THREAD

**Issue by dailytravel** [typesense/typesense#1031]
Please commit new version to add EnableNestedFields in typesense-go!

**Comment by kishorenc** [comment]
@dailytravel 

It's already part of the Go client, see here: https://github.com/typesense/typesense-go/blob/master/typesense/api/types_gen.go#L112

**Comment by dailytravel** [comment]
Hi!

I see, thank you so much!
