### ISSUE TITLE
Demo on https://typesense.org/ on doesn't work

### ISSUE THREAD

**Issue by bynormous** [typesense/typesense#104]
Hi I went to your site to see if you have a hosted service, but first thing I noticed was the Book demo input box on https://typesense.org/ doesn't work and throws this error:

<img width="1368" alt="Screen Shot 2020-04-30 at 10 34 16 AM" src="https://user-images.githubusercontent.com/9891511/80741223-25c84780-8ace-11ea-8714-8e2ee3f5ac39.png">

**Comment by kishorenc** [comment]
Thank you for the heads up -- this has been fixed now.
