### ISSUE TITLE
Colon (:) Token Separator not valid

### ISSUE THREAD

**Issue by imalao** [typesense/typesense#1053]
## Description

I am trying to add the colon `:` to the token separator list and this is not working.

## Steps to reproduce

I tried to create a collection with `token_separators = [":"]` and get this error : `e: Request failed with HTTP code 400 | Server said: `token_separators` should be an array of character symbols.`

Using  other separators like `token_separators = [","]` works!
```
{
  "name": "companies",
  "fields": [
    {
      "name": "company_name",
      "type": "string"
    },
    {
      "name": "num_employees",
      "type": "int32",
      "facet": true
    },
    {
      "name": "country",
      "type": "string",
      "facet": true
    }
  ],
  "default_sorting_field": "num_employees",
  "enable_nested_fields": true,
  "token_separators": [":"]
}
```

## Expected Behavior

Colon is a valid token separator

## Actual Behavior

I get an error

## Metadata

**Typesense Version**: v0.24.1

**OS**: n/a

**Comment by kishorenc** [comment]
@imalao 

I'm not able to reproduce this issue. See here: https://gist.github.com/kishorenc/75f96d94ab0022892366a392ccf0fa7c

**Comment by kishorenc** [comment]
Please make sure that the colon character is not some multi-byte unicode character.
