### ISSUE TITLE
Customise highlight snippet size and fields

### ISSUE THREAD

**Issue by elephantflea** [typesense/typesense#106]
## Description

Currently the highlight snippet size is up to 5 tokens either side of the highlighted value. Can a url parameter be added to control snippet/token size at query time.

Also can highlighting be turned off (or on) for certain fields either by a query parameter or as part of indexing rather than all fields. In my case I have a generic `keywords` field:

`{"name": "keywords", "type": "string" }`

That I have included in the `exclude_fields` query parameter as it isn't needed for the display of the results but it is still returned in the highlighting section.

An example query could look like;

`/collections/mycollection/search?query_by=name,description,keywords&q=red&highlight=description&highlight_size=10`

## Metadata

**Typsense Version**:  v0.11.2

**OS**: Ubuntu

**Comment by kishorenc** [comment]
@elephantflea 

1. Would it be sufficient if there was an option to specify a list of fields which will be highlighted fully without snippeting?

2. As for the other problem, I think fields in `exclude_fields` list should not be highlighted at all. I will make sure that this is fixed. Unless there is a genuine use case for disabling highlighting on a field but wanting to see the field content in the results.

**Comment by elephantflea** [comment]
@kishorenc 

1. So instead of showing the snippet it would be the entire field but including any `<mark>` tags?
2. I can't think of a reason why you would need the highlighted field if you have excluded the unhighlighted field so skipping the fields in `exclude_fields` sounds good

**Comment by kishorenc** [comment]
> it would be the entire field but including any <mark> tags?

Not, it will return the entire field value **with highlighting** (so <mark> tags will be present),  instead of just the partial relevant portion.

**Comment by elephantflea** [comment]
Sounds good, that will work

**Comment by kishorenc** [comment]
@elephantflea 

v0.12.0 has just landed and it has 2 features which will help here:

1. `highlight_full_fields` parameter: Comma separated list of fields which should be highlighted fully without snippeting. By default all fields will be snippetted.

2. We also now don't highlight excluded fields even if it is queried on.

Check it out and let me know if you notice any issues!

**Comment by Grafikart** [comment]
Is it still possible to get the original parameter ? 

A parameter that gives the ability to choose the how many words we want around the `<mark>`. 5 is a bit too short and setting highlight_full_fields or snippet_threshold is too restricted I think.

**Comment by kishorenc** [comment]
@Grafikart I agree 💯 and ran into this inconvenience myself. There is already a fix for this in the working branch. Will be part of the next release, about a week away. Reopening this issue for tracking.

**Comment by kishorenc** [comment]
The ability to specify number of tokens before and after the highlight is available via the `highlight_affix_num_tokens ` parameter as part of v0.16.0 just released 🎉

From the docs:

> highlight_affix_num_tokens : The number of tokens that should surround the highlighted text on each side. Default: 4
