### ISSUE TITLE
Error: 400 - Wildcard query is not supported for embedding fields.

### ISSUE THREAD

**Issue by vp-walter** [typesense/typesense#1072]
## Description

- added embeddings to the typsense documents.
- we use instantsearch to interact with typesense.
- When the request is sent we get: Error: 400 - Wildcard query is not supported for embedding fields.

I am guessing that instantsearch adds the wildcard to the query parameter when there is an empty string.

## Metadata

**Typesense Version**:

Typesense v0.25.0.rc34

**Comment by jasonbosco** [comment]
@vp-walter We addressed this in `0.25.0.rc41`. Could you upgrade to that build and try again?

**Comment by vp-walter** [comment]
thank you that fixed it!
