### ISSUE TITLE
Feature request: Built-in image embeddings

### ISSUE THREAD

**Issue by gustavopch** [typesense/typesense#1073]
The idea is to enable searching images (or images + text). A good reference of how that could be done is https://marqo.ai. Instead of adding an image field, it could just read the URL from a string field and fetch the image server-side to generate the embedding.

**Comment by kishorenc** [comment]
Reading from a remote URL is a bit wasteful and flaky. We could support upload and encoding of image into vectors but not store it. The image can be sent in base64 encoded form within JSON document. If we supported gzip encoding of import stream (work already in progress), then this should be efficient.

**Comment by gustavopch** [comment]
And maybe resize the image down before uploading. Just guessing, but I suppose for most cases the quality of the search wouldn't change beyond a certain resolution. Maybe make the resolution configurable in the SDKs so people can send larger or smaller images according to their use cases.

**Comment by gustavopch** [comment]
I believe this can be closed.
