### ISSUE TITLE
Feature request: ability to create non-indexed, but required fields

### ISSUE THREAD

**Issue by b0g3r** [typesense/typesense#1080]
## Description

In our use-case we have complex object as input, then extract from this object all searchable data and fill this data into typesense. We also place original raw object as non-indexed field.

Unfortunately Typesense raises an error when we try to make the field non-optional.

From Kishore:

> Historically the required field has always been applied for only those that are part of the index. So if a field is marked as required, it cannot be non indexed.
> But we will likely fix it
> It's a small check we have to remove

**Comment by kishorenc** [comment]
Fixed in `0.26.0.rc20`.

**Comment by jasonbosco** [comment]
Released in v26
