### ISSUE TITLE
Kubernetes Operator for Typesense

### ISSUE THREAD

**Issue by sai3010** [typesense/typesense#1086]
## Description

Hi! I have created an operator for managing Typesense. Please check it out here:
https://github.com/sai3010/Typesense-Kubernetes-Operator#readme

@kishorenc It would be great if you could mention this somewhere in the installation instructions.

**Comment by kishorenc** [comment]
I'll add a note in the docs for the upcoming 0.25 release.

**Comment by jasonbosco** [comment]
This mentioned in the docs here: https://typesense.org/docs/guide/install-typesense.html#kubernetes
