### ISSUE TITLE
If _eval for sort_by contains comma Typesense acts weirdly

### ISSUE THREAD

**Issue by b0g3r** [typesense/typesense#1089]
## Description

I tried to implement something similar to the [example](https://typesense-community.slack.com/archives/C01P749MET0/p1687277609980759?thread_ts=1687269558.944439&cid=C01P749MET0), but failed. It looks like Typesense splits the whole `sort_by` by commas without taking into account complex `_eval` conditions.

## Steps to reproduce

https://gist.github.com/b0g3r/02d2835141a7b061d790360e53bec4bb

## Expected Behavior

As in `#2 search`

## Actual Behavior

Varios errors like  `Only upto 3 sort fields are allowed`, `Could not find a field named _eval(users_id in the schema for sorting.`, `Parameter sort_by is malformed.`

## Metadata

**Typesense Version**:
0.25.0.rc38

**Comment by b0g3r** [comment]
Just wanted to add a use case so this parsing bug can be prioritized in the next RC 🌚. 

We have a dataset of articles, where each article has different metadata like SME, saved in favorites, update date, expected user status and others. We created a boolean condition that converts all this data into "relevant or probably not" and wanted to use it as a sort parameter to show relevant articles on the first places. Unfortunately, _eval doesn't support comma at the moment, so we can't use arrays in the boolean expression and it blocks us from the relevancy feature.

**Comment by kishorenc** [comment]
Fixed in `0.26.0.rc20`.

**Comment by b0g3r** [comment]
Confirm, fix works 🕺

**Comment by jasonbosco** [comment]
Released in v26
