### ISSUE TITLE
query_by should be optional when q=*

### ISSUE THREAD

**Issue by fabien** [typesense/typesense#109]
## Description

Currently, the `query_by` search parameter is required, which makes sense. However, it is more or less irrelevant when `q=*`.

## Steps to reproduce

`http://localhost:8108/collections/companies/documents/search?q=*`

## Expected Behavior

When `q=*` the `query_by` should become optional.

## Actual Behavior

Instead, an error is thrown: `Parameter `query_by` is required`

**Comment by kishorenc** [comment]
Fixed in `v0.1.4.0` just released.
