### ISSUE TITLE
Make the filter clauses limit configurable.

### ISSUE THREAD

**Issue by s-gal** [typesense/typesense#1096]
## Description

I face a problem when building a scoped key filter that if it gets too complex. I have the following use case that i need to define filters for customers in combination with addresses. if i add too many of these combination i get the error displayed below when searching the first time with this scoped key, even though the filter is still in correct typesense syntax.

## Steps to reproduce

Define a data-collection with the 5 string fields shipment_unit_code, shipment_unit_code_group_lvl1, shipment_unit_code_group_lvl2, shipment_unit_code_group_lvl3 and shipment_origin_location. 

Create a scoped key with following filter_by expression:

((shipment_unit_code:= `TEST1` || shipment_unit_code_group_lvl1:= `TEST1` || shipment_unit_code_group_lvl2:= `TEST1` || shipment_unit_code_group_lvl3:= `TEST1`) && (shipment_origin_location:=`1`)) || 
((shipment_unit_code:= `TEST2` || shipment_unit_code_group_lvl1:= `TEST2` || shipment_unit_code_group_lvl2:= `TEST2` || shipment_unit_code_group_lvl3:= `TEST2`) && (shipment_origin_location:=`2`)) || 
((shipment_unit_code:= `TEST3` || shipment_unit_code_group_lvl1:= `TEST3` || shipment_unit_code_group_lvl2:= `TEST3` || shipment_unit_code_group_lvl3:= `TEST3`) && (shipment_origin_location:=`3`)) || 
((shipment_unit_code:= `TEST4` || shipment_unit_code_group_lvl1:= `TEST4` || shipment_unit_code_group_lvl2:= `TEST4` || shipment_unit_code_group_lvl3:= `TEST4`) && (shipment_origin_location:=`4`)) ||
((shipment_unit_code:= `TEST5` || shipment_unit_code_group_lvl1:= `TEST5` || shipment_unit_code_group_lvl2:= `TEST5` || shipment_unit_code_group_lvl3:= `TEST5`) && (shipment_origin_location:=`5`)) || 
((shipment_unit_code:= `TEST6` || shipment_unit_code_group_lvl1:= `TEST6` || shipment_unit_code_group_lvl2:= `TEST6` || shipment_unit_code_group_lvl3:= `TEST6`) && (shipment_origin_location:=`6`))

Then do a search with this scoped key and you should get my stack trace.

The strange thing here is if i just remove one row of the filter (e.g. everything with TEST6) it suddenly works... So there seemes to be somewhere an technical limitation somewhere preventing this? Also it seemes to me that the many OR's might cause this? But only if it is nested? These are just guesses but maybe you can find thee problem with this information.

## Expected Behavior

Filter should work :)

## Actual Behavior

I receive this StackTrace:

Request failed with status code: 400.Server said: Filter expression is not valid.
org.typesense.api.exceptions.RequestMalformed:
Request failed with status code: 400.Server said: Filter expression is not valid.
	at org.typesense.api.ApiCall.getException(ApiCall.java:111)
	at org.typesense.api.ApiCall.makeRequest(ApiCall.java:308)
	at org.typesense.api.ApiCall.get(ApiCall.java:143)
	at org.typesense.api.Documents.search(Documents.java:43)

## Metadata

**Typesense Version**: 0.24.1

**OS**: Linux docker image

**Comment by kishorenc** [comment]
@s-gal 

Can you try with the `/multi_search` end-point? I wonder if the scoped API key is becoming too large for the GET request.

**Comment by s-gal** [comment]
@kishorenc error occurs als with `/multi_search` end-point...

wondering if the size of the API-KEY is the problem... if i add to the scoped key something like shipment_unit_code:=[`TEST1`,`TEST2`.....] it seemes like i could add hundreds of values here and the scoped key still causees no harm.. But for me very hard to say what's inside of typesense going on technically.

**Comment by s-gal** [comment]
Also just tested it with the newest typesense version of `0.25.0.rc45` just in case you might have fixed it already accidentally in the last weeks but it's not the case. Still can reproduce it there

**Comment by kishorenc** [comment]
Ok will look into this and get back to you.

**Comment by s-gal** [comment]
@kishorenc yes now more complicated filters are working and this helps a bit. Seemes to me as you doubled the limit?
We probably still could face problems in the future in our use case... 
So my scoped filter failed with this `0.25.0.rc48`-version now that has 46 OR-operators ( `||` ) and 6 AND-operators ( `&&` ). Does one operator count as 2 clauses because of the 2 characters? Or are brackets ( `()` ) also counting to this limitation?
In our use-case we can not really switch to the IN operator or simplify it because then the filters would be different, so for us it would be best if the limit would be even greater or not even existing. But as i am not technically involved in this project and can not see the downsides of no limit and a possible filter expression abuse. Because the performance of typesense seemes to be still pretty amazing even though the scoped filters containing many `||`

**Comment by kishorenc** [comment]
We will make this limit configurable by a server side flag.

**Comment by kishorenc** [comment]
This can be now increased via the `--filter-by-max-ops` server flag available in v27.
