### ISSUE TITLE
facet_query vs. hits empty

### ISSUE THREAD

**Issue by fabien** [typesense/typesense#110]
## Description

As soon as the `facet_query` search parameter is used, the query will return zero hits.

## Steps to reproduce

`http://localhost:8108/collections/companies/documents/search?q=*&facet_query=category:sports`

## Expected Behavior

This is not clear to me - is it intentional to stop returning any hits alongside the facets?

## Actual Behavior

Hits will be `[]`,  and `request_params: { per_page: 0, q: '*' }`

**Comment by kishorenc** [comment]
For facet queries, if a `per_page` parameter is not specified, it will default to `0`, thereby returning only facets and not hits. If you want hits as well, be sure to set `per_page=X` to fetch hits as well. 

The assumption is that when you’re searching for specific facets via facet query, you only care about the facets and not the actual hits at that point (e.g. when populating a facet filter sidebar component). Do you have a use case where that assumption breaks down?

**Comment by fabien** [comment]
Thanks. Didn’t realize that I could set per_page in this case. All good now!

**Comment by kishorenc** [comment]
@rlfrahm Thanks for the heads up: we have updated the docs.

**Comment by rlfrahm** [comment]
You're awesome @kishorenc!
