### ISSUE TITLE
How to execute command in Typesense Cloud

### ISSUE THREAD

**Issue by polarby** [typesense/typesense#1101]
I want to add an [analytics command](https://gist.github.com/jasonbosco/0c49916fc2e7a54f30d961aac111cf4a#create-an-analytics-rule-for-the-searches-to-be-aggregated) to my type sense cloud.

I have tried both my host ( `"host": "y7puih4wXXXX-1.a1.typesense.net",`)and the front-end URL(`https://cloud.typesense.org/clusters/y7puih4w2XXX1dp`) of my cluster, but both don't work:

`curl -k "http://localhost:8108/analytics/rules" ....`

Which URL is required here? There also seems to be no doc to access typesense cloud terminal. 

Issue #718 might also be interesting for this.

**Comment by jasonbosco** [comment]
@polarby On Typesense Cloud here's how the URLs would look like as a sample:

```bash
curl "https://y7puih4wXXXX-1.a1.typesense.net/analytics/rules" -X POST -H "Content-Type: application/json" \
      -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{
        "name": "top_queries",
        "type": "popular_queries",
        "params": {
            "source": {
                "collections": ["hnstories"]
            },
            "destination": {
                "collection": "top_queries"
            },
            "limit": 1000
        }
    }'
```

Your cluster however is running `0.23.1` which doesn't have this feature. Could you schedule an upgrade to `0.25.0.rc46` (Cluster Configuration > Modify) and then try again?
