### ISSUE TITLE
PSA: OpenSSL 1.1.1 is going to be EOL in less than two months

### ISSUE THREAD

**Issue by oddlama** [typesense/typesense#1104]
Hi, I'm currently trying to package typesense for NixOS, but I noticed that it still depends on OpenSSL 1.1.1 which is [going to reach EOL](https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/) in less than two months (on 11th September 2023). Some distributions (NixOS, Fedora, possibly others) are already phasing out support for OpenSSL 1.1.1 to avoid security issues after that date.

Since I couldn't find any information about moving to OpenSSL 3.x in this repository, I wanted to bring this to your attention. In case you update this I would be happy to bring typesense to NixOS ❤️ .

**Comment by kishorenc** [comment]
@oddlama :wave: 

In the upcoming 0.25 version, we are moving the build system to Bazel and that already uses OpenSSL 3.0:

https://github.com/typesense/typesense/blob/v0.25-join/WORKSPACE#L227

To build Typesense via Bazel, run this on the 0.25-join branch:

```
bazel build -- //:typesense-server 
```

Tests can be run via:

```
bazel test --test_output=all  -- //:typesense-test
```

**Comment by oddlama** [comment]
Thanks a lot, this makes this so much easier! I guess this can be closed then?
