### ISSUE TITLE
Filter values are silently truncated to 100 characters

### ISSUE THREAD

**Issue by 527bd5** [typesense/typesense#1109]
## Description

If you have facets with length >100, you cannot filter by them unless you truncate at query time. However, the facet response contains the untruncated strings. 

## Steps to reproduce

See this gist to reproduce: https://gist.github.com/527bd5/0c231ea749f033221eea428f439e0e9b

## Expected Behavior

It should return the document when you do a wildcard query and filter by its field value.

## Actual Behavior

It works for facet lengths <=100, but breaks when the facet lengths are >100 (i.e., returns 0 results). It does work when you truncate the filter value at query time. Note however that the facet response contains the full strings, even though you cannot filter by them.

I think that ideally it would work for arbitrarily long strings, but if that's difficult for some reason I think it would be acceptable to fail at index time instead.

## Metadata

I can reproduce this on `0.25.0.rc36-arm` on Mac and on `0.25.0.rc25` on a Linux server.

**Comment by kishorenc** [comment]
I think you mean filter values because the gist shows only a filtering operation. We've fixed this in recent 0.25 RC builds. Try 0.25.rc55.
