### ISSUE TITLE
Is there a way to sort by vector distance?

### ISSUE THREAD

**Issue by chimd715** [typesense/typesense#1111]
## Description
I am trying to use vector search, I can't find documentation about sorting by vector distance. Can you explain how to sort by vector distance?

## Steps to reproduce
https://typesense.org/docs/0.24.1/api/vector-search.html#what-is-an-embedding

## Metadata

**Typesense Version**: 0.24.1

**OS**: MacOS

**Comment by jasonbosco** [comment]
When you do a vector_query, the results are automatically sorted by vector distance automatically, with closest results appearing at the top.

**Comment by chimd715** [comment]
Ahh.. vector distance is sorted ascending order which is how it should be. I mistakenly thought it should be in descending order. Thanks for the answer
