### ISSUE TITLE
In what order synonyms and overrides are resolved

### ISSUE THREAD

**Issue by Clasyc** [typesense/typesense#1126]
In what order _synonyms_ and _overrides_ are resolved?

For example if I have an override - `query: phone, match: contains` and I have multi-way synonym for `android <-> phone`, and user is searching for `best android`, will my override going to be triggered?

**Comment by kishorenc** [comment]
Overrides are handled first since the rules can contain instructions to replace the query. Synonyms will then work on the modified query.

**Comment by Clasyc** [comment]
Yeah, that makes sense. I think this would be useful to mention in the documentation page.

Thanks for the response!

**Comment by jasonbosco** [comment]
Added this to the docs.
