### ISSUE TITLE
Schema property 'optional' not returned

### ISSUE THREAD

**Issue by fabien** [typesense/typesense#113]
## Description

It appears that the `optional` field property (within a collection schema) is not returned back to the client. This happens on `create` as well as `retrieve`.

## Steps to reproduce

1. create a schema with `optional` fields
2. retrieve the schema - the `optional` property is missing

## Expected Behavior

The `optional` property should be included.

## Actual Behavior

The `optional` property is missing.

**Comment by kishorenc** [comment]
Thank you for reporting this issue. Fixed in https://github.com/typesense/typesense/commit/e16a428ae080e62fe0d2c86e3d337caa45c8633b and the fix is available in this Docker image: `typesense/typesense:e16a428`.

**Comment by kishorenc** [comment]
Fixed in `v0.1.4.0` just released.
