### ISSUE TITLE
Typesense mixing up multiple nested field types

### ISSUE THREAD

**Issue by NuckChorris** [typesense/typesense#1139]
## Description

Typesense appears to be confusing the types of multiple nested fields in a schema.

## Steps to reproduce

Create a schema with multiple nested fields of differing type (string and int32 in this example):

```json
{
  "name": "anime:production@42069",
  "enable_nested_fields": true,
  "fields": [
    {
      "name": "titles",
      "type": "object"
    },
    {
      "name": "titles\\..*",
      "type": "string"
    },
    {
      "name": "start_date",
      "type": "object"
    },
    {
      "name": "start_date\\..*",
      "type": "int32",
      "facet": true,
      "optional": true
    }
  ]
}
```

Attempt to add a document:

```json
{
  "titles": {
    "en": "My Hero Academia"
  },
  "id": "420",
  "start_date": {
    "year": 2020,
    "month": 2,
    "day": 3
  }
}
```

## Expected Behavior

The document inserts successfully (HTTP 200 OK)

## Actual Behavior

Get an HTTP 400 Bad Request with the following error response:

```json
{
  "message": "Field `titles.en` must be an int32."
}
```

This can be resolved by removing the definition for `start_date\..*` (i.e., the `start_date` field is not the problem)

## Metadata

**Typesense Version**: 0.25.0rc54 (as well as 0.25.0rc34 and 0.25.0rc60-amd64)

**OS**: Docker for Mac

**Comment by kishorenc** [comment]
Fixed in 0.25.0.
