### ISSUE TITLE
Dropped schema fields still remain for documents existing in collection

### ISSUE THREAD

**Issue by sarge1989** [typesense/typesense#1141]
## Description

Schema successfully updated to drop fields, but field remains in the documents currently already in the Typesense collection. 

## Steps to reproduce

`let client = new Typesense.Client({
//typical setup
});

update_schema = {
  fields: [{ name: "type", drop: true }],
};

client
  .collections("messagesDev")
  .update(update_schema)
  .then(function () {
    console.log(`Done`);
  });`

## Expected Behavior

Collection schema should be updated and field should be removed from documents, at least that is implied in https://typesense.org/docs/0.23.1/api/collections.html#update-or-alter-a-collection

## Actual Behavior

After running this code, looking at the collection schema on the Typesense Cloud Portal, the type field has been successfully dropped and the collection schema is updated. However, the type field is still available in existing documents.

![image](https://github.com/typesense/typesense/assets/42286031/4fc55202-5082-41f1-ad34-4de52f7e1339)

## Metadata

**Typesense Version**:1.5.3

**OS**:Windows

**Comment by kishorenc** [comment]
Schema is meant only for the in-memory indices that Typesense uses for searching, filtering, sorting etc. We've always allowed document to store fields that're not present in the schema, and that's no different for fields that are dropped from the schema: they can continue to exist in the document on-disk. The drop operation only removed in-memory indices.

**Comment by sarge1989** [comment]
Thanks, that clears it up :)
