### ISSUE TITLE
Search widget within the landing page is not rendering

### ISSUE THREAD

**Issue by vishnukvmd** [typesense/typesense#1142]
## Description

Hey, not sure if this is the right place to report this, but it looks like Typesense's landing page is sending the API key in the query params, while the server is looking for it in the headers.

## Steps to reproduce

1. Open [typesense.org](https://typesense.org) / [xkcd-search.typesense.org](https://xkcd-search.typesense.org/)
2. The search widget will be broken
<img width="547" alt="Screenshot 2023-08-07 at 12 05 24 AM" src="https://github.com/typesense/typesense/assets/1161789/d450dc60-b456-46f2-a442-b7c8708416fe">

## Logs

```
Error: Request failed with HTTP code 401 | Server said: Forbidden - a valid `x-typesense-api-key` header must be sent.
```

**Comment by jasonbosco** [comment]
@vishnukvmd We were doing maintenance on the Typesense node that's running this demo, so you might have seen this error in passing. It should be fixed already.
