### ISSUE TITLE
Exact name is not matching in vector search

### ISSUE THREAD

**Issue by shikhar13012001** [typesense/typesense#1146]
## Description
We have a bunch of products/tools and we generated vector field like this
```python
    sentences = [f'{tool["toolName"]}. {tool["toolDescription"]}']
    sentence_embeddings = model.encode(sentences)
    tool['vec'] = sentence_embeddings[0].tolist()
```
we are using sentence transformer model ```all-mpnet-base-v2``` on the client side, when we search for exact name, the query 'DeepL', comes up 5th in line. I've tried with a bunch of names. An exact match search for a tool should show that tool first.
this is how we query.
We generate the query_embedding of search term using same model.
```js
let searchRequests = {
        searches: [
            {
                collection: 'out_index',
                q: '*',
                vector_query: `vec:([${query_embedding.join(', ')}],k:100)`,
                per_page: 9,
                page: 1, 
            },
        ],
    };
```
## Expected Behavior

The exact match should appear first.

## Actual Behavior

Non exact matches are positoned first in array of response

## Metadata

**Typesense Version**: Typesense v0.24.1

**Comment by shikhar13012001** [comment]
@jasonbosco Can you please look into this matter I really love typesense but this behaviour is bugging me for days

**Comment by shikhar13012001** [comment]
Hey @jasonbosco thank you the reply, it was great clarification. One more thing do you have a documentation page on the website on this new version?

**Comment by jasonbosco** [comment]
Not yet, we're very close to publishing it (may be in a week or so), unless we discover any other issues.

**Comment by shikhar13012001** [comment]
> Not yet, we're very close to publishing it (may be in a week or so), unless we discover any other issues.

Is the new version of typesense compatible with old version queries like the above one?

**Comment by jasonbosco** [comment]
> Is the new version of typesense compatible with old version queries like the above one?

Yes it is.
