### ISSUE TITLE
Upgrading typesense cluster is taking a lot of time for just 5000 documents

### ISSUE THREAD

**Issue by shikhar13012001** [typesense/typesense#1152]
## Upgrading typesense cluster is taking a lot of time for just 5000 documents,
![image](https://github.com/typesense/typesense/assets/75368010/656d5626-30a6-44c2-a29c-30aec6b5e9d3)
can someone take a look, I am getting OUT_OF_MEMORY errors

**Comment by jasonbosco** [comment]
The upgrade process required some manual intervention due to running out of memory. But the upgrade is complete now.
