### ISSUE TITLE
Support for ends with filter condition

### ISSUE THREAD

**Issue by eshwaruppala** [typesense/typesense#1157]
## Description

In data-intensive applications, businesses often need to filter data based on various conditions such as "contains," "doesn't contain," "starts with," and "ends with." Currently, Typesense lacks native support for the "ends with" functionality.

## Steps to Reproduce

N/A

## Expected Behavior

When filtering data using the "ends with" condition in Typesense, the expected behavior is that the query should return results that match the specified condition.

## Actual Behavior

Currently, Typesense does not provide native support for the "ends with" functionality, which makes it challenging to accurately filter data based on this condition.

## Metadata

- **Typesense Version**: 0.25.0rc
- **Operating System**: Typesense Cloud

**Comment by kishorenc** [comment]
We don't provide ends_with because suffix searching is not very easy to support. We do support an `infix` parameter which you can use here, but that uses bruteforce so only suitable for low volume use cases. There are no efficient (and mutable) datastructures for doing suffix search.
