### ISSUE TITLE
Add ability to change order of token drop

### ISSUE THREAD

**Issue by b0g3r** [typesense/typesense#1162]
## Description

It would be really helpful to have ability to change an order of dropped tokens, not from the end of query, but from the start. Right now for short queries last token can have big impact on relevancy of results if it contains important word. For example for queries like "getting started with technology" it's really painful to see results only with "getting started" and not with "technology"

**Comment by kishorenc** [comment]
Yes, I agree. This is on our near-term road map. We plan to support a `drop_tokens_mode` option that allows `start`, `end`, `start_alternate` and `end_alternate`. With the alternate modes, we will remove from either start/end and will alternate the drop direction until a result is found. This mode is useful for some cases.

**Comment by kishorenc** [comment]
Fixed in `0.26.0.rc20`. We've added a `drop_tokens_mode` parameter that can take 2 values:

- `right_to_left` (default)
- `left_to_right`
