### ISSUE TITLE
Issue faced in Update by query

### ISSUE THREAD

**Issue by joshishiv4** [typesense/typesense#1165]
## Description

While using the Update by a query from the v0.25.0 I am facing the issue of "Id key must be provided", while in the documentation example, there is no such dependency listed.

Versions:
- typesense: 0.25.0
- typesense-js: 1.7.1

## Steps to reproduce

![image](https://github.com/typesense/typesense/assets/115627496/811a10f6-08c6-4c92-bbaf-e2e1fee1a56c)

## Expected Behavior

It should update the records that are requested using the filter_by

## Actual Behavior

It throws an error of the `id` key must be provided

## Metadata

**Typesense Version**: 0.25.0

**OS**: Windows

**Comment by jasonbosco** [comment]
Could you post the exact code snippet you're using?

**Comment by joshishiv4** [comment]
Sure, here it is
```
client.collections(collectionName).documents().update({
    Created_At: new Date().getTime()/1000
}, {
    "filter_by": "deletedStatusKey:=0"
})
.then((res) => {
    console.log("RES: ", res);
})
.catch((error) => {
    console.error("ERROR in batch update: ", error);
})
```

**Comment by kishorenc** [comment]
@joshishiv4 

Thank you for reporting this. This is a client bug. The `curl` request should still work. We will update the clients shortly.

**Comment by joshishiv4** [comment]
Thank you for the update!

**Comment by jasonbosco** [comment]
Could you try this in `typesense-js` `v1.7.2-0`?

CC: @jdriscoll98

**Comment by jdriscoll98** [comment]
Will try it out in the morning and let you know!

**Comment by jdriscoll98** [comment]
@jasonbosco it worked for me! Thank you
