### ISSUE TITLE
Failed to run on Ubuntu 16.04

### ISSUE THREAD

**Issue by crodriguezdominguez** [typesense/typesense#1167]
## Description

After I install typesense 0.25 on Ubuntu 16.04, it fails to run.

## Steps to reproduce

Install typesense 0.25 on Ubuntu 16.04, then run typesense-server --version and an error will appear related to GLIBC not found.

## Expected Behavior

Typesense 0.25 fails to start.

## Actual Behavior

Typesense 0.25 should start in Ubuntu 16.04, since Typesense up to 0.24.1 starts normally.

## Metadata

**Typesense Version**: 0.25

**OS**: Ubuntu 16.04

**Comment by kishorenc** [comment]
Unfortunately we can only support recent versions of Ubuntu from now (Ubuntu 20+) because some of the newer features like GPU support require recent versions of glibc. We will try to support the LTS versions of Ubuntu.
