### ISSUE TITLE
Storing and Counting Empty Strings Multiple Times on Analytics & Query Suggestions

### ISSUE THREAD

**Issue by mahmudtopu3** [typesense/typesense#1169]
## Description

After adding analytical rules for aggregation when an empty string is passed as query it stores and starts counting. 
But when the query prams contains more white spaces it creates separates entries. 

## Steps to reproduce
Example: 
q1 = " "  //single white space
q2 = "  " //multiple white spaces
q3 = "php "  //php with a whitespace is stored (rstrip can be done)
q4 = "php" // php is stored
Two entries are created 
[
      {
            "document": {
                "count": 1,
                "id": "8125995372431972406",
                "q": ""
            },
            "highlight": {},
            "highlights": []
        },
        {
            "document": {
                "count": 1,
                "id": "12686171942349218503",
                "q": "  "
            },
            "highlight": {},
            "highlights": []
        }
]
## Expected Behavior

May be not storing 

## Actual Behavior

Storing separately 

## Metadata

**Typesense Version**: 0.25.0

**OS**: Ubuntu 22.04

**Comment by shashankshet** [comment]
Hi @kishorenc, can you provide some more information on this? which endpoint are you passing query params with whitespace included?

**Comment by kishorenc** [comment]
@shashankshet 

This is for the new query analytics feature in 0.25 where we aggregate popular queries. We have to handle stripping of whistespace before aggregating the queries.

**Comment by skilljobs** [comment]
Here is an example, 2,5 no entries are white spaces where 2nd one is single white space, 5th one is double whitespaces 
Although keeping the * can be good to detect initial page view where by default * is passed to show some contents on first load otherwise page will be empty. 
 
![image](https://github.com/typesense/typesense/assets/71579454/6f071901-d383-4af0-8585-b6d8c4585062)

**Comment by kishorenc** [comment]
Yes, we've now implemented a trim on the queries before aggregation. 

Fix available in `0.25.1.rc1`.
