### ISSUE TITLE
Feature request: sort_by string fields

### ISSUE THREAD

**Issue by fabien** [typesense/typesense#117]
## Description

It would be extremely handy to be able to sort results on `string` fields as well. Currently, `sort_by` only accepts numeric (`int32`, `int64`, `float`) fields. For the `default_sort_field` this is actually limited to just `int32`, and `float` (no  `int64`).

Ideally it would support ICU Collation settings. Some libraries have a concept of generating a sortKey (https://ilib-js.github.io/iLib/docs/api/jsdoc/symbols/Collator.html), which would allow a stable key representation of strings for sorting purposes.

**Comment by kishorenc** [comment]
Thank you for starting a discussion on this. The issue of sorting string fields has come up previously -- you might find that discussion useful: https://github.com/typesense/typesense/issues/90

As I mentioned on the other thread, the primary issue is that of performance and storage requirements. We've to store the actual strings in-memory for sorting. While that trade-off could be left to the discretion of the user, currently, Typesense's internal data structures are heavily optimized for numerical sorting. If we introduced string based sorting, it will slow down everything, which is undesirable as string based sorting seems to be not very popular. 

A middle ground would be to allow string based sorting only on the top-N hits returned but this can also be done client side. May I understand your use case for sorting by string?

**Comment by fabien** [comment]
Thanks for pointing me to the previous discussion. I was thinking of only allowing a substring of such string fields to be considered, ideally configurable as such. Say, the first 16 characters only. Then using this to generate a sortKey which incorporates complex ICU sorting into a plain sortable string value.

While this can also be done on the client, it might be less practical when used with `instantsearch.js` - I'm not sure if one can intervene there (perhaps the Typesense adapter can support this in a generic way?).

**Comment by kishorenc** [comment]
I think the idea of supporting sorting on fixed length string fields has merits. I will keep this issue open for tracking that.

**Comment by piolet** [comment]
i trying this options, add specific new field in my collection's schema, for example :
```
name: "name", type: "string",
name: "name_sort, type: "int64"
```

and for this new field, i take the first 9 characters of "_name_" and i convert into int like this :
```
a => 01
b => 02
...
z => 26
space => 00
```

when the name's length is lower than 9, i pad to the right with space (so "`a`" becomes "`a( + 8 spaces)`" and int value is "`100000000000000000`" and it can be compared to any other character string.

anyway, the limitation of this "tips", it's if your collection contains mainly too long text. It's only available, i think, for person list

**Comment by peteward** [comment]
Our example use-case:

We're using Typesense on both ecommerce and content sites. Due to the great and easy integration with instantSearch.js and the features they bring together, we're using it not only for Search but also for listing pages - product listing pages and content listing pages. In these cases it's common to want to sort by various fields - but never long text fields.

**Comment by jasonbosco** [comment]
@peteward If it's not long strings, does the workaround mentioned [here](https://github.com/typesense/typesense/issues/117#issuecomment-736666120) work?

**Comment by peteward** [comment]
Hi @jasonbosco, yeah we're trying it. It won't be as clean as naturally supporting sort. We'll need custom work on indexing and selecting a different field for sorting on, but hopefully it will do the job.

I'm just registering our use-case on this thread to show that sorting by string would be really useful.

**Comment by homerjam** [comment]
This is a blocker for me but I will subscribe for updates!

**Comment by laurenz-glueck** [comment]
I also would like to add my use-case here to add another example why sorting by string can be really helpful.

We want to use Typesense in our app for a user search with autocomplete. Therefor we index all users in a collection with their name in a field. When someone is now searching for a user, it would make sense to order the results by the name field to make it easier finding the desired user.

Currently we implemented a custom sorting of the results in our backend. But it would be nice to get the results already sorted by the name field form Typesense.

**Comment by kishorenc** [comment]
I've a preview Docker build for the string sorting feature: `typesense/typesense:0.23.0.rc10`

You should explicitly enable string sorting at a field level like this when creating the collection schema:

```
{"name": "title", "type": "string", "sort": true }
```

You can now include the `title` field in the `sort_by` clause.

Caveat: enabling string sorting will consume more memory because of the new index required for sorting the strings. Compared with the search index, which is an inverted index of `word -> document IDs`, a string sorting datastructure has to store the strings verbatim and so will consume more memory. Best to be used for small strings (anyway sorting large strings don't make much sense).

**Comment by tremendus** [comment]
@kishorenc In testing this feature this morning I noticed the following:
```
{
name: 'label',
type: 'string',
optional: true,
index: true,
facet: false
},
```
A request to the index with the default sort option specified in schema throws an error - `Malformed [Error]: Request failed with HTTP code 400 | Server said: Default sorting field `label` must be a single valued numerical field.`

**Comment by kishorenc** [comment]
@tremendus Forgot to get back to you on this: default sorting field does require a numerical field -- it cannot be a string. This is a limitation that we had to accept as a tradeoff for memory/performance reasons during implementation.

**Comment by JZubero** [comment]
@kishorenc Still seems not to be working. I am creating my collections via PHP client (latest version; v.4.8.0). This is a `var_dump()` of my schema definition right before it gets pushed to the API at https://github.com/typesense/typesense-php/blob/master/src/Collections.php#L63:

```
array(2) {
  ["name"]=>
  string(10) "foods_main"
  ["fields"]=>
  array(2) {
    [0]=>
    array(4) {
      ["name"]=>
      string(5) "title"
      ["type"]=>
      string(6) "string"
      ["facet"]=>
      bool(false)
      ["sort"]=>
      bool(true)
    }
    [1]=>
    array(4) {
      ["name"]=>
      string(8) "category"
      ["type"]=>
      string(6) "string"
      ["facet"]=>
      bool(true)
      ["sort"]=>
      bool(false)
    }
  }
}
```

The resulting collection is missing the sort flag for the field with name "title" though:

```json
{
  "name": "foods_main",
  "fields": [
    {
      "name": "title",
      "type": "string",
      "facet": false,
      "optional": false,
      "index": true
    },
    {
      "name": "category",
      "type": "string",
      "facet": true,
      "optional": false,
      "index": true
    }
  ],
  "default_sorting_field": ""
}
```

Am I doing anything wrong here?

**Comment by kishorenc** [comment]
May I know what version of Typesense you are using?

**Comment by JZubero** [comment]
Of course, it's 0.23.1

**Comment by JZubero** [comment]
Just checked and since the PHP client is just passing the schema config through to the actual API via Guzzle (https://github.com/typesense/typesense-php/blob/master/src/Collections.php#L63) without making any changes to it, it does not seem to be caused by the client. Actually I am experiencing the same behavior when I am running the command via shell inside by docker container (also running v0.23.1) :thinking: No `sort: true` for the field in the resulting collection schema.

**Comment by kishorenc** [comment]
Can you double check that you are indeed running this against 0.23.1? I just tried and it works fine for me and I know several customers who use string sorting this way. See: https://gist.github.com/kishorenc/ee63b32a7d8d6ea50e74b4c0cdfca1bf

**Comment by JZubero** [comment]
Thanks for hinting me in the right direction. After destroying and rebuilding the docker image (rebuilding container seemed not be to enough, maybe a caching issue) the schema gets generated correctly :heavy_check_mark:
