### ISSUE TITLE
How do you update default sorting field of a collection?

### ISSUE THREAD

**Issue by vamshiaruru32** [typesense/typesense#1175]
I have created default sorting field for a collection in typesense, but I need to change it now. Is there no API to update this default sorting field? if there is, where do I find it?

Any help is appreciated, thank you.

**Comment by jasonbosco** [comment]
The only way to update the default sorting field is to create a new collection with the updated value for this setting and then reindex your data in it.

**Comment by vamshiaruru32** [comment]
thanks for the response, are there any plans to support changing it without having to reindex the entire data?

**Comment by jasonbosco** [comment]
Yup, we'll add support for this as part of #691.

**Comment by vamshiaruru32** [comment]
So one way to update the default sorting field is to drop that column and then recreate with default sorting field set as false.
