### ISSUE TITLE
[Feature Request]: Filter scoring / Multiple optional filters

### ISSUE THREAD

**Issue by jhwheeler** [typesense/typesense#1177]
## Description

While migrating from Algolia, we're facing challenges with replicating our search prioritization based on user relationships. In Algolia, we utilized a filter to prioritize search results based on a user's `followers` and `following` relationships. Both `followers` and `following` are arrays of strings, representing user IDs. The filter we used in Algolia is:

```
(followers:${$currentUser.profile.id}<score=2> OR following:${$currentUser.profile.id}<score=1> OR followers:0<score=0>)
```

This filter prioritizes search results based on:

- If the current user is a follower of the user in the search results. If true, it assigns a score of 2.
- If the current user is being followed by the user in the search results. If true, it assigns a score of 1.
- If the user in the search results has no followers. If true, it assigns a score of 0.

However, Typesense does not seem to support assigning a value to the filtering expression, making this logic hard to replicate.

We tried the following approach as a workaround:

```
sort_by: _eval(followers:=[{$currentUser.profile.id}]):desc,_eval(following:=[{$currentUser.profile.id}]):desc,_text_match:desc,popularity:desc
```

But encountered a limitation:

- Only one sorting eval expression is allowed.
- Only 3 sort values are supported.

## Steps to reproduce

1. Attempt to create a filter in Typesense with multiple sorting eval expressions.
2. Add more than three sort values to the query.

## Expected Behavior

We expect Typesense to support:
- Assigning values to filtering expressions similar to Algolia's `<score=x>` syntax.
- Supporting multiple sorting eval expressions.
- Allowing more than three sort values.

This functionality would enable us to prioritize search results based on user relationships effectively.

## Actual Behavior

When trying to use multiple sorting eval expressions, we received an error stating, "Only one sorting eval expression is allowed." Additionally, we learned that only 3 sort values are supported.

## Additional Context

Consider a user searching for a common name, like "John." Without prioritization based on the searcher's relationships, the results would be non-specific and potentially overwhelming. By prioritizing users named "John" who have a direct relationship to the searcher (either as followers or following), we can provide more relevant and personalized search results, significantly enhancing the user experience on our platform.

## Metadata

**Typesense Version**: 0.25.0

**OS**: MacOS

**Comment by jasonbosco** [comment]
This is now available in `0.26.0.rc23`:

The syntax to use with `sort_by` is:

```
_eval([ (<exp_1>):<score_1>, (<exp_2>):<score_2> ]):<sort_order>
```

to provide custom scores to the records matching a filter expression. 

For example, if we have a shoe catalog and we want to rank all the `Nike` shoes above the `Adidas` shoes, we can send:

```
sort_by: _eval([ (brand:Nike):3, (brand:Adidas):2 ]):desc
```

There can be as many expressions as needed in the `_eval` and each of those expressions can be as complex as standard `filter_by` expressions.

**Comment by jhwheeler** [comment]
Brilliant! We will test this out ASAP; hopefully tomorrow, but certainly next week.

**Comment by sandstrom** [comment]
Would this be solved by this one? https://github.com/typesense/typesense/issues/376
