### ISSUE TITLE
Can typesense reducde vector dimensions automatically?

### ISSUE THREAD

**Issue by miguel11498** [typesense/typesense#1178]
I have a collection called clubs and for each club I have a field which is string[] with several tags describing what the club is about. I have created another field called "embedding" which is a vector representation of those tags by making my schema like that:   

 {
      "embed": {
        "from": [
          "tags"
        ],
        "model_config": {
          "api_key": "openAI-API-Key",
          "model_name": "openai/text-embedding-ada-002"
        }
      },
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "embedding",
      "num_dim": 1536,
      "optional": false,
      "sort": false,
      "type": "float[]"
    }

So typesense automatically creates a 1536 dimension vector from openAI. However, there is a big issue here because this is not scallable. lets say I have 1 million documents or 10 million, the RAM usage and the cost will sky rocket with these many dimensions. Does typesense has a way to reduce dimensions? or will it have that feature in the future? I tried to change the "num_dim" to 3 just to test but it just reverted back to 1536.

**Comment by jasonbosco** [comment]
The number of dimensions is determined by the embedding model used and Typesense does not control this aspect. So `openai/text-embedding-ada-002` is always `1536`. 

If you want to reduce the number of dimensions, you want to pick a built-in model like [`all-MiniLM-L12-v2`](https://typesense.org/docs/0.25.0/api/vector-search.html#using-built-in-models) which has 384 dimensions.
