### ISSUE TITLE
Build Failing Due to H2O URL 

### ISSUE THREAD

**Issue by ankane** [typesense/typesense#118]
## Description

Hi, when building from source, it's failing with:

```txt
Configuring h2o-2.3.0-beta2...
CMake Error: The source directory "/tmp/typesense/external-Darwin/h2o-2.3.0-beta2" does not appear to contain CMakeLists.txt.
```

It appears to be related to this change: https://github.com/typesense/typesense/commit/3cdb48f0604b614795db157fd4643fa614005694#diff-babe0c065fefe16905d2eec6fd3ee6feR11, which remove `v` from the URL. It works when the `v` is restored.

## Steps to reproduce

```sh
mkdir build
cd build
cmake ..
```

## Expected Behavior

Build succeeds

## Actual Behavior

See error above

## Metadata

**Typesense Version**: 0.13.0

**OS**: Mac 10.15

**Comment by kishorenc** [comment]
Thank you, fixed it in https://github.com/typesense/typesense/commit/2c94993ecb28a53808b386a49844ff7a5d4a65b4

**Comment by ankane** [comment]
That was fast, thanks @kishorenc!
