### ISSUE TITLE
Will typesense support query_weights with vector search?

### ISSUE THREAD

**Issue by miguel11498** [typesense/typesense#1180]
I have a collection called clubs and each document has a field called tags which is string[] and each tag describes what the club is about. Per example, a tennis club might have the tags ["tennis", "sports", "amateur"]. 

Right now I already have an embedding field representing the tags.

When I search "tennis" per example I would like to query by tags "tennis" and also by embedding "tennis" to get the closest match and then use the "query_weights" to give 0.2 weight to the tags and 0.8 to the embedding per example, so clubs with "tennis" tag would get a bit more weight, So i would not solely relly on the capacity for the vector search to capture the context

**Comment by jasonbosco** [comment]
We'll be exploring this as part of https://github.com/typesense/typesense/issues/1035

**Comment by kishorenc** [comment]
@miguel11498 

In v0.25 we support hybrid search which fuses the score of the text and vector search components. The weights are currently fixed though, but we plan on making them parameters in future: https://typesense.org/docs/0.25.0/api/vector-search.html#hybrid-search

**Comment by jasonbosco** [comment]
In 0.25.2, you can change the weightage of keyword search vs vector search: https://typesense.org/docs/0.25.2/api/vector-search.html#weightage-for-semantic-vs-keyword-matches
