### ISSUE TITLE
Hybrid Vector Search - Text Matching and Polygon Query Collision

### ISSUE THREAD

**Issue by hadminh** [typesense/typesense#1185]
## Description
Thank you for the awesome library. This Hybrid search is truly state-of-the-art, but I am not sure why I am encountering this issue. I have noticed that searching within a polygon with the query "abc" doesn't filter the results to within the polygon; it also shows queries that match "abc"

## Steps to reproduce
```js
    const vector_query = "vec:([0.7666807174682617,1.7292152643203735,-1.5116435289382935, ...])";
    const TYPE_ADAPT_CONFIG = {
      server: {
        apiKey: X_TYPESENSE_API_KEY,
        nodes: [
          {
            host: "localhost",
            port: 8108,
            protocol: "http",
          },
        ],
      },

      additionalSearchParameters: {
        query_by: "title",
        sort_by: "_text_match:desc,_vector_distance:asc",
        vector_query,
      },
    };
    const typesenseInstantsearchAdapter = new TypesenseInstantsearchAdapter(TYPE_ADAPT_CONFIG);

    const searchClient = typesenseInstantsearchAdapter.searchClient;

    const results = await searchClient.search([
      {
        indexName: "airbnb",
        params: {
          hitsPerPage: 5,
          insidePolygon: [
            [43.73704675452923, -79.38300646615075],
            [43.69904098010339, -79.37662108738296],
            [43.68832311435188, -79.34289320570862],
            [43.726111855665124, -79.29525638374871],
            [43.75444391542186, -79.30765204284718],
          ],
          query: "abc",
        },
      },
    ]);
```

## Expected Behavior
The response should be within the polygon

## Actual Behavior
Searching within polygon with query "abc" doesn't filter the result to within the polygon only.

## Metadata

**Typesense Version**:
[Version 0.25.0](https://github.com/typesense/typesense/releases/tag/v0.25.0)
[v2.7.1](https://github.com/typesense/typesense-instantsearch-adapter/releases/tag/v2.7.1)
**OS**:
ubuntu

**Comment by jasonbosco** [comment]
@hadminh Could you open the browser's network tab in the dev console, then do a search look for a request to `multi_search`, right click copy as curl and paste it here (excluding API keys).

**Comment by hadminh** [comment]
@jasonbosco I actually do this on the server therefore I wont be able to provide the curl command but here is the HTTP response header.
```http
POST /multi_search?x-typesense-api-key=vvvvvvvvvvvvvv HTTP/1.1
Accept: application/json, text/plain, */*
Content-Type: text/plain
User-Agent: axios/0.26.1
Content-Length: 1806
Host: localhost:8108
Connection: keep-alive

{"searches":[{"query_by":"title","sort_by":"_text_match:desc,_vector_distance:asc","vector_query":"vec:([0.7666807174682617,1.7292152643203735,-1.5116435289382935,...])","highlight_full_fields":"title","collection":"airbnb","q":"abc","filter_by":"_geoloc:(43.73704675452923,-79.38300646615075,43.69904098010339,-79.37662108738296,43.68832311435188,-79.34289320570862,43.726111855665124,-79.29525638374871,43.75444391542186,-79.30765204284718)","page":1,"per_page":250}]}

```

**Comment by jasonbosco** [comment]
I don't see any issues with the syntax... 

To help narrow down the issue further, could you put together a set of curl commands [like this](https://gist.github.com/jasonbosco/7c3432713216c378472f13e72246f46b) that creates a collection, adds two documents and then does a search that replicates the issue?

**Comment by hadminh** [comment]
Sorry, I have reproduced this and no longer see the problem... therefore I am going to close it!
