### ISSUE TITLE
Can we make most of the traffic go though a certan node?

### ISSUE THREAD

**Issue by elieobeid7** [typesense/typesense#1186]
We have 3 servers running typesense over https on port 443, we want to setup a cluster. n1.example.com, n2.example.com and n3.example.com. 3 different ubuntu servers in different countries. installed via the DEB packages. 

We're using typesense to help search our firebase firestore database, via the firestore typesense plugin. We have a Flutter application and we use the typesense SDK.

n1.example.com is our most powerful server and it's the closest server to our client in terms of geolocation.

1. Can we make all the traffic go through n1.example.com and only use the others in case of a problem?
2. In this what happens if n1.example.com? The developer told us that the Firebase extension and the client SDK don't support client side load balancing so our only option is to use server side load balancing. Is that correct? If so how to setup the cluster?

ideally for writes and updates I want a server side cluster because I don't want to send data from firestore to typesense 3 times, that would increase the firestore cost

I want the reads to happen from the client side, either that or to prioritize n1.example.com

**Comment by jasonbosco** [comment]
> Can we make all the traffic go through n1.example.com and only use the others in case of a problem?

Yes, you can configure the client library to do this, similar to [this](https://typesense.org/docs/guide/typesense-cloud/search-delivery-network.html#client-configuration).

You want to set nearestNode to `n1.example.com` so all requests are sent to that endpoint by default. And then set `nodes` to the other hostnames, so they're used as fallback. 

> The developer told us that the Firebase extension and the client SDK don't support client side load balancing so our only option is to use server side load balancing. Is that correct? 

The firebase Typesense extension does support multiple nodes (you can specify a comma-separated list), but it doesn't support the nearest node configuration. So you would have to fork the extension and run it in your own cloud functions and then you should be able to use the nearestNode configuration as described above.

**Comment by elieobeid7** [comment]
@jasonbosco and what about server side clustering?

https://typesense.org/docs/guide/high-availability.html#high-availability-in-typesense-cloud


1. should we use server side cluster configuration or should we rely on firebase extension to handle this? 
2. What about load balancing? Is not using a load balancer effficient? Or should use a load balancer in productuin?

**Comment by jasonbosco** [comment]
Server-side clustering is meant to only automatically replicate the data between all the nodes in the cluster, and ensure that even if one node goes down the other nodes can service traffic. It does not handle load balancing. 

So you would typically need to use the client-side load balancing mechanism we have in our client libraries, or you can also deploy a load balancer in front of all your Typesense nodes. 

> I was initially thinking to use server side cluster configuration for data replication and let the client handle the load balancing.

This would be the simplest given the requirements you mentioned.

**Comment by elieobeid7** [comment]
perfect thank you, that's all i needed to know, thanks a lot!
