### ISSUE TITLE
0.25 update fails

### ISSUE THREAD

**Issue by MktpStar** [typesense/typesense#1195]
## Description

Update on Centos7 and AlmaLinux 8.8 fail due to libc.so.6 incompatibility.
is there a way around this?

## Steps to reproduce

wget https://dl.typesense.org/releases/0.25.0/typesense-server-0.25.0-1.x86_64.rpm
sudo yum install ./typesense-server-0.25.0-1.x86_64.rpm

## Expected Behavior

successful update

## Actual Behavior

sudo yum install ./typesense-server-0.25.0-1.x86_64.rpm
Last metadata expiration check: 0:11:07 ago on Wed 30 Aug 2023 07:10:18 AM UTC.
Error:
 Problem: conflicting requests
  - nothing provides libc.so.6(GLIBC_2.30)(64bit) needed by typesense-server-0.25.0-1.x86_64
  - nothing provides libm.so.6(GLIBC_2.29)(64bit) needed by typesense-server-0.25.0-1.x86_64
  - nothing provides libpthread.so.0(GLIBC_2.30)(64bit) needed by typesense-server-0.25.0-1.x86_64

## Metadata

**Typesense Version**: 0.25

**OS**: AlmaLinux 8.8

**Comment by jasonbosco** [comment]
We had to drop support for older versions of Linux distros to be able to support some of the new features. For eg, on Ubuntu, you'd need at least Ubuntu 20.04 as of v0.25.0 of Typesense. 

Could you try upgrading to CentOS 8 or 9?

**Comment by MktpStar** [comment]
thanks, I wil try with AlmaLinux 9

**Comment by unclescooby** [comment]
> Could you try upgrading to CentOS 8 or 9?

Will require V9. It's not gonna work on Centos 8, Almalinux 8, etc. as they all seem to be using glibc 2.28. If it were possible to lower the requirement to that version that would surely allow a lot of servers to use latest typesense, which is a lot easier upgrade path than migrating a server to latest OS.

[source](https://pkgs.org/download/glibc)   (filter: types: official )

**Comment by kishorenc** [comment]
Unfortunately, we added some new features (e.g. vector embedding with GPU support), all of which required newer build distros, which meant newer glibc linked binaries.
