### ISSUE TITLE
split_join_tokens for other tokens than space

### ISSUE THREAD

**Issue by jdriscoll98** [typesense/typesense#1198]
## Description

Hi! 

I would like to know if there is a way to use other tokens (ex: "/", "," "-") the same way "split_join_tokens" uses space for typos. 

We have some products listed using "/"  that do not show up in search. For ex: 

"WP/KYB Enzo Ktm Husqvarna conversion aer 48 forks & shock GasGas cartridge Kit"

does not show up when searching for "KYB forks" but 

"WP KYB Enzo Ktm Husqvarna conversion aer 48 forks & shock GasGas cartridge Kit" does. 

## Expected Behavior

1. Should be able to provide a list of tokens used for "split_join_tokens" instead of just using space.

## Actual Behavior

2. can't do that

## Metadata

v0.25.0

**Comment by jasonbosco** [comment]
For this use-case you want to add those special characters to the `token_separators` setting in the collection schema when you create the collection. 

The parameter is documented under [this table](https://typesense.org/docs/0.25.0/api/collections.html#schema-parameters) and [this guide article](https://typesense.org/docs/guide/tips-for-searching-common-types-of-data.html) shows you several scenarios where it can help.

**Comment by jdriscoll98** [comment]
Thank you thats perfect! Might help if "split_join_tokens" had a link to the "token_seperators" instead of just saying space.

**Comment by jasonbosco** [comment]
Good idea! Will add that to the docs.
