### ISSUE TITLE
Results are not found when the matched word is in the middle of a sentence

### ISSUE THREAD

**Issue by RowPixel** [typesense/typesense#1199]
## Description

Hi, I have a question regarding this search. If I search for "First Google" or "Google Company" the document is returned but if I search for "First Google Company" then no documents are returned. Why is it not found if the match word is in the middle of the sentence? If I understand the documentation correctly, the ``drop_tokens_threshold`` parameter should solve the problem but unfortunately it doesn't work. Maybe I missed something?

## Steps to reproduce

1. Create collection
``` 
{
  "name": "companies",
  "fields": [
    {
      "name": "company_name",
      "type": "string"
    },
  ]
}
```
2. Add document
```
[
  {
    "company_name": "Google"
  }
]
```
3. Search query
```
{
  "q": "First Google company",
  "query_by": "company_name",
}
```

## Expected Behavior

I think it should return a document containing the "Google" company name.

## Actual Behavior

The document is not found.

## Metadata

**Typesense Version**: 0.25.0

**Comment by kishorenc** [comment]
The drop tokens only drops tokens from left to right and right to left. Neither of those will find a record whose only token appears in the middle of the query.

**Comment by RowPixel** [comment]
Hi, first of all thanks for your reply.

I don't get it, could you explain me more? I think it doesn't matter from which side starts drop tokens. When searching for "First Google Company", whether it drop First or Company then it should find document, isn't it?

On version 0.22.1 this case works fine and the document is found.

**Comment by kishorenc** [comment]
The drop tokens behavior was different in 0.22 and that might have worked. This is the current sequence of keywords that are tried for the query `First Google company`.

- `First Google company`
- `First Google`
- `First`
- `Google Company`
- `Company`

None of these would match `Google`.
