### ISSUE TITLE
Performance with LARGE data sets?

### ISSUE THREAD

**Issue by rluba** [typesense/typesense#120]
We’re experimenting with using Typesense on a very large dataset: around 3 million documents with full-text search.

After indexing around 8500 docs, Typesense consumed roughly 480MB of RAM, so we’re expecting around 170**GB** of RAM usage for the 3 million documents.

Has anyone tried using Typesense with this amount of data? How does search speed scale?

## Metadata

**Typsense Version**: 0.13.0 (using the official Docker image)

**OS**: Ubuntu 18.04 LTS.

**Comment by kishorenc** [comment]
Let's use https://github.com/typesense/typesense/issues/121 to discuss.

**Comment by rluba** [comment]
@kishorenc OK, but how is #121 related to the question of whether someone has used Typesense with that amount of data?

As you can see from the numbers, the individual documents are quite large – **much, much larger** than in the example given in the readme:
> To give you a rough idea: when 1 million Hacker News titles are indexed along with their points, Typesense consumes 165 MB of memory. The same size of that data on disk in JSON format is 88 MB. 

It took us just 8500 documents to almost triple the amount of memory need for your 1 million hacker news documents, so our 3 million documents would be equivalent to **more than one billion** hacker news documents, i.e., 3 orders of magnitude more than the example in the readme.

Has someone used that amount of data with Typesense?

**Comment by kishorenc** [comment]
People have told us that they have indexed 2-3M documents. However, they did not share specific RAM usage in those instances. The example that I can share with memory usage is an e-commerce bookstore who were able to index 1M book-related ecommerce records in 4 GB of RAM (the records had an on-disk storage of 2 GB). The typical actual memory usage will be 2-3x the on-disk storage (similar to the ballpark observed with the HN dataset).

> It took us just 8500 documents to almost triple the amount of memory need for your 1 million hacker news documents

How big are those 8500 documents on disk?
