### ISSUE TITLE
Partial insert using emplace action in import is not working in v0.25.0

### ISSUE THREAD

**Issue by tarunk04** [typesense/typesense#1200]
## Description
I recently upgraded the typsense version from 0.24.1 to 0.25.0. After upgrading partial insertion of the documents started failing.

``` python
 responses = client.collections[collection].documents.import_(docs, {'action': 'emplace', "batch_size": 250})
```
```json
{
  "code": 400,
  "document": {
    "id": "movie_3549",
    "title": "Ugly",
    "poster_urls": "<urls>",
    "content_type": "1",
    "tmdb_id": "443280",
    "release_year": 2016,
    "language": [1],
    "runtime": 20,
    "slug": "ugly"
  },
  "error": "Field `embedding` has been declared in the schema, but is not found in the document.",
  "success": false
}
```

I wanted to understand, is it not supported anymore or is it a bug?

## Steps to reproduce

For any schema, try to insert documents with partial fields.

## Expected Behavior

Partial insertion should work.

## Actual Behavior

Partial insertion is failing

## Metadata

**Typesense Version**: 0.25.0

**OS**: linux

**Comment by jasonbosco** [comment]
Could you share your collection's schema?

**Comment by tarunk04** [comment]
```python
schema = {
    "name": 'content',
    "fields": [
        {"name": 'id', "type": 'string', "index": True},
        {"name": 'tmdb_id', "type": 'string', "index": True},
        {"name": 'title', "type": 'string', "infix": True, "index": True},
        {"name": 'poster_urls', "type": 'string', "index": False, "optional": True},
        {"name": 'slug', "type": 'string', "index": True},
        {"name": 'content_type', "type": 'string', "facet": True},
        {"name": 'release_year', "type": 'int32', "facet": True},
        {"name": 'language', "type": 'int32[]', "facet": True, "index": True},
        {"name": 'cast_and_crew', "type": 'int32[]', "facet": True, "index": True},
        {"name": 'tags', "type": 'string[]', "facet": True, "index": True},
        {"name": 'providers', "type": 'int32[]', "facet": True, "index": True},
        {"name": 'genre', "type": 'int32[]', "facet": True, "index": True},
        {"name": 'monetization_types', "type": 'int32[]', "facet": True, "index": True},
        {"name": 'quality', "type": 'int32[]', "facet": True, "index": True},
        {'name': 'embedding', 'type': 'float[]', 'num_dim': 768},
        {"name": 'imdb_rating', "type": 'float', "index": True},
        {"name": 'runtime', "type": 'float', "index": True},
        {"name": 'age_certification', "type": 'int32', "index": True},
        {"name": 'popularity_score', "type": 'float'},
    ],
    "token_separators": ['-', ' ', ':', '&'],
}
```

**Comment by jasonbosco** [comment]
Could you try this on `0.25.1.rc6`?

**Comment by tarunk04** [comment]
facing same issue on `0.25.1.rc6`

**Comment by kishorenc** [comment]
@tarunk04 

I'm not able to reproduce this issue on 0.25.1rc6. Here's what I tried: https://gist.github.com/kishorenc/4d702dcee19c6a53b6f95e813e4c4bdf

Can you please provide a code snippet?

**Comment by tarunk04** [comment]
[kishorenc](https://github.com/kishorenc) what you shared in the gits, it working fine as you are creating the document first the doing the emplace, this is also working for me. My issue is when you try to emplace a document but that do not exists in the collection then if the document is a partial it is failing. 
But I was creating the partial document without any issue in version 0.24.1

**Comment by kishorenc** [comment]
@tarunk04 

The behavior in 0.24.1 is a bug. The goal of `emplace` is to either act as a partial `update` action **when the document already exists** or to act as a `create` action when document is not found. 

When it does act as a create action, it cannot ignore non-optional fields as that would fail validation. If you want to use emplace this way, then the fix is to mark those fields that could potentially be missing as optional in the schema.

**Comment by tarunk04** [comment]
Ok, got it. Thanks for the clarification. 

Just one thing I want to understand, is it possible to make a field `optional=true` and `index=true`, so that I can use the emplace for partial document creation?

**Comment by kishorenc** [comment]
Yes, just define a field as `optional: true`. `index: true` is not needed as it's the default for every field present in the schema. It's used when you want to use regular expressions to exclude some sub field name patterns from indexing.
