### ISSUE TITLE
Results are not found when a partial match word is at the start or middle of a query sentence

### ISSUE THREAD

**Issue by sowmikavi-b** [typesense/typesense#1205]
## Description

In typesense search, I get the related search result for the partial match only when it is at the end of the query sentence. If the partial match is at the start or middle of the sentence, I don't get any related results for the search.

## Steps to reproduce

Use one of the typesense live demos.
Link to the search page: https://recipe-search.typesense.org/
Search for the Thai soup recipe with a partial match word  "tha" and query sentence as the following:
1. tha
2. tha soup
3. soup tha
4. chicken tha soup
5. chicken soup tha

## Expected Behavior

When searching for records, it is expected to have a similar result for "tha soup" & "soup tha" and for "chicken tha soup" & "chicken soup tha".
Search for "tha" expected to show results for "thai". Both "tha soup" and "soup tha" search queries are to give results of "thai soup". Both "chicken tha soup" and "chicken soup tha" search queries are to have results of "chicken thai soup".

## Actual Behavior

The search for queries "tha", "soup tha", and "chicken soup tha" have returned the results of thai, thai soup, and chicken thai soup respectively. But for "tha soup" and "chicken tha soup", the result does not have thai soup or chicken thai soup, even if there is no more exact match for the search query.

Search results:
1. "tha" search give results for "thai" with partial match.
 ![Screen Shot 2023-09-04 at 7 38 09 PM](https://github.com/typesense/typesense/assets/144045075/3aff3b6c-3bed-456f-a83e-7e69af30b3f6)

2. "soup tha", where the partial match appears at the end of the search shows results for "thai soup".
![Screen Shot 2023-09-04 at 7 39 20 PM](https://github.com/typesense/typesense/assets/144045075/e5325a1a-db50-412f-ad97-624d3e8f8d91)

3. "tha soup", where the partial match word appears at the beginning of the search does not have any matching results for "thai soup". 
![Screen Shot 2023-09-04 at 7 38 21 PM](https://github.com/typesense/typesense/assets/144045075/6820564a-d49d-474f-bbe5-c3e3fc586533)

4. "chicken soup tha", where the partial match appears at the end of the search shows results for "thai chicken soup".
![Screen Shot 2023-09-04 at 7 39 05 PM](https://github.com/typesense/typesense/assets/144045075/7c2a338b-9045-420b-b047-f52090b395ff)

5. "chicken tha soup", where the partial match word appears at the middle of the search does not have many matching results for "thai chicken soup". 
![Screen Shot 2023-09-04 at 7 38 49 PM](https://github.com/typesense/typesense/assets/144045075/55815c29-ca63-44f6-909d-76b24c5fa591)

## Metadata

**Typesense Version**:

**OS**:

**Comment by jasonbosco** [comment]
@sowmikavi-b This happens because by default Typesense only does a prefix search on the last keyword (to power search-as-you-type experiences). 

We'll be adding the ability to prefix search on all search terms as part of https://github.com/typesense/typesense/issues/920. 

Closing this in favor of that feature request.
