### ISSUE TITLE
Embedding fields disappear when huge insert

### ISSUE THREAD

**Issue by tahola** [typesense/typesense#1206]
## Description

I have a collection of 200k documents, when I a upsert the document in, it its going well I can see the embedding data on each document but when its over the embedding data are not here anymore and I get no error. From what I see its seem to happen around 150k..

## Steps to reproduce

my collection :

```
'fields' => [
                ['name' => 'title', 'type' => 'string'],
                ['name' => 'tags', 'type' => 'string[]'],
                ['name' => 'date', 'type' => 'int32'],
                ['name' => 'views', 'type' => 'int32', 'facet' => true],
                ['name' => 'votes', 'type' => 'int32', 'facet' => true],
                [
                    "name" => "embedding",
                    "type" => "float[]",
                    "embed" => [
                      "from" => [
                        "title",
                        "tags"
                      ],
                      "model_config" => [
                        "model_name" => "ts/e5-small"
                      ]
                    ]
                  ]
            ],
```

## Metadata

**Typesense Version**:

0.25

**OS**:

Mac OS M1 with Docker installation

**Edit**:
It seem to happen when a document already exist: 

- when I run the an upsert on the first documents the first time : I have an embedding field on each document. 

 - when I do it again on the same documents (exact same function with upsert) : the documents lost the embedding field.
```
 $debug = $this->client->collections['collection_name']->documents->import($batch, ['action' => 'upsert']);
```

**Comment by jasonbosco** [comment]
@tahola We've fixed this issue in the latest RC build. Could you try replicating this on `0.25.1.rc6`?

**Comment by tahola** [comment]
@jasonbosco just tried and I confirm you that I cant replicate it, it work fine on `0.25.1.rc6`, my 200k documents have an embedding field, thank you very much.
