### ISSUE TITLE
Support collection aliases in Typesense Cloud Dashboard > Analytics rules

### ISSUE THREAD

**Issue by Nargonath** [typesense/typesense#1207]
## Description

We use aliases to abstract the name of our collections so we can easily swap underlying indexes when needed without having to redeploy the frontend. The problem is that you cannot create an analytics rule with an alias as the source collection through the Typesense Cloud Dashboard, only collections are listed in the UI. You can create one with alias as source through the API though.

## Steps to reproduce

1. Create a collection.
2. Create an alias for that collection.
3. Create a rule from Typesense Cloud Dashboard and notice only the collection is available not the alias.

## Expected Behavior

Both the collection and the alias should be available in the list for source collections, even probably for destination collections as well.

## Actual Behavior

Only the collections are available not the aliases in both sources and destinations field in Typesense Cloud Dashboard.

## Metadata

**Typesense Version**: 0.25.0

**OS**: Typesense Cloud

**Comment by jasonbosco** [comment]
We just pushed out an update so the UI shows aliases as well. Could you give it a shot now?

**Comment by Nargonath** [comment]
Yes it's all good @jasonbosco. I get aliases on the UI now. Thank you.
