### ISSUE TITLE
compare 2 fields in the same document 

### ISSUE THREAD

**Issue by hasanaktas** [typesense/typesense#1220]
## Description

I want to compare 2 fields in the same document. I'm trying to get psuedoPrice values greater than price, but I don't understand why it doesn't work.

```typescript
  const  fields= [
           {
                name: 'name',
                type: 'string',
            },
            {
                name: 'price',
                type: 'float',
                sort: true,
            },
            {
                name: 'pseudoPrice',
                type: 'float',
                sort: true,
            },
          
        ]

  const result = await client.collections<ProductSku>('productSku').documents().search({
                q: '*',
                query_by: '',
                filter_by: 'pseudoPrice:>price',
                per_page: 250,
            })
``` 

It gives the following error.

pseudoPrice not a float.

ways I've tried

`pseudoPrice:>price`

`[pseudoPrice]:>price`

`pseudoPrice:>[price]`

It works in the following ways.

`pseudoPrice:>105.5`

`price:>105.5`

Doesn't Typesense support direct field-to-field comparisons in queries?

**Comment by jsutaria** [comment]
I think the best way to do this would be to include the comparison in the document itself, and then filter_by that field.

**Comment by hasanaktas** [comment]
If it doesn't support it, I will do as you say. But I want to know whether it supports it or not. I tried a little with Elastic search and it supported. But since the document seemed very complicated, I wanted to try Typesense.

**Comment by jasonbosco** [comment]
Typesense does not support the ability to compare values of two fields, by specifying their field names. It only supports comparing a field with a static value.
