### ISSUE TITLE
Searching Through Multiple Collections

### ISSUE THREAD

**Issue by Enijar** [typesense/typesense#123]
## Description

Firstly, thanks for creating this awesome library!

I'm having trouble finding documentation on how to search through multiple collections; is this possible to do?

## Metadata

**Typsense Version**: 0.6.0

**OS**: Ubuntu 18.04

**Comment by Enijar** [comment]
In the mean-time (for others who may find this issue and need a temporary solution), I made a new collection named "all"; this combines the existing collection fields.

Here's an example of the collections config I have in NodeJS:

```js
const collections = [
  {
    name: "files",
    default_sorting_field: "identifier",
    fields: [
      {
        name: "identifier",
        type: "int32",
      },
      {
        name: "client_name",
        type: "string",
      },
      // ...
    ],
  },
  {
    name: "references",
    default_sorting_field: "identifier",
    fields: [
      {
        name: "identifier",
        type: "int32",
      },
      {
        name: "title",
        type: "string",
      },
      // ...
    ],
  },
];

const allCollection = {
  name: "all",
  default_sorting_field: "identifier",
  fields: [
    {
      name: "identifier",
      type: "int32",
    },
    {
      name: "type", // This will say if it's a file or reference
      type: "string",
    },
  ],
};

collections.forEach((collection) => {
  collection.fields.forEach((field) => {
    // The "all" collection already has it's identifier field defined (ignore)
    if (field.name === "identifier") {
      return;
    }
    // Prefix all fields with collection.name + field.name to avoid conflicts
    allCollection.fields.push({
      name: `${collection.name}_${field.name}`,
      type: field.type,
    });
  });
});

export default collections;
```

**Comment by jasonbosco** [comment]
@Enijar Are you using the [InstantSearch.js-Typesense adapter](https://github.com/typesense/typesense-instantsearch-adapter) by any chance?

If so, you can actually use InstantSearch.js to do multi-collection searches. Algolia calls this "Federated Search", where each key stroke is sent to multiple indices in parallel and then the results are displayed side-by-side in the UI. So the federated search happens all on the client-side. Here's an article from their docs on how to setup InstantSearch.js to do this: https://www.algolia.com/doc/guides/solutions/gallery/federated-search/#implementation-guide. 

If you have the Typesense adapter already configured, the method described above should just work out of the box.

**Comment by jasonbosco** [comment]
Just published v0.19.0 which has the ability to query multiple collections in a single HTTP request, using multi_search: https://typesense.org/docs/0.19.0/api/#multi-search

**Comment by JayabharathiP** [comment]
``This feature is great, but is there any possibility to move the query_by within the search Json, I like to search the same data in all fields available in products index, brands index 

**Example**
`{
          "searches": [
            {
              "collection": "products",
              "q": "shoe",
"query_by": "name, productDescription"
              "filter_by": "price:=[50..120]"
            },
            {
              "collection": "brands",
              "q": "Nike",
"query_by": "name, size, color"
            }
          ]
        }`

**Comment by kishorenc** [comment]
Yes that will work: any search parameter can be moved into the `searches` array.

**Comment by RBSUS** [comment]
Would anyone have the time and expertise to explain the advantages of maintaining multiple collections and using federated search, rather than creating a single 'all' collection. Perhaps the limitations of filter_by render multiple collections useful in some circumstances?

**Comment by jasonbosco** [comment]
The answer has a couple of variables, and so it depends on your use-case and how you'll be querying the data. 

Could you elaborate on what type of data you're searching through and the domain? Even better if you can share sample documents.

**Comment by RBSUS** [comment]
I'm still very much designing the schema. My instinct says I want to get as close to the final schema before deploying to production to avoid having to re-index all data. The use-case is a dropbox-like application with:

- Organisations and roles
- Multiple file types
- Searchable segments of text from within these files

The user can search all segments from all file types at once.
The main searchable field (str) is a simple string.
Each document also has different access permissions primarily based on the user's organisation.
Depending on the filetype, different metadata could be stored on the document such as 
'filetype': string
'location' (the location of the string within the file - this has a different data structure for each file type. For example, pdfs have page number, text files do not.)

So far we have a collection for each file type due to the subtly different schema, and thus we would need to use federated search.

**Comment by jasonbosco** [comment]
@RBSUS Given your specific use-case, I would recommend creating one collection per organization, and putting snippets from all types of files in that single collection. So your collection would look something like this:

```
segments { str, start, end, fileName, fileType, organisationId, accessibleToUserIds, accessibleToUserRoles, etc...  }
```

And then if you want to only show results from a particular file type, you can apply a filter on the `fileType` field.
