### ISSUE TITLE
Negation doesn't work in array int32[]

### ISSUE THREAD

**Issue by stefanolaru** [typesense/typesense#1231]
## Description

The negation in filter_by doesn't work in array of numbers (int32[]) but works fine in array of strings (string[])

## Steps to reproduce

Having a the following field in a collection:

```json
{
    "name": "website_agreed_ca_ids",
    "type": "int32[]",
    "optional": true
}
```

When I attempt a search with the following parameters `?q=*&filter_by=website_agreed_ca_ids:!=[10207]` I get the below

```json
{
    "message": "Error with filter field `website_agreed_ca_ids`: Numerical field has an invalid comparator."
}
```

After I converted the field to string[] it started to work and return the correct results.

```json
{
    "name": "website_agreed_ca_ids",
    "type": "string[]",
    "optional": true
}
```

**Comment by jasonbosco** [comment]
Could you try this in Typesense `0.25.1`?

**Comment by stefanolaru** [comment]
I confirm it works fine on `0.25.1`, thank you! 👏
