### ISSUE TITLE
Why is restore from disk so slow and takes double the RAM

### ISSUE THREAD

**Issue by Hades32** [typesense/typesense#1236]
## Description

One node in our cluster is restarting and needs to recover from a ~60.000 read/write lag. This recovery only happens at about 300 per 10s, while a single CPU is using ~20% and reads 5-10 MB/s and writes 10-70MB/s.

So obviously the hardware resources are not utilized fully.

At the same time the nodes grows to >4GB of RAM usage while the other nodes only need ~2GB.

## Steps to reproduce

idk

## Expected Behavior

It should be fast

## Actual Behavior

It's slow and fills up the RAM

## Metadata

**Typesense Version**: 0.25.0

**OS**: AWS Linux

**Comment by kishorenc** [comment]
Did you index data that exceeds RAM available and then perhaps delete it? Typesense runs a compaction of writes every hour. All writes within that hour are stored in a log and replayed. That might explain it worked when you deleted the data directory and restarted the node: it would have loaded from a compacted snapshot which would have skipped those writes that exceeded the RAM.

**Comment by Hades32** [comment]
Thanks @kishorenc , we delet and insert a lot, so that may very well be the case.
I'll reduce the snapshot time to every five minutes and hope that helps for the next time

**Comment by kishorenc** [comment]
Sounds good. Feel free to reopen this issue if that doesn't help.
