### ISSUE TITLE
Standard search timing out, but vector search working 

### ISSUE THREAD

**Issue by jsalts** [typesense/typesense#1240]
## Description

Here's my schema. I'm finding that standard search against the name field is timing out. Nearest neighbor searches against my embeddings fields work fine. Is there anything wrong with my query or schema here? Database is 5k items large and I don't believe it's a resource allocation issue. 

`
{
  "name": "games",
  "fields": [
    {
      "name": "name",
      "type": "string",
      "facet": false,
      "optional": true,
      "index": true,
      "sort": false,
      "infix": false,
      "locale": ""
    },
    {
      "name": "name_vec",
      "type": "float[]",
      "facet": false,
      "optional": false,
      "index": true,
      "sort": false,
      "infix": false,
      "locale": "",
      "num_dim": 1536
    },
    {
      "name": "genres",
      "type": "string",
      "facet": false,
      "optional": true,
      "index": true,
      "sort": false,
      "infix": false,
      "locale": ""
    },
    {
      "name": "tags",
      "type": "string",
      "facet": false,
      "optional": true,
      "index": true,
      "sort": false,
      "infix": false,
      "locale": ""
    },
    {
      "name": "categories",
      "type": "string",
      "facet": false,
      "optional": true,
      "index": true,
      "sort": false,
      "infix": false,
      "locale": ""
    },
    {
      "name": "price_category",
      "type": "string",
      "facet": false,
      "optional": true,
      "index": true,
      "sort": false,
      "infix": false,
      "locale": ""
    },
    {
      "name": "rating",
      "type": "string",
      "facet": false,
      "optional": true,
      "index": true,
      "sort": false,
      "infix": false,
      "locale": ""
    },
    {
      "name": "vec",
      "type": "float[]",
      "facet": false,
      "optional": false,
      "index": true,
      "sort": false,
      "infix": false,
      "locale": "",
      "num_dim": 1536
    }
  ],
  "default_sorting_field": "",
  "enable_nested_fields": false,
  "symbols_to_index": [],
  "token_separators": []
}
`

## Steps to reproduce

![image](https://github.com/typesense/typesense/assets/5424155/1b4dde15-6328-443e-8515-8cff7f124d67)
![image](https://github.com/typesense/typesense/assets/5424155/a72abb80-e100-419d-adde-9aa8703a9f4d)

**Comment by kishorenc** [comment]
That should not be an issue. Is it possible for you to share the dataset with us? You can email contact@typesense.org

**Comment by jsalts** [comment]
Done. Some other observations: 

* I don't see any entry with particularly long names that could explain a timeout. 
* The names contain a lot of Chinese characters. Maybe it's an encoding issue?
* Searching on "tags" works. Searching on "tag" (non-existent column) quickly returns an expected error. 
* Searching on "name" times out. Searching on "nam" (non-existent column) also times out. I'd expect it to return an error here quickly as it does for "tag."
* I've tried wiping out the collection a few times. 
* Running typesense 0.25.1 in docker for Windows backed by wsl (uname -a returns: Linux media-server 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux) 
* Going off memory search worked at one point. It was either before adding vectors or with a smaller dataset of games.

**Comment by jsalts** [comment]
Some additional troubleshooting: 
* I created a new collection called "games_metadata," then I dropped the vec/name_vec fields, then I reindexed. Search works on the name field. 
* I repeated the process, this time adding back the the vec field. Search works. 
* I repeated the process, this time adding back the name_vec field. Search is broken. 
* I repeated this process, this time adding back "vec_name" instead of name_vec (with the same data). Search works. 

I suspect there's something about having two fields with similar prefixes that is messing up search. For example, if I'm intending to search on "name," it's also executing code against "name_vec" or something along those lines. Once I renamed the field to vec_name, I was able to get search results against name instantly. 

I s

**Comment by kishorenc** [comment]
We recently fixed an issue related to shared prefixes. We are going to check if it's the same issue involved here.

**Comment by jsalts** [comment]
Issue also presents after changing my schema from (vec, vec_name, ...) to (vec, vec_name, vec_short_description). Searches against the vec field take quite a long time.

**Comment by kishorenc** [comment]
@jsalts This should be fixed in `0.25.2.rc4` -- can you please confirm?

**Comment by jsalts** [comment]
@kishorenc I reproduced the error in 0.25.1 then upgraded to 0.25.2.rc4 with the same database and it seemed to resolve the issue.

**Comment by kishorenc** [comment]
Thank you for confirming.
