### ISSUE TITLE
Filter out documents with empty array field

### ISSUE THREAD

**Issue by edervishaj** [typesense/typesense#1248]
## Description

In my schema I have a field `A` defined as `string[]`. I would like to retrieve the number of documents whose `A` is not empty but I have not found a way of achieving that. I have tried `/search?q=*&query_by=A` but it returns the count of all documents. Is this even possible?

## Metadata

**Typesense Version**: 0.19.0

**OS**: Ubuntu 20.04 LTS

**Comment by jasonbosco** [comment]
This is not possible to do in Typesense. 

So you would have to create a new boolean field called say `A_is_empty: true | false` and compute that at indexing time and then filter by that that field when searching.

**Comment by edervishaj** [comment]
Thanks!
