### ISSUE TITLE
typesense-server fails to start in docker

### ISSUE THREAD

**Issue by caussourd** [typesense/typesense#1253]
## Description

When running the docker image `typesense/typesense:0.25.1`, it fails to start with the following error in the logs:
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)
```

Passing parameters to `typesense-server` or not doesn't make any difference. The same error appears:
```
root@typesense-5c69bd955c-5xfvk:/opt# ./typesense-server 
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)

root@typesense-5c69bd955c-5xfvk:/opt# ./typesense-server --data-dir /data --api-key=xyz --enable-cors
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)
```

## Metadata

**Typesense Version**: tested with `0.25.1` and `0.26.0.rc20`

**Platform**: AWS EKS with Fargate

**Comment by kishorenc** [comment]
Does this work fine on your local machine?

**Comment by caussourd** [comment]
> Does this work fine on your local machine?

@kishorenc Yes, it works locally. There is no problem running `docker run -d typesense/typesense:0.25.1 --data-dir /tmp --api-key=xyz --enable-cors`

**Comment by kishorenc** [comment]
Do you know what underlying cpu architecture the host in running this on?

**Comment by caussourd** [comment]
@kishorenc The architecture is AMD64.

The problem has been solved though: deleting all the Kubernetes resources linked to the application and deleting the  associated Helm chart. Then it worked. I'm not sure what was causing the issue exactly. The error didn't help.
