### ISSUE TITLE
Exact match works without a closing symbol

### ISSUE THREAD

**Issue by PavelKoroteev** [typesense/typesense#1255]
## Description

Typesense enables exact match search without a closing symbol.

## Steps to reproduce

1. Make sure there are results with the typo corrected
https://books-search.typesense.org/?b%5Bquery%5D=sympatetik

2. Add the exact match symbol at the beginning
https://books-search.typesense.org/?b%5Bquery%5D=%22sympatetik

## Expected Behavior

Results were not changed, results were the same for both cases.

## Actual Behavior

In the second case, Typesense starts using an exact match search with a typo.
This behavior is different in the popular search engines, like so:

https://www.google.com/search?q=sympathetik
https://www.google.com/search?q=%22sympathetik
https://www.google.com/search?q=%22sympathetik%22

https://yandex.com/search/?text=sympathetik
https://yandex.com/search/?text=%22sympathetik
https://yandex.com/search/?text=%22sympathetik%22

https://search.yahoo.com/search?p=sympathetik
https://search.yahoo.com/search?p=%22sympathetik
https://search.yahoo.com/search?p=%22sympathetik%22

## Metadata

**Typesense Version**:
0.26.0.rc20

**OS**:
linux-amd64

**Comment by PavelKoroteev** [comment]
> I tried to reproduce and the results changed:
> 
> https://books-search.typesense.org/?b%5Bquery%5D=sympatetik 448 results found - Searched 28,961,877 books in 47ms
> 
> https://books-search.typesense.org/?b%5Bquery%5D=%22sympatetik No results found - Searched 28,961,877 books in 1ms.
> 
> This bug was fixed?

No.
The result is expected to be the same, shouldn't change, and should be the same for both search requests.
Because there is no closing tag yet.

**Comment by PavelKoroteev** [comment]
https://github.com/typesense/typesense/pull/1448

**Comment by jasonbosco** [comment]
Released in v26
