### ISSUE TITLE
Documentation for DocSearch in Nuxt

### ISSUE THREAD

**Issue by DarkPhoenix2704** [typesense/typesense#1258]
## Description

I am trying to implement docSearch in a Nuxt Website. 
## Expected Behavior

No Docs for them

## Actual Behavior
There should be docs

**Comment by jasonbosco** [comment]
Docsearch is framework agnostic. 

So you can follow the general instructions here for Next: https://typesense.org/docs/guide/docsearch.html#option-c-custom-docs-framework-with-docsearch-js-v3-modal-layout
