### ISSUE TITLE
glog and brpc defines the same flag which cause the runtime crash

### ISSUE THREAD

**Issue by grigortovmasian** [typesense/typesense#127]
## Description
I tried to build resent master branch on linux86_64 (ubuntu 18-04).
It actually forced me to install brpc and braft. 
After the build when I tried to run ./typesense-server it gives me the following error.

ERROR: flag 'v' was defined more than once (in files 'src/vlog_is_on.cc' and '/home/tiran/grig/incubator-brpc/src/butil/logging.cc').
the first file cames from glog library the second one is from brpc. 

I tired to trace the issue and found out that some months ago you have changed butil/logging.h to glog/logging.h.
In fact there is still some functionally which uses brpc and braft libs so I can't remove them. I can't remove glog too.

Have you ever faced this issue before? 
Do you have any suggestions how to fix it?

## Metadata

**Typsense Version**:

**OS**:

**Comment by kishorenc** [comment]
👋 BRPC must be configured to build with GLOG. If you are Ubuntu, you can just follow the Docker commands [here](https://github.com/typesense/typesense/blob/import-perf/docker/development.Dockerfile). It applies the necessary patches. 

The above link also points to the `import-perf` working branch, which is pretty near being released, so it would be useful to start with that, but the same Dockerfile exists on `master` as well.

**Comment by grigortovmasian** [comment]
Thank you for your feedback.
Seems like build brpc and braft with glog fixed that issue.
Regards,
Grigor
