### ISSUE TITLE
Logrotate configuration in Typesense

### ISSUE THREAD

**Issue by prateekIauro** [typesense/typesense#1272]
## Description

Typesense logs are getting saved in 1 single file which we are not able to manage. We could not find documentation for log rotate, to set it for daily/weekly rotation

## Steps to reproduce

Check the default log file generated when you first setup typesense on a system

## Expected Behavior

Preferably some configuration for log rotation where we can ensure that new log file is created for each day/week as per the configuration

## Actual Behavior

Single file is created for log forever, we need to manually rotate the logs(Please check attached screenshot)
![Screenshot 2023-10-03 at 15 49 15](https://github.com/typesense/typesense/assets/103488480/65f11f43-013f-4b7d-b52b-0a3ba5d85f84)

## Metadata

**Typesense Version**: 0.24.1

**OS**: linux

**Comment by kishorenc** [comment]
You've to setup a logrotate configuration just as you would do for any other service. Example config:

```
/var/log/typesense/*.log {
    daily
    size 25M
    rotate 7
    copytruncate
    missingok
    compress
    notifempty
}

```

**Comment by prateekIauro** [comment]
@kishorenc But this would require a reload of the typesense application to be applied. Is there a way we could do it without reload?

> You've to setup a logrotate configuration just as you would do for any other service. Example config:
> 
> ```
> /var/log/typesense/*.log {
>     daily
>     size 25M
>     rotate 7
>     copytruncate
>     missingok
>     compress
>     notifempty
> }
> ```

**Comment by kishorenc** [comment]
No this does not require reload. Since this question is not specific to Typesense (log rotation is common to all applications), I recommend reaching out to Stackoverflow for further clarifications.
