### ISSUE TITLE
Cannot update/drop field

### ISSUE THREAD

**Issue by MeikelLP** [typesense/typesense#1275]
## Description

I'm trying to update (an automatically created) field in my collection:

```json
    {
      "name": "shops.is_available",
      "type": "bool[]",
      "facet": false,
      "optional": true,
      "index": false,
      "sort": false,
      "infix": false,
      "locale": ""
    }
```
to be indexed. From what I understand and what the library allows me I have to drop this field first and then re-add it with the `index: true` value. Sadly the drop does not drop the field (maybe because it's added automatically?). So the second call (to re-add it) fails.

I tried to manually define every field in the schema first before adding documents. Sadly I didn't know how sub fields worked so I never knew these actually added fields automatically.

## Steps to reproduce

I'm using the [C# client](https://github.com/DAXGRID/typesense-dotnet) of typesense.

This is my code
```cs
        await _typesenseClient.UpdateCollection(ItemDocument.COLLECTION_NAME, new UpdateSchema(new []
        {
            new UpdateSchemaField("shops.is_available", FieldType.BoolArray, drop: true)
        }));
        await _typesenseClient.UpdateCollection(ItemDocument.COLLECTION_NAME, new UpdateSchema(new []
        {
            new UpdateSchemaField("shops.is_available", FieldType.BoolArray, facet: null, optional: false, index: true, sort: false)
        }));
```

This code does exactly what it says it does. The library isn't faulty.

## Expected Behavior

Dropping works so I can re-add the field with updated `index: true`

## Actual Behavior

Dropping fails. Field cannot be re-added
```json
 {"message": "Field `shops.is_available` is already part of the schema: To change this field, drop it first before adding it back to the schema."}
```

## Workaround

* Dropping the whole collection
* Recreateing the whole collection
* Reindexing all documents

Yes this is the worst but it's the only way to workaround this currently.
## Metadata

**Typesense Version**: `0.25.1`

**OS**: `typesense/typesense:0.25.1` in Docker (on Windows)

**Comment by kishorenc** [comment]
I just tried with a simple example here but it seems to work:

https://gist.github.com/kishorenc/bc4721be0877e24dd142f1094aa739f2

Can you provide a similar end to end example?

**Comment by MeikelLP** [comment]
@kishorenc I'm too unable to reproduce it in a minimal example. Is there any way to maybe enable debug logging when altering the schema, to see maybe what's going on?

**Comment by MeikelLP** [comment]
I was able to reproduce this issue after importing 250 of my live data. I will try to track down which document is causing this issue

**Comment by kishorenc** [comment]
If you can perhaps anonymize your data a bit and share it privately (please email to contact@typesense.org), I can check what's going wrong.

**Comment by MeikelLP** [comment]
I emailed the data to you.

**Comment by kishorenc** [comment]
@MeikelLP 

Thank you, this should be fixed in `0.25.2.rc4`. Can you please try it out?

**Comment by MeikelLP** [comment]
@kishorenc Thank you for the quick fix. The field is dropped but I'm unable to re-add it:

```cs
        // migration
        await _typesenseClient.UpdateCollection(ItemDocument.COLLECTION_NAME, new UpdateSchema(new []
        {
            new UpdateSchemaField("shops.is_available", FieldType.BoolArray, drop: true)
        }));
        await _typesenseClient.UpdateCollection(ItemDocument.COLLECTION_NAME, new UpdateSchema(new []
        {
            new UpdateSchemaField("shops.is_available", FieldType.BoolArray, facet: null, optional: false, index: true, sort: false, infix: false, locale: null, drop: null)
        }));
```

Response: 
```json
{"message": "Field `shops.is_available` not found."}
```

**Comment by kishorenc** [comment]
@MeikelLP I actually ran the shell script you shared with me on the 0.25.2.rc4 docker container and it worked. Can you please try again or share an updated shell script?

**Comment by MeikelLP** [comment]
Ah I think I spotted the issue:

In my actual code I set `optional: false` which caused this issue I assume because some data may not include this field yet
