### ISSUE TITLE
Unable to run docker image: terminate called recursively

### ISSUE THREAD

**Issue by honzasterba** [typesense/typesense#1278]
## Description

I am trying to start a typesense instance on Railway.app via the docker image. The image will not start.
Here is the logs I am getting:

I20231004 10:23:55.523072     1 typesense_server_utils.cpp:331] Starting Typesense 0.25.1
I20231004 10:23:55.523144     1 typesense_server_utils.cpp:334] Typesense is using jemalloc.
I20231004 10:23:55.524875     1 typesense_server_utils.cpp:384] Thread pool size: 256
I20231004 10:23:55.573406     1 store.h:64] Initializing DB by opening state dir: /data/db
I20231004 10:23:55.616441     1 store.h:64] Initializing DB by opening state dir: /data/meta
I20231004 10:23:55.642287     1 ratelimit_manager.cpp:546] Loaded 0 rate limit rules.
I20231004 10:23:55.642329     1 ratelimit_manager.cpp:547] Loaded 0 rate limit bans.
I20231004 10:23:55.643224     1 typesense_server_utils.cpp:495] Starting API service...
I20231004 10:23:55.643501     1 http_server.cpp:178] Typesense has started listening on port 8108
I20231004 10:23:55.643663   838 typesense_server_utils.cpp:232] Since no --nodes argument is provided, starting a single node Typesense cluster.
I20231004 10:23:55.644737   839 batched_indexer.cpp:124] Starting batch indexer with 256 threads.
terminate called after throwing an instance of 'std::system_error'
what():  Resource temporarily unavailable
I20231004 10:23:55.699187   838 server.cpp:1107] Server[braft::RaftStatImpl+braft::FileServiceImpl+braft::RaftServiceImpl+braft::CliServiceImpl] is serving on port=8107.
I20231004 10:23:55.699229   838 server.cpp:1110] Check out http://railway:8107 in web browser.
I20231004 10:23:55.725517   838 raft_server.cpp:68] Nodes configuration: 172.17.3.4:8107:8108
I20231004 10:23:55.725615   838 raft_server.cpp:111] Snapshot does not exist. We will remove db dir and init db fresh.
I20231004 10:23:55.726234   838 store.h:299] rm /data/db success
I20231004 10:23:55.726302   838 store.h:64] Initializing DB by opening state dir: /data/db
terminate called recursively
E20231004 10:24:06.257369   839 backward.hpp:4200] Stack trace (most recent call last) in thread 839:
E20231004 10:24:06.257457   839 backward.hpp:4200] #13   Object "", at 0xffffffffffffffff, in
E20231004 10:24:06.257472   839 backward.hpp:4200] #12   Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7fcfabf1dbb3, in __clone
E20231004 10:24:06.257478   839 backward.hpp:4200] #11   Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7fcfabe8cb42, in
E20231004 10:24:06.257484   839 backward.hpp:4200] #10   Object "/opt/typesense-server", at 0x55d7f76e75c3, in execute_native_thread_routine
E20231004 10:24:06.257489   839 backward.hpp:4200] #9  | Source "src/batched_indexer.cpp", line 125, in ThreadPool
E20231004 10:24:06.257498   839 backward.hpp:4200]     | Source "include/threadpool.h", line 60, in emplace_back<ThreadPool::ThreadPool(size_t)::<lambda()> >
E20231004 10:24:06.257505   839 backward.hpp:4200]     | Source "/usr/include/c++/10/bits/vector.tcc", line 115, in construct<std::thread, ThreadPool::ThreadPool(size_t)::<lambda()> >
E20231004 10:24:06.257511   839 backward.hpp:4200]     | Source "/usr/include/c++/10/bits/alloc_traits.h", line 512, in construct<std::thread, ThreadPool::ThreadPool(size_t)::<lambda()> >
E20231004 10:24:06.257516   839 backward.hpp:4200]     | Source "/usr/include/c++/10/ext/new_allocator.h", line 156, in thread<ThreadPool::ThreadPool(size_t)::<lambda()> >
E20231004 10:24:06.257522   839 backward.hpp:4200]       Source "/usr/include/c++/10/thread", line 149, in run [0x55d7f558584b]
E20231004 10:24:06.257529   839 backward.hpp:4200] #8    Object "/opt/typesense-server", at 0x55d7f76e78c0, in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())
E20231004 10:24:06.257536   839 backward.hpp:4200] #7    Object "/opt/typesense-server", at 0x55d7f54e180a, in std::__throw_system_error(int)
E20231004 10:24:06.257541   839 backward.hpp:4200] #6    Object "/opt/typesense-server", at 0x55d7f7665308, in __cxa_throw
E20231004 10:24:06.257546   839 backward.hpp:4200] #5    Object "/opt/typesense-server", at 0x55d7f76651a6, in std::terminate()
E20231004 10:24:06.257552   839 backward.hpp:4200] #4    Object "/opt/typesense-server", at 0x55d7f766513b, in __cxxabiv1::__terminate(void (*)())
E20231004 10:24:06.257558   839 backward.hpp:4200] #3    Object "/opt/typesense-server", at 0x55d7f54df9de, in __gnu_cxx::__verbose_terminate_handler() [clone .cold]
E20231004 10:24:06.257570   839 backward.hpp:4200] #2    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7fcfabe207f2, in abort
E20231004 10:24:06.257578   839 backward.hpp:4200] #1    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7fcfabe3a475, in raise
E20231004 10:24:06.257583   839 backward.hpp:4200] #0    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7fcfabe8ea7c, in pthread_kill
Aborted (Signal sent by tkill() 1 0)
E20231004 10:24:14.737015   839 typesense_server.cpp:121] Typesense 0.25.1 is terminating abruptly.

## Expected Behavior

Typesense node will start normally.

## Actual Behavior

The node keeps crashing and being restarted by Railway

## Metadata

I have created a template for creating a typesense node on railway: https://railway.app/template/pCQ-HZ?referralCode=xN06sk

**Typesense Version**: Docker typesense/typesense:0.25.1

**OS**: Docker

**Comment by kishorenc** [comment]
Can you ensure that ` /data/db` is writable? As a test you can try using `/tmp/data` to see if that works.

**Comment by honzasterba** [comment]
I did try setting data dir to /var did not help. I have also tried with /tmp and got same result.
Setting data-dir to /tmp/data failed because that directory does not exist.

**Comment by honzasterba** [comment]
I have looked at the docker files and it seems to me that it is just the executable wrapped in a docker image, nothing fancy with UIDs being done anywhere. Can you confirm that is true please?

**Comment by honzasterba** [comment]
I am really working hard to get this figured out.
One hint from the Railway team: does typesense have any known issues with ext4 mounted storage?
I have created a repo for testing here: https://github.com/xgroot-dev/typesense-runner
I am basically able to touch into the configured data dir no problem, but then typesense fails writing into it. Are there any undocumented flags/env vars I can set to see exactly what went wrong?

**Comment by honzasterba** [comment]
Final update, the path is writable, something else is going wrong here, could it binding to listen ports?
drwxr-xr-x 2 root root 4096 Oct  6 19:36 .
drwxr-xr-x 1 root root 4096 Oct  6 19:35 ..
-rw-r--r-- 1 root root    0 Oct  6 19:32 .writable-check
Touching
Done touching
total 8
drwxr-xr-x 2 root root 4096 Oct  6 19:36 .
drwxr-xr-x 1 root root 4096 Oct  6 19:35 ..
-rw-r--r-- 1 root root    0 Oct  6 19:36 .writable-check
I20231006 19:36:00.567088    14 typesense_server_utils.cpp:331] Starting Typesense 0.25.1
I20231006 19:36:00.567217    14 typesense_server_utils.cpp:334] Typesense is using jemalloc.
I20231006 19:36:00.569002    14 typesense_server_utils.cpp:384] Thread pool size: 256
I20231006 19:36:00.624982    14 store.h:64] Initializing DB by opening state dir: /data/db
I20231006 19:36:00.653776    14 store.h:64] Initializing DB by opening state dir: /data/meta
I20231006 19:36:00.681543    14 ratelimit_manager.cpp:546] Loaded 0 rate limit rules.
I20231006 19:36:00.681603    14 ratelimit_manager.cpp:547] Loaded 0 rate limit bans.
I20231006 19:36:00.681849    14 typesense_server_utils.cpp:495] Starting API service...
I20231006 19:36:00.682184    14 http_server.cpp:178] Typesense has started listening on port 8108
I20231006 19:36:00.682293   846 typesense_server_utils.cpp:232] Since no --nodes argument is provided, starting a single node Typesense cluster.
I20231006 19:36:00.682382   847 batched_indexer.cpp:124] Starting batch indexer with 256 threads.
terminate called after throwing an instance of 'std::system_error'
what():  Resource temporarily unavailable
W20231006 19:36:00.718555   846 task_control.cpp:202] Fail to create _workers[24], Resource temporarily unavailable
I20231006 19:36:00.724931   846 server.cpp:1107] Server[braft::RaftStatImpl+braft::FileServiceImpl+braft::RaftServiceImpl+braft::CliServiceImpl] is serving on port=8107.
I20231006 19:36:00.725062   846 server.cpp:1110] Check out http://railway:8107 in web browser.

**Comment by honzasterba** [comment]
this is the contents of the data dir when typesense crashes:

/data

/data/meta

/data/meta/LOG.old.1696621504555909

/data/meta/OPTIONS-000007

/data/meta/IDENTITY

/data/meta/OPTIONS-000011

/data/meta/LOG

/data/meta/LOCK

/data/meta/000008.log

/data/meta/000004.log

/data/meta/CURRENT

/data/meta/MANIFEST-000009

/data/meta/archive

/data/.writable-check

/data/db

/data/db/OPTIONS-000007

/data/db/IDENTITY

/data/db/MANIFEST-000005

/data/db/LOG

/data/db/LOCK

/data/db/000004.log

/data/db/CURRENT

/data/db/archive

/data/models

**Comment by honzasterba** [comment]
figured it out, Railway did not like the number of threads typesense was trying to start

**Comment by kishorenc** [comment]
@honzasterba 

Thank you for getting to the bottom of this issue and posting the resolution as well. Typesense uses 8 * number of cores available as a thread pool size. I'm surprised that Railway does not support creating these threads. What configuration value did you use in the end?

**Comment by honzasterba** [comment]
It was quite an investigation. 
Since I am just doing a testing deployment I set the number of threads to 32, which is equal to the number of cores available.
Apparently railway containers do not allow you to create more than 200 native threads.

**Comment by kishorenc** [comment]
Got it. Thanks for the details!
