### ISSUE TITLE
Error / timeout ECONNABORTED

### ISSUE THREAD

**Issue by fabien** [typesense/typesense#128]
## Description

```text
Request #1599685601652: Request to Node 0 failed due to "ECONNABORTED timeout of 2000ms exceeded"
Request #1599685601652: Sleeping for 0.1s and then retrying request...
```

Just wanted to check if this originates from Typesense, as I am seeing this repeatedly on the console while running some integration tests. The results are as expected though, and everything continues successfully.

## Steps to reproduce

This happens intermittently during indexing of items - it cannot be reproduced specifically in any way.

**Comment by jasonbosco** [comment]
This does originate from Typesense - specifically [here](https://github.com/typesense/typesense-js/blob/37838934bf74b901540f2329604fee20c4c4ddac/src/Typesense/ApiCall.js#L94) in the JS library. Looks like the request is taking more than the configured timeout of 2s to complete and so is being retried by the client. If you only see the message once, it's likely the 2nd retry succeeded.

**Comment by fabien** [comment]
Hi Jason, thanks for the pointer. 

When this happens I’m seeing it repeatedly, up to 10 times and more. I guess it’s because multiple items are being indexed individually (update: delete + re-insert), instead of a single batch call.

**Comment by jasonbosco** [comment]
You’re right. I meant to say, if you see the message only N-1 times per api call, where N is the number of retries configured in the client library, then the message can be safely ignored.

**Comment by raut-santosh** [comment]
Hey guys, 
i am also getting the same error but it is retrying multiple times and then it suddenly stops.
i have try changing connectionTimeoutSeconds in my client which is calling the api from nodejs.
