### ISSUE TITLE
Collections with slash in name cannot be deleted

### ISSUE THREAD

**Issue by honzasterba** [typesense/typesense#1287]
## Description

When you create a collection with / in the name, its impossible to work with such collection and eventually delete it

## Steps to reproduce

create collection with / in the name
try deleting it

## Expected Behavior

a) it should not be possible to create collections with / in name
b) such collections should be possible to create and later use

## Actual Behavior

collections with / in the name can be created but no further operations are possible and return 404

## Metadata

0.25

**OS**:

any

**Comment by jasonbosco** [comment]
Could you try url-encoding the collection name in the URL?

**Comment by honzasterba** [comment]
that worked, I think I will file an issue with the Ruby client library, since it should be handled there
