### ISSUE TITLE
Allow opting out of analytics/query aggregation for individual searches

### ISSUE THREAD

**Issue by aradalvand** [typesense/typesense#1290]
See [related discussion on Slack](https://typesense-community.slack.com/archives/C01P749MET0/p1696869180547259)

Currently there's no way to tell Typesense (e.g. via a query string parameter when sending a request to the search endpoint) that it should ignore that particular search in terms of analytics and not store its query in the queries collection. Opting out of this behavior for certain types of searches is desirable.

**Comment by alainrussell** [comment]
+1 we'd like this as well to suppress searches coming from the internal network of retailers we work with. Currently these internal searches skew the usefulness of the stats.

**Comment by kishorenc** [comment]
Available in `27.0.rc24`  -- you can send `enable_analytics=false` query-time parameter to prevent the search from being considered for analytics aggregation.
