### ISSUE TITLE
Question/feature request: finding similar documents

### ISSUE THREAD

**Issue by fabien** [typesense/typesense#130]
It would be interesting to find similar documents to a given documents. How would one go about handling this?

**Comment by kishorenc** [comment]
👋 There are certainly sub-optimal ways to do this by querying for individual tokens of a given document field (like title) and try to find similarly titled documents. However, from experience, this does not work well, so Typesense does not offer a way to do that. It is better done outside by a separate specialised system. 

Having said that, I think this is a useful feature to consider, so will see what we can do to integrate such a system inside Typesense.

**Comment by fabien** [comment]
Hi @kishorenc, thanks for your input. Can you elaborate on 'a separate specialised system'? You mean some custom piece of code that knows about the data structure and constructs a suitable query from it?

**Comment by kishorenc** [comment]
Showing similar documents to a given document is essentially a recommendation problem rather than a search problem. For e.g. if you have only a single TV from brand X in your catalog and someone is looking at that, you might want to recommend a TV from another brand rather than recommending TV accessories for brand X. One might also want to consider other attributes like page views of the products to determine order based on popularity. 

All of this needs additional/different data structures and algorithms. The good news is that I will be taking a serious look at this feature and you can expect atleast a prototype in October. Happy to involve you in that for feedback if you are interested. 

1. May I know what language your documents are in?
2. How big is your dataset?

**Comment by fabien** [comment]
Thanks @kishorenc, that makes sense. And yes, I would be happy to provide any feedback while this is being developed!

1. my dataset is bi-lingual, English and Dutch
2. per index of products, I am looking at around 5000 items, I not sure yet how large an index of all variants would be

**Comment by fabien** [comment]
They will be in separate collections.

**Comment by kishorenc** [comment]
I have done some prototyping on this front that looks promising, and with the 0.16 release done, I plan to focus on this next.

**Comment by gustavopch** [comment]
@kishorenc Any news since your prototype?

**Comment by rayjasson98** [comment]
Hi, is this feature under active development? Would like to see this feature getting incorporated in Typesense.

**Comment by jasonbosco** [comment]
We've added support for vector search in the latest RC build of Typesense. Here's how to use it: https://github.com/typesense/typesense/issues/207#issuecomment-1284501703

It does require you to use an ML model (outside of Typesense, for eg: word2vec) to generate embeddings for each of your records, and store them in Typesense. But once you have it, you can then do nearest neighbor search to implement similarity search.

**Comment by jasonbosco** [comment]
Here's an example that implements Similarity Search in an e-commerce product dataset: https://ecommerce-store.typesense.org/

If you click on "Find Similar" under each product, you'll see notes and source code links that show you how to implement this practically with Typesense.

**Comment by akamil-etsy** [comment]
this is awesome feature

**Comment by transitive-bullshit** [comment]
@jasonbosco followed up from twitter; why are the latest releases not viewable on GitHub?

**Comment by jasonbosco** [comment]
@transitive-bullshit we only publish GA releases on GitHub. 0.24 which has the vector search feature is in final RC stages (planning a GA release in 1-2 weeks), so it’s only available on Docker / DEB / RPM for now.

If you’re using Docker, the tag is typesense/typesense:0.24.0.rcn58.

If you’re not using Docker, let me know if you need native binaries for Linux / macOS and we can publish those.

**Comment by avi-agg** [comment]
In the current workflow of using embeddings for document searches, there is a requirement to first retrieve vector data and subsequently transmit it back to Typesense Cloud. This process results in considerable search latency and elevated bandwidth usage, a challenge that becomes more pronounced when handling hundreds of documents concurrently.

To address this, I propose the development of a specialized function. This function would take parameters specifying the document ID and search fields, with its primary purpose being the efficient identification and retrieval of similar documents. By directly returning the nearest node of similar documents, this function aims to significantly streamline the search process, thus reducing both latency and bandwidth consumption at both ends.

**Comment by jasonbosco** [comment]
@avi-agg This is already possible in 0.25 and above versions: https://typesense.org/docs/0.25.2/api/vector-search.html#querying-for-similar-documents

**Comment by avi-agg** [comment]
@jasonbosco Thank you once again for your invaluable support.
