### ISSUE TITLE
Feature request: Ability to modify weights of rank_fusion_score

### ISSUE THREAD

**Issue by honzasterba** [typesense/typesense#1300]
## Description

It would be nice to be able to use hybrid search and customise the weights of keyword vs vector/semantic search when hybrid score is being calculated.

## Metadata

**Typesense Version**: 0.25.1

**OS**: any

**Comment by ozanarmagan** [comment]
@honzasterba Please check #1267 and #1292

**Comment by honzasterba** [comment]
awesome!
