### ISSUE TITLE
When an auto-embedding field is set to index:false, the vector/sematic search request stuck

### ISSUE THREAD

**Issue by kzhang-dsg** [typesense/typesense#1306]
## Description

When an auto-embedding field is set to index:false, the vector/sematic search request stuck

## Steps to reproduce

Step 1. Create a auto embed field with `index` set to `false`:

```
{
  "name": "embedding",
  "type": "float[]",
  "index": false,
  "embed": {
    "from": [
      "brand",
      "categories"
    ],
    "model_config": {
      "model_name": "ts/all-MiniLM-L12-v2"
    }
  }
}
```
Setp 2. Index several documents. Check the "embedding" field is properly embedded.

Step 3. Perform a vector search or sematic search aginest the "embedding" field:
```
curl 'http://localhost:8108/multi_search' \
    -X POST \
    -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
    -d '{
          "searches": [
            {
              "collection": "products",
              "q": "chair",
              "query_by": "embedding"
            }
          ]
        }'  
```
## Expected Behavior

Search returns an error message saying the field is not searchable.

## Actual Behavior

The search request stuck forever without any error message.

## Metadata

**Typesense Version**: 0.25.1

**OS**: Linux

**Comment by ozanarmagan** [comment]
@kzhang-dsg 

Fixed. It will be included in the next minor release.
