### ISSUE TITLE
Date type support

### ISSUE THREAD

**Issue by an7e** [typesense/typesense#1313]
## Description

I am creating an application that outputs a list of items, with sorting and searching.
The problem I encountered is that when creating a schema for my document collection, I realized that Typesense does not support **Date** type like Elasticsearch. 

**Question:** Is there any support planned for **Date** type? If yes, what is approximate release date?

**Typesense Version**:  0.25.1

**OS**: Linux Ubuntu

**Comment by jasonbosco** [comment]
We don't have immediate plans to add date support, though it's on our radar. 

Until then, you would have to convert the date/timestamps into Unix timestamps (epoch time) and store it as `int64` type at indexing time. You'll then be able to use the numeric filtering operators to do date based filtering.

**Comment by an7e** [comment]
@jasonbosco thank you for your reply
