### ISSUE TITLE
How to make the id field searchable?

### ISSUE THREAD

**Issue by 0x80** [typesense/typesense#1319]
It seems that the id field is not searchable by default in the Typesense cloud UI, so I'm assuming the API will also not return results.

When I define a schema like below, and use it to create a collection via the API, the id field is not listed in the collection configuration page. 

This raises two questions for me:

* Do we even need to define the id field, if it is required for every document? What happens if I declare the id field to be type "bool"? It seems redundant.
* How can I find documents based on id, without creating another field with a different name and duplicating the id value there?

```ts
schema: {
      name: "users",
      fields: [
        {
          name: "id",
          type: "string",
        },
        {
          name: "email",
          type: "string",
        },
        {
          name: "name",
          type: "string",
          optional: true,
        },
        {
          name: "display_name",
          type: "string",
          optional: true,
        },
      ],
    },
```

Algolia as you know uses objectID for the document id, this name is less likely to clash with any document properties that the user would like to store, since "id" is still available to use.

In that regard, maybe you could use something like "document_id" or "object_id" and make it implicitly defined on every schema without bothering the user with it?

**Comment by jasonbosco** [comment]
> It seems that the id field is not searchable by default in the Typesense cloud UI, so I'm assuming the API will also not return results.

That's correct - not just in the Cloud UI, but also via the API. `id` is a special field in Typesense, that is used internally to dedupe/identify documents across writes, so you can only filter on it, but not do full text search on it.

If you want to do full-text search on the contents of the `id` field, you want to duplicate the same data into a new string field, and then specify that new field in the `q` parameter.

> Do we even need to define the id field

No, in fact if the id field is specified in the schema, Typesense ignores it. 

> if it is required for every document? 

Technically it's not required in every document, in the sense that if it's not set in a document, Typesense will auto-generate it internally and return the ID when that document is accessed. 

> What happens if I declare the id field to be type "bool"? It seems redundant.

`id` can only be a string field and cannot be changed.

> How can I find documents based on id, without creating another field with a different name and duplicating the id value there?

You can use `filter_by: id:=abcd` to fetch a document with ID `abcd`

**Comment by 0x80** [comment]
Thanks, it's good to know that I can leave `id` out of the schema definition. I am using the approach with the duplicated field (document_id) now, which is working fine 👍

**Comment by ArminShoeibi** [comment]
Hi there @jasonbosco

I’m trying to use Is not any of with the id field like this:

`id:![640926,598519,583651,372704,316539,315774,301011,298773,288544,285957,282763,273141,270086,264989,251149]`

But this doesn’t work, while the equivalent expanded form does:

`id:!=640926 && id:!=598519 && id:!=583651 && id:!=372704 && id:!=316539 && id:!=315774 && id:!=301011 && id:!=298773 && id:!=288544 && id:!=285957 && id:!=282763 && id:!=273141 && id:!=270086 && id:!=264989 && id:!=251149 && id:!=212956 && id:!=249307 && id:!=213095 && id:!=213065 && id:!=210597 && id:!=210604 && id:!=208276 && id:!=52743 && id:!=49692 && id:!=26216 && id:!=257478 && id:!=230951 && id:!=228498 && id:!=197408 && id:!=143606 && id:!=143201 && id:!=281253 && id:!=215198 && id:!=205914 && id:!=204698 && id:!=267620 && id:!=280701 && id:!=621040 && id:!=194056`

Docs say ![] should work for string fields, is there a limitation or bug with using it on the id field specifically?

**Comment by jasonbosco** [comment]
Since `id` is a special field, we need to add special handling for `:!=[]` for `id`. Could you open a separate GitHub issue for it?

**Comment by ArminShoeibi** [comment]
> Since `id` is a special field, we need to add special handling for `:!=[]` for `id`. Could you open a separate GitHub issue for it?

For sure.
https://github.com/typesense/typesense/issues/2700
