### ISSUE TITLE
Filtering `*` on Analytics popular queries

### ISSUE THREAD

**Issue by ajmnz** [typesense/typesense#1322]
## Description

When [creating a popular queries collection](https://typesense.org/docs/0.25.1/api/analytics-query-suggestions.html#create-a-collection-for-aggregation) for Analytics, one of the documents will inevitably be `*` if relying heavily on facets and filters to manage search results on the whole collection.

When building an Autocomplete search experience, `*` doesn't have much value or meaning, but the problem is that applying `"filter_by": "q:!=*"` doesn't do anything.

## Steps to reproduce

Execute the following search request on a popular queries collection that has a document with `q` set to `*`.

> Set the `count` field to something really high so it shows first

```json
{
  "q": "*",
  "query_by": "q",
  "filter_by": "q:!=*",
  "sort_by": "count:desc"
}
```

Hits will include `*`

```json
[
  {
    "count": 86,
    "id": "11421815545832784468",
    "q": "*"
  }
]
```

## Expected Behavior

Expected `"filter_by": "q:!=*"` to be applied and filter out `*`

## Actual Behavior

`*` is not filtered and will always appear.

## Metadata

**Typesense Version**: 0.25.1

**OS**: Whatever `typesense/typesense:0.25.1` Docker image runs on (Ubuntu I think)

**Comment by jasonbosco** [comment]
Ah hmm, could you try setting the collection schema for the analytics destination collection like this:

```js
{
  "name": "product_queries",
  "fields": [
    {
      "name": "q",
      "type": "string"
    },
    {
      "name": "count",
      "type": "int32"
    }
  ],
  "symbols_to_index": ["*"] // <=== Add this
}
```

And then try filtering on `*`?

**Comment by ajmnz** [comment]
That works, thanks!
