### ISSUE TITLE
Colons (`:`) do not work as token separators on cloud

### ISSUE THREAD

**Issue by npentrel** [typesense/typesense#1324]
## Description

Colons (`:`) do not work as token separators on cloud.

## Steps to reproduce

1. Click on new collection and add the following json:

```json
{
  "default_sorting_field": "last_updated",
  "fields": [
    {
      "facet": true,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "name",
      "optional": false,
      "sort": false,
      "type": "string"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "last_updated",
      "optional": true,
      "sort": true,
      "type": "int32"
    }
  ],
  "name": "separator_test",
  "symbols_to_index": [],
  "token_separators": [
    ":"
  ]
}
```

## Expected Behavior

Should work since it's a normal ASCII character ([link](https://github.com/typesense/typesense/issues/875)).

## Actual Behavior

I get the error `e: Request failed with HTTP code 400 | Server said: `token_separators` should be an array of character symbols.`.

## Metadata

**Typesense Version**: Typesense v0.23.1

**OS**: running in Typesense Cloud.

**Comment by kishorenc** [comment]
This works via curl, so could be an issue with the Cloud interface. We will investigate that and get back to you.

**Comment by jasonbosco** [comment]
@npentrel We've pushed out a fix for this issue. Could you try now on Typesense Cloud?

**Comment by npentrel** [comment]
Works beautifully now - thank you both!

**Comment by jasonbosco** [comment]
Great, thank you for catching that!
