### ISSUE TITLE
Optional filtering application

### ISSUE THREAD

**Issue by arvis00** [typesense/typesense#1328]
If my goal is to sort search results by date but give bias to some other parameters is this code correct:

`_eval(optionsLocations:=\(locationIDCity)):desc,_eval(optionsLocations:=\(locationIDState)):desc,_eval(optionsLocations:=\(locationIDCountry)):desc, date:desc`

So I want to sort results by date but first show the newest results that have locationIDCity (optionsLocations is an array of strings). Then after all newest results with cityID is shown (first priority), show results with stateID (second priority), thirdly show with CountryID (third priority) and then show the rest of results. All of these levels of sort should be sorted by date. 

Is the code above correct or should I write:

`_eval(optionsLocations:=[\(locationIDCity, locationIDState, locationIDCountry))]:desc, date:desc`

This second option as I understant will filter the optionsLocations array to include locationIDCity OR locationIDState OR locationIDCountry. But I want to prioritise these and firstly show cities then states then countries. BUT also show the newest objects at the same time. So is the first option correct?

This example better shows what I am after.

I have five objects:

(1) {optionsLocations: [city1, city2, state1, country1], date: july 20}
(2) {optionsLocations: [state1, country1], date: july 15}
(3) {optionsLocations: [country1], date: july 26}
(4) {optionsLocations: [city1, country1], date: july 5}
(5) {optionsLocations: [country2], date: july 10}
(6) {optionsLocations: nil, date: july 18}
(7) {optionsLocations: [city1, country4], date: january 5}

so the search should return objects in this order (if sorted by city1, state1, country1, date):
(1), (4), (2), (3), (5), (6), (7)

It is important to note that in this example it should NOT return all objects with city1 parameter first because my aim is to show the newest objects so I do not want to show old entries of city1 before showing state1 objects. This is illustrated by object no. 7 being at the end of results.

I hope it makes sense what I am after but to make it short I want to show the latest entries with certain bias towards particaluar parameters. So it is like a feed of posts which would show only the most recent ones at the top but also most relevant to the user's location. I am not sure if it is possible to set blocks of "time frames" where newest results with city1 would be at the top that are a week (hour, day, month) old, then state1 results (a week old) and so on.

**Comment by arvis00** [comment]
@jasonbosco in the docs I can see that you should also write :desc at the end of _eval() like this:
`_eval([ (optionsLocations: locationIDCity):3, (optionsLocations: locationIDState):2, (optionsLocations: locationIDCountry):1 ]):desc, date:desc`
Is that correct?

Also, currently when I apply this code, no results are returned for me. Do you need to have optionsLocation parameter to have sort option enabled in schema?

Lastly, regarding this sort code with eval(): what happens if there are no matches found with specific locationIDCity OR locationIDState OR locationIDCountry? Does it still return all other results (with different kinds of optionsLocations) at the end sorted by date?

**Comment by jasonbosco** [comment]
1. That's right. I've fixed the code in my previous comment to include `:desc` at the end of eval. 

2. Could you share a curl command that creates a collection, indexes a few documents and then does a search that replicates the issue? [Here's](https://gist.github.com/jasonbosco/7c3432713216c378472f13e72246f46b#file-typesense-repro-steps-sh) a template to use.

3. That's correct.

**Comment by arvis00** [comment]
This is my schema for optionsLocations:
`"facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "optionsLocations",
      "optional": true,
      "sort": false,
      "type": "string[]"`

(Note that sort is false)

In the docs it says that eval takes in the same parameters as filter. As optionsLocations is an array of strings in filter it has this syntax: `optionsLocations:=[locationIDCity, locationIDState, locationIDCountry]`

But in your example the syntax is different.

**Comment by arvis00** [comment]
My cluster was on version 0.25.1. After updating to 0.26.0.rc27 everything works as expected.
