### ISSUE TITLE
Allow control to disable using synonyms for search queries. 

### ISSUE THREAD

**Issue by narayanacharya6** [typesense/typesense#1334]
## New Feature Request

At the moment any search query one does the synonyms feature will be applied. There is no way to disable the usage of synonyms for certain queries. The only work around is to delete the synonyms which obviously is not a meaningful solution.

**Comment by stargazer33** [comment]
@narayanacharya6 imagine you can put the search term in quotes to force exact match (see #1880 ) - would it help?

**Comment by kishorenc** [comment]
In v27 RC builds, this is possible by setting the search time flag `enable_synonyms: false`.
