### ISSUE TITLE
Support Semantic Kernel

### ISSUE THREAD

**Issue by HazyFish** [typesense/typesense#1343]
## Description

We're a startup using Typesense. We want to build some LLM features using [Semantic Kernel](https://learn.microsoft.com/en-us/semantic-kernel/overview/) and really hope Typesense could be one of the supported vector databases with an available connector.

## Steps to reproduce

[Vector Database | Microsoft Learn](https://learn.microsoft.com/en-us/semantic-kernel/memories/vector-db#available-connectors-to-vector-databases)

## Expected Behavior

Typesense is one of the supported vector databases with an available connector.

## Actual Behavior

Typesense is currently not supported.

**Comment by jasonbosco** [comment]
@HazyFish Since the code for the integration would live in the Semantic Kernel repo, I would recommend opening a feature request in that repo

**Comment by HazyFish** [comment]
Sure! https://github.com/microsoft/semantic-kernel/issues/3337
