### ISSUE TITLE
Spellcheck not working with prefix of fieldValue

### ISSUE THREAD

**Issue by rahul-malviya-zpt** [typesense/typesense#1345]
## Description

Spellcheck is not working on prefix of field value.

## Steps to reproduce

1. Create a collection
2. Add only one field in the schema - 'title'
3. Add 3 documents with title value as 'brinjal', 'bran' and 'grain'
4. Search for 'brain'

## Expected Behavior

Document with title 'brinjal' should be returned in the result set along with 'bran' and 'grain'.
`brin` (prefix of brinjal) should have matched with the spell correction 'brin' of 'brain'.

## Actual Behavior

Only 'bran' and 'grain' are returned in the result.

## Metadata

**Typesense Version**: 0.25

**OS**: Typesense cloud

**Comment by kishorenc** [comment]
@rahul-malviya-zpt 

While `brin` is within 2 edit distance of `brain`, as we continue searching, `brinja` exceeds the 2-typo edit distance when compared with `brain` and from that point onwards no further characters will help `brain` match `brinjal` since they are not within 2 edit distances either (actual edit distance is 4).

**Comment by rahul-malviya-zpt** [comment]
@kishorenc 
I understand that the query 'brain' will not match with prefix 'brinja' but why did 'brin'(prefix of brinjal) not match with the query 'brain', when it is one edit distance away? 

I am expecting this behaviour because Jason mentioned that spell correction on prefix is supported. Is there a min character limit on the prefix length before it can be matched with spell corrections?

**Comment by kishorenc** [comment]
The query `brin` will match `brain` if there's no better typo match available. Since `brinjal` is a perfect prefix match that's picked ahead. You can adjust this behavior via the `typo_tokens_threshold`. From the docs:

> If typo_tokens_threshold is set to a number N, if at least N results are not found for a search term, then Typesense will start looking for typo-corrected variations, until at least N results are found, up to a maximum of num_typo number of corrections. Set typo_tokens_threshold to 0 to disable typo tolerance. Default: 1

Since default value is 1 and the `brinjal` correction atleast matches one document, further typo variations of the word was not checked. This offers flexibility in how you deal with typo correction.

**Comment by rahul-malviya-zpt** [comment]
@kishorenc you can try with a single document whose title is 'brinjal' and query as 'brain'. It gives zero results.

**Comment by kishorenc** [comment]
The query token is always compared with the whole word. So 'brain' (query) will not be matched with the prefix of the indexed word (brinjal). If we did that, there will be a lot of false positives. Instead, the query word is treated as a prefix and we check if another word completes it (we account for typos in the completion).

**Comment by kishorenc** [comment]
@rahul-malviya-zpt 

I forgot to mention that we do set a min threshold for 2-typo corrections. So to make `brain` match `brinjal` you need to enable it, via the `min_len_2typo` parameter. For e.g. see below. `brain` matches `brinjal` when `min_len_2typo` is set to 3.

![Screenshot from 2023-10-30 19-35-06](https://github.com/typesense/typesense/assets/782073/06784539-331c-48f2-849c-e616a64d35cd)

**Comment by rahul-malviya-zpt** [comment]
@kishorenc why do we have to rely on typo tolerance with 2 edit distance when `brin` is just one edit distance away from `brain`?

**Comment by kishorenc** [comment]
Since the query "brain" has 5 chars, we compare that with the first 5 chars of brinjal, i.e. with "brinj" for typos.

**Comment by rahul-malviya-zpt** [comment]
On query `brnj` `brinjal` matches, keeping the `min_len_2typo` as 7. 
If it was also matching the first 4 characters then `brin` wouldn't have matched with `brnj` with just 1 typo correction, as `brin` and `brnj` are 2 edit distance away.

**Comment by kishorenc** [comment]
There are some subtleties involved in the fuzzy matching algorithm for prefix typos. One detail that I omitted in my earlier response is that we look upto `num_typos` characters past the length of the query text to see if some trailing characters can align with the query to produce a lower edit distance. 

1. In the case of `brnj`, if we look at 1 char past, we will consider the first 5 chars of `brinjal` which is `brinj` and that's within one edit distance of the query. 
2. However, when we do the same for `brain`, the prefix `brinja` does not help -- it's not within 1 edit distance away.

**Comment by rahul-malviya-zpt** [comment]
Okay, got it. Thanks for the explanation.
