### ISSUE TITLE
Raspberry Pi 5 page size issues (ARM - 16K page size)

### ISSUE THREAD

**Issue by jdomlac** [typesense/typesense#1351]
## Description

Raspbian OS 64bit now brings 16K page size by default for the new Raspberry Pi 5, causing jemalloc unsupported system page size.
Similar issue on ARM machines: #969 

## Steps to reproduce

Run any typesense docker image:

```
export TYPESENSE_API_KEY=xyz

mkdir $(pwd)/typesense-data

docker run -p 8108:8108 -v$(pwd)/typesense-data:/data typesense/typesense:0.25.1 \
  --data-dir /data --api-key=$TYPESENSE_API_KEY --enable-cors
```

## Expected Behavior

Container running successfully.

## Actual Behavior

```
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
...
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
terminate called without an active exception
```

## Metadata

**Typesense Version**: 0.24.1, 0.25.1, 0.26.0

**OS**: Raspbian OS 64bit

**Comment by kishorenc** [comment]
This is becoming bit of a headache. AMD64 systems use 4K page size, newer ARM systems use 64K and Raspberry Pi now uses 16K. I wonder if we built using 64K it will work on all systems. I will try to produce a build for you to test by end of this week.

**Comment by thelazyoxymoron** [comment]
Sorry for the nag. Wondering if you've gotten a chance to look at the build using 64K.

I tried building this on my VPS but unfortunately the server crashed because of resource constraints.

**Comment by jdomlac** [comment]
Thanks for the build @kishorenc! I'm now running typesense on the Raspberry Pi 5 succesfully, without any problem so far.

**Comment by vertigo2600** [comment]
Hello @kishorenc @jdomlac 

I also have a pi5 and I'm trying to get typsense working with Docker.   Can you please explain how to use the new build you linked?

I tried adding the tar file to the desired directory and running "sudo docker image load -i  (typesense).tar.gz" but that's not working... 

My goal is to set up immich which relies on typesense but I'm stuck here.

> @thelazyoxymoron
> 
> Sorry about the delay. Can you please try with [this build](https://dl.typesense.org/debug/0.26.0.rcjemalloc1/typesense-server-0.26.0.rcjemalloc1-linux-arm64.tar.gz)?

**Comment by jdomlac** [comment]
What you get on the build is the actual executable, not a docker image, so what I did was:

`tar -xvf typesense-server-0.26.0.rcjemalloc1-linux-arm64.tar.gz`

You will now have the typesense-server executable. From here I built an image containing this executable. Here's the Dockerfile:
```
FROM typesense/typesense:0.26.0.rc38-arm64
COPY typesense-server /opt
ENTRYPOINT ["/opt/typesense-server"]
```
Just build this with `docker build` on the same directory you unpacked the executable and replace on the docker-compose files the typesense image with the custom one you just build.

Hope this helps.

**Comment by Jan0xxx** [comment]
I still get a error, however a different one ofcourse.
typesense  | E20231203    1 typesense_server_utils.cpp:359] Typesense failed to start. Data directory /XX does not exist.

Does anyone maybe have an idea how to fix this? Ofcourse, the data directory exists, but picking other ones does not help either.

**Comment by vertigo2600** [comment]
Thanks,  this was helpful but I'm still not quite there yet.   I was able to get an image built and a container started using your directions and some poking around through forums and searches... but the typsense container always closes after a few minutes because it's missing the data directory.   I realized this is because  when I run 

docker run -p 8108:8108 [image id] Im not passing any environment variables such as data directory or the api key.

I tried:  
docker run -p 8108:8108 [image id] \
  --data-dir /data --api-key=[my typsense api key] --enable-cors

but the same error occured.  I imagine the line above on it's own doesnt specify the env variables but I'm not sure how to make it do so.

For clarification the docker-comose.yml file I originally started with is below, where I have env set for api, data directory, and there is a separate .env file created with the proper values.  Is it possible to point the image line below to the new docker image ID that was built?

typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

My values:
docker image id:  9aa3a2dd7bd5
image tag:  typesense
pwd:  /home/vertigo2600/immich

any help or direction is greatly appreciated!

> What you get on the build is the actual executable, not a docker image, so what I did was:
> 
> `tar -xvf typesense-server-0.26.0.rcjemalloc1-linux-arm64.tar.gz`
> 
> You will now have the typesense-server executable. From here I built an image containing this executable. Here's the Dockerfile:
> 
> ```
> FROM typesense/typesense:0.26.0.rc38-arm64
> COPY typesense-server /opt
> ENTRYPOINT ["/opt/typesense-server"]
> ```
> 
> Just build this with `docker build` on the same directory you unpacked the executable and replace on the docker-compose files the typesense image with the custom one you just build.
> 
> Hope this helps.

**Comment by jdomlac** [comment]
When building a local docker image you can specify any tag:
`docker build . -t custom/image_name`
Then change it on your docker compose file:
```diff
typesense:
    container_name: typesense
-   image: typesense/typesense
+   image: custom/image_name
    environment:
```

**Comment by vertigo2600** [comment]
Thanks @jdomlac   I believe I've taken 4 steps forward and 1 step back!   Good news is I have immich up and running and there is no page size error.   It's functional, however I do however still have a few errors in the typsense log so i imagine I'll run into issues if I try to use the search bar.

I'll post my logs but let me know if I'm breaking ettiquite as the subject line issue of "Pi5 page size issues" is technically solved.

Typsense logs:
W20231205 13:57:35.343029   169 controller.cpp:1487] SIGINT was installed with 1
W20231205 13:57:35.490490   166 protobuf_file.cpp:91] open file failed, path: /data/state/log/log_meta: FILE_ERROR_NOT_FOUND
W20231205 13:57:35.490517   166 log.cpp:698] /data/state/log is empty
W20231205 13:57:35.499883   166 protobuf_file.cpp:91] open file failed, path: /data/state/meta/raft_meta: FILE_ERROR_NOT_FOUND
W20231205 13:57:35.505160   166 node.cpp:843] [default_group:172.21.0.2:8107:8108 ] Refusing concurrent configuration changing
E20231205 13:57:35.505215   166 raft_server.cpp:729] Node not ready yet (known_applied_index is 0).
E20231205 13:57:35.505403   210 raft_server.h:62] Peer refresh failed, error: Doing another configuration change

my guess is that it has to do with my environment variable:     - TYPESENSE_DATA_DIR=/data

In any case I'm at a point where I can wait for a stable release if I can't figure this out.

If I do I'll post a my complete step-by-step for any other linux newbies who are travelling down this rabbit hole.

Cheers!

**Comment by NJMorrow14** [comment]
hey @kishorenc, any chance you guys can release a .tar file for version 28.0?

**Comment by jasonbosco** [comment]
As of v28.0, we had to revert back the default pg size in the main ARM build to 4K. But we now publish a separate lg-pg-size build that has the page size set to 16K: https://typesense.org/docs/guide/install-typesense.html#large-page-size-build
