### ISSUE TITLE
Empty new line at documents import response

### ISSUE THREAD

**Issue by tugaykaracay** [typesense/typesense#1355]
## Description

Sometimes Typesense server returns an additional new line documents/import response. This causes a JSON.parse error on typesense-js library.

### Correct Response

```json
"{\"success\":true}
{\"success\":true}
{\"success\":true}"
```

### Invalid Response

```json
"{\"success\":true}
{\"success\":true}
{\"success\":true}
{\"success\":true}
{\"success\":true}
"
```

## Steps to Reproduce

1. Randomly happening

## Expected Behavior

There should be no new line at the end of response

## Actual Behavior

There is a empty new line at the end of response

## Metadata

**Typesense Version**: 0.25.2

**OS**: Docker Image

**Comment by kishorenc** [comment]
@tugaykaracay 

Is it possible for you to share a sample export call that triggers this behavior? For e.g. is it an export with a filter_by clause or just a plain export?

**Comment by kishorenc** [comment]
I misread the question: I now see that this is happening during _import_ and not _export_. Will look.

**Comment by kishorenc** [comment]
@tugaykaracay 

Since this happens randomly, can you check if this happens when the client side timeout happens? When that happens, the import could be abruptly cut off. I took a quick look at the code, but could not find any obvious issues.

**Comment by themerk** [comment]
I have definitely seen this too. It happens very rarely and seems totally random. I've experienced it since I started using Typesense Cloud many versions ago. I've never been able to capture the actual response since I'm using a hosted "serverless" platform and the exception just bubbles up from the typesense js library so it's hard to intercept. But I get that same parse error. Often it is successful on an immediate retry, but sometimes that fails as well. I suppose it could be network related, but I'd have thought the exception would be different if there isn't a valid HTTP 200 response.

I'm so glad someone else has seen this in the wild!

**Comment by kishorenc** [comment]
When an import response is prematurely truncated, the response code will still be 200 because the disconnect happens on the client because of a client imposed timeout. You can try increasing the connection timeout configuration on the client to see if that helps.

**Comment by tugaykaracay** [comment]
Hi, I've just checked the old logs, but it is not a client timeout error because the whole process only took ~300ms. We simply patched the typesense-js library to handle empty strings. Since we are using Typesense very intensively, we were encountering this error approximately 10 times per day but it is just ~0.02% of overall import requests.

**Comment by themerk** [comment]
I agree it's not a client timeout. It happens totally randomly on very small updates. The occasional large bulk imports I do with many times more data work fine and are well within the timeout.

**Comment by kishorenc** [comment]
Can you please try on `0.26.0.rc65`?

**Comment by tugaykaracay** [comment]
Hi, I can't try this until we upgrade the production nodes to latest RC version and we can't do that of course. You can close this issue if you want because or we need to wait until 0.26.0 or even 0.26.1 version release.

**Comment by kishorenc** [comment]
I think this should be fixed in v26. Feel free to reopen if the issue occurs again.
