### ISSUE TITLE
Multi-search: aggregate the results into a single list (merged and globally ranked multi-search)

### ISSUE THREAD

**Issue by dropsonic** [typesense/typesense#1357]
## Description

In many use cases, we need to show a unified search list composed of different entity types, each with its own set of facets, ranking rules, etc.

The list should be ranked globally based on the search query.

A typical example of this is an enterprise system like CRM or ERP where there are many types of entities, like contacts, leads, files, etc., or some "community" or blogging system with articles, comments, and users.

I've included some examples below.

Pipedrive CRM:
![image](https://github.com/typesense/typesense/assets/1544021/c08f184c-a4fc-4bf6-a8c5-1df56d5e228f)

Sulu CMS:
![image](https://github.com/typesense/typesense/assets/1544021/829f5b8f-224a-4f32-83cb-5a0787efc156)

Some "community"-like system:
![image](https://github.com/typesense/typesense/assets/1544021/ee51bbac-f24d-4bb3-819d-ea936de173b7)

Might also be linked with #1309.

This is a common pain point with search engines. For example, [Meilisearch declares this feature as their ultimate goal with federated search](https://blog.meilisearch.com/introducing-federated-search/):

> Our ultimate goal is to provide the hidden gem of federated search: **being able to search multiple sources and aggregate results in a single list**. Instead of having a response with a set of search results for each index searched, all the search results would be compiled into one list, sorted according to the ranking rules and settings of your choice.

## Expected Behavior

There is an option to execute multi-search and retrieve merged resultset that is ranked globally, not collection-wide.

## Actual Behavior

The results of multi-search must be merged on the client OR all entity types must be placed into a single index OR each collection must have its own UI section in the results.

### Client-side merging
Client-side merging possesses multiple technical challenges.
Theoretically, we can use `text_match` score to globally rank the results from different collections, but since different collections have a different set of fields and different ranking rules, I doubt that we can use the score to compare the results between collections.

Sorting by a common attribute is not possible. For example, as a user, I want to sort the resultset by last modified date descending, and it is almost impossible to achieve with multi-search by multiple collections with paging.

Paging is also an issue since the paging settings are per-collection, not per-query.

Another possible scenario is to display a separate section in the UI for every entity type, showing N results for a particular collection and a "Show More" button to load more results of a particular entity type. However, this is not very UX-friendly, especially in a case if the amount of entity types is high (5+).

### Using a single index
Using a single index is unsuitable for many scenarios, especially if the overall number of documents is very high so there are performance issues because of searching through a very large collection, and all entity types have a very different set of fields.
Also, In this case, fine-tuning the ranking per entity type is not possible.

**Comment by DmitryKey** [comment]
I agree to the overall request and have at present the same need.
Just wanted to suggest a method for this item:

> Theoretically, we can use text_match score to globally rank the results from different collections, but since different collections have a different set of fields and different ranking rules, I doubt that we can use the score to compare the results between collections.

It is called RRF: "Reciprocal Rank Fusion (RRF) is an algorithm that evaluates the search scores from multiple, previously ranked results to produce a unified result set." https://learn.microsoft.com/en-us/azure/search/hybrid-search-ranking

So per each page you can fuse the results using RRF. It would of course be great to have this option for fusing results built-in in Typesense.

**Comment by kishorenc** [comment]
Thank you for creating this issue. I agree that this will be useful. Will be tracking this as part of https://github.com/typesense/typesense/issues/381
