### ISSUE TITLE
array of string "string[] "  it didnt search the given query 

### ISSUE THREAD

**Issue by gokulnath1122** [typesense/typesense#1358]
## {"product": "Xiaomi Mi 11 ", "p_id": "p107","price": 5990,"ratings":5.0, "brand": "Xiaomi", "specs": ["Xiaomi Mi 11 - Black/128 GB", "Xiaomi Mi 11 - Blue/64 GB"], "colour": "Black", "product_details": [{"company": "Xiaomi Corporation", "place": "Beijing", "country": "China"}]}
{"product": "Sony Xperia 1 III", "p_id": "p106","price": 8909,"ratings":4.5, "brand": "Sony", "specs": ["Sony Xperia 1 III - Black/256 GB", "Sony Xperia 1 III - Purple/128 GB"], "colour": "Black", "product_details": [{"company": "Sony Group Corporation", "place": "Tokyo", "country": "Japan"}]}
{"product": "Google Pixel 6.1", "p_id": "p102","price": 81990,"ratings":4.4, "brand": "Google", "specs": ["Google Pixel 6.1 - White/128 GB", "Google Pixel 6.1 - Black/256 GB"], "colour": "White", "product_details": [{"company": "Alphabet Inc.", "place": "Mountain View", "country": "USA"}]}
{"product": "OnePlus 10 pro ", "p_id": "p104","price": 71990,"ratings":4.0, "brand": "OnePlus", "specs": ["OnePlus 10 pro - Blue/256 GB", "OnePlus 10 pro - Silver/128 GB"], "colour": "Blue", "product_details": [{"company": "OnePlus Technology", "place": "Shenzhen", "country": "China"}]}
{"product": "Xiaomi Mi 11i ", "p_id": "p107","price": 51990,"ratings":5.0, "brand": "Xiaomi", "specs": ["Xiaomi Mi 11i - Black/128 GB", "Xiaomi Mi 11i - Blue/64 GB"], "colour": "Black", "product_details": [{"company": "Xiaomi Corporation", "place": "Beijing", "country": "China"}]}

this is my jsonl data like this i have 1500 + i trying to search 128 gb but i get error 

## {
    "q": "128",
    "query_by": "specs"
}

## Expected Behavior

 "document": {
                "P_Name": "OS",
                "P_id": "P-106",
                "description": "operating system",
                "id": "1112",
                "is_Active": true,
                "price": 800,
                "product_details": [
                    {
                        "company": "windows",
                        "country": "USA",
                        "place": "washington"
                    }
                ],
                "product_id": [
                    "i phone - Blue/128 GB",
                    "i phone - green/64 GB",
                    "i phone - red/128 GB",
                    "i phone - Blue/256 GB"
                ],
                "type": "Software",
                "varriant_id": "v_1.2"
            },

and so .....

## Actual Behavior

i get error
## Metadata

**Typesense Version**: 0.25.0

**OS**: windows 10

**Comment by kishorenc** [comment]
You need to add `/` as a token separator, without which `White/128GB` will be indexed as `White128GB`. Here's how you can enable that during collection creation:

```
curl -k "http://localhost:8108/collections" -X POST -H "Content-Type: application/json" \
      -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{
        "name": "docs",
        "fields": [
          {"name": "title", "type": "string"}
        ],
        "token_separators": ["/"]
      }'       
```
