### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [typesense/typesense#1360]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Typesense application as shown [here](https://elest.io/open-source/typesense). I think it would be a great idea if we can add it to official readme/documentation here.
🔔  In addition to this, if you are interested we provide partnership opportunities with tools we support by revenue share upon addition of this method in docs. If you would like to collaborate, just shoot me an email at kaiwalya@elest.io :)

![image](https://github.com/typesense/typesense/assets/53310847/28ce0876-a08d-4d48-842a-78a4dfd61e05)

**Comment by jasonbosco** [comment]
We do not want to endorse closed-source extensions to Typesense, or other managed Typesense hosting _platforms_ besides what we have on Typesense Cloud, since it significantly increases our community support burden.
