### ISSUE TITLE
api key for wildcard collections

### ISSUE THREAD

**Issue by Geoffry304** [typesense/typesense#139]
## Description

Hello, am I correct that it isn't possible to create a search key for collections with a wildcard?

for  example
`
$prefix = 'test';
$response = $collectionManipulator->client()->keys->create([
            'description' => 'Search-only key for '. $prefix,
            'actions' => ['documents:search'],
            'collections' => [$prefix . "_*"]
        ]);
`

I want to do this because other application will also be stored on the server but they don't need to have access to other data. 
And manually adding for each collection is a lot of work.

Thanks in advance

**Comment by kishorenc** [comment]
👋  There is no way to refer to a bunch of collections using a wildcard at the moment, but that would be a good feature to support.

**Comment by jasonbosco** [comment]
Just released v0.18.0 with the ability to specify collection names using Regex when creating API keys: https://github.com/typesense/typesense/releases/tag/v0.18.0.

For eg: `coll.*` will match all collections that have "coll" in their name
