### ISSUE TITLE
Typesense seems cannot not allow an empty geopoint

### ISSUE THREAD

**Issue by khaledzaidan** [typesense/typesense#1391]
## Description

Even if a geopoint field is set as optional in the schema. It seems there's no way to successfully send a document to Typesense without the geopoint field. I've tried sending a null, a false, an array with two nulls or two falses, and i've tried not sending the field at all.

Typesense will always complain about something: either about the field being missing, or that a geopoint must be a 2 element array or that it simply isn't a geopoint (I'm guessing that it's in the wrong format).

## Steps to reproduce

I'm using the PHP SDK behind a Drupal module, so not sure about exact commands to reproduce (sorry), but I simply have a field `location` in the schema:
```
{
"facet": false,
"index": true,
"infix": false,
"locale": "",
"name": "langcode",
"optional": false,
"sort": false,
"type": "string"
}
```
And I've tried sending the values i mentioned above for this field.

## Expected Behavior

A null value is accepted if the geopoint field is optional.

## Actual Behavior

Error: "Field `location` must be a 2 element array: [lat, lng]." when I pass a null value.

## Metadata

**Typesense Version**: 0.25.1

**OS**: linux

**Comment by jasonbosco** [comment]
In your code snippet I see `"optional": false`. Could you set that to `"optional": true`? 

If the issue still exists, could you try upgrading to `0.25.2.rc9` and if the issue still persists, could you give me a set of curl commands [like this](https://gist.github.com/jasonbosco/7c3432713216c378472f13e72246f46b#file-typesense-repro-steps-sh) that replicates the issue?

**Comment by khaledzaidan** [comment]
Thank you for the quick response.

I have to say, this was just a user error... Drupal usually works by marking things as "required" rather than "optional"... i must've just confused myself at one point 🤦 

It all worked correctly once I'd set `"optional:: true`. I'll close the ticket!
