### ISSUE TITLE
Is it possible to index documents without storing them?

### ISSUE THREAD

**Issue by aborzanovic** [typesense/typesense#1398]
## Description

Basically the title. I have a decent amount of large documents and I'd like to index them but I'm worried about storage. Plus not having the actual document contents on the server would be a security bonus. Typesense records would basically just contain an ID. Is there a way to achieve this? Maybe sending the document over and updating it later to only contain an ID without touching the index? (Might be important to note - these documents would never change.)

Thanks!

**Comment by jasonbosco** [comment]
This is not possible. Indexing by definition stores the content of the documents in a way that's efficient for fast search.

**Comment by aborzanovic** [comment]
Sorry to reopen this and maybe it's a dumb question.

But if [this](https://github.com/typesense/typesense/issues/49#issuecomment-452175427) is still the case it would imply there's a separate storage for documents where I could strip them of their contents, right?

I get that an index would have to contain all of the contents but it would be deduplicated and it would be impossible to regenerate documents just based on the index.
