### ISSUE TITLE
Feature request: disable num_typos parameter for numeric characters

### ISSUE THREAD

**Issue by studiobovenkamer** [typesense/typesense#1400]
It would be great if we could use the "num_typos" feature along with a filter to disable it for numeric characters. Our current situation doesn't allow us to use the feature because setting it to even "1" can result in completely irrelevant results when used with typo tolerance for numbers. This is a problem for our users as they'll be shown fuzzy matches like "XYZ-223" when searching for a specific document named "XYZ-123". It would cause confusion for them, and it's not ideal from a UX perspective. 

In cases where users are searching for numeric values, they may not always expect or benefit from a typo tolerance feature. For example, when looking for a specific case number in a project archive, it's important that the search results match the exact number entered.

Subjective statement/opinion: Spelling errors are rarely made by users when it's searching for a numeric value.

**Comment by kishorenc** [comment]
Feature available in `0.26.0.rc48`. 

Set `enable_typos_for_numerical_tokens: true` to enable this feature. Default value is `false`.

**Comment by studiobovenkamer** [comment]
`enable_typos_for_numerical_tokens` seems to do the opposite of what is states.  If this is set to false then queries with typos ARE allowed, if I set it to true then typos in numerical queries are NOT allowed.

**Comment by kishorenc** [comment]
Fixed in `0.26.0.rc58`.

**Comment by jasonbosco** [comment]
Released in v26
