### ISSUE TITLE
Vector search result quality decreased over time

### ISSUE THREAD

**Issue by matthew-at-qamcom** [typesense/typesense#1404]
## Description

We have Typesense running on a database of about 18,000 embeddings.  Over time (~3 weeks) the quality of the approximate nearest neighbours search reduced significantly.  At the end, it produced the same set of results for drastically different embeddings.  Restarting Typesense resolved the issue.  

## Steps to reproduce

I've no idea how you'd reproduce this, sorry.  I appreciate it's a crap bug report, but figured you might like to know nonetheless. We did experience this on both of the two (almost) duplicate systems we've got running.

## Metadata

**Typesense Version**: 0.25.1

**OS**: Ubuntu 22.04

**Comment by kishorenc** [comment]
@matthew-at-qamcom 

Can you please try with `0.25.2.rc10`. We identified a potential regression that was fixed on this build. Please give this build a go and see if the same degradation happens over time.

**Comment by kishorenc** [comment]
@matthew-at-qamcom I know it has been only a week, but do you see any changes yet?

**Comment by matthew-at-qamcom** [comment]
Unfortunately, I'm not certain that patch fixes the same issue we're seeing.

On Friday, on our system that was running 0.25.2.rc10, we saw poor search results again.  While trying to discover why, the system was restarted and the embeddings database was significantly modified.  So I can't really say for certain either way: it could have been an issue with the embeddings this time, rather than a degradation in the quality of results returned by Typesense.

We'll keep testing and I'll get back to you once the systems have been running untouched for a while.

**Comment by matthew-at-qamcom** [comment]
We ran 0.25.2 for 14 days and didn't notice any degradation in results.  In comparison I'd previously seen degradation after just 8 days.  I'll close this issue.  Thanks for fixing it :o)

**Comment by kishorenc** [comment]
Thank you for confirming!
