### ISSUE TITLE
[Feature Request] Ability to use `include_fields` and `exclude_fields` in document GET endpoint

### ISSUE THREAD

**Issue by jasonbosco** [typesense/typesense#1411]
Related to https://github.com/typesense/typesense-js/issues/184

**Comment by hauktoma** [comment]
+ 1 for this feature.

We are using the "GET document" endpoint during ingest to check whether we need to reingest particular doc (doing diff if something changed). Main motivation is to keep the data up-to-date (important for us) but do not reingest blindly to avoid unnecessary recalculation. (Especially avoid recalculation of embedding fields -- image embedding and open-ai embeddings -- but also others, ideally skipping the document altogether if nothing changed.)

By calling the GET endpoint, the embedding fields (and some other fields) are returned also which is unnecessary for computation of our diff and they are not small. Using `exclude_fields` we would like to omit these from these queries.

**Comment by kishorenc** [comment]
This is fixed in recent RC builds of v27, e.g. `27.0.rc26`.
