### ISSUE TITLE
Allow `filter_curated_hits` parameter to work for pinned hits during search

### ISSUE THREAD

**Issue by vamshiaruru32** [typesense/typesense#1416]
## Description

If we use `pinned_hits` during a search call, those pinned hits appear in the results even if they don't match the search query/filter by. A parameter to tell typesense that they won't appear is required.

In curation, when you create overrides with `include_hits` you can provide `filter_curated_hits` param which provides a similar functionality.

**Comment by pspiller** [comment]
Having a `filter_curated_hits` equivalent on search calls would also be very useful for me. I'm using `pinned_hits` to simulate the effect of an override's `includes` parameter for immediate feedback in a UI. Without something like `filter_curated_hits`, it's possible to get documents in the results that don't match the query filters.

For comparison, it's possible to do this in Algolia, though it requires applying a "transient" rule to the query. Typesense's `pinned_hits` search parameter is much easier to use, and if there was a `filter_pinned_hits` parameter it'd be exactly what I need.

**Comment by kishorenc** [comment]
You can send `filter_curated_hits: true` for pinned hits as well now.  Try on `27.0.rc16` build.

**Comment by pspiller** [comment]
Great, thanks! I've tested this on `27.0.rc16` and filter conditions are applying to pinned hits.

**Comment by vamshiaruru32** [comment]
Hi @kishorenc , apologies for the delay. Got time to test this finally and it works as expected, thanks! I would like to know, is there a limit on number of pinned hits, or a recommended maximum? couldn't find it in documentation.

**Comment by kishorenc** [comment]
We don't enforce any limitation on number of pinned hits. Generally no point pinning more than a few because it's mostly a curation mechanism. If you want "fix" larger sets, better to assign a custom ranking field value and sort on that.
