### ISSUE TITLE
Question - Is it possible to have optional query parameters?

### ISSUE THREAD

**Issue by BekaArabidze98** [typesense/typesense#1420]
For example: `&query_by=name,description,responses,request,dataExample`
Is it possbile to have optional query params here, because There can be case where I dont have **dataExample**
in my schema field  and could be undefiend.
Becase of that sometimes when there is no dataExample field, typesense does not search anymore.

Thanks

**Comment by kishorenc** [comment]
Try marking the `dataExample` field as `optional` in the collection schema. For e.g.

```
{"name": "dataExample", "type": "string", "optional": true}
```

**Comment by BekaArabidze98** [comment]
Thing is when I am checking  schema it says that dataExample is optional.
I have just found out that.
