### ISSUE TITLE
Dependency errors with typesense 0.25.0 and 0.25.1 on linux

### ISSUE THREAD

**Issue by kslbdev** [typesense/typesense#1436]
## Description
I'm getting the following errors on amazon linux image, both arm64 and x86_64, (tried using `/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-arm64-gp2` as well as `/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2`) when using typesense 0.25.0 and 0.25.1. Note, The server is starting correctly with version 0.24.1

```
[ec2-user@ip-10-16-189-132 typesense]$ /opt/typesense/typesense-server
/opt/typesense/typesense-server: /lib64/libc.so.6: version `GLIBC_2.30' not found (required by /opt/typesense/typesense-server)
/opt/typesense/typesense-server: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /opt/typesense/typesense-server)
/opt/typesense/typesense-server: /lib64/libpthread.so.0: version `GLIBC_2.30' not found (required by /opt/typesense/typesense-server)
/opt/typesense/typesense-server: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /opt/typesense/typesense-server)
/opt/typesense/typesense-server: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /opt/typesense/typesense-server)
```

## Steps to reproduce
```
curl -O https://dl.typesense.org/releases/0.25.1/typesense-server-0.25.1-linux-arm64.tar.gz
tar -xzf typesense-server-0.25.1-linux-arm64.tar.gz -C /opt/typesense
rm typesense-server-0.25.1-linux-arm64.tar.gz
 /opt/typesense/typesense-server --config=/opt/typesense/typesense.ini
```

## Expected Behavior
Server should start without errors

## Actual Behavior
Server exits due to dependency errors

## Metadata
**Typesense Version**: 0.25.0 or 0.25.1
**OS**: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-arm64-gp2 OR /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

**Comment by kslbdev** [comment]
Looks like i needed to use an image with more recent kernel, as mentioned here #1195 and in the docs.

**Comment by jh0274** [comment]
@kslbdev can i ask what image you used please? I'm having trouble finding a kernel version > 6 for the image type i need..
