### ISSUE TITLE
Does Typesense have limitation for string field length or filter query length?

### ISSUE THREAD

**Issue by chimd715** [typesense/typesense#1439]
## Description

Does Typesense have limitation for string field length or filter query length?

## Steps to reproduce

Use very long value for string field then filter by the value

## Expected Behavior

Return saved data with very long string

## Actual Behavior

Does not return any result

## Metadata

**Typesense Version**: 0.24.1

**OS**: Mac

**Comment by kishorenc** [comment]
We support upto 100 clauses in filter by. We have an issue open to make this configurable: https://github.com/typesense/typesense/issues/1441

**Comment by chimd715** [comment]
100 clause as query parameter count. What I want to know is the string length for a single field/query.
For example, `"q": "*", "query_by": "name", "filter_by": "name:=" + "a" * 9999999999999999999`

**Comment by kishorenc** [comment]
We have a 100-char limit for individual tokens.

**Comment by chimd715** [comment]
Okay! Thanks!!

**Comment by ulgens** [comment]
Sorry for necroposting but I'm having a similar issue with no hope from the docs.

> We have a 100-char limit for individual tokens.

I'm not exactly sure what this means but it seems there is a "max length" limit for `filter_by` query. I can make a request with 

```python
# unexpected_ids is a list of UUIDs with 100_000 entries
unexpected_ids = unexpected_ids[:10000]
delete_response = self.collection.documents.delete(
    DeleteQueryParameters(
        batch_size=1000,
        filter_by=f"id:=[{', '.join(unexpected_ids)}]",
        ignore_not_found=True,
    ),
)
```

but making the request without the slicing fails with 

```
typesense.exceptions.RequestMalformed: [Errno 400] API error.
```

I believe there is a hard limit on the body or arg size that the server accepts, but so far I couldn't find any information about its details.
