### ISSUE TITLE
Feature Request: server configuration option to increase (or remove) the maximum number of filter_by parameters

### ISSUE THREAD

**Issue by Geomitron** [typesense/typesense#1441]
## Description

I have a use case that requires adding hundreds of filter_by parameters (joined with && or ||) to query my data properly. If I use over 100, I get a 400 response: "`filter_by` has too many operations." Please add an option to increase or remove this limit.

**Typesense Version**: 0.25.1

**OS**: typesense/typesense:0.25.1 docker image

**Comment by Nargonath** [comment]
When using `filter_by` for a `IN` operator kind of query, e.g `filter_by=category:=['cat1', 'cat2']`, is there a limit on the number of values that you can search in? I tested using `/multi_search` and with an array with 10,000 values. I didn't get any error from Typesense but I wonder if they're really all accounted for.

**Comment by Nargonath** [comment]
I retested with existing values and not dummy generated ones. I didn't face any issues and they all seemed to be accounted for.

**Comment by freetonik** [comment]
>is there a limit on the number of values that you can search in?

I am also interested in finding an answer. It's cool that it works with 10k values, but is there still a higher limit? Anybody knows?

**Comment by jasonbosco** [comment]
This is now configurable using the `filter-by-max-ops` server parameter in v27.1, documented under this table: https://typesense.org/docs/27.1/api/server-configuration.html#resource-usage
