### ISSUE TITLE
Expiry for Scoped Search Keys

### ISSUE THREAD

**Issue by agentile** [typesense/typesense#145]
## Description

It would be nice to be able to set expiry of scoped search keys, like Algolia does with `validUntil` https://www.algolia.com/doc/api-reference/api-methods/generate-secured-api-key/

You would be able to encode an expiry unix timestamp as part of the scoped search key, then the server, if it is present if past the timestamp, the request fails.

The use case here is mainly around security, where we can set expiration limits, so that if a user is deleted their scoped search key will no longer work after a given session time frame, rather than needing to rotate search keys as often.

**Typsense Version**:
0.16

**OS**:
Amazon Linux 2

**Comment by jasonbosco** [comment]
@agentile We just released v0.18.0 with this feature: https://github.com/typesense/typesense/releases/tag/v0.18.0.

You can now set an `expires_at` field when creating keys with a Unix timestamp to specify an expiration date.
