### ISSUE TITLE
sort_by in geo-search forgets real distances when 'precision' is used

### ISSUE THREAD

**Issue by DmitryKey** [typesense/typesense#1460]
## Description

`'sort_by': f"_text_match(buckets: 5):desc, location({lat}, {lon}, precision: 2mi):asc"`

Forgets to return original distances

while 

`'sort_by': f"_text_match(buckets: 5):desc, location({lat}, {lon}):asc"`

does return original distances

(syntax above is Python)

## Steps to reproduce

Index objects with 'location' field of type 'geopoint' and configure above sort functions on the queries.

## Expected Behavior

I'd like to see original distances to objects in both cases.

## Metadata

**Typesense Version**: 0.25.1

**OS**: docker

**Comment by happy-san** [comment]
Hi @DmitryKey I tried to reproduce the issue with `0.26.0.rc66` but I do get `geo_distance_meters` in the response even with `precision` specified in the `sort_by`. Can you try using this build and check if it works for you too? If not, please share a minimal example that reproduces the issue.

**Comment by DmitryKan-TomTom** [comment]
Hi @happy-san somehow did not get notified of your question - thanks for checking!

I have upgraded to version 26.0 and do see the `geo_distance_meters` as well. But the point is that the values are exactly the same: 3218m.
What I expect to get is the real distance, like 52m, 143m etc.

Does it make sense?

**Comment by happy-san** [comment]
Can you share a simple example to reproduce the issue?

**Comment by happy-san** [comment]
@jonathan-rvezy Can you share a set of lat-longs and the query so I can reproduce the issue?

**Comment by kishorenc** [comment]
Fixed in `27.0.rc24`
