### ISSUE TITLE
Configuring local embedding model

### ISSUE THREAD

**Issue by AzikDeveloper** [typesense/typesense#1470]
In the documentation [here](https://typesense.org/docs/0.25.2/api/vector-search.html#using-your-own-models) it says:

> Create a directory under <data_dir>/models and store your ONNX model file, vocab file, and a JSON for model config there.

what directory is "<data_dir>" exactly ?
I downloaded "distiluse-base-multilingual-cased-v2" model but not sure where to place it so that typesense can use it.

**Comment by jasonbosco** [comment]
`data_dir` is the same as the `--data-dir` server configuration parameter you used when starting the Typesense server.
