### ISSUE TITLE
Song Showcase seems to crash on specific request

### ISSUE THREAD

**Issue by Kerollmops** [typesense/typesense#148]
## Description

Hey, I am testing the song showcase you have recently linked into the Showcase markdown. 

## Steps to reproduce

It seems that when I am searching for "a milli" and tick the artist "Lil Wayne" the server becomes down for a moment.
[Here seems to be the specific URL that kills it](https://songs-search.typesense.org/?s%5Bquery%5D=milli&s%5BrefinementList%5D%5Bprimary_artist_name%5D%5B0%5D=Lil%20Wayne).

Once this URL is called, the engine only answer with `{ "message": "Not Ready"}` messages with the 503 status.

---

Hum, or is it related to this new feature?

> Ensured that the server returns a 503 response when it is still catching up on the writes from the leader. This threshold can be controlled by the --catch-up-threshold-percentage argument (default: 95).

**Comment by jasonbosco** [comment]
@Kerollmops Looks like the demo is suddenly getting a fair amount of traffic. So I'm in the process of upscaling the infrastructure to handle the traffic. That could explain the 503. Once it's back I'll check that particular query to see if it indeed causes issues.

**Comment by Kerollmops** [comment]
Ok so the real thing to reproduce the bug is to write "a milli" in the search bar, tick "lil wayne" by searching it in the artist, there, I don't understand why, but the website automatically removes the "a " in front of my request, if I put it back I get 503s.

**Comment by jasonbosco** [comment]
Confirming that that particular facet query is indeed the one that's causing the issue. I found the stack trace in the logs. Looking into it further. Thank you for reporting this @Kerollmops!

**Comment by jasonbosco** [comment]
Turns out this was a JSON serialization issue with some specific characters in the MusicBrainz dataset. The fix is now available in an RC build. Will publish it in the coming week.
