### ISSUE TITLE
Astro Support

### ISSUE THREAD

**Issue by yolmcore** [typesense/typesense#1484]
Feature request:

We are using Astro for our web site and would like to use it for Documentation too, but neither they nor you offer integration with one another. Can you add a search integration similar to Docusaurus to Astro / AstroDocs? 

If not, can you point me to how I could do it without an integrated solution?

**Comment by jasonbosco** [comment]
@yolmcore You can already use Typesense DocSearch with any documentation site. The Docusaurus and Vuepress plugins are just convenience methods. 

You want to follow Steps 1 and Step 2 + Option C in [this article](https://typesense.org/docs/guide/docsearch.html).
