### ISSUE TITLE
"Partial product name search"  :  search with   keyword which product with apple airpods need to show  product or relavant , its showing some other product related to food at last with apple watch .   api linnk with sample data: 

### ISSUE THREAD

**Issue by gokulnath1122** [typesense/typesense#1487]
## Metadata

**Typesense Version**:

**OS**:

**Comment by jasonbosco** [comment]
Please open a new issue with more information. A set of curl commands [like this](https://gist.github.com/jasonbosco/7c3432713216c378472f13e72246f46b) with some sample data will be best to help identify a solution.
