### ISSUE TITLE
'filter_by' value not accepting colons(:)

### ISSUE THREAD

**Issue by axionos** [typesense/typesense#149]
## Description

I want to filter my data by something like "http://type", but the filter doesn't accept a colon.
Is there a way a colon(:) can be included in values that are faceted and searched?

## Steps to reproduce

Send below searchParameters to search and filter the data. The first one doesn't work but the second one does.

`let searchParameters = {
      q: '*',
      query_by: 'name',
      filter_by: 'type:=http://type/ontology/WholesaleBroker'
};`

`let searchParameters = {
      q: '*',
      query_by: 'name',
      filter_by: 'type:=http//type/ontology/WholesaleBroker'
};`

## Expected Behavior

Typesense returns data with type 'http://type/ontology/WholesaleBroker'.

## Actual Behavior

If the first searchParameters is being sent, an error is returned:
Error: Request failed with HTTP code 400 | Server said: Could not parse the filter query.

Second searchParemeters returns the expected data, but it's not including the colon(:).

## Metadata

**Typsense Version**: 0.8.0

**OS**: Mac

**Comment by kishorenc** [comment]
@axionos 👋 

Thanks for reporting this issue. I've just fixed this, and I can create a RC build for you to test. 

1. Are you using the Mac binary or Docker on Mac?
2. Would like to confirm again that you are really using version `0.8.0` as mentioned above, since that's a really old version of Typesense.

**Comment by axionos** [comment]
Hi @kishorenc 

1. I'm using linux binary and mac binary and linux binary on server is `typesense-server-0.16.0-1.x86_64.rpm` which is the latest version.

2. Yes, it is version 0.8.0. That's the version that was automatically installed when I ran `npm install typesense`. I noticed the latest version is 0.16.1. Do you recommend to upgrade?

Please let me know how to test the RC build. Thank you!

**Comment by hadfield** [comment]
@axionos the 0.8.0 is the npm package version, which is the right one for the current server version.

according to docs on NPM:

Typesense Server | typesense-js
-- | --
>= v0.16.0 | >= v0.8.0

**Comment by axionos** [comment]
@kishorenc I downloaded the newest 0.16.1 version from https://typesense.org/downloads/ to update the server and tested filtering with a type including colon(:).
However, it is still giving me the same error message (Error: Request failed with HTTP code 400 | Server said: Could not parse the filter query).

**Comment by kishorenc** [comment]
@axionos I've published the `0.17.0.rc4` RC rpm build with this fix here: [Download](https://dl.typesense.org/releases/0.17.0.rc4/typesense-server-0.17.0.rc4-1.x86_64.rpm).

Docker image is also available: `docker pull typesense/typesense:0.17.0.rc4`

Please try it out and let me know if you are still getting that error.

**Comment by axionos** [comment]
@kishorenc After installing the updated typesense server, the issue with colons have been fixed. Thank you!

**Comment by kishorenc** [comment]
Glad to hear, and thanks for confirming!

**Comment by LaundroMat** [comment]
Are the instances on typesense cloud the latest versions? Because I have the same issue. Filtering on a facet containing a colon results in a `RequestMalformed: [Errno 400] Could not parse the filter query.` error.

```
schema = {
    'name': 'test',
    'fields': [
        {'name': 'ranking', 'type': 'int32'},   
        {'name': 'content', 'type': 'string'},
        {'name': 'type', 'type': 'string', 'facet': True},
        {'name': 'source', 'type': 'string', 'facet': True},
    ],
    'default_sorting_field': 'ranking'
}

source = 'something:else'

client.collections['test'].documents.upsert({
    'ranking': 1,
    'content': 'test',
    'type': 'the testing type',
    'source': source
})

search_params = {
    'q': '*',
    'query_by': 'content',
    'facet_by': 'type,source'
}

client.collections['test'].documents.search(search_params)

search_params['filter_by'] = 'type:the testing type' # Works fine

client.collections['test'].documents.search(search_params)

search_params['filter_by'] = f'source:{source}'  

client.collections['test'].documents.search(search_params) # RequestMalformed: [Errno 400] Could not parse the filter query.

```

**Comment by kishorenc** [comment]
I just verified on 0.17.0 again on Cloud and it works. Can you please check the right side bar of your cluster page to verify that you are indeed on 0.17.0? Clusters are not auto upgraded.

**Comment by LaundroMat** [comment]
Oh, am I so sorry! For one reason or another I did not see that the typesense version was displayed on the cluster page 🙄 
It's at 16.1, so there's the issue. Thanks for the speedy response and sorry again.
