### ISSUE TITLE
Possibility of returning the query with typo corrections

### ISSUE THREAD

**Issue by danielbasso** [typesense/typesense#1492]
## Description

I don't know if it is supported right now, but would be nice to be possible to have in the response the query that was applied with the typo corrections. I want to implement something like google's "did you meant ...". As it stands right now, the only way I know that Typesense did modify the search behind the scenes is looking for the highlights.

**Comment by jasonbosco** [comment]
Within the `highlight` key in the response, you should also see a `matched_tokens` key which will give you an array of words that were matched. You could use that to power a "Did you mean" feature...

**Comment by danielbasso** [comment]
Hi @jasonbosco , nice to meet you.

I thought of using the approach you suggested, but it is sub-optimal for 3reasons:

1) Check issue #1459 . `matched_tokens`, as of right now, don't return the full list of tokens, for the reasons explained there;
2) `matched_tokens` is a property of each hit, not the response, so I would have to iterate through each hit and get the tokens first, and the resulting set could not be complete (say, there is a word in the next batch of results);
3) There is no way of knowing, from the` matched_tokens` list, which words were replaced, in cases of more than one word was used in the search (I tested that this can happen, a two word search that one of them is replaced and the other not).

Why is this a problem: The only way right now of knowing which word was replaced is by looking at the highlights of each individual hit. As a enhancement, I suggest:

1) For the result object, have alongside the user query ("q"), a new field indicating the actual query with the replaced words;
2) In this new field, the replaced words could be marked, similar to highlights, so frontend could style them differently;
3) For the result object, have a list of words with the original search word and the replaced word,

**Comment by jasonbosco** [comment]
> For the result object, have alongside the user query ("q"), a new field indicating the actual query with the replaced words;

The problem though is that each document inside the `hits` array might have matched due to matching a different subset of keywords that the user typed in. So the "corrections" are not applied at the search query level, but instead at each document...

**Comment by danielbasso** [comment]
Got it. Thanks for the explanation.
