### ISSUE TITLE
Extra new line shows up in the Import API response, which affects JSONL parsing in client libraries

### ISSUE THREAD

**Issue by jasonbosco** [typesense/typesense#1494]
```javascript
client
  .collections(collectionName)
  .documents()
  .import(formattedDocs, { action: 'upsert' });
```

```bash
/node_modules/typesense/src/Typesense/Documents.ts:346
        .map((r) => JSON.parse(r)) as ImportResponse[];
         ^
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /node_modules/typesense/src/Typesense/Documents.ts:346:26
    at Array.map (<anonymous>)
    at Documents.<anonymous> (/node_modules/typesense/src/Typesense/Documents.ts:346:10)
    at step (/node_modules/typesense/lib/Typesense/Documents.js:48:23)
    at Object.next /node_modules/typesense/lib/Typesense/Documents.js:29:53)
    at fulfilled (/node_modules/typesense/lib/Typesense/Documents.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Typesense Response (notice the extra new line at the end): [parsing-error.txt](https://github.com/typesense/typesense/files/13969763/parsing-error.txt)

Context in Slack Discussion:

https://threads.typesense.org/2Kb80b

https://typesense-community.slack.com/archives/C01P749MET0/p1705508838665499

<img width="1399" alt="Screenshot 2024-01-17 at 5 10 17 PM" src="https://github.com/typesense/typesense/assets/458383/e23c260c-a748-44f6-aa21-12c0eb73f5db">

## Metadata

**Typesense Version**: 0.26.0.rc40

**OS**: Typesense Cloud

**Comment by ffager83** [comment]
I’ve been getting this exact issue on our self hosted cluster as well! We’re on 0.25.2, currently with three nodes in our cluster.

works well locally with ”same” data, single node. But close to everytime gives the json parse error when trying to import prod data from MongoDB to typesense. 

Really nice to see a solution/explanation to this! Thanks to everyone involved! 🙏🏼

cant wait for final 0.26.0 now! 😎

thank you for an absolutely awesome piece of software!

**Comment by jasonbosco** [comment]
@ffager83 The patch for this is already in `0.26.0.rc49`. 

You should see this version when you go to Cluster Configuration > Modify in Typesense Cloud.

**Comment by ffager83** [comment]
> @ffager83 The patch for this is already in `0.26.0.rc49`.
> 
> You should see this version when you go to Cluster Configuration > Modify in Typesense Cloud.

Thanks for your quick reply and quick fix! 

But as briefly mentioned before, we’re using a self hosted and self configured Typesense cluster. Running inside our exsisting AWS infra. So not using Typesense Cloud. 

But yes, we could update to the newer version, shouldnt be an issue. 👍🏼 

Still being marked as an RC, do you consider it being stable enough and production ready as compared to 0.25.2? 
And also is the current node/javascript client compatible with it? (1.7.2 if I remember correctly)

I will take a closer look at the new version today and play around with it. 😎

**Comment by milsosa** [comment]
Is there any planned date for the final release of v0.26.0?

**Comment by jasonbosco** [comment]
We're at least 3-4 weeks out. We don't have a fixed release schedule, since we want to make sure we give enough time for users to give us feedback and iron out any issues before a GA release.

**Comment by jasonbosco** [comment]
We've expanded the scope of 0.26.0 a bit more, so we're still at least a month out unfortunately. 

That said, `0.26.0.rc54` is stable and we have high traffic users using it successfully in production. So you can already start using that.

**Comment by jasonbosco** [comment]
Released in v26

**Comment by jdriscoll98** [comment]
@jasonbosco You guys are awesome!
