### ISSUE TITLE
Trying to generate embeddings using in-built

### ISSUE THREAD

**Issue by zehawki** [typesense/typesense#1507]
## Description

Trying some experiments (Round 1):
1. Started with a "fresh" server (clone of an existing production)
2. Upgraded TS to 0.25
3. Target is a collection with around 18K docs (post, articles etc)
4. Did an update collection to generate embeddings with `ts/all-MiniLM-L12-v2`
5. Server has been churning away since then for 18 hours
6. API calls to this collection dont complete (as expected) while calls to other collections do complete, also as expected
7. Which means that TS is working fine, and its not crashed
8. Next I did a restart on typesense-server.service, however server is still churning away and # 4 is still the behavior

So, this begs some questions:
1. While obviously embeddings are computationally intensive, could they be going for such a long duration?
2. How does one see whats going on, the log doesnt show anything re embeddings AFAICS
3. Shouldnt a service restart stop this. (Of course that might leave the DB is an inconsistent state, so I understand why the activity is resumed post restart)
4. How does one then stop embeddings generation?

## Metadata

**Typesense Version**:
0.25.2

**OS**:
Ubuntu 20.04.6 LTS

**Comment by kishorenc** [comment]
> Did an update collection to generate embeddings with ts/all-MiniLM-L12-v2

Can you post the exact command you used? Sounds like a bug.

**Comment by zehawki** [comment]
Via postman, PATCH to `{{server_url}}/collections/{{collection_name}}`

```
{
    "fields": [
        {
            "name": "embedding",
            "type": "float[]",
            "embed": {
                "from": [
                    "title",
                    "desc",
                    "content"
                ],
                "model_config": {
                    "model_name": "ts/all-MiniLM-L12-v2"
                }
            }
        }
    ]
}
```

**Comment by zehawki** [comment]
Still further experiments:
1. Started with a "fresh" server (clone of an existing production)
2. Upgraded TS to 0.25
3. Deleted the earlier collection I was trying on
4. Created the collection again
5. *Updated* the collection with the embedding field exactly as I was trying earlier - this time it happened instantly, since of course 0 docs
6. Added a doc, and I can see that the embeddings field has data

```
{
  "embedding": [
    -0.01504360232502222,
    -0.03568878397345543,
    ...
  ]
}
```

**Comment by kishorenc** [comment]
Are you able to reproduce the same issue consistently when you do have docs already in collection? Meanwhile we will also try to reproduce this behavior.

**Comment by zehawki** [comment]
Round 3 - same as my 1st post:

1. Target is the same collection with around 18K docs (post, articles etc)
2. Did an update collection to generate embeddings with ts/all-MiniLM-L12-v2
3. Server has stared churning away
4. API calls to this collection don't complete (as expected) while calls to other collections do complete, also as expected
5. Which means that TS is working fine, and its not crashed

![image](https://github.com/typesense/typesense/assets/8095144/748e0886-f81a-4acc-9e8c-8ad5b9917583)


Will update after some hours if this remains the same.

**Comment by zehawki** [comment]
Yup, server has been churning away for last 12 hrs, so I was able to reproduce the same issue at least once.

**Comment by kishorenc** [comment]
I'm able to reproduce the issue. Will keep you posted on the fix.

**Comment by kishorenc** [comment]
@zehawki 

This could be an issue only with `ts/all-MiniLM-L12-v2` model. For e.g. when I try on `ts/e5-small` it worked fine, so that's a work around for now.

**Comment by zehawki** [comment]
As a side issue, and not to hijack this thread - can you guys please make some recommendation, if possible, of which is the "best" model to use within TS. Of course, "best" could be subjective, but perhaps you guys have tested some of the models and can make some recommendations.

**Comment by zehawki** [comment]
And this would also be relevant in case one wants to change the previous embeddings https://github.com/typesense/typesense/issues/1450

**Comment by kishorenc** [comment]
@zehawki 

On further testing, I'm actually unable to reproduce this issue (it was a little slower with `ts/all-MiniLM-L12-v2` but it did not actually get stuck). I've now tried this on a few different datasets. Would you be able to share a sample dataset? 

As for recommendation on the best model, you can refer to the MTEB leaderboard to check how different models perform across a variety of domains and Q&A datsets: https://huggingface.co/spaces/mteb/leaderboard

**Comment by zehawki** [comment]
> Would you be able to share a sample dataset?

Is there a format that you guys prefer? Though this is a bit difficult to export.

Conversely can I just send across the snapshot?

**Comment by kishorenc** [comment]
A snapshot is fine as well. So I need to load the snapshot and then run the alter command?

**Comment by zehawki** [comment]
I'd also like to point out some strange server happenings:

As part of my trials, I selected 2 servers running Typesense - one in the US and another in India.
In both I created a new collection `content1`, with auto embedding (ts/all-MiniLM-L12-v2)
I indexed thousands of the same docs Ive been working with in this set of trials, into `content1`.

Here's the 1st graphic showing server CPU util for the past 1 month in both geos. Until I started with the semantic search trials, the utilization barely went above 20%, and this is most normal.

![image](https://github.com/typesense/typesense/assets/8095144/b41c660f-9326-498e-a759-d38be63ed8c2)



The 2nd graphic below shows peaks where I indexed the documents, indexing was done in parallel to both servers. Indexing completed at 0130 on 27/01/24. NO further indexing occurred on `content1` after that.

![image](https://github.com/typesense/typesense/assets/8095144/d9b9f6b8-8c46-4f34-87de-844300741027)



Post that suddenly around 0545 on 27/01/24 the server CPU util shot up to 100%, on BOTH servers, simultaneously. Something that has never occurred before. So what caused this spike, soon after upgrade to 0.25 and auto-embedding generation? It can't be traffic to 2 separate geos simultaneously.

Further, both servers became complete unresponsive - no API responses, couldnt SSH etc. Again something that has never ever occurred before.

After this, I rebooted both servers, deleted `content1` from both, and both servers have been humming along like before.

**Comment by kishorenc** [comment]
> At which point you could load and run the alter command.

Sounds good.

>  So what caused this spike, soon after upgrade to 0.25 and auto-embedding generation? 

Anything in the logs just before those spikes?

**Comment by zehawki** [comment]
I think this is possibly solved. Previously after looking thru all the logs, it looked like an out-of-memory issue. 

Today Ive tried with:

1. Much better server class
2. TS 26.0
3. 20K docs
4. gte-small

And it got done in about 35 mins (1st spike).

![image](https://github.com/typesense/typesense/assets/8095144/1bfe5803-1a7a-4ef9-baf7-02c1946cc71f)
