### ISSUE TITLE
New lines causing for lack of matching

### ISSUE THREAD

**Issue by agentile** [typesense/typesense#151]
## Description

I index a note (string) that has a new line in it

```
  ["body"]=>
  string(12) "note:
vikram"
```

Then search for `vikram` , will not hit. `note` will. Is this expected? Should I be using particular query parameters here? 
With corresponding field with Algolia, this document will be found

## Steps to reproduce

Index content with newlines, see above.

## Expected Behavior

Match content not affected by new lines.

## Actual Behavior

Match does not hit.

## Metadata

**Typsense Version**:
0.16.1
**OS**:
Amazon Linux 2

cc @jasonbosco

**Comment by kishorenc** [comment]
👋 Yes, this is an issue because the tokenizer splits text only on a space and not a newline character. Will address this.

**Comment by kishorenc** [comment]
@agentile This has been fixed in `v0.17.0` just released.
