### ISSUE TITLE
update nested fields not working it show updated:1 but it not updated

### ISSUE THREAD

**Issue by MutharasuArchunan13** [typesense/typesense#1517]
## Description
I am encountering difficulties updating particular values within nested fields. While attempting to update, I retrieve the entire document, filter by index, and perform the update. However, this approach becomes problematic when updates are frequent. Additionally, after updating, the Typesense API returns { "num_updated": 1 },using typesense update(update_data,{filter_by:"conditions"} indicating an update, but the document remains unchanged.

## Steps to reproduce
![image](https://github.com/typesense/typesense/assets/143673568/6820ffd2-2af7-439a-a406-93e9536ee0f4)

## Expected Behavior

After updating based on the ID and fields, the document within the nested fields should reflect the changes.

## Metadata

**Typesense Version**: 0.25.2

**OS**: ubuntu

**Comment by kishorenc** [comment]
We discussed this in Slack. Feel free to reopen if this is a different issue.
