### ISSUE TITLE
Externally-generated embeddings for indexing and querying

### ISSUE THREAD

**Issue by zehawki** [typesense/typesense#1527]
I would like to be able to use any model for both indexing and querying, and one way to achieve this is to generate the embeddings externally.

A slightly different version of this: https://github.com/typesense/typesense/issues/1254, and coming from a desire to use any model (self hosted or via someone's API) without being dependent on TS needing to provide and support that. Also this https://github.com/typesense/typesense/issues/1318

For indexing its quite clear: [Option A: Importing externally-generated embeddings into Typesense](https://typesense.org/docs/0.25.2/api/vector-search.html#option-a-importing-externally-generated-embeddings-into-typesense
)
But I'm a bit puzzled how one would perform querying in this case? Am I supposed to use [Nearest-neighbor vector search](https://typesense.org/docs/0.25.2/api/vector-search.html#nearest-neighbor-vector-search) and supply the query embeddings under `vector_query`?

**Comment by ozanarmagan** [comment]
>Am I supposed to use [Nearest-neighbor vector search](https://typesense.org/docs/0.25.2/api/vector-search.html#nearest-neighbor-vector-search) and supply the query embeddings under vector_query?

Yes, you can provide external query embeddings under `vector_query`.
