### ISSUE TITLE
[docs] How to backup cluster data ?

### ISSUE THREAD

**Issue by v-byte-cpu** [typesense/typesense#153]
## Description

I want to know how to backup all cluster data. At the present time I found only **Export documents from a collection** API. Moreover, I did not find any configuration options for export documents. I assume that this operation should have at least batch size like [Elasticsearch Scroll API](https://www.elastic.co/guide/en/elasticsearch//reference/current/paginate-search-results.html#scroll-search-results).

Also I advise to enable **discussions** section like in MeiliSearch project (https://github.com/meilisearch/MeiliSearch/discussions) for questions like this.

## Expected Behavior

Any option to backup all cluster data.

**Comment by kishorenc** [comment]
👋 @v-byte-cpu 

The export end-point exports all the documents in a collection in one go. Do you have a specific reason for wanting a scroll parameter here? These documents can be imported back via the `/import` end-point later on.

While we also run periodic snapshots of the raft cluster state+data, we don't have a way to trigger an on-demand snapshot via API yet. For now, you can back-up the `state` sub-directory inside the Typesense data directory. To restore, you have to start Typesense as a **single node cluster** by pointing it against a `data` directory containing the `state` sub-directory backed up earlier. Once that single leader node is up successfully, you can add other follower nodes by updating the `nodes` file.

> Also I advise to enable discussions section

Thanks for the feedback. Feel free to open Github issues for now -- I will just label them as questions and we can continue the discussion.

**Comment by v-byte-cpu** [comment]
> Do you have a specific reason for wanting a scroll parameter here?
With large datasets it seems quite reasonable to export them in chunks.

**Comment by kishorenc** [comment]
Got it. I think for larger datasets, a full snapshot is probably better. I will prioritise an end-point that can be called to trigger a snapshot (snapshots already happen every hour). Would it be okay if there was a snapshot directory available that you can then safely copy to S3 or some other blob storage?

**Comment by v-byte-cpu** [comment]
Yes, sure.

**Comment by kishorenc** [comment]
@v-byte-cpu I just noticed your updated comment. 

> The only thing I miss that stop me from switching to typesense is sharding support. 

Can you please elaborate on this?

**Comment by v-byte-cpu** [comment]
Hi @kishorenc, my dataset is going to expand by 7 million items each year. So I would just like to add more machines to my existing setup instead of vertical scaling. You can read brilliant article [Understanding Sharding in Elasticsearch](https://codingexplained.com/coding/elasticsearch/understanding-sharding-in-elasticsearch).

Also I can create golang client library for typesense API if you are interested.

**Comment by kishorenc** [comment]
Thanks for the clarification. I'm familiar with ES -- just wanted to confirm that it was about horizontal scalability. At the moment, Typesense is focussed on use cases that are in the 100M item range or below. It's a trade-off choosing to focus first on that since anyway Typesense index is in-memory and that puts some constraints on the dataset you can hold without too much $$$.

> Also I can create golang client library for typesense API if you are interested.

Thanks for the offer -- I will really appreciate that. I actually have a bare bones skeleton I started working on a year or so ago. I will polish that up and put it on a separate repo so that can take a look and maybe use it as a starting point. This way the design will also be similar to our other clients.

**Comment by v-byte-cpu** [comment]
Ok, I will start developing it. Can I contact you in any chat platform in case of any questions related to typesense development ? Gitter, Matrix, Wire, xmpp etc.

**Comment by kishorenc** [comment]
Look forward to it. I will clean up the existing go client in a couple of days and update this thread. I'm also close to wrapping up the on demand snapshot API too.

**Comment by v-byte-cpu** [comment]
@kishorenc I am almost done with go client library for typesense 0.17 API. I'll wrap it up and release it in the next few days.

**Comment by kishorenc** [comment]
Wow, excellent. Did you use any of our existing clients as reference? Perhaps this is already so, but my only suggestion would be to follow a similar interface where possible with the other language clients, especially the structure of the ApiCall class (e.g how health-checks and retries are handled) and how the clients generally just pass on parameters to the server and let the server do most of the validations. This will help us make updates to the clients in future.

**Comment by v-byte-cpu** [comment]
Yes, sure. I use python client interface as reference.

**Comment by kishorenc** [comment]
Fantastic ❤️ If you don't mind, I can create a new repository under the Typesense Github org and grant you access to that. We can then start promoting it as an official library and maintain it with your help.

**Comment by v-byte-cpu** [comment]
It is a great idea :rocket: ! Sorry for the late response. I think it is better just to transfer my repo to typesense namespace. I open-sourced it today here: https://github.com/v-byte-cpu/typesense-go. It is still work in progress but there's not much left. You can track current status of high-level client implementation in this task: https://github.com/v-byte-cpu/typesense-go/issues/4. Low-level client is automatically generated from OpenAPI spec file created especially for Typesense 0.17 version :vulcan_salute:. Later I will update README with documentation, right now you can read unit tests code for usage examples. Finally, I will cover all library with integration tests.
P.S. I apply TDD :)

**Comment by jasonbosco** [comment]
@v-byte-cpu Great work and progress!! 

re: transferring repos, in the past I've run into issues with transferring repos between github accounts / orgs if the owner is not an admin part of both orgs. Even adding a person as an admin to a single repo didn't seem to help. The best way I've found to do this, has been to create a new repo under the typesense org, give you access to it and then you'll be able to add this new repo as a remote to your local git repo and push your code to this repo. Then we can add a message to the README file in your repo pointing people to the repo in the typesense org. This is what we ended up doing for the PHP client for example: https://github.com/devloopsnet/typesense-php

Let me know if that sounds good and I can create a repo and give you access to it.

**Comment by v-byte-cpu** [comment]
@jasonbosco yes, it sounds good !

**Comment by jasonbosco** [comment]
Great! I just sent you an invite. You should be able to see it here: https://github.com/typesense/typesense-go/invitations

**Comment by v-byte-cpu** [comment]
I pushed latest master to this repo. Could you please enable kanban dev board like this one https://github.com/v-byte-cpu/typesense-go/projects/1 (or grant me access to create them) ?. It is convenient tool to track progress and relevant tasks.

Also it is necessary to enable drone.io CI builds and renovate-bot for new repo.

**Comment by jasonbosco** [comment]
@v-byte-cpu I've set you as admin on the repo, so you should be able to setup CI now. I've also enabled projects.

**Comment by v-byte-cpu** [comment]
@jasonbosco Thank you !

**Comment by v-byte-cpu** [comment]
@kishorenc @jasonbosco Unfortunately, I ran into some trouble to configure renovate-bot etc, because enabling github apps should be done on organization level. I created chat on gitter to discuss all issues to avoid spamming on this thread [![Gitter](https://badges.gitter.im/typesense-go/community.svg)](https://gitter.im/typesense-go/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by jasonbosco** [comment]
@v-byte-cpu I know this thread evolved into discussing other topics, but coming back to your original ask about doing backups, we just released v0.18.0 with the ability to trigger on-demand snapshots: https://github.com/typesense/typesense/releases/tag/v0.18.0.

More details here: https://typesense.org/docs/0.18.0/api/#cluster-operations-snapshot

**Comment by v-byte-cpu** [comment]
It is great !

**Comment by panoet** [comment]
> @v-byte-cpu I know this thread evolved into discussing other topics, but coming back to your original ask about doing backups, we just released v0.18.0 with the ability to trigger on-demand snapshots, that can be used for backups: https://github.com/typesense/typesense/releases/tag/v0.18.0.
> 
> More details here: https://typesense.org/docs/0.18.0/api/#cluster-operations-snapshot

I know this is quite old thread. But I enjoyed your conversation :D

Anyway, I think it will be useful if we can export our documents in pieces. In my case, I want to export all data and put it to another database. For 1 million rows, I think its better to export it in chunks.
