### ISSUE TITLE
Does typesense have a in-memory cache system for frequent search ?

### ISSUE THREAD

**Issue by microSoftware** [typesense/typesense#1535]
If some search are frequently search, does typesense have some kind of in-memory cache system to make it more efficient/faster for subsequent seach queries ?

**Comment by kishorenc** [comment]
Yes, you can send the `use_cache: true` parameter during search to make use of a query cache. See: https://typesense.org/docs/0.25.2/api/search.html#caching-parameters

**Comment by microSoftware** [comment]
@kishorenc exactly what i was looking for. Thanks
