### ISSUE TITLE
Parameter `pinned_hits` is malformed

### ISSUE THREAD

**Issue by axionos** [typesense/typesense#154]
## Description

I'm unable to use data id that looks like 'http://data.id' for the pinned_hits and am getting below error.

UnhandledPromiseRejectionWarning: Error: Request failed with HTTP code 400 | Server said: Parameter `pinned_hits` is malformed.

## Steps to reproduce

Use pinned_hits field with id starting with 'http://' like below:

pinned_hits: 'http://data.123.id:1, http://data.456.id:2'

## Expected Behavior

Return the pinned data on the top of the returned list

## Actual Behavior

Getting this error: UnhandledPromiseRejectionWarning: Error: Request failed with HTTP code 400 | Server said: Parameter `pinned_hits` is malformed.

## Metadata

**Typsense Version**: 0.17.0.rc4

**OS**:  mac

**Comment by axionos** [comment]
This issue has been fixed with `typesense/typesense:0.18.0.rc1` .
Thank you.

**Comment by jasonbosco** [comment]
Just released v0.18.0 with this fix: https://github.com/typesense/typesense/releases/tag/v0.18.0.
