### ISSUE TITLE
Excluding results that contain a certain keyword

### ISSUE THREAD

**Issue by LaundroMat** [typesense/typesense#155]
Is there a way to filter out search results when they contain a specific word (in any field)? 

I would not expect typesense to impose a specific query format for excluding a word, but does the API provide a way to exclude results containing a specific word?

**Comment by LaundroMat** [comment]
> Is there a way to filter out search results when they contain a specific word (in any field)?
> 
> I'm not expecting typesense to expect a specific query format for excluding a word, but does the API provide a way to do so?

**Comment by kishorenc** [comment]
@LaundroMat There isn't a way to do this at the moment but this is on my radar. Are you looking to do with only with the query (`q=`) fields or for filtering as well?

**Comment by LaundroMat** [comment]
I'd prefer excluding by filtering, as then I'd easily be able to give the user more than one way of excluding results.

**Comment by kishorenc** [comment]
One way to achieve this is by introducing `-` as an exclusion operator. So, something like `color: -blue` would match records which are not blue. Then you can include some colors and exclude others via `colors: [-blue, red, orange]`. For a phrase, might have to prefix `-` before each token, so `color: -dark -green`. That's my initial take, but have to see how it evolves during implementation.

**Comment by v-byte-cpu** [comment]
what if some token contains `-` symbol ?

**Comment by kishorenc** [comment]
Good point, a real word like `-something` might get excluded. It will be a problem only for words that start with hyphen, which is rare, but still should be supported by allowing a backslash escaping like `\-something`.

**Comment by LaundroMat** [comment]
I've given it some more thought, and both ways (through filtering and through the query) would in fact have a lot of value. The query part would release the developer from the burden of translating the query to a filter themselves. But finegrained search (as in the example you're giving with the colours) is very valuable as well.

You decide which you go with first :-)

**Comment by kishorenc** [comment]
Implemented excluding query tokens via the "-" prefix, e.g. query "django -python" will match all document that contain the word "django" but not "python".

RC build: [Download](https://dl.typesense.org/releases/0.18.0.rc5/typesense-server-0.18.0.rc5-linux-amd64.tar.gz)

**Comment by LaundroMat** [comment]
Damn guys, you are fast 👍 I'll only be able to check on your changes in a few weeks, but already looking forward to it :)

**Comment by kishorenc** [comment]
No worries. 👍

**Comment by jasonbosco** [comment]
Just released v0.18.0 with support for keyword negation: https://github.com/typesense/typesense/releases/tag/v0.18.0
