### ISSUE TITLE
Possibility to filter with OR instead of AND?

### ISSUE THREAD

**Issue by LaundroMat** [typesense/typesense#158]
## Description

I have an index where a particular date field (`end_date`, an int64 timestamp) can be empty.

## Expected Behavior
I would like to be able to filter a search by ORing different conditions. In my case, return all results where  `end_date` is later than today OR `end_date` is None.

**Comment by kishorenc** [comment]
@LaundroMat 👋 

This is not possible at the moment, but should be able to add support for a syntax like:

`ts: [>1606311403, 0]` 

This will translate to: "Filter by timestamps that are greater than 1606311403 OR equal to 0".

**Comment by kishorenc** [comment]
I've a build for you try this against :)

https://dl.typesense.org/releases/0.18.0.rc4/typesense-server-0.18.0.rc4-linux-amd64.tar.gz

You can also check against this Docker image: `typesense/typesense:0.18.0.rc4`

**Comment by LaundroMat** [comment]
Thanks for the very quick reaction! I don't have a lot of time to set things up right now, so I'll report back to you later. I just wanted to say thanks already :)

**Comment by jasonbosco** [comment]
Just released v0.18.0 with this feature: https://github.com/typesense/typesense/releases/tag/v0.18.0
