### ISSUE TITLE
Problem encoding character

### ISSUE THREAD

**Issue by nathan-cuvellier** [typesense/typesense#159]
Hello,
I have a problem with encoding character, as you can see in the photo below.
Is it possible to specify something like UTF8?

![problem](https://user-images.githubusercontent.com/25644340/100321021-5b7cd280-2fc2-11eb-9b79-c21e781388f6.png)

version typesense: 0.17

Thanks !

**Comment by kishorenc** [comment]
👋 Can you please show me how the title field looks when you load the source file in a text editor? It seems to be like there are three invalid or non-unicode characters next to "à".

**Comment by nathan-cuvellier** [comment]
_For information, the screenshot is from Postman._

I get the title "Mise à jour Timy depuis PC" from database in UTF8 and it **becomes** "Mise \u00e0 jour Timy depuis PC" in typesense

The problem is the same with all accents: like **ê** which becomes **^e** in my browser.
The data in the document object is correct as you can see, the problem is only with the highlights object
I got around the problem with the php [htmlentities](https://www.php.net/manual/en/function.htmlentities.php) function

`htmlentities('Mise à jour Timy depuis PC'); // Mise &agrave; jour Timy depuis PC `

**Comment by kishorenc** [comment]
@nathan-cuvellier Thanks for the additional details. I've fixed this issue: https://github.com/typesense/typesense/commit/7ece846ccf0ce4915e0fd7cd1958d1f5a94369ad

Can you please tell me whether you run Typesense from Docker, Mac or Linux binary? I can cut a pre-release build with this fix for you.

**Comment by nathan-cuvellier** [comment]
Thanks a lot for this quick fix, I'm running typesense from Linux binary.
I can test the pre-release build with pleasure !
I return to work in 4 days, I will be able to test that the 2020-12-2

**Comment by nathan-cuvellier** [comment]
Where can I download the pre-release build?

**Comment by kishorenc** [comment]
Here you go: [Download](https://dl.typesense.org/releases/0.18.0.rc5/typesense-server-0.18.0.rc5-linux-amd64.tar.gz)

**Comment by andrewjwu** [comment]
@kishorenc I'm also experiencing this issue with the macOS binary. Is there an ETA for this fix or would it be possible to get a pre-release build? Thanks!

**Comment by kishorenc** [comment]
The macOS pre-release binary is here: [Download](https://dl.typesense.org/releases/0.18.0.rc5/typesense-server-0.18.0.rc5-darwin-amd64.tar.gz)

**Comment by jasonbosco** [comment]
Just released v0.18.0 with this fix: https://github.com/typesense/typesense/releases/tag/v0.18.0
