### ISSUE TITLE
Able to disable synonym search in the query

### ISSUE THREAD

**Issue by Hypnobrew** [typesense/typesense#1594]
## Description
Having synonyms setup in Typesense, we get matches on both these when searching for a matching search query as expected.
We have the need for some queries to override this to only return matches for the specific term and not the synonym.

## Steps to reproduce
Setup a synonym X/Y.

Search for X and it will yield results for both X and Y.

## Expected Behavior

Search for X with a parameter i.e. `ignore_synonyms: true` will yield results only for X.

## Metadata

**Typesense Version**: 0.26

**OS**: Cloud

**Comment by stargazer33** [comment]
i can imagine to search for "X" (put the word in quotes) to yield results only for X.
Might be similar to #1880

**Comment by jasonbosco** [comment]
This is now possible in v27.1 of Typesense Server. The parameter is called `enable_synonyms`, documented under this table: https://typesense.org/docs/27.1/api/search.html#ranking-and-sorting-parameters
