### ISSUE TITLE
Search request with large number for max_facet_values does not terminate

### ISSUE THREAD

**Issue by sb-relaxt-at** [typesense/typesense#1599]
## Description

A search request specifying a large number for max_facet_values does not terminate.

## Steps to reproduce

We want to query for all facets, therefore we set max_facet_values to a large value. In a former version (0.20) we specified 2^32-1 as the field is represented by a size_t which should be at least a 32 bit unsigned integer. This has worked in 0.20 but stopped working sometimes as  in 0.25.2 the request does not terminate.

`curl "http://typesense-server/collections/testrealties_de/documents/search?q=test&max_facet_values=4294967295"`

From my limited testing it seems as if it is a signed int now, so 2^32/2-1 is the largest value working properly.

## Expected Behavior

The request should terminate properly or fail with a meaningful message if the value for max_facet_values is invalid.

## Actual Behavior

The request does not terminate.

## Metadata

**Typesense Version**: 0.25.2

**Comment by kishorenc** [comment]
Thank you for reporting this issue. This has been fixed in recent 0.26 RC builds, which will be released as GA soon.

**Comment by sb-relaxt-at** [comment]
Thank you very much!
