### ISSUE TITLE
Always match full words

### ISSUE THREAD

**Issue by anothergituser** [typesense/typesense#160]
Hello, 
How can i make it to always search full words? If the query is "car" i don't want to match "scars". I tried typo_tokens_threshold=0 and drop_tokens_threshold=0 to no effect.
Thanks.

**Comment by kishorenc** [comment]
👋 You also need to set `num_typos=0` so that spelling correction does not happen.

**Comment by anothergituser** [comment]
Can confirm it works, thanks!

**Comment by kishorenc** [comment]
On second thoughts, it might be a good idea to ensure that setting `typo_tokens_threshold=0` is sufficient to ensure this. Can you please tell me an example query and value against which this behavior is triggered? I could not reproduce it in a quick example I tried locally with.
