### ISSUE TITLE
Apply Override Selectively to a Query in real time?

### ISSUE THREAD

**Issue by atif089** [typesense/typesense#1605]
## Description

Is it possible to selectively apply an override for A/B Testing? Let's say I have 2 curations `cur-base` and `cur-var`. My variant 0 users should see all the results with `cur-base` applied, while variant 1 users should see `cur-var` applied.

**Comment by jasonbosco** [comment]
In the most recent RC build of Typesense, you can add tags to override rules: https://github.com/typesense/typesense/issues/1464

Then at search time, you can selectively trigger a curation rule(s) using the tag, as a search parameter.
