### ISSUE TITLE
Add support for combined image and text embeddings using CLIP

### ISSUE THREAD

**Issue by prmaxim** [typesense/typesense#1607]
## Description

We use CLIP for product recommendations in e-commerce. By generating two vectors (image + name) and then adding the concatenated result to the TS embedding field, we get more accurate recommendations than with image embedding alone.

The CLIP API allows requests for multiple fields and returns an array of embeddings back:
`[[image embedding], [text embedding]]`

TS now natively supports CLIP for image embeddings, but doesn't allow to create embeddings from multiple fields.

Note: the issue #1291 looks broader and covers this specific issue of combining CLIP embeddings.

## Steps to reproduce

Create a collection with an image and text fields:

```json
{
  "name": "Images",
  "fields": [
    {
      "name": "name",
      "type": "string"
    },
    {
      "name": "image",
      "type": "image",
      "store": false
    },
    {
      "name": "embedding",
      "type": "float[]",
      "embed": {
        "from": [
          "image",
          "name"
        ],
        "model_config": {
          "model_name": "ts/clip-vit-b-p32"
        }
      }
    }
  ]
}
```

## Actual Behavior

Error: Only one field can be used in the `embed.from` property of an embed field when embedding from an image field.

## Metadata

**Typesense Version**: 0.26.0.rc58

**Comment by prmaxim** [comment]
This feature would be incredibly useful for our work, allowing us to handle everything within Typesense without the need for additional processing. Thank you for considering it!

**Comment by kishorenc** [comment]
@prmaxim 

How do you combine the separate vectors produced for the image and text fields?

**Comment by kishorenc** [comment]
How do you query this 1024 dimensional concatenated embedding with a 512-dimensional query embedding? What will be the value of the remaining half of the query vector?

**Comment by prmaxim** [comment]
At this stage, all TS documents have 1024-dimensional embeddings. We then query for similar documents using document ID:
```json
{
"q": "*",
"vector_query": "embedding:([], id: foobar)",
"sort_by": "_vector_distance:asc, newest:desc"
}

**Comment by kishorenc** [comment]
Got it. Have you tried doing the averaging of the image and text vectors? Supporting averaging would help us support both text search queries as well as document ID based similarity search as you have outlined above. With the concatenate approach, we can't support query text because we will only have half the embedding vector. If average works equally well, we can implement that first.

**Comment by prmaxim** [comment]
We haven’t tried the averaging approach yet since we started with concatenating and it worked well. However, I’m happy to test it within the next day to confirm. So far, we keep the CLIP embeddings separate, which allows us to reindex the collection and compare results. I’ll post an update here once it’s done. Thank you!

**Comment by prmaxim** [comment]
@kishorenc We’ve tested averaging the image and text vectors, and the results are very similar. So, we’re all for using this approach in TS by default. Thank you!

**Comment by kishorenc** [comment]
Ok that sounds good and makes it easier to support both query and document based searches. We will kick-off the work shortly and will post an update on this thread.

**Comment by kishorenc** [comment]
This feature is available in `27.0.rc25`. 

In the following configuration, the `image` and `name` embedding will be automatically averaged as a single vector during indexing.

Please give it a go and give us feedback.

```
{
  "name": "images",
  "fields": [
    {
      "name": "name",
      "type": "string"
    },
    {
      "name": "image",
      "type": "image",
      "store": false
    },
    {
      "name": "embedding",
      "type": "float[]",
      "embed": {
        "from": [
          "image",
          "name"
        ],
        "model_config": {
          "model_name": "ts/clip-vit-b-p32"
        }
      }
    }
  ]
}
```

**Comment by prmaxim** [comment]
@kishorenc We tested it, and CLIP embeddings are now working for multiple fields 🎉 Thank you!

Could you please clarify a couple of questions:
1. Will this configuration create embeddings for every document update, even if the 'from' field values haven't changed? It feels that way based on the logs.
2. It seems that it's also possible to create embeddings from more than two 'from' fields, like [image, text, text]? Is this correct?

**Comment by ozanarmagan** [comment]
@prmaxim 

1. This configuration will re-create embeddings only if any value in `embed.from` fields updated. Otherwise embedding generation won't happen.
2. Yes, it is possible to have more than two fields in `embed.from` now.

**Comment by prmaxim** [comment]
Thanks @ozanarmagan That sounds great! The only concern is whether the embeddings generation will occur again when the image value isn’t stored in the collection (`store: false`). We observe similar time and CPU usage when updating the same document with identical image and name values. Could you please clarify this for us?

**Comment by kishorenc** [comment]
@prmaxim 

With `store: false`, it's not possible for us to retrieve and compare the field value for the image, so we will have to re-generate embedding.

**Comment by ozanarmagan** [comment]
@prmaxim Maybe you can try `index:false` instead of `store:false`, this wil prevent creating an index for the image field, but will persist it on the disk.
