### ISSUE TITLE
Ambiguous error (Field `title` is already part of the schema)

### ISSUE THREAD

**Issue by ybirader** [typesense/typesense#1616]
## Description

I have a Typesense server up and running and it seems to be working correctly.

However, I get this warning in the logs: `Request failed with HTTP code 400 | Server said: Field `title` is already part of the schema: To change this field, drop it first before adding it back to the schema.`

What does this mean?

My schema defines a field called `title`- I'm not sure what this warning is referring to.

**Comment by kishorenc** [comment]
Somehow the server is being sent an alter request: https://typesense.org/docs/0.25.2/api/collections.html#update-or-alter-a-collection

**Comment by ybirader** [comment]
Thanks- I've found the bug. I was accidentally calling update.
