### ISSUE TITLE
[Silly question] How does search speed scale with CPUs for a single query

### ISSUE THREAD

**Issue by aaroncueckermann** [typesense/typesense#1631]
## Description

Sorry but I couldn't find an explicit answer to this in the docs so posting here.

For a single search query (not concurrent queries) will more vCPUs make the query faster i.e. does query speed scale ~linearly with the number of vCPUs. 

Are there other ways I can make my searches faster given my context?

## Context

We have a low query volume but user expectations of very fast response time, we have low 10s of millions of documents with ~8 query_by fields and pretty gnarly dynamic filtering conditions (leads to slow response time [1-2s]).

**Comment by kishorenc** [comment]
@aaroncueckermann 

We've been spending a lot of time on our query planner recently to handle single-search query performance. Some of these changes will be available in the upcoming release. Please email us on contact@typesense.org with details and we can discuss how we can help.
