### ISSUE TITLE
Synonyms like k8s <-> kubernetes aren't working with enabled stemming

### ISSUE THREAD

**Issue by b0g3r** [typesense/typesense#1635]
## Steps to reproduce

https://gist.github.com/b0g3r/63087b32df11f8c14ab21159be577eaf

## Expected Behavior

Both examples should return k8s and kubernetes documents

## Metadata

**Typesense Version**: 0.26.0.rc65

**Comment by ozanarmagan** [comment]
@b0g3r Fixed with #1638

**Comment by b0g3r** [comment]
@ozanarmagan great news! Do you have available rc build with the fix?
