### ISSUE TITLE
Search with start_with only

### ISSUE THREAD

**Issue by piolet** [typesense/typesense#164]
## Description

Do you provide an option to force queries to return only results whose **query_by** start with the **q** parameter ?
To avoid client-side filtering.

Currently, i add a field (with first character of an other field) in my schema, with a facet, but it only partially does the job.

thx

**Comment by kishorenc** [comment]
Will `q` contain multiple words? There is the `?prefix=true` option which returns results that match the prefix but it only matches the prefix for the last word if there are multiple words in the query. So, when you search for `?q=red+sh` it will match `red shoes`.

**Comment by piolet** [comment]
This may be enough. Mixed with the `num-typos` parameter at 0 and a filtering of the result on my side.
i'll try this soon ;)

Thanx
