### ISSUE TITLE
[Joins] join with no filter results in the error "Filter value cannot be empty".

### ISSUE THREAD

**Issue by webcredo** [typesense/typesense#1642]
Attempting a join without specifying a filter in way you described like `$Join_Collection_Name(id: *)` results in the error "Filter value cannot be empty".

With filter like `$Join_Collection_Name(id:=123)` it works me correclty

**Typesense Version**:
0.26.0.rc70

**Comment by kishorenc** [comment]
@webcredo 

v26 has now been released. Please see this example, which works for me: https://typesense.org/docs/26.0/api/joins.html#one-to-one-relation

Can you post a full example that showcases the issue that we can run and check?
