### ISSUE TITLE
Adding support to load a conversation from an external system (beyond the TTL) for RAG

### ISSUE THREAD

**Issue by ashwanthkumar** [typesense/typesense#1645]
## Description

Following up from https://twitter.com/kishorelive/status/1775001870295019603, please consider adding support for ingesting / loading conversations into Typesense from an external store. So we could load up the data into typesense if the user wants to continue the historical chat from beyond the TTL value.

## Expected Behavior

APIs to support ingesting conversations into Typesense.

## Metadata

**Typesense Version**: 0.26

**OS**: All?

**Comment by kishorenc** [comment]
In v27, we have refactoring the RAG API significantly. You can now use a regular Typesense collection as the [backing store](https://typesense.org/docs/27.0/api/conversational-search-rag.html#create-a-conversation-history-collection) for RAG conversations. This way, you have full access to CRUD operations.
