### ISSUE TITLE
RAM spike when selecting final page

### ISSUE THREAD

**Issue by aaroncueckermann** [typesense/typesense#1649]
## Description

RAM spike when selecting the last page in a collection and took down typesense server.

## Expected Behavior

No RAM spike

## Metadata

<img width="553" alt="image" src="https://github.com/typesense/typesense/assets/71329703/08e6b857-1d64-475d-ace7-a01c19731854">

**Typesense Version**: Typesense v0.26.0.rc69

**OS**: TypeSense Cloud

**Comment by kishorenc** [comment]
Typesense as a search engine is most efficient for searching the top results. Deep pagination requires memory and is not a recommended use case for Typesense. You can use the `limit_hits` parameter to put a ceiling on the maximum number of results that can be fetched from a collection.
