### ISSUE TITLE
Trying to understand inconsistent disk usage between cluster nodes

### ISSUE THREAD

**Issue by psaxton** [typesense/typesense#1666]
## Description

We keep having Typesense containers crashing because they run out of volume space.

We have a 3 instance cluster running from official Docker images. When a container crashes, it writes logs similar to _"E20240411 20:24:56.555313   334 collection.cpp:544] Write to disk failed. Will restore old document"_ at a rate of about 1000 times per second. Before it crashes, it is writing logs similar to _"E20240411 20:24:51.221179   262 raft_server.cpp:644] 3553 lagging entries > healthy write lag of 500"_ at a rate of about 1 log per second where the count of lagging entries is generally decreasing before the crash. The only way to get the instance to rejoin the cluster is to wipe the persistent volume and have it rejoin from scratch.
Each instance is given a 10GB persistent volume. We only have about 600k documents in a single collection that is refreshed using Typesense-docsearch-scraper. The scraper creates a new collection populates it, switches the alias and deletes the old collection.
Disk usage between the nodes varies greatly.

typesense-0:
```bash
typesense-0:/$ cd /usr/share/typesense/data
typesense-0:/usr/share/typesense/data$ df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvdaa      9.8G  1.1G  8.8G  11% /usr/share/typesense/data
typesense-0:/usr/share/typesense/data$ du -h --max-depth=2
4.0K    ./models
4.0K    ./meta/archive
5.2M    ./meta
7.8M    ./state/log
8.0K    ./state/meta
1000M   ./state/snapshot
1007M   ./state
100K    ./db/archive
17M     ./db
16K     ./lost+found
1.1G    .
```

typesense-1:
```bash
typesense-1:/$ cd /usr/share/typesense/data
typesense-1:/usr/share/typesense/data$ df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme2n1    9.8G  5.7G  4.1G  59% /usr/share/typesense/data
typesense-1:/usr/share/typesense/data$ du -h --max-depth=2
4.0K    ./models
4.0K    ./meta/archive
4.3M    ./meta
8.0K    ./state/meta
5.7G    ./state/snapshot
2.7M    ./state/log
5.7G    ./state
8.0K    ./db/archive
8.6M    ./db
16K     ./lost+found
5.7G    .
```

typesense-2:
```bash
typesense-2:/$ cd /usr/share/typesense/data
typesense-2:/usr/share/typesense/data$ df -h .
/dev/nvme3n1    9.8G  7.6G  2.3G  78% /usr/share/typesense/data
typesense-2:/usr/share/typesense/data$ du -h --max-depth=2
2.6M    ./db/archive
6.2G    ./db
4.0K    ./meta/archive
4.2M    ./meta
16K     ./lost+found
4.0K    ./models
196K    ./state/snapshot
8.0K    ./state/meta
1.4G    ./state/log
1.4G    ./state
7.6G    .
```

Is it normal for different nodes in the same cluster to have such drastically different disk usage patterns?

## Metadata

**Typesense Version**: 0.25.2
**OS**: Docker image on Kubernetes (EKS)

**Comment by jasonbosco** [comment]
We've improved disk usage in v26.0, for this specific write pattern of creating new timestamped collections and deleting the old one, like how the scraper does. 

Could you try upgrading to it, and then setting `db-compaction-interval = 21600` as a Typesense server parameter, to see if that helps?

**Comment by psaxton** [comment]
@jasonbosco Thanks for the quick response. I've updated to Typesense 26.0 and included the `--db-compaction-interval=21600` in the arguments. Disk usage has held around 8-9GB since then but that seems quite high for the number of documents. It could just be leftover cruft from 0.25.2. I've wiped the persistent storage, restarted the cluster and started a fresh index and will let it stew over the weekend to see what happens.

**Comment by psaxton** [comment]
After rebuilding all the data under 26.0 the disk usage under _/usr/share/typesense/data_ is much more steady and consistent across cluster nodes. We are noticing that one node seems to be keeping everything in _./db_ while the other 2 appear to be moving data over to _./state/snapshot_ despite all containers being started with identical parameters. Any ideas why that may be?

typesense-0:
```bash
typesense-0:/$ cd /usr/share/typesense/data
typesense-0:/usr/share/typesense/data$ df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme2n1    9.8G  1.5G  8.3G  16% /usr/share/typesense/data
typesense-0:/usr/share/typesense/data$ du -h --max-depth=2
4.0K    ./models
236K    ./state/log
1.5G    ./state/snapshot
8.0K    ./state/meta
1.5G    ./state
16K     ./lost+found
3.9M    ./db/archive
30M     ./db
4.0K    ./meta/archive
5.3M    ./meta
1.5G    .
```

typesense-1:
```bash
typesense-1:/$ cd /usr/share/typesense/data
typesense-1:/usr/share/typesense/data$ df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme4n1    9.8G  1.6G  8.2G  16% /usr/share/typesense/data
typesense-1:/usr/share/typesense/data$ du -h --max-depth=2
236K    ./state/log
8.0K    ./state/meta
1.6G    ./state/snapshot
1.6G    ./state
4.0K    ./models
16K     ./lost+found
3.9M    ./db/archive
30M     ./db
4.0K    ./meta/archive
5.3M    ./meta
1.6G    .
```

typesense-2:
```bash
typesense-2:/$ cd /usr/share/typesense/data
typesense-2:/usr/share/typesense/data$ df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme3n1    9.8G  1.5G  8.3G  16% /usr/share/typesense/data
typesense-2:/usr/share/typesense/data$ du -h --max-depth=2
16K     ./lost+found
3.9M    ./db/archive
1.5G    ./db
4.0K    ./models
4.0K    ./meta/archive
5.3M    ./meta
236K    ./state/log
680K    ./state/snapshot
8.0K    ./state/meta
928K    ./state
1.5G    .
```

**Comment by kishorenc** [comment]
Can you tell me what type of disk you are using for the data directory?

When a write arrives, it is written to the raft log and also written to the store in `db` directory. Every 1 hour, a snapshot happens where the contents of the `db` directory is __hard linked__ within the `state/snapshot` directory (hard linking is like soft link but happens at the inode level so that data is not duplicated). When Typesense is restarted, we replace the `db` directory with the contents of the db from `state/snapshot` . You can confirm this behavior in a Typesense server on your localhost.

So ideally, the `db` directory should be more or less have the same data in `state/snapshot` unless a lot of writes have happened before a snapshot occurs.

**Comment by psaxton** [comment]
The data directory is a persistent volume provided by AWS EBS GP3 block
store.

I will take a deeper dive into what files/inodes are actually in each
directory on each node as well as research what `du` is actually telling me.

**Comment by psaxton** [comment]
It seems that updating to 26.0 has resolved the disk use issues. I don't think the discrepancies I'm seeing with `du` at this point are harmful. Thank you very much for your assistance. Closing issue.
