### ISSUE TITLE
Collection schema cannot contain a field with name id. Ignoring field

### ISSUE THREAD

**Issue by abcdan** [typesense/typesense#1668]
## Description
When creating a collection that has `id`, `id_search`, `created_at` (and a few other, irrelevant fields like firstname/lastname/etc). we're getting an error stating that we cannot have a field with the name id.

When I change `id_search` to for example `searchable_id` it lets me do it. 

_Note: we use PHP and Typesense PHP but the error comes from the Typesense server as the SDK contains no exact reference to this error_

## Steps to reproduce
```php
    'fields'                => [
        [
            'name' => 'id',
            'type' => 'string',
        ],
        [
            'name' => 'searchable_id',
            'type' => 'string',
            'optional' => true,
        ],

        [
            'name' => 'created_at',
            'type' => 'int64',
        ],
    ],
```

## Expected Behavior
I expect it to be possible to create a field containing `id` in the beginning.

## Actual Behavior
It returns the following error
```
Collection schema cannot contain a field with name id. Ignoring field
```
## Metadata
We use Laravel Scout and have an import script that manually makes the collection like this:

```php
       $modelSettings    = config('scout.typesense.model-settings.' . $modelClass);
        $collectionSchema = $modelSettings['collection-schema'];
        $collectionName   = $modelSettings['collection_name'] . 's';

        $collections = $this->client->collections;
        if (!in_array($collectionName, array_column($collections->retrieve(), 'name'))) {
            $collectionSchema['name'] = $collectionName;
            $collections->create($collectionSchema);
        }
```

**Typesense Version**:
26.0

**OS**:
Inside of a Docker Container

**Comment by jasonbosco** [comment]
This is an expected error, by design. 

From the docs:

> If the document contains an `id` field of type string, Typesense will use that field as the identifier for the document. Otherwise, Typesense will assign an auto-generated identifier to the document. Since it's a special field, the `id` field is not required to be defined as part of the collection schema.

**Comment by abcdan** [comment]
Interesting, many thanks. One question: I've seen that before. But: why does this not happen when ID is not the beginning, as per searchable_id?

**Comment by jasonbosco** [comment]
This is because only a field called `id` specifically is a special field. Other fields that end with `_id` are not automatically used as an id field and don't have any specific meaning.

**Comment by abcdan** [comment]
Alright, so "id_search" will always give this error and "search_id" won't. Thanks!

**Comment by jasonbosco** [comment]
No, a field named `id_search` should not throw any errors in the logs, when mentioned in the schema.

**Comment by abcdan** [comment]
> No, a field named `id_search` should not throw any errors in the logs, when mentioned in the schema.

Interesting, but on 26.0 when I use id_search it gives an error and searchable_id for example does not.

**Comment by jasonbosco** [comment]
Hmm, I don't see the same issue. 

I used [this gist](https://gist.github.com/jasonbosco/7c3432713216c378472f13e72246f46b#file-run-typesense-sh) to run Typesense. Then created a collection using a field called `id_search` and no errors were logged. Then created a field called `id` and the error was logged. 

![Screenshot 2024-04-16 at 9 45 44 AM](https://github.com/typesense/typesense/assets/458383/c70b7ad6-fcf0-4ac7-b2c7-25d778297281)
