### ISSUE TITLE
Constraint enforcements on JOINed references should be optional

### ISSUE THREAD

**Issue by onhate** [typesense/typesense#1675]
## Description

I would like to bring a discussion on the topic of how JOINS work now.

As of the current implementation Typesense is enforcing constraints validations, for example, if you index a ticket that has a field agentId that references an agents collection Typesense will reject the indexing of tickets whose agentId value does not exists on the agents collection.

I understand the benefits of this approach, but thinking as Typesense not being the source of true and it in most cases being a source that synced from other database it adds complexity to the syncing of data (specially batch re-indexes) because now I am forced to first index all the agents and then only being able to index the tickets.

Also, it will not work if you already use NoSql databases that don't have constraint validations and allow you to have things like `ticket.assigee = 'group:XXX'` that does not really refers to an agent...

I'll raise a issue on the repository to continue the discussion, but in my opinion there would be an option to allow "loose constraints" on references.

**Comment by kishorenc** [comment]
We could add an optional property that can be enabled for the reference field, e.g. `async_reference: true`. When indexing documents of any collection we'll check if it's being referenced and whether the field is marked as `async_reference` and the add the references appropriately.

**Comment by onhate** [comment]
and internally it would work as we discussed on slack, creating a placeholder for missing references that later will be updated when the record is inserted in the referred collection? If so, the filed name async_references is very use case specific, a name like `loose` or `no_constraint` would allow better understanding of the feature, wdyt?

**Comment by kishorenc** [comment]
Yes, correct. We will have more details when we get down to the implementation details.

**Comment by dbuedo** [comment]
This option will be very useful for our use case too.

**Comment by happy-san** [comment]
With `28.0.rc4`, a field with `reference` can have an option `async_reference: true`. Enabling this option will help documents to be indexed successfully instead of returning:
```
Reference document having `...` not found in the collection `...`.
```
when the referenced document is not yet indexed.

The resolution of references will happen when the referenced documents get indexed later.

**Comment by onhate** [comment]
Thank you folks, you are the best!
