### ISSUE TITLE
Question: Synonym Support

### ISSUE THREAD

**Issue by cboothe** [typesense/typesense#168]
## Description

RediSearch has support for synonyms on a specific index versus database wide.
https://oss.redislabs.com/redisearch/Synonyms/

Is this something you are looking to add?

**Comment by kishorenc** [comment]
@cboothe 👋 

Yes, almost ready with that. Should be available for testing in the next couple of weeks :)

**Comment by jasonbosco** [comment]
@cboothe We just released v0.18.0 with the synonyms feature: https://github.com/typesense/typesense/releases/tag/v0.18.0
