### ISSUE TITLE
All demo websites are not functional

### ISSUE THREAD

**Issue by shiyanshirani** [typesense/typesense#1680]
## Description
All the demo websites are not functioning in `Reference Implementations` on Typesense's website, search API is giving `401` because `x-typesense-api-key` is not present in headers. 

## Steps to fix
Provide the API key in the headers.

**Comment by jasonbosco** [comment]
Thank you for the heads-up. The demos should be back up now. 

We had a glitch in the underlying infrastructure that's hosting the demos that we've now resolved.
