### ISSUE TITLE
Best practices to truncate a collection

### ISSUE THREAD

**Issue by comichael** [typesense/typesense#1688]
Are there any guidelines / best practices on how to delete a collection with all its contents, with regards to server space?

We have tried to delete the collection and recreate it as a dummy - and call CompactDisk( ), but it doesn't seem to reduce free space on the server.

How are folks actually solving this issue?

**Comment by jasonbosco** [comment]
After deleting the collection via the API, the on-disk contents are compacted every 7 days by default in v26 of Typesense. 

You can either manually trigger DB compaction using [this endpoint](https://typesense.org/docs/26.0/api/cluster-operations.html#compacting-the-on-disk-database) and you want to then trigger [a snapshot](https://typesense.org/docs/26.0/api/cluster-operations.html#create-snapshot-for-backups) (to clear the old DB from previous snapshots). 

Or you can also decrease the default DB compaction interval using the `db-compaction-interval` flag (seconds).

**Comment by comichael** [comment]
Thanks for your quick reply Jason. 

Just tested this: First calling CompactDisk( ), then CreateSnapshot(path)

Before: Disk usage = 5,7 GB
After: Disk usage = 6,2 GB
(Based on metrics.SystemDiskUsedBytes)

I expected that the disk usage would be reduced. 

Not sure what I'm missing. Any explanation / elaboration on this is appreciated.

**Comment by jasonbosco** [comment]
It could be the old snapshots. Could you delete the snapshot directory generated by the create snapshot endpoint, once the snapshot API returns success?
