### ISSUE TITLE
Way to crawl sites and put the received data in the documents?

### ISSUE THREAD

**Issue by geekjr** [typesense/typesense#169]
Is there a way to crawl a site and put the crawled data into documents?

**Comment by jasonbosco** [comment]
If you have a Gastby site, there's a plugin to index site content on build into Typesense: https://github.com/typesense/gatsby-plugin-typesense

I'm planning to extract some of the core logic from that plugin into a generic site crawler shortly: https://github.com/typesense/gatsby-plugin-typesense/issues/5#issuecomment-736946427

**Comment by geekjr** [comment]
OK. Thanks
