### ISSUE TITLE
Search by doc ID in the UI

### ISSUE THREAD

**Issue by FPierre** [typesense/typesense#1692]
## Description

I can't find a way to search for a document by its ID in the search field in the back office. Is it possible to do this?

## Steps to reproduce

![Screenshot from 2024-04-29 08-21-52](https://github.com/typesense/typesense/assets/3307327/e3414954-413e-4bf7-aa5f-3dd188720422)

## Expected Behavior

Returns the document when its ID is given in the search field

## Actual Behavior

No document found

## Metadata

**Typesense Version**: `v0.25.1`, `v0.25.2` and `v26`

**OS**: Linux, Mac

**Comment by jasonbosco** [comment]
The `id` field is not full-text searchable in Typesense. 

You can only filter on it starting v0.25 (which you can do in the Cloud UI using `filter_by=id:123` in the Additional Search Parameters section). 

If you want to do full text search on the ID field, you want to duplicate it into a new field and then set that in query_by.
