### ISSUE TITLE
Docs to install a specific version of typesense

### ISSUE THREAD

**Issue by shiyanshirani** [typesense/typesense#1697]
how to install specific (v.24.1 in my case) version of DEB package on Ubuntu/Debian

**Comment by jasonbosco** [comment]
You can change the version number in the URLs on the [downloads page](https://typesense.org/downloads/) to download older versions.

You want to make sure you use the correct version string listed here: https://typesense.org/docs/#typesense-versions

For eg, it's `0.24.1` and not `24.1`.
