### ISSUE TITLE
WooCommerce connector/integration

### ISSUE THREAD

**Issue by codeagencybe** [typesense/typesense#170]
## Description

Does anybody know of an existing or project in progress for a WooCommerce (Wordpress) connector or integration? 

I'm interested to try Typesense for CMS and ecommerce based setups with Wordpress and WooCommerce. 
I already have googled several hours to find some relevance article or a start but couldn't find anything. 

Any starting point or links to this topic are very much appreciated. 
Thanks so much!

Fabio

**Comment by jasonbosco** [comment]
@codeagencybe We don't have an official WooCommerce integration and I'm not aware of a community one either.

However, I did some quick research on how you'd go about setting this up and I found that WooCommerce gives you a REST API to export data in a JSON format: https://woocommerce.github.io/woocommerce-rest-api-docs/#products

You essentially want to export the data you need through their REST API and then bulk import them into Typesense periodically.

**Comment by codeagencybe** [comment]
@jasonbosco 

Yes I'm aware of the WooCommerce API. But that's not the question or information related to my question. 
My question is about a connector or plugin for WooCommerce that improves the Wordpress search feature with Typesense + brings the faceted search and all goodies from Typesense into Wordpress (and WooCommerce). 

At the moment the closest thing we can find related to search/indexing is with  Elasticsearch or Redisearch where both have solutions readily available for CMS platforms. 
To give you a few ideas:
https://wordpress.org/plugins/elasticpress/
https://wordpress.org/plugins/redisearch/

These plugins both take care of the data sync from the CMS to ElasticSearch/Redis AND improve the frontend UI/UX. 

In terms of Elasticsearch, it works great but it's a huge resource hog because of it's Java dependencies and therefor expensive (machines with minimum 32GB RAM etc...). 
I would like to see something else (and better, more performant) beccomes more present in these landscapes. 
Typesense could be very interesting but to get any tracking in this, we need a plugin. 

That's the reason I'm asking if there is anything out there. Even a start would be good so I can follow and see where I can contribute to such project. 
Or perhaps if Typesense has any plans for releasing their own "official" connectors anytime (soon)?

**Comment by jasonbosco** [comment]
Ah, got it. We have a yet-to-be-prioritized item in our backlog to explore an integration with the Wordpress ecosystem, so no immediate plans at the moment. 

That said, we'd definitely appreciate community contributions on this front, especially since we don't have Wordpress experts on our team.

**Comment by aaronjpitts** [comment]
Over the holidays I'm planning to have a look at building such a plugin for WordPress. It might just perhaps be a WordPress CLI tool to start with to index the posts into typesense. I'll update this issue when I can :)

**Comment by codeagencybe** [comment]
@jasonbosco 
Exactly, that's the thing I was hunting for wether something might come from Typesense as "official" plugin or if this is coming from community end. 
But I'm more than happy to help and contribute on this since Wordpress is mostly are CMS we use in projects and it's also one of the biggest marketshare in the world. So it would benefit Typesense a lot if there is one. 

@aaronjpitts 
Exactly my idea also. A WP CLI version would be a better first base/iteration as this can run in background. 
But it will also need a plugin to bring that power back into Wordpress backend/frontend. 

My idea on this is:
* improve the load times in searching backend by having faster response times when searching specific records (products, orders, posts, customers, ...)
* in general faster loading times of backend pages because TS returns data much faster
* create widgets or override existing widgets to improve frontend experience when searching. 
Typical use cases are: 
   searching products that show a dropdown list of matching results
   faceted/fuzzy search possibilities
   filtered searches
   
If you are interested to collaborate on this, feel free to ping me.

**Comment by jasonbosco** [comment]
@codeagencybe @aaronjpitts That sounds awesome! ❤️ Let me know if I can help/clarify anything on the Typesense side as you explore building this out.

Also, if you're able to drop a link to the repo you're using to collaborate in this thread, that could help get more eyes from the community. I know one more person who might be interested as well.

**Comment by claytoncollie** [comment]
@aaronjpitts @codeagencybe , @jasonbosco and I spoke about this sort of thing a few weeks ago. We use Algolia and they originally built a WP plugin which was later sunset and then forked by WebDevStudios.

https://github.com/WebDevStudios/wp-search-with-algolia

I suggest that as a starting point and hopefully @jasonbosco can give his input about what to strip it out and what needs to be added. This plugin has backend (index operation on `save_post` and `save_term`) and frontend functionality (autocomplete.js and instantsearch.js).

**Comment by codeagencybe** [comment]
@jasonbosco 

Thanks! 
So far I haven't started anything yet as I was exploring if there were any existing initiatives already started (or not). 
But I can spin up a repo for a new project. 

@claytoncollie 
Yes I know Algolia too. There are also other similar tools like ElasticPress and Redisearch. 
Both of them are open source and well maintained too.
They also serve the exact same purpose and handle index operations and search and/or autocomplete. 

Links for reference and inspiration:
https://wordpress.org/plugins/redisearch/
https://nl.wordpress.org/plugins/elasticpress/

Those can also serve as a starting point in several ways. 

I will start a new repo later today and share back here for anybody else who wants to jump in and contribute.

Thanks!

**Comment by codeagencybe** [comment]
@jasonbosco  @claytoncollie  @aaronjpitts 

Repo just started at https://github.com/codeagencybe/typesense-wordpress

**Comment by jasonbosco** [comment]
A Typesense user has now built and published a Woocommerce plugin: https://www.codemanas.com/downloads/typesense-search-for-woocommerce/
