### ISSUE TITLE
[Feature Request] Support updating metadata of a collection

### ISSUE THREAD

**Issue by jackwilsdon** [typesense/typesense#1700]
## Description

Currently, metadata on a collection can only be set at creation time.

## Steps to reproduce

N/A

## Expected Behavior

Able to update metadata on a collection when making a `PATCH /collections/<name>` request.

## Actual Behavior

Cannot update metadata on a collection.

## Metadata
**Typesense Version**: 26.0

**OS**: Docker on macOS, `typesense/typesense:26.0` image

**Comment by jaeyson** [comment]
Hi @jackwilsdon, what's the temporary workaround (steps) for this?
1. create a copy collection with the updated name
2. add all the documents in that collection
3. drop the old collection

It seems like there's lots of moving  with documents here.

**Comment by jasonbosco** [comment]
This is now available in 27.0.rc22 - you can now update the metadata field via alter collection API.
