### ISSUE TITLE
Surprising behavior on ids containing URL-unsafe characters

### ISSUE THREAD

**Issue by saibotsivad** [typesense/typesense#1703]
## Description

I'm switching an existing application to Typesense, the old approach used the filepath as the document identifier, e.g. `path/to/file.md`, but used `encodeURLComponent` to sanitize it for URLs, e.g. `path%2Fto%2Ffile.md`

When inserting a document to Typesense, the id is inserted as-is, but when you access it via API endpoints like [updating](https://typesense.org/docs/26.0/api/documents.html#update-a-single-document) or [deleting](https://typesense.org/docs/26.0/api/documents.html#delete-a-single-document) a document, you need to URL-encode ***the id as-is***.

## Steps to reproduce

Start up a Typesense instance, for example with Docker:
```bash
export TYPESENSE_API_KEY=xyz
mkdir $(pwd)/typesense-data
docker run -p 8108:8108 \
            -v$(pwd)/typesense-data:/data typesense/typesense:26.0 \
            --data-dir /data \
            --api-key=$TYPESENSE_API_KEY \
            --enable-cors
```

Create a simple collection, like this:
```bash
curl "http://localhost:8108/collections" \
       -X POST \
       -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
       -d '{
         "name": "companies",
         "fields": [
           {"name": "company_name", "type": "string" },
         ],
         "default_sorting_field": "num_employees"
       }'
```

Imagine that you were using something like a filepath (e.g. `path/to/file.md`) as your identifier.

You might think to insert the document like this:
```bash
curl "http://localhost:8108/collections/companies/documents?action=upsert" \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
        -H "Content-Type: text/plain" \
        -X POST \
        -d '{"id": "path/to/file.md","company_name": "Stark Industries"}'
```

And then you'd expect it to come back on a search (and **it does**):
```bash
curl "http://localhost:8108/collections/companies/documents/search?q=stark&query_by=company_name" \
        -X GET \
        -H "Content-Type: application/json" \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}"
```

But you might then try to grab it by the id you used, and not pay attention to encoding (this will **not** work):
```bash
curl "http://localhost:8108/collections/companies/documents/path/to/file.md" \
        -X GET \
        -H "Content-Type: application/json" \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}"
```

You might think to encode the id when you insert it:
```bash
curl "http://localhost:8108/collections/companies/documents?action=upsert" \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
        -H "Content-Type: text/plain" \
        -X POST \
        -d '{"id": "path%2Fto%2Ffile.md","company_name": "Stark Industries"}'
```

But if you try to grab it by the encoded id, this will **not** work:
```bash
curl "http://localhost:8108/collections/companies/documents/path%2Fto%2Ffile.md" \
        -X GET \
        -H "Content-Type: application/json" \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}"
```

## Expected Behavior

Now that I've gone through this exercise, I realize what should have been obvious earlier:

When you try to grab/update/delete a document by its identifier, you need to URL-encode **the saved id**.

If you store the id as `path/to/file.md` then the URL-encoded version is `path%2Fto%2Ffile.md` so this request would work:
```
GET /collections/companies/documents/path%2Fto%2Ffile.md
```

But if you store a URL-encoded version as the id, e.g. `path%2Fto%2Ffile.md`, then you'll need to URL-encode **_that_** to get it to work, e.g. it'll be double encoded:
```
GET /collections/companies/documents/path%252Fto%252Ffile.md
```

## Actual Behavior

Everything actually works as it should, I just wasn't paying close enough attention while updating this existing application.

**Comment by saibotsivad** [comment]
Thanks to @jasonbosco for the quick response, hopefully this issue will help someone else struggling with encoding and searching through issues for help.

My only suggestion is it could be added to the documentation somewhere, like maybe in [retrieving a document](https://typesense.org/docs/26.0/api/documents.html#retrieve-a-document) it could say something about the `id` needs to be the URL encoded version of whatever the inserted document has on it?

**Comment by jasonbosco** [comment]
Thank you for documenting this @saibotsivad. 

I was looking into adding this into the docs, and just noticed that we have this call out [here](https://typesense.org/docs/26.0/api/documents.html#index-documents)

![Screenshot 2024-05-02 at 2 42 11 PM](https://github.com/typesense/typesense/assets/458383/843e3711-80a5-4d78-9bef-6a51fc89d4f3)
