### ISSUE TITLE
Does Typesense support multiple indices for multi-tenancy?

### ISSUE THREAD

**Issue by sali0** [typesense/typesense#173]
Hey all, love the project. Was wondering if Typesense allows some mechanism of having multiple indices, whether by actually creating multiple or by the ability to fake it, like Elasticsearch can (https://www.elastic.co/guide/en/elasticsearch/guide/current/faking-it.html). Thanks.

**Comment by jasonbosco** [comment]
@sali0 Yes! We support multiple-indices. Each index is called a `collection` in Typesense and you can create as many as you need. 

If you're specifically looking to do multi-tenancy with a single collection, you want to use the scoped search keys feature: https://typesense.org/docs/0.17.0/api/#generate-scoped-search-key

You can essentially embed a filter (say `user_id=123`) and generate a unique API key for each user and use that to only allow users to access their own records.

**Comment by sali0** [comment]
Awesome! Thanks for the reply 👍
