### ISSUE TITLE
Curation overrides causing duplicate results

### ISSUE THREAD

**Issue by smlparry** [typesense/typesense#1740]
## Description
Hi there, firstly thank you so much for Typesense, incredibly useful and much easier to use than elasticsearch etc

I am however hitting one issue with curation overrides. I'm getting duplicate items returned, see below

![Screenshot 2024-05-20 at 5 57 50 pm](https://github.com/typesense/typesense/assets/7920702/a9ba453c-e909-4da8-b7e4-af224dbdf30c)

I am wondering, is this expected behaviour? Is there a way that I can return only unique results? 

I could of course filter these once I get the result back from the server, but this will mess with pagination

I have combed the docs, but I don't seem to be able to find a setting where I can do this, nor does it even refer to this issue which makes me think I'm doing something wrong?

## Steps to reproduce
1. Create a curation, and include 1 pinned item
2. Trigger a search such that the curation is applied
3. Notice that the item appears at the top of the search, and in the search results

## Expected Behavior
I would expect the curated results to be filtered from the remaining search 

## Actual Behavior
I am getting duplicate results, as curated hits, and then also appearing in the remaining search results

![Screenshot 2024-05-20 at 5 57 50 pm](https://github.com/typesense/typesense/assets/7920702/a9ba453c-e909-4da8-b7e4-af224dbdf30c)

## Metadata

**Typesense Version**: 0.25.1

**OS**: Docker / Mac

**Comment by jasonbosco** [comment]
Could you upgrade to v26.0 to see if you can still replicate the issue there?

**Comment by smlparry** [comment]
Apologies @jasonbosco it does look like upgrading to 26.0 fixes the issue.

Thanks mate, closing
