### ISSUE TITLE
Requesting support for Scandinavian letters (ä, ö, æ, ø, å)

### ISSUE THREAD

**Issue by FPDK** [typesense/typesense#1748]
## Description

I'd like to request better support for Danish, Swedish and Norwegian letters, as the current normalisation implementation produces some undesirable results.

The letters are:
- æ
- ø
- å
- ä
- ö

It would be great if above letters could also be supported in synonyms.

## Steps to reproduce

1) Test data:   
```
{"title":"bånd","id":"1"}
{"title":"band","id":"2"}
{"title":"dæmper","id":"3"}
{"title":"damper","id":"4"}
{"title":"flåd","id":"5"}
{"title":"flad","id":"6"}
{"title":"rød","id":"7"}
{"title":"red","id":"8"}
{"title":"rod","id":"9"}
```

2) Create a collection and load test data
```
export TYPESENSE_HOST='http://localhost:8108'
export TYPESENSE_API_KEY=xyz

curl "${TYPESENSE_HOST}/collections" \
      -X POST \
      -H "Content-Type: application/json" \
      -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{
        "name": "nordic",
        "fields": [
          {"name": "title", "type": "string"}
        ]
      }'

curl "${TYPESENSE_HOST}/collections/nordic/documents/import" \
      -X POST \
      -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
      --data-binary '@nordic.jsonl'
```

3) Search 
```
curl -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
"${TYPESENSE_HOST}/collections/nordic/documents/search?query_by=title&num_typos=0&typo_tokens_threshold=0&q=rød"
```

## Expected Behavior
Result containing normalised words should not be returned when *num_typos* and *typo_tokens_threshold* is 0.
When typos is supported, letters with the Nordic characters should be prioritised first.

## Actual Behavior
Searching for **bånd** also returns **band**
Searching for **dæmper** also returns **damper**
Searching for **flåd** also returns **flad**
Searching for **rød** also returns **rod**

## Metadata

**Typesense Version**: typesense:27.0.rc11

**OS**: Linux 5.15

**Comment by jasonbosco** [comment]
You want to set the `locale` parameter in the field definition here:

```json
{"name": "title", "type": "string"}
```

This is documented under [this table](https://typesense.org/docs/26.0/api/collections.html#schema-parameters)

**Comment by FPDK** [comment]
Thank you. I found my issue to be related with the 'query_by_weights'. If I prioritise non-localised fields above localised ones, the order is not always satisfactory. The odd thing is those non-localised fields are product numbers, which have no overlap with my query.
