### ISSUE TITLE
Question: Is there a TypeSense UI/Dashboard?

### ISSUE THREAD

**Issue by sameerkumar18** [typesense/typesense#176]
## Description

Hi, Is there any Dashboard available to visualize the records that exist on my Typesense cluster?
I'd prefer something like Algolia's Dashboard - Been using it over the past couple of years

MVP Idea - I'd love to simply see some records with pagination rendered on an HTML page (even without any functionality, read-only)

cc @jasonbosco

**Comment by jasonbosco** [comment]
@sameerkumar18 We don't have an official dashboard at the moment. But it is in our backlog.

In the meantime, if you're just looking to view records, you could use [this instant search demo repo](https://github.com/typesense/typesense-instantsearch-demo), modify the parameters in [this file](https://github.com/typesense/typesense-instantsearch-demo/blob/master/src/app.js) as needed and then run `npm start` to get a simple UI to search and paginate through records - this is what I use internally when I have a need to look at results visually.

**Comment by jasonbosco** [comment]
@sameerkumar18 We just launched a dashboard in Typesense Cloud: 

<img width="1551" alt="Screen Shot 2021-05-18 at 11 41 09 PM" src="https://user-images.githubusercontent.com/458383/118770955-c6eb8280-b836-11eb-90c5-c49602ee295e.png">

**Comment by jasonbosco** [comment]
Also CC @ctorgalson since you asked about this recently!

**Comment by kamil-karkus** [comment]
> @sameerkumar18 We just launched a dashboard in Typesense Cloud:
> 
> <img alt="Screen Shot 2021-05-18 at 11 41 09 PM" width="1551" src="https://user-images.githubusercontent.com/458383/118770955-c6eb8280-b836-11eb-90c5-c49602ee295e.png">
@jasonbosco Is there any chance to get it for self-hosted app?

**Comment by sashahilton00** [comment]
I assume the lack of activity here should be interpreted as the UI being part of the cloud offering only for the forseeable future?

**Comment by philipeachille** [comment]
Hey all, I have created a simple Typesense UI for the browser here https://github.com/philipeachille/typesense-ui 

Just clone or download the code and open typesense-ui-html to run the UI with demo data. Thereafter you can connect to your own instance.

**Comment by hhimanshu** [comment]
> Hi, [@ctorgalson](https://github.com/ctorgalson) [@sameerkumar18](https://github.com/sameerkumar18) I created a UI/dashboard website/electron app as a side project https://github.com/bfritscher/typesense-dashboard

Very useful, thank you

**Comment by lucifermorningstar1305** [comment]
Hey I also just created a Typesense dashboard. Here's the link: [](https://github.com/lucifermorningstar1305/typesense-client)

**Comment by scarlson1** [comment]
I also created one with support for breaking changes in v30 (analytics, curation, synonyms): https://github.com/scarlson1/typesense-dashboard
