### ISSUE TITLE
Querying facets only cuts off value string

### ISSUE THREAD

**Issue by GitteDreyerApoteka** [typesense/typesense#1761]
## Description

I want to query all our categories, which are three levels deep and comes in a rather odd syntax like
`cat0#cat0 > cat1#cat1 > cat2#cat2`.
We use Raptor as a Search provider calling this url `https://search.raptorsmartadvisor.com/multi_search?collection={collectionName}`

I see that the values returned gets cut off at 100 characters. Is this intentional, a bug or a wrongful request body?
## Steps to reproduce
Please see my request body and response here - the underline values are those that gets cut off:
![image](https://github.com/typesense/typesense/assets/149602188/bcf25bd0-0276-4235-ae31-94c07cb684d1)

## Metadata

**Typesense Version**:

**OS**:

**Comment by jasonbosco** [comment]
Could you upgrade to Typesense Server `27.0.rc14`, and then add `"facet_strategy": "exhaustive"` as a search parameter to see if that helps? 

More context on facet strategies here: https://github.com/typesense/typesense/issues/1698#issuecomment-2121240328

In `top_values` mode, we limit to 100 characters for facet values.

**Comment by jasonbosco** [comment]
We also plan to increase this 100 character limit in top_values mode to 255 in an upcoming RC build

**Comment by GitteDreyerApoteka** [comment]
Thanks for your reply. I have reached out to our Search provider and asked if they could make this upgrade. I'll let you know of the outcome.
