### ISSUE TITLE
Unable to filter for existent/non-existent attributes

### ISSUE THREAD

**Issue by EricHasegawa** [typesense/typesense#1781]
## Description

I have a collection that has an attribute called `entity_types` that's a list of strings. I want to be able to filter for records where entity_types is NULL or of length zero. There's currently no way to do this. Am I missing something/wrong about this? Or is this unsupported.
 
## Expected Behavior
Some sort of `!exists:entity_types` type filter.

## Actual Behavior
I cannot do this.

## Metadata

**Typesense Version**: 26.o

**OS**:  Mac OSX. Hosted on Typesense cloud.

**Comment by jasonbosco** [comment]
This is not possible to do in Typesense at the moment. 

We're tracking this feature request here: https://github.com/typesense/typesense/issues/790

There's also a workaround in that thread in the meantime. 

Duplicate of #790
