### ISSUE TITLE
Conversation Search using existing embedding

### ISSUE THREAD

**Issue by FisherRobison** [typesense/typesense#1784]
We already have existing embeddings indexed. Is it possible to use these in the v26.0 Conversational Search? I only see the auto-embedding field but am not sure how to modify it to use our field.

**Comment by jasonbosco** [comment]
You can enable automatic embedding in a new collection, and then import your existing embeddings into that field. 

Typesense will not regenerate embeddings if they're already present in the documents. 

You'll then be able to use conversational search with that new collection, and the auto-embedding part will only be active during query time.

**Comment by FisherRobison** [comment]
Makes sense. Thank you!
