### ISSUE TITLE
Custom sort order: Collection? / Field? / Documents?

### ISSUE THREAD

**Issue by hqm42** [typesense/typesense#179]
I would like to sort documents based on the context of the search query (e.g. product category). What would be my best options to accomplish this task?

I could think of two possible wasteful solutions:
- One collection per product category containing all products in this category (I would loose global search or parent category search)
- One document per product per category with custom ranking

Currently I am using elasticsearch and sort by the `rankings.rank` field filtered by `scope = category_2` when I want the document order for `category_2`:
```json
# example document
{
  "id": "doc_1",
  "rankings": [
    { "scope": "category_1", "rank": 1 }
    { "scope": "category_2", "rank": 99 }
  ]
}
```

How can I avoid duplicating all the documents?

**Comment by jasonbosco** [comment]
Hi @hqm42, I _think_ I understand what you're referring to, but let me know if I've misunderstood your ask. Based on the example document, it sounds like you'd like to be able to have certain results be returned at certain fixed positions in the results, but the fixed position would vary depending on the value of a different field in the document (like product category). 

Normally, you'd use the [Curation / Overrides](https://typesense.org/docs/0.18.0/api/#curation) feature for this. However, it currently only allows you to use the search query as the context, not another field in the document. 

So instead, I'd recommend using the `pinned_hits` parameter of the search endpoint. Just before querying, you could send the exact document IDs and positions you'd like them to be returned in, in the `pinned_hits` param. You'd want to maintain the mapping between product categories and document rankings in your application and pass them along when search queries are made. 

Does that help?

If I've misunderstood your ask, could you give me two examples of search queries you'd do, and what you'd expect the result ordering to be in each case?

**Comment by hqm42** [comment]
Thank your for your instant feedback, but I think you misunderstood. Lets say I have two categories:
- Men's Socks
- Men's Sportswear

Some socks may be present in both categories. But the sports socks do not sell very well in the context of the "Men's Socks" category:
- Rank for Men's Sportswear: 4 (one of the best selling products for customers looking for sportswear)
- Rank for Men's Socks: 591 (customers looking for socks will probably not buy this product)

I know I can change the positions of single documents in my search result, but sending >1000 `pinned_hits` with every query does not seem practical to me.

One way to allow custom rankings would be to allow fields not present in the document schema, or maybe have wildcard field names:

**collection_schema.json**
```js
{
  // ...
  "fields": [
    // ...
    {"name": "rank_*", "type": "int32" }
  ]
}
```

**product_1.json**
```js
{
  // ...
  "rank_category_mens_socks": 4,
  "rank_category_mens_sportswear": 591
}
```

**query_mens_socks.json**
```js
{
  // ...
  "sort_by": "rank_category_mens_socks:asc"
}
```

**query_mens_socks.json**
```js
{
  // ...
  "sort_by": "rank_category_mens_sportswear:asc"
}
```

Currently I could achieve this behaviour by having one collection per category and query the right collection based on the current category, but this would be very wasteful in terms of resources.

**Comment by jasonbosco** [comment]
Got it. I understand now. 

The wild-card idea sounds interesting. As a workaround in the meantime, if your categories are fairly fixed, you could define each of your category rank fields in the schema explicitly and still use one collection:

```
{
  // ...
  "fields": [
    // ...
    {"name": "rank_category_mens_socks", "type": "int32" },
    {"name": "rank_category_mens_sportswear", "type": "int32" }
  ]
}
```

**Comment by hqm42** [comment]
Sadly this will not work for me, as my categories change a lot.
I could however generate fields for `rank_category_1` ... `rank_category_100000` .  Can I use `sort_by` with optional fields? Is there any overhead for missing optional fields?

**Comment by jasonbosco** [comment]
@hqm42 Unfortunately you can't use optional fields with `sort_by`, because then it's sort position would be undefined. 

So you'd have to use a constant integer for those records you want to have a `null` value for, and then you'll be able to use that field with `sort_by`. 

All of this said, this approach does feel hacky IMO, to implement what you're looking to do. So question for you: 

We currently only support the ability to override rankings based on search query, using the `[overrides](https://typesense.org/docs/0.18.0/api/#curation)` endpoint. Now, if we support overrides based on `filter_by` values, would that be a better solve for your use case? For eg, something like this:

```json
override_1 = {
  "rule": {
    "filter_by": "category:mens_socks",
  },
  "includes": [
    {"id": "422", "position": 1},
    {"id": "54", "position": 2}
  ],
  "excludes": [
    {"id": "287"}
  ]
}

override_2 = {
  "rule": {
    "filter_by": "category:mens_sportswear",
  },
  "includes": [
    {"id": "422", "position": 5},
    {"id": "54", "position": 6}
  ],
  "excludes": [
    {"id": "287"}
  ]
}
```

And then any time you run a search query with a `filter_by` parameter defined in the override rule, those ranking will be used.

**Comment by hqm42** [comment]
That would require to know which documents are in the search result before running the query. If I already knew that I would not need a search engine ;)

From a typesense consumer point of view, I would prefer the "dynamic fields with prefix" solution. Documents not containing my requested `sort_by` field (e.g. `rank_category_mens_socks`) would always be sorted after all documents containing this field (like in postgresql: `ORDER BY rank_category_mens_socks ASC NULLS LAST`). It would be my responsibility to filter out these documents (e.g. `"filter_by": "categories:mens_socks"`). Our current implementation with elastcearch uses nested objects in our sort query, but I think nested objects would add too much complexity to typesense only to enable this use case:

**Comment by jasonbosco** [comment]
Hi @hqm42 

We've added support for regex field names in v0.20.0 (not yet publicly released). Here's an RC build if you'd like to try it out:

```shell
docker run -p 8108:8108 -v/tmp/typesense-data:/data typesense/typesense:0.20.0.rc31 --data-dir /data --api-key=xyz
```

You can now define a schema like this:

```javascript
{
  // ...
  "fields": [
    // ...
    {"name": "rank_.*", "type": "int32" }
  ]
}
```

**Comment by hqm42** [comment]
Thank you so much! I will try it out next week.

**Comment by hqm42** [comment]
The new dynamic schema feature solves all problems for my use case :)
