### ISSUE TITLE
Can't downloading RC builds from dl.typesense.org

### ISSUE THREAD

**Issue by FPDK** [typesense/typesense#1792]
I'm trying to download 27.0.rc16 x64 DEB package, but I get this message:

_404 Sorry - we could not find this page. Ironic isn't it?_

I have followed the [documentation here](https://typesense.org/docs/guide/faqs.html#how-do-i-access-rc-builds).

I'm using this URL: https://dl.typesense.org/releases/27.0/typesense-server-27.0.rc16-amd64.deb

Is the documentation not up to date, or am I doing something wrong?

**Comment by jasonbosco** [comment]
The version exists in two places in the URL.

The correct URL is https://dl.typesense.org/releases/27.0.rc16/typesense-server-27.0.rc16-amd64.deb
