### ISSUE TITLE
Can't match filter against empty string

### ISSUE THREAD

**Issue by dosena** [typesense/typesense#180]
## Description

Feature request: I want to be able to match against the empty string in filters (possibly in the `q=` text query field as well).

## Steps to reproduce
If I have a collection schema like this
```
{
  "fields": [
    {
        "name": "text",
        "type": "string"
    },
    {
        "name": "entry1",
        "type": "string",
        "facet": true
    },
    {
        "name": "entry2",
        "type": "string",
        "facet": true
    },
    {
        "name": "entry3",
        "type": "string",
        "facet": true
    }
  ]
}
```
... I can add documents like this:
```
{
    "text": "Hodge",
    "entry1": "not empty",
    "entry2": "red",
    "entry3": ""
}
{
    "text": "Podge",
    "entry1": "not empty",
    "entry2": "",
    "entry3": ""
}
```

## Expected Behavior

I should be able to search using filters to get only the second document, e.g. something like `filter_by=entry1:not+empty&&entry2:null`

## Actual Behavior

It's not possible. I can completely leave out the filter against `entry2`, but then I get both documents. Trying `null`, or the empty string `""` just won't work for `entry2`

## Metadata

**Typsense Version**:  0.18.0

**OS**: macOS Mojave

**Comment by jasonbosco** [comment]
Hi @dosena, interesting use case! Thinking out loud, the challenge involved is, how do we represent the `null` value in a search query. We could use a special string like `NULL`, and look for it in the query and then add a way to escape the string `"NULL"` if it exists in someone's dataset...

In the meantime, you could do this on your side by picking a special string to represent `NULL` in your dataset and index that as the value of the (faceted) field, any time it has no data. For eg, if your data set does not have a value like "NULL", you could just use that as the value and filter based on that. Or may be a random sequence of characters that doesn't represent a dictionary word. Now, of course you'd have to implement logic application-side to detect this special string and swap it out for `""`.

**Comment by dosena** [comment]
In our case we worked around it by adding an extra boolean `has_entry2` that signified if `entry2` had a value or not.

Then there's the differentiation between `NULL` and an empty string (i.e. string of length 0). I don't know if we really need both cases; in my case the empty string alone would suffice. Maybe the implementation code would "collapse" an empty string into a `NULL`.

I only really know your HTTP API; I would picture something like just omitting a value would be `NULL` or an empty string: e.g. `.../search?q=*&filter_by=entry2:&per_page=100`.

Might make more sense to interpret omitted values as`NULL`  - you could use it in combination with types other than strings that don't have this secondary empty-string problem.

**Comment by dosena** [comment]
Also related are `optional` fields - how can you query against optional fields that were not assigned a value?

**Comment by jasonbosco** [comment]
@dosena Good point about querying optional fields. I'll leave this issue open and keep you posted when we implement it.

**Comment by Nargonath** [comment]
Did you make progress on filtering by optional fields that are not present?

**Comment by jasonbosco** [comment]
Here's how to handle this: https://github.com/typesense/typesense/issues/790#issuecomment-1314105452. 

Will close this issue as a duplicate, in favor of the above one.

**Comment by Nargonath** [comment]
Thanks @jasonbosco for your answer. I was hoping for a different solution as we have many optional fields in our schema and adding a boolean field for each one of them didn't seem right. Especially since you cannot act on the current dataset if you haven't already created the booleans preemptively.

**Comment by jasonbosco** [comment]
@Nargonath Yeah, the solution in that comment is a temporary workaround for now. We definitely intend to add an IS NULL operator to Typesense natively as part of #790.

**Comment by Nargonath** [comment]
Ah cool, thanks @jasonbosco for the heads-up. I'm looking forward to it.
