### ISSUE TITLE
Compiling Typesense binary on an ARM system

### ISSUE THREAD

**Issue by patelneel55** [typesense/typesense#181]
## Description

Amazing project y'all, its exactly what I was looking for! I am looking into deploying the typesense server on a raspberry pi by compiling the binary from source however, I'm having a couple issues with the `-msse -msse2` optimizations for the x86_64 architectures, as well as some headers such as `#include <emmintrin.h>`. Would it be possible to successfully compile and execute this project on an ARM system with modifications/patch if need be?

Thanks!

## Metadata

**Typsense Version**: 0.18.0

**OS**: Raspbian Stretch (armhf)

**Comment by jasonbosco** [comment]
Hi @patelneel55 we briefly discussed supporting ARM architectures last year, but other things came up, so we didn't dig into it further. Interesting use case of running Typesense on a Raspberry Pi! 

Definitely open to PRs!

**Comment by artt** [comment]
@patelneel55 Did you ever get this to work? Just got an RPi just for this purpose, and found out that the docker image was for amd64 only :(

**Comment by freewizard** [comment]
In case anyone still interested in get AArch64 compiled:
- s2 needs to be updated with this patch: https://github.com/google/s2geometry/pull/166/
- art.cpp requires SSE2, but may workaround with https://github.com/DLTcollab/sse2neon
- braft, just drop `-msse4` in make file

**Comment by kishorenc** [comment]
I was able to get Typesense ported to ARM a few weeks back with the help of a community member. Current plan is to make it available for the next release (0.23) onwards.

**Comment by mikob** [comment]
@kishorenc that's great news! Looking forward to the next release!
Related: #185

**Comment by everdrone** [comment]
@kishorenc Is it possible to contribute to the arm build? Is there a branch I can look into?

**Comment by kishorenc** [comment]
Typesense [0.23 branch](https://github.com/typesense/typesense/tree/v0.23) builds on ARM well. We will publish an official ARM binary when we release 0.23.

**Comment by rgplvr** [comment]
When is the planned release of 0.23 or is there any way i can build this any pointer/documentation would be helpful

**Comment by mikob** [comment]
@kishorenc any updates on the 0.23 release?

**Comment by kishorenc** [comment]
v0.23 is out. We publish an ARM binary built on Graviton 2.

**Comment by mikob** [comment]
@kishorenc thanks very much! Working great on AWS!
