### ISSUE TITLE
Nested fields schema float is created as int64[]

### ISSUE THREAD

**Issue by anaibol** [typesense/typesense#1810]
Description
When attempting to insert documents with float nested fields, an error occurs stating that a nested field must be an array of int64, even though the field type is defined correctly.

Steps to reproduce
Define a Typesense schema with nested fields like the one below:

```json
{
  "name": "products",
  "fields": [
    { "name": "id", "type": "string" },
    { "name": "name", "type": "string" },
    { "name": "description", "type": "string" },
    { "name": "category", "type": "string" },
    { "name": "offers", "type": "object[]", "fields": [
      { "name": "id", "type": "string" },
      { "name": "price", "type": "float" },
      { "name": "currency", "type": "string" },
      { "name": "description", "type": "string" },
      { "name": "validFrom", "type": "int64" },
      { "name": "validUntil", "type": "int64" }
    ]}
  ],
  "default_sorting_field": "id"
}
```

Expected Behavior
When should be able to insert documents

Actual Behavior
When inserting documents:
`
error: 'Field "offers.price" must be an array of int64.'
`

Metadata
Typesense Version: 26/27

OS: linux

**Comment by jasonbosco** [comment]
`fields` can only exist at the top level of the collection schema definition. 

So this part of the schema is invalid:

```json
{ 
  "name": "offers", "type": "object[]", 
  "fields": [
      { "name": "id", "type": "string" },
      { "name": "price", "type": "float" },
      { "name": "currency", "type": "string" },
      { "name": "description", "type": "string" },
      { "name": "validFrom", "type": "int64" },
      { "name": "validUntil", "type": "int64" }
    ]
}
```

You can either leave it as:

```json
{ "name": "offers", "type": "object[]" }
```

In wish case, all field inside every object in the array of objects will be indexed. 

Or if you only want a subset of the nested fields to be indexed, you want to do something like this:

```json
{
  "name": "products",
  "fields": [
    { "name": "name", "type": "string" },
    { "name": "description", "type": "string" },
    { "name": "category", "type": "string" },
    { "name": "offers.price", "type": "float[]" },
    { "name": "offers.currency", "type": "string[]" },
    { "name": "offers.description", "type": "string[]" }
  ]
}
```

Finally, the data type for a given field should be consistent across all documents.

**Comment by anaibol** [comment]
> `fields` can only exist at the top level of the collection schema definition.
> 
> So this part of the schema is invalid:
> 
> ```json
> { 
>   "name": "offers", "type": "object[]", 
>   "fields": [
>       { "name": "id", "type": "string" },
>       { "name": "price", "type": "float" },
>       { "name": "currency", "type": "string" },
>       { "name": "description", "type": "string" },
>       { "name": "validFrom", "type": "int64" },
>       { "name": "validUntil", "type": "int64" }
>     ]
> }
> ```
> 
> You can either leave it as:
> 
> ```json
> { "name": "offers", "type": "object[]" }
> ```
> 
> In wish case, all field inside every object in the array of objects will be indexed.
> 
> Or if you only want a subset of the nested fields to be indexed, you want to do something like this:
> 
> ```json
> {
>   "name": "products",
>   "fields": [
>     { "name": "name", "type": "string" },
>     { "name": "description", "type": "string" },
>     { "name": "category", "type": "string" },
>     { "name": "offers.price", "type": "float[]" },
>     { "name": "offers.currency", "type": "string[]" },
>     { "name": "offers.description", "type": "string[]" }
>   ]
> }
> ```
> 
> Finally, the data type for a given field should be consistent across all documents.

Thanks for the clarification!
