### ISSUE TITLE
`conversation_model_id` is invalid.

### ISSUE THREAD

**Issue by NeweggWolf** [typesense/typesense#1816]
## Description

Using the newly created conversation_model_id to perform conversation search, but it response that the conversation_model_id  is invalid.

## Steps to reproduce
![image](https://github.com/typesense/typesense/assets/129843552/a460c7b4-0b06-4eee-95ee-70262e0b3e79)
![image](https://github.com/typesense/typesense/assets/129843552/84a86c35-a4c6-4a74-82d4-691ea86e35c1)

## Metadata

**Typesense Version**:  26.0

**OS**: docker image ： typesense/typesense:26.0  （Ubuntu）

 5 node cluster

**Comment by ozanarmagan** [comment]
Can you please retry with `v27.0.rc22`?

**Comment by NeweggWolf** [comment]
Thank you, V26.0. I tried using GPT-3.5, and it also works.
