### ISSUE TITLE
Is there any ways to sort documents based on Date type when using TypeScript

### ISSUE THREAD

**Issue by rafekun** [typesense/typesense#182]
## Description
I want to sort firestore documents by Date object. Any workarouds, best practices?
Should I convert Date to floats? 
Thanks!

**Comment by jasonbosco** [comment]
Hi @rafekun, you want to convert dates to Unix Timestamp integers and use int64 as your data type. You can then sort based on the integer field, to sort by date. 

Here's an example of how to do this in Javascript: https://github.com/typesense/showcase-songs-search/blob/39b3a402da0d0df4cda458daeb3909e030e3ba58/scripts/indexer/index.js#L172-L177

Here's the corresponding schema: https://github.com/typesense/showcase-songs-search/blob/39b3a402da0d0df4cda458daeb3909e030e3ba58/scripts/indexer/index.js#L138

**Comment by rafekun** [comment]
Thanks!!
