### ISSUE TITLE
Is TODO.md current?

### ISSUE THREAD

**Issue by jonathan-mothership** [typesense/typesense#1831]
We're comparing options for search providers and we're wondering if this 3-year-old TODO list is current for Typesense: https://github.com/typesense/typesense/blob/main/TODO.md

**Comment by jasonbosco** [comment]
No, that list is not current. We've since moved to just using GitHub issues.

**Comment by jasonbosco** [comment]
We maintain the roadmap here: https://github.com/orgs/typesense/projects/1
