### ISSUE TITLE
Duplicate Fields highlight and highlights in Query Response

### ISSUE THREAD

**Issue by justin5267** [typesense/typesense#1834]
### Issue Description

When performing a query with Typesense, the response contains duplicate fields for highlighting: highlight and highlights. Both fields seem to provide the same information. I only need one of these fields in the response, but I have been unable to determine how to achieve this from the documentation.

<img width="476" alt="image" src="https://github.com/user-attachments/assets/d118c614-4e53-480e-95fd-fc6676d38e42">

### Steps to Reproduce:
Perform a query with Typesense.
Observe that the response includes both highlight and highlights fields.

### Expected Behavior:
I would like to configure the response to include only one of these fields (highlight or highlights), as having both is redundant.

### Actual Behavior:
Both highlight and highlights fields are returned in the query response.

### Attempts to Resolve:
I have carefully read through the documentation but have not been able to find a way to configure the response to return only one of the fields.

Thank you for your assistance in resolving this issue.

**Comment by kishorenc** [comment]
The `highlights` key is deprecated. To disable it entirely you can set `enable_highlight_v1: false`.

**Comment by sweihub** [comment]
This should be well documented, I was confused by this `highlights` too.

Would you document what are deprecated fields, for the fresh user, We don't want the deprecated fields.
https://typesense.org/docs/30.1/api/search.html#results-parameters
