### ISSUE TITLE
Make the context window limit configurable for RAG / conversational search?

### ISSUE THREAD

**Issue by CMLivingston** [typesense/typesense#1866]
## Description

I'm using TS Cloud to do some RAG on text and code extracted from crawled HTML. 

The docs for conversational RAG mention a 3000 token limit:

> Context Window Limits
> 
> Although we retain the entire conversation history in Typesense, only the most recent 3000 tokens (approximately 1200 characters) of the conversation history will be sent for generating the standalone question due to the context limit.
> 
> Similar to the conversation history, only the top search results, limited to 3000 tokens, will be sent along with the standalone question.

[#](https://typesense.org/docs/26.0/api/conversational-search-rag.html#managing-past-conversations)

## Use case

I'm doing RAG on documents like crawled web pages with lots of content, code examples, json objects, etc (think documentation sites), and I want to just crawl the URL and put the relevant content in a single record to keep things simple in the short term. Using this approach, I hit the token limit pretty quick and get 1-2 results max in my RAG search. Is there a limitation in TS that prevents getting the most out of underlying context window? Seems like TS server has already done its job by providing the results, and it might be a bandwidth / LLM API consideration at that point. 

Any clarity on my options here would be greatly appreciated. I would like to avoid chunking the records after crawling, however, long-term, I can see how doc-scraper might help (url anchors and subsections etc).

Great project and thanks in advance!

**Comment by kishorenc** [comment]
@CMLivingston 

Actually the `max_bytes` configuration dictates the actual limit so that documentation is outdated. We will remove it -- thanks for the heads up!
