### ISSUE TITLE
Failed to load library libonnxruntime_providers_cuda.so

### ISSUE THREAD

**Issue by FadelMF** [typesense/typesense#1876]
## Description

I am a beginner when it comes to Linux and all things installation. I am trying to install typesense on a GPU, but I get an `[ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory` error when I ingest data using the embedding model. On my machine, I am using CUDA Version 12.3 and not 11.x, how can I fix typesense to run on libcublasLt.so.12, just like mine?
Thank you in advance.

**Comment by ozanarmagan** [comment]
Hi, 

Unfortunately currently we only support CUDA11, so you will need to downgrade your CUDA to 11.8

**Comment by FadelMF** [comment]
Hi @ozanarmagan ,
Thanks for replying to my issue.

Maybe one more question, what will happen to my LLM inference (in this case for RAG) if the CUDA version is downgraded, are there any issues with performance, version collisions between 12 and 11 in the answer generation process or all my scripts will be obsolete?

**Comment by ozanarmagan** [comment]
Do you use a local LLM inference with vLLM for RAG?

**Comment by FadelMF** [comment]
No sir, I use the `transformers` library (`from transformers import AutoTokenizer, AutoModelForCausalLM`) directly to run LLM (llama 3.1 8B) for my RAG.

**Comment by ozanarmagan** [comment]
I don't think there will be a version collision, but even if it happens you should be able to downgrade transformers library.

**Comment by FadelMF** [comment]
Glad to hear it, thanks Ozan for helping me out!
