### ISSUE TITLE
Exclude by id field doesn't work

### ISSUE THREAD

**Issue by v-byte-cpu** [typesense/typesense#188]
## Description

`filter_by` with excluded id field doesn't work

## Steps to reproduce

I try to exclude document with specific (dynamic) id from search result with the following `filter_by` clause:

```
id: -b43888a8-999b-4021-bca3-5929377b79b1
```

## Expected Behavior

Search result without document with excluded id

## Actual Behavior

Typesense returns 404 error

```
"Could not find a filter field named `id` in the schema
```

## Metadata

**Typsense Version**:

0.18.0

**OS**:
not relevant, docker container

**Comment by jasonbosco** [comment]
@v-byte-cpu Typesense doesn't support exclusion operators in filter values. But since you're trying to exclude by ID, you can use the `hidden_hits` search parameter. For eg: to hide records with IDs `123` and `456`, you'd specify `hidden_hits=123,456`.

**Comment by v-byte-cpu** [comment]
@jasonbosco I thought it was already implemented in https://github.com/typesense/typesense/issues/155. By the way, your solution solves my problem. Thank you!

**Comment by jasonbosco** [comment]
#155 started out with an ask to do facet value negation, but it evolved into keyword negation in the query. Facet value negation is still in our backlog. 

Closing this issue report.
