### ISSUE TITLE
Defaulting to different type on nested objects

### ISSUE THREAD

**Issue by fogx** [typesense/typesense#1882]
## Description

We have deeply nested objects with many float values. `object[]` will index all these fields, but will create the schema with `int64[]`. Can i define the data type of the children somehow, without manually defining it for each one in the schema?

example: An object with percentage values for countries.
```
{
  AU: 2.5,
  CA: 2.5,
  EU: 5,
  GB: 5,
  US: 75,
}
```

**Comment by kishorenc** [comment]
Yes, given the following object.

```
{
    "currencies": {
        "AU": 2.5.
        "EU": 5
    }
}
```

you can define the types for the children of `currencies` like this in the field schema definition:

```
{
    "name": "currencies\\..*",
    "type": "float"
}
```

The `\\` is used to escape the dot and then a `.*` used to match any value that follows `currencies.`.

**Comment by fogx** [comment]
awesome thanks, i guess i didn't connect those parts in my head 👍 
For anyone else stumbling upon this, here is the [documentation](https://typesense.org/docs/26.0/api/documents.html#dealing-with-dirty-data)
