### ISSUE TITLE
disable the search Analytics for specific requests

### ISSUE THREAD

**Issue by MaherRemitaDZ** [typesense/typesense#1887]
## Description
I'm using Laravel with typsesnse as the search driver for Scout, I want a way to disable the search analytics for some routes for example in my case i want all the API routes to be excluded from the search analytics i only want the result without saving the query

according to typesens docs, there is bo built-in way to do this

## Metadata

**Typesense Version**:

**OS**:

**Comment by MaherRemitaDZ** [comment]
disable the search Analytics for specific requests

**Comment by kishorenc** [comment]
On 0.27 RC builds, you can disable analytics aggregation for specific search queries (for e.g. those originating from a test script), by setting `enable_analytics: false` as a search query parameter. You can try on `27.0.rc30`.

**Comment by MaherRemitaDZ** [comment]
How can download or upgrade to v27.0.rc30

**Comment by jasonbosco** [comment]
Here's an FAQ on how to access rc builds: https://typesense.org/docs/guide/faqs.html#how-do-i-access-rc-builds

**Comment by MaherRemitaDZ** [comment]
thanks, I already installed it, Everything is working
