### ISSUE TITLE
Filter value array cannot be empty anymore

### ISSUE THREAD

**Issue by ivan-wolf** [typesense/typesense#1890]
## Description

Starting with `26.0`, a filter like `categories:=[]` produces an error:

```
Error with filter field "categories": Filter value array cannot be empty.
```

It worked as expected in `0.25.2` (no hits produced).

Is the change intentional (behavior expected)?

## Steps to reproduce

Send a search like the following:

```json
{
  "q": "*",
  "filter_by": "categories:=[]"
}
```

## Expected Behavior
Search results in no hits.

## Actual Behavior
The following error is returned (code 400):

```json
{
   "message":"Error with filter field `categories`: Filter value array cannot be empty."
}
```

## Metadata

**Typesense Version**: `26.0`

**Comment by kishorenc** [comment]
Fixed in `27.0.rc33`.
