### ISSUE TITLE
Search Results Issue

### ISSUE THREAD

**Issue by mannywebdev** [typesense/typesense#1892]
## Description

When indexing terms like "Red Bull" or "Kit Kat" as two separate words in Typesense, the search functionality does not recognize queries such as "redbull" or "kitkat" as valid. However, if these terms are indexed as single words, like "Redbull" or "Kitkat", the search yields results for both spaced ("Red Bull") and unspaced ("redbull") queries. This behavior is causing inconsistencies in search results, depending on how the terms are indexed.

## Expected Behavior

When a term like "Red Bull" is indexed as two separate words, the search query "redbull" (without spaces) should still return relevant results, recognizing the term as a valid match.

## Actual Behavior

When "Red Bull" is indexed as two separate words, the search query "redbull" (without spaces) does not return any results. This behavior forces the need to index terms without spaces to ensure search queries work as expected, which may not be feasible or desirable in all cases.

In my case there are many products like this with spaces, which are not coming in search results.

So is there a workaround you can suggest.

**Comment by jasonbosco** [comment]
You want to set `split_join_tokens: always` as a search parameter. 

This parameter is documented here: https://typesense.org/docs/26.0/api/search.html#typo-tolerance-parameters
