### ISSUE TITLE
[bug] In import: using parameter "return_id": the response missing "id" in case of error

### ISSUE THREAD

**Issue by stargazer33** [typesense/typesense#1893]
## Description
According to documentation: "If you want the import response to return the ingested document's id in the response, you can use the return_id parameter."
I tried it: in case some documents have error - the `id` of such document is missing!

## Steps to reproduce
Linux command line:
```
curl -sS -H "X-TYPESENSE-API-KEY: xyz" "http://localhost:8108/collections/r4/documents/import?action=upsert&return_id=true" -X POST --data-binary @./data/dump/bigfile.jsonl |jq .
{
  "code": 400,
  "document": "{\"id\":\"wlWMMcoqShiuWbBSK73_ng\",\"title\":\"title1\", ... }",
  "error": "Field `url` has been declared in the schema, but is not found in the document.",
  "success": false
}
{
  "id": "wH64iUUhScCcBnY8aNJVOw",
  "success": true
}
{
  "id": "Cnt5XP49Q02DaUayIFTAng",
  "success": true
}
...
```

## Expected Behavior
I expect `"id"` for ALL documents, for successful and for not successful.
This makes code on the client side much simpler - in all cases I get "success" and "id"

## Actual Behavior
In case of` "success": false` field `id` is missing.
And, I got the "document" field, which is unexpected: I did not set the `return_doc` parameter

**Typesense Version**:
26

**OS**:
Ubuntu

## Additional info
The openapi.yml description for this response:
```
      responses:
        200:
          description:
            Result of the import operation. Each line of the response indicates the result
            of each document present in the request body (in the same order). If the import
            of a single document fails, it does not affect the other documents.
            If there is a failure, the response line will include a corresponding error
            message and as well as the actual document content.
          content:
            application/octet-stream:
              schema:
                type: string
                example: |
                  {"success": true}
                  {"success": false, "error": "Bad JSON.", "document": "[bad doc"}
        400:
          description: Bad request, see error message for details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
```
I do not think it is consistent with actual response: 
`"id"` is not mentioned at all
`"document"` is mentioned under response 200
I think, some cleanup should be done here

**Comment by kishorenc** [comment]
Fixed in `27.0.rc32`.
