### ISSUE TITLE
Allow Configuration or Include `x-typesense-api-key` in CORS Preflight `Access-Control-Allow-Headers`

### ISSUE THREAD

**Issue by 0x4139** [typesense/typesense#1896]
This restriction limits the ability to interact securely with the Typesense API from frontend applications across different domains.

## Steps to Reproduce

1. Deploy a frontend application on a different domain or localhost.
2. Make a request to the Typesense server including the `x-typesense-api-key` header.
3. Observe the CORS error in the browser console.

## Expected Behavior

The request should succeed without being blocked by the browser's CORS policy, allowing the `x-typesense-api-key` header to be used in cross-origin requests.

## Actual Behavior

The request is blocked, and the browser throws a CORS error because the `x-typesense-api-key` header is not allowed in the `Access-Control-Allow-Headers` list in the preflight response.

This issue restricts the ability to interact with the Typesense API securely from frontend applications, particularly when running them in different domains (e.g., local development servers, staging environments, or different production domains).

## Proposed Solutions
To address this issue, we propose the following enhancements:

1. **Include `x-typesense-api-key` in Default CORS Configuration:**
   - Modify the default CORS configuration of the Typesense server to include `x-typesense-api-key` in the `Access-Control-Allow-Headers` list. This would allow all cross-origin requests to include this header without requiring additional configuration.

2. **Allow Custom CORS Configuration:**
   - Provide an option for developers to customize the CORS headers, specifically the `Access-Control-Allow-Headers`, through the server configuration. This would enable users to add headers as needed for their specific use case.

3. **Document Workarounds for Developers:**
   - In the official documentation, provide guidance on how to handle CORS issues when using the `x-typesense-api-key` header. This could include setting up a reverse proxy, using middleware in an Express.js server, or using a CORS proxy service during development.

## Benefits
- **Improved Developer Experience:** By including the `x-typesense-api-key` in the default CORS configuration or allowing customization, developers will face fewer obstacles when integrating Typesense with their frontend applications.
- **Increased Flexibility:** Allowing custom CORS configuration would enable developers to adjust security policies to meet their specific requirements, enhancing Typesense's usability in a variety of deployment scenarios.
- **Security Considerations:** The ability to control which headers are allowed via CORS ensures that developers can balance security with functionality based on their deployment context.

## Additional Information
This enhancement will be particularly useful for developers working in modern web application environments where frontend and backend services are often hosted on different domains or during local development.

Thank you for considering this request. We appreciate your ongoing efforts to make Typesense a robust and developer-friendly solution.

**Comment by jasonbosco** [comment]
You can configure CORS in Typesense using these parameters: https://typesense.org/docs/26.0/api/server-configuration.html#cors

If you're on Typesense Cloud, you can email support at typesense dot org with your cluster ID and we can set this up for you.

**Comment by jasonbosco** [comment]
Typesense does send `Access-Control-Allow-Headers: x-typesense-api-key` in the preflight HTTP OPTIONS response when you enable CORS:

![Screenshot 2024-08-14 at 10 18 36 AM](https://github.com/user-attachments/assets/ac7f00e4-079b-4d86-b187-6aaa52ac406e)

You can try it out yourself here: https://address-autocomplete.typesense.org/

Could you give me a set of docker and curl commands [like this](https://gist.github.com/jasonbosco/7c3432713216c378472f13e72246f46b) that replicates the issue you're seeing?
