### ISSUE TITLE
Expired API keys with autodelete are not automatically removed

### ISSUE THREAD

**Issue by joonatanaatos** [typesense/typesense#1897]
## Description

I noticed that my expired API keys with the autodelete field set to true were not automatically removed.

## Steps to reproduce

1. Create an API key with an expiry date and autodelete set to true.
2. Wait for the key to expire.

## Expected Behavior

The API key is automatically deleted.

## Actual Behavior

The API key is not deleted.

## Metadata

**Typesense Version**: 26.0

**OS**: [Docker](https://hub.docker.com/r/typesense/typesense) deployed on a Kubernetes stateful set.

**Comment by joonatanaatos** [comment]
The housekeeping function in the auth manager was previously called from `src/housekeeper.cpp` but that part of the code is currently commented out. It seems like the housekeeping for auth manager has accidentally been disabled in commit `ec61706c05d660cf1035a62d0b7b81b7a5d201d0`.

**Comment by kishorenc** [comment]
Thank you for the PR.

Fixed in 27.0.rc33`.
