### ISSUE TITLE
List Collections doesn't respect collections limit

### ISSUE THREAD

**Issue by JordanXtern** [typesense/typesense#1902]
## Description

I have a scoped key: {
      "actions": [
        "collections:create",
        "collections:delete",
        "collections:get",
        "collections:list"
      ],
      "collections": [
        "projectname.*"
      ],
      "description": "Project Name",
      "expires_at": 64723363199,
      "id": 38,
      "value_prefix": "roUU"
    }

But it is allowed to list all collections no matter what, every other action is scoped correctly to only allowing collections with projectname*

## Expected Behavior

For the actions to only allow listing ones the key is allowed to see. In a multi tenant system the key can see any other tenants collections.

**Comment by jasonbosco** [comment]
The permissions layer operates at the API request layer (not response layer).

So setting `collections:list` by definition allows access to the `GET /collections` endpoint. It's not possible to restrict which collections show up in the `GET /collections` API response.

**Comment by jasonbosco** [comment]
We've now addressed this in v27.0.rc37 and above.
