### ISSUE TITLE
Exact matches rank last

### ISSUE THREAD

**Issue by Nick-Mazuk** [typesense/typesense#191]
## Description

I'm building a collection to serve query suggestions. However, I'm finding that exact matches are ranked below documents with longer text. For instance, the document "some query with extra information" ranks below the exact match of "some query"

## Steps to reproduce

The following is with the JS client.

```ts
const Client = require('typesense').Client

const client = new Client({nodes: [{host: '127.0.0.1', port: 8108, protocol: 'http'}], apiKey: 'xyz'})

let f = async () => {
  await client.collections().create({
      name: 'suggestions',
      fields: [
          { name: 'value', type: 'string', facet: false },
          { name: 'dummyField', type: 'int32', facet: false },
      ],
      default_sorting_field: 'dummyField'
  })
  
  await client.collections('suggestions').documents().import([
      { id: 'suggestion-1', value: 'some query', dummyField: 1 },
      { id: 'suggestion-2', value: 'some query with extra information', dummyField: 1 },
  ])
  
  const { hits } = await client.collections('suggestions').documents().search({ q: 'some query', query_by: 'value' })
  
  console.log(hits.map((hit) => hit.document.value ))
  // ['some query with extra information', 'some query']
}

f();
```

As you can see, the only ranking information is the text-match score. Yet the exact match is ranked lower.

I've also seen the same results when using HTTP API with Insomnia, so this is likely not specific to the JS client.

## Expected Behavior

The shorter, exact match would appear first. Furthermore, I'd expect the shorter document to rank higher always as it's a closer match. Even if the user typed `'some que'`, I'd expect the shorter suggestion to rank higher.

## Actual Behavior

The exact match is ranked lower than the less exact matches.

## Metadata

**Typsense Version**: 0.18 (docker)

**OS**: macOS

**Comment by agentile** [comment]
@jasonbosco @kishorenc 
This one will likely be important for us as well. 

We are working to migrate more fully away from Algolia in the next 30 days and exact match handling will be something of note that we will be looking at comparing.

We have use cases for example where we want to exact match on email address or phone numbers.

**Comment by Nick-Mazuk** [comment]
@kishorenc, any reason why this is an "enhancement" and not a "bug"? Virtually all similar search engines rank exact matches first by default (e.g., Algolia, ElasticSearch, MeiliSearch, etc.), so to me this seems more like an algorithmic bug than a feature request.

**Comment by harshadparchandtheagilehub** [comment]
Any timelines by when this would be released ?

**Comment by kishorenc** [comment]
I'm looking into this and will have a RC build soon to try out the fix.

**Comment by fekstr** [comment]
@kishorenc Happy to see that this is in progress! This is the number 1 issue preventing us from deploying Typesense based search into production. I'm curious about how the timeline looks at the moment?

**Comment by kishorenc** [comment]
This had to be paused so that we could get `v0.20.0` out. I will be picking this back up again next week.

**Comment by kishorenc** [comment]
This is available for testing in this Docker RC build: `typesense/typesense:0.21.0.rc7`

Please give it a spin and give us your feedback.

**Comment by copydepo** [comment]
> This is available for testing in this Docker RC build: `typesense/typesense:0.21.0.rc7`
> 
> Please give it a spin and give us your feedback.

Hello!

Can I test it without using Docker?
