### ISSUE TITLE
Join on facet values

### ISSUE THREAD

**Issue by steingran** [typesense/typesense#1917]
## Description

The current Join functionality is about adding additional fields related to search hits. I am trying to do the same with facets, but there I hit a wall. I have values in a facet where I would like to look up values from a different collection, but this does not seem to be supported?

My facet contains an ID, and I want to connect this ID with an ID in a different collection and retrieve a field from that other collection. This is to retrieve a text which is connected to the ID, this is part of a solution to get the text in the correct language.

## Expected Behavior

I expected search options to enable joins for facets, but I found none.

## Actual Behavior

There are no search options to enable this functionality, at least not that I can see

## Metadata

26.0

**OS**:
Linux/AWS

**Comment by kishorenc** [comment]
This is on our roadmap, and we're tracking in here: https://github.com/typesense/typesense/issues/1706
