### ISSUE TITLE
Documents with certain ids cannot be retrieved

### ISSUE THREAD

**Issue by Nick-Mazuk** [typesense/typesense#192]
## Description

If a document has an id that requires escaping in URLs, you cannot retrieve that document by its id.

## Steps to reproduce

Let's take a look at this sample document in the `blog` collection:

```json
{
    "id": "blog post 1",
    "title": "Blog post 1",
}
```

As you can see, the `id` includes spaces, which in URLs must be encoded as `%20`. Let's try to look up the blog post:

```shell
curl -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -X GET \
    "http://localhost:8108/collections/blog/documents/blog%20post%201"
```

```json
{
    "message": "Could not find a document with id: blog%20post%201"
}
```

This also occurs if the curl command doesn't already escape the spaces:

```shell
curl -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -X GET \
    "http://localhost:8108/collections/blog/documents/blog post 1"
```

Furthermore, I've been able to reproduce this behavior:

- with several URL characters that need encoding (not just spaces)
- with the JS client

```js
client.collections('blog').documents('blog post 1').retrieve()
```

With the JS client, it's probably more confusing. I would have assumed the id is passed in the body of the HTTP request, and therefore characters are never escaped. It's not even obvious right now that the id would ever be invalid.

## Expected Behavior

Either

- Typesense should unescape the escaped characters
- The API docs should mention that these characters are forbidden in ids (with an error when trying to add documents with these ids)

## Actual Behavior

See above.

## Metadata

**Typsense Version**: 0.18 (docker)

**OS**: macOS 11.1

---

I have not tested this, but it may also be impossible to update or delete these documents. If documents with invalid ids get into a production collection, it may be incredibly difficult to remove them without deleting the entire collection.

**Comment by jasonbosco** [comment]
Good catch. We didn't intend for document IDs to have spaces in them, especially because they're used in the resource URL. I'll add this to the docs.

Mind if I ask what your use case is for IDs with spaces? I'm curious to learn more.

**Comment by Nick-Mazuk** [comment]
> Good catch. We didn't intend for document IDs to have spaces in them, especially because they're used in the resource URL. I'll add this to the docs.
> 
> Mind if I ask what your use case is for IDs with spaces? I'm curious to learn more.

Thanks for the reply! I don't have any use cases that require IDs to have spaces, I just initially used them for titles because it was easier. It makes total sense for ids to not have spaces, just wasn't something I thought about initially.

**Comment by LaundroMat** [comment]
I stumbled on the same issue.
My use case is that I store movie information and I use the movie URL as the ID. That way, I'm make sure I never have duplicate URLs.
