### ISSUE TITLE
[Feature request] -- add exclude_fields to collection schema

### ISSUE THREAD

**Issue by Nick-Mazuk** [typesense/typesense#193]
There are some fields that may be useful for ranking but should not be returned to the client.

For instance, the Typesense docs recommend adding a `default_sorting_field`. For instance, it could be page views on a blog post, click-through-rate, product revenue, profit margin, or some "ranking score" that's recalculated.

In short, there are times where fields should never be public.

## Current solution

Right now, you can define `exclude_fields` with the schema. However, since that lives in the browser, you're admitting that this field exists. Someone could then find your API key and use it to discover the contents of that field.

The only viable solution is to perform the search on the backend, then relay the results to the user. However, that results in a worse user experience.

Even still, it introduces the chances for developer error. Someone in the future may be adding a new feature that requires searching through this collection, and they may forget to add this exclude_fields argument. Oops!

## Comparisons

For comparison, other options have a similar feature.

- **Algolia**: business metrics
- **MeiliSearch**: attributesToRetrieve

With MeiliSearch, someone could theoretically still guess the name of the field and find it, but because there is a whitelist option, not even the name of the field is public.

## Potential solutions

- Add exclude_fields to the schema. Then these fields are excluded by default.
- Add a display_fields to the schema, basically the reverse of the exclude_fields.
- Add a display_fields option to the search options. Though it's not ideal:
  - developers still have to remember to add this field
  - since this field is used for sorting, it may still be exposed when using the `sort_by` option

**Comment by jasonbosco** [comment]
@Nick-Mazuk Great point about `exclude_fields`, especially when storing non-public sort information. I like the idea of adding this to the collection schema definition. 

I've added this to our backlog, but I'll leave this issue open for tracking purposes.

**Comment by jasonbosco** [comment]
@Nick-Mazuk There's actually a way to do this with [scoped api keys](https://typesense.org/docs/0.18.0/api/#generate-scoped-search-key) with embedded search params:

```
let keyWithSearchPermissions = 'xyz'
let scopedApiKey = client.keys().generateScopedSearchKey(keyWithSearchPermissions, {'exclude_fields': 'sensitive_field_1,sensitive_field_2'})
```

Now if you use `scopedApiKey` to do searches instead of the main search api key, the server will automatically enforce the embedded `exclude_fields` param and users can't override it. 

Happy coincidence that a feature we designed for something else (multi-tenant indices) actually works well for this use case :)

**Comment by Nick-Mazuk** [comment]
Thanks @jasonbosco! That's clever and should do what I need. Will try it out later today.

**Comment by jasonbosco** [comment]
Closing this, since there is a way to do this with scoped API keys. But please feel free to re-open the issue if you run into issues.
