### ISSUE TITLE
Segmentation fault (address not mapped to object)

### ISSUE THREAD

**Issue by peturgeorgievv** [typesense/typesense#1933]
## Description

We have an issue that occurs without any real reason. There are imports that pass by time and all pass correctly, even tested with the same data. Yet sometimes we get the error from below, which we can't handle on our side, or at least don't see an issue on our side. We're self-hosted and this is a blocker for us to go into production. 

`E20240904 06:31:37.874377    35 backward.hpp:4200] Stack trace (most recent call last) in thread 35:
E20240904 06:31:37.874416    35 backward.hpp:4200] #13   Object "", at 0xffffffffffffffff, in
E20240904 06:31:37.874423    35 backward.hpp:4200] #12   Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7c54f0b2a84f, in
E20240904 06:31:37.874429    35 backward.hpp:4200] #11   Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7c54f0a98ac2, in
E20240904 06:31:37.874434    35 backward.hpp:4200] #10   Object "/opt/typesense-server", at 0x59dffae5f9a3, in execute_native_thread_routine
E20240904 06:31:37.874439    35 backward.hpp:4200] #9  | Source "include/threadpool.h", line 59, in operator()
E20240904 06:31:37.874445    35 backward.hpp:4200]       Source "/usr/include/c++/10/future", line 1592, in ThreadPool [0x59dff8326e1c]
E20240904 06:31:37.874454    35 backward.hpp:4200] #8  | Source "/usr/include/c++/10/future", line 1459, in _M_set_result
E20240904 06:31:37.874473    35 backward.hpp:4200]     | Source "/usr/include/c++/10/future", line 412, in call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*>
E20240904 06:31:37.874490    35 backward.hpp:4200]     | Source "/usr/include/c++/10/mutex", line 729, in __gthread_once
E20240904 06:31:37.874495    35 backward.hpp:4200]       Source "/usr/include/x86_64-linux-gnu/c++/10/bits/gthr-default.h", line 700, in _M_run [0x59dff851a273]
E20240904 06:31:37.874501    35 backward.hpp:4200] #7    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7c54f0a9dee7, in
E20240904 06:31:37.874506    35 backward.hpp:4200] #6  | Source "/usr/include/c++/10/future", line 572, in operator()
E20240904 06:31:37.874511    35 backward.hpp:4200]       Source "/usr/include/c++/10/bits/std_function.h", line 622, in _M_do_set [0x59dff8326032]
E20240904 06:31:37.874519    35 backward.hpp:4200] #5  | Source "/usr/include/c++/10/bits/std_function.h", line 292, in __invoke_r<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<_Fn, _Alloc, _Res(_Args ...)>::_M_run<std::_Bind<Index::batch_memory_index(Index*, std::vector<index_record>&, const string&, const tsl::htrie_map<char, field>&, const tsl::htrie_map<char, field>&, const string&, const std::vector<char>&, const std::vector<char>&, bool, size_t, size_t, size_t, bool, bool, const tsl::htrie_map<char, field>&)::<lambda()>()>, std::allocator<int>, void, {}>::<lambda()>, void>&>
E20240904 06:31:37.874527    35 backward.hpp:4200]     | Source "/usr/include/c++/10/bits/invoke.h", line 115, in __invoke_impl<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<_Fn, _Alloc, _Res(_Args ...)>::_M_run<std::_Bind<Index::batch_memory_index(Index*, std::vector<index_record>&, const string&, const tsl::htrie_map<char, field>&, const tsl::htrie_map<char, field>&, const string&, const std::vector<char>&, const std::vector<char>&, bool, size_t, size_t, size_t, bool, bool, const tsl::htrie_map<char, field>&)::<lambda()>()>, std::allocator<int>, void, {}>::<lambda()>, void>&>
E20240904 06:31:37.874533    35 backward.hpp:4200]     | Source "/usr/include/c++/10/bits/invoke.h", line 60, in operator()
E20240904 06:31:37.874538    35 backward.hpp:4200]     | Source "/usr/include/c++/10/future", line 1397, in operator()
E20240904 06:31:37.874544    35 backward.hpp:4200]     | Source "/usr/include/c++/10/future", line 1456, in __invoke_r<void, std::_Bind<Index::batch_memory_index(Index*, std::vector<index_record>&, const string&, const tsl::htrie_map<char, field>&, const tsl::htrie_map<char, field>&, const string&, const std::vector<char>&, const std::vector<char>&, bool, size_t, size_t, size_t, bool, bool, const tsl::htrie_map<char, field>&)::<lambda()>()>&>
E20240904 06:31:37.874557    35 backward.hpp:4200]     | Source "/usr/include/c++/10/bits/invoke.h", line 110, in __invoke_impl<void, std::_Bind<Index::batch_memory_index(Index*, std::vector<index_record>&, const string&, const tsl::htrie_map<char, field>&, const tsl::htrie_map<char, field>&, const string&, const std::vector<char>&, const std::vector<char>&, bool, size_t, size_t, size_t, bool, bool, const tsl::htrie_map<char, field>&)::<lambda()>()>&>
E20240904 06:31:37.874564    35 backward.hpp:4200]     | Source "/usr/include/c++/10/bits/invoke.h", line 60, in operator()<>
E20240904 06:31:37.874578    35 backward.hpp:4200]     | Source "/usr/include/c++/10/functional", line 499, in __call<void>
E20240904 06:31:37.874588    35 backward.hpp:4200]     | Source "/usr/include/c++/10/functional", line 416, in __invoke<Index::batch_memory_index(Index*, std::vector<index_record>&, const string&, const tsl::htrie_map<char, field>&, const tsl::htrie_map<char, field>&, const string&, const std::vector<char>&, const std::vector<char>&, bool, size_t, size_t, size_t, bool, bool, const tsl::htrie_map<char, field>&)::<lambda()>&>
E20240904 06:31:37.874601    35 backward.hpp:4200]     | Source "/usr/include/c++/10/bits/invoke.h", line 95, in __invoke_impl<void, Index::batch_memory_index(Index*, std::vector<index_record>&, const string&, const tsl::htrie_map<char, field>&, const tsl::htrie_map<char, field>&, const string&, const std::vector<char>&, const std::vector<char>&, bool, size_t, size_t, size_t, bool, bool, const tsl::htrie_map<char, field>&)::<lambda()>&>
E20240904 06:31:37.874612    35 backward.hpp:4200]       Source "/usr/include/c++/10/bits/invoke.h", line 60, in _M_invoke [0x59dff854f916]
E20240904 06:31:37.874624    35 backward.hpp:4200] #4    Source "src/index.cpp", line 653, in operator() [0x59dff854f7b0]
E20240904 06:31:37.874634    35 backward.hpp:4200] #3    Source "src/index.cpp", line 826, in index_field_in_memory [0x59dff854ccae]
E20240904 06:31:37.874642    35 backward.hpp:4200] #2    Source "src/facet_index.cpp", line 104, in insert [0x59dff84a3ba7]
E20240904 06:31:37.874650    35 backward.hpp:4200] #1  | Source "src/facet_index.cpp", line 171, in splice
E20240904 06:31:37.874665    35 backward.hpp:4200]     | Source "/usr/include/c++/10/bits/stl_list.h", line 1596, in splice
E20240904 06:31:37.874672    35 backward.hpp:4200]     | Source "/usr/include/c++/10/bits/stl_list.h", line 1576, in _M_transfer
E20240904 06:31:37.874682    35 backward.hpp:4200]       Source "/usr/include/c++/10/bits/stl_list.h", line 1895, in update_count_nodes [0x59dff84a2207]
E20240904 06:31:37.874691    35 backward.hpp:4200] #0    Object "/opt/typesense-server", at 0x59dffadd80eb, in std::__detail::_List_node_base::_M_transfer(std::__detail::_List_node_base*, std::__detail::_List_node_base*)
Segmentation fault (Address not mapped to object [0x100000001])

Typesense 27.0.rc19 is terminating abruptly.
`

## Steps to reproduce

It occurs randomly, so can't give steps to reproduce it.

## Metadata

**Typesense Version**: Typesense 27.0.rc19

**Comment by kishorenc** [comment]
This issue is fixed on the v27 GA release. Please use actual `27.0` and not this earlier RC build.
