### ISSUE TITLE
Search response different from docs

### ISSUE THREAD

**Issue by Nick-Mazuk** [typesense/typesense#194]
## Description

When searching through documents, the JSON response is different from the docs.

## Steps to reproduce

Any valid search query.

## Behavior

Actual response

```json
{
	"facet_counts": [ ],
	"found": 10000,
	"out_of": 10000,
	"page": 1,
	"request_params": { },
	"search_time_ms": 1,
	"hits": [ ]
}
```

Response according to the docs

```json
{
	"facet_counts": [ ],
	"found": 1,
	"took_ms": 1,
	"hits": [ ]
}
```

_Note: I removed the information inside the `hits`, `facet_counts`, and `request_params` since those were not important._

## Metadata

**Typsense Version**: 0.18 (docker)

**OS**: macOS 11.1

---

Update: found the docs repository, so I'm creating a pull-request right now.

**Comment by jasonbosco** [comment]
Thank you for the PR @Nick-Mazuk!
