### ISSUE TITLE
The hybrid search gives bad results

### ISSUE THREAD

**Issue by irevoire** [typesense/typesense#1964]
## Description

Hello, I was trying out the typesense hybrid search, and I feel like I did something wrong because I don’t get what’s expected at all.

Here's an example of a search where typesense gives really bad results with the full-text search but very good results with the semantic searches:
<img width="1553" alt="image" src="https://github.com/user-attachments/assets/aaa91c3f-cb7a-4683-952d-7f29669b9caf">

You would think that by using the hybrid search, I would get, at the very least, more results coming from the semantic search than from the full-text search.

But no, typesense simply interleaves the bad results with the good results:
<img width="753" alt="image" src="https://github.com/user-attachments/assets/8156bd91-a34d-437e-9b1b-0cc688d0bd5b">

Is this expected? Shouldn’t typesense compare the « scores » of each document and realize that its full-text search was bad and do something about it?

## Metadata

**Typesense Version**: Latest version

**OS**: Linux

**Comment by kishorenc** [comment]
There are multiple ways to do hybrid search (i.e. combine scores from keyword and vector searches), and the approach we have taken is using rank fusion which derives a ranking based on the position of the document in vector search and keyword search. From our experience, any given method to combine the scores will always have a few queries that might not quite work. Our rank fusion implementation does allow you to configure the `alpha` parameter which controls the relative importance of keyword and vector matches -- this can be used to adjust for dataset / query patterns.

**Comment by irevoire** [comment]
So, if I understand correctly, typesense doesn’t take into account _at all_ the results it got from its multiple sources but instead simply picks randomly between each source, right?
Then we can configure which kind of random we want, like interleave the results or something more complex, but whatever we do, we’ll never be able to avoid pushing bad results into the results when one of the two sources is bad, right?

And I was wondering, if both sources rank a document pretty high, will it get a « bonus » and appear first?
For example, let’s say I have something like that:
```
fts semantic
A    E
B    B
C    F
D    G
```

Will the final result put `B` first? Or will it stay in the second position? I hope it doesn’t get duplicated, right?

**Comment by kishorenc** [comment]
> but instead simply picks randomly between each source, right?

No, why would we pick results _randomly_? That's not what I said.

Here's our documentation on [hybrid search](https://typesense.org/docs/27.0/api/vector-search.html#hybrid-search) that goes into how rank fusion works -- it's well supported by most vector databases.

> And I was wondering, if both sources rank a document pretty high, will it get a « bonus » and appear first?

This will depend on the alpha parameter chosen (relative importance between vector and keyword search). Again, please refer to our documentation. All of these concepts are explained in detail.

**Comment by irevoire** [comment]
> No, why would we pick results randomly? That's not what I said.

Yeah, it’s not completely random, obviously, but it doesn’t take into account at all the fact that your full-text search may have found no good matches, but it will still show them like any other results.

> Here's our documentation on [hybrid search](https://typesense.org/docs/27.0/api/vector-search.html#hybrid-search) that goes into how rank fusion works -- it's well supported by most vector databases.

Yeah, I’ve seen this block of code that shows how it’s supposed to work.
```
K = rank of document in keyword search
S = rank of document in semantic search

rank_fusion_score = 0.7 * K + 0.3 * S
```

I was just thinking that the « rank » wasn’t actually related to the order of the documents returned in each search.

For the context, I was trying the hybrid searches with typesense, and this merge algorithm often gave really bad results, so I thought it was an issue with my setup.
I don’t see how tweaking this algorithm could change anything, though. I’ll either get bad results from the semantic search when it doesn’t work well or from the full-text search when it doesn’t work well.
When a query is so bad that the full-text search doesn’t return anything, I guess this mechanism works great.
And it doesn’t work the other way around because the semantic search will always have stuff to return.
