### ISSUE TITLE
Sorting by left joined field

### ISSUE THREAD

**Issue by juliesaia-vendora** [typesense/typesense#1975]
## Description

I'm trying to sort by a joined field while doing a left join. Only some of my documents have a relation present, and I want to sort such that the documents with a relation appear first.

## Steps to reproduce

Left join: 

`filter_by: id:* || $orders(...)`

`sort_by: $orders(totalPrice:desc)`

## Expected Behavior

Returns:

```
[
  {
    name: "Customer with big orders",
    orders: [...]
  },
  {
    name: "Customer with small orders",
    orders: [...]
  },
  {
    name: "Customer with no orders"
  }
]
```

## Actual Behavior

`No references found to sort by on orders.totalPrice.`

## Metadata

**Typesense Version**: 28.0.rc.4

**OS**: Typesense Cloud

**Comment by jasonbosco** [comment]
Could you share a set of curl commands like [this](https://gist.github.com/jasonbosco/7c3432713216c378472f13e72246f46b) that replicates the issue with a minimal dataset?

**Comment by juliesaia-vendora** [comment]
Thanks for the quick reply! Here's a repro.

The expected response here is for the returned customers to be sorted by amount, with "Customer with no order" at the bottom, and "Customer with negative order" omitted.

Removing `sort_by` removes the error, but maybe I'm misunderstanding left joins as "Customer with negative order" is still being returned, even though I have `filter_by: $orders(amount:>0)`.

```
### Run Typesense via Docker ########################################
export TYPESENSE_API_KEY=xyz
    
mkdir "$(pwd)"/typesense-data

docker run -p 8108:8108 \
            -v"$(pwd)"/typesense-data:/data typesense/typesense:27.0 \
            --data-dir /data \
            --api-key=$TYPESENSE_API_KEY \
            --enable-cors

### Reproduction Steps ###############################################
export TYPESENSE_API_KEY=xyz

curl "http://localhost:8108/debug" \
       -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}"


curl "http://localhost:8108/collections" \
       -X POST \
       -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
       -d '{
         "name": "customers",
         "fields": [
           {"name": "name", "type": "string" }
         ]
       }'

curl "http://localhost:8108/collections" \
       -X POST \
       -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
       -d '{
         "name": "orders",
         "fields": [
           {"name": "customer", "type": "string", "reference": "customers.id" },
           {"name": "amount", "type": "int32" }
         ]
       }'

curl "http://localhost:8108/collections/customers/documents/import?action=upsert" \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
        -H "Content-Type: text/plain" \
        -X POST \
        -d '{"id": "124","name": "Customer with large order"}
            {"id": "125","name": "Customer with small order"}
            {"id": "126","name": "Customer with no orders"}
            {"id": "127","name": "Customer with negative order"}'
            

curl "http://localhost:8108/collections/orders/documents/import?action=upsert" \
    -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
    -H "Content-Type: text/plain" \
    -X POST \
    -d '{"id": "124","customer": "124","amount": 1000}
        {"id": "125","customer": "125","amount": 100}
        {"id": "126","customer": "127","amount": -100}'

curl "http://localhost:8108/multi_search" \
        -X POST \
        -H "Content-Type: application/json" \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
        -d '{
          "searches": [
            {
              "collection": "customers",
              "q": "",
              "query_by": "name",
              "filter_by": "(id:* || $orders(amount:>0))",
              "sort_by": "$orders(amount:desc)"
            }
          ]
        }'

### Documentation ######################################################################################
# Visit the API reference section: https://typesense.org/docs/27.0/api/collections.html
# Click on the "Shell" tab under each API resource's docs, to get shell commands for other API endpoints
```

**Comment by jasonbosco** [comment]
Thank you for that. We were able to replicate the issue and fix it. 

The fix will be available in the next RC build sometime next week.

**Comment by juliesaia-vendora** [comment]
amazing!!! you guys are the best :)

**Comment by kishorenc** [comment]
@juliesaia-vendora 

Can you please try on `28.0.rc9`?

**Comment by juliesaia-vendora** [comment]
Really sorry for the late update, we ended up using a separate totalAmount field indexed on the customer field (because we also had to aggregate totals before sorting). So this is less urgent for our specific use case

For this issue though, i just tried the repro script on 28.0.rc12 and I'm still getting `No references found to sort by on orders.amount`

**Comment by happy-san** [comment]
@juliesaia-vendora This shouldn't be possible. That specific error message was removed from the codebase.
https://github.com/typesense/typesense/pull/1979/files#diff-79fee4641c75f547b13f765ad61765e07fc63fc9924e34a918652f7bd954e837L4911-L4912

**Comment by juliesaia-vendora** [comment]
omg so sorry! you're right I was still on the old docker image, sorry about that

issue can be closed :)
