### ISSUE TITLE
Fields with `null` values are now unset during import

### ISSUE THREAD

**Issue by ivan-wolf** [typesense/typesense#1978]
## Description

In `26.0`, when importing a document with fields that have `null` as value, the field was saved as such in the document.
In `27.0`, a field with `null` as value seems to be unset.

## Steps to reproduce

Import a document like the following: `{"id": 1, "name": null}` (`{"upsert": true}`).
Notice that the resulting document is `{"id": 1}`.

## Expected Behavior

The resulting document is not altered (i.e. fields with `null` values are not dropped/unset).

## Actual Behavior

A field with `null` as value is dropped/unset.

## Metadata

**Typesense Version**: 27.0

**OS**: Docker image

**Comment by kishorenc** [comment]
@ivan-wolf 

There was a regression in 27.0 which is fixed in `27.1.rc1` build. We are also going to release a 27.1 version with a few other patches this week.

**Comment by kishorenc** [comment]
Sorry @ivan-wolf I misunderstood the issue earlier (there was another export related issue).

Upsert with a `null` value should actually be seen as deleting that value. So the field should not persist the `null` value sent during the upsert process. This was actually a bug that we fixed in v27.

**Comment by kishorenc** [comment]
> When importing documents with action=upsert, for new documents fields with null values are saved.

Are you sure about this? I just tried and the values were unset when importing with `action=upsert`.

Historically we have always treated `null` values as same as them not existing in the doc. For e.g. to send `null` values, the filed needs to be marked as `optional`. We also don't allow querying/filtering on `null` values. So even if you set the field as `null` you can't actually use that value to query or filter upon.

**Comment by kishorenc** [comment]
> It could be that the behavior only applies to embedded fields

Indeed, this occurs only for nested fields. We should make the behavior uniform with regular fields, which has how it has always been.

**Comment by kishorenc** [comment]
Correct, please create a separate report to correct the anomaly.
