### ISSUE TITLE
Event Rate Limit Issue with Analytics Feature on Self-Hosted Typesense

### ISSUE THREAD

**Issue by angelmarmol** [typesense/typesense#1980]
## Description

I am encountering an issue with the new analytics feature in my self-hosted Typesense instance. Specifically, I receive an "event rate limit reached" message after making only 4-5 event calls within a minute when trying to implement product popularity tracking. This limitation appears to prevent the sending of multiple events in quick succession, which is common when users interact with a product catalog.

## Steps to reproduce

1. Implement an event tracking for product popularity.
2. Make 4-5 calls to the analytics endpoint within a minute.
3. Observe the error message received.

{
    "message": "event rate limit reached."
}

## Expected Behavior

I expect to successfully send multiple analytics events without receiving an "event rate limit reached" message when interacting with the product catalog. Additionally, it would be ideal if the event rate limit value could be made configurable or parametrizable, allowing for adjustments based on the application's needs and user interaction patterns.

## Actual Behavior

The error message received.

{
    "message": "event rate limit reached."
}

## Metadata

**Typesense Version**: 27.0

**OS**: RHEL

**Comment by kishorenc** [comment]
There is a `--analytics-minute-rate-limit` server parameter which you can increase (default is: 5).

**Comment by kishorenc** [comment]
We have to document this: will keep this issue open until then.

**Comment by angelmarmol** [comment]
Thank you for your quick response. It works fine.
