### ISSUE TITLE
AND query mode

### ISSUE THREAD

**Issue by pricj004** [typesense/typesense#20]
## Description

I notice that querying seems to occur using an `OR` operator across query terms. I'd love the option to make it `AND`.

## Steps to reproduce

Using the website `books` demo, search 'harry august'

## Expected Behavior

The only result should be 'The First Fifteen Lives of Harry August`

## Actual Behavior

'The First Fifteen Lives of Harry August' is the first result returned, but it also returns books like 'Harry Potter'. Presumably this is because it matches on _any_ query token (e.g. `OR`) instead of _all_ query tokens (e.g. `AND`).

**Comment by kishorenc** [comment]
@pricj004 Typesense does use`AND` but it also tries to return other results when there are not enough results that match exactly with an `AND` operation. Typesense starts dropping tokens with least individual hits from the original query and thereby expanding the scope of the user query to give additional results. You can see the relevant code here if you are interested:  

https://github.com/typesense/typesense/blob/ebb8d278739a2531816373743cc7a23e0453017f/src/index.cpp#L749

This can be useful in certain cases to offer related results that the user could be interested in. However, I can see how this can be a problem when you don't need this behavior.

Wondering if we made that `Index::SEARCH_LIMIT_NUM` constant configurable, if it would help. Currently that's set to `100` results (i.e. if a query does not have atleast `100` matches we will rewrite/relax the query by dropping the least occurring token). Interested to hear your thoughts here as well.

**Comment by pricj004** [comment]
Oh I see! Yes, if `Index::SEARCH_LIMIT_NUM` was configurable, I could drop it to zero, and that would yield the desired behaviour. Perfect!

**Comment by kishorenc** [comment]
This has been shipped as part of `v0.9.0`:

https://github.com/typesense/typesense/releases/tag/v0.9.0

**Comment by mountain** [comment]
We found similar issue in v0.16.0 and want to customize settings to make the search behavior more like a AND query mode

Could you elaborate more on this Index::SEARCH_LIMIT_NUM in document? I could not found any clue on this except this issue.

**Comment by kishorenc** [comment]
👋 @mountain 

For a given query "foo bar", Typesense first finds all documents that contains both the tokens (i.e. AND mode). When Typesense does not find "enough" documents that contain all the tokens in the query, it expands the search in two ways:

1. Look for tokens that are `num_typos` distance within the tokens. 
2. Try dropping tokens from the query to see if it can surface documents containing only some of the tokens in the query.

You can control the thresholds for these two scenarios via the `typo_tokens_threshold` and `drop_tokens_threshold` search parameters respectively.

If you don't wish to ever return non-exact matches, then just set these two parameters to `0` during querying.

More details are available [on the docs](https://typesense.org/docs/0.16.0/api/#search-collection), screenshot of which is below:

<img width="763" alt="Screenshot 2020-10-30 at 6 03 03 PM" src="https://user-images.githubusercontent.com/782073/97705482-2f148a00-1ada-11eb-8160-a51a7666aace.png">

Happy to elaborate further if you have any further questions/suggestions.

**Comment by mountain** [comment]
@kishorenc Thanks for your detailed explanation, and I will have a try.
