### ISSUE TITLE
Not getting the expected hits when the field value is surrounded by hyphens

### ISSUE THREAD

**Issue by Aaron23145** [typesense/typesense#201]
## Description
When I'm searching a search term and the field value is surrounded by hyphens is not getting matched by Typesense. Seems that it is not treated as a separator character like a whitespace would be.

It's possible that this is the intended behavior, but in some cases would be useful being able to customize this.

## Steps to reproduce

Schema:
```
{
    'name': 'products',
    'fields': [
        {'name': 'internal_id', 'type': 'int64'},
        {'name': 'internal_ref', 'type': 'string'},
        {'name': 'name', 'type': 'string'},
        [Other irrelevant fields...]
    ],
    'default_sorting_field': 'internal_id',
}
```

I have around 1M of documents. Every document has a different `internal_ref`.

I have one specific document whose `internal_ref` value is `54-OR323014`. Even though there's a lot of other documents that start in the same way and vary by only one or two characters.

When I'm searching the following, I'm getting the expected results, all the products that start with the search term.
```
/collections/products/documents/search?q=54-OR323&query_by=internal_ref&include_fields=internal_ref&num_typos=0
```

```
{
  "facet_counts": [],
  "found": 40,
  "hits": [
    {
      "document": {
        "internal_ref": "54-OR32399"
      },
      "highlights": [
        {
          "field": "internal_ref",
          "matched_tokens": [
            "54-OR32399"
          ],
          "snippet": "<mark>54-OR32399</mark>"
        }
      ],
      "text_match": 130560
    },
    [More similar hits...]
  ],
  "out_of": 1091854,
  "page": 1,
  "request_params": {
    "per_page": 10,
    "q": "54-OR323"
  },
  "search_time_ms": 1
}
```

However, I'm also interested in getting products when only searching by the second part of the `internal_ref`. If `54-OR323014` is the complete `internal_ref`, I want to find products by only searching `OR323014` too.

```
/collections/products/documents/search?q=OR323014&query_by=internal_ref&include_fields=internal_ref&num_typos=0
```

## Expected Behavior

I would expect getting at least 1 hit, with the product that has the `54-OR323014` value in its `internal_ref` field.

## Actual Behavior

I don't get any hit.

```
{
  "facet_counts": [],
  "found": 0,
  "hits": [],
  "out_of": 1091854,
  "page": 1,
  "request_params": {
    "per_page": 10,
    "q": "OR323014"
  },
  "search_time_ms": 0
}
```

Another example:
```
/collections/products/documents/search?q=enoic&query_by=name&include_fields=internal_ref,name&num_typos=0
```
```
{
  "facet_counts": [],
  "found": 0,
  "hits": [],
  "out_of": 1091854,
  "page": 1,
  "request_params": {
    "per_page": 10,
    "q": "enoic"
  },
  "search_time_ms": 0
}
```

However, I got a lot of products that contain the `enoic` search term, but they are surrounded by hyphens.
One example of its value: `2-(4-Isobutylphenyl)prop-2-enoic`.

## Metadata

**Typsense Version**: 0.18.0

**OS**: Ubuntu 20.04 LTS

**Comment by jasonbosco** [comment]
@Aaron23145 We currently separate words by spaces and index them. When you do a prefix search (the default mode) only the beginnings of words matched. This is why you're not seeing results for strings that are contained within other words.

The current workaround for this would be to add a space before any tokens that need to be treated as separate words when searching.

In `v0.20` (the version after the one we're currently about to release), we're planning to add the ability to customize the word separator character list. You'll then be able to add `-` to the list to resolve this issue.

**Comment by kishorenc** [comment]
Recent versions of Typesense supports the `token_separators` configuration, which allows one to customize how the words are split.
