### ISSUE TITLE
Error "This plugin does not work with your version of WordPress." with WP 6.3.1

### ISSUE THREAD

**Issue by joshuaiz** [typesense/typesense#2019]
## Description

Cannot activate the plugin because of error:

`This plugin does not work with your version of WordPress.`

Running WordPress 6.3.1 (latest).

## Steps to reproduce

1. Migrated WP site to a new host (WP Engine).
2. Tried to activate the Search with Typesense plugin.
3. Cannot activate because of error mentioned above.

## Expected Behavior

Expected to be able to activate the plugin.

## Actual Behavior

Plugin says `Cannot Activate`.

## Metadata

2.0.6

**OS**:
macOS Sequoia

**Comment by jasonbosco** [comment]
The Wordpress plugin was built by a different team: [Codemanas](https://www.codemanas.com). 

You want to reach out to them for support.

**Comment by joshuaiz** [comment]
@jasonbosco Apologies. My Google-Fu was leading me astray.
