### ISSUE TITLE
Support of JSON and/or blob as a datatype for non-indexed data

### ISSUE THREAD

**Issue by andrewsitt** [typesense/typesense#202]
Hi Jason,

As far as I can see, there's little mention in the documentation about non-indexed fields. It just mentions that fields not in the collection will not be indexed.

What data types can be used in typesense documents for fields which cannot be indexed? Is it the same as those which are indexable, or are more supported?

We'd like to propose support of JSON and/or blob as non-indexed fields, assuming they aren't supported already.

**Comment by jasonbosco** [comment]
Hi @andrewsitt, you can use any data types for the non-indexed fields, even nested fields. 

These non-indexed fields are simply stored on disk and returned in the search results.

**Comment by andrewsitt** [comment]
Thanks @jasonbosco
