### ISSUE TITLE
Search input limit

### ISSUE THREAD

**Issue by grungert** [typesense/typesense#204]
I have noticed that search input works only for the first 10 tokens from the query. Words after are not included in the search. Is there a default limit? Can I change and expand that limit?

**Comment by jasonbosco** [comment]
Hi @grungert Good catch! There is indeed a limit of 10 tokens currently. Our thinking was that, with instant search-as-you-type experiences, users would typically get to the results they're looking for within 10 search tokens. 

Could you expand on your use case for wanting to configure / expand that?

**Comment by grungert** [comment]
Hi @jasonbosco,

I'm working on a project where the data set is large. And, let's call it titles, are long (avg. 30 letters/tokens). And there are similar titles. I'm thinking to use doc2vec for this. 

Anyway, it is amazing code, and I like it. I will use it on some projects. 

But I'm interested in this topic. Is there a way to change that limit? And if yes, is there any impact on performance?

**Comment by jasonbosco** [comment]
@grungert To clarify, the limit on tokens is actually a limit on the number of tokens we highlight, not the number of tokens that are searched for. So it should return all documents, just that we only highlight the first 10 tokens for performance reasons. 

We don't have a way to configure the number of tokens highlighted at the moment.

**Comment by jasonbosco** [comment]
@grungert Please feel free to re-open this issue if you're looking for more than 10 highlights in each search result.
