### ISSUE TITLE
408 when analytics_manager tries to import to popular_queries collection

### ISSUE THREAD

**Issue by ghmattossilva** [typesense/typesense#2040]
## Description

I've created the collection and rule following the steps in this page: https://typesense.org/docs/27.0/api/analytics-query-suggestions.html#when-self-hosting
```
schema = {
  "name": "customTestQueries",
  "fields": [
    {"name": "q", "type": "string" },
    {"name": "count", "type": "int32" }
  ]
}
client.collections.create(schema)
ruleName =  'customTestQueriesAggregation'
ruleConfiguration = {
  "type": "popular_queries",
  "params": {
    "source": {
      "collections": ["customTest"]
    },
    "destination": {
      "collection": "customTestQueries"
    },
    "expand_query": False,
    "limit": 1000
  }
}
client.analytics.rules.upsert(ruleName, ruleConfiguration)
```
When i run a query on the source collection, the logs show:
```
E20241030 13:49:33.112310   186 http_client.cpp:194] CURL timeout. Time taken: 4.00167, method: POST, url: http://10.0.0.70:8108/collections/customTestQueries/documents/import?action=emplace
E20241030 13:49:33.112439   186 analytics_manager.cpp:577] Error while sending popular queries events to leader. Status code: 408, response:
```
When trying to reproduce the error with a curl command, it works and the values are inserted:
```
curl -k "http://localhost:8108/collections/customTestQueries/documents/import?action=emplace" \
      -X POST \
      -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
      -d '{"q": "test", "count": 1}'
```
response: {"success":true}

Typesense is running on docker with commands:
```
--data-dir /data --api-key=xxx--enable-cors  --enable-search-analytics=true --analytics-dir=/data/analytics-data --analytics-flush-interval=60 --log-dir=/logs-data/logs --enable-access-logging=true 
   
```
## Metadata

**Typesense Version**: 27.1

**OS**: ubuntu 22.04

**Comment by rossanodr** [comment]
I'm facing the same issue

**Comment by kishorenc** [comment]
`408` is a timeout status code. The locally aggregated analytics data is sent to the leader (could be the same node in the case of a single node cluster) and this API call has a 4 second timeout. Since you mentioned Docker, check whether there is permission / networking enabling the server to call itself on that IP.

**Comment by ghmattossilva** [comment]
found the issue. analytics_manager was trying to use the wrong network.
setting the --peering-subnet argument correctly fixed the issue
