### ISSUE TITLE
On-Demand Snapshot is blocking other operations

### ISSUE THREAD

**Issue by v-byte-cpu** [typesense/typesense#205]
## Description

Integration tests for golang Typesense client revealed the problem that on-demand snapshot operation blocks other write operations (at least operations to create new collections).

## Steps to reproduce

Comment/remove `t.Skip` [here](https://github.com/typesense/typesense-go/blob/master/typesense/test/operations_test.go#L12). And run all integration tests:

```
go test ./... -tags integration,docker -v
```

```
=== RUN   TestKeysRetrieve                                                                                                                             
--- PASS: TestKeysRetrieve (0.06s)                                                                                                                     
=== RUN   TestSnapshot                                                                                                                                 
--- PASS: TestSnapshot (0.38s)                                                                                                                         
=== RUN   TestVote
    operations_test.go:19: returns false, fix it                           
--- SKIP: TestVote (0.00s)
=== RUN   TestSearchOverrideRetrieve
    override_test.go:12: 
                Error Trace:    dbhelpers.go:205                           
                                                        override_test.go:12 
                Error:          Received unexpected error:                 
                                Post "http://localhost:49539/collections": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                Test:           TestSearchOverrideRetrieve                 
--- FAIL: TestSearchOverrideRetrieve (5.00s)                               
=== RUN   TestSearchOverrideDelete
--- PASS: TestSearchOverrideDelete (0.19s)                                 
=== RUN   TestSearchOverrideUpsertNewOverride                              
--- PASS: TestSearchOverrideUpsertNewOverride (0.09s)                      
=== RUN   TestSearchOverrideUpsertExistingOverride                         
--- PASS: TestSearchOverrideUpsertExistingOverride (0.13s)
```

the first thing the `TestSearchOverrideRetrieve` test does is create a collection. 

## Expected Behavior

Snapshot doesn't block write operations (copy-on-write behavior).

## Actual Behavior

At least create collection request is blocked. 

## Metadata

**Typsense Version**: 0.18.0

**OS**:

not relevant, docker

**Comment by jasonbosco** [comment]
Good catch. Will work on addressing this.

**Comment by jasonbosco** [comment]
@v-byte-cpu Fixed this in the most recent v0.19 RC build. Could you try this out in this docker image: 

```
docker pull typesense/typesense:0.19.0.rc13
```

**Comment by v-byte-cpu** [comment]
I tried with 0.19.0.rc13 tag and tests running after snapshot do not fail. However, two another tests revealed that override upsert operation stopped returning id in response. Nevertheless, this bug seems to be fixed.

**Comment by jasonbosco** [comment]
@v-byte-cpu could you try with the 0.19.0.rc15 tag, fixed the override id issue there.

**Comment by v-byte-cpu** [comment]
@jasonbosco tried with rc15 tag, all tests passed.
