### ISSUE TITLE
Re-elect leader returns false

### ISSUE THREAD

**Issue by v-byte-cpu** [typesense/typesense#206]
## Description

Integration tests for golang Typesense client revealed the problem that vote operation returns false for one node setup.

## Steps to reproduce

Comment/remove `t.Skip` [here](https://github.com/typesense/typesense-go/blob/master/typesense/test/operations_test.go#L20). And run all integration tests:

```
go test ./... -tags integration,docker -v
```

```
=== RUN   TestVote                                                        
    operations_test.go:22:                                                
                Error Trace:    operations_test.go:22
                Error:          Should be true  
                Test:           TestVote                                   
--- FAIL: TestVote (0.00s)
=== RUN   TestSearchOverrideRetrieve
--- PASS: TestSearchOverrideRetrieve (0.09s)                               
=== RUN   TestSearchOverrideDelete
--- PASS: TestSearchOverrideDelete (0.13s)                                 
=== RUN   TestSearchOverrideUpsertNewOverride     
```

## Expected Behavior

Vote operation returns true.

## Actual Behavior

Vote operation returns false.

## Metadata

**Typsense Version**: 0.18.0

**OS**:

not relevant, docker

**Comment by jasonbosco** [comment]
@v-byte-cpu The vote API can only be called on a follower. By initiating new voting, a follower can become a leader. So in a single node setup, the only node is a leader so this API does not apply to it and returns false.

**Comment by v-byte-cpu** [comment]
@jasonbosco good, I will fix the test.
