### ISSUE TITLE
Case sensitive and diacritics search

### ISSUE THREAD

**Issue by hangnm10795** [typesense/typesense#2081]
## Description

Hi team,
I'm trying to apply Typesense on my project and having this issue:
When performing searches in Vietnamese, the current Typesense configuration does not adequately handle:
1. Case sensitivity
2. Diacritical marks (accent-insensitive search) (in Vietnamese there are ` ``´ ~ . ? ă â ã õ ó ò í ì ĩ ị ư ứ ừ ũ,... `

## Steps to reproduce
```
search_parameters = {
  'q' : 'xịt chống nắng',
  'query_by'  : 'name'
}

client.collections['products'].documents.search(search_parameters)
```
**Current Behavior:**
- Search for `xịt chống nắng` only returns exact case matches, and strings contains the exact lowercase phase.
- Search for `xit chong nang` does not return accented variants, and even return unrelated result that does not contains the phase at all. 

## Expected Behavior
Search should return results regardless of:
  1. Case variations (lowercase, uppercase, mixed case). 
  For example: when search for `xịt chống nắng`, results should be:

   - `xịt chống nắng`
   - `Xịt chống nắng`
   - `XỊT CHỐNG NẮNG`
   - `xit chong nang`

  2. Presence or absence of diacritical marks
For example: when search for `xit chong nang`, results should also be:

   - `xịt chống nắng`
   - `Xịt chống nắng`
   - `XỊT CHỐNG NẮNG`
   - `xit chong nang`

## Actual Behavior

1. When search for `xịt chống nắng` or `XỊT CHỐNG NẮNG`, results are:
   - `xịt chống nắng`
   - `Xịt chống nắng`

2. When search for `XỊT CHỐNG NẮNG`, results are:
   - `XỊT CHỐNG NẮNG`

3. When search for `xit chong nang`, results are:
   - `Ích Giáp vương - Hỗ trợ điều trị và phòng ngừa rối loạn chức năng tuyến giáp` 
   (this was in my data set, but does not related to the keyword at all)

## Metadata

**Typesense Version**:
27.1

**OS**:
Windows 10

**Comment by hangnm10795** [comment]
I added the locale for 'vi' out of desperation, even though the documentation did not specify, and it worked. While it doesn't handle the diacritics issue, I'm fine with it for now, so I'll close this issue. Sorry for the inconvenience.

![image](https://github.com/user-attachments/assets/3181007f-34f9-4868-8cde-4a90c05b513f)

**Comment by kishorenc** [comment]
I was just about type about using the locale. Without a locale we remove the diacritics. 

I will add a note to clarify this on the docs page. Thank you.
