### ISSUE TITLE
Create Docker latest release manifest

### ISSUE THREAD

**Issue by stephanoparaskeva** [typesense/typesense#209]
In docker-compose.yml I'm required to do:
` image: typesense/typesense:0.19.0.rc10`

What I'd like to do:
`image: typesense/typesense`

To get the latest image

**Comment by jasonbosco** [comment]
Hi @stephanoparaskeva We don't release images tagged as "latest" because we want to ensure that people don't accidentally end up with a pre-release nightly. We want to be explicit rather than implicit on the versioning.
