### ISSUE TITLE
Backup and restore procedure

### ISSUE THREAD

**Issue by jchaconst1** [typesense/typesense#2124]
Hello, I'm doing tests, but I see that the documentation for backup and restore is very brief and general, is it possible that I am not finding the official restore procedure? Thanks in advance

I'm on version 27.1 and I'm hosting a Typesense cluster on three RHEL machines.

**Comment by jasonbosco** [comment]
Here's the official guide on how to backup and restore: https://typesense.org/docs/guide/backups.html

It really is that simple with a few steps, but if there's any missing information in those steps, please let me know and we can improve the guide based on your feedback.
