### ISSUE TITLE
Number of sorting fields typesense accepts is unclear

### ISSUE THREAD

**Issue by ctorgalson** [typesense/typesense#213]
## Description

I'm not sure if this is a bug or a documentation error, but under [Search a Collection](https://typesense.org/docs/0.18.0/api/#search-collection), the API docs say that "[u]p to 3 sort fields can be specified" with the `sort_by` parameter:

![image](https://user-images.githubusercontent.com/1063424/107012440-4ded8100-6799-11eb-9bd8-480101eeee6c.png)

However actual requests using three sort fields return the http status `400` with the message `Only up to 2 sort fields are allowed`. This happens when using Instantsearch widgets/rest clients with a query like the following:

    http://typesense.project.local/collections/project/documents/search?q=*&query_by=variant&sort_by=poa:asc,price:asc,_text_match:desc

I see the same result when using the (PHP) api almost directly (the command below is a _thin_ wrapper around `typesense/typesense-php`):

![image](https://user-images.githubusercontent.com/1063424/107012968-09161a00-679a-11eb-8a93-920af96b046e.png)

## Steps to reproduce

- Use three fields in the `sort_by` parameter via any method (direct http query, Typesense API use, Instantsearch widgets, etc).

## Expected Behavior

Sorted results :)

## Actual Behavior

    { code: 400, error: "Only upto 2 sort fields are allowed." }

## Metadata

**Typsense Version**:

```yaml
  - 
    Debug:
      state: 1
      version: 0.19.0.rc13 
```

**Note**: the docs I've cited above are for `v0.18.0` since the `0.19.0` docs aren't available yet.

**OS**:

n/a

**Comment by jasonbosco** [comment]
@ctorgalson Good catch! Patched this in `0.19.0.rc16`. Could you confirm that it works locally? 

I can then update your Typesense Cloud cluster with this latest RC build.

**Comment by ctorgalson** [comment]
@jasonbosco Sorry for the delay. Still trying to get the sorting _right_, but I can confirm that I can now use three sorting fields and each new one modifies the sort order (verified in the actual search app as well as directly using that cli tool of ours).

Thanks!

**Comment by e-lobo** [comment]
hello.. may i ask why only 3 are supported?

**Comment by kishorenc** [comment]
Sorting is an expensive operation (especially on large datasets). Typesense is able to sort large number of documents really fast against one/more fields on-the-fly, which gives a lot of flexibility. The downside is that we've to implement some optimizations that restricts the number of fields you can use in each record for tie breaking sort order. 

If you really need to sort on more than 3 values, here's a work around that can work in certain cases: if you are able to "pack" multiple values into a single int64 field, then you can expand the number of fields you can sort on. For e.g. in 8 bytes, you can store 8 1-byte values or 4 2-byte values or 2 4-byte values etc.
