### ISSUE TITLE
cluster upgrade procedure?

### ISSUE THREAD

**Issue by scottf-tvw** [typesense/typesense#214]
## Description
looking for guidance on upgrading a 3 node cluster in production. just in general not a version specific issue.
It would be great to bring down a node, upgrade it and continue on but I am not sure how well that's going to go.
currently we simply upgrade an AMI and re-deploy the instances as a new cluster into the target group after reindexing all of the collections (takes many hours). this also can only be done in a downtime after hours scenario.
looking for just some general advice in the subject for those whom have been doing it. 

## Metadata

**Typsense Version**:
v0.18.0

**OS**:
Ubuntu 16.04.5 LTS in AWS

**Comment by jasonbosco** [comment]
Hi @scottf-tvw,

> It would be great to bring down a node, upgrade it and continue on

This is indeed possible and the recommended way to upgrade versions. This is in fact how we upgrade Typesense Cloud clusters. If you're using RPM / DEB packages, you just need to install the new version of the package and then restart the process.

One particular thing to note is that a 3-node cluster can handle an "outage" of a max of 1 node. So you want to upgrade one node at a time and let it catch up fully with the other 2 nodes, before upgrading the next one.
