### ISSUE TITLE
Question: How to setup high availability with Docker and Nginx

### ISSUE THREAD

**Issue by Nick-Mazuk** [typesense/typesense#216]
## Description

I'm trying to setup a TypeSense cluster with high availability.

Currently, I have TypeSense running in a docker container, and Nginx proxies incoming requests to TypeSense. And when using just one node, this works flawlessly so far.

However, I'm having issues defining the IP addresses for the `--nodes` argument.

```bash
W20210209 05:01:44.249701    77 raft_server.cpp:482] Multi-node with no leader: refusing to reset peers.
I20210209 05:01:49.069952    82 node.cpp:1484] node default_group:172.17.0.2:8107:8108 term 1 start pre_vote
W20210209 05:01:49.070509    82 node.cpp:1494] node default_group:172.17.0.2:8107:8108 can't do pre_vote as it is not in [list of IP addresses, not unlike the example from the guide "192.168.12.1:8107:8108,192.168.12.2:8107:8108,192.168.12.3:8107:8108"]
```

I did remove the specific IP addresses from that log.

In short, it seems like the issue is that because of the Nginx proxy, the IP addresses that the nodes will need to use to communicate with each other are not the actual IP addresses of any one TypeSense image (since all inbound HTTP requests are proxied to localhost).

Has anyone worked through a similar situation?

## Metadata

**Typsense Version**: 0.19.0.rc16 (docker)

**OS**: Ubuntu 20.04

**Comment by Nick-Mazuk** [comment]
## Update

To try to fix this, I substituted each instance's own IP address with the localhost version. This did not work either.

Here's what I mean. Since I'm not sure I want to make the IP addresses public, let's say I have two instances, A and B. Their public IP addresses are AA.AA.AA.AA and BB.BB.BB.BB. In reality, I'm working with 5 nodes, but I think this is equivalent for these purposes.

Originally, the nodes config file was:

```
AA.AA.AA.AA:8017:8108,BB.BB.BB.BB:8017:8108
```
 That setup produced the error from the first message, saying that it couldn't connect because its internal IP address `172.17.0.2:8107:8018` did not exist in the nodes config file.

So on instance A, I replaced its public IP address with the local one.

```
172.17.0.2:8017:8108,BB.BB.BB.BB:8017:8108
```

And the equivalent thing for instance B.

However, this created the following error:

```bash
W20210209 16:47:11.925382    84 node.cpp:1464] node default_group:172.17.0.2:8107:8108 request PreVote from BB.BB.BB.BB:8107:8108 error: [E2][172.17.0.2:8107][E2]peer_id not exist
```

### Attempt 3

Next, I tried setting the `--peering-address` and `--peering-port` arguments. However, this looks like these arguments define the internal IP address, not the external one. So when setting the `--peering-address` to the public IP address AA.AA.AA.AA, TypeSense won't start.

```bash
I20210209 17:07:55.105746     1 typesense_server_utils.cpp:301] Starting Typesense 0.19.0.rc16
I20210209 17:07:55.106432     1 typesense_server_utils.cpp:304] Typesense is using jemalloc.
I20210209 17:07:55.126166     1 typesense_server_utils.cpp:405] Starting API service...
I20210209 17:07:55.130105     1 http_server.cpp:189] Typesense has started listening on port 8108
E20210209 17:07:55.136571    77 server.cpp:955] Fail to listen AA.AA.AA.AA:8107
E20210209 17:07:55.137954    77 typesense_server_utils.cpp:246] Failed to start peering service
```

I feel like I'm just missing something obvious here, and if so, sorry about asking such an obvious quesiton.

**Comment by jasonbosco** [comment]
Hi @Nick-Mazuk, all the docker containers in a cluster need to be able to access each other at the networking layer. There are a [couple of ways](https://docs.docker.com/network/) to do this in Docker, but before diving into that, a couple of questions:

1. Any reason you want to run Typesense using Docker in production, vs using the deb/rpm package directly?
2. Any reason you want to put Typesense behind nginx? I ask because, Typesense comes with a battle-tested HTTP server built-in called H2O (used by the likes of Fastly), and so is designed to be exposed to internet-bound traffic directly, without having to be put behind an nginx reverse proxy. 

Putting 1 & 2 together, you can get a production grade HA setup by just installing the deb/rpm package on 3 or 5 instances and using their private IPs in the nodes file.

**Comment by Nick-Mazuk** [comment]
Hi @jasonbosco,

Those are great questions. I didn't know that TypeSense came with a production-grade HTTP server, which is great! That was the main reason for using Nginx.

As for using Docker, that's mainly to use v0.19, which I know is still not officially out.

**Comment by jasonbosco** [comment]
Ah I see. Here are links to download the deb/rpm packages for the latest 0.19 RC:

https://s3-us-west-2.amazonaws.com/dl.typesense.org/releases/0.19.0.rc17/typesense-server-0.19.0.rc17-1.x86_64.rpm

https://s3-us-west-2.amazonaws.com/dl.typesense.org/releases/0.19.0.rc17/typesense-server-0.19.0.rc17-amd64.deb

Should be much simpler to set these up in prod, compared to docker!

**Comment by v-byte-cpu** [comment]
@jasonbosco 
> Any reason you want to run Typesense using Docker in production, vs using the deb/rpm package directly?

Docker (OCI standards) and Container orchestrators (Kubernetes and Nomad) are the de facto standards for deploying modern production grade systems.

> Any reason you want to put Typesense behind nginx?

Load balancing, TLS termination, etc. It is not related directly to nginx. Another scenario is using Consul cluster to distribute requests to typesense nodes in internal infrastrcture.

**Comment by jasonbosco** [comment]
> Docker (OCI standards) and Container orchestrators (Kubernetes and Nomad) are the de facto standards for deploying modern production grade systems.
> > Any reason you want to run Typesense using Docker in production, vs using the deb/rpm package directly?

Yup yup! Sorry, that was a broad question. I really meant to ask if @Nick-Mazuk was using something like k8s, to necessitate using docker. 

> Load balancing, TLS termination, etc. It is not related directly to nginx. Another scenario is using Consul cluster to distribute requests to typesense nodes in internal infrastructure.

Typesense does have the ability to handle TLS termination and the client libraries have a round-robin + failover mechanism to distribute requests across nodes, which is a simple client-side load-balancing mechanism. But I see your point, if you really needed to, you could also use nginx for server-side load balancing, but that would add another network hop. 

I was mainly trying to point out that you could get a lot of mileage with an RPM/DEB install along with the built-in client-side round-robin mechanism, especially if you don't use k8s / docker in production already.

**Comment by v-byte-cpu** [comment]
> Typesense does have the ability to handle TLS termination and the client libraries have a round-robin + failover mechanism to distribute requests across nodes, which is a simple client-side load-balancing mechanism
Yes, I appreciate that but there are a lot of production-ready battle-tested solutions crafted especially for solving these tasks. I prefer Unix philosophy: Write programs that do one thing and do it well.

**Comment by jasonbosco** [comment]
I like the Unix philosophy in general as well. 

But in the case of Typesense, one of our stated goals is to optimize for low ops overhead, and make it super easy to deploy a production-grade search server, with minimal dependency requirements. This is why we embed a production-grade HTTP server library within the binary. 

That said, there's nothing in the architecture that prevents deploying Typesense in a different production setup. We want to make it easy and convenient for majority of deployments, while still keeping it flexible to use with other pieces of tech.

**Comment by Nick-Mazuk** [comment]
Thanks for the download links, @jasonbosco!

Still having some problems getting the different instances synced up, though. Everything's working fine until I add the nodex configuration file. When adding the nodes file to the configuration, TypeSense won't start up.

For reference, I'm using Ubuntu 20.04 (LTS) x64.

`/etc/typesense/typesense-server.ini`

```ini
[server]

api-address = 0.0.0.0
api-port = 443
data-dir = /var/lib/typesense
api-key = [key]
log-dir = /var/log/typesense
ssl-certificate = /etc/letsencrypt/live/example.com/fullchain.pem
ssl-certificate-key = /etc/letsencrypt/live/example.com/privkey.pem
enable-cors = true
nodes = ~/typesense-nodes.txt
```

`~/typesense-nodes.txt`

```txt
A.A.A.A:8107:443,B.B.B.B:8107:443
```

Again, where A.A.A.A and B.B.B.B are the public ports. Like you could send a request to `A.A.A.A:443/healath` and get the `200` response.

**Comment by Nick-Mazuk** [comment]
> I like the Unix philosophy in general as well.
> 
> But in the case of Typesense, one of our stated goals is to optimize for low ops overhead, and make it super easy to deploy a production-grade search server, with minimal dependency requirements. This is why we embed a production-grade HTTP server library within the binary.
> 
> That said, there's nothing in the architecture that prevents deploying Typesense in a different production setup. We want to make it easy and convenient for majority of deployments, while still keeping it flexible to use with other pieces of tech.

I do think it's great that everything's integrated together. It does make setup really easy (much easier and faster than doing the Nginx/Docker thing I was doing before). Though in the long-run, I think TypeSense should be able to play well with other things. Though it sounds like that's what your aiming for!

**Comment by jasonbosco** [comment]
@Nick-Mazuk in the ini file, could you use an absolute path for the nodes file, instead of a relative path?

```
nodes = /full/path/to/typesense-nodes.txt
```

**Comment by Nick-Mazuk** [comment]
Using the absolute path did fix that problem.

Now, just need to figure out how to open up port 8107. I believe port 443 is working correctly because I can search using HTTPS. Will work on this later this evening.

**Comment by Nick-Mazuk** [comment]
More updates (still working on this on my end), but I haven't gotten it fully working yet. I haven't figured out why port 8107 isn't accessible, so I tried swapping that port out with port 80, which I know is accessible by all instances.

However, that's getting an interesting error when I check the logs:

```bash
W20210210 03:56:05.155315 15163 raft_server.cpp:482] Multi-node with no leader: refusing to reset peers.
I20210210 03:56:06.739459 15172 node.cpp:1484] node default_group:A.A.A.A:80:443 term 12 start pre_vote
W20210210 03:56:06.739593 15172 node.cpp:1494] node default_group:A.A.A.A:80:443 can't do pre_vote as it is not in A.A.A.A:8107:443
```

Notice how it's simultaneously thinking it's on port 80 and port 8107. I've double-checked, and I've definitely removed all mentions of port 8107.

Furthermore, the `/health` route is returning a 503 error.

**Comment by jasonbosco** [comment]
The nodes file only tells Typesense the other nodes it needs to peer with, it doesn't configure its own peering port. 

If you need to change the peering port to 80, you want to add

```
peering-port = 80
```

to `/etc/typesense/typesense-server.ini` on all the nodes.

**Comment by Nick-Mazuk** [comment]
Thanks @jasonbosco. I should have mentioned that I did add the peering-port to the in file already.

> In clustered-mode, if a majority of nodes are down, then the cluster returns a 503 to prevent split-brain situations.

That makes perfect sense!

**Comment by jasonbosco** [comment]
Could you post the content of the nodes file and ini file from each of the nodes?

**Comment by Nick-Mazuk** [comment]
### Node A

Ini file

```ini
; Typesense Configuration

[server]

api-address = 0.0.0.0
api-port = 443
data-dir = /var/lib/typesense
api-key = [api key]
log-dir = /var/log/typesense
ssl-certificate = /etc/letsencrypt/live/example.com/fullchain.pem
ssl-certificate-key = /etc/letsencrypt/live/example.com/privkey.pem
enable-cors = true
peering-address = A.A.A.A
peering-port = 80
nodes = /root/typesense-config/nodes.txt
```

/root/typesense-config/nodes.txt

```txt
A.A.A.A:80:443,B.B.B.B:80:443,C.C.C.C:80:443,D.D.D.D:80:443,E.E.E.E:80:443
```

### Node B

Ini file

```ini
; Typesense Configuration

[server]

api-address = 0.0.0.0
api-port = 443
data-dir = /var/lib/typesense
api-key = [api key]
log-dir = /var/log/typesense
ssl-certificate = /etc/letsencrypt/live/example.com/fullchain.pem
ssl-certificate-key = /etc/letsencrypt/live/example.com/privkey.pem
enable-cors = true
peering-address = B.B.B.B
peering-port = 80
nodes = /root/typesense-config/nodes.txt
```

/root/typesense-config/nodes.txt

```txt
A.A.A.A:80:443,B.B.B.B:80:443,C.C.C.C:80:443,D.D.D.D:80:443,E.E.E.E:80:443
```

### Node C

Ini file

```ini
; Typesense Configuration

[server]

api-address = 0.0.0.0
api-port = 443
data-dir = /var/lib/typesense
api-key = [api key]
log-dir = /var/log/typesense
ssl-certificate = /etc/letsencrypt/live/example.com/fullchain.pem
ssl-certificate-key = /etc/letsencrypt/live/example.com/privkey.pem
enable-cors = true
peering-address = C.C.C.C
peering-port = 80
nodes = /root/typesense-config/nodes.txt
```

/root/typesense-config/nodes.txt

```txt
A.A.A.A:80:443,B.B.B.B:80:443,C.C.C.C:80:443,D.D.D.D:80:443,E.E.E.E:80:443
```

### Node D

Ini file

```ini
; Typesense Configuration

[server]

api-address = 0.0.0.0
api-port = 443
data-dir = /var/lib/typesense
api-key = [api key]
log-dir = /var/log/typesense
ssl-certificate = /etc/letsencrypt/live/example.com/fullchain.pem
ssl-certificate-key = /etc/letsencrypt/live/example.com/privkey.pem
enable-cors = true
peering-address = D.D.D.D
peering-port = 80
nodes = /root/typesense-config/nodes.txt
```

/root/typesense-config/nodes.txt

```txt
A.A.A.A:80:443,B.B.B.B:80:443,C.C.C.C:80:443,D.D.D.D:80:443,E.E.E.E:80:443
```

### Node E

Ini file

```ini
; Typesense Configuration

[server]

api-address = 0.0.0.0
api-port = 443
data-dir = /var/lib/typesense
api-key = [api key]
log-dir = /var/log/typesense
ssl-certificate = /etc/letsencrypt/live/example.com/fullchain.pem
ssl-certificate-key = /etc/letsencrypt/live/example.com/privkey.pem
enable-cors = true
peering-address = E.E.E.E
peering-port = 80
nodes = /root/typesense-config/nodes.txt
```

/root/typesense-config/nodes.txt

```txt
A.A.A.A:80:443,B.B.B.B:80:443,C.C.C.C:80:443,D.D.D.D:80:443,E.E.E.E:80:443
```

**Comment by jasonbosco** [comment]
Thanks Nick. So the issue is that the old config has been cached in the cluster's state, so it's still trying to connect to the old set of nodes. Could you do the following in this order: stop all the nodes, then start just one node without the `nodes` key in the config file, wait for a few minutes for it to become healthy (this will clear its config cache, since you're effectively starting it as a single node cluster). Then stop the node, uncomment the `nodes` key in the config file and start it back up. Then if you start all the nodes back it _should_ work. 

On a side note, hopefully this is just for testing - I'd highly recommend not using port 80 as the peering port.

**Comment by Nick-Mazuk** [comment]
Thanks a ton, Jason. Finally got it working! And I was able to move it back to 8107 instead of 80.
