### ISSUE TITLE
Multi-Search does not work with API key

### ISSUE THREAD

**Issue by Nick-Mazuk** [typesense/typesense#217]
## Description

When using the `/multi_search` endpoint with a restricted API key, it returns a 401 error.

```json
{
    "message": "Forbidden - a valid `x-typesense-api-key` header must be sent."
}
```

This is likely an issue with the API key since doing the same query with the master API key succeeds. This may be because I created the API key incorrectly, but I don't think so.

## Steps to reproduce

I created an API key with the JS client.

```js
const response = await client.keys().create({
  actions: ['documents:search'],
  collections: ['music'],
  description: 'Front-end search'
})

console.log(response)
// {
//   actions: [ 'documents:search' ],
//   collections: [ 'music' ],
//   description: 'Front-end search',
//   expires_at: 64723363199,
//   id: 0,
//   value: 'restricted_api_key'
// }
```

Next, try searching

```bash
curl --request POST \
  --url 'https://example.com/multi_search \
  --header 'Content-Type: text/plain' \
  --header 'X-Typesense-API-Key: restricted_api_key' \
  --data '{
    "searches": [
      {
        "q": "John",
        "query_by": "title",
        "collection": "music"
      }
      ]
    }'
```

## Expected Behavior

The same response as using the master API key:

```json
{
    "results": [
        {
            "facet_counts": [],
            "found": 0,
            "hits": [],
            "out_of": 0,
            "page": 1,
            "request_params": {
                "per_page": 10,
                "q": "John"
            },
            "search_time_ms": 0
        }
    ]
}
```

## Actual Behavior

The 401 unauthorized response.

## Metadata

**Typsense Version**: 0.19.0.rc17

**OS**: Ubuntu 20.04 (LTS) x64

**Comment by jasonbosco** [comment]
@Nick-Mazuk To narrow the issue, could you try creating a key with collections set to `*`, to see if that works?

```
const response = await client.keys().create({
  actions: ['documents:search'],
  collections: ['*'],
  description: 'Front-end search'
})
```

**Comment by Nick-Mazuk** [comment]
Setting collections to `*` works.

In case it helps, I also tried a few other combinations just now.

### Succeeds

```js
const response = await client.keys().create({
  actions: ['documents:search'],
  collections: ['*'],
  description: 'Front-end search'
})
```

```js
const response = await client.keys().create({
  actions: ['*'],
  collections: ['*'],
  description: 'Front-end search'
})
```

### Fails

```js
const response = await client.keys().create({
  actions: ['*'],
  collections: ['music', 'blogs'], // all the collections in TypeSense
  description: 'Front-end search'
})
```

```js
const response = await client.keys().create({
  actions: ['documents:search'],
  collections: ['music', 'blogs'], // all the collections in TypeSense
  description: 'Front-end search'
})
```

**Comment by jasonbosco** [comment]
Great, thank you for that. Looking into it...

**Comment by kishorenc** [comment]
@Nick-Mazuk Can you please try against `typesense/typesense:0.19.0.rc19` -- should be fixed.

**Comment by Nick-Mazuk** [comment]
@kishorenc Yep, it works on rc19! Thanks a lot!

**Comment by andycansdale** [comment]
I'm getting the same issue with Typesense Cloud. When restricting API keys by collection, it's always throwing a 401 even when all collections needed by the federated search are included. Cloud is at v0.20.0.

**Comment by jasonbosco** [comment]
Could you share a code snippet like this that replicates the issue: https://github.com/typesense/typesense/issues/217#issuecomment-776973115

Could you also share the output of `/keys` for the parent search API Key?

**Comment by andycansdale** [comment]
@jasonbosco Thanks for your quick reply. My situation is an exact replica of Nick's comment. The only thing that changes are the names of my collections.

Here is the keys output redacted for privacy. The first key with collections "*" works and the last one fails with a 401:

```
{
  "keys": [
    {
      "actions": [
        "documents:search"
      ],
      "collections": [
        "*"
      ],
      "description": "Search Only key [Generated from Typesense Cloud]",
      "expires_at": 64723363199,
      "id": 1,
      "value_prefix": "xxx"
    },
    {
      "actions": [
        "*"
      ],
      "collections": [
        "*"
      ],
      "description": "Admin key",
      "expires_at": 64723363199,
      "id": 11,
      "value_prefix": "xxx"
    },
    {
      "actions": [
        "documents:search"
      ],
      "collections": [
        "agents",
        "listings",
        "locations"
      ],
      "description": "Scoped search key",
      "expires_at": 64723363199,
      "id": 12,
      "value_prefix": "xxx"
    }
  ]
}
```

My intention is to eventually create a scoped api key using include_fields to allow us to have a single collection for both public and private usage, but only allow public access to non-sensitive data with the public scoped key on our website and use a different key for our internal searches which can include the sensitive data using exclude_fields or no scoping at all.

However I've not been able to do a basic scope by collections yet.

**Comment by jasonbosco** [comment]
I vaguely remember us fixing another related issue in a recent version since 0.20, so I'd recommend upgrading to the latest release 0.23.1 to see if that already fixes this issue. You can schedule a version upgrade in Typesense Cloud, by visiting the cluster's dashboard, visit "Overview" -> Configuration -> Modify Configuration -> Pick an Upgrade Window.

**Comment by jasonbosco** [comment]
@andycansdale Mind opening a new Github issue with this question (so it's easy to find for future searchers)?
