### ISSUE TITLE
default sorting field

### ISSUE THREAD

**Issue by Geoffry304** [typesense/typesense#218]
Hello, can we change the order of the default sorting field?
When i'm not sorting the default order seems to be desc and I want it to be asc.

Thanks in advance
Regards
Geoffry

**Comment by jasonbosco** [comment]
@Geoffry304 The default sort order is 

`_text_match:desc,default_sorting_field:desc`

If you need to override this, you'd have to specify the `sort_by` field explicitly in your query like this: 

`_text_match:desc,field_x:asc`

**Comment by jasonbosco** [comment]
Feel free to re-open the issue, if you have additional questions.

**Comment by Geoffry304** [comment]
Hello, thanks for the response and sorry for the late answer :).

It is working when I specify the `sort_by` field but when I do that the ais-sort-by component is not selecting the correct sort field.

For example the default filtering is on  `endDate:desc`, but I want it to be endDate:asc, so I change the `sort_by` to: 
`_text_match:desc,endDate:asc` 
But the ais-sort-by stays on the `endDate:desc` filter and on the call to typesense is with the `endDate:asc` filter
