### ISSUE TITLE
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at xxx (Reason: CORS request did not succeed)

### ISSUE THREAD

**Issue by fedden** [typesense/typesense#219]
## Description
Hi there 👋  

First of all this looks like a fantastic library. Thanks for making it open source. I'm hoping to build a great demonstration of how to combine it with supabase.

However I'm running into CORS errors when using the JS client and I'm not sure where I've gone wrong. I'm not the worlds biggest web whizz so could be making some rookie error, but I'm a little stumped. 

Basically in a sentace, in the Python client (or via curl) I can successfully query data _and_ run the health check.

On a different machine with the JS client, I am running into what appear to be CORS errors as the headers are not properly configured. I get the following error in the console:
```bash
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://greyhound-compute.duckdns.org:8108/collections/properties/documents/search?query_by=url,price,address,space,latitude,longitude&sort_by=&highlight_full_fields=url,price,address,space,latitude,longitude&q=*&facet_by=&filter_by=&page=1. (Reason: CORS request did not succeed).
```

## Steps to reproduce
This is what I use to start the server (args in curly braces are substituted for the real values):
```bash
docker run                      \
  -p {port}:{port}              \
  -v {db_path}:/data            \
  typesense/typesense:0.18.0    \
  --data-dir /data              \
  --api-key={typesense_api_key} \
  --enable-cors                 \
  --listen-port {port}
```

Note I enable CORS (I think) via the parameters.

I can then check the health via python (and print the headers):
```python
    result = requests.get(f"http://localhost:{port}/health")
    print(
        {"status_code": result.status_code, **result.json(), "headers": result.headers}
    )
```

This gives me the following stdout (I'm looking for CORS related stuff):
```js
{'status_code': 200, 'ok': True, 'headers': {'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'content-type': 'application/json; charset=utf-8', 'content-encoding': 'gzip', 'vary': 'accept-encoding', 'accept-ranges': 'none', 'transfer-encoding': 'chunked'}}
```
Note that we see `access-control-allow-origin': '*',` so this output looks good to me.

However, when I connect via my JS client though (on different machine running a dev npm server), I see the following:

<img width="1440" alt="Screenshot 2021-02-17 at 01 15 09" src="https://user-images.githubusercontent.com/11923487/108142408-9e2fe180-70bd-11eb-96d4-3e791866df1a.png">

I'm not seeing the `Access-Control-Allow-Origin: *` line present in the headers of the requests. This appears to be the case for all requests in my browser. I think this is problematic for me and is causing issues accessing my collections.

I'd be deeply appreciative of any thoughts or directions to take on this.

## Expected Behavior

Expected behaviour is that the JS client would receive successful responses to the requests made. 

## Actual Behavior

The JS client appears to have a CORS issue, possibly related to bad headers. Likely a user error on my part. The Python client can both succesfully query data and run the health check, and the relavant headers appear to be present.

## Metadata

**Typsense Version**:
docker image `typesense/typesense:0.18.0`
**OS**:
Ubuntu for server, Mac OS for JS client

**Comment by jasonbosco** [comment]
Hi @fedden, thank you for the detailed report! Could you send me the HAR file from the screenshot you shared? I'm curious to see what the request/response looks like for those options requests.

**Comment by fedden** [comment]
Brill thanks for the timely response @jasonbosco 

> Also, just in case, could you try this on typesense/typesense:0.19.0 and if you're using the Typesense InstantSearch adapter, upgrade to v1.0.0 (we just released these today).

So I've updated the instant search adapter (npm output):
```bash
(base) ➜  frontend git:(develop) ✗ npm update

> typesense-instantsearch-adapter@1.0.0 postinstall /Users/leonfedden/dev/mitto/frontend/node_modules/typesense-instantsearch-adapter
> node scripts/postinstall.js

Note: v1.0.x of typesense-instantsearch-adapter only works with Typesense Server v0.19.x and above.
npm WARN @chakra-ui/checkbox@1.1.3 requires a peer of framer-motion@>=3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @chakra-ui/menu@1.0.6 requires a peer of framer-motion@>=3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @chakra-ui/modal@1.4.5 requires a peer of framer-motion@>=3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @chakra-ui/popover@1.1.0 requires a peer of framer-motion@>=3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @chakra-ui/react@1.1.6 requires a peer of framer-motion@>=3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @chakra-ui/toast@1.1.7 requires a peer of framer-motion@>=3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @chakra-ui/tooltip@1.0.6 requires a peer of framer-motion@>=3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @chakra-ui/transition@1.0.6 requires a peer of framer-motion@>=3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN algoliasearch-helper@3.4.4 requires a peer of algoliasearch@>= 3.1 < 5 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-apply-mdx-type-prop@1.6.22 requires a peer of @babel/core@^7.11.6 but none is installed. You must install peer dependencies yourself.
npm WARN react-instantsearch-core@6.9.0 requires a peer of algoliasearch@>= 3.1 < 5 but none is installed. You must install peer dependencies yourself.
npm WARN stylis-rule-sheet@0.0.10 requires a peer of stylis@^3.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN typesense-instantsearch-adapter@1.0.0 requires a peer of @babel/runtime@^7.10.2 but none is installed. You must install peer dependencies yourself.
npm WARN typesense@0.11.1 requires a peer of @babel/runtime@^7.10.2 but none is installed. You must install peer dependencies yourself.
npm WARN frontend No repository field.
npm WARN frontend No license field.

+ typesense-instantsearch-adapter@1.0.0
updated 2 packages and audited 1231 packages in 6.501s
```

And I've updated the docker command to:
```bash
docker run                      \
  -p {port}:{port}              \
  -v {db_path}:/data            \
  typesense/typesense:0.19.0    \
  --data-dir /data              \
  --api-key={typesense_api_key} \
  --enable-cors                 \
  --listen-port {port}
```

Hopefully I'm up to date now..

Unfortunately I'm still running into these errors:
<img width="1440" alt="Screenshot 2021-02-17 at 10 10 45" src="https://user-images.githubusercontent.com/11923487/108189613-d6104680-7108-11eb-8e56-833a469057ae.png">

-------------

> Could you send me the HAR file from the screenshot you shared? I'm curious to see what the request/response looks like for those options requests.

Yea sure. Hopefully this is alright, first time I've done that. You should see requests to https://greyhound-compute.duckdns.org:8108/multi_search?x-typesense-api-key=o31JBqjb9H0fh that are relevant to typesense.

For context the greyhound url is a DDNS url to my local server as my local IP is dynamic and can't make it static.

[localhost_Archive [21-02-17 10-13-01].har.zip](https://github.com/typesense/typesense/files/5994894/localhost_Archive.21-02-17.10-13-01.har.zip)

Thanks for looking into this, let me know if you need anything else

**Comment by jasonbosco** [comment]
I unfortunately don't see any request or response headers in the HAR file for requests made to Typesense.

In any case, I updated [this demo repo](https://github.com/typesense/typesense-instantsearch-demo) locally to use http://greyhound-compute.duckdns.org:8108 as the Typesense node and it worked without errors in Chrome, Firefox, Safari and Opera. So I'm wondering what else could be unique about your environment that might cause this issue... 

Could you also try cloning the above repo, updating the typesense node config and query_by fields  in app.js and see if you run into the cors issue?

If you don't run into issues with that app, could you isolate the parts of your app from which this issue can be replicated, push it to a github repo and share it with me? I can then run it locally to debug the issue.

**Comment by fedden** [comment]
Wow thanks for such a dilligent detailed response. Really appreciate it. I updated the src/app.js of the typesense demo repo to look like the following:
<img width="723" alt="Screenshot 2021-02-17 at 23 38 09" src="https://user-images.githubusercontent.com/11923487/108282325-579fbd00-7179-11eb-8c00-807685218220.png">

And subsequently saw the same issues crop up:
<img width="1440" alt="Screenshot 2021-02-17 at 23 37 57" src="https://user-images.githubusercontent.com/11923487/108282359-62f2e880-7179-11eb-9e0a-8a05a93c9a06.png">

So must be something to do with my environment. Perhaps something to do with how I'm on the same network as my server (even though I used the DDNS url rather than the public IP?). 

Anyway I appreciate you digging into this. I'll let you know if I land on a solution, let me know if you have any directions you think would be worth taking - I certainly appreciate your clarity with the previous solutions and general experience here 🙂

**Comment by jasonbosco** [comment]
Happy to help!

In the `host` field in app.js, could you remove `http://` and just use `greyhound-compute.duckdns.org`? I'm curious if you still see the CORS error after that.

**Comment by Xetera** [comment]
Leaving this here in case it helps someone else.
It seems the docs are a bit misleading, the `--enable-cors` command doesn't actually enable cors. You specifically have to set `TYPESENSE_ENABLE_CORS=true` in your environment variables to get the server to respond with cors headers.
