### ISSUE TITLE
Documentation for Running In-Process?

### ISSUE THREAD

**Issue by loic-sharma** [typesense/typesense#22]
## Running In-Process

Hello, I have a dataset that is roughly 1.5 million documents. Today, this dataset is stored in a SQL database and is accessed through a single web server. Would typesense be a good candidate for in-process search on this dataset? If so, is there documentation on how to do this?

**Comment by Braunson** [comment]
I'm also interested in hearing from others and the authors of typesense if this is an ideal candidate for larger data sets. I'm looking to move a project 5-10k records initially but it will grow to 5+ million very shortly. There would be over a dozen filters and later I'd need something that would be able to return 'sets' of results based on the filters. Is that even viable or possible right now?

**Comment by kishorenc** [comment]
@loic-sharma - Take a look at [`main.cpp`](https://github.com/typesense/typesense/blob/master/src/main/main.cpp) to see how you can use it in-process. Summary: you need to initialize a `CollectionManager` and use it to create a `Collection`. Then you can perform operations on the `collection` object. Please note that these classes are not thread-safe as they have been designed to work with the non-blocking single threaded HTTP server that Typesense exposes. Internally, they create their own threads for parallelism during searching alone.

@Braunson - Should easily be able to handle upto 10M records. I've just not tried indexing more than that. The other things you have mentioned sounds fine as well.

Happy to help further online/offline.

**Comment by kishorenc** [comment]
Closing this for now -- feel free to reopen if needed.

**Comment by loic-sharma** [comment]
Thanks @kishorenc!
