### ISSUE TITLE
[Feature request] Support index document `set`

### ISSUE THREAD

**Issue by goleary** [typesense/typesense#225]
I'd like to be able to overwrite whatever is in the index for a given id, or if there is nothing in the index for that id then set it.

From my understanding `upsert` will create, or "update" but I don't want to run this risk of mixing data from different operations, so I'd prefer to know that I'm overwriting everything that is in the index for a given key.

Today I am performing a delete followed by a create, but I'd love to be able to avoid submitting multiple requests for this type of operation.

**Comment by inluxc** [comment]
Do you mean an AddOrReplace method, that's im looking for.
I currently migrating from Meilisearch and this is one of the missing options i have.

**Comment by kishorenc** [comment]
I've already fixed this. I can build and post a RC build here tomorrow.

**Comment by kishorenc** [comment]
@inluxc @goleary 

I've fixed the `upsert` behavior to require all fields so `upsert` now essentially becomes replace. Partial updates can still be done with the `?action=update` flag as before.  You can test this feature in this Docker build:

```
typesense/typesense:0.21.0.rc18
```

**Comment by seowzhenjun0126** [comment]
Hi @kishorenc , may I know when will this be available in Typesense Cloud? Thanks!

**Comment by kishorenc** [comment]
@seowzhenjun0126 Please email us (contact at typesense org) -- we can upgrade your cluster to a recent stable RC build containing this fix.

**Comment by seowzhenjun0126** [comment]
@kishorenc  Sure thing! Thanks

**Comment by kishorenc** [comment]
Shipped in `0.21.0` release.

**Comment by goleary** [comment]
Thank you @kishorenc !!
