### ISSUE TITLE
[Feature request] Support tokenization of words in queries (handles queries missing spaces).

### ISSUE THREAD

**Issue by goleary** [typesense/typesense#230]
If you have a document with an indexed field "blue origin" and you query with "blueorigin" this document will not be returned by TypeSense. I understand this to be due to a lack of tokenization of substrings of the query.

For comparison, Algolia handles this type of query gracefully.

**Comment by artt** [comment]
Sounds related to #228

**Comment by goleary** [comment]
That was my initial reaction @artt, although after talking with @jasonbosco he felt it was different enough that it warranted a separate issue.  I'll let him weigh in on why that is.

**Comment by kishorenc** [comment]
We've discussed the issue of splitting/joining query tokens on https://github.com/typesense/typesense/issues/133 -- just need to get to it and also figure out what will be a reasonable limit on the various permutations this will generate as search tokens.
