### ISSUE TITLE
What is the API client for Go ?

### ISSUE THREAD

**Issue by 0uep** [typesense/typesense#231]
Hi
Le link "API client for Go" in the README.md points to `https://github.com/typesense/typesense`.
What is the API client for Go ?
Moreover, is there an API client for Rust ?

**Comment by jasonbosco** [comment]
@0uep Fixed the link. Meant for it to be: https://github.com/typesense/typesense-go

We don't have an API client for Rust at the moment, but we're open to contributions! Let me know if you're interested in collaborating on it.

**Comment by 0uep** [comment]
Thank you very much :+1:
I do not know yet Rust.
But if I use TypeSense I may contribute to my required features because I was a pretty good C++ developer (from 1999 to C++17) before adopting Python & Go.

**Comment by kishorenc** [comment]
@0uep I welcome you to contribute to the cpp code if the opportunity presents :)
