### ISSUE TITLE
Api Return Relevance Score

### ISSUE THREAD

**Issue by rlcyf** [typesense/typesense#232]
halo!

Is it possible to return the score in the search api？

just like ES "_score" value
```
POST /my_index/my_type/_search
{
   "query": {
      "match_phrase": {
         "title": {
            "query": "quick dog",
            "slop":  50 #1
         }
      }
   }
}
```

Response
```
{
"hits": [
{
"_id": "3",
"_score": 0.75, #1
"_source": {
"title": "The quick brown fox jumps over the quick dog"
}
},
{
"_id": "2",
"_score": 0.28347334, #2
"_source": {
"title": "The quick brown fox jumps over the lazy dog"
}
}
]
}


```

**Comment by kishorenc** [comment]
Yes we return a 'match_score' value in the response that is the text relevance score. If you are using other sorting fields, then the results won't be ordered on text mach but each record in the response will still have that value.

**Comment by rlcyf** [comment]
> Yes we return a 'match_score' value in the response that is the text relevance score. If you are using other sorting fields, then the results won't be ordered on text mach but each record in the response will still have that value.

ths!
I went to see
