### ISSUE TITLE
doesnt match if the whitespace characters between two tokens are missing in the search query. 

### ISSUE THREAD

**Issue by dingusagar** [typesense/typesense#235]
## Description
There can be situations where the user types the query and misses the whitespace between two words. 
This is technically a typo and typesense is expected to give the matches. But I am getting no matches. 

## Steps to reproduce
data in collection : [ "Combo Earrings" , ..]
search query : comboearrings
    
search_parameters = {
        'q': 'comboearrings',
        'query_by': 'title',
        'sort_by': '_text_match:desc'
    }

## Expected Behavior

I expected to see some match to the data in the collections. Ideally it should match with the product name "Combo Earrings"

## Actual Behavior

There is no match happening to any results. 

## Metadata

**Typsense Version**: 0.19.0

**OS**:  Ubuntu 20.04.2.0 LTS (Focal Fossa)

**Comment by kishorenc** [comment]
@dingusagar Thanks for creating this issue. This is definitely on our roadmap, and also previously raised/discussed in 

- https://github.com/typesense/typesense/issues/230
- https://github.com/typesense/typesense/issues/133

Certainly going to get prioritised now with so much asks :)

**Comment by dingusagar** [comment]
Okay thanks for the reply. waiting for this enhancement to come out!

**Comment by kishorenc** [comment]
This is fixed in `v0.23`.
