### ISSUE TITLE
Prefer original spelling

### ISSUE THREAD

**Issue by nickdbush** [typesense/typesense#242]
## Description

Currently, it seems that typos are given the same weighting as the original spelling in the query (although I could be wrong). This means that there have been multiple occasions in which results with a clear text match come far beneath many irrelevant corrections.

## Expected Behavior

The specific matches should take precedence over typo matches. For a similar, MeiliSearch's docs describe that "Results are sorted by increasing number of typos: find documents that match query terms with fewer typos first". I am aware that they utilise a different architecture and that this may not be feasible to implement within Typesense's structure. However, that approach does seem like a more accurate reflection of the intents of the user. For some highly specific words, scrubbing through multiple pages of pagination seems unwieldy.

## Actual Behavior

The results are mixed, leading to situations in which auto-corrections have higher text match scores than results that perfectly matches the query.

## Metadata

**Typsense Version**: 0.19.0

**OS**: Docker image, Windows

This is an amazing project and I am so genuinely thankful for the work that you share with us!

**Comment by nickdbush** [comment]
Ah seems like this could be a dupe of #191 (although that isn't concerned with typos as much as the length of strings, but the crux of exact matching seems to be shared). Happy to close this and add comments over there if you think they're related.

**Comment by jasonbosco** [comment]
Hi @nickdbush, thank you for reporting this. #191 is slightly different than this one. This does sound similar to an issue reported by another user via email just this past week. 

While we do weight exact matches first ahead of ones with typo corrections, I suspect there's an issue when several query_by fields are used, where typo-corrected terms across fields (their aggregated scores) end up drowning the field with the exact match. 

To be sure, would you be able to share a sample dataset and the full search query you're using, that replicates this issue? 

If you'd prefer to share the dataset privately, could you email it to contact at typesense dot org?

**Comment by nickdbush** [comment]
Have forwarded along some example queries and connection details!

**Comment by jasonbosco** [comment]
Got it. Thanks Nick. This is also closely related to #243 and #191. @kishorenc is looking into all three of them. Will keep you posted.

**Comment by kishorenc** [comment]
@nickdbush Can you please try again with typesense/typesense:0.20.0.rc28 Docker image?

**Comment by nickdbush** [comment]
This issue appears to be fixed in 0.20.0.rc28 - thanks @kishorenc!
