### ISSUE TITLE
query by multiple fields (1 string type and 1 string[] type ) not giving expected results. 

### ISSUE THREAD

**Issue by dingusagar** [typesense/typesense#243]
## Description
Even when the exact query is present in the collection, its only coming up second in the response. I am wondering why is the text match score of an exact match lower than that of a partialy matching string. This happend when I tried to use the query by multiple fields feature in typesense.

## Steps to reproduce
    There are two fields in my collection that I want to query by,  The fields are 
            {'name': 'city_name', 'type': 'string'},
            {'name': 'synonyms', 'type': 'string[]'},

I have records in my collection like this: 
{'city_name' : 'Bengaluru', 'synoynms' : [ 'Banglore', Bangalore'] } , 
{'city_name' : 'Mumbai', 'synoynms' : [ 'Bombay'] }
{'city_name' : 'Madurai', 'synoynms' : [ 'Madura'] }
{'city_name' : 'Chennai', 'synoynms' : [ 'Madras'] }

and my search query is like this:

    search_parameters = {
        'q': 'madras',
        'query_by': 'city_name,synonyms',
        'query_by_weights': '1,1',
        'sort_by': '_text_match:desc'
    }

## Expected Behavior
for the query "madras", the best match should  be {'city_name' : 'Chennai', 'synoynms' : [ 'Madras'] } because the exact query "Madras" is present in synonyms field in the record.

## Actual Behavior

for the query "madras", the best match is coming as a match to the record {'city_name' : 'Madurai', 'synoynms' : [ 'Madura'] }.
Ideally I would expect the best match to be {'city_name' : 'Chennai', 'synoynms' : [ 'Madras'] } because the exact query "Madras" is present in synonyms field in the record.

The match to the {'city_name' : 'Chennai', 'synoynms' : [ 'Madras'] } only comes in the second position of the list of matches. 

## Metadata

**Typsense Version**:
0.19.0

**OS**:
Ubuntu 20 LTS

**Comment by kishorenc** [comment]
Thanks for reporting this issue. This is happening because the matches across multiple fields are overpowering the exact match. I'm looking into accounting for this. Stay tuned.

**Comment by dingusagar** [comment]
Thanks for the quick reply. waiting for the update.

**Comment by kishorenc** [comment]
@dingusagar Can you please try with the `typesense/typesense:0.20.0.rc28` Docker image?

**Comment by dingusagar** [comment]
sure, will check and update here

**Comment by dingusagar** [comment]
hi, I have verified the fix from the docker image you shared. it seems to be working fine. thanks for the fix.

**Comment by kishorenc** [comment]
Glad to hear, thanks for confirming

**Comment by kishorenc** [comment]
Addressed as part of `v0.20.0` released last week.
