### ISSUE TITLE
Creating a specific key

### ISSUE THREAD

**Issue by fbergroth** [typesense/typesense#244]
## Description

I would like to be able to specify a specific key for searching, like `--search-only-api-key`, but it's been marked deprecated and doesn't seem to work either. It seems keys created via the key management endpoint are always randomly generated.

I'm using typesense for read-only data, and sometimes I reload the data with another snapshot. Instead of mutating the existing collection, I would like to simply start from scratch, create the collection, fill it with data, and re-create the same key for searching.

Is there any way to do this?

Cheers!

**Comment by fbergroth** [comment]
In an attempt to work around this, I think I'm hitting a bug where loading a snapshot causes a crash.

- start typesense in an empty directory
- create a new key
- create a snapshot
- kill the server
- start typesense pointing to snapshot directory

```
# typesense-server -d /tmp/typesense-data-snapshot/
I20210316 14:12:51.097334   109 typesense_server_utils.cpp:301] Starting Typesense 0.19.0
I20210316 14:12:51.097393   109 typesense_server_utils.cpp:304] Typesense is using jemalloc.
I20210316 14:12:51.129885   109 typesense_server_utils.cpp:405] Starting API service...
I20210316 14:12:51.129899   183 typesense_server_utils.cpp:210] Since no --nodes argument is provided, starting a single node Typesense cluster.
I20210316 14:12:51.130095   109 http_server.cpp:189] Typesense has started listening on port 8108
I20210316 14:12:51.138459   183 server.cpp:1045] Server[braft::RaftStatImpl+braft::FileServiceImpl+braft::RaftServiceImpl+braft::CliServiceImpl] is serving on port=8107.
I20210316 14:12:51.138495   183 server.cpp:1048] Check out http://37508ce2cbd8:8107 in web browser.
I20210316 14:12:51.139473   183 log.cpp:674] Use crc32c as the checksum type of appending entries
I20210316 14:12:51.139565   183 log.cpp:1158] log load_meta /tmp/typesense-data-snapshot//state/log/log_meta first_log_index: 1 time: 67
I20210316 14:12:51.139640   183 log.cpp:1098] load open segment, path: /tmp/typesense-data-snapshot//state/log first_index: 1
I20210316 14:12:51.139818   183 raft_meta.cpp:521] Loaded single stable meta, path /tmp/typesense-data-snapshot//state/meta term 2 votedfor 172.20.0.2:8107:8108 time: 26
I20210316 14:12:51.139967   183 raft_meta.cpp:521] Loaded single stable meta, path /tmp/typesense-data-snapshot//state/meta term 2 votedfor 172.20.0.2:8107:8108 time: 19
I20210316 14:12:51.139987   183 node.cpp:576] node default_group:172.20.0.2:8107:8108 init, term: 2 last_log_id: (index=2,term=2) conf: 172.20.0.2:8107:8108 old_conf: 
I20210316 14:12:51.140038   183 node.cpp:1549] node default_group:172.20.0.2:8107:8108 term 2 start vote and grant vote self
I20210316 14:12:51.144158   183 raft_meta.cpp:546] Saved single stable meta, path /tmp/typesense-data-snapshot//state/meta term 3 votedfor 172.20.0.2:8107:8108 time: 3533
I20210316 14:12:51.144192   183 node.cpp:1783] node default_group:172.20.0.2:8107:8108 term 3 become lead
er of group 172.20.0.2:8107:8108 
I20210316 14:12:51.144240   183 typesense_server_utils.cpp:261] Typesense peering service is running on 172.20.0.2:8107
I20210316 14:12:51.144255   183 typesense_server_utils.cpp:262] Snapshot interval configured as: 3600s
I20210316 14:12:51.144273   183 raft_server.cpp:430] Term: 3, last_index index: 2, committed_index: 0, known_applied_index: 0, applying_index: 0, pending_index: 3, disk_index: 2, pending_queue_size: 1
W20210316 14:12:51.144296   183 node.cpp:811] [default_group:172.20.0.2:8107:8108 ] Refusing concurrent configuration changing
E20210316 14:12:51.144392   189 raft_server.h:57] Peer refresh failed, error: Doing another configuration change
I20210316 14:12:51.147850   192 raft_server.h:245] Configuration of this group is 172.20.0.2:8107:8108
E20210316 14:12:51.377612   109 backward.hpp:4196] Stack trace (most recent call last):
E20210316 14:12:51.377631   109 backward.hpp:4196] #14   Object "/bin/typesense-server", at 0x86ab30, in _start
E20210316 14:12:51.377637   109 backward.hpp:4196] #13   Object "/lib/x86_64-linux-gnu/libc-2.28.so", at 0x7f5cbb00d09a, in __libc_start_main
E20210316 14:12:51.377660   109 backward.hpp:4196] #12   Source "/typesense/src/main/typesense_server.cpp", line 124, in main [0x7b1d1f]
E20210316 14:12:51.377663   109 backward.hpp:4196] #11   Source "/typesense/src/typesense_server_utils.cpp", line 408, in run_server [0x98ae92]
E20210316 14:12:51.377667   109 backward.hpp:4196] #10   Source "/typesense/src/http_server.cpp", line 195, in run [0x92f720]
E20210316 14:12:51.377671   109 backward.hpp:4196] #9    Source "/typesense/external-Linux/h2o-5accc794404996fb056f1826f5a172693de95f22/lib/common/socket/evloop.c.h", line 619, in h2o_evloop_run [0x9aa0d4]
E20210316 14:12:51.377676   109 backward.hpp:4196] #8    Source "/typesense/external-Linux/h2o-5accc794404996fb056f1826f5a172693de95f22/lib/common/socket/evloop.c.h", line 567, in run_pending [0x9a92e5]
E20210316 14:12:51.377679   109 backward.hpp:4196] #7  | Source "/typesense/external-Linux/h2o-5accc794404996fb056f1826f5a172693de95f22/lib/common/socket/evloop.c.h", line 534, in read_on_ready
E20210316 14:12:51.377683   109 backward.hpp:4196]       Source "/typesense/external-Linux/h2o-5accc794404996fb056f1826f5a172693de95f22/lib/common/socket/evloop.c.h", line 248, in run_socket [0x9a91f8]
E20210316 14:12:51.377687   109 backward.hpp:4196] #6  | Source "/typesense/external-Linux/h2o-5accc794404996fb056f1826f5a172693de95f22/lib/common/multithread.c", line 90, in queue_cb
E20210316 14:12:51.377693   109 backward.hpp:4196]       Source "/typesense/external-Linux/h2o-5accc794404996fb056f1826f5a172693de95f22/lib/common/multithread.c", line 64, in h2o_buffer_consume [0x9a782d]
E20210316 14:12:51.377699   109 backward.hpp:4196] #5    Source "/typesense/include/http_data.h", line 412, in on_message [0x9347eb]
E20210316 14:12:51.377705   109 backward.hpp:4196] #4    Source "/typesense/src/core_api.cpp", line 1115, in raft_write_send_response [0x916899]
E20210316 14:12:51.377712   109 backward.hpp:4196] #3    Source "/typesense/src/core_api.cpp", line 1047, in post_create_key [0x92333b]
E20210316 14:12:51.377717   109 backward.hpp:4196] #2    Source "/typesense/src/auth_manager.cpp", line 96, in create_key [0x875887]
E20210316 14:12:51.377722   109 backward.hpp:4196] #1  | Source "/typesense/src/auth_manager.cpp", line 129, in increment
E20210316 14:12:51.377727   109 backward.hpp:4196]     | Source "/typesense/include/store.h", line 189, in shared_lock
E20210316 14:12:51.377730   109 backward.hpp:4196]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/shared_mutex", line 722, in lock_shared
E20210316 14:12:51.377734   109 backward.hpp:4196]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/shared_mutex", line 421, in lock_shared
E20210316 14:12:51.377740   109 backward.hpp:4196]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/shared_mutex", line 224, in __glibcxx_rwlock_rdlock
E20210316 14:12:51.377745   109 backward.hpp:4196]       Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/shared_mutex", line 73, in get_next_api_key_id [0x872dd8]
E20210316 14:12:51.377751   109 backward.hpp:4196] #0    Object "/lib/x86_64-linux-gnu/libpthread-2.28.so", at 0x7f5cbb33ea00, in __pthread_rwlock_rdlock
Segmentation fault (Address not mapped to object [0x418])
Segmentation fault (core dumped)
```

**Comment by kishorenc** [comment]
>  I would like to simply start from scratch, create the collection, fill it with data, and re-create the same key for searching.

There is no way to specify a key explicitly, except for the master key. Would aliases help you here? 

https://typesense.org/docs/0.19.0/api/collection-alias.html

With an alias, you can essentially start from scratch on a new collection and just update the alias to swap to the new collection atomically and then drop the old collection after that. 

> In an attempt to work around this, I think I'm hitting a bug where loading a snapshot causes a crash.

Thanks for reporting this. I'm able to reproduce and will look into what's happening here.

**Comment by fbergroth** [comment]
> Would aliases help you here?

Thanks, I had missed aliases. I can make it work with aliases and a persistent disk, but I would much rather load the latest data and recreate keys on a fresh instance, and then do a rolling update once indexing is finished.

Ideally I would like to be able to pass the actual key when creating keys. Maybe it can be optional, and randomly generated if missing. I can probably work around it by creating a snapshot with a single key, and bootstrapping from there, if the crashing issue is fixed.

> Thanks for reporting this. I'm able to reproduce and will look into what's happening here.

Great, thanks!

**Comment by cboothe** [comment]
If providing an API key was possible we could move over from other Search solutions that already have API keys generated.

**Comment by kishorenc** [comment]
@cboothe Could you expand on your use case for wanting to re-use the same API key from another search engine with Typesense? Curious to understand the context behind this so we can design a good solution.

**Comment by cboothe** [comment]
Thanks  @kishorenc ideally we would like to migrate public/private keys generated from Elastic App Search.
https://www.elastic.co/guide/en/app-search/current/credentials.html#credentials-create

Another use case is we currently use the same public key for search access and event + search tracking using another service API. If we could share the API keys by generating them in Typesense then the data could be migrated over and continue to work without customer interruption.

**Comment by cboothe** [comment]
@kishorenc I see you are busy working on 0.20.0-rc 
Did this change make the cut?

**Comment by kishorenc** [comment]
The issue of the crash with snapshot is fixed on `typesense/typesense:0.20.0.rc25` Docker build. cc @fbergroth 

@cboothe But, I presume you are talking about the ability to specify a custom key as well? 0.20 is not done yet so I will see if I can squeeze that in on a RC build by next week.

**Comment by cboothe** [comment]
@kishorenc Yes, that was my question. Timing of the feature "specifying a custom key". Either release 0.20 or sometime after that

**Comment by kishorenc** [comment]
@cboothe This is now available in `typesense/typesense:0.20.0.rc28` Docker image.

Example usage:

```
curl -X POST -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -H 'Content-Type: application/json' -d '{"value": "eXsDhaPQh2aYjaBLhUsb", "description":"Test key.","actions":["*"], "collections": ["companies"]}'  'http://localhost:8108/keys'
{"actions":["*"],"collections":["companies"],"description":"Test key.","expires_at":64723363199,"id":0,"value":"eXsDhaPQh2aYjaBLhUsb"}
```

**Comment by cboothe** [comment]
@kishorenc Thanks! I just tried it with rc28 and although the API key is created. I am not able to create a collection or search with the new key.

Example value: public-f327-4728-ad88-7d5408c85f13

{
  "description":"Test value",
  "value": "public-f327-4728-ad88-7d5408c85f13",
  "actions": ["*"], 
  "collections": ["aro_2_6e65772d636f6c6c656459123"]
}

Error: {
  "message": "Forbidden - a valid `x-typesense-api-key` header must be sent."
}

With the "xyz" API key that the server was started with I get 
{
  "facet_counts": [],
  "found": 0,
  "hits": [],
  "out_of": 0,
  "page": 1,
  "request_params": {
    "collection_name": "aro_2_6e65772d636f6c6c656459485",
    "per_page": 10,
    "q": "test"
  },
  "search_time_ms": 0
}

**Comment by fbergroth** [comment]
It works for me, thanks!

Perhaps you did not set `$TYPESENSE_API_KEY` @cboothe

**Comment by kishorenc** [comment]
Thanks for confirming @fbergroth 

@cboothe I just tried again and it works. Try the following:

```
$ curl -X POST -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -H 'Content-Type: application/json' -d '{"value": "eXsDhaPQh2aYjaBLhUsb", "description":"Test key.","actions":["*"], "collections": ["companies"]}'  'http://localhost:8108/keys'

$ export TYPESENSE_API_KEY=eXsDhaPQh2aYjaBLhUsb

$ curl -k "http://localhost:8108/collections" -X POST -H "Content-Type: application/json" \ 
      -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{
        "name": "test_collection", "num_memory_shards": 4,
        "fields": [
          {"name": ".*", "type": "auto"}
        ]
      }'
```

**Comment by cboothe** [comment]
Yes this works but my example has letters and hyphens in it which does not work. Do you support strings as API keys? Or only numeric?

The create command works fine. It is when I try to use it that it fails.

**Comment by kishorenc** [comment]
@cboothe Alphanumeric works. I've used the sample key you had above. Here is the sequence that I tried and which works:

```
curl -X POST -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -H 'Content-Type: application/json' -d '{"value": "public-f327-4728-ad88-7d5408c85f13", "description":"Admin key.","actions":["*"], "collections": ["*"]}'  'http://localhost:8108/keys'

TYPESENSE_API_KEY="public-f327-4728-ad88-7d5408c85f13" curl -k "http://localhost:8108/collections" -X POST -H "Content-Type: application/json" \
-H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{
        "name": "test_collection", "num_memory_shards": 4,
        "fields": [
          {"name": ".*", "type": "auto"}
        ]
      }'

TYPESENSE_API_KEY="public-f327-4728-ad88-7d5408c85f13" curl -k -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" "http://localhost:8108/collections/test_collection/documents/search?q=*"
```

If you can reproduce the issue you are facing as a set of CURL commands as above, it will be helpful.

**Comment by cboothe** [comment]
@kishorenc Thanks for confirming the key string is going to work. When I use your sequence it works but not with my own.
Switched to image: typesense/typesense:0.20.0.rc33

I am assuming that creating the key for a collection before it exists is ok?

`
curl -X POST -H "X-TYPESENSE-API-KEY: xyz" -H 'Content-Type: application/json' -d '{"value": "public-f327-4728-ad88-7d5408c85h15", "description":"Admin key.","actions":["*"], "collections": ["test_collection3"]}'  'http://localhost:8108/keys'      

curl -k "http://localhost:8108/collections" -X POST -H "Content-Type: application/json" \
-H "X-TYPESENSE-API-KEY: xyz" -d '{
        "name": "test_collection3", "num_memory_shards": 4,
        "fields": [
          {"name": ".*", "type": "auto"}
        ]
      }'

# Fails (Key that was created to access the collection)
curl "http://127.0.0.1:8108/collections/test_collection3/documents/search?q=*" -H "X-TYPESENSE-API-KEY: public-f327-4728-ad88-7d5408c85h15"

{"message": "Forbidden - a valid `x-typesense-api-key` header must be sent."}

# Works (Key that created the collection)
curl "http://127.0.0.1:8108/collections/test_collection3/documents/search?q=*" -H "X-TYPESENSE-API-KEY: xyz"

{"facet_counts":[],"found":0,"hits":[],"out_of":0,"page":1,"request_params":{"collection_name":"test_collection3","per_page":10,"q":"*"},"search_time_ms":0}
`

**Comment by kishorenc** [comment]
Ah, I figured out what's going on here 🤦 We were using the size of the fixed length auto generated keys  (32 chars) to determine if the key is a scoped search key (base64 encoded) or a regular API key. Now with custom keys, obviously someone could create a API key longer than 32 chars. I will have a fix for this shortly.

**Comment by kishorenc** [comment]
@cboothe Please try against `typesense/typesense:0.20.0.rc39`.

**Comment by cboothe** [comment]
Works! Thanks @kishorenc 
This is a great addition to the feature set.

**Comment by kishorenc** [comment]
Addressed as part of `v0.20.0` released last week.

**Comment by zehawki** [comment]
I guess this is am undocumented feature? I also came looking for a way to set a specific search key, and I see that a method is available. Its a really important feature. Please add to docs.

**Comment by kishorenc** [comment]
@zehawki It's documented [here](https://typesense.org/docs/0.22.1/api/api-keys.html#arguments). Screenshot below:

<img width="770" alt="Screenshot 2022-01-24 at 7 00 42 AM" src="https://user-images.githubusercontent.com/782073/150708098-41c1ec0c-37e2-48da-9605-bdbbe916ed34.png">

**Comment by zehawki** [comment]
Thank you @kishorenc! My stupidity - I just looked at the code snippet and not the table right below. Sheeesh 😳
