### ISSUE TITLE
User Favorites/Likes - Using Scoped API Keys or Multi Search?

### ISSUE THREAD

**Issue by mcunningham** [typesense/typesense#245]
Hi there! I have somewhat of a unique use case and wondering if Typesense could be used for it.

I have a database of products that users have the ability to "favorite" each product. In my search results UI, I want to display a favorite/like button alongside each result in the search and it should show the favorites state when searching. So for instance if a user favorited a specific product then when that product shows up as a search hit at any point, there is some flag/other way to tell if the user who is searching has favorited that specific product. A favorite is not specific to an individual user, the same product could be favorited by different user.

In Postgres I can do this with a favorites bridge table which can track both product id and user id which liked it. For search, it seems a bit trickier. Is there any config for Typesense that could help here?

I have looked at Typesense scoped api keys, which seem to be able to scope on a user level by filtering the results,  however I still want to display all the results, just have a flag set if the given user who is searching has liked the product. 

If not scoped api keys, Maybe would Federated / Multi Search be able to help with this?

**Comment by jasonbosco** [comment]
Hi @mcunningham, interesting use case! You could implement this by:

1. Adding a field called say `favorited_by_users: [user_id_1, user_id_2, ...]` to every product record. 
2. Then you'd do two search queries - one that uses `filter_by=favorited_by_users:current_user_id` and another that doesn't use this filter. You can send both these queries in a multi-search query.
3. Then when you get the results for both queries, you'd union and de-dupe the results based on the product ID.

One caveat to this is that you'd probably want to not expose the list of user_ids that have liked a product to your end users. To solve for this, you can use a Scoped API Key and embed the `exclude_fields` search parameter in it, to make sure that the `favorited_by_users` is not returned as part of the document in search results.

**Comment by mcunningham** [comment]
Hey @jasonbosco thanks for the reply. I will definitely try out that approach. In regard to de-duping could that be possible with a [group_by](https://typesense.org/docs/0.19.0/api/documents.html#group-by) in the `commonSearchParams` from your Federated/Multi Search [docs example](https://typesense.org/docs/0.19.0/api/documents.html#federated-multi-search)? For example in the query below. Or would that just de-dupe the individual requests separately?  
```js
let searchRequests = {
  searches: [
    {
      collection: "products",
      q: "shoe",
      filter_by: "favorited_by_users:current_user_id",
    },
    {
      collection: "products",
      q: "shoe",
    },
  ],
};

// Search parameters that are common to all searches go here
let commonSearchParams = {
  group_by: "id",
  group_limit: "1",
};

client.multiSearch.perform(searchRequests, commonSearchParams);


```

**Comment by jasonbosco** [comment]
`commonSearchParams` is actually just syntactic sugar to list all parameters that are common to all searches in a batch in one place. Each search query is still executed independently. So the code example above just translates to:

```javascript

// Search Query 1
{
  collection: "products",
  q: "shoe",
  filter_by: "favorited_by_users:current_user_id",
  group_by: "id",
  group_limit: "1",
}

// Search Query 2
{
  collection: "products",
  q: "shoe",
  group_by: "id",
  group_limit: "1",
}
```

Multi search is a way to batch multiple (still independent) search queries, in a single HTTP request.

Said another way, `group_by` and `group_limit` unfortunately won't work because they're applied on a per search query basis.

So the de-duping needs to be done on your side once you have the results from both queries.

**Comment by mcunningham** [comment]
Ok yeah makes sense. I will try it out de-duping on the client. Appreciate your help @jasonbosco, closing this

**Comment by tyuwan** [comment]
@mcunningham, I am in a similar situation, how well does this scale? We have over 10k-50k of likes per a product. Sorry for opening this up again.
