### ISSUE TITLE
Windows - Native Binary Download

### ISSUE THREAD

**Issue by mcunningham** [typesense/typesense#246]
Is there a windows binary available to run locally without using docker? Similar to the macOS and linux packages? If not, is there any way I can export/package the server for a windows machine to run locally without the need of additional containers?

**Comment by kishorenc** [comment]
👋 @mcunningham There is no native package for Windows. There will be significant effort involved in porting to Windows, and I'm not very familiar with the Windows tool chain.

**Comment by jasonbosco** [comment]
@mcunningham I haven’t tried this myself, but you could theoretically use [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) to run the Typesense Linux binary on Windows.

Would be curious if this works for Typesense.
