### ISSUE TITLE
Non-alphanumeric ascii characters not searchable

### ISSUE THREAD

**Issue by ctorgalson** [typesense/typesense#249]
## Description

We're searching a largish index, that contains occasional product names containing non-alphanumeric characters like `+`. E.g. `Lorem Ipsum+`.

While we get those records back in the search, and while we can sort them to the top of the results (using a numeric weight field), we don't seem able to explicitly search for them.

I'm unclear if this is [Typesense ignoring non-alphanumeric characters for good reasons](https://github.com/typesense/typesense/issues/241#issuecomment-798471212) or if this is Typo tolerance (as we've had similar issues with two-character model variants like e.g. searches for `windows xp` returning  `windows` in results).

So mostly, I have questions:

- does it sound like we've overlooked anything in the docs?
- does this sound like we're bumping up against character-indexing limitations or typo-tolerance?
- if this _is_ something Typesense can't do for the moment, is it on the roadmap?

## Steps to reproduce

The screenshot shows the output of a cli tool we're using that's a _very_ thin wrapper around `typesense/typesense-php` v4.5.0.

![image](https://user-images.githubusercontent.com/1063424/112997541-809a7100-916d-11eb-9b3c-ad2ac1ecc15a.png)

## Expected Behavior

Results containing `+` only.

## Actual Behavior

All results :)

## Metadata

**Typsense Version**: 0.19.0

**OS**: linux (varies from prod to local)

**Comment by kishorenc** [comment]
@ctorgalson Typesense does not index special characters, and that's on our immediate list of things to handle. We want to provide an option to allow certain special characters to be indexed and searched upon. This is a priority for us so we will support this soon.

The issue with `windows xp` might be because of https://github.com/typesense/typesense/issues/242 which is already fixed in nightly and will be part of the next release.

**Comment by ctorgalson** [comment]
Thanks for the info @kishorenc! 

We'll try out the nightly (or at least the next release), and wait for news about the special characters.

**Comment by Khatunzev-Anton** [comment]
Hi, we have similar issue with searchterms in filter_by option. The following query
collections/companies/documents/search?q=*&filter_by=rootfield__document_uri:="di-r_3"&include_fields=rootfield__document_uri
returns items with rootfield__document_uri "dir3","dir_3","di-r_3". Waiting for the solution in next release
