### ISSUE TITLE
Feature: Add option to enabled highlighting on excluded fields

### ISSUE THREAD

**Issue by alexkreidler** [typesense/typesense#252]
## Description

I have a field `dimension_values` with type `[]string`. It is usually a very long array with fairly long string values.

The responses I was getting from Typesense were fairly large (1MB, 400KB), so I added  `dimension_values` to the `excluded` query parameter. This reduced the request size to ~7KB and made the UI much snappier.

However, the search query often returns results in those excluded fields. Right now there is no other way to indicate that the result is in an excluded field (this might be another good thing to add separately).

I want to show the users highlighting for the excluded fields, so that they know the result is correct. 

## Expected

There should be an option like `highlight_excluded_fields` which returns the `highlights` array for the matches on the excluded fields, but excluded fields should stay excluded.

I know that #106 made a change to the behavior: "We also now don't highlight excluded fields even if it is queried on." Hopefully it is not too difficult to add this option.

Thanks for such a great tool!

#### Version Info:
<summary>
<details>

**Typsense Version**:
0.19.0

**OS**:
Docker 19.03 on Ubuntu 20.04

</details>
</summary>

**Comment by kishorenc** [comment]
Thanks for creating issue. I think this is a great use case, and I will add this option.

**Comment by tao** [comment]
If I understand the issue correctly, then I believe this is something that my website also requires.

We have a lot of articles with a `content` field... this can be sometimes 1000 ~ 4000+ words. I want to perform a search and show the highlighted sentence from the article... but I don't want the `result.document.content` field to be included because it is such a large document.

So in this case, I just want the highlight for `content` if it exists but don't want to include the original `content` field in the response.

**Comment by tao** [comment]
For example: the response size of my search requests is around `14MB` for 10 documents with the `content` field included... so only returning the `content` highlight if it exists would cut down the response size massively.

**Comment by kishorenc** [comment]
We have added a way to allow highlighting of excluded fields. There's now a `?highlight_fields=x,y,z` parameter that you can use to specify a list of fields that should be highlighted. 

So, you can now even highlight fields that are not being queried on. Feature available on this Docker build: 

`typesense/typesense:0.21.0.rc19` -- please try it out and let me know how it works.

**Comment by tao** [comment]
It seems like it's working for me, my response sizes are around 3KB now, that's so much better than before.

**Comment by kishorenc** [comment]
Shipped in `0.21.0` release.
