### ISSUE TITLE
[Feature request] unretrievable fields

### ISSUE THREAD

**Issue by reinoldus** [typesense/typesense#255]
Unretrievable fields that can be used for ranking but can't be retrieved using the public api key would be of great benefit

Similar to:
https://www.algolia.com/doc/api-reference/api-parameters/unretrievableAttributes/

**Comment by jasonbosco** [comment]
Hi @reinoldus, you can already do this by embedding the `exclude_fields` search parameter in a scoped key. More details here: https://github.com/typesense/typesense/issues/193#issuecomment-765878863
