### ISSUE TITLE
Index and Search multiple value fields?

### ISSUE THREAD

**Issue by kokizzu** [typesense/typesense#256]
## Description

I found no example on the docs, can TypeSense index and query multiple values/array of string, for example:
```
name: "Ted",
favoriteProgrammingLanguage: ["C++","C","Go"]
```
or nested Map/Object?
```
name: "Mosby",
skills: {"C++":6, "C":8, "Go": 9}
```

or we have to flatten it?

**Comment by kishorenc** [comment]
@kokizzu Yes, Typesense can index a multi-value array. In the schema, define the type of the field as `string[]`. Example:

```
curl "http://localhost:8108/collections" -X POST -H "Content-Type: application/json" -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{                                                                                             255 ↵
         "name": "companies",
         "fields": [
           {"name": "company_name", "type": "string" },
           {"name": "num_employees", "type": "int32" },
           {"name": "countries", "type": "string[]", "facet": true }
         ],
         "default_sorting_field": "num_employees"
       }'
```

Typesense does not index a dictionary or nested fields though: they have to be flattened out.

**Comment by thomaslobjoie** [comment]
@kishorenc When you say it has to be flatten out, does that mean the response will look like:

`"document": {
      "countries": "France,Canada,USA",
      "company_name": "My great company",
      "id": "entity:node/4:en",
      "num_employees": 10,
}`

Is a comma the default separator?

**Comment by kishorenc** [comment]
@thomaslobjoie 👋 What I meant is that Typesense cannot index a value which itself is a dictionary. For example, in this document:

```
{
    "person": {
       "age": 21,
       "name": "Jack"
   }
}
```

It's not possible to ask Typesense to index the `name` inside the `person` object. You will have to flatten out the document like this:

```
{
  "person.age": 21,
  "person.name": "Jack"
}
```

**Comment by thomaslobjoie** [comment]
Ok, but that is not really what I am trying to do at the moment. I will rephrase.

I am trying to create a multi value field in typesense, the schema for that field will be:

```{"name": "countries", "type": "string[]", "facet": true }```

Will the result of that field be:

```
"countries": "France,Canada,USA"
```

**Comment by kishorenc** [comment]
The result will be array:

> "countries": ["France", "Canada", "USA"]

**Comment by JayabharathiP** [comment]
How to search on multi-valued fields like this, is there a way to find empty value [] using search query

"countries": ["France", "Canada", "USA"]

**Comment by jasonbosco** [comment]
@JayabharathiP Here's an example from the docs. If genres is a `string[]` field:

- genres:=[Rock, Pop] will return documents where the genres array field contains Rock OR Pop.
- genres:=Rock && genres:=Acoustic will return documents where the genres array field contains both Rock AND Acoustic.

There is no way to search for documents with an empty array value unfortunately.
