### ISSUE TITLE
[Feature Request] Add the possibility to disable highlights

### ISSUE THREAD

**Issue by RomainLanz** [typesense/typesense#260]
Hey there! 👋 

## Description

In our case, we do not need to have `highlights` entry inside the results given by TypeSense.
I believe it would be great to add a flag to disable entirely the `highlights`.

## Expected Behavior

Being able to disable the `highlights`.

## Actual Behavior

`highlights` are being returned for any results.

## Metadata

**Typsense Version**: 0.20.0.rc42

**OS**: Docker for Windows

**Comment by kishorenc** [comment]
@RomainLanz Thanks for suggesting this feature. Would just ignoring the highlights key in the response be okay? I want to know if there is any constraint here in doing that.

**Comment by RomainLanz** [comment]
Hey @kishorenc! 👋 

Yes, the goal for us is to decrease the payload size as much as we can.

**Comment by jochy** [comment]
A dirty hack would be to ask Typesense to highlight a field that doesn't match with your search.
For instance: `'highlight_fields': 'id'`

**Comment by kishorenc** [comment]
Yeah I would just recommend just sending a field that does not exist. Typesense will not throw an error, so feel free to send: `highlight_fields=x` where `x` does not exist.
