### ISSUE TITLE
Scoped API Key filter_by clause doesn't work with multi_search

### ISSUE THREAD

**Issue by theodem** [typesense/typesense#263]
## Steps to reproduce

I have an index, in which each document have a boolean field named "is_public".
For exemple, the index have 50 documents in which 40 have the field "is_public" set to false and the 10 other have the field "is_public" set to true. 

Then I create a scoped API key with the value "filter_by:is_public:=true" implemented in it.

## Expected Behavior

If i make a multi_search request to that index using the scoped api key generated previously, it is expected to return only results which the "is_public" field is set to true, so only 10 documents.

## Actual Behavior

When i make a multi_search request with the scoped API key and without any "filter_by" argument it actually return only 10 documents which is good. But if i add any "filter_by" clause in one of the searches (in the searches JSON, not the global arguments) it return all the documents matching that filter_by clause without applying the scoped API key filter_by clause.

## Metadata

**Typsense Version**: Typesense cloud 0.19

**Comment by jasonbosco** [comment]
@theodem This is a bug that has been fixed in v0.20 (about to be released). Since you're using Typesense Cloud, we can upgrade your cluster to the latest RC build of v0.20. Could you email your cluster ID to contact at typesense dot org?
