### ISSUE TITLE
Typesense server on Mac fails with missing library with latest v0.20.0

### ISSUE THREAD

**Issue by mcunningham** [typesense/typesense#264]
I am getting an error when trying to launch a Typesense server locally (macOS Big Sur 11.2.1) with the latest typesense version (v0.20.0). 

## Steps to reproduce

I followed the basic instructions on the typesense homepage 

```
wget https://dl.typesense.org/releases/0.20.0/typesense-server-0.20.0-darwin-amd64.tar.gz

tar xvzf ./typesense-server-0.20.0-darwin-amd64.tar.gz

./typesense-server --data-dir /tmp --api-key=xyz
  ```

## Expected Behavior

Expected local server to launch

## Actual Behavior

I received this error when trying to launch the server.

```
dyld: Library not loaded: /usr/local/opt/gflags/lib/libgflags.2.2.dylib
  Referenced from: /Users/home/Desktop/typesense-test/./typesense-server
  Reason: image not found
zsh: abort      ./typesense-server --data-dir /tmp --api-key=xyz

```

## Metadata

**Typsense Version**:
v0.20.0

**OS**: macOS Big Sur 11.2.1

**Comment by kishorenc** [comment]
@mcunningham Sorry about that, can you please download the the binary and try again? It should be fixed.

**Comment by mcunningham** [comment]
@kishorenc yes it is fixed now. Thank you!
