### ISSUE TITLE
chinese fulltext search

### ISSUE THREAD

**Issue by nroe** [typesense/typesense#267]
it seems that chinese full-text search can only split characters.
such as you want search "美丽中国，好玩又好吃" with “好吃” or "好玩". you have to split the characters when creating the index, like this “美 丽 中国，好 玩 又 好 吃” separate all characters with spaces. and use term with "好 吃" or "好 玩"。is there a better way to support chinese search ?

**Comment by kishorenc** [comment]
@nroe A lot of progress has been made on this front, check this thread: https://github.com/typesense/typesense/issues/228

Would you like to help me test this out for Chinese? I can create a build with support for Chinese characters enabled. 

One question I've at the moment is about prefix searching on Chinese: are the Chinese characters typically constructed/composed from sub-character glyphs (like the Korean characters)? Or are the entire symbol constructed at one go?

**Comment by mkm0094** [comment]
@kishorenc  Does 0.21.0 support Chinese word segmentation？

**Comment by zjttfs** [comment]
Try <jieba> chinese text segmentation 
[CppJieba](https://github.com/yanyiwu/cppjieba/blob/master/README_EN.md)

**Comment by kishorenc** [comment]
Indexing and searching on Chinese text is now supported on this RC Docker build: `typesense/typesense:0.21.0.rc11`

Usage:

```
# Create a collection with a field `title` marked as containing Chinese text

curl -k "http://localhost:8108/collections" -X POST -H "Content-Type: application/json" \
      -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{
        "name": "titles", "num_memory_shards": 4,
        "fields": [
          {"name": "title", "type": "string", "locale": "zh" },
          {"name": "points", "type": "int32" }
        ],
        "default_sorting_field": "points"
      }'

# Index a document

curl "http://localhost:8108/collections/titles/documents?dirty_values=coerce_or_reject&action=upsert" -X POST \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{"points":113.4,"title":"獻給我思念的每一朵雲──海", "id": "0"}'

# Search

curl -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" http://localhost:8108/collections/titles/documents/search/\?q\=我\&query_by\=title

```

Please try it out and give us feedback for improvement.

**Comment by mkm0094** [comment]
@kishorenc   Tested, but the search content is meaningless。
search"你已经可以存储和操作数据后" Split "matched_tokens": [ "数据", "和", "数据" ], These meaningless keywords。
Instead of using"你已经可以存储和操作数据后"To search。
No exact match was found in the document。

What to get
`在你已经可以存储和操作数据后，让我们简要地回顾一下基本线性代数的部分内容。这些内容能够帮助你了解和实现本书中介绍的大多数模型。下面我们将介绍线性代数中的基本数学对象、算术和运算，并用数学符号和相应的代码实现来表示它们。`

**Comment by kishorenc** [comment]
@mkm0094 When I index that text and search with the query `你已经可以存储和操作数据后`, I see the result being found, see here:

https://gist.github.com/kishorenc/5753f2778d518a9ebb46db91a2dd5224

Can you please explain what is going wrong for you?

**Comment by nroe** [comment]
I think the current version can already support chinese search very well. just need to perform word segmentation before searching and indexing. this project is great.

**Comment by kishorenc** [comment]
>  just need to perform word segmentation before searching and indexing

Correct. Typesense before this RC build only segmented words on spaces. If you pre-processed your text to do segmentation before indexing and querying you could search well. This RC build does the segmentation for you so you no longer have to do that manually.

**Comment by Xwudao** [comment]
> Indexing and searching on Chinese text is now supported on this RC Docker build: `typesense/typesense:0.21.0.rc11`
> 
> Usage:
> 
> ```
> # Create a collection with a field `title` marked as containing Chinese text
> 
> curl -k "http://localhost:8108/collections" -X POST -H "Content-Type: application/json" \
>       -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{
>         "name": "titles", "num_memory_shards": 4,
>         "fields": [
>           {"name": "title", "type": "string", "locale": "zh" },
>           {"name": "points", "type": "int32" }
>         ],
>         "default_sorting_field": "points"
>       }'
> 
> # Index a document
> 
> curl "http://localhost:8108/collections/titles/documents?dirty_values=coerce_or_reject&action=upsert" -X POST \
>         -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{"points":113.4,"title":"獻給我思念的每一朵雲──海", "id": "0"}'
> 
> # Search
> 
> curl -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" http://localhost:8108/collections/titles/documents/search/\?q\=我\&query_by\=title
> ```
> 
> Please try it out and give us feedback for improvement.

Hello, I now want to know if in the SDK, do I need to add the `locale` field to define the model
