### ISSUE TITLE
I cannot save data to the hard drive.

### ISSUE THREAD

**Issue by WatanabeThiago** [typesense/typesense#276]
## Description

I cannot save data to the hard drive.

## Steps to reproduce

Start PC
docker run -p 8108:8108 -v/typesense/pandoris:/data typesense/typesense:0.20.0 --data-dir /data --api-key=xyz
Create Collection
Insert Documents on Collection

Shutdown PC
Start PC
docker run -p 8108:8108 -v/typesense/pandoris:/data typesense/typesense:0.20.0 --data-dir /data --api-key=xyz
List Collections

## Expected Behavior

Collections I created earlier

## Actual Behavior

[]

## Metadata

**Typsense Version**: 0.20.0

**OS**: Windows 10

**Comment by kishorenc** [comment]
@WatanabeThiago 

1. Does the problem occur only when you restart your computer or even if you stop and restart the Docker container?
2. Can you please check the contents of the data directory (i.e. `/typesense/pandoris`) before and after the restart?

**Comment by kishorenc** [comment]
@WatanabeThiago 

Is the Docker container automatically restarted when you restart your computer? If not, can you try checking that directory right after you restart your computer, but **before** starting Typesense Docker container? I would like to know if the directory is already empty on restart.

**Comment by WatanabeThiago** [comment]
The directory is ALWAYS empty. Even when I insert or search for results.

![print for github](https://user-images.githubusercontent.com/50850299/119877483-7abbd480-beff-11eb-8bd1-6c30b0f73b03.png)

My suspicion is that the collections are not saving to the hard drive, saving only to RAM.

Another suspicion I have is that typesense is not finding the directory.

# Other information


![image](https://user-images.githubusercontent.com/50850299/119877252-2d3f6780-beff-11eb-9451-a95d002712a9.png)

collections script
![image](https://user-images.githubusercontent.com/50850299/119877314-4516eb80-beff-11eb-82e3-d1bc849256a7.png)

**Comment by aries1980** [comment]
This question is unrelated to Typesense. OP would have the same issue with e.g. an `ubuntu:stable` image.

I gave it a spin with
`docker run -p 8108:8108 -v /typesense/pandoris:/data typesense/typesense:0.20.0 --data-dir /data --api-key=xyz` creates a directory on `C:\typesense\pandoris` .

Docker does not use WSL2 in Windows unless you enable it in Docker Desktop, but the volumes are still bound to the host FS. This also depends on the hypervisor you are using.

Note: Docker Desktop with WSL2 is very experimental atm. The features in WSL2 and DD are playing tag.

**Comment by abelyakin** [comment]
Same problem but on ubuntu 20.04 lts
I start docker container with command:
docker run -d -p 8108:8108 -v /tmp/typesense-data:/data typesense/typesense:0.22.1 --data-dir /data --api-key=123--enable-cors -d

typesesnse creates a directory in the specified location.
But after the system reboot, it just doesn't pick up the current index DB. It returns no collections.

**Comment by kishorenc** [comment]
The OS clears the /tmp directory contents on system reboot. Use another directory.

**Comment by ThomasJanUta** [comment]
If you are using Windows with WSL and typesense runs inside a docker image with Docker Desktop inside that distribution, you need to set a data-dir: https://typesense.org/docs/0.24.0/api/server-configuration.html#using-command-line-arguments

This is the command that worked for me:
```
sudo docker run -d --name typesense --restart always -p 8108:8108 -v /mnt/c/Users/User/typesense:/data typesense/typesense:0.25.1 --data-dir /data --api-key=REPLACE_WITH_TYPESENSE_ADMIN_API_KEY
```
If you run the docker container the `typesense` folder should now contain the data:
```
db
meta
models
state
```
