### ISSUE TITLE
Determine which collection to show first in a federated search

### ISSUE THREAD

**Issue by miracle2k** [typesense/typesense#277]
Say I have two collections: artists and artworks, and I want to allow searching for either of them. Say I get results from both collections (which is quite likely).

Is there a good way for me to decide which of the collections has the better hit, i.e maybe the artist hit is a close match while the artwork match is only happening due to Levenshtein distance - is there a way to return the score of a hit?

If not, do people recommend using a single collection instead in a case like this?

**Comment by kishorenc** [comment]
If you want to show a single list of results which mixes records from both collections, it's convenient to just use a single collection. Index artists and artworks as separate fields. See our song search demo here: https://songs-search.typesense.org/

**Comment by miracle2k** [comment]
I think that demo just indexes the songs though (with the artist name as a field). This is not exactly what I want, as I need a search for "Maroon 5" to go to the artist page. So for a single collection, I would then probably have fields such as:

`
title=artistName|artworkName
kind=artist|artwork
artworkSpecificField1=
artworkSpecificField2=
artistSpecificField1=
`

I am assuming this would work, and has the advantage of being able to show the results in mixed form, but obviously isn't making use of the advantages of the collection structure.

Is exposing the searchScore result field something that could be considered?

**Comment by miracle2k** [comment]
Actually, it seems that the results do include a `text_match` property which indicates how close the match is (though I am not sure yet if they are comparible across collections!)

**Comment by kishorenc** [comment]
@miracle2k The `text_match` property can indeed be compared across collections since it is a measure of text similarity between the query and the matching text segment.
