### ISSUE TITLE
documents export with filter_by and include_fields will be very useful.

### ISSUE THREAD

**Issue by andrewsitt** [typesense/typesense#283]
## Description

At the moment, search, we are limited to 250 items, although paging may be used to retrieve more.

We need an ability to retrieve an unlimited number of items, as is already provided by "Export" but with the additional features of filter_by and include_fields (which is currently only provided by search)

**Comment by kishorenc** [comment]
@andrewsitt 

Ready for testing in this Docker build: `typesense/typesense:0.21.0.rc18`

Example:

```
/export?filter_by=points:>100&exclude_fields=x,y&include_fields=z
```

The `filter_by` clause is optional, so you can set include and exclude fields on the full dataset as well.

**Comment by kishorenc** [comment]
Available in `0.21.0` release.

**Comment by streamly** [comment]
I am using this feature but an include / exclude fields option for $client->collections['companies']->documents['124']->retrieve();
would be useful. I have to use export with an id filter just to get an array field to update.

**Comment by jasonbosco** [comment]
Could you open a separate Github issue for that, so we can track it?
