### ISSUE TITLE
[Feature Request]  Filters for multiple collections for scoped keys.

### ISSUE THREAD

**Issue by jamesamuel** [typesense/typesense#284]
## Description

It's currently possible to assign 'exclude_fields' to a single collection, but not multiple via a single search key. The use case for this is when a multi-search is required and restricted data per collection is required.

## Expected Behavior

A single scope search key where restricted access can be applied to multiple collections.

This logic could also be applied to parent keys. Currently, a separate API key is required per collection IF they require different actions i.e. search, get, delete etc. 

'Search' could be removed from parent keys altogether and scoped keys could handle it allowing granular permissions.

_Parent API keys could be:_

```
const key = client.keys().create([
    {
        description: "Users search key",
        actions: ["documents:search"],
        collections: ["users"],
    },
    {
        description: "Companies admin key",
        actions: ["documents:create, documents:update, documents:delete"],
        collections: ["companies"],
    }
])
```

**Output: Single API key**

_Scope search keys could be:_

```
const key = client.keys().generateScopedSearchKey([
  {
    description: "users search key for user 123",
    collection: "users",
    filter_by: "company_id:124",
    exclude_fields: "company_id, private_data",
    expires_at: 1906054106,
  },
  {
    description: "companies search key for user 123",
    collection: "companies",
    filter_by: "company_id:124",
    exclude_fields: "company_id, private_data",
    expires_at: 1906054106,
  },
]);

```

**Output: Single API key**

**Comment by jasonbosco** [comment]
As of `0.23.0.rc42` each search in a multi search request can have a separate API Key - parent or scoped with different sets of filters:

```json
{
  searches: [
    {
      collection: "books",
      query_by: "title",
      filter_by: "publication_year:<2005",
      "x-typesense-api-key": key1,
    },
    {
      collection: "books1",
      query_by: "authors",
      "x-typesense-api-key": key1,
    },
  ],
}
```
