### ISSUE TITLE
Chinese search Search by keyword without splitting keywords

### ISSUE THREAD

**Issue by mkm0094** [typesense/typesense#288]
## Description

Yes, it supports very well in blurry scenes.
But in some special scenes, accurate keyword search is still needed, Instead of splitting the keyword search

#### Data Sources: 
https://github.com/overnote/over-javascript/tree/master/01-JavaScript%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95

#### json format:
[javascript.json.zip](https://github.com/typesense/typesense/files/6613388/javascript.json.zip)

```shell
curl "http://localhost:8108/collections" \
       -X POST \
       -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: Hu52dwsas2AdxdE" \
       -d '{
         "name": "javascript_ceshi",
         "fields": [
           {"name": "js_id", "type": "int32" },
           {"name": "content", "type": "string","locale":"zh" }
         ],
         "default_sorting_field": "js_id"
       }'

#!/bin/bash
input="javascript.json"
while IFS= read -r line
do
  curl "http://localhost:8108/collections/javascript_ceshi/documents" \
        -X POST \
        -H "Content-Type: application/json" \
        -H "X-TYPESENSE-API-KEY: Hu52dwsas2AdxdE" \
        -d "$line"
done < "$input"

curl -H "X-TYPESENSE-API-KEY:Hu52dwsas2AdxdE" http://localhost:8108/collections/javascript_ceshi/documents/search/\?q\=函数就不可以转换\&query_by\=content
```

## Expected Behavior

Search keywords="函数就不可以转换" js_id=141

There should be only one search result   

<img width="939" alt="QQ20210608-120540@2x" src="https://user-images.githubusercontent.com/18025419/121121303-ea13bb80-c851-11eb-9eb0-4519eaf84e1a.png">

## Actual Behavior

Search through matched_tokens to find 10 results, Under certain conditions, can we not split the keywords?

"函数就不可以转换"is "函数就不可以转换" ,Don't split it into  [ "函数", "就不", "可以", "转换" ] or  [ "函数", "可以" ]

No need to split user search terms

Such search results are very bad, typesense can only be used to search for titles, tags, introductions, etc. These texts are few, and users can get the content they want under fuzzy search。

Hope in the future be able to see the search keywords are not split, thank you for providing such a good project

<img width="1067" alt="222" src="https://user-images.githubusercontent.com/18025419/121121678-9e154680-c852-11eb-8cf9-6441a55cc8ee.png">
<img width="981" alt="33" src="https://user-images.githubusercontent.com/18025419/121121910-17ad3480-c853-11eb-9de7-15bc9fa370a7.png">
<img width="1058" alt="44" src="https://user-images.githubusercontent.com/18025419/121121939-23006000-c853-11eb-90b7-1bcbd8428144.png">

## Metadata

**Typsense Version**: typesense/typesense:0.21.0.rc11

**OS**:Macbook 11.2.1

**Docker**:3.3.3

**Comment by kishorenc** [comment]
@mkm0094 This behavior can be controlled by the use of the `drop_tokens_threshold` flag. Set this flag value to `0` and Typesense will not try to split the keyword. Likewise you can also set `num_typos=0` to disable typo correction since that's not applicable for Chinese.

Let me know what happens when you add the following parameter to the search API URL:

`&drop_tokens_threshold=0`

**Comment by mkm0094** [comment]
@kishorenc  Added &drop_tokens_threshold=0 and num_typos=0, the search results have improved a lot, but there are still flaws。 search ”运算符“ 18 results, reduced to 4

## Steps to reproduce

Same as above
Search term “运算符”

## Expected Behavior
Should be three results
<img width="723" alt="QQ20210610-150812@2x" src="https://user-images.githubusercontent.com/18025419/121480513-bd040c00-c9fd-11eb-9ca0-39234dd5fdde.png">

## Actual Behavior

There are 4 results, one deviation。Search matches “运算”，No match”运算符“。Does not meet search expectations
<img width="589" alt="2222" src="https://user-images.githubusercontent.com/18025419/121484172-8af4a900-ca01-11eb-9928-8aab7554ec69.png">
<img width="813" alt="QQ20210610-151119@2x" src="https://user-images.githubusercontent.com/18025419/121480875-24ba5700-c9fe-11eb-86c1-fc4f46eef343.png">

**Comment by Duynguyennnt** [comment]
how to fix it. i got the same error @mkm0094
