### ISSUE TITLE
Demo not working on typesense.org

### ISSUE THREAD

**Issue by keybits** [typesense/typesense#29]
## Description

The demo search has stopped working

## Steps to reproduce

visit https://typesense.org/ and try the demo

## Expected Behavior

A search result should appear

## Actual Behavior

nothing appears

## Metadata

Tried various browsers. In Chrome console I'm seeing: `Failed to load resource: net::ERR_CONNECTION_REFUSED`

**Comment by kishorenc** [comment]
Sorry about that - it's back up now: had to rotate some underlying infrastructure.

**Comment by keybits** [comment]
Thanks. And thank you for making Typesense really liking it :-)
