### ISSUE TITLE
Please clarify some of the API documentation

### ISSUE THREAD

**Issue by unclescooby** [typesense/typesense#292]
Hi,

I'm building my own php solution for typesense and like to have some more insight:

- how does typesense deal with quotes, special characters, etc in strings.. stuff that will usually require escaping or some form of encoding. Will typesense simply ingest and return everything as is? Any filtering applied?
- when browsing the php library code I encountered 2 document update functions ([first](https://github.com/typesense/typesense-php/blob/master/src/Document.php#L77) and [second](https://github.com/typesense/typesense-php/blob/33adc5b3c31024f927f1a7390809757f9289a86e/src/Documents.php#L99) ). The first one creates a PATCH request and API docs mention partial docs can be used. The second one is a POST request, like upsert() but with action=update.  Can both endpoints be used for partial updates? Or maybe the latter is there for legacy purposes? EDIT: removed php comments
- I've also seen for the 2 mentioned php functions, as well as for create() and upsert(), a function parameter was added in v.4.6.0, but not seeing it reflected in the 0.20.0 API docs... EDIT: looks to be related to dirty-values parameter
- also saw a  `num_memory_shards` parameter mentioned somewhere. What is it?
- and last: the 0.20.0 docs on creating collections. The pre-defined schema tip mentions fields not in the collection's schema will be stored on disk but not indexed in memory. Does that mean they will not be queryable, but will be returned with results? And, coming from disk, would that slow down typesense?
- Also what's the purpose of the string* fieldtype? EDIT: found string* purpose on documents page. Can it only be used with wildcard field?

I may come up with more questions later, but first need to digest the auto schema docs. Latest typesense looking good and I'll be testing it :)

**Comment by unclescooby** [comment]
A late response from this end too... but thanks for answering.

> string* is meant to be used for coercing all values to string .... It can be used with any field names.
Reading the collections API doc, gave me the impression that `string*` and `auto` types were exclusive to autoschema fields (regex/wildcard) and that all the other data types were exclusive to pre-defined fields, but it turns out that all types except `auto` can be used for pre-defined fields, and all data types can be used for wildcard and regex fields. Can you confirm this?

And with all types I meant to include the `geopoint` type, which does get accepted for regex/wildcard during schema creation.. whereas the docs say that a `geopoint` field requires an explicit field type definition.  Is that a bug?

**Comment by kishorenc** [comment]
> all types except auto can be used for pre-defined fields, and all field types can be used for wildcard and regex fields. Can you confirm this?

This is correct.

> whereas the docs say that a geopoint field requires an explicit field type definition. Is that a bug?

The document is not correct here: what the docs meant to say is that geo fields are not detected by a simple `{"name": ".*", "type": "auto" },` definition since we cannot differentiate between a genuine array field with 2 float values and a geo field which also uses a 2-element array. I will clarify this -- thanks for bringing this to our attention!

**Comment by unclescooby** [comment]
Ah... I did misread field type and interpreted it as field name, but the reply was still useful. It seems that for geofields it's better to use a predefined fieldname, or something like `{"name": "loc.*", "type": "geofield" }`

**Comment by kishorenc** [comment]
Yes, a `{"name": "loc.*", "type": "geopoint" }` definition would work.

**Comment by unclescooby** [comment]
One more thing: I was wondering if typesense accepts any regex patterns/characters other than the `.*` (combined with letters) for fieldnames.  So a bit of testing with schema creation and not providing field `optional` argument, and then viewing that argument in the returned schema suggests the answers is no. Using eg. `[^abc]` as fieldname returns `"optional":false`. Even faulty regex like `[*` gets accepted! So what does typesense do with such fields? (indexing would probably fail by not supplying a value for that field).

Also, which characters are acceptable for predefined fieldnames?

**Comment by kishorenc** [comment]
> I was wondering if typesense accepts any regex patterns/characters other than the .* (+prefix/postfix) for fieldnames

I just realized that we use the presence of ".*" in the field name to mark a field as a dynamic field, so if have to have ".*" in addition to other regexps in the field name, then we will support that. So something like `^abc.*` would work.

> Also, which characters are acceptable for predefined fieldnames? Are A-Z case sensitive?

We don't impose any restrictions on valid field name characters.

**Comment by unclescooby** [comment]
> I just realized that we use the presence of "." in the field name to mark a field as a dynamic field
Field names with only a `.` by default return `"optional":false` which to me indicates they cannot be an auto schema detection / dynamic / regex field. They can be set to `"optional":false` which is only possible for regular fields. Please verify.

**Comment by kishorenc** [comment]
Sorry there was a typo. I meant that we check for presence of '.*' in the field name.

**Comment by unclescooby** [comment]
One other thing: duplicate regex fieldnames are allowed: ` ['name' => 'Foo.*', 'type' => 'string'], ['name' => 'Foo.*', 'type' => 'string'],`

Bug or feature?

**Comment by unclescooby** [comment]
To add to previous comment. In typesense 0.21 duplicate explicit fieldnames are also allowed....
