### ISSUE TITLE
Typo is scored higher than actual match

### ISSUE THREAD

**Issue by junelmujar** [typesense/typesense#298]
## Description

I just noticed that "triangular" is scored higher than "trigonometric" for a search on "trig".

Lesson: Surface Area of Triangular Prisms Record
Tags: solid
Text Match Score:129378

Lesson: Geometry Proofs
Tags: angle, right angle, triangle
Text Match Score:128609

Lesson: The Trigonometric Ratios
Tags: adjacent, angle, cosine, hypothenuse, tangent, triangle
Text Match Score:127583     

I have the following values set in the additional search params:

	additionalSearchParameters: {
		queryBy: "Lesson,Tags",
		sortBy: "_text_match:desc",
		queryByWeights: '2,1',
		numTypos: 1
	}

Is there something that I'm missing parameter/setting wise to correct this or this is just how Typesense scored the matches?

Thanks!

## Metadata

**Typsense Version**: Cloud

**Comment by kishorenc** [comment]
@junelmujar Thanks for reporting this issue. This has been addressed and the fix is available as part of a release candidate build. Can you please try locally against this build?

```
typesense/typesense:0.21.0.rc16
```

If that works, I will be happy to upgrade your Typesense Cloud cluster to the RC build: please email us with the cluster details.

**Comment by junelmujar** [comment]
That's great news @kishorenc! Thanks a lot for this.

I'll test it locally and will let you know how it goes.

**Comment by junelmujar** [comment]
> @junelmujar Thanks for reporting this issue. This has been addressed and the fix is available as part of a release candidate build. Can you please try locally against this build?
> 
> ```
> typesense/typesense:0.21.0.rc16
> ```
> 
> If that works, I will be happy to upgrade your Typesense Cloud cluster to the RC build: please email us with the cluster details.

Hi @kishorenc , I can confirm that the fix from new build works. The results are now returned in the correct order.  Thanks a lot for this fix.

Btw, I forgot to ask, what's the email address should I send our  Typesense Cloud cluster info to?
 
Thanks.  /Junel

**Comment by kishorenc** [comment]
Good to hear. Please email us contact at typesense org.
