### ISSUE TITLE
Batch Delete endpoint

### ISSUE THREAD

**Issue by inluxc** [typesense/typesense#300]
## Description

Batch delete api endpoint

## Expected Behavior

Instead of deleting one by one we can send multiple ids to be deleted.

## Actual Behavior

Delete one document per call

## Metadata

0.20

Linux

**Comment by jasonbosco** [comment]
@inluxc There's a delete by query api, which batch deletes: https://typesense.org/docs/0.20.0/api/documents.html#delete-by-query.
