### ISSUE TITLE
Ability to customize word segmentation using custom dictionary

### ISSUE THREAD

**Issue by hetian9288** [typesense/typesense#301]
Do you support loading local thesaurus or dynamically adding keywords?

**Comment by kishorenc** [comment]
Can you please elaborate how you would like to use this dictionary? Typesense does have a synonyms feature: I'm not sure if that would help: https://typesense.org/docs/0.20.0/api/synonyms.html#synonyms

**Comment by hetian9288** [comment]
Customize the thesaurus used for word segmentation;
For example, "香薰洗衣液瓶装深层清洁用品持久留香干清洗剂洗衣凝珠代发"
We need to add product nouns such as "洗衣液、洗衣凝珠" to the word segmentation database

The current default segmentation result:
洗衣液 -> [洗衣、液]
洗衣凝珠 -> [洗衣、凝、珠]

**Comment by kishorenc** [comment]
@hetian9288 We've added beta support for segmenting and indexing Chinese text only in a RC build -- are you using a RC build?

While we don't have a way to customize the segmentation behavior, I think it might be a good idea to segment the text yourself before indexing it into Typesense. That way you have maximum control over how the text is split. If you plan to take this approach:

a) Don't use the any locale while creating the field definitions
b) Segment both the indexed text and the search query string yourself
c) Use the `?pre_segmented_query=true` parameter as described [here](https://github.com/typesense/typesense/issues/228#issuecomment-856083274) to ensure that Typesense does not attempt to segment the query string.

**Comment by hetian9288** [comment]
ok your solution has been solved my question, it is wonderful! thank you very much!
