### ISSUE TITLE
should handle missing half of a hyphenated word

### ISSUE THREAD

**Issue by jhoguet** [typesense/typesense#303]
## Description

when searching for the school `Missisquoi Union Middle-High School` I should be able to search for `Missisquoi Union High`

## Steps to reproduce

``` 
    const schemaName = 'high-schools-bugs-v3'
    await typesense.collections().create({
        "name": schemaName,
        "fields": [
            { "name": "InstitutionID", "type": "string" },
            { "name": "InstitutionName", "type": "string" },
            { "name": "PhysicalCity", "type": "string" },
            { "name": "PhysicalState", "type": "string" }
        ],
    });

    await typesense.collections(schemaName).documents().import([
        {"InstitutionID":"633962","InstitutionName":"Missisquoi Union Middle-High School","PhysicalCity":"Swanton","PhysicalState":"VT"}
    ]);

    const result = await typesense.collections(schemaName).documents().search({
        'query_by': 'InstitutionName,PhysicalCity,PhysicalState',
        'q': 'Missisquoi Union High',
        per_page: 10,
        limit_hits: 10,
        typo_tokens_threshold: 0
    })
```

## Expected Behavior

expect result to have a hit for `Missisquoi Union Middle-High School`

## Actual Behavior

result does not have a hit for `Missisquoi Union Middle-High School`

## Metadata

I expect this is because `Missisquoi Union Middle-High School` becomes `Missisquoi Union MiddleHigh School` and then `high` doesn't match `MiddleHigh` but in our dataset replacing a hyphen with a space would be more appropriate. 

this is reproducing on 0.20 and 0.21.0.rc14

**Comment by kishorenc** [comment]
@jhoguet As you guessed, Typesense indeeds removes the hyphens before indexing so  `Middle-High` becomes `MiddleHigh`. There is no way to customize this behavior as of now, but is tracked in [this issue](https://github.com/typesense/typesense/issues/201) -- we plan to implement this in future.

For now, you have to replace hyphens with a space before indexing.

**Comment by jhoguet** [comment]
@kishorenc thanks for the quick response.

**Comment by kishorenc** [comment]
Recent versions of Typesense supports the `token_separators` configuration, which allows one to customize how the words are split.
