### ISSUE TITLE
Fatal error during indexing: [json.exception.type_error.302] type must be number, but is string

### ISSUE THREAD

**Issue by britisharmy** [typesense/typesense#305]
I am running this version of typsesense ` typesense-server-0.21.0.rc7-amd64.deb` however i get this error

`Fatal error during indexing: [json.exception.type_error.302] type must be number, but is string`

I am using the typesense php driver and all i am doing is trying to add data to my collection

```
$document = [
		  'property_owner_id'  => "$property_owner_id",
		  'property_name' => "$property_name",
		  'property_country' => "$property_country",
		  'property_address' => "$property_address",
		  'property_coordinates' => $property_coordinates,
		  'property_star_rating' => $property_star_rating,
		  'property_reviews_score' => $property_reviews_score,
		  'property_price_per_night_usd' => $property_price_per_night_usd,
		  'property_price_per_night_euro' => $property_price_per_night_euro,
		  'property_price_per_night_pound'=> $property_price_per_night_pound,
		  'property_price_per_night_ksh'=> $property_price_per_night_ksh,
		  'property_price_per_night_ugx'=> $property_price_per_night_ugx,
		  'property_price_per_night_rem'=> $property_price_per_night_rem,
		  'property_price_per_night_yen'=> $property_price_per_night_yen,
		  'property_image'=> "$property_image",
		  'property_tv'=> "$property_tv",
		  'property_radio'=> "$property_radio",
		  'property_breakfast' => "$property_breakfast",
		  'property_bed_type' => "$property_bed_type",
		  'property_kitchennete' => "$property_kitchennete",
		  'property_city' => "$property_city",
		  'property_region' => "$property_region",
		  'property_chain_name'=> "$property_chain_name",
		  'property_status'=> "$property_status",
		  'property_maximum_occupancy_capacity' => $property_maximum_occupancy_capacity,
		  'property_remaining_occupancy_capacity'=> $property_remaining_occupancy_capacity,
		  'property_date_added' => "$property_date_added",
		  'property_date_updated' => "$property_date_updated",
		];
		$this->client->collections['props']->documents->create($document);
```

**Comment by kishorenc** [comment]
@britisharmy There should be stack trace produced in the logs. Can you post the full stack trace on a gist and link to it?

**Comment by britisharmy** [comment]
This is the relevant log otherwise the rest of the lines are raft server refreshes and other data not particular to this problem

`E20210630 16:46:42.063069 117393 index.cpp:482] Fatal error during indexing: [json.exception.type_error.302] type must be number, but is string, document: {"id":"10","property_address":"Waiyaki Way, L.R. No. 1870/X/8","property_bed_type":"true","property_breakfast":"true","property_chain_name":"0","property_city":"Nairobi","property_coordinates":["-1.263951","36.7582356"],"property_country":"KE","property_date_added":"1686026802","property_date_updated":"1686026802","property_image":"https://cf.bstatic.com/images/hotel/max1024x768/143/143166572.jpg","property_kitchennete":"true","property_maximum_occupancy_capacity":55,"property_name":"Park Inn by Radisson, Nairobi Westlands","property_owner_id":"2130853399","property_price_per_night_euro":250,"property_price_per_night_ksh":250,"property_price_per_night_pound":250,"property_price_per_night_rem":250,"property_price_per_night_ugx":250,"property_price_per_night_usd":250,"property_price_per_night_yen":250,"property_radio":"true","property_region":"Nairobi","property_remaining_occupancy_capacity":48,"property_reviews_score":2,"property_star_rating":5,"property_status":"open","property_tv":"true"}`

**Comment by britisharmy** [comment]
Fixed the array for geopoint and works as expected.

**Comment by kishorenc** [comment]
Thanks: I have also added validation for this so that a more meaningful error message is returned when a string is used in a `geopoint` field.
