### ISSUE TITLE
Faceting a json string

### ISSUE THREAD

**Issue by britisharmy** [typesense/typesense#307]
I have a long list of options numbering around 49 and i was wondering, is it possible to json encode the entire selection of all 49 options which are basically key value pairs and later perform actions such as  filtering of the josn string using instant search?

I am using vue js so its possible i fetch the encoded string and convert it on client side to javascript object

For instance in instants search

```
<ais-toggle-refinement
		  attribute="nested_object.property_star_rating"
		  label="3 Stars"
/>
```

Is this possible?

**Comment by jasonbosco** [comment]
Typesense does not yet support nested fields (See #227). So until then you'd have to flatten objects when indexing them in Typesense. For eg: you'd store `nested_object.property_star_rating: 5` in the document and then you'll be able to use it like any regular attribute in the instantsearch widgets.
