### ISSUE TITLE
Return all fields that match in the highlight section of search results

### ISSUE THREAD

**Issue by jasonbosco** [typesense/typesense#31]
## Description

When searching for a query in multiple fields in a document, currently, the search results only return one field in the highlight section. We ideally want to return all fields that match in the highlight section.

## Steps to reproduce

```shell
# Create a users schema:
# {
#   "name": "users",
#   "fields": [
#     {
#       "name": "full_name",
#       "type": "string"
#     },
#     {
#       "name": "shipping_address",
#       "type": "string"
#     },
#     {
#       "name": "billing_address",
#       "type": "string"
#     },
#     {
#       "name": "customer_id",
#       "type": "int32"
#     }
#   ],
#   "default_sorting_field": "customer_id"
# }

$ curl -X POST "http://localhost:8108/collections" -H  "accept: application/json" -H  "X-TYPESENSE-API-KEY: abcd" -H  "Content-Type: application/json" -d "{  \"name\": \"users\",  \"fields\": [    {      \"name\": \"full_name\",      \"type\": \"string\"    },    {      \"name\": \"shipping_address\",      \"type\": \"string\"    },    {      \"name\": \"billing_address\",      \"type\": \"string\"    },    {      \"name\": \"customer_id\",      \"type\": \"int32\"    }  ],  \"default_sorting_field\": \"customer_id\"}"

# Index a user:
# {
#   "customer_id": 124,
#   "full_name": "Tony Stark",
#   "billing_address": "10880 Malibu Point, Malibu, CA 90265",
#   "shipping_address": "10880 Malibu Point, Malibu, CA 90265"
# }

$ curl -X POST "http://localhost:8108/collections/users/documents" -H  "accept: application/json" -H  "X-TYPESENSE-API-KEY: abcd" -H  "Content-Type: application/json" -d "{  \"customer_id\": 124,  \"full_name\": \"Tony Stark\",  \"billing_address\": \"10880 Malibu Point, Malibu, CA 90265\",  \"shipping_address\": \"10880 Malibu Point, Malibu, CA 90265\"}"

# Now search for users with the word "Malibu" in their shipping or billing address:

$ curl -X GET "http://localhost:8108/collections/users/documents/search?q=Malibu&query_by=shipping_address%2Cbilling_address" -H  "accept: application/json" -H  "X-TYPESENSE-API-KEY: abcd"

# Result:
# {
#   "facet_counts": [],
#   "found": 1,
#   "hits": [
#     {
#       "document": {
#         "billing_address": "10880 Malibu Point, Malibu, CA 90265",
#         "customer_id": 124,
#         "full_name": "Tony Stark",
#         "id": "1",
#         "shipping_address": "10880 Malibu Point, Malibu, CA 90265"
#       },
#       "highlight": {
#         "field": "shipping_address",
#         "snippet": "10880 <mark>Malibu</mark> Point, Malibu, CA 90265"
#       }
#     }
#   ],
#   "page": 1,
#   "search_time_ms": 0
# }

```

## Expected Behavior

- The result should include both shipping address and billing address in the `highlight` section.
- The result should also `<mark>` all occurrences of the word in the field.

## Actual Behavior

- The result only includes shipping address in the `highlight` section.
- The highlight only marks the first occurrence of the query.

## Metadata

**Typsense Version**: typesense/typesense:wildcard_query_support

**OS/Platform**: Docker Image

**Comment by kishorenc** [comment]
@jasonbosco The highlight currently returns the snippet from the `best` matching field. Wondering if the performance hit by having to track best match from all fields is worth the benefit. If so, then `highlight` will have to become an array rather than a single object as it is right now.

**Comment by kishorenc** [comment]
@jasonbosco Okay, figured out a work around. Let's actually tackle this as part of `0.9.0` since it will involve a change to the `highlight` structure -- don't want to change it twice. Thinking of having it like:

```
"highlight": {
  "field_one": {
      "field": "field_one",
      "snippet": "some <mark>content</mark>"
  },
  ...
}
```

The other option is to have `highlight` be an array of objects but that won't give random access to a specific field, like the map structure above would.

**Comment by kishorenc** [comment]
> May be call it highlights (plural)?

👍I've made that change.

> Also, since we have the field name as the key, we could remove the “field” key right?

Mostly because in some statically typed languages, it gives the flexibility to model that object as a proper class (the name would be needed as an identifier in that case) and allow the language to treat the map as essentially an "iterable" of objects. You will appreciate it if you used Java and wanted to map a custom JSON object using a Jackson parser :)

PR is ready. Check: https://github.com/typesense/typesense/pull/32

**Comment by jasonbosco** [comment]
Left comments on PR #32
