### ISSUE TITLE
Help with iOS app

### ISSUE THREAD

**Issue by aaronkbutler** [typesense/typesense#310]
## Description

I am trying to incorporate typesense full-text search into my Google Firestore-powered iOS application. I'm a beginner at a lot of this backend stuff, and was wondering if anyone could give me any suggestions for how to proceed.

**Comment by kishorenc** [comment]
@aaronkbutler 👋 Typesense does not yet have a client library to use on iOS. So you will have to make HTTP requests from your code using a HTTP client. All API resources have a `shell` example that shows the raw HTTP request needed: https://typesense.org/docs/0.20.0/api/collections.html

**Comment by kishorenc** [comment]
@aaronkbutler We're actively working on a Swift client. Would you be interested in testing it when we are ready with a preview?

**Comment by aaronkbutler** [comment]
Yes! Definitely. Currently using curl requests in my Swift project, but would love to check out the Swift client when you have a preview ready.
