### ISSUE TITLE
BUG: `TYPESENSE_PEERING_ADDRESS` does not set peering_address

### ISSUE THREAD

**Issue by tuladhar** [typesense/typesense#311]
## Description

When running the typesense in Kubernetes environment, it always uses internal IP address of the pod, regardless of change to `TYPESENSE_PEERING_ADDRESS`
```
I20210708 12:36:53.635774   100 typesense_server_utils.cpp:260] Typesense peering service is running on 10.19.0.33:8107
```

## Steps to reproduce
* Set the `TYPESENSE_PEERING_ADDRESS` environment variable
* View the logs to see the listening peering address.

```
I20210708 12:36:53.635774   100 typesense_server_utils.cpp:260] Typesense peering service is running on 10.19.0.33:8107
```

## Expected Behavior

**Expected:**
* Setting the `TYPESENSE_PEERING_ADDRESS` should set the `peering_address` here.
```
            this->peering_address = get_env("TYPESENSE_PEERING_ADDRESS");
```

## Actual Behavior

**Actual:**

When running the typesense in Kubernetes environment, it always uses internal IP address of the pod, regardless of change to `TYPESENSE_PEERING_ADDRESS`
```
I20210708 12:36:53.635774   100 typesense_server_utils.cpp:260] Typesense peering service is running on 10.19.0.33:8107
```

## Metadata

**Typsense Version**:
`typesense/typesense:0.21.0.rc23`

**OS**:
Linux

**Comment by kishorenc** [comment]
Thanks! This is fixed in `typesense/typesense:0.21.0.rc24`.
