### ISSUE TITLE
Documentation for collection creation (default_sorting_field requirement) is seemingly incorrect

### ISSUE THREAD

**Issue by Wizhi** [typesense/typesense#314]
## Description

The collection schema `default_sorting_field` isn't actually required, [even though the documentation says it is.](https://typesense.org/docs/0.11.2/api/collections.html#arguments)

## Expected Behavior

Setting `default_sorting_field: ""` upon collection creation should fail.

## Actual Behavior

Setting `default_sorting_field: ""` [seemingly causes results to be ordered by sequence identifier.](https://github.com/typesense/typesense/blob/353344d671529707fceaa66756c925bb9599bfc6/src/collection.cpp#L759-L763Q)

I'm by no means sure that my assumption about Typesense "falling back" to the sequence identifier is correct, since I've only briefly skimmed the code.

I do like this, however, since it's not always the case that I actually need default sorting.

## Metadata

**Typsense Version**: 0.20.0

**OS**: Linux (docker)

**Comment by kishorenc** [comment]
Thank you for catching this. It's indeed optional now..I'll update the docs.

**Comment by kishorenc** [comment]
It turns out that the linked page is an older version of Typesense. Recent version of the docs are already documenting the flag as optional. E.g. https://typesense.org/docs/0.20.0/api/collections.html#with-pre-defined-schema

**Comment by Wizhi** [comment]
Oh boy do I feel a little dumb now. 😅 

I think I found the docs through a Google search, so that was a human error on my part.
Thanks for clarifying.

**Comment by kishorenc** [comment]
No, I have to actually thank you for this: now we know that we have to tweak the weights on the sitemap to let Google index the right pages.
