### ISSUE TITLE
"Not Ready or Lagging" ...... 

### ISSUE THREAD

**Issue by zjttfs** [typesense/typesense#316]
it was a long wait......

![error](https://user-images.githubusercontent.com/24729880/125715008-44d6c32c-0814-42b6-88b9-c8a4046e2318.png)

![status](https://user-images.githubusercontent.com/24729880/125715099-4c96556a-363a-4966-8f77-f598053afc27.png)

![htop](https://user-images.githubusercontent.com/24729880/125715133-e26e1bb1-38f1-4248-8d07-f6e88435d6ba.png)

## Metadata

**Typsense Version**: 0.21

**OS**: centos 7.9

**Comment by zjttfs** [comment]
`

Array
(
    [0] => Array
        (
            [created_at] => 1626254594
            [default_sorting_field] => 
            [fields] => Array
                (
                    [0] => Array
                        (
                            [facet] => 
                            [index] => 1
                            [name] => name
                            [optional] => 
                            [type] => string
                        )

                )

            [name] => zpb_tui
            [num_documents] => 149608250
            [num_memory_shards] => 4
        )

    [1] => Array
        (
            [created_at] => 1626254594
            [default_sorting_field] => 
            [fields] => Array
                (
                    [0] => Array
                        (
                            [facet] => 
                            [index] => 1
                            [name] => title
                            [optional] => 
                            [type] => string
                        )

                    [1] => Array
                        (
                            [facet] => 
                            [index] => 1
                            [name] => content
                            [optional] => 
                            [type] => string
                        )

                )

            [name] => zpb_video
            [num_documents] => 89275
            [num_memory_shards] => 4
        )

    [2] => Array
        (
            [created_at] => 1626254594
            [default_sorting_field] => 
            [fields] => Array
                (
                    [0] => Array
                        (
                            [facet] => 
                            [index] => 1
                            [name] => nickname
                            [optional] => 
                            [type] => string
                        )

                    [1] => Array
                        (
                            [facet] => 
                            [index] => 1
                            [name] => area
                            [optional] => 
                            [type] => string
                        )

                )

            [name] => zpb_user
            [num_documents] => 2402
            [num_memory_shards] => 4
        )

    [3] => Array
        (
            [created_at] => 1626254594
            [default_sorting_field] => 
            [fields] => Array
                (
                    [0] => Array
                        (
                            [facet] => 
                            [index] => 1
                            [name] => title
                            [optional] => 
                            [type] => string
                        )

                    [1] => Array
                        (
                            [facet] => 
                            [index] => 1
                            [name] => file_suffix
                            [optional] => 
                            [type] => int32
                        )

                )

            [name] => zpb_wenku
            [num_documents] => 0
            [num_memory_shards] => 4
        )

    [4] => Array
        (
            [created_at] => 1626254594
            [default_sorting_field] => 
            [fields] => Array
                (
                    [0] => Array
                        (
                            [facet] => 
                            [index] => 1
                            [name] => title
                            [optional] => 
                            [type] => string
                        )

                    [1] => Array
                        (
                            [facet] => 
                            [index] => 1
                            [name] => intro
                            [optional] => 
                            [type] => string
                        )

                )

            [name] => zpb_page
            [num_documents] => 28706
            [num_memory_shards] => 4
        )

    [5] => Array
        (
            [created_at] => 1626254594
            [default_sorting_field] => 
            [fields] => Array
                (
                    [0] => Array
                        (
                            [facet] => 
                            [index] => 1
                            [name] => title
                            [optional] => 
                            [type] => string
                        )

                    [1] => Array
                        (
                            [facet] => 
                            [index] => 1
                            [name] => intro
                            [optional] => 
                            [type] => string
                        )

                )

            [name] => zpb_ask
            [num_documents] => 920265
            [num_memory_shards] => 4
        )

)

`

**Comment by kishorenc** [comment]
👋 can you please post the last few lines of the log?

**Comment by zjttfs** [comment]
[typesense.log](https://github.com/typesense/typesense/files/6820162/typesense.log)
@kishorenc Thanks

**Comment by kishorenc** [comment]
@zjttfs Thanks for the logs.

Let me explain what the `Not ready or lagging` error message means: when you send an import or large batch of writes into Typesense, they are placed into a write queue and Typesense then proceeds to index them from the queue (this also happens during a restart). 

To prevent overwhelming Typesense and to provide back pressure for the reads and writes, we have a couple of arguments which are documented [here](https://typesense.org/docs/0.21.0/guide/configure-typesense.html#using-command-line-arguments).

1. `--healthy-read-lag`:  Reads are rejected if the updates lag behind this threshold. Default: 1000.
2. `--healthy-write-lag`: Writes are rejected if the updates lag behind this threshold. Default: 500.

I suppose what has happened here is that the read lag threshold has tripped so your searches (read requests) were getting rejected. This also protects the client from reading stale data from a server (if it is lagging for some genuine reason). You can just increase these thresholds as you see fit for your use case by restarting Typesense with higher values for those arguments (we hope to make this config change dynamic + API driven in the future).

The log looks fine at the end (there is no lag since the `applying_index` is `0`):

> I20210715 11:39:24.681211  1400 raft_server.cpp:565] Term: 4, last_index index: 20243, committed_index: 20243, known_applied_index: 20243, applying_index: 0, pending_index: 0, disk_index: 20243, pending_queue_size: 0, local_sequence: 781395750

So if you query now, it should succeed. Happy to further clarify any doubt you might have.

**Comment by huynv86** [comment]
i am also facing with this issue
i want to know how long time this lagging state will be? if this is short time then i can tell user please be patient and waiting for this lagging gone

**Comment by huynv86** [comment]
this is last log file,
![image](https://user-images.githubusercontent.com/747614/147569670-75d32506-8c49-45b5-929b-036077866745.png)

**Comment by kishorenc** [comment]
It should be ephemeral if too many write requests hit Typesense at the same time. However, from the log screenshot above that does not seem to be the case for you, because the `local_sequence` number is not changing too fast and the difference between the `applying_index` and `last_index` is not different.

**Comment by huynv86** [comment]
so how i can fix this. Currently our users can't using service, because it's not stable
![image](https://user-images.githubusercontent.com/747614/147572335-c5531f76-feb5-4a84-b81a-2893a612f972.png)

**Comment by huynv86** [comment]
even i restart server, restart Typesense but this error always is "Collection schema cannot contain a field with name `id`. Ignoring field."
![image](https://user-images.githubusercontent.com/747614/147572478-8c55be5d-28e4-490a-9479-1403e750910d.png)

**Comment by huynv86** [comment]
after deleting a collection of a new user, now it's work normally
unfortunately i can't determine the reason
