### ISSUE TITLE
potential readme update?

### ISSUE THREAD

**Issue by simin75simin** [typesense/typesense#317]
In readme, you said, 
> Algolia offers the following features that Typesense does not have currently: geo spatial searches

But "Geo search" is a feature described earlier?

**Comment by kishorenc** [comment]
Oh yes, we've to update this description. Geo search was just launched yesterday, so we missed updating this readme. Thanks for bringing this up.

**Comment by jasonbosco** [comment]
Fixed in https://github.com/typesense/typesense/commit/6d45d13737d627e1b373ff29c74ebac20de02ac9.
