### ISSUE TITLE
how to get more search results?

### ISSUE THREAD

**Issue by zjttfs** [typesense/typesense#322]
#### search -> `McDonald` 

![1](https://user-images.githubusercontent.com/24729880/126928938-a155cbb2-8aff-4a40-8619-46614e6018df.png)

--------------------

#### search -> `Fancy McDonald`

![2](https://user-images.githubusercontent.com/24729880/126929055-38eeebeb-b555-4a95-8603-f2c6cc3c23b8.png)

Hope that the results containing `McDonald` can be searched .
Not only search results for `Fancy McDonald` 

## Metadata
**Typsense Version**: 0.21
**OS**: centos

### data 

 > [
	{id: "230416", title: "英国 麦当劳 最新 广告 广告片 ： Fancy a McDonald s 笑 的 力量"},
	{id: "221890", title: "感觉 更 远 Ronald McDonald House Charities 加拿 加拿大"},
	{id: "222161", title: "两个 Amigos Tex Mex 堆栈 McDonald s 不列颠 大不列颠 联合 王国 联合王国"},
	{id: "221917", title: "巨无霸 50 McDonald s 瑞士"},
	{id: "221708", title: "Stackin Books 纽约 书库 McDonald s 不列颠 大不列颠 联合 王国 联合王国"},
	{id: "221565", title: "有些 早晨 ， 只有 麦当劳 的 早餐 就行了 McDonald s 不列颠 大不列颠 联合 王国 联合王国"},
	{id: "221506", title: "麦当劳 欧洲 储蓄 者 智者 通 McDonald s 葡萄 葡萄牙"},
	{id: "221324", title: "超级 英雄 McDonald s 不列颠 大不列颠 联合 王国 联合王国"}
	more........
]

### Collections:

> [
     'name' => 'zpb_video',
     'fields' => [  ['name' => 'title', 'type' => 'string']  ] 
 ]

**Comment by kishorenc** [comment]
@zjttfs  I don't follow you 100%. Are you looking to search for `Fancy McDonald` but want records containing **only** `McDonald` to also show up? 

You can paginate by using the `?page=X` parameter. Later pages should have records that contain only `McDonald`. Do read up on the `drop_tokens_threshold` parameter also -- this controls when tokens in the query should be dropped to surface more results.

**Comment by zjttfs** [comment]
@kishorenc 
set `drop_tokens_threshold = 100`.
![3](https://user-images.githubusercontent.com/24729880/126953693-e4f61ed3-339f-400d-9536-71c0c9eb2fb2.png)

After adding more keywords, the results become less again
search -> `Fancy McDonald 广告片  麦当劳 英国`

![4](https://user-images.githubusercontent.com/24729880/126953942-232decb5-72fa-4652-abe7-88556485b066.png)
`found: 4`

**Comment by kishorenc** [comment]
Typesense does not support searching for both Chinese and English characters in the same field. Support for CJK languages is currently in beta (see [here for usage](https://github.com/typesense/typesense/issues/288)). 

Can you give me an example with just English query? Also, to paginate, you can use `page` parameter. By default only first page is fetched and you can also control the number of documents returned per page with the `per_page` parameter.
