### ISSUE TITLE
Sorting by float fields doesn't work

### ISSUE THREAD

**Issue by morphine00** [typesense/typesense#326]
## Description

If you try and sort results by a float field, the collection remains unsorted.

## Steps to reproduce

Include a float field in a collection, search that collection, and try sorting by it.

## Expected Behavior

That either the sorting by float field works, or that the developer is informed that the feature isn't supported.

## Actual Behavior

The collection remains unsorted.

## Metadata

**Typsense Version**: 0.21.0

**OS**: Typesense admin panel; Instantsearch.js adapter

**Comment by morphine00** [comment]
Ah, addition: sorting with integer fields works fine.

**Comment by jasonbosco** [comment]
@morphine00 Here's an example that has "price" as a float field and sorting desc by that field seems to work fine: 

https://ecommerce-store.typesense.org/?products%5BhierarchicalMenu%5D%5Bcategories.lvl0%5D%5B0%5D=Cell%20Phones&products%5BsortBy%5D=products%2Fsort%2Fprice%3Adesc

Could you post a minimal dataset, collection schema and the exact search query to replicate this issue?

**Comment by morphine00** [comment]
Sure thing. It's TypeSense cloud cluster 5whf9nxq8l36p7yzp, you can probably a look there directly (I hope this is ok). If you try and sort by creation_date, which is a float field (timestamp), directly in the admin interface, the order appears to be incorrect. Is there a limit on the # of digits?

**Comment by jasonbosco** [comment]
@morphine00 For record-keeping purposes, could you email contact@typesense.org from the email address that is tied to the Github account you logged in with into Typesense Cloud, stating that it's ok to access your cluster data to debug this issue? 

(As a matter of policy, we do not access customer data, unless explicitly requested and documented).

**Comment by jasonbosco** [comment]
@morphine00 Thank you for the email. Could you make sure the `sort_by` field just has `creation_date:desc`, instead of `_text_match:desc, creation_date:desc`? This seems to work for me.

`creation_date:desc` is the equivalent of `creation_date:desc, _text_match:desc`.

Now, I did notice that `creation_date:asc` has an issue, which I suspect is because of floating point accuracy. Will take a look at this. In the meantime, one quick way to mitigate this issue with sort asc would be to use integer values to represent the timestamp field.

**Comment by morphine00** [comment]
Yep, I noticed that it's, uh, consistently inconsistent. I had already implemented and tested the integer workaround as we don't _need_ micro-second timestamps, but I figured I'd bring up the issue in case other folks run into it.

**Comment by kishorenc** [comment]
I'm going to close this issue -- please re-open if you find any non-timestamp float values being wrongly sorted.
