### ISSUE TITLE
[Bug report] Missing record with `typo_tokens_threshold=0`

### ISSUE THREAD

**Issue by goleary** [typesense/typesense#327]
## Description

When I query `julia` with `typo_tokens_threshold=0` a record with "Julia Angwin" does not show while a record with "Julian Shapiro" does show. If I get rid of the `typo_tokens_threshold` parameter both are returned.

## Steps to reproduce

Julia not returned (with `typo_tokens_threshold=0`)

![image](https://user-images.githubusercontent.com/16123225/127407847-b25d9bb4-a8fa-495e-ad70-ef3e41af10a6.png)

Julia returned (no `typo_tokens_threshold`)
![image](https://user-images.githubusercontent.com/16123225/127407869-624976ea-fac5-4cfc-8fa9-3e7d65266b12.png)

## Expected Behavior

Both Julia & Julian records are returned (with Julia ranked higher)

## Actual Behavior

only Julian record is returned.

## Metadata

**Typsense Version**: v0.21.0

**OS**: cloud

**Comment by jasonbosco** [comment]
This is fixed as of v0.22.0.rc3. 

Docker build: `typesense/typesense:0.22.0.rc3`
