### ISSUE TITLE
support of arrays of geopoint (geopoint[])

### ISSUE THREAD

**Issue by andrewsitt** [typesense/typesense#329]
We need to support search for companies which have multiple offices. 

What we would like to have is
1. support of geopoint[], and
2. the geo search filters by any geopoint in the array, 
3. and then sorts with reference to the geopoint in the array which is closest to the requested geopoint

**Comment by kishorenc** [comment]
@andrewsitt `geopoint[]` support landed on `typesense/typesense:0.22.0.rcs10` 

Please give it a spin and let me know.

**Comment by jasonbosco** [comment]
Released in v0.22
