### ISSUE TITLE
Error Logs | Docker ENV Variable - Define Verbosity

### ISSUE THREAD

**Issue by sagungargs15** [typesense/typesense#333]
## Description

Unable to set deeper logs (Request for ENV docker Variable)

## Steps to reproduce

ENV variable missing in the documentation

## Expected Behavior

See more verbose logs 

## Actual Behavior

Can't see when new collections are created or deleted there no error_logs if nothing works
Reference Sample: https://hasura.io/learn/graphql/hasura-advanced/debugging/2-logging-level/

## Metadata

**Typesense Version**: 0.21.0

**OS**: AWS Fargate 1.4

**Comment by kishorenc** [comment]
Typesense doesn't have a verbose logging mode. Logs are quite liberal already in terms of logging in tricky parts.

**Comment by alexsegura** [comment]
On the other side, I would be interested into a way to **reduce** verbosity
