### ISSUE TITLE
Collection search panel in cloud.typesense.org: trying to remove field in "Query By" box throws a JS error

### ISSUE THREAD

**Issue by morphine00** [typesense/typesense#335]
## Description

Collection search panel in cloud.typesense.org: trying to remove field in "Query By" box throws a JS error

## Steps to reproduce

1. Have more than one collection in a cluster.
2. Navigate to your second collection.
3. Click Search.
4. Scroll down to "Query By", try and remove one of the filters.
5. There will be a JS error and most of the UI stops working until you reload the page

![image](https://user-images.githubusercontent.com/14062988/128432859-58d24202-0e40-4cfd-9d40-960aad2928a4.png)

## Expected Behavior

The filter vanishes. This works okay for the first collection.

## Actual Behavior

A JavaScript error is through and most of the UI stops working until you reload the page.

## Metadata

**Typsense Version**: 0.21.0 (cluster)

**OS**: Chrome/Edge

**Comment by morphine00** [comment]
After investigation by @jasonbosco , turns out the problem is related to #328 . Closing this.

**Comment by jasonbosco** [comment]
Thank you for helping debug this 🙏
