### ISSUE TITLE
Adding a new field to an existing typesense collection

### ISSUE THREAD

**Issue by britisharmy** [typesense/typesense#337]
I have created a collection and somewhere down the line, i decide to add a new field to the existing collection. Is there a way i can do this?

So far the method i have seen to work is to delete the entire  collection plus the data just to add a new field.

A way to add a field would be such an awesome thing.

Thanks.

**Comment by jasonbosco** [comment]
As `v0.21.0`, you'd have to create a new collection with the updated schema and re-index the data unfortunately. We have an open item to make on-the-fly schema changes easier.

A couple of pointer to make this process easier:

1. I'd recommend setting up a [collection alias](https://typesense.org/docs/0.21.0/api/collection-alias.html) and updating your application to use the alias, so you can do a zero downtime switch when you change the collection schema.
2. If you have new fields that are added dynamically, an option to consider is using [auto-schema detection](https://typesense.org/docs/0.21.0/api/collections.html#with-auto-schema-detection) with regex field names:
