### ISSUE TITLE
Upserts inserting duplicate records

### ISSUE THREAD

**Issue by britisharmy** [typesense/typesense#339]
I have a long object with ten plus fields and i have noted something.  Lets say you have an object

```
curl "http://localhost:8108/collections/companies/documents?action=upsert" -X POST \
        -H "Content-Type: application/json" \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
        -d '{
          "userid": "124",
          "company_name": "Stark Industries",
          "num_employees": 5215,
          "country": "USA",
          "last_updated": 7737727728
        }'
```

if the same object has a new timestamp

```
curl "http://localhost:8108/collections/companies/documents?action=upsert" -X POST \
        -H "Content-Type: application/json" \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
        -d '{
          "userid": "124",
          "company_name": "Stark Industries",
          "num_employees": 5215,
          "country": "USA",
          "last_updated": 9999999999
        }'
```

typesense is inserting  a new record. Should it work like this or must the id be named `id` for the engine to realize its the same object, just a new last updated timestamp?

**Comment by kishorenc** [comment]
You should reference the `id` field for the engine to realize that it's an update and not a new document.

**Comment by britisharmy** [comment]
So, its doesn't matter whether the id field is called id in my typesense document or its called something else i.e userid?

**Comment by britisharmy** [comment]
Seen the part i wanted https://typesense.org/docs/0.21.0/api/documents.html#index-a-document

**Comment by jasonbosco** [comment]
For posterity: the ID field needs to be called “id”, otherwise Typesense will automatically assign an ID field to the document.
