### ISSUE TITLE
[Feature Request] Duplicate Collection

### ISSUE THREAD

**Issue by panoet** [typesense/typesense#342]
## Description

Sometime I need to duplicate collection as a backup just in case something goes wrong (e.g. when inserting data).

## Metadata

**Typsense Version**: cloud

**OS**: -

**Comment by kishorenc** [comment]
👋 @panoet In terms of back-up best practice, it's not a good idea to store the duplicate collection on the same Typesense host.  So, please use the `/export` end-point to take periodic backup of your collection data and store it elsewhere, for e.g. on S3.
