### ISSUE TITLE
Document proper way to shutdown/stop typesense-server

### ISSUE THREAD

**Issue by Sembiance** [typesense/typesense#347]
I didn't see in the docs what the proper way is to safely shutdown/stop the `typesense-server`

I assume the proper way is to simply issue a `SIGINT` kill signal to the `typesense-server` process and it will safely shut itself down. Is this correct?

If so, I feel like it should be documented somewhere...

By the way, typesense is great! I'm become a sponsor :)

**Comment by kishorenc** [comment]
👋 @Sembiance Thank you for supporting us!

> I assume the proper way is to simply issue a SIGINT kill signal to the typesense-server process 

Correct, Typesense handles the signal and gracefully waits for existing requests/writes to finish before shutting down. I will add this to our documentation, thanks for the heads up!
