### ISSUE TITLE
using sort_by

### ISSUE THREAD

**Issue by carlmendoza** [typesense/typesense#353]
New typesense user here, just wondering - does the `sort_by` option for searching documents only work on int fields? 

I currently have as my schema: 

```
 const submissionSchema = {
    'name': 'submissions',
    'fields': [
      {'name': 'submissionId', 'type': 'string' },
      ...
    ],
}
```

and for search:

```
  const searchParameters = {
      'q': q,
      'query_by': 'submissionId',
      'sort_by': 'submissionId:asc',
    }
```

but currently getting the error `Server said: Could not find a field named submissionId in the schema for sorting.`

**Comment by jasonbosco** [comment]
@carlmendoza That's correct, Typesense only supports sorting on integers and floats. 

There’s a workaround mentioned in this thread that you might find useful: https://github.com/typesense/typesense/issues/117

**Comment by carlmendoza** [comment]
thanks will have a look
