### ISSUE TITLE
Searching with * doesn't return all results

### ISSUE THREAD

**Issue by carlmendoza** [typesense/typesense#354]
Follow up question/enquiry - when I run a search with `q: '*'` to do search all essentially, I see that typesense doesn't return all of my results, until I run a search again with a valid search term.

Just wondering, is this by design i.e. only to show a subset of results until the user actually provides a good enough search term for typesense to work with.

Thanks in advance!

**Comment by jasonbosco** [comment]
@carlmendoza Typesense should return all results with a * query. 

For eg, a * query is used to populate this page on load: https://ecommerce-store.typesense.org/

Now the results are lag instead, so by default you will only get the first 10 results unless you change the per_page search parameter

**Comment by carlmendoza** [comment]
@jasonbosco thanks for both comments!
