### ISSUE TITLE
Querying within URLs (substring or partial search)

### ISSUE THREAD

**Issue by colinramsay** [typesense/typesense#355]
## Description

We are using Typesense for our site search and we have keywords in our URLs (product names). Typesense doesn't see query terms within URLs when we add them to a document.

## Steps to reproduce

```
curl "http://localhost:8108/collections" \
       -X POST \
       -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
       -d '{
         "name": "pages",
         "fields": [
           {"name": "url", "type": "string" }
         ]
       }'
```

```
curl "http://localhost:8108/collections/pages/documents" -X POST \
        -H "Content-Type: application/json" \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
        -d '{
          "url": "http://example.com/products/abc"
        }'
```

```
curl -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
"http://localhost:8108/collections/pages/documents/search\
?q=abc&query_by=url"
```

## Expected Behavior

The document with the URL "http://example.com/products/abc" should be returned, since it contains the query term.

## Actual Behavior

No results are returned.

## Metadata

**Typesense Version**:
0.22.0.rcu4

**OS**:
Ubuntu 20.04 running the docker image tagged 0.22.0.rcu4.

**Comment by colinramsay** [comment]
I _assume_ this is because Typesense stores the URL as a single string and doesn't actually do substring matching when querying. If I were to store the URL split on the folder separator, something like this:

`example.com products abc"

Then it would work but then I wouldn't be able to highlight the term within the URL.

**Comment by jasonbosco** [comment]
@colinramsay Yup, it's the same issue as #122. We're hoping to tackle this in the upcoming release, so you can choose which special characters to index vs use as word separators. If you want to subscribe to that issue, I'll post an update there when this out.

**Comment by mvuidev** [comment]
@jasonbosco Hi ! Any news on this one ? I'm facing the same issue (using 0.23.0). Thank you.

**Comment by mvuidev** [comment]
@jasonbosco Hi, i tried the new "token_separators" parameter and it seems to do the trick !
