### ISSUE TITLE
facet field must be a string

### ISSUE THREAD

**Issue by bnfd** [typesense/typesense#357]
I'm following the step by step instructions in the documentation (https://typesense.org/docs/0.21.0/guide/building-a-search-application.html#adding-books-to-the-collection) and when I try to add the books to the collection I get:

`typesense.exceptions.RequestMalformed: [Errno 400] Facet field `publication_year` must be a string or a string[].`

Here's the first line of the JSON file:
`{"publication_year_facet": "2008", "title": "The Hunger Games", "authors": ["Suzanne Collins"], "publication_year": 2008, "id": "1", "average_rating": 4.34, "image_url": "https://images.gr-assets.com/books/1447303603m/2767052.jpg", "ratings_count": 4780653, "authors_facet": ["Suzanne Collins"]}`

**Typesense Version**: 0.21.0

**OS**: Ubuntu

**Comment by jasonbosco** [comment]
@bnfd I just tried it and it worked fine. Could you make sure you're running v0.21.0 by hitting the `/debug` endpoint? 

If you are indeed running v0.21.0, could you do a `GET /collections` and post the output? Could you also post the exact python snippet you're using?

**Comment by bnfd** [comment]
@jasonbosco Sorry, I was running an earlier version.
