### ISSUE TITLE
A Postman collection would be great to have

### ISSUE THREAD

**Issue by zehawki** [typesense/typesense#360]
It would be great if you make a Postman collection available. Apologies if its already there - in which case, please point me to it. I simply could not find.

(I was able to get up and running within a few mins with Meili due to their rather amazingly well organized collection.)

PS: You may want to turn on discussions so that these kinds of requests dont go into issues.

**Comment by kishorenc** [comment]
We've a community contributed Postman collection now: https://github.com/typesense/postman
