### ISSUE TITLE
HTML tags should not be searchable

### ISSUE THREAD

**Issue by zehawki** [typesense/typesense#364]
## Description

A search for `<p>` `<h2>` etc etc matches the doc contents. This results in a match to everything when HTML content is part of a document.

The larger question is how Typesense intends to treat HTML tags. Will you strip away before indexing, or do you expect the input data to not have HTML tags.

I didnt see any mention about this in the docs...

**Comment by jasonbosco** [comment]
Typesense does not strip any html tags. Here's a way to still search through HTML docs: https://github.com/typesense/typesense/issues/265#issuecomment-832051823
