### ISSUE TITLE
Understanding memory usage

### ISSUE THREAD

**Issue by zehawki** [typesense/typesense#366]
## Description

So starting here https://typesense.org/docs/0.21.0/guide/system-requirements.html#choosing-ram

I've sent in 94 docs, 30% simple stuff like this

`{'channel_id': 429, 'channel_type': 'topics', 'content': '<p>Older article</p>', 'created_at': 20161224183000, 'desc': 'Older article', 'featured_slug': None, 'id': 'article_457', 'nn_domain': 'www.xyz.com', 'post_id': 457, 'post_subtype': 'G', 'post_type': 'article', 'slug': 'older-article', 'title': 'Older article'}`

` {'channel_id': 393, 'channel_type': 'topics', 'content': '<p>Article 1 for SA</p>', 'created_at': 20201207214524, 'desc': 'All MainCross plans are enabled for a global Content Delivery Network that spans over 200 cities in more than 100 countries, and provides for fast load times.', 'featured_slug': None, 'id': 'article_397', 'nn_domain': 'www.xyz.com', 'post_id': 397, 'post_subtype': 'G', 'post_type': 'article', 'slug': 'article-1-for-sa', 'title': 'Article 1 for SA'}
`
and 70% where the content value has upto ~800 words, but with the same keys as above. All these are really small pieces of data 2-4KB each, so lets round up to 400KB in the worse case.

Metrics gives me:

```
{
    "system_cpu1_active_percentage": "0.00",
    "system_cpu2_active_percentage": "0.00",
    "system_cpu_active_percentage": "0.00",
    "system_disk_total_bytes": "8259014656",
    "system_disk_used_bytes": "2677587968",
    "system_memory_total_bytes": "1,003,769,856",
    "system_memory_used_bytes": "406,765,568",
    "system_network_received_bytes": "542,656,715",
    "system_network_sent_bytes": "76,02,637",
    "typesense_memory_active_bytes": "56,938,496",
    "typesense_memory_allocated_bytes": "52,873,168",
    "typesense_memory_fragmentation_ratio": "0.07",
    "typesense_memory_mapped_bytes": "81,100,800",
    "typesense_memory_metadata_bytes": "51,70,064",
    "typesense_memory_resident_bytes": "56,938,496",
    "typesense_memory_retained_bytes": "20,086,784"
}

```
Which item should I be looking at here to understand RAM utilization and then check scaling as I load more docs. (I understand that given how the underlying OS manages RAM, garbage collection and who knows what else, it might not be so straightforward to report "actual" RAM used. I also understand that maybe this dataset is just too trivial to even get to an answer.)

**Typsense Version**:

v0.21

PS: Would be great if you could please format the values before returning in the API call, so that its hoooman readable ;-)

**Comment by zehawki** [comment]
Further info on the experiments. Next I deleted the collection, restarted the service. And here are metrics:

```
{
    "system_cpu1_active_percentage": "0.00",
    "system_cpu2_active_percentage": "0.00",
    "system_cpu_active_percentage": "0.00",
    "system_disk_total_bytes": "8259014656",
    "system_disk_used_bytes": "2673582080",
    "system_memory_total_bytes": "1003769856",
    "system_memory_used_bytes": "408670208",
    "system_network_received_bytes": "545221322",
    "system_network_sent_bytes": "7783451",
    "typesense_memory_active_bytes": "38776832",
    "typesense_memory_allocated_bytes": "35551456",
    "typesense_memory_fragmentation_ratio": "0.08",
    "typesense_memory_mapped_bytes": "63959040",
    "typesense_memory_metadata_bytes": "4547040",
    "typesense_memory_resident_bytes": "38776832",
    "typesense_memory_retained_bytes": "7868416"
}
```

**Comment by zehawki** [comment]
Another data point, this time after adding 89 articles to a new index. So there's 94 from the previous and 89 new and this time all the docs are certainly 4KB each.

```
{
    "system_cpu1_active_percentage": "0.00",
    "system_cpu2_active_percentage": "0.00",
    "system_cpu_active_percentage": "0.00",
    "system_disk_total_bytes": "8259014656",
    "system_disk_used_bytes": "2674245632",
    "system_memory_total_bytes": "1003769856",
    "system_memory_used_bytes": "394465280",
    "system_network_received_bytes": "546293109",
    "system_network_sent_bytes": "9811954",
    "typesense_memory_active_bytes": "52,404,224",
    "typesense_memory_allocated_bytes": "48,605,160",
    "typesense_memory_fragmentation_ratio": "0.07",
    "typesense_memory_mapped_bytes": "75,472,896",
    "typesense_memory_metadata_bytes": "51,27,952",
    "typesense_memory_resident_bytes": "52,404,224",
    "typesense_memory_retained_bytes": "17,326,080"
}
```

**Comment by kishorenc** [comment]
@zehawki 

`typesense_memory_active_bytes` is the best metric to track here because that metric is exposed directly from the memory allocator. Other memory counts can be a bit misleading because they will involve dirty caches or buffers that can be reused but not released to the OS so that it is more efficient. 

There is also some fixed overhead initially, for e.g. a fresh Typesense server will take about 35-40 MB of memory. 

Also the in-memory index initially starts out being sparse but once you ingest a few thousands documents, further documents will mostly contain tokens from previous documents, so the inverted index structure can reuse previously existing mappings so the memory growth will not be as steep as it is initially. So it is not prudent to extrapolate memory usage initially.

**Comment by zehawki** [comment]
Got it, thank you. Will update this thread once Ive added in many more docs.

**Comment by zehawki** [comment]
Another data point, now at 8100 docs to an index with ~8 facets

{
    "system_cpu1_active_percentage": "0.00",
    "system_cpu2_active_percentage": "0.00",
    "system_cpu_active_percentage": "0.00",
    "system_disk_total_bytes": "8259014656",
    "system_disk_used_bytes": "3395215360",
    "system_memory_total_bytes": "1003769856",
    "system_memory_used_bytes": "493723648",
    "system_network_received_bytes": "1201046787",
    "system_network_sent_bytes": "387610940",
    **"typesense_memory_active_bytes": "133,648,384",**
    "typesense_memory_allocated_bytes": "122997536",
    "typesense_memory_fragmentation_ratio": "0.08",
    "typesense_memory_mapped_bytes": "163459072",
    "typesense_memory_metadata_bytes": "8724128",
    "typesense_memory_resident_bytes": "133648384",
    "typesense_memory_retained_bytes": "65654784"
}

**Comment by kishorenc** [comment]
The memory growth should grow much smaller as you keep indexing more documents because there are finite number of words that can appear in datasets, and after enough documents are indexed, very few new words occur.

Btw, you might also want to try indexing against `typesense/typesense:0.22.0.rcs11` -- we've made some changes to reduce memory foot print (~20% on the datasets I tested).

**Comment by zehawki** [comment]
@kishorenc but that's not what I'm seeing BTW. Now at 11K docs, memory footprint has **doubled**.

{
    "system_cpu1_active_percentage": "0.00",
    "system_cpu2_active_percentage": "0.00",
    "system_cpu_active_percentage": "0.00",
    "system_disk_total_bytes": "8259014656",
    "system_disk_used_bytes": "4729315328",
    "system_memory_total_bytes": "1003769856",
    "system_memory_used_bytes": "635957248",
    "system_network_received_bytes": "3079865020",
    "system_network_sent_bytes": "5091764997",
    **"typesense_memory_active_bytes": "256,880,640",**
    "typesense_memory_allocated_bytes": "245777256",
    "typesense_memory_fragmentation_ratio": "0.04",
    "typesense_memory_mapped_bytes": "286523392",
    "typesense_memory_metadata_bytes": "11280032",
    "typesense_memory_resident_bytes": "256880640",
    "typesense_memory_retained_bytes": "72613888"
}
