### ISSUE TITLE
Unable to get correct order with sort_by

### ISSUE THREAD

**Issue by zehawki** [typesense/typesense#367]
## Description

I have a query with a sort_by on a created_at field, which does not seem to be sorting correctly. The results come in order as:

"created_at": 20210827211310,
"created_at": 20210827212221,
"created_at": 20210825004258,
"created_at": 20210825010459,
"created_at": 20210825105712,
"created_at": 20210825182208,
"created_at": 20210825191211,
"created_at": 20210825005943,

## Steps to reproduce

`Query = {{server_url}}/collections/{{collection_name}}/documents/search?q=*&query_by=title, desc, content&sort_by=created_at:desc`

Pertinent bit of the schema:

```
{
    "name": "created_at",
    "type": "float"
},
```

And a sample, each is similar:

```
{
    "channel_id": 394,
    "channel_type": "topics",
    "content": "<p>1st doc for Typesense</p>",
    "created_at": 20210827211310,
    "creator_username": "zehawk",
    "desc": "1st doc for Typesense",
    "featured_slug": "1st-doc-for-typesense",
    "id": "topic_conversation_1601",
    "nn_domain": "www.xyz.com",
    "post_id": 1601,
    "post_subtype": "O",
    "post_type": "conversation",
    "slug": "1st-doc-for-typesense",
    "title": "1st doc for Typesense"
}
```

**Typsense Version**:
v0.21

**Comment by kishorenc** [comment]
Float will not be able to store a large timestamp precisely. So it is truncating parts of the input and hence the order is haphazard. 

Please see my previous comment here: https://github.com/typesense/typesense/issues/114#issuecomment-643235078

**Comment by zehawki** [comment]
@kishorenc Yes of course, my bad.

Apologies for posting a duplicate, I really must search better.
