### ISSUE TITLE
search result wrong

### ISSUE THREAD

**Issue by HuynhVuong87** [typesense/typesense#374]
when i perform long pinned_hits then search result will be "{
    "message": "Parameter `q` is required."
}"
but if i decrease number of pinned_hits then it works well

this request bellow will return wrong result

https://localhost:8180/collections/RW2XEo1oLIcTaQ6ruwn569nGKGM2_PRODUCTS_COPY/documents/search?q=lljljljlkjljlkjljljlkjlkjllhlklljljljljljlkjlkjlkjlkjljlkjljkljlljljljlljkjkl&query_by=id&include_fields=id&per_page=250&pinned_hits=google.com_zzz_193275066_8135476537:1,google.com_fb_193275066_8135476537:2,google.com_ggg_193275066_8135476537:3,google.com_zzz_193275066_11913531307:4,google.com_fb_193275066_11913531307:5,google.com_ggg_193275066_11913531307:6,google.com_zzz_193275066_9851530924:7,google.com_fb_193275066_9851530924:8,google.com_ggg_193275066_9851530924:9,google.com_zzz_193275066_5783694082:10,google.com_fb_193275066_5783694082:11,google.com_ggg_193275066_5783694082:12,google.com_zzz_193275066_11816917110:13,google.com_fb_193275066_11816917110:14,google.com_ggg_193275066_11816917110:15,google.com_zzz_193275066_2972668159:16,google.com_fb_193275066_2972668159:17,google.com_ggg_193275066_2972668159:18,google.com_zzz_193275066_11614375486:19,google.com_fb_193275066_11614375486:20,google.com_ggg_193275066_11614375486:21,google.com_zzz_193275066_6085327860:22,google.com_fb_193275066_6085327860:23,google.com_ggg_193275066_6085327860:24,google.com_zzz_193275066_9371694366:25,google.com_fb_193275066_9371694366:26,google.com_ggg_193275066_9371694366:27,google.com_zzz_193275066_6888297085:28,google.com_fb_193275066_6888297085:29,google.com_ggg_193275066_6888297085:30,google.com_zzz_193275066_3038162631:31,google.com_fb_193275066_3038162631:32,google.com_ggg_193275066_3038162631:33,google.com_zzz_193275066_8035600673:34,google.com_fb_193275066_8035600673:35,google.com_ggg_193275066_8035600673:36,google.com_zzz_193275066_4484222910:37,google.com_fb_193275066_4484222910:38,google.com_ggg_193275066_4484222910:39,google.com_zzz_193275066_8536241397:40,google.com_fb_193275066_8536241397:41,google.com_ggg_193275066_8536241397:42,google.com_zzz_193275066_9936364614:43,google.com_fb_193275066_9936364614:44,google.com_ggg_193275066_9936364614:45,google.com_zzz_193275066_9636175832:46,google.com_fb_193275066_9636175832:47,google.com_ggg_193275066_9636175832:48,google.com_zzz_193275066_3884321192:49,google.com_fb_193275066_3884321192:50,google.com_ggg_193275066_3884321192:51,google.com_zzz_193275066_3686249208:52,google.com_fb_193275066_3686249208:53,google.com_ggg_193275066_3686249208:54,google.com_zzz_90674098_7367169194:55,google.com_fb_90674098_7367169194:56,google.com_ggg_90674098_7367169194:57,google.com_zzz_345832940_6483430775:58,google.com_fb_345832940_6483430775:59,google.com_ggg_345832940_6483430775:60,google.com_zzz_57067048_6429729731:61,google.com_fb_57067048_6429729731:62,google.com_ggg_57067048_6429729731:63,google.com_zzz_268337282_4637768395:64,google.com_fb_268337282_4637768395:65,google.com_ggg_268337282_4637768395:66,google.com_zzz_77826017_4305899652:67,google.com_fb_77826017_4305899652:68,google.com_ggg_77826017_4305899652:69,google.com_zzz_6081572_4625243431:70,google.com_fb_6081572_4625243431:71,google.com_ggg_6081572_4625243431:72,google.com_zzz_290355610_3345611652:73,google.com_fb_290355610_3345611652:74,google.com_ggg_290355610_3345611652:75,google.com_zzz_6081572_6954277392:76,google.com_fb_6081572_6954277392:77,google.com_ggg_6081572_6954277392:78,google.com_zzz_5595476_6543230405:79,google.com_fb_5595476_6543230405:80,google.com_ggg_5595476_6543230405:81,google.com_zzz_34835308_616354622:82,google.com_fb_34835308_616354622:83,google.com_ggg_34835308_616354622:84,google.com_zzz_29111827_2126499169:85,google.com_fb_29111827_2126499169:86,google.com_ggg_29111827_2126499169:87,google.com_zzz_347852836_5867290562:88,google.com_fb_347852836_5867290562:89,google.com_ggg_347852836_5867290562:90,google.com_zzz_104134564_9819585530:91,google.com_fb_104134564_9819585530:92,google.com_ggg_104134564_9819585530:93,google.com_zzz_8125544_4208824163:94,google.com_fb_8125544_4208824163:95,google.com_ggg_8125544_4208824163:96,google.com_zzz_31739770_5573977160:97,google.com_fb_31739770_5573977160:98,google.com_ggg_31739770_5573977160:99,google.com_zzz_54524288_9534399240:100,google.com_fb_54524288_9534399240:101,google.com_ggg_54524288_9534399240:102,google.com_zzz_79069470_5950886748:103,google.com_fb_79069470_5950886748:104,google.com_ggg_79069470_5950886748:105,google.com_zzz_299381127_9417250527:106,google.com_fb_299381127_9417250527:107,google.com_ggg_299381127_9417250527:108,google.com_zzz_301273598_7563848781:109,google.com_fb_301273598_7563848781:110,google.com_ggg_301273598_7563848781:111,google.com_zzz_8125544_5117041189:112,google.com_fb_8125544_5117041189:113,google.com_ggg_8125544_5117041189:114,google.com_zzz_9823458_2002160912:115,google.com_fb_9823458_2002160912:116,google.com_ggg_9823458_2002160912:117,google.com_zzz_67442159_2233429353:118,google.com_fb_67442159_2233429353:119,google.com_ggg_67442159_2233429353:120,google.com_zzz_22393535_1839459603:121,google.com_fb_22393535_1839459603:122,google.com_ggg_22393535_1839459603:123,google.com_zzz_5597373_7814622347:124,google.com_fb_5597373_7814622347:125,google.com_ggg_5597373_7814622347:126,google.com_zzz_334638366_3862850477:127,google.com_fb_334638366_3862850477:128,google.com_ggg_334638366_3862850477:129,google.com_zzz_43929679_2051114772:130,google.com_fb_43929679_2051114772:131,google.com_ggg_43929679_2051114772:132,google.com_zzz_138456569_5749139938:133,google.com_fb_138456569_5749139938:134,google.com_ggg_138456569_5749139938:135,google.com_zzz_29459282_6837003893:136,google.com_fb_29459282_6837003893:137,google.com_ggg_29459282_6837003893:138,google.com_zzz_23449214_5569626480:139,google.com_fb_23449214_5569626480:140,google.com_ggg_23449214_5569626480:141,google.com_zzz_112361139_4975706998:142,google.com_fb_112361139_4975706998:143,google.com_ggg_112361139_4975706998:144,google.com_zzz_60742701_7010921612:145,google.com_fb_60742701_7010921612:146,google.com_ggg_60742701_7010921612:147,google.com_zzz_333254830_4861419797:148,google.com_fb_333254830_4861419797:149,google.com_ggg_333254830_4861419797:150,google.com_zzz_237601165_4723930691:151,google.com_fb_237601165_4723930691:152,google.com_ggg_237601165_4723930691:153,google.com_zzz_4213659_8822623186:154,google.com_fb_4213659_8822623186:155,google.com_ggg_4213659_8822623186:156,google.com_zzz_104482128_6630426508:157,google.com_fb_104482128_6630426508:158,google.com_ggg_104482128_6630426508:159,google.com_zzz_58271199_11600586164:160,google.com_fb_58271199_11600586164:161,google.com_ggg_58271199_11600586164:162,google.com_zzz_20567150_5917809014:163,google.com_fb_20567150_5917809014:164,google.com_ggg_20567150_5917809014:165,google.com_zzz_240471082_5789787654:166,google.com_fb_240471082_5789787654:167,google.com_ggg_240471082_5789787654:168,google.com_zzz_70867169_4470540821:169,google.com_fb_70867169_4470540821:170,google.com_ggg_70867169_4470540821:171,google.com_zzz_80247184_1584866871:172,google.com_fb_80247184_1584866871:173,google.com_ggg_80247184_1584866871:174,google.com_zzz_135242200_2771383172:175,google.com_fb_135242200_2771383172:176,google.com_ggg_135242200_2771383172:177,google.com_zzz_26067095_6817038166:178,google.com_fb_26067095_6817038166:179,google.com_ggg_26067095_6817038166:180,google.com_zzz_161224619_6847495759:181,google.com_fb_161224619_6847495759:182,google.com_ggg_161224619_6847495759:183,google.com_zzz_61028488_6253534303:184,google.com_fb_61028488_6253534303:185,google.com_ggg_61028488_6253534303:186,google.com_zzz_7669738_4975015884:187,google.com_fb_7669738_4975015884:188,google.com_ggg_7669738_4975015884:189,google.com_zzz_32770552_7184862636:190,google.com_fb_32770552_7184862636:191,google.com_ggg_32770552_7184862636:192,google.com_zzz_51620379_4606772003:193,google.com_fb_51620379_4606772003:194,google.com_ggg_51620379_4606772003:195,google.com_zzz_280185368_8022772019:196,google.com_fb_280185368_8022772019:197,google.com_ggg_280185368_8022772019:198

**Comment by kishorenc** [comment]
@HuynhVuong87 GET query has a limit of 4K characters. A warning will be logged in Typesense server logs when a long query string exceeding 4K characters is made: I think the issue is because of this.

You will have to use the `multi_search` end-point which uses POST request.
