### ISSUE TITLE
[Feature Request] Exclude filtering on non-faceted fields

### ISSUE THREAD

**Issue by theodem** [typesense/typesense#377]
## Description

I currently have a collection with data created from lots of different users, each document contain a field 'creator_id'.
On our front, our users can access some documents EXCEPT their one documents, so the best way should be to exclude the documents that contain their own ID.

Currently one work-around is to facet the field 'creator_id' but that facet will not be used as intended so that might add some overhead on typesense server/memory, correct if i'm wrong ?

Another work-around is to fetch all the data then exclude on the front but that add unnecessary load on the bandwith as well as on the front.

## Actual Behavior

When performing exclude filtering on a non-faceted field (a string field for example), the server send the following error: "To perform exclude filtering, filter field `creator_id` must be a facet field."

## Metadata

**Typsense Version**: 0.21

**Comment by kishorenc** [comment]
@theodem 

I think we _should_ be able to do exclusion filtering now, without relying on the facet index. This limitation will be addressed in the near future. But, for now, I think the memory overhead of a facet index for a single-valued ID field should not be too much when compared to other indexing data structures.

**Comment by kishorenc** [comment]
We no longer use the facet indexing for exclusion filter. Closing.
