### ISSUE TITLE
[Feature Request] support id in filter_by query

### ISSUE THREAD

**Issue by goleary** [typesense/typesense#378]
## Description

I'd like to be able to do a bulk delete of documents using their `id`

using js:

```js
await typesenseClient
        .collections("collection_name")
        .documents()
        .delete({ filter_by: `id: [${deleteIds.join(',')}]` });
```

Currently this requires explicitly indexing the `id` field so that a query is successful.

It would be nice to have id based bulk delete supported out of the box.

I don't care if the syntax is consistent with the above, just that it's possible without needing the explicit index of `id`.

**Comment by noreff** [comment]
I also would be interested in that, currently I receive following error
`{"message": "To perform exact filtering, filter field `id` must be a facet field."}`

if I'm sending query like 
```
curl -H "X-TYPESENSE-API-KEY: ${API_KEY}" -X DELETE \ "${API_ENDPOINT}/collections/${COLLECTION}/documents?filter_by=id:[1, 2, 3, 4, 5]&batch_size=5"
```

Is there any way to do a bulk delete by id without making `id` a facet field?

**Comment by kishorenc** [comment]
It's not possible to do bulk delete by ID but this is certainly on our radar to fix. If you have any other numerical field for the document you can delete by filtering on it with a >= 0 filter.

**Comment by goleary** [comment]
@kishorenc I already mentioned this to you, but I'm looking to do a bulk delete of specific records, not wipe the entire collection.

**Comment by goleary** [comment]
@kishorenc I've actually tried using `filter_by` like we discussed & I get an error:

```
Server said: Could not find a filter field named `id` in the schema.
```

looks like maybe the `id` fields needs to be marked `facet: true`?  

I'm a little confused by this because I thought I could use filters on fields that are not faceted.

**Comment by huynv86** [comment]
hope this feature in future, i am waiting

**Comment by jasonbosco** [comment]
@huynv86 We addressed filtering by ID in a recent RC build. Could you try on `0.22.0.rcs40`? 

DEB: https://dl.typesense.org/releases/0.22.0.rcs40/typesense-server-0.22.0.rcs40-amd64.deb
Linux: wget https://dl.typesense.org/releases/0.22.0.rcs40/typesense-server-0.22.0.rcs40-linux-amd64.tar.gz
Docker: `typesense/typesense:0.22.0.rcs40`

**Comment by jasonbosco** [comment]
Released in v0.22

**Comment by goleary** [comment]
awesome, thanks!

**Comment by HuynhVuong87** [comment]
message: "Query string exceeds max allowed length of 4000. Use the /multi_search end-point for larger payloads."

how i can delete by query very long URL
example: delete by filter 1000 IDs
hope Typesense let me delete documents by query using POST method likes multi_search feature

**Comment by kishorenc** [comment]
You've to break into batches. It's anyway a good idea to do it since delete operations will block searches.
