### ISSUE TITLE
error request

### ISSUE THREAD

**Issue by HuynhVuong87** [typesense/typesense#379]
just sometime
![image](https://user-images.githubusercontent.com/37244262/132538449-9a00a806-7d0d-477b-8441-8f1a61533af4.png)

it works when i retry
this error appear several time per/day

**Comment by jasonbosco** [comment]
`ERR_NETWORK_CHANGED` sounds like there's some network connectivity issue. Could happen if your VPN connection frequently reconnects, or if there are many Wifi access points and your computer keeps switching between them, etc.

**Comment by HuynhVuong87** [comment]
thank you for your explain
i will keep watching and report to you
