### ISSUE TITLE
Persistent range values

### ISSUE THREAD

**Issue by yashiroiori** [typesense/typesense#384]
Into multi search how do to always get min and max values range when filter?? Like your example ecommerce but I don't use Instantsearch, used multi search perform, when send filter the values range it's chance with new filter but I need to get always min/max values of collection to config range slide component

Brand selected "Apple" values range selected "155,552" but min and max value remain
![image](https://user-images.githubusercontent.com/17031855/133299681-efce70a1-aae5-4862-9729-bfdfde417d87.png)

#My search

Original values range
![image](https://user-images.githubusercontent.com/17031855/133300156-9c9b76f2-bdba-42c2-af40-50c79940ddb6.png)

After some filter new values, in this part need to get original range values [max: 4999710, min:110063] and filtered range values [max: 1111820, min:110063], how get both values??
![image](https://user-images.githubusercontent.com/17031855/133300262-9ad66dfe-470c-4fe3-bf62-c7266105e772.png)

Range slide always with original values to set into range slide and set filtering data with values selected to filter
![image](https://user-images.githubusercontent.com/17031855/133300414-b3d72c48-7795-4f67-b5b2-1094aaa78c2c.png)

Range slide component
![image](https://user-images.githubusercontent.com/17031855/133300782-e75e54b4-26c3-4328-8e1b-76e11acc55ac.png)

Actually searchRequest
![image](https://user-images.githubusercontent.com/17031855/133301137-ece7beb1-cf19-4c21-85bd-49cc7ed04629.png)

**Comment by jasonbosco** [comment]
@yashiroiori You could add another search query to your multi-search request, without any filters and `facet_by: price` to get the min and max value and use that in the range slider. 

On a side note, you can also look at the network requests in the dev console for the ecommerce demo to see what queries are being sent to Typesense. You can then use similar queries in your app.
