### ISSUE TITLE
Update document

### ISSUE THREAD

**Issue by huynv86** [typesense/typesense#385]
I can delete a document but i cannot update it because unauthorized key. Even i can delete document with the same apikey

**Comment by kishorenc** [comment]
Did you check the permissions of the key you are using?

If you are able to reproduce this problem consistently, can you post a code snippet that shows the problem?

**Comment by huynv86** [comment]
as i mentioned in my other issue https://github.com/typesense/typesense/issues/391, my typesense data was broken. I re-indexed and it works well
please release new version soon
with this error then i can't use typesense in production

**Comment by jasonbosco** [comment]
We just release v0.22 yesterday.
