### ISSUE TITLE
[Feature Request] Support Range Facet

### ISSUE THREAD

**Issue by aleris** [typesense/typesense#386]
## Description

Allow facets to define ranges for numerical values, for when the entire range of values is very big, like for example for monetary values. A category like facet cannot work for this case as there are just too many different values.

This would work similar with the elasticsearch Range Facet (https://www.elastic.co/guide/en/app-search/current/facets-guide.html):

```json
{
  "type": "range",
  "ranges": [
    { "from": 1, "to": 150000, "name": "Not busy" },
    { "from": 150000, "to": 500000, "name": "Somewhat busy" },
    { "from": 500000, "name": "Very busy"}
  ]
}
```

**Comment by biendinh** [comment]
I upgraded to v0.25 but I didn't know how to use this feature.
Please make a document on this feature.

Thanks.

**Comment by kishorenc** [comment]
@biendinh 

I've just documented this here: https://typesense.org/docs/0.25.0/api/search.html#facet-ranges
