### ISSUE TITLE
Using wildcard in exclude_fields

### ISSUE THREAD

**Issue by seowzhenjun0126** [typesense/typesense#389]
Hi, when creating a new collection, it is possible to use wildcard to index a field.

Can I do the same for `exclude_fields` when performing search? Ideally I want to exclude the same wildcard field that I have specified when creating the collection.

Thanks!

**Comment by kishorenc** [comment]
@seowzhenjun0126 I don't follow your question. Can you give me an example?

**Comment by seowzhenjun0126** [comment]
I am using the following field in my schema when creating collection:

`{ name: '^receive_time.*', type: 'int64', facet: true }`

Here `receive_time` is an object with each user id as the nested key. It could be something like this:

`{
    ...,
    receive_time: {
        user_id_1: 1632538167865,
        user_id_2: 1632538230910,
    },
    ...
}`

where `user_id` could be any id from my app. I've flatten the object before sending it to Typesense.

I want to sort data using this field, but do not want to return the value to user. I tried doing something like this:

`exclude_fields: receive_time.*`

but it doesn't seems like it's working.

Do you have any suggestions as to how I'd achieve this?

**Comment by kishorenc** [comment]
@seowzhenjun0126 Typesense does not support indexing and querying on fields in embedded/nested objects. We've a feature request open for this here: https://github.com/typesense/typesense/issues/227
