### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by unclescooby** [typesense/typesense#390]
## Description

Did some schema setup and indexing tests and found several issues. Whether those are bugs or (lack of) features is for you to decide... 

- when data coercion is enabled this also adds conversion behaviour to explicit fields. Seems like the coercion feature minus inferred datatype. The docs only mention coercion for auto fields inferred type.
- data coercion in general: does not support conversion from scalar to array and vice versa, eg. sending an int value to a field with type int32[]
- **_EDIT_**: cannot replicate this now - probably observed this with v0.20.0 .... field with type string* does not accept array containing int or bool (unless first value in first array was a string)
- field with type string*, locks in the first type you send, like inferred datatype of auto field, eg. if first sending an array, next value must also be an array
- regex fields do not accept null... **_EDIT_**: that was incorrect. It should be: regex fields of any type, and wildcard of type auto do not accept null as the first value sent
- for fields not in the schema: null is not removed from the data
- data coercion: regex field type int32: send a numeric string: value does not get converted to int (not tested with other datatypes, but it looks like data coercion/conversion does not work for regex fields)
- data coercion: regex field type int32: first send an int, next send a numeric string: all values become int. As I noticed above string did not get converted to int, I suspect it's fieldtype auto inferred type behavior...
- data coercion: regex field type int32: first send a numeric string, next send an int: all values become strings. This seems to confirm it's fieldtype auto behavior, when it should be int32
- regex field does not accept empty arrays, even when fieldtype is set to an array fieldtype such as string[]. The wildcard does accept empty arrays (not for fieldtype auto, which makes sense)

## Steps to reproduce

Using: typesense-server-0.21.0-1.x86_64.rpm

Just setup schema as the companies examples in the api docs and added an extra field for testing ... then indexed some documents with the import endpoint, again with values from the api examples, and an extra field for testing. Then I used the retrieve document endpoint to view the resulting documents.

For regex field testing I made sure not to have a wildcard in the schema to avoid [another bug](https://github.com/typesense/typesense/issues/388) that could possibly override handling/behaviour.

To enable data coercion I used a regex field that does not match any fieldname sent for indexing.

## Metadata

**Typsense Version**: 0.21 

**OS**: Linux CentOS 7

**Comment by kishorenc** [comment]
@unclescooby Thank you, this is an amazing list. I will go through the list in detail and respond, but quick comment regarding coercion: certainly the intention is to provide that for both explicit and inferred types.

**Comment by unclescooby** [comment]
You're welcome. I 'm surprised those issue were not noticed. It may be an issue with the rpm package only? Re the regex fields, If I recall the coercion does work if fieldtype is auto, but not with other types. Please check/verify for yourself...

**Comment by unclescooby** [comment]
An addition to the 2nd point: this also goes for inferred type. Eg. wildcard field type auto: first send an array, next send a string, will return an error saying that the field must be an array. Note that this doesn't occur for a regex field, but that's probably because of current regex limited functionality.

**Comment by kishorenc** [comment]
Atleast with the coercision to/from array, it was intentional: the goal with coercion was to deal with simple data mapping errors. I was not sure if coercing an array to a singular value by picking the first value or vice versa will fall into that category.

**Comment by unclescooby** [comment]
Well, I can understand that if I send an int to an int32[] field that it wouldn't accept it. I can also understand that if a field picked up via autofield is inferred as string, then next sending an array, does not get accepted.

What I cannot understand that this doesn't work for a string* field which is advertised as doing just that, From the API docs: Defining a type as string* allows Typesense to accept both singular and multi-value/array values.

**Comment by unclescooby** [comment]
So I wondered how my application could properly prepare field data so it will send correct types. Then I realized it would be helpful if I can get fieldtypes from the collection schema. And happy to find that fields picked up via regex/wildcard are actually added to the collection (schema). So did some testing, first sending an int, next sending numeric string to following fields:

1. wildcard field type AUTO
2. wildcard field type STRING
3. regex field type AUTO
4. regex field type STRING

In typesense 0.21.0 I'm seeing bug in #4: fieldtype and all values should be string, but instead fieldtype become int64 inferred from first value, and all values are int. This confirms the regex field bug reported above.

Then checked v 0.20.0 and the bug wasn't there. Instead it had a bug with #3: added fieldtype is auto and values are not converted at all.

So, it's great that the latter bug was fixed, now I hope the bug with #4 will be fixed.

**Comment by kishorenc** [comment]
> What I cannot understand that this doesn't work for a string* field which is advertised as doing just that
>  From the API docs: _Defining a type as string* allows Typesense to accept both singular and multi-value/array values._

@unclescooby 

That description is misleading, sorry about that! The intent behind the `string*` type is for a case when you have no idea whether a particular field is a singular string value or a multi-valued string (i.e. array). In such a scenario you will use a `string*` and the the type will be inferred by the _first value_ that appears for a field. So, `string*` will accept either a single/array string depending on the first document that is ingested, but subsequently cannot accept both. 

In general, I think it might make sense to coerce single values to arrays, if the previous values have been arrays. However, that behavior will not be confined only to `string*`.

**Comment by unclescooby** [comment]
Hmm that's indeed a big difference. So the docs should be changed to explain the either/or behaviour.

> In general, I think it might make sense to coerce single values to arrays, if the previous values have been arrays. However, that behavior will not be confined only to string*.

I agree. It's just a matter of ensuring it's correct type then wrap in an array. Having such feature for all fieldtypes would be great. 

> I was not sure if coercing an array to a singular value by picking the first value ...

Array to singular is harder to achieve. Picking first value (whic may not be of correct type.. nested array even). Stringify or json encode if the field must be a string, array count if it needs to be an int, etc. I'm currently working with processwire cms and [here's how ](https://github.com/processwire/processwire/blob/master/wire/core/Sanitizer.php#L3564)the author converts array to string (PHP). Perhaps offer something like that as a configurable feature.

**Comment by unclescooby** [comment]
Was doing some more testing with regex and wildcard fields, type auto and type string. Found that all 4 of these accept null if the first value was not null. If the first value sent is also null (a very possible scenario) then wildcard type string very happily accepts that, whereas regex type string does not. For fieldtype auto both wildcard and regex do not accept it. I'd suggest that if a first value is null typesense completely ignore that field: don't flag "first value received", don't throw an error, don't create the schema field and index the document without that field value. Then as soon as that field comes in with an acceptable value, process it as a new field.

**Comment by unclescooby** [comment]
As I learned more about how typesense data coercion and regex fields works, I'm closing this thread and leaving it for reference. In the meantime I've created a new issue for regex fields.
