### ISSUE TITLE
Unexpected token c in JSON at position 2","level":"error"

### ISSUE THREAD

**Issue by WatanabeThiago** [typesense/typesense#394]
Unexpected token c in JSON at position 2","level":"error"

![image](https://user-images.githubusercontent.com/50850299/135294602-be7a3642-5ca4-4c2b-9514-904b0559fbc7.png)

**Comment by kishorenc** [comment]
@WatanabeThiago Where did you get this error? Do you have a code snippet that I can run to reproduce the error?
