### ISSUE TITLE
Install Typesense via deb and rpm

### ISSUE THREAD

**Issue by kishorenc** [typesense/typesense#40]
## Description

Currently we only publish a tarball with just the executable. Having a proper deb and rpm would allow us to package a systemd/init.d script that makes administration/stop/start etc. easier.

## Steps to reproduce

NA

## Expected Behavior

We should be able to install from a deb/rpm and do `service typesense start/stop/status/restart`.

## Actual Behavior

NA

## Metadata

 **Typsense Version**: `0.10.x`

**OS**: `all`

**Comment by jasonbosco** [comment]
@kishorenc Do we already have a way to pass in options via a config file rather than the command line? I was thinking, when we daemonize via an init script, it will be cumbersome to edit the init script every time when users need to change config file values. So it will be beneficial to implement config file parsing for options before we daemonize. What do you think?

**Comment by kishorenc** [comment]
That makes sense. I've created https://github.com/typesense/typesense/issues/41.

**Comment by LethalPants** [comment]
Has this been implemented? I want to use typesense in WSL which supports `service start/stop` instead of `systemctl...`

**Comment by jasonbosco** [comment]
@LethalPants Yes, here are the deb and rpm packages: https://typesense.org/downloads/

**Comment by nogamenofun98** [comment]
When using the source from this `wget https://dl.typesense.org/releases/0.20.0/typesense-server-0.20.0-1.x86_64.rpm`

It still using systemd instead of service start/stop. i run in wsl Ubuntu 20.04 LTS

**Comment by kishorenc** [comment]
For Ubuntu you should use the DEB and not RPM.

**Comment by nogamenofun98** [comment]
I tried using DEB one also same result, using this command "sudo apt install ./typesense-server-0.20.0-amd64.deb"

**Comment by kishorenc** [comment]
Can you please post what specific error message you are seeing?

**Comment by kishorenc** [comment]
Ok I just found that WSL does not enable systemctl by default. However there seems to be a work around here: https://github.com/DamionGans/ubuntu-wsl2-systemd-script

Have you tried that?
