### ISSUE TITLE
Error Format Data

### ISSUE THREAD

**Issue by nelsonxx1** [typesense/typesense#403]
## Description

While I was uploading Data to the 3-node cluster of Typesense in Docker, the script stopped and also the node 2

## Steps to reproduce

add logs

client error

![image (1)](https://user-images.githubusercontent.com/999292/137383548-c98d182a-dd69-4b5f-bf5d-35af4df8b65a.png)

server logs, stop and stop in start again

[output.log](https://github.com/typesense/typesense/files/7348874/output.log)

## Expected Behavior

No errors

## Actual Behavior

Throws Error and Stop node server

## Metadata

**Typsense Version**: docker images typesense/typesense:0.22.0.rcs14

**OS**: Ubuntu 20.04.3 LT

**Comment by nelsonxx1** [comment]
The Node 1 and 3 its run. I create one snapshot to node 3 and delete data in node 2 and copy snapshot to node 2 and start, Produce the same error when the data is indexing

**Comment by nelsonxx1** [comment]
update to docker image  typesense/typesense:0.22.0.rcs16

![image](https://user-images.githubusercontent.com/999292/137579814-068f73ab-74c6-4848-b418-ba972b784edc.png)

**Comment by nelsonxx1** [comment]
typesense/typesense:0.22.0.rcs17

![image](https://user-images.githubusercontent.com/999292/137580593-d60bd54c-fa3f-4ba8-b9a6-2eabfc67cfa3.png)

**Comment by jasonbosco** [comment]
Released in v0.22
