### ISSUE TITLE
Weird search behavior

### ISSUE THREAD

**Issue by option-greek** [typesense/typesense#404]
## Description

When query contains short terms (mug/cup etc), they match completely unrelated results (I'm guessing due to typo distance)

## Steps to reproduce

https://ip/collections/products/documents/search?q=coffee%20cup&query_by=name,descr,keywords,product_categories&filter_by=store_lat_long%3A(12.973801,77.611885,6%20km)&facet_by=brand,color,size,age_bracket,gender

https://ip/collections/products/documents/search?q=coffee%20mug&query_by=name,descr,keywords,product_categories&filter_by=store_lat_long%3A(12.973801,77.611885,6%20km)&facet_by=brand,color,size,age_bracket,gender

## Expected Behavior

Should not match the below strings (in name or description):
Cadbury Bournville Rich Cocoa 70% Dark Chocolate Bar, 3 x 80g
Cadbury Bournville 70% Dark chocolate. 

## Actual Behavior

coffee+cup matches "Cadbury Bournville 70% Dark chocolate. " due to "Cadbury" token
coffee+mug matches "Cadbury Bournville Rich Cocoa 70% Dark Chocolate Bar, 3 x 80g" due to "80g" token

## Metadata

**Typsense Version**: 0.21 (latest)

**OS**: linux
[full_results.txt](https://github.com/typesense/typesense/files/7353873/full_results.txt)

**Comment by option-greek** [comment]
Thanks @kishorenc . That worked like a charm. I'm curious about the actual fix. Will this have any impact on the typo logic ( may be avoiding typo correction for short words ?). Also, any timeline on when this might be released.

**Comment by jasonbosco** [comment]
Released in v0.22
