### ISSUE TITLE
Some records are lost when searching for a query

### ISSUE THREAD

**Issue by maxvoronov** [typesense/typesense#408]
## Description
Hi team. We spotted a problem with searching. We have huge collection with ~29 millions records, which contain simple string field with part number (only [A-Z0-9]+ symbols) and other fields.

When we try to find record by not full part number, then TypeSense will lost some records in results.

## Steps to reproduce

Add to collection records with different part numbers. Also add 141 records for testing with part number like `J28292xxx`, where `xxx` is some digits. After try to search with parameters:
```json
{"q": "J28292", "query_by": "number", "num_typos": 0}
```
P.S.: Default `num_typos = 2` has same behaviour.

## Expected Behavior

We expect to 141 records in search results:
```json
{
    "facet_counts": [],
    "found": 141,
    "hits": [...]
}
```

## Actual Behavior

We got only 40 records. Some records was lost, but we can find them if pass full part number (like `J28292118`).
```json
{
    "facet_counts": [],
    "found": 40,
    "hits": [...]
}
```

## Metadata

**Typsense Version**: v0.21.0
**Docker image**: typesense/typesense:0.21.0
**OS**: Linux

**Comment by MaxVoronov** [comment]
Hi @kishorenc,
Yeah, we have tested v0.22.0.rcs18 and all works great. Thank you so much.
Please can you tell me, when do you plan to release v0.22.0?
