### ISSUE TITLE
Typesense server doesn't start

### ISSUE THREAD

**Issue by shah-mcc** [typesense/typesense#423]
## Description

The server doesn't start.
```
typesense-server.service: Failed with result 'signal'.
Failed to start Typesense Server.
```

## Steps to reproduce

Brand new install on Ubuntu 20.04.3 LTS
```
wget https://dl.typesense.org/releases/0.21.0/typesense-server-0.21.0-amd64.deb
sudo apt install ./typesense-server-0.21.0-amd64.deb
```

## Expected Behavior

The server should start.

## Actual Behavior

Relevant log entries
```
W20211028 16:14:55.687260  1289 protobuf_file.cpp:91] open file failed, path: /var/lib/typesense/state/log/log_meta: FILE_ERROR_NOT_FOUND
W20211028 16:14:55.687273  1289 log.cpp:685] /var/lib/typesense/state/log is empty
I20211028 16:14:55.707548  1289 log.cpp:1136] log save_meta /var/lib/typesense/state/log/log_meta first_log_index: 1 time: 20239
W20211028 16:14:55.707703  1289 protobuf_file.cpp:91] open file failed, path: /var/lib/typesense/state/meta/raft_meta: FILE_ERROR_NOT_FOUND
I20211028 16:14:55.707736  1289 raft_meta.cpp:521] Loaded single stable meta, path /var/lib/typesense/state/meta term 1 votedfor 0.0.0.0:0:0 time: 26
W20211028 16:14:55.711993  1289 protobuf_file.cpp:91] open file failed, path: /var/lib/typesense/state/meta/raft_meta: FILE_ERROR_NOT_FOUND

```

## Metadata

**Typsense Version**: 0.21.0

**OS**: Ubuntu 20.04.3 LTS

**Comment by shah-mcc** [comment]
When I try to run the binary directly I get the following error in `/var/log/syslog`
```
Oct 30 08:53:34 ubuntu-server kernel: [ 1535.926828] traps: typesense-serve[3659] trap invalid opcode ip:c8df75 sp:7fb6acc74468 error:0 in typesense-server[911000+f5a000]
```
Is there anything else I need to do? Is there any other place I need to check for logs?

**Comment by kishorenc** [comment]
Can you please tell me what underlying CPU architecture you are using? Also, are you using any virtualization layer? It seems like the binary is not fully compatible with the underlying architecture.

**Comment by shah-mcc** [comment]
After running `lscpu`
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   36 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           23
Model name:                      Pentium(R) Dual-Core  CPU      E5700  @ 3.00GHz
Stepping:                        10
CPU MHz:                         1200.276
CPU max MHz:                     3003.0000
CPU min MHz:                     1203.0000
BogoMIPS:                        6001.38
Virtualization:                  VT-x
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        2 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX EPT disabled
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT disabled
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse3
                                 6 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_
                                 tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 mo
                                 nitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm xsave lahf_lm pti tpr_sh
                                 adow vnmi flexpriority dtherm
```

**Comment by kishorenc** [comment]
The processor does not seem to support AVX (pre-2011) so I think that might be the issue here. I just did a objdump of the Typesense Linux binary and it indeed uses AVX instructions like `vpbroadcastq`. We probably won't be able to support non-AVX processors.

**Comment by shah-mcc** [comment]
No issues. Thanks for all the help. I will install typesense on a linode instance for testing. The CPU is quite old but it still works fine as a small dev server with the latest versions of nginx, redis, nodejs and postgres with 3 remote developers connecting via VSCode remote.
My only suggestion is maybe you guys can mention the required instructions somewhere so others can check before installing or unnecessarily creating github issues,

**Comment by kishorenc** [comment]
I agree, we will certainly add the processor requirements to the documentation. The AVX instructions are needed to speed up the underlying algorithms that Typesense uses, and it's an oversight on my part of have forgotten about adding this as a requirement.

Thank you for helping in the investigation!

**Comment by kishorenc** [comment]
I will leave this issue open, maybe you can confirm after you try on Linode.

**Comment by shah-mcc** [comment]
It works just fine on Linode. I am already using it with my dummy data.

**Comment by kishorenc** [comment]
Thank you for confirming.

**Comment by 756yang** [comment]
After my inspection, the official archive compiled by typesense supports most x64 platforms. Based on the platform instruction set, it requires at least SSE2, SSSE3, SSE4.1 support, and may require SSE3 and SSE4.2 support.

The AVX instruction set is additional and not necessarily required.

**Comment by Allan-Nava** [comment]
I created the **/var/log/typesense** but I have this error:
```

Dec 12 09:04:41 dev-typesense-01 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl restart typesense-server _uses_shell=True stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
Dec 12 09:04:41 dev-typesense-01 systemd[1]: Started Typesense Server.
Dec 12 09:04:41 dev-typesense-01 typesense-server[13827]: Typesense failed to start. Log directory "/var/log/typesense" does not exist.
Dec 12 09:04:41 dev-typesense-01 systemd[1]: typesense-server.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 09:04:41 dev-typesense-01 systemd[1]: typesense-server.service: Failed with result 'exit-code'.

```

**Comment by 756yang** [comment]
> I created the **/var/log/typesense** but I have this error:
> 
> ```
> 
> Dec 12 09:04:41 dev-typesense-01 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl restart typesense-server _uses_shell=True stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
> Dec 12 09:04:41 dev-typesense-01 systemd[1]: Started Typesense Server.
> Dec 12 09:04:41 dev-typesense-01 typesense-server[13827]: Typesense failed to start. Log directory "/var/log/typesense" does not exist.
> Dec 12 09:04:41 dev-typesense-01 systemd[1]: typesense-server.service: Main process exited, code=exited, status=1/FAILURE
> Dec 12 09:04:41 dev-typesense-01 systemd[1]: typesense-server.service: Failed with result 'exit-code'.
> ```

@Allan-Nava you could check your cpu features, may be not support SSE41 or SSE42.
or you could download typesense binary file from official github, just run it.

**Comment by Allan-Nava** [comment]
> > I created the **/var/log/typesense** but I have this error:
> > ```
> > 
> > Dec 12 09:04:41 dev-typesense-01 ansible-ansible.legacy.command: Invoked with _raw_params=systemctl restart typesense-server _uses_shell=True stdin_add_newline=True strip_empty_ends=True argv=None chdir=None executable=None creates=None removes=None stdin=None
> > Dec 12 09:04:41 dev-typesense-01 systemd[1]: Started Typesense Server.
> > Dec 12 09:04:41 dev-typesense-01 typesense-server[13827]: Typesense failed to start. Log directory "/var/log/typesense" does not exist.
> > Dec 12 09:04:41 dev-typesense-01 systemd[1]: typesense-server.service: Main process exited, code=exited, status=1/FAILURE
> > Dec 12 09:04:41 dev-typesense-01 systemd[1]: typesense-server.service: Failed with result 'exit-code'.
> > ```
> 
> @Allan-Nava you could check your cpu features, may be not support SSE41 or SSE42. or you could download typesense binary file from official github, just run it.

The configuration was not correct with ini i put = "/var/log/typesense"
