### ISSUE TITLE
exact match for repeated words

### ISSUE THREAD

**Issue by dokudoki** [typesense/typesense#427]
## Description

When searching for repeated words such as "Boom Boom". It seems to ignores the repeated word from query.

## Steps to reproduce
`q="Boom Boom"`
`prioritize_exact_match=true`

https://songs-search.typesense.org/?songs_1630520530850%5Bquery%5D=boom%20boom

## Expected Behavior

"Boom Boom" should be first in the results

## Actual Behavior

"Boom Boom" is not in the results or don't have higher priority.

## Metadata

**Typsense Version**: 0.21

**OS**: linux

**Comment by kishorenc** [comment]
Fixed in `0.23.0.rc59`.
