### ISSUE TITLE
facet_query exact matches

### ISSUE THREAD

**Issue by simonhayward** [typesense/typesense#429]
## Description

When searching within a facet using `facet_query` we want only exact matches returned so essentially with parameters: `num_typos=0` set. It is possible to restrict the `facet_query` in the same way as the main query `q` so we can restrict the matches to exact query matches, so applying `num_typos` to `facet_query` ?

## Metadata

**Typsense Version**: Typesense v0.21.0

**OS**: Cloud

**Comment by nekkon** [comment]
+1

**Comment by kishorenc** [comment]
Thanks for creating this feature request. We have to expose the parameter to control num_typos for facet query to the API.

**Comment by kishorenc** [comment]
This is available on `0.23.0.rc44` as `facet_query_num_typos` parameter (default: `2`).
