### ISSUE TITLE
Document update with null values

### ISSUE THREAD

**Issue by ferusm** [typesense/typesense#435]
## Description

Unable to set property to null when using document update operation

## Steps to reproduce

1. Craete document with optional ```refId``` field;
2. Try update it with payload like:
```
{
  id: "12345",
  refId: null
}
```

## Expected Behavior

When I post the payload to the PATCH method, I expect the document field to be updated with the value from the payload field

P.S. PATCH method must ```patch``` document.

## Actual Behavior

Payload properties with ```null``` value are ignored

## Metadata

**Typsense Version**: 0.21.0

**OS**: Win 11

**Comment by unclescooby** [comment]
@kishorenc please see my last comment in #401

**Comment by kishorenc** [comment]
@ferusm This is a very good catch, thank for reporting it. We are currently dropping the `null` values from the document before indexing. This is fine for initial creation of the document, but for updates it ends up not removing the value from the previously stored document. We will fix it.

**Comment by kishorenc** [comment]
@ferusm Can you please test against this Docker build: `typesense/typesense:0.22.0.rcs30`

**Comment by sMunkKk** [comment]
@kishorenc Do you have date for this patch in prod ?

**Comment by kishorenc** [comment]
This is already fixed in v0.22.

**Comment by sMunkKk** [comment]
@kishorenc Nice 👍 Thank you 😉
