### ISSUE TITLE
Unexpected behavior when using exhaustive_search parameter

### ISSUE THREAD

**Issue by maxvoronov** [typesense/typesense#437]
In some cases when we use parameter `exhaustive_search=true` we can got incorrect results or wait result too long time.

### Case 1: incorrect result
Query params: `q=5758&query_by=number&num_typos=0&per_page=10&include_fields=id,number,is_oem&exhaustive_search=true`
Where:
- **number**: string, contains only [A-Z0-9]+
- **is_oem**: bool, facet=true, optional=true

Result:
```json
{
    "facet_counts": [],
    "found": 2277,
    "hits": [
        {
            "document": {
                "id": "1182329",
                "is_oem": false,
                "number": "5758"
            },
            "highlights": [
                {
                    "field": "number",
                    "matched_tokens": [
                        "5758"
                    ],
                    "snippet": "<mark>5758</mark>"
                }
            ],
            "text_match": 33514497
        },  {
            "document": {
                "id": "49682314",
                "is_oem": true,
                "number": "5758243000"
            },
            "highlights": [
                {
                    "field": "number",
                    "matched_tokens": [
                        "5758243000"
                    ],
                    "snippet": "<mark>5758243000</mark>"
                }
            ],
            "text_match": 33448960
        },
        // + 8 additional items
    ],
    "out_of": 30974320,
    "page": 1,
    "request_params": {
        "collection_name": "catalog",
        "per_page": 10,
        "q": "5758"
    },
    "search_cutoff": false,
    "search_time_ms": 22
}
```

As you can see we have items with `is_oem=true` and `is_oem=false`. But if we try to filter it then we unexpectedly got zero results:
Query params: `q=5758&query_by=number&num_typos=0&per_page=10&include_fields=id,number,is_oem&exhaustive_search=true&filter_by=is_oem:true`
```json
{
    "facet_counts": [],
    "found": 0,
    "hits": [],
    "out_of": 30974320,
    "page": 1,
    "request_params": {
        "collection_name": "catalog",
        "per_page": 10,
        "q": "5758"
    },
    "search_cutoff": true,
    "search_time_ms": 18390
}
```

This problem caused also with filters which have other type (like `int32`). But all works fine if we filter by set (like `int32[]`).
Also note how increased time of response: from 22ms to 18.4sec. This is next problem.

### Case 2: too long response
Query params: `q=233&query_by=number&num_typos=0&filter_by=is_oem:true&exhaustive_search=true`
Response time: 167198ms (2min 47sec)

Query params: `q=233&query_by=number&num_typos=0&exhaustive_search=true`
Response time: 145ms

Also we try to use new parameter `search_cutoff_ms` but it didn't help:
Query params: `q=233&query_by=number&num_typos=0&filter_by=is_oem:true&exhaustive_search=true&search_cutoff_ms=2000`
Response time: 164076ms (2min 44sec)

**Note:** we also receive empty results in these queries, CPU usage can increase up to 30% only for per query.

## Metadata

**Typsense Version**: v0.22.0rcs30
**OS**: Linux Debian 4.19.208-1 x86_64

**Comment by kishorenc** [comment]
@MaxVoronov 

**Case 1**

The search cutoff introduced in v0.22 is kicking in, ending the search early when cutoff time is reached (it won't be exact, just best effort), see this field in the response:

```
 "search_cutoff": true,
```

To avoid this confusion, in `0.22.0.rcs33` we have removed cut-off from being applied to filtering (it already excludes facets). Nevertheless, wildcard `*` search and regular token-based searches are both governed by the default 2000 ms search cutoff period. You have to send a larger cutoff interval like`?search_cutoff_ms=800000` (800 seconds).

**Case 2**

Once you start sending a large search cutoff value, queries should atleast produce results even if they take longer. 

Once you confirm that, we can look into the performance aspect: are you saying that adding `filter_by=is_oem:true` the query ends up taking a much longer time?

**Comment by MaxVoronov** [comment]
Hi @kishorenc,
I have sent a dataset for debugging to your email.

**Comment by maxvoronov** [comment]
Hi @kishorenc,
I have checked v0.22.0rcs37 and all works great. Thank you!
