### ISSUE TITLE
Case sensitive when searching in Cyrillic

### ISSUE THREAD

**Issue by ingvarr6** [typesense/typesense#438]
## Description

The search for Cyrillic is case sensitive, but using the Latin I can search in any case.

## Steps to reproduce
Create collection
```
curl -sv -k "http://localhost:8108/collections" -X POST -H "Content-Type: application/json" \
      -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{
        "name": "test", "num_memory_shards": 4,
        "fields": [
          {"name": "title", "type": "string" }
         ]}'
```
Add two records
```
curl -sv 'http://localhost:8108/collections/test/documents' -X POST \
       -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
       -d '{"title":"Test Тест"}'
curl -sv 'http://localhost:8108/collections/test/documents' -X POST \
       -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
       -d '{"title":"TEST ТЕСТ"}'
```

## Expected Behavior

Trying to search a `тест` should get two records
`curl -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" "http://localhost:8108/collections/test/documents/search?q=тест&query_by=title&num_typos=0"`

## Actual Behavior

Found 0 records

```
{
    "facet_counts": [],
    "found": 0,
    "hits": [],
    "out_of": 2,
    "page": 1,
    "request_params": {
        "collection_name": "test",
        "per_page": 10,
        "q": "тест"
    },
    "search_time_ms": 2
}
```

## Metadata

**Typsense Version**: 0.21.0

**OS**: MacOS Big Sur 11.4

**Comment by kishorenc** [comment]
👋 Thank you for creating this issue. This indeed seems to be a problem. I will look into what's happening and get back to you.

**Comment by kishorenc** [comment]
@ingvarr6 I figured out what's going wrong here and working on a fix: will share a build in a couple of days for testing.

**Comment by kishorenc** [comment]
@ingvarr6 I've a build for you to test. Do you use Docker?

**Comment by dannylin108** [comment]
I have the same issue and willing to test it, preferably in Docker configuration :)

**Comment by kishorenc** [comment]
@dannylin108 Please test against this Docker build:

`typesense/typesense:0.23.0.rc8`

**Comment by kishorenc** [comment]
One thing you do need to do is to define a language locale to the fields so that Typesense can handle that language. For e.g. for greek, use the `el` locale like this:

```
curl -k "http://localhost:8108/collections" -X POST -H "Content-Type: application/json" \
      -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{
        "name": "titles", 
        "fields": [
          {"name": "title", "type": "string", "locale": "el" },
          {"name": "points", "type": "int32" }
        ]
      }' 
```

You can also use `sr` locale for Serbian, `ru` for Russian etc.

**Comment by dannylin108** [comment]
> @dannylin108 Please test against this Docker build:
> 
> `typesense/typesense:0.23.0.rc8`

Case insensitive search seems working well (added locale for queried fields).

But there is strange behavior with mixed up matched tokens and highlighting as well: the document which was found is correct, but matched tokens are some random words or punctuation signs around the word was looked for.

Is this issue already known by the team or should I report?

**Comment by kishorenc** [comment]
Can you please add a sample document and query that showcases this issue? We will fix it.

**Comment by ingvarr6** [comment]
@kishorenc thanks, looks great.

**Comment by dannylin108** [comment]
> Can you please add a sample document and query that showcases this issue? We will fix it.

OK, sent you an email :nerd_face:

**Comment by panos-stavrianos** [comment]
> @dannylin108 Please test against this Docker build:
> 
> `typesense/typesense:0.23.0.rc8`

It's not working without the locale specified.
Is it possible to specify multiple locales?

**Comment by kishorenc** [comment]
Locales need to be specified to enable language specific features for Cyrillic.

**Comment by igoralentyev** [comment]
Still the same behavior with newest version and not possible to provide multiple locales (I have multiple languages in my project). So, any solution?

**Comment by kishorenc** [comment]
> Still the same behavior with newest version

Please provide a reproducible example like given earlier in this issue (with collection schema, sample documents and query).

**Comment by igoralentyev** [comment]
You could just try this queries and see result

https://hirify.me/?search=%D0%9C%D0%B0%D1%80%D0%BA%D0%B5%D1%82%D0%BE%D0%BB%D0%BE%D0%B3

https://hirify.me/?search=%D0%BC%D0%B0%D1%80%D0%BA%D0%B5%D1%82%D0%BE%D0%BB%D0%BE%D0%B3

and english versions of this

https://hirify.me/?search=marketer

https://hirify.me/?search=Marketer

as you can see, in english results are the same. In russian - not the same.

If i provide locale - ru it will disable indexing at all, cause i have 80% of english text, so it is defenitely not ru locale.

Schema - 

`'collection-schema' => [
                    'fields' => [
                        [
                            'name' => 'id',
                            'type' => 'string',
                        ],
                        [
                            'name' => 'created_at',
                            'type' => 'int32',
                            'sort' => true,
                        ],
                        [
                            'name' => 'updated_at',
                            'type' => 'int32',
                            'sort' => true,
                        ],
                        [
                            'name' => 'tags',
                            'type' => 'string[]',
                            'optional' => true,
                        ],
                        [
                            'name' => 'title',
                            'type' => 'string',
                            'optional' => true,
                            'sort' => true,
                        ],
                        [
                            'name' => 'text',
                            'type' => 'string',
                        ],
                        [
                            'name' => 'original_text',
                            'type' => 'string',
                        ],
                        [
                            'name' => 'contacts',
                            'type' => 'object[]',
                            'optional' => true,
                        ],
                        [
                            'name' => 'company_title',
                            'type' => 'string',
                            'optional' => true,
                        ],
                        [
                            'name' => 'work_format',
                            'type' => 'string',
                            'optional' => true,
                        ],
                        [
                            'name' => 'work_type',
                            'type' => 'string',
                            'optional' => true,
                        ],
                        [
                            'name' => 'region',
                            'type' => 'string',
                            'optional' => true,
                        ],
                        [
                            'name' => 'english_level',
                            'type' => 'string',
                            'optional' => true,
                        ],
                        [
                            'name' => 'grade',
                            'type' => 'string[]',
                            'optional' => true,
                        ],
                        [
                            'name' => 'salary',
                            'type' => 'object',
                            'optional' => true,
                        ],
                        [
                            'name' => 'specialization',
                            'type' => 'string',
                            'optional' => true,
                        ],
                        [
                            'name' => 'relocation',
                            'type' => 'string',
                            'optional' => true,
                        ],
                        [
                            'name' => 'employee_type',
                            'type' => 'string',
                            'optional' => true,
                        ],
                        [
                            'name' => 'verified',
                            'type' => 'bool',
                            'optional' => true,
                        ],
                        // [
                        //     'name' => 'source',
                        //     'type' => 'string',
                        //     'optional' => true,
                        //     'sort' => true,
                        // ],
                    ],
                    'default_sorting_field' => 'created_at',
                    'enable_nested_fields' => true,
                ],
                'search-parameters' => [
                    'query_by' => 'title, text, tags, company_title, contacts, specialization, region, english_level, grade, salary, relocation, employee_type, verified, source',
                ],`

query is super simple 

`$searchParameters = [
                    'q'         => $this->search,
                    'query_by'  => $fieldsStr,
                    'query_by_weights' => $weights,
                    'text_match_type' => 'max_weight',
                    'prefix' => $this->strictSearch ? false : true, // меньше но релевантне
                    // 'prefix' => true,
                    'sort_by'   => '_eval(verified:true):desc,' . $this->sortResult,
                    // 'sort_by'   => '_text_match:desc, created_at:desc',
                    // 'sort_by'   => 'created_at:desc, _text_match:desc',
                    // 'sort_by'   => '_text_match(buckets:15), created_at:desc',
                    // 'prioritize_num_matching_fields' => false,
                    'per_page' => $this->pages,
                    'drop_tokens_threshold' => 5,
                    'drop_tokens_mode' => 'right_to_left',
                    'prioritize_exact_match' => true,
                    'page' => $this->page ?? 1,
                    'split_join_tokens' => 'always',
                    'prioritize_num_matching_fields' => true,
                ];`
                
for case i described used only 'q' parameter 

using laravel with scout and latest typesense (updated today)

**Comment by dpetrov** [comment]
I believe that is still an issue. Please see below:

`{"state":1,"version":"0.24.0"}

```
curl -sv -k "http://localhost:8108/collections" -X POST -H "Content-Type: application/json" \
      -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{
        "name": "test", "num_memory_shards": 4,
        "fields": [
          {"name": "title", "type": "string", "locale": "bg" }
         ]}'

curl -sv 'http://localhost:8108/collections/test/documents' -X POST \
       -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
       -d '{"title":"Test Тест"}'
curl -sv 'http://localhost:8108/collections/test/documents' -X POST \
       -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
       -d '{"title":"TEST ТЕСТ"}'
```

Querying the data:

```
$ curl --silent -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" "http://localhost:8108/collections/test/documents/search?q=&query_by=title&num_typos=0" | jq .
{
  "facet_counts": [],
  "found": 2,
  "hits": [
    {
      "document": {
        "id": "1",
        "title": "TEST ТЕСТ"
      },
      "highlight": {
        "title": "TEST ТЕСТ"
      },
      "highlights": [],
      "text_match": 100,
      "text_match_info": {
        "best_field_score": "0",
        "best_field_weight": 12,
        "fields_matched": 4,
        "score": "100",
        "tokens_matched": 0
      }
    },
    {
      "document": {
        "id": "0",
        "title": "Test Тест"
      },
      "highlight": {
        "title": "Test Тест"
      },
      "highlights": [],
      "text_match": 100,
      "text_match_info": {
        "best_field_score": "0",
        "best_field_weight": 12,
        "fields_matched": 4,
        "score": "100",
        "tokens_matched": 0
      }
    }
  ],
  "out_of": 2,
  "page": 1,
  "request_params": {
    "collection_name": "test",
    "per_page": 10,
    "q": ""
  },
  "search_cutoff": false,
  "search_time_ms": 0
}
```

Searching with **_q=тест_**


```
$ curl --silent -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" "http://localhost:8108/collections/test/documents/search?q=тест&query_by=title&num_ty
{
  "facet_counts": [],
  "found": 0,
  "hits": [],
  "out_of": 2,
  "page": 1,
  "request_params": {
    "collection_name": "test",
    "per_page": 10,
    "q": "тест"
  },
  "search_cutoff": false,
  "search_time_ms": 0
}
```

**Comment by igoralentyev** [comment]
Yep, still an issue and looks like devs doesnt care.

**Comment by jasonbosco** [comment]
Saying devs don't care is not helpful. 

It's always a matter of prioritization. We have to balance our available bandwidth among multiple parallel things, and so we have to prioritize based on the criteria outlined [here](https://github.com/typesense/typesense/issues/731). 

Also, logistically, it's hard to keep a track of closed issues when prioritizing new work. Please open a new issue, with a reproducible snippet that replicates the issue against the latest RC build (which as of this writing is v28.0.rc35) and we can then prioritize it based on community interest.

**Comment by igoralentyev** [comment]
> Saying devs don't care is not helpful.
> 
> It's always a matter of prioritization. We have to balance our available bandwidth among multiple parallel things, and so we have to prioritize based on the criteria outlined [here](https://github.com/typesense/typesense/issues/731).
> 
> Also, logistically, it's hard to keep a track of closed issues when prioritizing new work. Please open a new issue, with a reproducible snippet that replicates the issue against the latest RC build (which as of this writing is v28.0.rc35) and we can then prioritize it based on community interest.

This issue has been open since 2021. We've all provided code snippets and detailed explanations, but it doesn't matter because the issue is with the server itself, not the client code—snippets won't change that. All you need to do is fix the handling of Cyrillic encoding or add support for specifying multiple locales.

**Comment by kishorenc** [comment]
@igoralentyev 

The original issue was about case sensitivity of the Cyrillic text. As I have mentioned earlier on this thread, that issue has been fixed and it **requires** a locale field. I tried the original example again and it works correctly with a locale field:

```
# Create collection
curl -sv -k "http://localhost:8108/collections" -X POST -H "Content-Type: application/json" \
      -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{
        "name": "test", "num_memory_shards": 4,
        "fields": [
          {"name": "title", "type": "string", "locale": "bg" }
         ]}'

# Add two records
curl -sv 'http://localhost:8108/collections/test/documents' -X POST \
       -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
       -d '{"title":"Test Тест"}'
curl -sv 'http://localhost:8108/collections/test/documents' -X POST \
       -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
       -d '{"title":"TEST ТЕСТ"}'

# Search `q=тест` produces 2 hits
curl -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" "http://localhost:8108/collections/test/documents/search?q=тест&query_by=title&num_typos=0"
```

@dpetrov is using `{"state":1,"version":"0.24.0"}` which is several versions old and does not have that fix. Latest stable version is 27.1.

Your issue is completely different because you are not providing a locale and expecting to search on two languages:

> If i provide locale - ru it will disable indexing at all, cause i have 80% of english text, so it is defenitely not ru locale.

This needs a new issue. We might not even be able to support two languages without locales, but you have to first give us a fully reproducible curl example as given above, which you have not done.

**Comment by igoralentyev** [comment]
@kishorenc Got it, thanks!

In the meantime, I managed to find a super trivial but working workaround.

I just store lowercased data and lowercase the search query :)
