### ISSUE TITLE
Different items count in search query and aggregations

### ISSUE THREAD

**Issue by maxvoronov** [typesense/typesense#444]
## Description
We spotted different items count in list and aggregations when we use search query. When we use regular filters then problems not happened. 

## Steps to reproduce

Search query: `q=123&query_by=number&filter_by=car_makers:[91]%26%26is_oem:true&exhaustive_search=true`
```
{
    "facet_counts": [],
    "found": 24,
    "hits": [...],
}
```

Aggregation query: `q=123&query_by=number&num_typos=0&per_page=0&facet_by=car_makers&max_facet_values=10000&exhaustive_search=true&filter_by=is_oem:true`
```
{
    "facet_counts": [
        {
            "counts": [
                {
                    "count": 10,
                    "highlighted": "91",
                    "value": "91"
                },
                // ...
            ],
            "field_name": "car_makers",
            "stats": {
                "avg": 353.494923857868,
                "max": 11900.0,
                "min": 0.0,
                "sum": 278554.0,
                "total_values": 26
            }
        }
    ],
    "found": 11154,
    "hits": [],
}
```

## Expected Behavior

Expected equal count of items in list and aggregation - 24 items.

## Actual Behavior

We found 24 items in list and 10 items in aggregations.

## Metadata

**Typsense Version**: v0.22.0rcs37
**OS**: Linux Debian 4.19.208-1 x86_64

**Comment by kishorenc** [comment]
@maxvoronov 

I think what's happening here is this: even under exhaustive search mode, Typesense restricts prefix candidates to first 10K tokens to ensure that people don't accidentally blow things up :) Here, there are probably greater than 10K numbers that start with `123`, so _which_ of the 10K numbers that are returned **depend on the filter condition used.** 

When you do `filter_by=is_oem:true` the first 10K numbers that begin with `123` are returned and the faceting count is done on those corresponding records, while when you add the additional filter `filter_by=car_makers:[91] && is_oem:true`, a different subset of the 10K numbers could be returned, so the aggregation on those set of records could be different.

The other thing to note here is that one query uses `num_typos=0` and the other does not, so once again that can influence the aggregation counts.

**Comment by maxvoronov** [comment]
It looks like you're right. I have modified search query: `q=12345` + only filter `is_oem:true`. And list and aggregations items are equal (`"found": 535`). 

Can we tune custom value of prefix candidates using settings or query params?

**Comment by kishorenc** [comment]
Not at the moment, but we can add a parameter for increasing that threshold. I can provide a build next week once I wrap up some ongoing tasks.

**Comment by maxvoronov** [comment]
Hi @kishorenc,
Any updates?

**Comment by kishorenc** [comment]
@maxvoronov Sorry, we had to pick up some additional tasks for the 0.22 release and I forgot to circle back to this. I will provide an update by next week.

**Comment by kishorenc** [comment]
@maxvoronov I've added a `?max_candidates=X` flag in `typesense/typesense:0.23.0.rc19` Docker build. Please check the build in your staging environment first to see if it helps.
