### ISSUE TITLE
Hits are empty, but found 328 documents

### ISSUE THREAD

**Issue by WatanabeThiago** [typesense/typesense#445]
## Description

Hits are empty

## Steps to reproduce

1. Download Postman;
2. TypeSense Postman Collection;

My client:
![image](https://user-images.githubusercontent.com/50850299/143307959-bef19e4d-7ac8-4713-80e7-3ae4cbca5e76.png)

My collection:
![image](https://user-images.githubusercontent.com/50850299/143308124-f5f399d3-c19c-4855-8b61-acbf7c4e23b8.png)

Try search:
![image](https://user-images.githubusercontent.com/50850299/143307829-46a1c86b-c496-4bbd-b088-62850da160c2.png)

## Expected Behavior

Hits not empty

## Actual Behavior

hits empty

## Metadata

**Typsense Version**:
0.21

**OS**:
Ubuntu 20.04

**Comment by WatanabeThiago** [comment]
My error, the cause is: I have trying set "id" how to int

**Comment by kishorenc** [comment]
In 0.22 (upcoming release), we just ignore the `id` field if it is present in the schema since it's a special field. `id` must be a string.
