### ISSUE TITLE
[QUESTION] Multiple collections and scoped api key 

### ISSUE THREAD

**Issue by eliott-loreal** [typesense/typesense#448]
## Description
I'm using a scoped api key with a filter_by clause.
The scoped key is generated from a search-only key that can access multiple collections.
I need to filter on a field that exists only in one of these collections.
When I search in the collection in question, no problem.
When I search in any other collection, I get the following error because the field does not exist:
``` json
{
    "message": "Could not find a filter field named `my_field` in the schema."
}
```
Is there a way to specify that the filter should only apply to the desired collection ?
Or the only solution is to have multiple keys (preventing a multi-search query on different collections) ?

Thank you :)
## Metadata

**Typsense Version**: 0.21.0

**OS**: Mac OS / Ubuntu

**Comment by kishorenc** [comment]
@eliott-loreal

It's not possible to use a different API key for each collection in a multi_search query, because authentication happens at the very beginning. So you have to indeed use 2 separate API keys and issue separate requests.

**Comment by jasonbosco** [comment]
This is now possible to do within a single multi search request. More information here: https://github.com/typesense/typesense/issues/284#issuecomment-1067208921
