### ISSUE TITLE
How to implement autocomplete using react-instantsearch?

### ISSUE THREAD

**Issue by HananoshikaYomaru** [typesense/typesense#449]
So far I have enjoyed using Typesense to create my search UI. One thing I don't know how to do is to make a autocomplete search bar using react-instantsearch and Typesense.

I want to achieve something like this: https://react-instantsearch.netlify.app/storybook/?path=/story/index--autocomplete 

I have 7 collections in typesense and I want the autocomplete search bar search on some specific collections. The results on different collections should be separated with a header, just like the example.

Can anyone explain a little bit on how I can achieve this?

**Comment by jasonbosco** [comment]
@HananoshikaYomaru Here's a react-instantsearch guide on how to build a multi index search like the one in your link: https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/multi-index-search/react/#synchronize-two-instantsearch-indices

To make it work with Typesense, you'd need to include the typesense instant search adapter like this: https://github.com/typesense/typesense-instantsearch-adapter#with-react-instantsearch

**Comment by N-pharmarack** [comment]
@HananoshikaYomaru Were you able to implement autocomplete in react-instantsearch with typesense, 
I have tried it and it gives me error like ->  Error: 400 - Error with filter field `objectID`: Numerical field has an invalid comparator.

@jasonbosco Can you please let me know how to resolve this error.

**Comment by jasonbosco** [comment]
@N-pharmarack Could you open a new issue for this, along with your instantsearch adapter configuration, and the widget code you're using?
