### ISSUE TITLE
typesense-server.service: Main process exited, code=killed, status=9/KILL

### ISSUE THREAD

**Issue by HuynhVuong87** [typesense/typesense#453]
please help me trace this

![image](https://user-images.githubusercontent.com/37244262/144912293-ecbeccf3-7d37-4e43-9ad0-71827af36d0c.png)

**Comment by HuynhVuong87** [comment]
i have log file 55Mb, could you give me your email, i will send it to u

**Comment by jasonbosco** [comment]
@HuynhVuong87 This usually happens when RAM is exhausted and the OS ends up killing the Typesense process. 

May I know how much RAM this server has?

**Comment by HuynhVuong87** [comment]
my server has only 1 Gb Ram
![image](https://user-images.githubusercontent.com/37244262/144946444-720f0ce0-a386-4657-9f62-50e5d8ecb1a1.png)
i also sent you log file
i think my server end up killing Typesense process because recently i am developing some feature on my app, but i don't know what action index or search or something else, i am trying to trace the reason why

**Comment by jasonbosco** [comment]
Looking through the logs you emailed, I don't see any other crashes - the process seems to be running fine up to the point when it's abruptly killed and restarted. 

Could you type `sudo journalctl` and see if there's anything related to typesense that's logged there? Out of Memory (OOM) issues are usually logged by the OS there. 

Also, do you have a historical trend of memory usage that you can look at see how much free memory there is over a period of time? That will also help confirm if this is an OOM issue.

**Comment by HuynhVuong87** [comment]
i have just send you root usr pass of server
could u please help me investigate this issue, i have no more experience with server command

**Comment by jasonbosco** [comment]
@HuynhVuong87 This is indeed an out of memory issue. Here are some relevant log lines:

```
Dec 08 14:30:01 ShipXanhSearch kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/typesense-server.service,task=typesense-serve,pid=598,uid=0
Dec 08 14:30:01 ShipXanhSearch kernel: Out of memory: Killed process 598 (typesense-serve) total-vm:1399776kB, anon-rss:729284kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:1876kB oom_score_adj:0
Dec 08 14:30:01 ShipXanhSearch kernel: oom_reaper: reaped process 598 (typesense-serve), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
Dec 08 14:30:01 ShipXanhSearch systemd[1]: typesense-server.service: Main process exited, code=killed, status=9/KILL
Dec 08 14:30:01 ShipXanhSearch systemd[1]: typesense-server.service: Failed with result 'signal'.
Dec 08 14:30:01 ShipXanhSearch systemd[1]: typesense-server.service: Scheduled restart job, restart counter is at 1.
Dec 08 14:30:01 ShipXanhSearch systemd[1]: Stopped Typesense Server.
```

You want to increase the amount of RAM the server has, so it can hold all the data you're indexing. Here's more information on [how to choose RAM](https://typesense.org/docs/guide/system-requirements.html#choosing-ram).

**Comment by jasonbosco** [comment]
@HuynhVuong87 This is indeed an out of memory issue. Here are some relevant log lines:

```
Dec 08 14:30:01 *** kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/typesense-server.service,task=typesense-serve,pid=598,uid=0
Dec 08 14:30:01 *** kernel: Out of memory: Killed process 598 (typesense-serve) total-vm:1399776kB, anon-rss:729284kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:1876kB oom_score_adj:0
Dec 08 14:30:01 *** kernel: oom_reaper: reaped process 598 (typesense-serve), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
Dec 08 14:30:01 *** systemd[1]: typesense-server.service: Main process exited, code=killed, status=9/KILL
Dec 08 14:30:01 *** systemd[1]: typesense-server.service: Failed with result 'signal'.
Dec 08 14:30:01 *** systemd[1]: typesense-server.service: Scheduled restart job, restart counter is at 1.
Dec 08 14:30:01 *** systemd[1]: Stopped Typesense Server.
```

You want to increase the amount of RAM the server has, so it can hold all the data you're indexing. Here's more information on [how to choose RAM](https://typesense.org/docs/guide/system-requirements.html#choosing-ram).
