### ISSUE TITLE
Filter_by returns 'And' counts but behaves as 'Or'

### ISSUE THREAD

**Issue by Mantra-Media** [typesense/typesense#454]
## Description

Assuming 3 documents:

```
1: categories: ['a','b','c']
2: categories: ['a','b']
3: categories: ['b','d']
```

The counts without a filter_by condition returns:

```
a: 2
b: 3
c: 2
```

The counts with filter_by eg categories:=['a']:
```
a: 2
b: 2
c: 1
```

Now adding ` b` to the existing condition I would expect that I get `2` documents back with the`filter_by condition ['a','b']` but this is not the case as `all documents matching b` and not just documents matching a **and** b are selected:
```
a: 2
b: 3
...
```

It seems like filter_by within the same field seems to behave like an `or` filter if I am correct?

This is very confusing for a consistent UI/UX experience and the count for the facet pointless as it is **never** possible to get the expected number of documents (`2` and not `3`) when adding the condition to the filter_by?

**Comment by kishorenc** [comment]
👋 @Mantra-Media 

The `['a','b']` syntax is meant to be an OR and not an AND so the behavior is correct. Have you tried doing:

`categories: a && categories: b`?

This should return 2 documents.

**Comment by Mantra-Media** [comment]
This works! 

This is not obvious from the docs, there it is stated:

```You can also filter using multiple values and use the backtick character to denote a string literal: category:= [`Running Shoes, Men`, Sneaker]```

But this is then only the `OR` way of doing things and misses the `AND` part.

Thank you so much for the clarification

**Comment by Mantra-Media** [comment]
Ok, it somehow works but the aggregation counts are not fully correct.

We have a big dataset and it might be related to https://github.com/typesense/typesense/issues/444
