### ISSUE TITLE
Token is not recognizable if it has a character in symbol_to_index array

### ISSUE THREAD

**Issue by khaitruong922** [typesense/typesense#455]
## Description

I want to search the term "c++" with the new version of typesense using symbols_to_index field in schema. However, when I include "+" in the symbols_to_index array, the term with "+" cannot be found in search result. Same with "#" for "C#". When I don't use the symbols_to_index when creating schema, all the results are returned but not in order. 

FYI, I am using typesense-js library.

symbols_to_index: ["@", "+", "#"],

## Expected Behavior

q = "c++"

return ["c++","c#","c"]

## Actual Behavior

q = "c++"

return ["c"]

## Metadata

**Typesense Version**: 0.22.0

**OS**: Windows

**Comment by jasonbosco** [comment]
@khaitruong922 Could you post a set of curl commands that creates the collection, adds minimal documents and does a query to show the issue?

**Comment by khaitruong922** [comment]
There you are. Hope you can figure out the issue.

**1. Create colllection**
curl --location --request POST 'http://localhost:8108/collections' \
--header 'x-typesense-api-key: sup3rs3cr3tapik3y' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "student",
    "fields":[{
      "name": "skills",
      "type": "string[]"
    }],
    "symbols_to_index":["+","#"]
}'

**2. Insert data**

curl --location --request POST 'http://localhost:8108/collections/student/documents' \
--header 'x-typesense-api-key: sup3rs3cr3tapik3y' \
--header 'Content-Type: application/json' \
--data-raw '{
    "skills":["c"]
}'

curl --location --request POST 'http://localhost:8108/collections/student/documents' \
--header 'x-typesense-api-key: sup3rs3cr3tapik3y' \
--header 'Content-Type: application/json' \
--data-raw '{
    "skills":["c#"]
}'

curl --location --request POST 'http://localhost:8108/collections/student/documents' \
--header 'x-typesense-api-key: sup3rs3cr3tapik3y' \
--header 'Content-Type: application/json' \
--data-raw '{
    "skills":["c++"]
}'

**3. Search**

curl --location --request GET 'http://localhost:8108/collections/student/documents/search?query_by=skills&q=c++' \
--header 'x-typesense-api-key: sup3rs3cr3tapik3y'

**Comment by kishorenc** [comment]
Glad that you figured this out. Typesense indeed treats + in the query string as space since it's a common practice.
