### ISSUE TITLE
Include and exclude while filtering

### ISSUE THREAD

**Issue by tijana-t** [typesense/typesense#457]
## Description

Hi, here is a certain thing I have difficulties accomplishing.

I have the same issue as the one below that is closed. 
#155 
Is there a way to exclude fields that contains some value, while filtering in facet fields? Also, vice versa, is there a way to return fields that include certain values?

## Steps to reproduce
For example, if I have an array of values ['apple, apple pie, peach']
Is there a way to exclude every field that contains an 'apple'?
I tried an exclusion operator: **item: -apple**,  but it does the opposite, and returns the first item.

Thank you.

**Comment by jasonbosco** [comment]
Hi @tijana-t, #155 is only for excluding keywords in queries. For filtering, you can use something like `filter_by: item:!=[apple]`

**Comment by kishorenc** [comment]
Documented via https://github.com/typesense/typesense-website/pull/140
