### ISSUE TITLE
how can index but not save special fields?

### ISSUE THREAD

**Issue by HuynhVuong87** [typesense/typesense#459]
i want to index some nested fields but i don't want to save them
could you please give me a solution
Eg:
{
field1: ...,
field2:...,
....
nested_field1: ["test1", "test2", "test3"],
nested_field2: ["test1", "test2", "test3"],
...
 }

i want to index nested_field1,.. but i don't want to save them on Typesense

**Comment by kishorenc** [comment]
@HuynhVuong87 

Can you elaborate what you mean by:

> but i don't want to save them on Typesense

Do you not want the field to available in the document in the response but you want to search on it?

**Comment by HuynhVuong87** [comment]
yes, correct.
I don't want to save this field in document but i want to search this field
by default Typesense save all field into document that it indexed, but i don't want because it will make some nested fields double saved

**Comment by kishorenc** [comment]
We don't have a way to do this, since the data on disk is compressed, so disk storage is usually not an issue.
