### ISSUE TITLE
can't create collection with id field on version 0.22.0 or 0.22.1

### ISSUE THREAD

**Issue by HuynhVuong87** [typesense/typesense#460]
this error effects to all our new users because we create collections for each user
could you please fix this soon, it worked well on old version 0.21.0

**Comment by kishorenc** [comment]
@HuynhVuong87 

The `id` field is an implicit field, which cannot be treated as a regular field. We ran into several gotchas because of this. So we are not longer allowing it to be part of the field definition. If you wish to have some form of identifier you can still do so under a different field name like `_id`.

**Comment by kishorenc** [comment]
Just to be clear, you _can_ create a collection with the `id` field, but it just gets ignored and is not treated as a regular field:

```
% curl -k "http://localhost:8108/collections" -X POST -H "Content-Type: application/json" \                                                                                                                                               7 ↵
      -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{
        "name": "docs",
        "fields": [ 
          {"name": "id", "type": "string"},
          {"name": "title", "type": "string" },
          {"name": "points", "type": "int32" }
        ],
        "default_sorting_field": "points"
      }'
{"created_at":1639224297,"default_sorting_field":"points","fields":[{"facet":false,"index":true,"name":"title","optional":false,"type":"string"},{"facet":false,"index":true,"name":"points","optional":false,"type":"int32"}],"name":"docs","num_documents":0,"symbols_to_index":[],"token_separators":[]}%
````

**Comment by HuynhVuong87** [comment]
thank you for your explain
please, check this response from search with pinned_hits
{"message": "Could not find a field named `id` in the schema."}
i face with this problem when i update to 0.22.0

https://server29.example.com/collections/PRODUCTS/documents/search?q=lljljljlkjljlkjljljlkjlkjllhlklljljljljljlkjlkjlkjlkjljlkjljkljlljljljlljkjkl&query_by=id&include_fields=id&pinned_hits=test.vn_test_100081944_2588791101:1,test.vn_test2_100081944_2588791101:2,test.vn_test3_100081944_2588791101:3,test.vn_stock_100081944_2588791101:4

**Comment by kishorenc** [comment]
Yes, this won't work on 0.22. There are 2 solutions:

a) reindex the documents with an explicit `_id` field and then query against that. 
b) use a `filter_by=id:xxxx` which should work.

I'm sorry about this change, but people were creating an `id` field with non-string attributes etc. which led to many subtle issue. Please be careful about testing version upgrades on local/staging environment before upgrading production.

**Comment by HuynhVuong87** [comment]
thank you so much, i love Typesense team <3 support 5 stars <3

**Comment by kishorenc** [comment]
Welcome!
