### ISSUE TITLE
Feature Request: Search for parts of combined/prefixed words, f.i. "justice" within "injustice"

### ISSUE THREAD

**Issue by obottek** [typesense/typesense#463]
## Description
We would like to get results where the token is part of an prefixed word in the search field. We search for "justice" and would like to get results with the word "injustice" too.

This happens alot on German language, since they have to concept of combined words. It is somehow weired to not get those results returned at all, not even with a lower score.

## Steps to reproduce
Go to the book store demo database and search for "justice": https://books-search.typesense.org/?b[query]=justice
You will not get any results with the word "injustice" only.

## Expected Behavior
Results with the word "injustice" should be returned, but with a lower score.

## Actual Behavior
You get no results with the word "injustice", if there isn't the separate word "justice" in it too.

## Metadata

**Typsense Version**:
0.22.0
**OS**:

**Comment by kishorenc** [comment]
@obottek Typesense is optimized for prefix search, so it will not be possible for us to match infixes this way, and also if we tried to match `justice` on `injustice` it will cause a lot of false positives in most of the regular use cases. We might add support for brute-force infix/suffix searching in the future as part of https://github.com/typesense/typesense/issues/393 for searching identifiers etc. but it's probably not going to be fast enough for generic search.

**Comment by HuynhVuong87** [comment]
+1 this is important feature in real life, hope Typesense team will do it

**Comment by jasonbosco** [comment]
Closing in favor of #393.
