### ISSUE TITLE
OR clauses in filtering for event dates

### ISSUE THREAD

**Issue by Apeli** [typesense/typesense#469]
## Description

When using Typesense for searching for events, there are multiple date checks that need to happen.

(start_unix & end_unix are unix timestamps for event start dates, as int32, startTime is the unix timestamp of the first date in a Date range, endTime the last date in the range)

In theory: filter_by=(start_unix:<startTime && end_unix:>endTime) || (start_unix:>startTime)

Is this possible?

**Typsense Version**: 0.22.0

**OS**: OSX

**Comment by kishorenc** [comment]
@Apeli Unfortunately, this is not possible yet but is one of the important items on our backlog to tackle in the near future: https://github.com/typesense/typesense/issues/281

**Comment by jasonbosco** [comment]
@Apeli Here's one workaround in the meantime that you might find useful: https://github.com/typesense/typesense/issues/281#issuecomment-948179523
