### ISSUE TITLE
Amazon Elastic Container Service (ECS)

### ISSUE THREAD

**Issue by renehauck** [typesense/typesense#472]
## Description

I would like to use typesense in Amazon Elastic Container Service (ECS), which generally works, but the problem is the high availability. According to the description, typesense requires fixed IPs, which are of course not possible via ECS. Even if it were possible to use local domains instead of IPs, these would also have to be constantly updated somehow. Is there a workaround for this or is something along these lines planned to be implemented? Many thanks for your work!

## Expected Behavior

Possibility to deploy typesense in ECS :-)

## Actual Behavior

typesense Dependence on local IP's

## Metadata

**Typsense Version**:

**OS**:

**Comment by kishorenc** [comment]
@renehauck 

Typesense uses the DNS/IP address as the identifier for the nodes. Without this, we will need some form of discovery service and that will require an external data store which probably introduces additional complexity. 

One way to work around this issue on ECS will be to front the ECS container with network load balancer, as I believe they can be configured to be have static IPs.

But my recommendation is to just run Typesense on 3 stand-alone EC2 instances. It's the simplest form of deployment and is very easy to manage.

**Comment by jthDEV** [comment]
Depending on the amount of data you need to index, you might consider to just ramp up a new container when a certain load is achieved. We have a scenario where a complete re-index requires only 10secs. So we decided to ramp up new containers when we require further capacity. This is not the best choice from architecture point of view, but it works for small indices.

**Comment by renehauck** [comment]
In any case, thank you very much for the help. I would like to create the EC2 approach with Pulumi soon if I have time and can also share it if there is interest. 
Nevertheless, I still have a question. Let's say we have Typesense in production with 50 million data in a cluster with 3 instances. We then realise that 3 instances are no longer enough and add another 2, would the whole cluster have to do a new indexing or just the 2 new instances?

**Comment by kishorenc** [comment]
> We then realise that 3 instances are no longer enough and add another 2

No longer enough in terms of memory or cpu? Each node in the Typesense cluster stores the same data (they are mirror replicas). To upscale the individual nodes, you have rotate them one by one, and each of the node will reload the data back from disk and index into memory on a restart.

**Comment by renehauck** [comment]
ok, thanks, I'll close the issue then :-)
