### ISSUE TITLE
server hangs on startup, no output

### ISSUE THREAD

**Issue by Sembiance** [typesense/typesense#478]
## Description
Attempting to run `typesense-server` bin 0.22.1 on Linux kernel 5.14.7 (Intel(R) Core(TM) i9-7980XE CPU)

Running it and it just hangs, never produces any console output, never listens on a port.

Running `strace typesense-server` yields the attached [strace_log.txt](https://github.com/typesense/typesense/files/7785191/strace_log.txt)

Hanging on `futex(0x42e7c20, FUTEX_WAIT_PRIVATE, 1, NULL`

Running `gdb typesense-server` and yields attached [gdb_log.txt](https://github.com/typesense/typesense/files/7785213/gdb_log.txt)

Hanging on `#0  0x00007ffff7d5a538 in ?? () from /lib64/libc.so.6` and `#1  0x0000000000d21960 in bthread::first_sys_pthread_mutex_lock(pthread_mutex_t*) ()`

With nothing being sent to stdout, stderr, dmesg or /var/log/messages, I'm at a loss of how to troubleshoot further.

On another note, I attempted to compile from source, to try and enable some debug symbols, but gave up after spending an entire morning fighitng the cmake configuration. It wouldn't automatically find any of my system installed libraries in `/usr/lib64` I had to manually specify `-DUnwind_LIBRARY=/usr/lib64/libunwind.so -Dglog_LIBRARY=/usr/lib64/libglog.so -Dgflags_LIBRARY=/usr/lib64/libgflags.so -DLevelDB_LIBRARY=/usr/lib64/libleveldb.so -DProtobuf_LIBRARIES=/usr/lib64/libprotobuf.so -DICU_LIBRARY=/usr/lib64/libicuuc.so -DCURL_LIBRARY=/usr/lib64/libcurl.so -DSNAPPY_LIBRARIES=/usr/lib64/libsnappy.so -DOPENSSL_ROOT_DIR=/usr/lib64` and then it passed the configuration step. Attempting to compile failed though because I don't have `brpc` and `braft` installed.

**Comment by jasonbosco** [comment]
@Sembiance I saw an issue with similar symptoms and we addressed it in an 0.23 RC build. Could you give this build a shot: https://dl.typesense.org/releases/0.23.0.rc5/typesense-server-0.23.0.rc5-linux-amd64.tar.gz

CC: @kishorenc on build issues

**Comment by kishorenc** [comment]
@Sembiance May I know what Linux distro and version you are using? Someone recently reported a similar issue on Slack that turned out to be because of some incompatibilities with the latest glibc version shipping on Ubuntu 21. If you can get me the version of glibc on your machine, I can confirm.

**Comment by Sembiance** [comment]
@jasonbosco 0.23RC5 works great!! Started right up!

@kishorenc I'm running Gentoo linux. `glibc v2.34-r3`

**Comment by kishorenc** [comment]
Glibc 2.34 indeed is a problem  When I shared this rc5 build earlier, it seemed to solve the starting up issue but someone reported that it however stopped after a while. So this problem is probably still going to exist. I'll be looking into a proper solution soon. For the time being, if you face further issues you've to use a distro with older glibc.

**Comment by Sembiance** [comment]
@kishorenc I'll stick with the 0.22.1 docker image for now. Thanks for the update!

**Comment by kishorenc** [comment]
@Sembiance 

I think I've fixed this issue in this build here: 
https://dl.typesense.org/releases/0.23.0.rc11/typesense-server-0.23.0.rc11-linux-amd64.tar.gz

**Comment by Sembiance** [comment]
@kishorenc cool beans. That version also started right up. I'll be sticking with the 0.22.1 docker image for now though for stability reasons. Thanks though, I look forward to when 0.23.0 is fully released :)
