### ISSUE TITLE
understand about latest data in document

### ISSUE THREAD

**Issue by huynv86** [typesense/typesense#479]
If I update multiple documents, they will be in queue to be re-indexing. So how i can get a updated document while waiting for re-indexing this document
for example
http://localhost:8108/collections/companies/documents/124
if this document is get directly from database then it's data is newest it's not depend on this document's still in re-indexing queue, is this right?

**Comment by kishorenc** [comment]
> So how i can get a updated document while waiting for re-indexing this document

Any external data system is always going to have a short lag when compared with your primary database. If a certain part of your application requires immediate update, then you have to only rely on the database.

**Comment by huynv86** [comment]
i mean rocksdb that Typesense is using. I dont use primary database
can i get updated document from this rocksdb while in short lag?

**Comment by kishorenc** [comment]
@huynv86 Typesense updates both in-memory index and the on-disk data at the same time, so if there is a lag indicated, that applies to both the data stored on-disk in RocksDB and the in-memory indices.
