### ISSUE TITLE
Log searches for analytics

### ISSUE THREAD

**Issue by keybits** [typesense/typesense#48]
Is there a way to create a log of searches, chosen result and other metrics like date / tine of search, to help with analysing what people are searching for?

**Comment by kishorenc** [comment]
@keybits There is no way to do that currently. There a couple of work arounds:

1. Have a nginx server in front and parse the logs.
2. Proxy the requests to Typesense with your own web app and get those metrics from the request and response.

**Comment by keybits** [comment]
Thanks for the reply. The suggested workarounds are fine - helps keep Typesense focused on search :-)

**Comment by jasonbosco** [comment]
Search analytics is now supported in v0.25.0 of Typesense: https://typesense.org/docs/0.25.0/api/analytics-query-suggestions.html
