### ISSUE TITLE
seemly, results are not exactly in this case

### ISSUE THREAD

**Issue by huynv86** [typesense/typesense#480]
this results are ok
![image](https://user-images.githubusercontent.com/747614/147951181-7e7c7abe-45bf-48f4-a759-a747b546432c.png)

but with this keyword, the results are not as I expected. even this keyword with meaning is better than before
![image](https://user-images.githubusercontent.com/747614/147950961-4f96cf82-a52a-490c-a3a2-1645baa8fd40.png)

version Typesense 0.21.0
same index, just different keyword

**Comment by kishorenc** [comment]
@huynv86 

Can you please share a sample dataset containing a few records, along with the exact query you are making so I can reproduce the issue and see what's happening here?

**Comment by huynv86** [comment]
> @huynv86
> 
> Can you please share a sample dataset containing a few records, along with the exact query you are making so I can reproduce the issue and see what's happening here?

sure, i sent dataset to your email kishorenc@gmail.com
thank you

**Comment by kishorenc** [comment]
@huynv86 

Can you encode the `&` in the query to `%26`? That should fix the issue you are facing because the raw ampersand is treated as an HTTP get parameter separator so the query gets truncated.

**Comment by huynv86** [comment]
perfect, thank you
