### ISSUE TITLE
[Feature Request]: Client Connection event

### ISSUE THREAD

**Issue by apidev234** [typesense/typesense#481]
## Description

I just launched a typesense cluster on aws ubuntu, Because I'm kinda learning aws i wanted to know that if i had even successfully connected or not? But i doubt if there's any possible way to do that? I tried curl commands but failed
## Steps to reproduce
-Add a event like when the typesense client is ready, that event is fired? client.on('connected').... etc....

## Metadata

**Typsense Version**: latest

**OS**: Ubuntu-20.04

**Comment by jasonbosco** [comment]
@apidev234 You can use the health endpoint to ensure that the connection is successful: https://typesense.org/docs/0.22.1/api/cluster-operations.html#health
