### ISSUE TITLE
how to search by last characters of word

### ISSUE THREAD

**Issue by HuynhVuong87** [typesense/typesense#482]
document have a field with value 220101KDE3V3V6
search with keyword 2201, found 1 document
BUT search V3V6, NOT FOUND
how to search by last characters or character in middle?

**Comment by kishorenc** [comment]
Typesense handles only prefix search. This type of suffix searching is often useful only with model/part numbers like your own example. To handle those, you have to pre-process the model numbers to pre-split them into logical segments and index them. For e.g. you can split `220101KDE3V3V6` into `2201-01-KDE3-V3V6` and index them (be sure to enable `-` as a custom separator as well in the collection schema). You can also have multiple variations of the string in an array, and index that array.

Suffix searching is very memory intensive, so solving the problem using the work around above is far more efficient.

**Comment by kishorenc** [comment]
Closing this in favour of https://github.com/typesense/typesense/issues/393.
