### ISSUE TITLE
Search result edge case

### ISSUE THREAD

**Issue by jadamroth** [typesense/typesense#486]
## Description

This isn't a bug, but a specific edge case that I'm wondering if I missed something in my configuration or if there's something I can do to improve my results.

I have a collection with data linked from Firestore hosted on typesense cloud and am running a nodejs script on my local computer via the javascript library to search for results. Everything works very well except when I search for strings that "look" like a number (i.e. could implicitly casted as integers), but needs to be a string (an example would be a phone number).

Here's some tests I run:
My stored string is "z123" and search "123". Doesn't work 
My stored string is "z123" and search "z123". Works
My stored string is "123z" and search "123". Works

While my use case above might not be easy to understand, I tried some other examples with a phone number that will make more sense.

My stored string is "+1.123.456.7890" and search "123". Doesn't work
My stored string is "1.123.456.7890" and search "123". Doesn't work
My stored string is "456.123.7890" and search "123". Doesn't work
My stored string is "123.456.7890"  and search "123". Works

## Steps to reproduce

See the tests above. Here is my code from nodejs
```node
searchResults = await typesense.collections('my_collection').documents().search({
    q: '123',
    query_by: 'my_field'
})
```

## Expected Behavior

To return results when searching via strings that could be implicitly casted as integers

## Actual Behavior

Return results from the examples above

## Metadata

**Typsense Version**: v0.22.1

**OS**: typesense hosted cloud

**Comment by jadamroth** [comment]
Looks like this is a similar question to #482. A couple questions:
1) what are the options if the data is not uniform as in the example from issue 482? 
2) is there a way to index the first X characters of the field similar to how you can configure in a mysql column?

**Comment by jasonbosco** [comment]
@jadamroth Typesense currently only supports searching for prefixes of words. Searching in the middle of strings is called infix / suffix searching and we have an open issue to track it here: #393. 

> what are the options if the data is not uniform as in the example from issue 482?

If you have any common separators in the strings, for eg `.`, `-`, `+` in the case of your phone numbers use case, you can set those as [`token_separators`](https://typesense.org/docs/0.22.1/api/collections.html#schema-arguments) when creating the collection. So when you index `+1.123.456.7890` it will internally get indexed as `1` `123` `456` `7890` and then when you search for any one of those sub-strings, you'll get a hit.

**Comment by jadamroth** [comment]
Thank you. I will close this issue and monitor issue #393 progress
