### ISSUE TITLE
(filter_by) Filtering for entries with null value in a column 

### ISSUE THREAD

**Issue by rogerho1224** [typesense/typesense#488]
## Description
Is there a way to state in the filter_by param that we only want results that have null / are empty in a specific column?
Is there a way to do a generic non-null? Basically looking for the equivalent of MYSQL's IS NULL and IS NOT NULL.

**Comment by kishorenc** [comment]
@rogerho1224 It's not possible to filter on `null` values, because a missing/null value is simply absent in our inverted index. You can use an application defined identifier like `__NULL__` to denote a null value and then appropriately filter on it to identify missing values.
