### ISSUE TITLE
[Internal Information] How is the data stored?

### ISSUE THREAD

**Issue by alexbowers** [typesense/typesense#49]
This isn't a bug, if it isn't the appropriate place or it, then feel free to close.

I have been interested in how search works for a while now, but haven't found any articles I found particularly approachable from 0 knowledge on the internals.

Would you be able to explain a little about how the data gets stored, and how that benefits the performance of a search?

I tried looking through the code a little bit to see if I could find the binary file formats but from a quick skim I was unable to find it.

Thanks.

**Comment by kishorenc** [comment]
@alexbowers Sorry for the super long delay in getting back to you! 

Typesense stores the `token => documents` [inverted index](https://en.wikipedia.org/wiki/Inverted_index) as an [Adaptive Radix Trie](https://db.in.tum.de/~leis/papers/ART.pdf) in memory. The actual documents are stored on disk using [RocksDB](https://github.com/facebook/rocksdb).
