### ISSUE TITLE
can we use this api in native android

### ISSUE THREAD

**Issue by Naveenkant93** [typesense/typesense#491]
## Metadata

**Typsense Version**:

**OS**:

**Comment by kishorenc** [comment]
Hi @Naveenkant93 We have a Java client here that you can use: https://github.com/typesense/typesense-java

But you can't run Typesense itself inside an android application as an embedded search engine.

**Comment by PaulWoitaschek** [comment]
Is it on the roadmap to get an Android port any time?
I'm developing voice: https://github.com/PaulWoitaschek/Voice
And integrating typesense would just make our search so much better.
