### ISSUE TITLE
Feature request: - sorting w.r.t. relevancy and weight 

### ISSUE THREAD

**Issue by anil-tiwari** [typesense/typesense#492]
## Description

Hi , I am using typesense for search but my use case is little bit differ.
As the typesence priorities to the relevancy and occurrence of the word or character, but i need on more parameter like weight(or uses ) on which i can make a sorting of result.

If possible please let me know if you guys are looking in this feature

**Comment by jasonbosco** [comment]
Hi @anil-tiwari, this is already possible. You can change the sort order to any field, as described here: https://typesense.org/docs/guide/ranking-and-relevance.html#strict-ordering-or-hard-sorting

**Comment by anil-tiwari** [comment]
**Data structure:::**

> Titile  - String
> Category - String
> Popularity - Double

**What I want to achieve :::**

I Want to search on title and category and whatever the results are proposed by the system should sort based on a function e.g. multiply of text match score and popularity.
We have tried the solution provided by you, the results are not up to the mark because it sorts the data 1st on popularity and a text match is used as a tie-breaker

Is there any possibility to calculate another score based on some function that generates scores with text match and popularity both?

**Comment by jasonbosco** [comment]
Typesense doesn’t have a way to specify a function to rank by. But if your end goal is to mix popularity with text relevance, this might be helpful: https://typesense.org/docs/guide/ranking-and-relevance.html#ranking-based-on-relevance-and-popularity

**Comment by johnparn** [comment]
Hi!

Thanks for your hard work with TypeSense!

Being able to tweak the `_text_match` score and to merge the `_text_match` score with the scores of other fields would be nice features. 

At the moment I have tweaked the the score computed by `_text_match` by deduplicating the words that are indexed, as frequency is one of the metrics used to to calculate the score. For my concern that works for now, but it would be smooth to configure a weight in the configuration, like `"_text_match_weights": "1,1,1,3,2"` to tweak the weight of the default metrics _Frequency_, _Edit distance_, _Proximity_, _Ordering of query_by fields_ and _Field weights specified in query_by_weights field_.

And to merge the `_text_match` score with other fields; `"sort_by": "_score_group(popularity, _text_match), title"`.
