### ISSUE TITLE
Use of uWebSockets instead of h2o

### ISSUE THREAD

**Issue by joshxyzhimself** [typesense/typesense#493]
## Description

Hi all, I have noticed that TypeSense [1] uses H2O [2] as their HTTP server.

According to [3]:

> Typesense comes built-in with a high performance HTTP server [2] that is used by likes of Fastly [4] in their edge servers at scale. So Typesense can be directly exposed to incoming public-facing internet traffic, without the need to place it behind another web server like Nginx / Apache or your backend API.

Now according to uWebSockets [5] benchmarks, UWS have better performance than H2O. I'm curious, could TypeSense also benefit from this difference in their performance?

![image](https://user-images.githubusercontent.com/60829711/150113425-c05a52ee-9bc2-4c06-bffb-931ca0185400.png)

- [1] https://typesense.org/
- [2] https://github.com/h2o/h2o
- [3] https://typesense.org/docs/guide/running-in-production.html#production-best-practices
- [4] https://www.fastly.com/
- [5] https://github.com/uNetworking/uWebSockets/tree/master/benchmarks
- [6] https://h2o.examp1e.net/benchmarks.html

**Comment by kishorenc** [comment]
@joshxyzhimself 

I was not aware of `uWebSockets` -- thanks for bringing that to my attention. To be honest, we have not seen the h2o layer to be a bottleneck for real-world performance.  Much of the search latency comes not from the http layer, but from the actual searching, sorting and fetching of results from disk. So it's not likely that we will switch to a new framework on the basis of http performance. 

Nevertheless, I will keep a look out for other features that might motivate us to switch in future (http3 etc.).
