### ISSUE TITLE
Sorting by string fields not working

### ISSUE THREAD

**Issue by Meghabm07** [typesense/typesense#494]
## Description

I have used the docker build [typesense/typesense:0.23.0.rc10](https://github.com/typesense/typesense/issues/117#issuecomment-1000857228) for sorting a string field "playStartTime" from cinema list.

I have explicitly enabled string sorting at a field level. Below is my schema for the cinema list

[Schema Example](https://typesense.free.beeceptor.com/schema)

I have added a query request and response sample in the below link

[Request Sample](https://typesense.free.beeceptor.com/request)
[Response Sample](https://typesense.free.beeceptor.com/response)

playStartTime is not sorting in the response which I'm getting

Is there any mistake from my side?
Can anyone help me to resolve this issue? 

Thanks in advance

## Metadata

**typesense/typesense:0.23.0.rc10**:

**Comment by kishorenc** [comment]
@Meghabm07 

What happens when you don't apply a `group_by`? Does it work without grouping?

**Comment by kishorenc** [comment]
I came across a variation of this group_by in another context and it has been fixed in 0.23 GA release. Feel free to reopen if you can reproduce.
