### ISSUE TITLE
Fetching more than 250 results is it possible?

### ISSUE THREAD

**Issue by dyanakiev** [typesense/typesense#497]
## Description

Hello, is there a way to change the max limit of 250 results per_page?

**Comment by jasonbosco** [comment]
@dyanakiev The max value for `per_page` is fixed for performance reasons and cannot be changed. You can use the `page` parameter to fetch more documents in a paginated fashion: https://typesense.org/docs/0.22.1/api/documents.html#pagination

If you want to fetch all documents matching a filter, you can also use the documents/export endpoint with filter_by: https://typesense.org/docs/0.22.1/api/documents.html#export-documents
