### ISSUE TITLE
What is the difference between found and out_of?

### ISSUE THREAD

**Issue by dyanakiev** [typesense/typesense#498]
Hello,
What is the difference between found and out_of? Currently for my searches they are the same.

**Comment by jasonbosco** [comment]
If you have say 10K documents in total in your collection, and for a given query only 150 of them are matched as results, `out_of` will be 10K and `found` will be 150.

**Comment by dyanakiev** [comment]
Perfect! Thank you for the explanation!

**Comment by saidagit77** [comment]
@jasonbosco/ @kishorenc 

if pass * in query with no filters then **found** and **out_of** two values should be same right? but for me its showing diff values in **out_of** and **found**. what cloud be the reason? , please find the details and help me

**version** : 0.25.1

**CURL Request:**

`curl --location 'http://localhost:8108/multi_search?x-typesense-api-key=1234' \
--header 'Accept: application/json, text/plain, */*' \
--header 'Accept-Language: en-GB,en;q=0.9' \
--header 'Connection: keep-alive' \
--header 'Content-Type: text/plain' \
--header 'DNT: 1' \
--header 'Origin: http://192.168.141.236' \
--header 'Referer: http://192.168.141.236/' \
--header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36' \
--data '{"searches":[{"exhaustive_search":true,"query_by":"contentId,name,dataType,languages,casting,genre,networkName,networkId,description","highlight_full_fields":"contentId,name,dataType,languages,casting,genre,networkName,networkId,description","collection":"contents","q":"*","facet_by":"dataType,genre,languages,networkId,networkName","max_facet_values":10,"page":1,"per_page":12}]}'`

**Response:**

<img width="833" height="404" alt="Image" src="https://github.com/user-attachments/assets/6555aeca-e58a-4778-ad28-3591a75c0159" />

**Comment by kishorenc** [comment]
0.25.1.is a very old version of Typesense. Please try on v29.

**Comment by saidagit77** [comment]
its working fine in 24 , 28 and 29 versions . this issue getting 0.25.1(Production env).

**Comment by kishorenc** [comment]
It could have been a bug which we fixed. Please upgrade to a more recent version.
