### ISSUE TITLE
Paging max

### ISSUE THREAD

**Issue by scottf-tvw** [typesense/typesense#50]
## Description

As noted in the documentation the limit for results is 500. Seems this is not a limit per query but overall? 

## Steps to reproduce

query page number beyond total of 500 initial, while total document > 500

## Expected Behavior

One would assume that if there were 1,500 results found for example and you ask for page 2 with a per_page of 500, that it would return the next 500, leaving 500 more to return on page 3. 

## Actual Behavior

Asking for following page of a results set when page count * per_page would exceed 500, while the total results found > 500 returns:
`"message": "Only the first 500 results are available."`

## Notes
Our documents are amalgams of data from transcripts that belong to single events. we are merging the search results for all of the timecodes for text found in the document search. there are millions of documents in the collection(s). so paging results as one would expect them to behave, does not. Is this paging behavior a bug?? if this is the expected logic then this is a major roadblock and not something one would expect from paging functionality. It would be extremely limiting to not be able to access records in a range beyond the first 500. 

**Typsense Version**:
0.9.2
**OS**:
ubuntu server 18 in clusters

**Comment by kishorenc** [comment]
>  It would be extremely limiting to not be able to access records in a range beyond the first 500.

@scottf-tvw This was a conscious design decision. Typesense offers great flexibility in how you sort the data in query-time without any pre-defined sort orders during indexing. This flexibility comes at a cost: sorting millions of documents in real-time will take a long time, so we've to restrict the total "hits" returned to 500 documents.

**Comment by scottf-tvw** [comment]
OK I understand the nuance there, For my purposes I made the modifications myself.
