### ISSUE TITLE
GeoSearch not returning values south of the equator.

### ISSUE THREAD

**Issue by paulsUsername** [typesense/typesense#502]
The API is not returning polygon values when the polygon is south of the equator. See below screenshot visualising the locations. My database contains values within this area.

To replicate. Create a DB with values in South America. The run a search like below:

http://localhost:8081/collections/my-collection/documents/search?q=*&query_by=name&per_page=250&filter_by=location:(13.3163, -82.3585, -29.134, -82.3585, -29.134, -59.8528, 13.3163, -59.8528)

## Expected Behavior

Expecting it to return values south of the equator.

## Actual Behavior

Does not return these values and ignores the location element of the request.

<img width="588" alt="Screenshot 2022-01-23 at 16 55 04" src="https://user-images.githubusercontent.com/32492218/150689308-ca8aacb4-23af-4508-a942-cafe7ce6fb83.png">

**Comment by paulsUsername** [comment]
Whats stranger is it is sometimes returning values south of the equator, for example the below request works and returns values:

http://localhost:8081/collections/my-collection/documents/search?q=*&query_by=name&per_page=250&filter_by=location:(28.2559, -82.3877, -27.8496, -82.3877, -27.8496, -52.4115, 28.2559, -52.4115)

**Comment by paulsUsername** [comment]
The only way I have discovered to solve the issue is to use center + radius instead of a polygon.

**Comment by kishorenc** [comment]
@paulsUsername Thank you for reporting this issue. I will look into this and get back to you.

**Comment by paulsUsername** [comment]
We are hoping to integrate Typesense into production soon but this is currently a blocker.

**Comment by kishorenc** [comment]
@paulsUsername I already have a potential fix for this issue. Can I share a Docker build with you using which you can test? Or do you prefer a Linux binary.

**Comment by paulsUsername** [comment]
Yeah docker would be perfect, but we are working on Typsesnse cloud so wont be of much use till we can get something deployed on there.

**Comment by kishorenc** [comment]
@paulsUsername Please check against this Docker build: `typesense/typesense:0.23.0.rc23`

If that works, we can upgrade your Cloud cluster to use this build. For that, please email us with the cluster ID.

**Comment by kishorenc** [comment]
@paulsUsername Did you get a chance to try that build? Any feedback?

**Comment by kishorenc** [comment]
Patched in `v0.22.2`.
