### ISSUE TITLE
Filter exclusively on ID by array of strings

### ISSUE THREAD

**Issue by ewanmay** [typesense/typesense#503]
## Description

When looking to filter out a specific group of IDs from the users in my database, I was unable to retrieve any results from the database.

Essentially, I want to query the database for all users except the ones with the IDs in an array like `[id1, id2, id3, id4]`

## Steps to reproduce

Create any sort of schema with an ID field present
Change the filter_by field to contain a string like `id:!=[id1, id2]` or `id:![id1, id2]` or `id:=[-id1, -id2]`

## Expected Behavior

Returns an array of users except for the ones included in the ID string array. 

## Actual Behavior

Returns an empty array, or throws "Server said: Not equals filtering is not supported on the `id` field."

## Metadata

**Typesense Version**: V0.22.1

**Typesense JS SDK Version**: V1.0.2

**OS**: Linux

**Comment by garth** [comment]
Having had this issues a few times, I usually create an additional `_id` field with the same id value and filter against that.

**Comment by tonprince** [comment]
Does the error message means that we cannot query by the id field?

**Comment by jasonbosco** [comment]
@tonprince That's correct - not at the moment. You would have to use this workaround: https://github.com/typesense/typesense/issues/503#issuecomment-1229272478

**Comment by kishorenc** [comment]
On 0.25 RC, Typesense allows filtering on the `id` field but you can't yet do `:!=` filtering. We will be fixing that as well, soon.

**Comment by bschnelle** [comment]
@kishorenc any timeline on when `!=` will be available on the `id` field?

**Comment by kishorenc** [comment]
This is fixed on the 0.26 development branch.

**Comment by jasonbosco** [comment]
Available in 0.26.0.rc54

**Comment by jasonbosco** [comment]
Released in v26
