### ISSUE TITLE
Case sensitivity (of facet fields, maybe others?)

### ISSUE THREAD

**Issue by zehawki** [typesense/typesense#504]
## Description

Say a field is a facet field, and then the same values (case insensitive) are sent for indexing in this field eg:

- producta
- ProductA
- PRODUCTA

These are being considered as different values in one case and the same value in another case as follows:

1. Different values - Getting a list of facet field values will list this value multiple times in the API response, eg producta count = 8, ProductA = 2
2. Same value - But then filter by either value will return all results with count = 10

Here's a live example:

1. q=*&per_page=0&facet_by=tags&max_facet_values=100 gives:

![image](https://user-images.githubusercontent.com/8095144/150966838-aed64dd4-6b49-4121-8e71-f8b76b506e7c.png)

2.filter_by=%26%26tags:COVID19Manipur&page=1

![image](https://user-images.githubusercontent.com/8095144/150968890-49423bf2-3914-4b5f-ae95-5dbe5bca6930.png)

## Expected Behavior

1. The two APIs responses should be in sync - either be case sensitive or case insensitive uniformly
2. Should preferable be case insensitive in both cases. Getting a list of facet field values should give a merged count and return only one of the values. Of course in that case, how will TypeSense know which value to send back?

## Metadata

**Typsense Version**: 0.22.1

**Comment by kishorenc** [comment]
@zehawki Thank you for this detailed report. I agree -- we should have a uniform behavior here, preferably case insensitive. Typesense will probably send any one of the cased variants it finds. It's upto the application to standardize the facet values for display.

**Comment by eMarek** [comment]
Hi, I was testing the Ecommerce example and I came across similar issue.

Here is the link:
https://ecommerce-store.typesense.org/?products%5Bquery%5D=li&products%5BrefinementList%5D%5Bbrand%5D%5B0%5D=Case-Mate&products%5BrefinementList%5D%5Bbrand%5D%5B1%5D=Buqu&products%5BhierarchicalMenu%5D%5Bcategories.lvl0%5D%5B0%5D=Cell%20Phones

There are few products with "BUQU" brand and few with "Buqu" brand (lowercase vs. uppercase). It happens that Typesense has some issues with that. Try to select "Case-Mate" and "Buqu" brands. You will see that 15 products are returned. It seems that "BUQU" branded products are returned among them even though I didn't select that brand.

Screenshot:
<img width="961" alt="Screenshot 2022-02-01 at 20 49 47" src="https://user-images.githubusercontent.com/311634/152058357-81e87774-868a-4e9b-ae52-668ecc1a9bb1.png">

Not sure if this is related to the lowercase vs. uppercase thingy, but I found out that these two brands are initially not listed under filters. Any idea why?

Screenshot:
<img width="438" alt="Screenshot 2022-02-01 at 21 04 43" src="https://user-images.githubusercontent.com/311634/152058540-c9c1d6d4-296d-4d3f-9957-e8c53f1d0b25.png">

**Comment by kishorenc** [comment]
@eMarek 

Sorry, I missed replying to you. When the `Buqu` filter is selected, Typesense looks for products with that brand, but while indexing, Typesense lowercases the brand name so both `Buqu` and `BUQU` are indexed as `buqu` so 15 products are found, instead of 13.

**Comment by kishorenc** [comment]
Fixed in `0.23.0.rc54`: facet values are now "normalized".
