### ISSUE TITLE
Build error - Field is not defined in the collection schema

### ISSUE THREAD

**Issue by Richacinas** [typesense/typesense#505]
## Description

I'm getting a build error when trying to create a Typesense schema.

## Steps to reproduce

1. Added `<h1 data-typesense-field="brand_name">Brand name here</h1>` to some of my generated pages.
2. `typesense/typesense:0.22.1` docker image is up and running.
3. I added to gatsby config this:

```
{
      resolve: `gatsby-plugin-typesense`,
      options: {
        rootDir: `${__dirname}/public`,
        collectionSchema: {
          name: "brand",
          fields: [
            {
              name: "brand_name",
              type: "string",
            },
            {
              name: "page_path",
              type: "string",
            },
            {
              name: "page_priority_score",
              type: "int32",
            },
          ],
          default_sorting_field: "page_priority_score",
        },
        server: {
          apiKey: "86c5153b35cf",
          nodes: [
            {
              host: "localhost",
              port: "8108",
              protocol: "http",
            },
          ],
        },
      },
    },
```
I must say that I have another 2 blocks like this one on my gatsby config, for another couple of fields.

4. Run `npm run build`

## Expected Behavior

I would expect the build process to finish and the schemas to get created properly.

## Actual Behavior

I get the error:

`[Typesense] Field "brand_name" is not defined in the collection schema`

## Metadata

**Typesense Version**:

- Docker image: 0.22.1
- Gatsby plugin: 0.3.0

**OS**:

- Ubuntu 20.04 LTS
- npm 8.1.3
- node 14.15.0

**Comment by jasonbosco** [comment]
Since this is related to the Gatsby plugin, let's continue the conversation here: https://github.com/typesense/gatsby-plugin-typesense/issues/13#issuecomment-1021591838
