### ISSUE TITLE
Typesense crashes

### ISSUE THREAD

**Issue by viv-design** [typesense/typesense#508]
## Description

The typesense docker container exits with an error "ERROR Edge 2 has duplicate vertex with edge 7...Typesense 0.22.1 is terminating abruptly. wat? exit" when a geo search for self intersecting polygon or points belonging to more than one polygon are passed

## Steps to reproduce

Try to search for self intersecting polygon or pass 2 or more polygons

## Expected Behavior

The container should not exit, instead only log the error -> ERROR Edge 2 has duplicate vertex with edge 7

## Actual Behavior

The container exits and no more searches can be made

## Metadata

**Typsense Version**: 0.22.1

**OS**: CentOS7 running docker image

`/typesense/external-Linux/s2geometry-0.9.0/src/s2/s2loop.cc:131 ERROR Edge 2 has duplicate vertex with edge 7
/typesense/external-Linux/s2geometry-0.9.0/src/s2/s2loop.cc:284 FATAL Check failed: IsValid() E20220126 11:45:57.620537    61 backward.hpp:4199] Stack trace (most recent call last) in thread 61:
E20220126 11:45:57.620569    61 backward.hpp:4199] #22   Object "", at 0xffffffffffffffff, in
E20220126 11:45:57.620580    61 backward.hpp:4199] #21   Object "/lib/x86_64-linux-gnu/libc-2.23.so", at 0x7fc211b0e51c, in __clone
E20220126 11:45:57.620591    61 backward.hpp:4199] #20   Object "/lib/x86_64-linux-gnu/libpthread-2.23.so", at 0x7fc2124ed6b9, in start_thread
E20220126 11:45:57.620602    61 backward.hpp:4199] #19   Source "../../../../../libstdc++-v3/src/c++11/thread.cc", line 80, in execute_native_thread_routine [0x19b518f]
E20220126 11:45:57.620613    61 backward.hpp:4199] #18 | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/thread", line 215, in operator()
E20220126 11:45:57.620623    61 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/thread", line 271, in _M_invoke<0>
E20220126 11:45:57.620633    61 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/thread", line 264, in __invoke<ThreadPool::ThreadPool(size_t)::<lambda()> >
E20220126 11:45:57.620644    61 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 95, in __invoke_impl<void, ThreadPool::ThreadPool(size_t)::<lambda()> >
E20220126 11:45:57.620656    61 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 60, in operator()
E20220126 11:45:57.620666    61 backward.hpp:4199]     | Source "/typesense/include/threadpool.h", line 53, in operator()
E20220126 11:45:57.620676    61 backward.hpp:4199]       Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 1560, in _M_run [0xa78274]
E20220126 11:45:57.620687    61 backward.hpp:4199] #17 | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 1427, in _M_set_result
E20220126 11:45:57.620697    61 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 404, in call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*>
E20220126 11:45:57.620710    61 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/mutex", line 729, in __gthread_once
E20220126 11:45:57.620720    61 backward.hpp:4199]       Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/x86_64-linux-gnu/bits/gthr-default.h", line 700, in _M_run [0xb22e09]
E20220126 11:45:57.620731    61 backward.hpp:4199] #16   Object "/lib/x86_64-linux-gnu/libpthread-2.23.so", at 0x7fc2124f4a98, in __pthread_once_slow
E20220126 11:45:57.620741    61 backward.hpp:4199] #15 | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 564, in operator()
E20220126 11:45:57.620751    61 backward.hpp:4199]       Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/std_function.h", line 622, in _M_do_set [0xa763ca]
E20220126 11:45:57.620765    61 backward.hpp:4199] #14 | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/std_function.h", line 292, in __invoke_r<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<_Fn, _Alloc, _Res(_Args ...)>::_M_run<std::_Bind<HttpServer::process_request(const std::shared_ptr<http_req>&, const std::shared_ptr<http_res>&, route_path*, const h2o_custom_req_handler_t*)::<lambda()>()>, std::allocator<int>, void, {}>::<lambda()>, void>&>
E20220126 11:45:57.620779    61 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 113, in __invoke_impl<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<_Fn, _Alloc, _Res(_Args ...)>::_M_run<std::_Bind<HttpServer::process_request(const std::shared_ptr<http_req>&, const std::shared_ptr<http_res>&, route_path*, const h2o_custom_req_handler_t*)::<lambda()>()>, std::allocator<int>, void, {}>::<lambda()>, void>&>
E20220126 11:45:57.620791    61 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 60, in operator()
E20220126 11:45:57.620801    61 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 1365, in operator()
E20220126 11:45:57.620811    61 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 1424, in __invoke_r<void, std::_Bind<HttpServer::process_request(const std::shared_ptr<http_req>&, const std::shared_ptr<http_res>&, route_path*, const h2o_custom_req_handler_t*)::<lambda()>()>&>
E20220126 11:45:57.620822    61 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 110, in __invoke_impl<void, std::_Bind<HttpServer::process_request(const std::shared_ptr<http_req>&, const std::shared_ptr<http_res>&, route_path*, const h2o_custom_req_handler_t*)::<lambda()>()>&>
E20220126 11:45:57.620841    61 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 60, in operator()<>
E20220126 11:45:57.620851    61 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/functional", line 499, in __call<void>
E20220126 11:45:57.620935    61 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/functional", line 416, in __invoke<HttpServer::process_request(const std::shared_ptr<http_req>&, const std::shared_ptr<http_res>&, route_path*, const h2o_custom_req_handler_t*)::<lambda()>&>
E20220126 11:45:57.620949    61 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 95, in __invoke_impl<void, HttpServer::process_request(const std::shared_ptr<http_req>&, const std::shared_ptr<http_res>&, route_path*, const h2o_custom_req_handler_t*)::<lambda()>&>
E20220126 11:45:57.620960    61 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 60, in operator()
E20220126 11:45:57.620970    61 backward.hpp:4199]       Source "/typesense/src/http_server.cpp", line 619, in _M_invoke [0xb27289]
E20220126 11:45:57.620980    61 backward.hpp:4199] #13   Source "/typesense/src/core_api.cpp", line 265, in get_search [0xb03bd3]
E20220126 11:45:57.620990    61 backward.hpp:4199] #12   Source "/typesense/src/collection_manager.cpp", line 864, in do_search [0xadd8a2]
E20220126 11:45:57.621001    61 backward.hpp:4199] #11   Source "/typesense/src/collection.cpp", line 929, in search [0xaa1272]
E20220126 11:45:57.621011    61 backward.hpp:4199] #10   Source "/typesense/src/index.cpp", line 1594, in run_search [0xb633e7]
E20220126 11:45:57.621021    61 backward.hpp:4199] #9    Source "/typesense/src/index.cpp", line 2046, in search [0xb5fa86]
E20220126 11:45:57.621030    61 backward.hpp:4199] #8    Source "/typesense/src/index.cpp", line 1386, in do_filtering [0xb5c0e7]
E20220126 11:45:57.621040    61 backward.hpp:4199] #7    Object "/opt/typesense-server", at 0x1225045, in S2Loop::S2Loop(std::vector<Vector3<double>, std::allocator<Vector3<double> > > const&)
E20220126 11:45:57.621050    61 backward.hpp:4199] #6    Object "/opt/typesense-server", at 0x12250f7, in S2Loop::S2Loop(std::vector<Vector3<double>, std::allocator<Vector3<double> > > const&, S2Debug)
E20220126 11:45:57.621062    61 backward.hpp:4199] #5    Object "/opt/typesense-server", at 0x12252d8, in S2Loop::Init(std::vector<Vector3<double>, std::allocator<Vector3<double> > > const&)
E20220126 11:45:57.621071    61 backward.hpp:4199] #4    Object "/opt/typesense-server", at 0x1225820, in S2Loop::InitOriginAndBound()
E20220126 11:45:57.621081    61 backward.hpp:4199] #3    Object "/opt/typesense-server", at 0x1225ccb, in S2Loop::InitIndex()
E20220126 11:45:57.621091    61 backward.hpp:4199] #2    Object "/opt/typesense-server", at 0x11e2764, in S2FatalLogMessage::~S2FatalLogMessage()
E20220126 11:45:57.621101    61 backward.hpp:4199] #1    Object "/lib/x86_64-linux-gnu/libc-2.23.so", at 0x7fc211a3e039, in abort
E20220126 11:45:57.621111    61 backward.hpp:4199] #0    Object "/lib/x86_64-linux-gnu/libc-2.23.so", at 0x7fc211a3c438, in raise
Aborted (Signal sent by tkill() 1 0)
E20220126 11:45:58.287703    61 typesense_server.cpp:89] Typesense 0.22.1 is terminating abruptly.
wat? exit
`

**Comment by kishorenc** [comment]
@viv-design Can you please post an example polygon that triggers this issue?

**Comment by kishorenc** [comment]
@viv-design 

Please check against this Docker build: `typesense/typesense:0.23.0.rc23` -- handling the errors now.

**Comment by kishorenc** [comment]
Patched in `v0.22.2`.
