### ISSUE TITLE
Feature request: - queryBy not common parameters in federated search

### ISSUE THREAD

**Issue by edsonfeimberg** [typesense/typesense#509]
Currently Typesense seems to support only queries where you have commonly named fields in your different collections

example: field 'foo' present in collection A and B

Would be very useful if we could, in federated search, search by, for example: 'foo' in collection A and 'bar' in collection B.

**Comment by jasonbosco** [comment]
@edsonfeimberg This is already possible in the Typesense multi_search API. You can specify different query_by values for each search query within the mutli_search request. 

If you're referring to the instantsearch adapter by any chance, you want to configure the adapter using `collectionSpecificSearchParameters` as described here: https://github.com/typesense/typesense-instantsearch-adapter#index

**Comment by edsonfeimberg** [comment]
I followed the example and had this block of code:

```
const searchRequests = {
        searches: [
          {
            collection: 'brands',
            q: this.queryString,
          },
          {
            collection: 'cars',
            q: this.queryString,
          },
        ],
      }

      // Search parameters that are common to all searches go here
      const commonSearchParams = {
        query_by: 'name, full_name',
      }

      client.multiSearch.perform(searchRequests, commonSearchParams)
    },
```
 So that i could fetch by 'name' in 'brands' collection and by 'full_name' in 'cars' collection, but the request to 'brands' fail because 'full_name' field doesn't exist in that collection.



0 | Object { code: 404, error: "Could not find a field named `full_name` in the schema." }
-- | --
1 | Object { found: 3738, out_of: 27998, page: 1, … }

**Comment by jasonbosco** [comment]
Could you try this:

```
const searchRequests = {
        searches: [
          {
            collection: 'brands',
            q: this.queryString,
            query_by: 'name'
          },
          {
            collection: 'cars',
            q: this.queryString,
            query_by: 'full_name'
          },
        ],
      }

      // Search parameters that are common to all searches go here
      const commonSearchParams = {}

      client.multiSearch.perform(searchRequests, commonSearchParams)
    },
```

**Comment by edsonfeimberg** [comment]
I can confirm this syntax works!
