### ISSUE TITLE
30 minute server startup time. 

### ISSUE THREAD

**Issue by scottf-tvw** [typesense/typesense#51]
## Description

Very long startup time, at this point 30 minutes. I have around 150k documents spread across 20 collections or so. The data schema is the same in all of them. Document sizes range from 5 -> 200KB depending on if the document has a transcript. 
The documents contain an array of strings with transcript text for each array item, and an array of int32 to store the timecodes associated with each line.

> Initially I experimented with storing each transcript line in its own document but since each transcript belongs to a single event, without an aggregate method, it made the data unusable. It produced about 5M document records in all.

documents are added all of the time and not removed, they are synced with our backend that creates the data to fit the schema as event records are updated in our main system. 

I have a cluster in a autoscaling group but because of the long startup times taking so long, it makes multiple instances impossible to sustain. 

Q. is there a tweak to get this to start up faster?
Q. is it the data itself? can there be a better way to store this data to match results to a single event?
Q. Is my use-case way out of scope for typesense?

## Steps to reproduce

example of one of the larger documents
https://search.invintus.com/collections/9375922947/documents/search/?q=State&query_by=transcriptLines,description,title,agendaTitles,agendaDescriptions&sort_by=eventDateTime:asc&per_page=1

Schema:
```
"fields": [
            {
                "facet": false,
                "name": "clientID",
                "type": "string"
            },
            {
                "facet": false,
                "name": "eventID",
                "type": "string"
            },
            {
                "facet": false,
                "name": "title",
                "type": "string"
            },
            {
                "facet": false,
                "name": "description",
                "type": "string"
            },
            {
                "facet": false,
                "name": "status",
                "type": "string"
            },
            {
                "facet": true,
                "name": "categories",
                "type": "string[]"
            },
            {
                "facet": false,
                "name": "thumb",
                "type": "string"
            },
            {
                "facet": false,
                "name": "agendaTimes",
                "type": "int32[]"
            },
            {
                "facet": false,
                "name": "agendaTitles",
                "type": "string[]"
            },
            {
                "facet": false,
                "name": "agendaDescriptions",
                "type": "string[]"
            },
            {
                "facet": false,
                "name": "eventDateTime",
                "type": "int32"
            },
            {
                "facet": false,
                "name": "runtimeMinutes",
                "type": "int32"
            },
            {
                "facet": false,
                "name": "transcriptTimes",
                "type": "int32[]"
            },
            {
                "facet": false,
                "name": "transcriptLines",
                "type": "string[]"
            }
        ]
```

## Expected Behavior

hopefully much shorter than 30 minutes to read from disk

## Actual Behavior

```
2019/01/27 10:19:38 932233      INFO [typesense_server_utils.cpp->run_server:69]        Starting Typesense 0.9.2
2019/01/27 10:19:40 459019      INFO [typesense_server_utils.cpp->run_server:79]        Loading collections from disk...
2019/01/27 10:49:49 654728      INFO [typesense_server_utils.cpp->run_server:86]        Finished loading collections from disk.
2019/01/27 10:49:49 657052      INFO [http_server.cpp->run:144] Typesense has started. Ready to accept requests on port 8108
```

## Metadata

**Typsense Version**: 0.9.2

**OS**: ubuntu server 18.x

**hardware**: AWS EC2 r5a.xlarge  
data resides on EFS mount

**Comment by kishorenc** [comment]
@scottf-tvw 

I don't think it should be taking this long at all.

> data resides on EFS mount

My primary suspicion is the EFS.

> I have a cluster in a autoscaling group but because of the long startup times taking so long, it makes multiple instances impossible to sustain.

Are you sharing the same EFS data directory across multiple instances on the ASG, all of them booting off the same Typesense directory? How many instances are there on the ASG?

Let's first rule out data issues. Can you try the following:

1. Run only a single EC2 node in the ASG
2. Stop Typesense on that single node
3. Copy the Typesense data directory to the instance storage
4. Start Typesense by point to this data directory on the instance storage

How fast does Typesense start up now?

For high availability, instead of sharing the data directory via EFS, I recommend running replica servers:  https://typesense.org/0.9.2/guide/#high-availability

**Comment by scottf-tvw** [comment]
the data directory is only used to copy the data if needed, its not used for all the other nodes to read from, the cluster nodes are replica servers. 
I will try making a copy to the local EBS for the master and boot reading that.

**Comment by scottf-tvw** [comment]
is there a flag for debug information or more robust logging at the startup cmd?

**Comment by kishorenc** [comment]
@scottf-tvw If you can share the data, I can take a look. There isn't a way to have more verbose logging during startup. 

You should be able to just zip the data directory and share that directly.

**Comment by kishorenc** [comment]
@scottf-tvw Actually, I've a few more questions specific to your infrastructure/data -- before sharing the data, can we first discuss that? Email me - it would be discuss those specifics offline.

**Comment by kishorenc** [comment]
@scottf-tvw We've done some parallelization improvements in the latest release (`0.10.0`) which should help with the startup time.

**Comment by kishorenc** [comment]
Closing this issue. Feel free to reopen if a follow-up is needed.

**Comment by scottf-tvw** [comment]
Kishore, I moved to 0.10.1 and attempted a startup on my data set but it simply crashed with a resulting 

```
2019/11/11 23:50:33 954169      INFO [collection_manager.cpp->init:98]  Loading collection 8186354873

2019/11/11 23:50:33 960709      INFO [collection_manager.cpp->init:98]  Loading collection 8548232213

2019/11/11 23:50:33 986661      INFO [collection_manager.cpp->init:98]  Loading collection 9082264252

2019/11/11 23:50:33 988340      INFO [collection_manager.cpp->init:98]  Loading collection 9375922947

Killed
```

I ended up going back to 0.9.x but it will eventually also crash. I can get 0.10.1 to work only if I start with empty collections and reload all of the data via the api.

**Comment by kishorenc** [comment]
@scottf-tvw 

Definitely want to work with you to get to a good shape here.  

Typesense latest version is now `0.11.0`. If you can stop the server, compress the data directory and send it over, I can take a look. Does it crash while loading a specific collection?

**Comment by scottf-tvw** [comment]
Yes on the largest one. It really takes a significant time to load it before it fails. I have a local hardware system I am trying this on as well that has 24G of memory vs the 32 of the r5a.xlarge in aws to see if its simply running out of memory loading the data. 
I will email you the link to the current dataset. 
I also will get 0.11.0 and try to load up on that version.

**Comment by kishorenc** [comment]
What's the total size of uncompressed data on disk? That would give you a rough idea of memory requirements needed. Roughly 2x the memory of the uncompressed disk size is required if you are indexing most fields in a document stored on disk. For e.g. on-disk uncompressed storage is 10 GB, 20 GB of RAM is roughly required.

**Comment by scottf-tvw** [comment]
The total size of the data directory is 491MB. I sent an email to contact at typsense with the link to the current data folder tar file.

**Comment by scottf-tvw** [comment]
FYI a fair amount of the documents in the `9375922947` collection are pretty big. they hold vtt transcript index data with timecode and its associated event information. our use-case is fairly unique since we need to be able to search the voice transcripts that belong to an event. I have considered breaking the transcripts into chunks but aggregates would be needed to display results belonging to one event, which drops the speed considerably since that has to be done by our backend before delivering the results for a single events-> all results found for it.   You will see what I mean when you look at some of the documents.
