### ISSUE TITLE
Invalid Synonyms Break Collections

### ISSUE THREAD

**Issue by CameronSumpter** [typesense/typesense#510]
## Description

Attempting to add an invalid set of synonyms breaks the ability to update the related collection.

## Steps to Reproduce

Pass a synonym ID of type `int` or a synonym array without a `synonyms` key.

e.g. Instead of:
```
$client->collections['country']
       ->synonyms
       ->upsert('usa', ['synonyms' => ['us', 'united states']]);
```

Passing either of these will cause the issue:
```
$client->collections['country']
       ->synonyms
       ->upsert(1, ['us', 'united states']);
```

```
$client->collections['country']
       ->synonyms
       ->upsert('usa', ['us', 'united states']);
```

## Expected Behavior

HTTP 400 should be returned with an error and the collection should continue operating normally thereafter. Ideally, when passed a non-associative array of strings, Typesense would assume that they should, as a group, be taken as a multi-way synonym set.

## Actual Behavior

REST requests to the affected collection—specifically to add documents, modify synonyms, or delete the collection itself—time out and are not processed. Documents in the collection prior to the breaking request are still searchable.

## Metadata

**Typesense Version**: v0.23.0.rc20
**OS**: Typesense Cloud

**Comment by kishorenc** [comment]
@CameronSumpter 

Thanks for reporting this. I have added additional validation here. Will be happy to upgrade your Typesense Cloud cluster with this fix, if you wish.
