### ISSUE TITLE
Deletes are very slow in 3.9 million doc db

### ISSUE THREAD

**Issue by Sembiance** [typesense/typesense#515]
When running typesense `0.23.0_rc11` on `linux 5.15.12` performing deletes are very slow in a database with 3.9 million docs. Not a regression, it was slow in previous versions too.

Exact reproducible steps below, including test data.

Create our data dir and run the server:
```
mkdir data
typesense-server --data-dir=./data --api-address=127.0.0.1 --api-port=8108 --peering-address=127.0.0.1 --api-key=TESTCASEKEY
```

Create the schema:
```
curl "http://localhost:8108/collections" -X POST -H "Content-Type: application/json" -H "X-TYPESENSE-API-KEY: TESTCASEKEY" -d '{
"name" : "twig",
"fields" : [
{ "name" : "filename", "type" : "string" },
{ "name" : "size", "type" : "int64" },
{ "name" : "nsfw", "type" : "int32" },
{ "name" : "itemid", "type" : "int32", "facet" : true },
{ "name" : "catid", "type" : "int32", "facet" : true },
{ "name" : "genreid", "type" : "int32", "facet" : true },
{ "name" : "family", "type" : "string", "facet" : true },
{ "name" : "formatid", "type" : "string", "facet" : true, "optional" : true },
{ "name" : "ts", "type" : "int64", "optional" : true },
{ "name" : "content", "type" : "string", "optional" : true },
{ "name" : "ext", "type" : "string", "optional" : true },
{ "name" : "label", "type" : "string[]", "optional" : true },
{ "name" : "duration", "type" : "int32", "optional" : true },
{ "name" : "width", "type" : "int32", "optional" : true },
{ "name" : "height", "type" : "int32", "optional" : true },
{ "name" : "animated", "type" :  "bool", "optional" : true },
{ "name" : "title", "type" : "string", "optional" : true },
{ "name" : "subCount", "type" : "int32", "optional" : true, "index" : false },
{ "name" : "href", "type" : "string", "optional" : true, "index" : false },
{ "name" : "contentURL", "type" : "string", "optional" : true, "index" : false },
{ "name" : "extra", "type" : "string", "optional" : true, "index" : false }
] }'
```

Download the data and index it. You need about 20GB of free space (1.4GB download, expands to 6.2GB and typesense uses 11GB)
```
wget "https://telparia.com/twig-indexData.zip"
unzip twig-indexData.zip
cd indexData
gunzip *.gz
for i in *.jsonl; do curl --silent "http://127.0.0.1:8108/collections/twig/documents/import" -X POST -H "X-TYPESENSE-API-KEY: TESTCASEKEY" --data-binary @"$i" | sort | uniq -c; done
```

Verify we have **3,972,801** docs: `curl "http://127.0.0.1:8108/collections/twig" -X GET -H "X-TYPESENSE-API-KEY: TESTCASEKEY"`

Now run a delete with a `filter_by` that matches **902** documents: `time curl "http://127.0.0.1:8108/collections/twig/documents?filter_by=itemid:171" -X DELETE -H "X-TYPESENSE-API-KEY: TESTCASEKEY"`

On my system it took **32** seconds, which seems **really long** for just **902** documents to delete.

Here is a delete by query that matches **4,569** docs and takes **2 minutes and 28 seconds**: `time curl "http://127.0.0.1:8108/collections/twig/documents?filter_by=itemid:521" -X DELETE -H "X-TYPESENSE-API-KEY: TESTCASEKEY"`

On my production server where some searches may have been taking place, I was attempting to delete an itemid that matched **150,000+** docs and it took **hours**. During this delete I tried deleting just a single document by id and it took **20 seconds** for that single delete to run.

I'd love it if `DELETE` speed could be vastly improved. Seems like there should be a lot of room for improvement here.

Maybe some way to specify that the `DELETE` operation should be top priority and to just run through them as fast as possible?

**Comment by kishorenc** [comment]
@Sembiance 

I've a build for you to test. 

Docker: `typesense/typesense:0.23.0.rc27`
Linux binary: [`0.23.0.rc27`](https://dl.typesense.org/releases/0.23.0.rc27/typesense-server-0.23.0.rc27-linux-amd64.tar.gz)

Please test on your staging/dev environment first.

**Comment by kishorenc** [comment]
🎉 That's awesome. This will also help with indexing/update performance. 

This wasn't a bug, but I noticed that we could improve the way the integer fields could be indexed, and so refactored our integer indexing logic ([change](https://github.com/typesense/typesense/commit/1a29175bc07e1439ed2cb10d8bf6d72f987e8dc6)). We had earlier done a similar refactor for the string fields in v0.22, but since this schema is so integer heavy, that didn't help.

**Comment by Sembiance** [comment]
Super great to hear that the changes from this will help other areas too, typesense just keeps getting better.

Thanks again for the awesome improvement, really appreciated!
