### ISSUE TITLE
Match all words in query

### ISSUE THREAD

**Issue by orasik** [typesense/typesense#516]
## Description

When I search for a few words, the results would show documents containing **any** of these words.
For instance, I would like to search for all documents having **Node _and_ React** instead of **Node _or_ React**.

I wonder if there is a way to ensure seeing results matching all words in the query instead of the whole sentence.

**Comment by kishorenc** [comment]
@orasik 

Typesense prioritizes documents that contain all documents and only looks for documents containing either of the word when it can't find atleast one document with both words. We've improved this behavior further in 0.23 RC builds (specifically we have improved this for multi-field searches), so you might want to try against `typesense/typesense:0.23.0.rc26` Docker build.

That RC build also contains initial support for phrase search. Wrap your words with quotes to match exact phrases, e.g. `"node with react"`.

**Comment by orasik** [comment]
@kishorenc Fantastic, I will try it today and feedback with results.
But is there any way I can only see documents with all words? for instance, adding a **+** sign between words instead of space?

**Comment by kishorenc** [comment]
We support `-` exclusion but not `+`. To get this behavior, you can set `?drop_tokens_threshold=0` this will ensure that no tokens are ever dropped from the original query. You can also set `?typo_tokens_threshold=0` and `num_typos=0` to disable typo tolerance.

**Comment by orasik** [comment]
Thanks @kishorenc!  `drop_tokens_threshold=0` did the trick for me.
