### ISSUE TITLE
custom response

### ISSUE THREAD

**Issue by HuynhVuong87** [typesense/typesense#517]
![image](https://user-images.githubusercontent.com/37244262/152957907-ed94a200-1cbd-4eb5-b8f2-d8fbd4309cd9.png)

how to custom response with some properties as i want
eg. I don't want to show out_of field

**Comment by kishorenc** [comment]
I've an item in the backlog to make `exclude_fields` support `out_of` field. I will get to that shortly.

**Comment by HuynhVuong87** [comment]
one more thing, 
Seemly, there is a bug
when i use accessible_to_organization_id  then out_of count all docs in collection, it's wrong. Actually out_of should be only include documents belong to accessible_to_organization_id

**Comment by kishorenc** [comment]
That particular field just returns the total count of docs in the collection, so it doesn't scope count to just that organization.

**Comment by HuynhVuong87** [comment]
> That particular field just returns the total count of docs in the collection, so it doesn't scope count to just that organization.

it's better if i can show/hide this, i don't want to show total because this's business secret. example if user want to know total how many sales in collection, they just need to make a request

**Comment by kishorenc** [comment]
Got it, working on a way to exclude it via scoped API key configuration.

**Comment by kishorenc** [comment]
@HuynhVuong87 I've a fix for this: do you use Docker or Linux binary or DEB/RPM?

**Comment by HuynhVuong87** [comment]
> @HuynhVuong87 I've a fix for this: do you use Docker or Linux binary or DEB/RPM?

thank you so much
i will wait in next version

**Comment by kishorenc** [comment]
This is fixed in `v0.23`.
