### ISSUE TITLE
Question: does typesense keep the whole document in RAM?

### ISSUE THREAD

**Issue by orasik** [typesense/typesense#518]
If I understand correctly, TypeSense will only index fields that are defined in the schema collection.
So if I have a defined schema:
```
id
title
description
```
and I insert a document with:
```
id
title
description
keywords
image
```
it will only index the `title` and `description`.

But my question is, does TypeSense keep `keywords` and `image` in RAM?

**Comment by jasonbosco** [comment]
> But my question is, does TypeSense keep `keywords` and `image` in RAM?

No, Typesense stores unindexed fields only on disk. These fields are fetched from disk and returned as part of the response when a particular record is a hit.
