### ISSUE TITLE
Cluster is going down after 1M+ documents

### ISSUE THREAD

**Issue by orasik** [typesense/typesense#519]
## Description

1. I am running a cluster of 3 nodes.
2. Each node has 4vCPUs and 16GB of RAM.
3. Each node has a mounted drive to keep data separated from system files.
4. I am inserting documents in a batch of 5000.

The indexing is working brilliantly until I reach one million documents when I started receiving errors.

Checking logs, I noticed that two nodes had the following error:
```
acceptor.cpp:256] Fail to accept from listened_fd=20: Too many open files [24]
default_variables.cpp:335] Fail to open /proc/self/fd: Too many open files [24]
```

Another error (which had 28,656,615 lines in the log file) is:
```
typesense_server_utils.cpp:271] Error while refreshing peer configuration: File containing nodes configuration is empty.
```

I can see the file for node configuration.

Also, I found it weird that the log file was 4GB! I suppose the line mentioned above with 28M lines can be a factor?

## More info
I am running TypeSense binary as a service. 

I have tried the procedure above twice, same error after 1 million documents.

## My debugging 
1. I thought it is due to the open files limit on Linux, however after running `ulimit` the response was: `unlimited`.
2. I then tried `ulimit -n` and now I see `1024`. 
3. The number of files are as below (excluding files in archive folders):
```
db => 175 files
state => 6 files
meta => 11
```
The number of files including the archive folders:
```
db => 759
State => 913
meta => 13
```

## Metadata

**Typsense Version**: 0.22.2

**OS**: Ubuntu 20

**Comment by orasik** [comment]
I have identified the issue, it was the hard limit of open files `1024`.

## Solution

Add a higher limit in the typesense service file. Example:

```
[Service]
LimitNOFILE=16000
LimitNOFILESoft=16000
```
After doing that and restarting the service, I noticed the number of open files by one of the nodes is >1200 which is fine now but was an issue before.

Here is a good reference for changing the limit per service http://woshub.com/too-many-open-files-error-linux/

Hope this will help someone in the future.

**Comment by jasonbosco** [comment]
@orasik Thank you for documenting the solution!
