### ISSUE TITLE
Api for the snapshot's loading progress

### ISSUE THREAD

**Issue by hadminh** [typesense/typesense#520]
`client.operations.perform('snapshot', {'snapshot_path': '/tmp/typesense-data-snapshot'})`

After taking a snapshot, coping it into my new server and staring the new server, I need to know if the state folder has been fully loaded.

Is there a way to know if the Typesense-server has indexed all the state folder into memory?

For example:
.
.
.

`await client.state.retrieve();`

`GET ${TYPESENSE_HOST}/state`

Response:
```
{
  "state_loading_progress": "77.7"
}
```

**Comment by kishorenc** [comment]
When the /health endpoint returns "ok: true" that indicates that the server is done restoring and is ready.
