### ISSUE TITLE
[Feature Request] Ranking based on Relevance and Popularity connected to Override

### ISSUE THREAD

**Issue by aaroncueckermann** [typesense/typesense#525]
Currently, Ranking based on Relevance and Popularity can not be linked to an override. It would be nice to be able to promote certain products in a context-aware manner.

**Comment by kishorenc** [comment]
@aaroncueckermann Can you please provide an example so that I can understand your use case exactly?

**Comment by aaroncueckermann** [comment]
Hi @kishorenc

I want to be able to boost or bury search results based on an override (similar to the Algolia Rules section).

e.g. If the user searches "environmentally friendly cotton t-shirts". I want to be able to re-rank the results to boost the more environmentally friendly products. (perhaps using sort_by with buckets)

override = {
  "rule": {
    "query": "environment",
    "match": "contains"
  },
  "sort_by"="_text_match(buckets: 10):desc, environment_score:desc"
}


P.S.
At the same time it would also be very useful if you could apply overrides to a combination of filterable attributes as well as the query itself. 

e.g.

Apply overrides to an entire product category in combination with a query. So if the user searches for t-shirt and then filters by the material cotton you can apply overides to pin/hide/boost certain items. 

Thanks for taking the time to read this, I would love to hear what you think.

**Comment by kishorenc** [comment]
Thanks for the clarification. I agree, both will be very useful. Will add to our roadmap.

**Comment by aaroncueckermann** [comment]
Hi @kishorenc, sorry to hound but I was wondering if there is a timeline for the features described above to be added?

**Comment by kishorenc** [comment]
At the outset, I think we should be able to add support for these in the next 3-4 weeks. I will keep you posted on this thread.

**Comment by aaroncueckermann** [comment]
Thanks, much appreciated.

**Comment by aaroncueckermann** [comment]
Hi @kishorenc,

I was wondering if there was an update on this requested feature?

Thanks,
Aaron

**Comment by aaroncueckermann** [comment]
Hey @kishorenc, no problem! Thanks for getting back to me. Looking forward to seeing it!

**Comment by aaroncueckermann** [comment]
Hey @kishorenc 

I hope the text relevancy issues are going well!

Sorry to hound you, but I was hoping you would be able to provide an estimated timeframe for when you think this feature might be completed as my team is hoping to include it in our product.

Many thanks,
Aaron

**Comment by kishorenc** [comment]
@aaroncueckermann 

The good news is that I've already implemented the `sort_by` support for overrides, but it could not land on 0.23 release which is due in the next few days. However, I will be able to cut you a RC build of the next version (0.24) with this feature in the next few days so that you can test it and use it.

**Comment by aaroncueckermann** [comment]
@kishorenc 

Fantastic, thank you so much!

**Comment by aaroncueckermann** [comment]
> @aaroncueckermann
> 
> The good news is that I've already implemented the `sort_by` support for overrides, but it could not land on 0.23 release which is due in the next few days. However, I will be able to cut you a RC build of the next version (0.24) with this feature in the next few days so that you can test it and use it.

Hey @kishorenc would it be possible to get a cut of that RC build?

Many thanks,
Aaron

**Comment by kishorenc** [comment]
Yes, I can share the build: do you want Docker or a Linux artifact like DEB or tar.gz?

**Comment by aaroncueckermann** [comment]
Docker would be great please

**Comment by kishorenc** [comment]
@aaroncueckermann Did you get a chance to test this out?

**Comment by aaroncueckermann** [comment]
> @aaroncueckermann Did you get a chance to test this out?

Hey @kishorenc sorry about the late reply I was away for a little while. Getting it operational is in our current sprint and will hopefully be done by the end of the week as we need to make changes to the PHP Client and transfer our development servers over from Typesense Cloud. Will update you when if we have any issues or if all goes well!

**Comment by jasonbosco** [comment]
v0.24 is now available with this feature
