### ISSUE TITLE
How to configure number of snippets to be shown for each hit?

### ISSUE THREAD

**Issue by zopyx** [typesense/typesense#527]
With this template, I see only one snippet from one field even if there are more than one hits for a query within the same document.

```
   <div class="hit-text">{{#helpers.snippet}}{ "attribute": "text" }{{/helpers.snippet}}</div>
```

How can you give the number of snippets to be shown?

**Comment by kishorenc** [comment]
This is not yet possible but we want to figure out the best way to support it. 

Closing in favor of the discussion here: https://github.com/typesense/typesense/issues/434
