### ISSUE TITLE
[Bug] Highlighting logic: problems with punctuation symbols

### ISSUE THREAD

**Issue by newvladimirov** [typesense/typesense#528]
## Description

Highlighting algorithm ignores commas and dots

## Steps to reproduce

The search query is "readability":

![image](https://user-images.githubusercontent.com/11041059/154163677-98fcad4a-ceba-4915-b22e-31a490e2754e.png)
![image](https://user-images.githubusercontent.com/11041059/154163774-ada12137-6388-4631-90c9-2440c0474daf.png)

## Metadata

**Typsense Version**: typesense:0.23.0.rc27 (the stable version works even worse with punctuation) 

**OS**: MacOS 12.0.1 (21A559)

**Comment by newvladimirov** [comment]
And one more example with brackets:
the query is "readability golang" 
result is: 
![image](https://user-images.githubusercontent.com/11041059/154333085-d65968bd-3ab1-44d0-87a5-0c8e8ea2ec3b.png)

**Comment by kishorenc** [comment]
Thank you for reporting, I'll take a look and get back to you.

**Comment by kishorenc** [comment]
Fixed in `0.23.0.rc54`.
