### ISSUE TITLE
query count

### ISSUE THREAD

**Issue by HuynhVuong87** [typesense/typesense#529]
i have collection sales with create_time field

i want to know how many sales/day for a range of days in single query

eg. 
16 Feb has total 92 sales, revenue 1000$
17 Feb has total 22 sales , revenue 2523422$
18 Feb has total 55 sales, revenue 3435$
19 Feb has total 64 sales, revenue 353$
20 Feb has total 92 sales, revenue 2222$
21 Feb has total 500 sales, revenue 232$

could you give me a solution

**Comment by kishorenc** [comment]
Typesense can only aggregate on the date (via faceting) but can further group on revenue within each date. This requires advance, multi-level aggregation and is probably out of scope for a search engine like Typesense.
