### ISSUE TITLE
[New Feature] Presets API for search

### ISSUE THREAD

**Issue by jasonbosco** [typesense/typesense#530]
This new API endpoint will allow you to store preset values for all search parameters, instead of having to specify ech search parameter value in code when calling the search endpoint.

**Comment by HuynhVuong87** [comment]
please show examples or some docs, i am curious this

**Comment by Clasyc** [comment]
what is timeline for this feature?

**Comment by kishorenc** [comment]
Docs here: https://github.com/typesense/typesense-website/blob/v0.24.0/docs-site/content/0.24.0/api/search.md#presets

It will be available in the next version of Typesense (0.24), due for release shortly.

**Comment by jasonbosco** [comment]
v0.24 is now available with this feature: https://typesense.org/docs/0.24.0/api/search.html#presets
