### ISSUE TITLE
Maximum returned length for snippeted field

### ISSUE THREAD

**Issue by spencerkent** [typesense/typesense#533]
## Description
My search is on 3 fields in my index, and the 3rd field is very long (a long document body) so I only ever want display a short part of this field in the UI. I'm using the instantsearch.js adapter, with the highlight and snippet helpers like so:

```javascript
hits({
   container: '#hits',
   templates: {
     item(hit) {
       return `
         <h3>${highlight({ attribute: 'document_name', highlightedTagName: 'mark', hit })}</h3>
         <p>${highlight({ attribute: 'document_author', highlightedTagName: 'mark', hit })}</p>
         <p>${snippet({ attribute: 'document_body', highlightedTagName: 'mark', hit })}</p>
       `;
     }
   }
})
```
## Expected Behavior
If a hit comes from `document_body`, then a snippet is displayed with highlights, as I expect, nice! If the hit comes from `document_name` or `document_author`, I want the UI to still display a short snippet of `document_body`, maybe just the first N words, but with no highlight. 

## Actual Behavior
Currently, if the hit comes from `document_name` or `document_author`, the UI displays the entire `document_body` which messes up the UI with a huge chunk of text. 

I asked about this [over on the instantsearch.js project page](https://github.com/algolia/instantsearch.js/discussions/5018), and was told that Algolia is configured to only return a specific number of words you configure, even if there's no hit in the snippetted field, so what I'm seeing is likely the result of something I'm missing in the typesense instantsearch adapter or the typesense server itself. Can you help me figure out how to achieve the expected behavior? 

Thank you!

## Metadata

**Typsense Version**: 0.22.2

**OS**: Linux/AMD64 (Running this from the published 0.22.2 Docker image)

**Comment by jasonbosco** [comment]
@spencerkent Could you also share the typesense instantsearch adapter configuration you're using?

**Comment by spencerkent** [comment]
Sure, according to package.lock the version of the adapter is 2.2.0. When I'm instantiating the `TypesenseInstantSearchAdapter` in my javascript, I do it like this:
```javascript
const typesenseInstantsearchAdapter = new TypesenseInstantSearchAdapter({
  server: {
    apiKey: "#####",
    nodes: [
      {
        host: "localhost",
        port: "8108",
        protocol: "https"
      }
    ]
  },
  additionalSearchParameters: {
    queryBy: "document_name,document_author,document_body"
  }
});
```

**Comment by jasonbosco** [comment]
@spencerkent I think this might be fixed in a recent version of the adapter. Could you upgrade the typesense-instantsearch-adapter to `v2.4.1-0` and try this out again?

**Comment by spencerkent** [comment]
Unfortunately, it didn't fix the problem--still seeing the same behavior with `v2.4.1-0`  😤

**Comment by spencerkent** [comment]
(The version of instantsearch.js that I have installed is `4.38.1`, if that helps reproduce)

**Comment by jasonbosco** [comment]
@spencerkent I just noticed that you're using the `highlight` helper inside a JS string template, but I thought it was only available in liquid templates. May I know how you've defined the `highlight` JS function?

In any case, in JS templates, I'd recommend using the hit object directly which gives you more fine grained control about whether to use the snippet value or the full value. For eg:

https://github.com/typesense/typesense-instantsearch-demo/blob/8f5d332adae132c70b5daf4d0d24bc5c7f8b0750/src/app.js#L46

**Comment by spencerkent** [comment]
@jasonbosco I was doing it from the instantsearch /es/helpers module like this: 
```
import {highlight, snippet} from "instantsearch.js/es/helpers";
```
I agree that using the hit object directly is nicer, I switched to doing that based on the demo you linked, thanks. Now my workaround now is to just use javascript to truncate the `document_body` field. But, it would be nice to have a configuration option à la [attributesToSnippet](https://www.algolia.com/doc/api-reference/api-parameters/attributesToSnippet/) which would give me the option to only return `n` words **from the server** when the snippet isn't on that particular field. If my `document_body` fields are huge, that's sending a lot of data over the wire that is never going to be rendered in the UI.

**Comment by jasonbosco** [comment]
> But, it would be nice to have a configuration option à la [attributesToSnippet](https://www.algolia.com/doc/api-reference/api-parameters/attributesToSnippet/) which would give me the option to only return n words from the server when the snippet isn't on that particular field

You can use the `highlight_affix_num_tokens` search parameter for this, documented in [this table](https://typesense.org/docs/0.22.2/api/documents.html#results-parameters). You want to specify this in `additionalSearchParameters` when instantiating the instant search adapter. 

Also, by default the instantsearch adapter requests the entire field to be highlighted, but you can override this be setting `highlight_full_fields` in `additionalSearchParameters` to a subset of fields.
