### ISSUE TITLE
API Stats End Point Without Space and Special Character in the JSON Result

### ISSUE THREAD

**Issue by panoet** [typesense/typesense#535]
## Description

There is space and '/' char in the json key. It makes the json produced difficult to processed using commond library. In my case, I want to export it to Prometheus using json_exporter.

## Steps to reproduce

Access /stats.json endpoint

## Expected Behavior

No withspace there, maybe it should be replaced with "_"

> {
>   "latency_ms": {
>     "GET_collections_products": 0.0,
>     "POST_collections": 4.0,
>     "POST_collections_products_documents_import": 1166.0
>   },
>   "requests_per_second": {
>     "GET_collections_products": 0.1,
>     "POST__collections": 0.1,
>     "POST_collections_products_documents_import": 0.1
>   }
> }

## Actual Behavior

> {
>   "latency_ms": {
>     "GET /collections/products": 0.0,
>     "POST /collections": 4.0,
>     "POST /collections/products/documents/import": 1166.0
>   },
>   "requests_per_second": {
>     "GET /collections/products": 0.1,
>     "POST /collections": 0.1,
>     "POST /collections/products/documents/import": 0.1
>   }
> }

## Metadata

**Typsense Version**: 0.22

**OS**: Ubuntu 18.04

**Comment by kishorenc** [comment]
@panoet 

The stats end-point's goal is to provide the latency and request count values for the various API paths in a _readable format_.  So we've adopted the current key format of `<HTTP_METHOD_NAME> URL_PATH` -- using underscores will make it very difficult to understand. You can write another program that hits this end-point and ingest metrics into Prometheus periodically.
