### ISSUE TITLE
Curation API and filters

### ISSUE THREAD

**Issue by mikran** [typesense/typesense#536]
When curating documents it does not seem to be possible to set rules for `filter_by` values of the search.

For example we would like to curate different document for search `search?q=hamburg&query_by=title&filter_by=language:en` and one where filter_by is `filter_by=language:de`.

**Comment by kishorenc** [comment]
Yes, we should extend the curation features to support `filter_by` rules.

**Comment by jasonbosco** [comment]
This is now supported in `0.24.0.rcn10`. 

An override rule like this:

```json
{
  "overrides": [
    {
      "id": "curate-shoes",
      "includes": [
        {
          "id": "15",
          "position": 1
        }
      ],
      "rule": {
        "filter_by": "category:=[`shoes`]"
      },
      "stop_processing": true
    }
  ]
}
```

will get triggered when the `filter_by` search param (exactly) matches:

```
category:=[`shoes`]
```

**Comment by jasonbosco** [comment]
v0.24 is now available with this feature.
