### ISSUE TITLE
Include Text Match Score In The Result

### ISSUE THREAD

**Issue by panoet** [typesense/typesense#537]
## Description

Plese include the Text Match Score in the every result. We can use it to fine tuning the result. In my case, I am building a search engine to be used as analysis tools, and want to pass the result from Typesense to another logic. And we need to set a treshold so if a result have similarity score above it, it will be passed to the next logic.

## Steps to reproduce

There in no such feature.

## Expected Behavior

I get the text match score in every result.

## Actual Behavior

Not available for now.

## Metadata

**Typsense Version**: 0.22.0

**OS**: Ubuntu 18.03

**Comment by jasonbosco** [comment]
The text match score is indeed returned in all results:

<img width="373" alt="Screen Shot 2022-02-25 at 12 10 49 PM" src="https://user-images.githubusercontent.com/458383/155766044-fa25226b-561e-477c-bcb1-cff16e8c2da7.png">

Could you share a curl snippet and the response where the score doesn't show up?

**Comment by kishorenc** [comment]
@panoet 

The text match score is an absolute score computed based on the number of words that match between the query and the text, the proximity between the matched words, number of typos (if any), etc. In the case of multi-field searches, this score is also a sum of field-wise matching scores. As you can see, it's not easy to break this score down into the individual components.

You should instead be thinking in terms of the following parameters to control the relevancy of text matches:

- num_typos
- typo_tokens_threshold
- drop_tokens_threshold
- prioritize_exact_match

These parameters are described here: https://typesense.org/docs/0.22.2/api/documents.html#search-parameters

**Comment by kristinlindquist** [comment]
+1 on @panoet's question 'Is it possible to convert it as "percentage"?' Is there an upper bound on the text_match score given a certain schema and configuration?
