### ISSUE TITLE
How to deal with multiple values in facet

### ISSUE THREAD

**Issue by vnugent** [typesense/typesense#538]
How do you use facet when it has multiple values?  Let's consider the songs example in the [official docs](https://typesense.org/docs/0.22.2/api/documents.html#filter-results), a song can have multiple genres, blues + rock; multiple artists cover the same song.  In this case how do you define the schema and the query so that I can search songs by title?

> For eg: if you have a dataset of songs, and if you facet by the genre field and do a search, Typesense will return the number of matching songs in every genre in the results. This is useful to show users a summary of results, so they can further drill-down the results.

schema
```
const schema = {
  name: 'songs',
  fields: [
   ...,
    {
      name: 'genres',
      type: 'string',  <--- Should it be an array of strings or comma-separated values?
      facet: true
    },
    {
      name: 'performers',
      type: 'string',  <---  
      facet: true
    },
}

```

**Comment by kishorenc** [comment]
Yes, see the books example with the `authors` field being a string array and being faceted here: https://typesense.org/docs/guide/building-a-search-application.html#faceting
