### ISSUE TITLE
Prefix matching misses obvious results

### ISSUE THREAD

**Issue by rbrosboel** [typesense/typesense#540]
## Steps to reproduce

I query with the options `drop_tokens_threshold = 0` and `prefix = true`. For the following two similar queries I get unexpectedly different results:

- `little merm` returns good matches
- `little mer` returns no matches. I would expect it to include some of the matches above.

I have around 1.5 million documents in my dataset. I have been unable to reproduce on a smaller dataset, but have observed similar performance on [books-search.typesense.org](books-search.typesense.org):

- `little merm` returns many matches with the name "Little Mermaid", as expected.
- `little mer` returned none of the above, but instead plenty of matches that I would subjectively classify as much worse.

Is there a good explanation for what I experience, or could there be an issue with prefix search?

## Metadata

**Typsense Version**: 0.23.0.rc17

**OS**: Windows, WSL, Docker, typesense/typesense:0.23.0.rc17

**Comment by kishorenc** [comment]
@rbrosboel when querying for 'little mer' do the results contain other words that begin with 'mer'?

Can you also try searching with 'exhaustive_search=true' search parameter? Does it help?

**Comment by rbrosboel** [comment]
@kishorenc These are the top results I get with the different options.

Querying `little mer` with `drop_tokens_threshold = 0` returns 0 results.

Querying `little merm` with `drop_tokens_threshold = 0` returns 10 results in this order:
```
Little Mermaid
Little Mermaid Hotel Ishigakijima
Little Mermaid Dive Resort
Little Mermaid 1 Bedroom Home
The Little Mermaid TC 9107
Little Mermaid Dive Resort by Cocotel
Little Mermaid Villa- Beautiful Private Villa
The Little Mermaid Guesthouse & Restaurant
The Little Mermaid of Kimballton
Little Mermaid Statue
```

Querying `little mer` with `exhaustive_search = true` returns 119,140 results in this order:
```
Little Mermaid
Little Mermaid Hotel Ishigakijima
Little Mermaid Dive Resort
Little Mermaid 1 Bedroom Home
The Little Mermaid TC 9107
Little Mermaid Dive Resort by Cocotel
Little Mermaid Villa- Beautiful Private Villa
The Little Mermaid Guesthouse & Restaurant
The Little Mermaid of Kimballton
Little Mermaid Statue
Little Herdwick
Moressa Little
Little Melrose
Little Mornington
Little Mead
Little America
Little Ferry
Little Marais
Little Germany
Little Hereford
Little Melton
Little Marcle
Little Meadows
AC Hotel by Marriott Little Rock Downtown
Little Berwick Cottage
...
```

Querying `little merm` with `exhaustive_search = true` returns 11,746 results in this order:
```
Little Mermaid
Little Mermaid Hotel Ishigakijima
Little Mermaid Dive Resort
Little Mermaid 1 Bedroom Home
The Little Mermaid TC 9107
Little Mermaid Dive Resort by Cocotel
Little Mermaid Villa- Beautiful Private Villa
The Little Mermaid Guesthouse & Restaurant
The Little Mermaid of Kimballton
Little Mermaid Statue
Little Germany
Termini Station Little House
Little Ryukyu Hermit Crab Homestay
Little Saint Germain Lake
Little Bear Lodge by Escape to Blue Ridge
Little Venice Paddington Studio
Little Amanya Camp
New In Rome Little Candy Apt In Vatican
Little Hill - 3 Bed - Wisemans Bridge
Your Apartment The Little Birdie
...
```

For completeness, querying `little mer` with out of the box defaults returns 1,666 results in this order:
```
Little Bear Lodge by Escape to Blue Ridge
Little Venice Paddington Studio
Little Amanya Camp
New In Rome Little Candy Apt In Vatican
Little Hill - 3 Bed - Wisemans Bridge
Your Apartment The Little Birdie
Little london
577 Little Harbor
Studio 6 Little Rock, AR - West
Little Herdwick
Little Cottage
Holiday Inn Express & Suites Little Rock-West, an IHG Hotel
3 Br Luxury & Spacious Apartment in Little Italy
O Little Tent de Koh Chang
Little Eden Guest Lodge
Holiday Inn Little Rock-Airport-Conference Center, an IHG Hotel
The Savoy Hotel on Little Collins Melbourne
Little Beach Hotel Da Nang
Little Acorn
Little Rock Creek Retreat
...
```

**Comment by kishorenc** [comment]
@rbrosboel 

I think I understand what's happening here. When there are a lot of words sharing a prefix, Typesense restricts prefix candidates to a few words because typically it's difficult to guess which word the user is actually looking for. So for e.g. with just `mer` there are probably many words that begin with that prefix so Typesense picks a few of them based on the `default_sorting_field` score, but then it could happen that none of them co-occur with the previous word in the query (`Little`) so no results are found. 

Using the exhaustive_search mode removes this restriction and makes Typesense consider all words matching a prefix, at the expense of some performance.

**Comment by rbrosboel** [comment]
@kishorenc 

Plausible explanation. Thanks.

Would it be possible to support the combination `drop_tokens_threshold = 0` and `exhaustive_search = true`? This should let Typesense consider all prefix words, but still require all tokens?

**Comment by kishorenc** [comment]
Yes, that is already possible and should work.

**Comment by kishorenc** [comment]
Oh wait, `exhaustive_search` actually overrides `drop_tokens_threshold` as well, since it aims to be exhaustive in all aspects. Thankfully, there is another configuration called `max_candidates` that we have introduced in these RC builds that will control the number of prefix candidates that Typesense will look at. Set `max_candidates: 1000` and I think it should work fine.

**Comment by rbrosboel** [comment]
@kishorenc Nice, this seems to give much better results for my dataset. Thank you for an awesome project, and for taking the time to help out with this!
