### ISSUE TITLE
Please add a way to get the TS version number

### ISSUE THREAD

**Issue by zehawki** [typesense/typesense#544]
How does one get the version number of TS installed?

I'm unable to find anything in the docs - either under command line, or API.

Apologies if its already there! A search for "version" also doesnt show anything.

![image](https://user-images.githubusercontent.com/8095144/157316011-ea6388bd-611c-4c6e-8440-d6e518a93069.png)

**Comment by jasonbosco** [comment]
@zehawki We need to add this to the docs, but if you do a `GET /debug` with a `x-typesense-api-key` header, you'll see the version number.
