### ISSUE TITLE
Synonym with special character "+" doesn't work as expected

### ISSUE THREAD

**Issue by eminos** [typesense/typesense#553]
## Description

Adding this two-way synonym doesn't give the expected results.
```javascript
[
    '+',
    'plus'
]
```

## Steps to reproduce

Create a collection with `'symbols_to_index' => ['+']` (I don't know if that matters or not.)

Then add the above synonym.

I tried this on Typesense Cloud:
![image](https://user-images.githubusercontent.com/1682784/158637628-8a3df26a-9a70-4408-9780-16a9ef1215c2.png)

I get the same result on my local installation:
![image](https://user-images.githubusercontent.com/1682784/158637820-94cdeea6-7d6f-40be-aed7-feb2c5731a90.png)

## Metadata

**Typsense Version**: 0.22.2 / 0.22.1

**OS**:

**Comment by kishorenc** [comment]
@eminos 

This is indeed a bug. When the synonyms are stored, we split them into tokens/words and store them as a list. And that tokenzier is dropping the special characters. We'll have to fix that.

**Comment by j10sanders** [comment]
This matters for periods as well.  For example, I can't map `express.js` to `express`

**Comment by kishorenc** [comment]
This is fixed in `typesense/typesense:0.24.0.rc19`.

**Comment by jasonbosco** [comment]
v0.24 is now available with this fix/feature.
