### ISSUE TITLE
Can not start Typsense on Mac 10.13.6 - dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by philipeachille** [typesense/typesense#557]
## Description

Can not start Typesense on older Mac OS

## Steps to reproduce

Go through normal install and start-routine on MacOS 10.13.6

## Expected Behavior

Start of Typesense Server

## Actual Behavior

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/christianhildebrand/Applications/typesense/./typesense-server (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/christianhildebrand/Applications/typesense/./typesense-server (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6

## Metadata

**Typsense Version**: 
0.22.2

**OS**:
MacOS 10.13.6

**Comment by kishorenc** [comment]
I recently discovered this and unfortunately, it's not easy to fix since I would then need to build the binary on a very old version of macOS, and would probably need a spare machine just for that. 

For now, Typesense requires atleast macOS Big Sur.
