### ISSUE TITLE
How to run on a Wordpress site (MySQL)?

### ISSUE THREAD

**Issue by pkiula** [typesense/typesense#56]
## Description

Neither the stuff on Github nor the 'detailed guide' on the website quite talks about what one needs to do to create the data index, from which TypeSense queries. Do we have to create multiple JSONs as documented in the example? Is there a Wordpress plugin to do the same? 

## Steps to reproduce

None. It's a question. 

## Expected Behavior

Expect TypeSense to have some smart mechanisms to easily automate the *creation* of indexes by sections of a typical website or app. Also, it's hard to come by examples of what one needs to do to tweak CSS etc for altering the look of the default search. 

## Actual Behavior

Does none of the above. Even the guide is super simple. 

## Metadata

Latest. 

**OS**:

Linux CentOS on the server.

**Comment by kishorenc** [comment]
@pkiula 

Thank you for the feedback. The guide and README focus on indexing database records/entities and does not cover how to index and search website. I've created [an issue](https://github.com/typesense/typesense-website/issues/11) for that and I hope to have an article soon on that.

To be honest, we've not done much work to make it easy to use Typesense to index websites and pull data from other applications like Wordpress. This is one area which we are going to focus on in the coming months.
