### ISSUE TITLE
Would there be a full list of actions to know how we can customize the scope of API keys

### ISSUE THREAD

**Issue by tjmonsi** [typesense/typesense#571]
## Description

There are a list of sample actions here: https://typesense.org/docs/0.22.2/api/api-keys.html#sample-actions

but I would like to know if there is a full list that I can look at to know the full list of actions so that I can properly scope my API keys

**Comment by kishorenc** [comment]
@tjmonsi 

The permission string is created in the `<resource name>:<action>` format.  Here's how we generate them: https://github.com/typesense/typesense/blob/6092916a185c39032a7c1fdc637c41cfbe4ecce2/include/http_data.h#L406-L422
