### ISSUE TITLE
[BUG] Document ids are accepted with space char (%20) and cannot be deleted from Cloud db

### ISSUE THREAD

**Issue by gicelte** [typesense/typesense#574]
## Description

Using the API I created some documents with ids without trimming space chars they contained, as I did not even know some ids were like that, and as such they got accepted in the Typesense Cloud database.

After removing the space char from the id, to make it correct, the document was upserted again in Typesense and actually duplicates the one with the space char. See an example here:
https://www.galeria9.com.br/?arts%5Bquery%5D=diamante%20de%20ouro

## Steps to reproduce

1. Create a document having an id ending with a space char
2. Upsert the document into the Cloud database
3. Attempt deleting the document (I tried with the API and with a straight DELETE curl request to the cloud database URL)

## Expected Behavior

Document deleted.

## Actual Behavior

Document NOT deleted.
Error sample: {"message": "Could not find a document with id: ART41554-4742%20"}

## Metadata

**Typesense Version**:
https://cdn.jsdelivr.net/npm/algoliasearch@4.5.1/dist/algoliasearch-lite.umd.js
https://cdn.jsdelivr.net/npm/instantsearch.js@4.8.3/dist/instantsearch.production.min.js
https://cdn.jsdelivr.net/npm/typesense-instantsearch-adapter@1.2.1-7/dist/typesense-instantsearch-adapter.min.js

**OS**:
Any

**Comment by kishorenc** [comment]
Fixed in `0.23.0.rc54`
