### ISSUE TITLE
Unable to use negation filter to integer field.

### ISSUE THREAD

**Issue by xpader** [typesense/typesense#576]
## Description

Can not use negation filter to numeric field.

## Steps to reproduce

Use `status:!=1` on numeric field (type: int32 or int64).

## Expected Behavior

Return results that field value not 1.

## Actual Behavior

`status:!=1` error:
**Error with filter field `status`: Numerical field has an invalid comparator.**

`status:<>1` error:
**Error with filter field `status`: Not an int32.**

## Metadata

**Typsense Version**:
0.22.2

**OS**:
Ubuntu 20.04

**Comment by kishorenc** [comment]
Yes, this is not supported at the moment, but will be adding support for it shortly.

**Comment by samuelhautcoeur** [comment]
Any chance we can see that in v0.24?

**Comment by kishorenc** [comment]
@samuelhautcoeur 

It won't be part of 0.24 but we've already added support for this on a 0.25 RC build, and should be available shortly for you to test (~ 1 week).
