### ISSUE TITLE
How can we change RocksDB configuration?

### ISSUE THREAD

**Issue by melovv** [typesense/typesense#58]
Hi.

Again, very nice work with typesense.

I was wondering: how can we change RocksDB configuration?

**Comment by kishorenc** [comment]
@melovv 

Thank you for the compliment. 

We don't have a way to change the RocksDB configuration at the moment. There are lots of knobs and we arrived at a configuration that balanced speed with write amplification. If you can describe to me what you want to change, we can see how to expose the relevant configurations.

Happy to also chat more about your specific use case over email: contact at wreally dot com
