### ISSUE TITLE
browser warning "Request to Node 0 failed due to "ECONNABORTED timeout of 1000ms exceeded" ApiCall.ts:205:20"

### ISSUE THREAD

**Issue by kulame** [typesense/typesense#581]
## Description
browser show a warning message 
``` 
Request to Node 0 failed due to "ECONNABORTED timeout of 1000ms exceeded" ApiCall.ts:205:20

```

what's wrong with this?

## Metadata

**Typsense Version**: typesense/typesense:0.22.2

**OS**:ubuntu

**Comment by kishorenc** [comment]
The request took longer than 1000 ms to exceed, so connection was aborted. You can increase the timeout in the JS client to allow slower requests to complete.
