### ISSUE TITLE
Embedded params parsing error in Firefox

### ISSUE THREAD

**Issue by seowzhenjun0126** [typesense/typesense#583]
## Description

Hi, I am getting this error from the Typesense server:

`500 Internal Server Error`
`{"message": "Embedded params parsing error."}`

in **Firefox** when I try to query for data.

The same query doesn't have an issue in Google Chrome and Postman, and also doesn't have an issue in Firefox when queried for the first time. It only occurs to the queries after that.

After some experiments, it seems like the error happens when the `/multi_search` endpoint has a body of `searches` with an array of length > 1.

## Expected Behavior

The query shouldn't have any error when run in Firefox.

## Actual Behavior

The error `Embedded params parsing error.` occurs in Firefox, but not in Google Chrome.

## Metadata

**Typsense Version**: v0.23.0.rc55

**OS**: Typesense Cloud

**Comment by seowzhenjun0126** [comment]
Hi @kishorenc ,

You can try this query, it is some dummy data on my site.

URL: https://xegwybd68pt4a51lp-1.a1.typesense.net/multi_search?x-typesense-api-key=ejg2emp6cEpXU2UxMVJYNTlKVzlYM1FVckRGaGpjVVNIY3p2ZDFLSjdnVT1zRnJheyJmaWx0ZXJfYnkiOiJvcmdJZDpOMzk0OURObVEyS0Y3R0dXOERKMiYmcGVybXMuY2FuX3JlYWQ6RmhmdGhGSHR1Z1dSc2JUSFNaQllqRXRiWXU4MiJ9

POST body:
`
{"searches":[{"query_by":"data.name, data.email, data.phone, data._remarks, data._remarks_1 , metadata.tags","per_page":50,"num_typos":1,"exclude_fields":"orgId, data._remarks, data._remarks_1, metadata.assign_method, metadata.assign_op, metadata.dist_group_id, metadata.source, metadata.notify, metadata.time_bomb","sort_by":"_text_match:desc, metadata.creation_time:desc","highlight_full_fields":"data.name, data.email, data.phone, data._remarks, data._remarks_1 , metadata.tags","collection":"leads","q":"*","facet_by":"metadata.assigned_by_uid,metadata.owner,perms.can_read,metadata.tags,data.status_1,data.status_2,metadata.creation_time,last_update.time,data.app_date","filter_by":"metadata.owner:=[`FhfthFHtugWRsbTHSZBYjEtbYu82`] && metadata.assigned_by_uid:=[`FhfthFHtugWRsbTHSZBYjEtbYu82`]","max_facet_values":50,"page":1},{"query_by":"data.name, data.email, data.phone, data._remarks, data._remarks_1 , metadata.tags","per_page":1,"num_typos":1,"exclude_fields":"orgId, data._remarks, data._remarks_1, metadata.assign_method, metadata.assign_op, metadata.dist_group_id, metadata.source, metadata.notify, metadata.time_bomb","sort_by":"_text_match:desc, metadata.creation_time:desc","highlight_full_fields":"data.name, data.email, data.phone, data._remarks, data._remarks_1 , metadata.tags","collection":"leads","q":"*","facet_by":"metadata.owner","filter_by":"metadata.assigned_by_uid:=[`FhfthFHtugWRsbTHSZBYjEtbYu82`]","max_facet_values":50,"page":1},{"query_by":"data.name, data.email, data.phone, data._remarks, data._remarks_1 , metadata.tags","per_page":1,"num_typos":1,"exclude_fields":"orgId, data._remarks, data._remarks_1, metadata.assign_method, metadata.assign_op, metadata.dist_group_id, metadata.source, metadata.notify, metadata.time_bomb","sort_by":"_text_match:desc, metadata.creation_time:desc","highlight_full_fields":"data.name, data.email, data.phone, data._remarks, data._remarks_1 , metadata.tags","collection":"leads","q":"*","facet_by":"metadata.assigned_by_uid","filter_by":"metadata.owner:=[`FhfthFHtugWRsbTHSZBYjEtbYu82`]","max_facet_values":50,"page":1}]}
`

Note that it seems like if the body is long enough the error will happen. If you try to remove some data from the body, the query returns fine.

**Comment by kishorenc** [comment]
@seowzhenjun0126 

I've put together this small HTML file which makes a multi search request from Javascript using jQuery. This works fine for me on both Chrome and Firefox. Can you please try it to see if the issue is reproduceable on your end? https://gist.github.com/kishorenc/c4b75269aedf7c5c4c6e6e55e96854c9

In both Chrome and Firefox, I see the network console show a successful result as response without any error.

**Comment by seowzhenjun0126** [comment]
Hi @kishorenc 

Yes, it works fine when I run the HTML file.

But when I try to "Edit and Resend" the request without actually editing anything, it came back as an error.

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/56989187/165434858-2d4aaa93-e519-43ce-9ac7-3a61b4724b33.png">

**Comment by kishorenc** [comment]
Got it, I'm looking into this. Will keep you posted.

**Comment by kishorenc** [comment]
We've patched your cluster, can you please check again?

**Comment by seowzhenjun0126** [comment]
Hi @kishorenc ,

I just tested and it's working fine now, thank you very much for your prompt response!

**Comment by kishorenc** [comment]
Thanks for confirming!
