### ISSUE TITLE
Range filter not working on int64 fields

### ISSUE THREAD

**Issue by Mohana-Manikandan** [typesense/typesense#585]
## Description

Pardon me, I may be using the apis wrongly but I noticed that Range filters are not working on int64 fields while searching.

## Steps to reproduce

1. Create a collection which contains a time field that is of type int64 which stores epoch milliseconds
2. Add documents to the collection
3. Perform a search with a  filter_by parameter on time as a range

**[Non Working Code] Search Parameters with range filter**
search_parameters = {
    'q'         : 'ddfb511f-9b40-4365-ba43-cb9d9adc05e7',
    'query_by'  : 'xxx-xxx',
    'filter_by' : 'time:[1646092800000...1648771199000]',
    'sort_by'   : 'time:asc'
  }

**[Working Code] Search parameters without range filer (using > & <)**
search_parameters = {
    'q'         : 'ddfb511f-9b40-4365-ba43-cb9d9adc05e7',
    'query_by'  : 'xxx-xxx',
    'filter_by' : 'time:>1646092800000 && time:<1648771199000',
    'sort_by'   : 'time:desc'
  }

## Expected Behavior

Search should run and return the results in between the above timestamps

## Actual Behavior
Getting a client error mentioning the time field is not an int64.

```
(node:15683) UnhandledPromiseRejectionWarning: Error: Request failed with HTTP code 400 | Server said: Error with filter field `time`: Not an int64.
    at ApiCall.customErrorForResponse (/home/ubuntu/typesense/client/node_modules/typesense/lib/Typesense/ApiCall.js:220:21)
    at ApiCall.performRequest (/home/ubuntu/typesense/client/node_modules/typesense/lib/Typesense/ApiCall.js:118:48)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15683) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Metadata

**Typsense Version**: 0.22.2
**Typesense JS Client Version**: 1.2.2
**OS**: Linux

**Comment by kishorenc** [comment]
@Mohana-Manikandan 

The range filter syntax is wrong. It must be 2 dots and not 3 dots. With 3 dots, Typesense just treats the entire value as a single string. 

The following will work:

```
time:[1646092800000..1648771199000]
```

**Comment by Mohana-Manikandan** [comment]
My bad, I overlooked the documentation while searching documents. Thanks Kishore !
