### ISSUE TITLE
separate or combine, what save memory

### ISSUE THREAD

**Issue by huynv86** [typesense/typesense#586]
In my case, to make unique a doc and check exist
option 1: build id in format field1_field2_field3_field4. Easy to check exist, just filter id field
option 2: generate guid for id and index field1, field2, field3, field4. Check exist by filter field1, field2, field3, field4
i care about RAM memory, so what is best way. Seemly option1 will eat RAM more than option 2, is it right?

**Comment by kishorenc** [comment]
In Typesense 0.23, the `id` field is no longer indexed in-memory so option 1 is the best option going forward.
