### ISSUE TITLE
new startup

### ISSUE THREAD

**Issue by RDP1974** [typesense/typesense#588]
hello,
typesense seems exceptional,
I'm evaluating it for a new startup project,

please can I ask this: guess a community by 100,000  records with geo location, each one updating its position every minute (so moving, instead to be fixed); does typesense can manage an average 1,000 or 1,500 updates/indexed of geo positions every second (without cpu overburn or data corruption)?

thank you
kind regards

**Comment by RDP1974** [comment]
Can batch updates will lower the overhead?
Example1
Transaction->insert 100 records->commit 

or inserting 100 records in one unique call?

In other words, typesense is well suited for data with frequent updates or inserts?

**Comment by kishorenc** [comment]
Yes, with the recent 0.23 builds we have really optimized the updates performance further. With batched imports you can make several thousands of updates really fast.

**Comment by RDP1974** [comment]
great
thanks

**Comment by RDP1974** [comment]
Btw: how to do batch updates or inserts?

**Comment by kishorenc** [comment]
Here: https://typesense.org/docs/0.22.2/api/documents.html#index-multiple-documents

**Comment by RDP1974** [comment]
please can I ask if the Windows (Server) version is reliable and stable for production use as the linux counterpart?
(atleast for a begin period)
