### ISSUE TITLE
How does parameter q match special characters?

### ISSUE THREAD

**Issue by bianjunjie1981** [typesense/typesense#589]
## Description

How does parameter q match special characters?

It looks like special characters have been filtered
Such as *** % &! # @**...

## Metadata

**Typsense Version**:

**OS**:

**Comment by jasonbosco** [comment]
By default special characters are indeed ignored. You want to use the `symbols_to_index ` configuration when creating the collection. Here are more details under this table (search for `symbols_to_index`): https://typesense.org/docs/0.22.2/api/collections.html#schema-parameters

**Comment by bianjunjie1981** [comment]
Thank you for your advice

> By default special characters are indeed ignored. You want to use the `symbols_to_index ` configuration when creating the collection. Here are more details under this table (search for `symbols_to_index`): https://typesense.org/docs/0.22.2/api/collections.html#schema-parameters
