### ISSUE TITLE
obtaining match score in results?

### ISSUE THREAD

**Issue by jspeis** [typesense/typesense#59]
Is there any way to obtain the internal scores of the level of the match for each result from the `${TYPESENSE_HOST}/collections/:collection/documents/search` endpoint? (e.g. if there is a way to get back something like `{id: "124", ... , _score: 0.98}` for each result?)

**Comment by kishorenc** [comment]
@jspeis 

No, those scores are not exposed, since they are just absolute numbers used for sorting and don't indicate a form of "percentage accuracy".  

Is there a specific reason you want them exposed?

**Comment by jspeis** [comment]
@kishorenc I see, thanks for your response!

In my particular case I had a few different collections that have differing metadata schemas and in one particular instance it could be useful to search across all collections and compare results. Though I suppose in this case I could also create a single unified collection. 

Generally, I think it could be nice if there was some way to customize/override the default scoring algorithm.

**Comment by kishorenc** [comment]
There is probably no harm in exposing the score and is also easy to do that. Will add that in a future release.

The default scoring algorithm is a simple tie breaker which seems to work for most common search use cases. What kind of customization would you like?

**Comment by lufias** [comment]
@kishorenc has this feature been implemented? I have a good use case for this. Im building a listing of items for user to search for. But sometimes, the search doesn't return what they are actually looking for. Say for example the highest score is below the threshold of 50%, then I know the result is not satisfied. Thus, I want to know and maybe log the searching keyword so that I can review and perhaps add what the user is searching for in future if necessary.

**Comment by kishorenc** [comment]
@lufias 

No, this is not yet implemented. I've built a custom build for you with the `match_score` field now exposed in the search results: https://dl.typesense.org/releases/typesense-server-0.12.0-pre-1-linux-amd64.tar.gz

You can try it out. However, it's not a percentage score -- it's an absolute score which is really just the tie breaking expressed as a single numerical value for easy sorting of the hits.

**Comment by stereosteve** [comment]
Also it would be nice to have a `typo_count` along side any result.  This would make it easy to draw a line in the UI between exact matches and near matches for things like SKUs.

**Comment by kishorenc** [comment]
On the official v0.12.0 release, the match score is returned via the `text_match` response field. 

I will create a separate issue for returning `typo_count`.
