### ISSUE TITLE
Sort option geo_precision throws bad syntax error

### ISSUE THREAD

**Issue by ymc-sise** [typesense/typesense#592]
## Steps to reproduce

Use the `geo_precision` sort option according to your documentation 
https://typesense.org/docs/0.22.2/api/documents.html#sorting-by-additional-attributes-within-a-radius

## Expected Behavior

No error.

## Actual Behavior

Throws a `Bad syntax for geopoint sorting field "location".`

## Metadata

**Typsense Version**: 0.22.2

**OS**: Alpine Linux, 3.15.4

## Solution

Either fix the documentation from `geo_precision` to `precision`:

`'sort_by' : 'location(48.853, 2.344, precision: 2mi):asc, popularity:desc'`

or fix the constant from `precision` to `geo_precision` in your header file:
https://github.com/typesense/typesense/blob/master/include/field.h#L481

Otherwise, in my opinion this check fails here https://github.com/typesense/typesense/blob/master/src/collection.cpp#L699

What confuses me a bit, you are testing it here with `loc` and `precision`
https://github.com/typesense/typesense/blob/master/test/collection_sorting_test.cpp#L820

**Comment by kishorenc** [comment]
My bad, this is documentation issue -- it must be `precision`.
