### ISSUE TITLE
Feature Request: Distinct queries

### ISSUE THREAD

**Issue by manuelJung** [typesense/typesense#596]
## Description

A distinct query feature (sql-like) would be awesome! Why: Imagine you have an index containing product SKUs. Multiple SKUs form a product by providing the same `productId` prop. So we have the product "Shirt" which has 3 SKUs; each in a different size. Each SKU has the same productId. In the UI I want to display my SKUs, but only one SKU per product. I don't want to have all 3 different sizes listed next to each other (just one size is enough since all will have the same image). 

The Distinct-Feature would not allow to resolve hits with the same productId. Only the most recent one (best sorting score) will be picked and resolved in the result

Possible API:

```javascript
const search_parameters = {
  'q': "",
  'distinct: "productId"
}
```

Output: 
```javascript
const out = {
  ...,
  "page": 1,
  "hits": [
     { productId: "1", ... },
     { productId: "2", ... }
  ]
}
```

**Comment by jasonbosco** [comment]
@manuelJung This is already supported. Here's the documentation for it: https://typesense.org/docs/0.22.2/api/documents.html#group-results
