### ISSUE TITLE
Self Hosted High Availability Cluster Setup

### ISSUE THREAD

**Issue by Bug-Reaper** [typesense/typesense#599]
## Description

So I have a global shared VPC setup on Google Cloud and my plan is to run several Typesense Kubernetes clusters in various regions and have them peer across the shared VPC internal network. Forked [this 3 node cluster setup](https://github.com/typesense/typesense-kubernetes) and built from there. Have a couple questions hope someone can assist:

1. Can I include wildcard IP addresses in the node-list at (`/usr/share/typesense/nodes`)? There's ranges of internal IP addresses I'd like to be peered and it'd be really convenient to avoid explicitly keeping track of which internal IPs are in use.
2. Should a leader be elected for each cluster or is it expected that a single leader will be elected across all instances/regions/clusters?
3. Is this multi 3-node clusters setup the right approach for global redundancy?

**Typsense Version**: Latest
**OS**: Docker Image

**Comment by Bug-Reaper** [comment]
Appreciate the answer!

I don't think GoogleKubernetesEngine (GKE) supports clusters with nodes outside the designated cluster zone/region. Though I am open to suggestions for Kubernetes host providers with globally distributed single cluster options.

Had planned to put up a few clusters in different zones/regions but still on the same internal network such that they can all peer with each other. Even though nodes are spread across various Kubernetes clusters I guess you could still consider them a part of the same Typesense-DB-cluster in the sense all nodes would peer with each other.

----

A. I'd like to confirm only a single leader will ever be elected (regardless to the number of peers).
B. Is there a max number of peers?

**Comment by kishorenc** [comment]
Sorry, I missed replying to this issue.

A. Correct, only a single leader
B. No maximum number but since each write requires the majority of the node in the cluster to acknowledge it, we don't recommend adding more than 5 nodes. A 5 node cluster can tolerate 2 node failures which is sufficient resiliency even at scale.

**Comment by sandstrom** [comment]
Sorry for hijacking this thread, but if you want multi-region failover, wouldn't you need at least 7 nodes?

### With 5 nodes

Region1: 3 nodes
Region2: 2 nodes

*If region1 fails, there are only two nodes which isn't enough for majority in region2 to vote a new leader.*

### With 7 nodes

Region1: 4 nodes
Region2: 3 nodes
