### ISSUE TITLE
Account for word position in the search ranking

### ISSUE THREAD

**Issue by joker-777** [typesense/typesense#601]
Hi, I'm trying to develop a simple suggestion feature that I want to show to the user via autocomplete. I [created a small prototype](https://codesandbox.io/s/typesense-autocomplete-forked-cfimzy) to test it. Unfortunately, I found out that the terms are not shown in the order that I expected and I couldn't find a way to change the ranking order either. I'm aware of [this page](https://typesense.org/docs/guide/ranking-and-relevance.html) but I couldn't find out how to change priorities or add criteria that include the position of the word. Here is what I expected

search: "a"
 * **a** term
 * **a**nother term
 * term **a** with multiple **a**s but with less priority

But in my prototype, you can see that it doesn't show the results like this

<img src="https://user-images.githubusercontent.com/378859/170035648-c9800592-615f-45ba-abae-074f34c22f17.png" width="300" />

I expected to have the possibility to change the ranking criteria in a similar way then Algolia does

<img src="https://user-images.githubusercontent.com/378859/170035783-04ce52d3-6d14-41a4-b44d-34e2bb2d3625.png" width="300" />

**Comment by kishorenc** [comment]
Available in `0.23.1`. Word position in a field value can be used a ranking signal via the `prioritize_token_position` search parameter.
