### ISSUE TITLE
Filter not working properly

### ISSUE THREAD

**Issue by shyamvadaliya12** [typesense/typesense#605]
## Description

filter_by:[`dob:>${new Date().getTime()}`,"country:='US'"] Or filter_by:["dob:>1646418600","dob:<1646505000"]
In filter if we pass two feilds that time it is not working properly.

query:
client
        .collections("users")
        .documents()
        .search({
            q : "*",
            sort_by : 'dob:asc',
            filter_by:["dob:>1646418600","dob:<1646505000"]
        })
output:
![image](https://user-images.githubusercontent.com/73700344/171787697-38ce356a-d2e5-4294-9ab8-dc6f1359ced9.png)

## Expected Behavior
It should display the data where the field dob is between 3/5/2022 and 4/5/2022

## Actual Behavior

It is displaying all data of collection.

## Metadata

**Typsense Version**: 1.3.0

**Comment by shyamvadaliya12** [comment]
@kishorenc It is int64

**Comment by kishorenc** [comment]
Actually, the `["dob:>1646418600","dob:<1646505000"]` syntax is an OR and not an AND. If you want AND you need to do `dob: >X && dob:<Y`.

**Comment by shyamvadaliya12** [comment]
@kishorenc  I am still getting the same output

**Comment by kishorenc** [comment]
Can you post a small reproduceable dataset as well along with the query?

**Comment by kishorenc** [comment]
Please reopen if this is still an issue with a reproduceable data + query.
