### ISSUE TITLE
Counter mismatch between facets and number hits

### ISSUE THREAD

**Issue by zopyx** [typesense/typesense#610]
See screenshot. I see 3 items for `BlogEintrag` in the facets but 4 hits in the search result list. Where is the difference coming from?
![e4153dfb-efbb-4aaf-8730-bfc58fce4096](https://user-images.githubusercontent.com/594239/172102059-2c889c6b-1251-4d42-8034-98e558067cd4.png)

Tested with Typesense 0.22.1.

**Comment by jasonbosco** [comment]
@zopyx Could you try adding `exhaustive_search=true` as a search parameter?

**Comment by zopyx** [comment]
I can not reproduce the problem any more after recreating the collection and reindexing all content.
