### ISSUE TITLE
Seeing worse performance with queries with multiple words in complex scenario on 0.23

### ISSUE THREAD

**Issue by VicFleur** [typesense/typesense#611]
I'm testing Typesense ```0.23.0``` against ```0.22.2``` in a non-production environment.
Database size is 2492169 rows at the moment, with 25 fields (the queries use just 7 fields at the moment, but I see no noticeable difference in querying more or less fields). The dataset is messy (ie. multiple variations of the same tag, long titles, etc) but I have no control over it — I'm expecting it to grow to 16mln rows in the future and I'm worried about the performances.

Settings:
- ```query_by``` with custom ```query_by_weights```
- ```sort_by```: score:desc,_text_match(buckets: 24):desc (score is a precalculated int)
- ```num_typos```: 1
- ```typo_tokens_threshold```: 0
- ```drop_tokens_threshold```: 1
- ```per_page```: 24
- ```highlight_fields```: title

again, not seeing any noticeable difference by removing/altering any of the above. Not seeing any difference with using ```split_join_tokens``` or not. Also tried to reindex everything on a fresh new index, same results. 

Here's a table with times measured based on the number of results:

| Example query | Results | Time on 0.22.2 | Time on 0.23.0 |
| --- | ---: | ---: | ---: |
| Single word A | 1.400 | 7ms | **8ms** |
| Single word B | 7.000 | 15ms | **8ms** |
| Single word C | 791.600 | 223ms | **470ms** |
| Single word D | 1.100.000 | 564ms | **686ms** |
| Two words | 851.000 | 1300ms | **2445ms** |

The database is through Docker on a decent VPS with lots of headroom, 8 vcores, 32GB ram.
Can't share more details about the dataset publicly, but can share something in private if needed.

Thankyou!

**Comment by VicFleur** [comment]
thanks for the explanation!

"Two words" from the table above ranked number 9 from a sample of 250K live queries, from what I can gather it seems to be the toughest one to test as one of the words is also part of a group of 10 synonyms. That being said, 90+% of the queries are going to be faster than 10/20ms so any slowdown is unnoticeable at the moment.

Still, being a popular query, with two very common words (nothing to exclude unfortunately), I think it's fair to be used as a test and not just ignored.

I did another test, and at least in my case, synonyms have the biggest impact, here's a small summary:

| Example query | Results | Time | Results without synonyms | Time without synonyms |
| --- | --- | --- | --- | --- |
| Single word D | 1.100.000 | 686ms | 757.400 | 380ms |
| Two words | 851.000 | 2445ms | 819.500 | 1491ms |

(Single word D has 7 synonyms, the second word of Two words has 10 synonyms)

Considering that my public isn't interested in the vast majority of those 800K results, but I can't just cut items from the database due to the presence of lots of niche queries that wouldn't get any result — are there any strategies that could be implemented on my side to mitigate the slowness of the largest queries? ie. splitting items into tiers by score and then somehow querying the lower tiers only if not enough results were found in the top ones?

**Comment by kishorenc** [comment]
> are there any strategies that could be implemented on my side to mitigate the slowness of the largest queries? ie. splitting items into tiers by score and then somehow querying the lower tiers only if not enough results were found in the top ones?

Yes, if you can add a field to filter for higher tier records, then that will naturally reduce the total result set processed and will improve performance.

**Comment by VicFleur** [comment]
Thanks, that helped a bit.
Hope Typesense will get even faster in the future anyway!
