### ISSUE TITLE
Get all the facets without any search Result

### ISSUE THREAD

**Issue by dipankarmaikap** [typesense/typesense#612]
## Description

typesense shoud offer a way to get all the facets in the collection without any other search info.

With algolia we can do it like this

```js
index.search("", {facets: ["*"]})
```
## Usecases
Currently all the facets/filters gets removed if there is no data or after we check on some filters others/some gets removed but this is no a good behavior in all cases. If we have a way to get all the facets with how many hit/data each one have we can show all the filters always and disabled but show all the options if there is no match.

**Comment by OlehObodin** [comment]
I need this  feature too for dynamic creation of filters on storefront. Also filters depends on product variant fields which can be changing. So for now we have to make strict predefined values (size, color, model) whatever for each category.

**Comment by zergormagn** [comment]
It's possible to have dynamically created widgets based on initial search results (without dynamicwidgets) by hooking to the onrender event in Instant Search as TS sends all the facets available. But It's fairly difficult to code, also there is a heavy performance penalty especially with larger datasets.

**Comment by recervictory** [comment]
I am trying to implement Dynamic Widget from algolia but either it is not displayed or asking for `facet [*]`. I am really confused with the documentation.

**Comment by zergormagn** [comment]
From my understanding it won't work as you currently have to tell the TS server what facets you want.   So the only way to create dynamic like widgets/factes with TS is to save the dynamic facets in a named facet.  And then re-request the missing facets based on the hits received.  

The problem with this approach is that it's slow.   Although should work ok with few thousand items,

DyamicWidgets allows explicitly named facets and that also fails with the TS adapter, I'm not really sure why?

Think this should be set to higher priority:
Most of new Algolia examples now use dynamicwidgets. 
And more importantly it's a vital component for ecommerce stores.  Where one hit might have "color" another one could have "screen size" etc.  and there can be hundreds of such attributes which are impossible to define, or code efficiently at present.

**Comment by pixelkoduje** [comment]
I see that instead of the `"*" error`, it shows the error 'Field `name` is not marked as a guy in the schema.'
I using `const data = useDynamicWidgets({
     guys: ['*']
   })` in docker version 0.25.0.rc9
It's not finished, do I need to do something else to make it work?
I'm using react-instantsearch-hooks-web

**Comment by KULTI1995** [comment]
you can see it more easily. By adding "face_by":"*" to the query
I noticed that version 0.25.0.9rc was added 8 days ago, and you have made a lot of changes since then. Are you able to upload the version after new updates to Docker Hub? I will test this and let you know.

**Comment by kishorenc** [comment]
This is fixed in 0.25.x -- you can send `facet_by=*`.
