### ISSUE TITLE
possible to change data storage backend to redis?

### ISSUE THREAD

**Issue by hiqbn** [typesense/typesense#62]
possible to change data storage backend with redis connector?

would like the backend to be stored in https://github.com/yongman/tidis

**Comment by kishorenc** [comment]
No, this is not possible at the moment. Pluggable storage layer might be nice, but is not a priority unless more people request it.

**Comment by hiqbn** [comment]
would like to change it to redis how do i do that? any clues where i should be looking at?

**Comment by kishorenc** [comment]
Yes `store.h` is the abstraction for the storage layer. Unfortunately, it does leak some implementation details at the moment like the RocksDB iterator class etc.

**Comment by hiqbn** [comment]
can consolidate all the functions at store.h so next time we can just change the storage layer here?

**Comment by kishorenc** [comment]
Yes `store.h` should be the interface implemented by a storage engine. And `store.cpp` should contain all storage related logic for RocksDB. One can create similar sub-classes for other storage engines using the same interface and initialize correspondingly.

**Comment by hiqbn** [comment]
i dont know how to do this but can you do it? i can contribute by making small donations

just do the redis port without multi/exec will do

**Comment by kishorenc** [comment]
A generic storage interface will involve quite some refactoring and testing before it is ready. It might happen in future based on priority. May I understand the need for a Redis backed storage though? Maybe there is a way to achieve what you want in an alternative manner.

**Comment by hiqbn** [comment]
i have redis cluster and sentinel etc set up and it's more "distributed". can you use redis as backend and without the local memory overhead? the backend will be a redis cluster.

when do you think it can be done?

**Comment by kishorenc** [comment]
Typesense stores the indices in-memory, so even if a Redis backend is used, the searching would require the in-memory data structures. So you will still need the Typesense server to have high availability.

**Comment by hiqbn** [comment]
can you rewrite it for storing the indices in redis? i can make a small donation.
there's no redisearch alternative and if it's backed by redis, this will be the best available search backed by redis other than redisearch

**Comment by kishorenc** [comment]
I appreciate your offer, but unfortunately it's not practical to store the indices on Redis as Typesense depends on several custom in-memory data structures.
