### ISSUE TITLE
Document export: filter_by adds trailing newline char

### ISSUE THREAD

**Issue by brianweet** [typesense/typesense#622]
## Description

Given a collection with two documents, running an export without params gives me this:

`/collections/companies/documents/export`
```
{"id":"doc1"}\n
{"id":"doc2"}
```
When using a `filter_by` param, the last document has a newline char at the end, this is not expected.

## Steps to reproduce

Call `/collections/companies/documents/export?filter_by=id:[doc1]`

## Expected Behavior

```
{"id":"doc1"}
```

## Actual Behavior

```
{"id":"doc1"}\n
```

## Metadata

**Typsense Version**: v0.23.0

**OS**: docker

**Comment by jasonbosco** [comment]
v0.24 is now available with this fix.
