### ISSUE TITLE
Collection schema changes on its own

### ISSUE THREAD

**Issue by Awea** [typesense/typesense#624]
## Description

I have a collection that defines a field with `name: "foo", type: "auto", index: false` and it's the second time (over the last two months) that `index: false` suddenly becomes `index: true`. And I can't explain how since I'm running v0.22 and schema can't be updated.  

## Steps to reproduce

This time it happens after a restart of the container but 🤷

## Metadata

**Typsense Version**: 0.22

**OS**: ubuntu / docker

**Comment by kishorenc** [comment]
@Awea We've fixed this issue on v0.23.0. The `index: false` setting was not getting persisted on restart. This has been fixed: can you please upgrade and see if that helps?

**Comment by Awea** [comment]
@maximevalette That's great, thanks 🙇 I'll update right away!
