### ISSUE TITLE
AWS App Runner Service Fail

### ISSUE THREAD

**Issue by francesco-hayes** [typesense/typesense#630]
## Description

I am trying to deploy "typesense/typesense:0.23.0" docker image to AWS App Runner via ECR. It is currently the only deployment service we have access to for this project. Do I miss understand the use case of AWS App Runner?

This is my first attempt at using AWS Deployment Services so any help and or guidance would be appreciated. Thank you!

## Steps to reproduce

Deploy the docker container to ECR and connect it to the App Runner Service when prompted. 

![step-1](https://user-images.githubusercontent.com/44263980/174844199-5b71e371-1087-4ade-8b76-7ee0105d9ff1.png)
![step-2](https://user-images.githubusercontent.com/44263980/174844218-654cde1b-f51b-4553-898d-3a95d2106eb6.png)
![report](https://user-images.githubusercontent.com/44263980/174844229-5107a073-457d-4551-a72b-f18abf86be4a.png)

## Expected Behavior

The expected behavior is a successful deployment to AWS App Runner.

## Actual Behavior

I currently see a failed service deployment. Typesense will fail after each "health check" on the defined port once the image is pulled and begins deployment.

I have tried setting different environment variables in hopes I might have missed something for the docker image to deploy. However, all that has left me with the same outcome.

## Metadata

**Typsense Version**: 0.23.0

**OS**: Docker

**Comment by jasonbosco** [comment]
That's right. Serverless models typically don't allow access to disk, and can also be interrupted by management system, which doesn't work with Typesense's in-memory + disk as backup model.

**Comment by francesco-hayes** [comment]
Awesome, thank you for the prompt response.
