### ISSUE TITLE
Return index of the given word

### ISSUE THREAD

**Issue by timy-16** [typesense/typesense#636]
Hello!
I'd like to know if there's a way to somehow  get the index of the word along with other things (snippet, highlight, etc)

Let's say I have a description.
"This cake is **very** tasty, but **very** expensive"

When I search for **"very"** I want to get.
_(Starting from 1)_

**Occurrences= [4,7]**

And is it also possible to do the same but with phrases?

For example, the query is "very tasty". And it should return the index of the first word in a given phrase, or in other words, the start of the phrase.

I was thinking, if there's no such way, to do the search myself, after I get the results.
The way it would look like is this:
When typesense returns the result, it highlights the query and wraps it in a tag. And with this, I could simply loop through the description and count each word until I come across the tag and then return the index myself. But it looks like too much work, especially if the text is 10000 words long or even more.

It would be really nice if someone could help me out with this)

**Comment by kishorenc** [comment]
@timy-16 While Typesense does not return the positions of highlighted words, we do return the actual words in an array in the response, like this:

```
{
          "field": "company_name",
          "snippet": "<mark>Stark</mark> Industries",
          "matched_tokens": ["Stark"]
}
```

You can use the strings in `matched_tokens` to find their positions in the text.

**Comment by timy-16** [comment]
@kishorenc Thank you for your response!
A few more questions, is it possible to search for exact expression?
What am I going to get as a response? Is the whole expression going to be wrapped in html tag?
For example, if I have:
Description: "This cake is delicious"
And I search for "cake is delicious" 
Is the response going to be like:
Description:
 "This <mark>cake is delicious<\mark>"?

**Comment by kishorenc** [comment]
1. Search for exact phrases by wrapping phrase in double quote, e.g. `"exact matching phrase"`.
2. Typesense wraps each individual word with a `<mark>` tag, regardless of whether it's a phrase query or a regular query.

**Comment by timy-16** [comment]
@kishorenc Thanks a lot. One more question, if you don't mind, is there a way to somehow  store all collections, even when PC is down (I'm using self host), or do I have to always create new collection, add documents to it whenever I reboot my PC?

**Comment by timy-16** [comment]
@kishorenc if it is really so, why am I receiving an error 404 when I try to access the collection that was previously created?
**Input**
`response = client.collections['videos'].retrieve()`
**Output**
`typesense.exceptions.ObjectNotFound: [Errno 404] Not Found`

**Comment by kishorenc** [comment]
Did you `/tmp` as your data directory? That would clear up on reboot. Otherwise data is persisted.

**Comment by timy-16** [comment]
@kishorenc Oh, silly me. Thank you very much for your help and for the amazing product that you've all made! Great work!
