### ISSUE TITLE
Highlights don't show up for large fields with infix turned on

### ISSUE THREAD

**Issue by yekta** [typesense/typesense#640]
## Description

I have documents with large `plaintext` fields (15-20kb). If I set `infix` param to `always` when doing a search, highlights don't show up. When I set `infix` to `off`, highlights do show up.

## Steps to reproduce

For now I don't have a fast reproduction example but here is the  pseudo code with the params:

This is the one that doesn't return highlights for `plaintext` (which is a 15-20kb field), it does for `title` though.
```
const query_by = ['title', 'plaintext'];
const infix = ['always', 'always'];
const include_fields = ['title','plaintext'];
```

This is the one that returns highlights for both fields correctly:
```
const query_by = ['title', 'plaintext'];
const infix = ['always', 'off'];
const include_fields = ['title','plaintext'];
```

## Expected Behavior

I expect highlights to be returned regardless of the size of the field and infix being turned on.

## Actual Behavior

Highlights are not returned for the `plaintext` field (15-20kb field) in the example when infix is turned on. They are returned for the `title` field (which is a very small field), with infix turned on.

## Metadata

**Typsense Version**: v0.23.0

**OS**: Ubuntu 20.04.4 lts

**Comment by kishorenc** [comment]
The infix search feature is not meant for searching on long text strings. Please see the discussion here: https://github.com/typesense/typesense/issues/559#issuecomment-1096599358
