### ISSUE TITLE
Exact match is not working properly 

### ISSUE THREAD

**Issue by timy-16** [typesense/typesense#641]
Hello!
So I tried to search for exact match by wrapping the query in double quotes, but it didn't work quite well.
When I searched for `given choice`, it wasn't supposed to return or highlight anything, but it did. It gave me this result

`<mark>given<\mark> the <mark>choice<\mark>`

. Then I found out that someone else had this issue, tried the solution(pulled version 0.23.0.rc47), still the same output(((
Also, when I search for `"real"` it highlights `"really"`too.
Is there a way to search only for the exact match, and return nothing when it could not find any?

**Comment by kishorenc** [comment]
0.23.0 is the latest stable version. Did you try in that?

**Comment by timy-16** [comment]
@kishorenc that was the first version I tried(((

**Comment by kishorenc** [comment]
@timy-16 

I created a simple collection with a `title` field and indexed two titles: `given the choice` and `was really hot`. Then when i query for `given choice` and `real`, no results were found for either query.

I think you might be having trouble encoding the `"`? If you can post a fully reproduceable code snippet that show cases the problem, I can troubleshoot. Many people are already using phrase search on production, so I think the issue is something that's not generic.

**Comment by timy-16** [comment]
@kishorenc 
This is the code:
```
def search(expression):
    response = client.collections['text_collection'].documents.search({
        'q': "real",
        'query_by': 'text',
        "drop_tokens_threshold": 0,
        'highlight_start_tag': "<!!!FOUND!!!>",
        'highlight_end_tag': "</!!!FOUND!!!>"
    })
    return response
```

This is what I get:
```
{'facet_counts': [], 'found': 1, 'hits': [{'document': {'id': '0', 'text': 'given the choice that many people will become really upset about this'}, 'highlights': [{'field': 'text', 'matched_tokens': ['real'], 'snippet': 'given the choice that many people will become <!!!FOUND!!!>real</!!!FOUND!!!>ly upset about this'}], 'text_match': 282583051272193}], 'out_of': 1, 'page': 1, 'request_params': {'collection_name': 'text_collection', 'per_page': 10, 'q': 'real'}, 'search_cutoff': False, 'search_time_ms': 0}
``

**Comment by kishorenc** [comment]
Is it possible for you to post a fully runnable example that includes collection creation, indexing a sample doc and then the query above?

**Comment by timy-16** [comment]
@kishorenc 
```
import os
import sys
import typesense

curr_dir = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(1, os.path.abspath(os.path.join(curr_dir, os.pardir)))


client = typesense.Client({
    'api_key': 'some_api_ley',
    'nodes': [{
        'host': 'localhost',
        'port': '8108',
        'protocol': 'http'
    }],
    'connection_timeout_seconds': 5
})

test_schema = {
    'name': 'text_collection',
    'fields': [
        {
            'name': 'text',
            'type': 'string'
        }
    ]
}
test_sample = {
    'text': 'given the choice that many people will become really upset about this'
}
response = client.collections.create(test_schema)
response = client.collections['text_collection'].documents.create(test_sample)


def search(expression):
    response = client.collections['text_collection'].documents.search({
        'q': expression,
        'query_by': 'text',
        "drop_tokens_threshold": 0,
        'highlight_start_tag': "<!!!FOUND!!!>",
        'highlight_end_tag': "</!!!FOUND!!!>"
    })
    return response


print(search("real"))
```
Hope this helps!

**Comment by kishorenc** [comment]
This will send the query string without the double quotes needed for phrase search:

```
'q': expression,
```

Instead do this:

```
'q': '"' + expression + '"',
```

**Comment by timy-16** [comment]
@kishorenc Thank you once again!  Everything works fine now.
