### ISSUE TITLE
Geo search can't find the same document after increasing the search area

### ISSUE THREAD

**Issue by andreww2012** [typesense/typesense#648]
## Description

When searching within a polygon, after increasing the search area, it is possible for TypeSense to return less documents than it did for the smaller area.

## Steps to reproduce

```sh
docker volume create typesense-geosearch-bug

docker run -p 8111:8108 -v typesense-geosearch-bug:/data --name typesense-geosearch-bug -itd typesense/typesense:0.23.1 --data-dir /data --api-key=123

curl -L -X POST 'http://localhost:8111/collections' \
  -H 'X-TYPESENSE-API-KEY: 123' \
  -H 'Content-Type: application/json' \
  --data-raw '{
    "name": "locations",
    "fields": [
        {"name": "loc", "type": "geopoint"}
      ]
  }'

curl -L -X POST 'http://localhost:8111/collections/locations/documents' \
  -H 'X-TYPESENSE-API-KEY: 123' \
  -H 'Content-Type: application/json' \
  --data-raw '{
    "id": "a",
    "loc": [60, -48]
  }'
```

### First query

```sh
# The value that will be changed in the next query
#       v         v
# 60, -117, 23, -117, 23, 34, 60, 34
curl -L -X GET 'http://localhost:8111/collections/locations/documents/search?q=*&filter_by=loc:(60,%20-117,%2023,%20-117,%2023,%2034,%2060,%2034)' -H 'X-TYPESENSE-API-KEY: 123'
```

```json
{
  "facet_counts": [],
  "found": 1,
  "hits": [
    {
      "document": {
        "id": "a",
        "loc": [
          60,
          -48
        ]
      },
      "highlights": [],
      "text_match": 100
    }
  ],
  "out_of": 1,
  "page": 1,
  "request_params": {
    "collection_name": "locations",
    "per_page": 10,
    "q": "*"
  },
  "search_cutoff": false,
  "search_time_ms": 5
}
```

### Second query

```sh
# Decreased longitude by 1:
#       v         v
# 60, -118, 23, -118, 23, 34, 60, 34
curl -L -X GET 'http://localhost:8111/collections/locations/documents/search?q=*&filter_by=loc:(60,%20-118,%2023,%20-118,%2023,%2034,%2060,%2034)' -H 'X-TYPESENSE-API-KEY: 123'
```

```json
{
  "facet_counts": [],
  "found": 0,
  "hits": [],
  "out_of": 1,
  "page": 1,
  "request_params": {
    "collection_name": "locations",
    "per_page": 10,
    "q": "*"
  },
  "search_cutoff": false,
  "search_time_ms": 4
}
```

## Expected Behavior

Correctly return all the documents with the points contained within a given polygon.

## Metadata

**Typesense Version**: 0.23.1

**OS**: Windows 10 19043.1165

**Comment by andreww2012** [comment]
May I also leave a geo search related suggestion here?
Currently, if the field has a type of `geopoint[]`, searching within a polygon on that field would return a document if *any* of the points is contained within a polygon. Would it be possible to add an option to make the criterion stricter, that is, "*all* the points must be inside the polygon"?
And thank you for such an excellent library!

**Comment by kishorenc** [comment]
This is really odd, I'm able to reproduce the issue on a smaller issue on the library we are using for geo encoding and searching and I've asked the authors for their inputs.

> Would it be possible to add an option to make the criterion stricter, that is, "all the points must be inside the polygon"?

This is a good suggestion. Can you please create another issue for tracking this? We will add to our roadmap.

**Comment by andreww2012** [comment]
Thank you. Did that.

**Comment by kishorenc** [comment]
@andreww2012 

I figured out what's happening. If you're using Google maps to project the points, that doesn't represent the points visually correctly in zoomed out mode because of the mercator projection. The actual projection looks different on a spherical surface.

With longitude as `-117` that point falls inside: http://www.gcmap.com/mapui?P=60N+117W+-+60N+34E%2C+23N+117W+-+23N+34E%2C+60N+48W&MS=wls&DU=mi

And, you can see how the point falls just outside the zone when `60, -118, 23, -118, 23, 34, 60, 34` is used: http://www.gcmap.com/mapui?P=60N+118W+-+60N+34E%2C+23N+118W+-+23N+34E%2C+60N+48W&MS=wls&DU=mi

**Comment by andreww2012** [comment]
Thank you very much for the explanation!

In my use case, I simply use geo search to check if a number of points all lie inside the rectangle, and their coordinates are just projected from cartesian plane coordinates into a `[lat, lng]` pair. Well, apparently that's a wrong use case for a geo search, and I guess I should resort to using coordinates comparison to get the desired results.

It would be awesome if the geo search could be described in more details in the docs, like what its limitations/what use cases are wrong and how exactly it works with `geopoint[]` fields.

**Comment by kishorenc** [comment]
> their coordinates are just projected from cartesian plane coordinates into a [lat, lng] pair. 

I don't think you can project cartesian plane coordinates into geo pairs like that. What value do these cartesian coordinates represent? Our geo search implementation is very much optimized for searching on lat/lng -- that's why we don't call it as a generic N-dimensional search. We might have to build a non-geo multi-dimension search feature to support this use case. I can comment further if you can tell me what type of values you are storing and searching on.

**Comment by kishorenc** [comment]
The geo search library we use accounts for the spherical surface of the Earth. If the cartesian plane co-ordinates can be represented into lat/lng that is confined to a very small geographical area, perhaps the search would be accurate enough, but when you represent the points across such large distances as given here, the curvature of the earth is going to make things difficult.

In short, we don't have a way to easily index and search cartesian coordinates: what we have is meant for real earth geo locations.

**Comment by andreww2012** [comment]
Thank you for your time and clarification of things.

I've tried to confine the Cartesian coordinates into a smaller area, and it indeed produced the better results, but in the end I've switched to using coordinates comparison, and it seems like it's doing the job because I wouldn't want to risk to suddenly get wrong results again.

It also seems #652 is no longer relevant for me.
