### ISSUE TITLE
Exact matching marks all words from the query in a text

### ISSUE THREAD

**Issue by timy-16** [typesense/typesense#650]
Hello!

Is there a way to only wrap words in 
`['hits'][0]['highlights'][0]['value']`
that exactly match the query? The snippet shows you that there's an exact match, but it's a bit hard to find where exactly the match is. 
I was hoping to loop through the text and get the index of the word that is wrapped in tags, but there are some other wrapped words that are irrelevant to the query.

For example, when I search for `"in the past"`, I get all "the", "in", "past" highlighted whenever they occur in the text, even if they are far away from each other.
I may have  text highlighted like this:
`Tom is buying a house. He went to <mark>the<mark/> house, <mark>in</mark> which he saw his <mark>past</mark> self.`

Maybe there's an option to highlight only exact matches, or better yet get the index of the matched token in a full text, so that I don't have to do it myself😁

**Comment by kishorenc** [comment]
We don't have a way to distinguish exact matches in highlights easily. One work around I can think of is to use the `matched_tokens` array in the highlight response and to look them up in the actual text to see if they occur right next to each other.

**Comment by timy-16** [comment]
@kishorenc Ok, thank you
