### ISSUE TITLE
Query by text and url fields - token_separators

### ISSUE THREAD

**Issue by mvuidev** [typesense/typesense#651]
## Description

Hi,
I need to search in multiple string fields, including one "url" field.
Example : searching "abcd.com" should return the document with url "https://www.abcd.com/x/y/z".
I have done that using the "token_separators" parameter: "token_separators" : ["."], works great.

The problem is that all other documents containing "com" in their url field, or in which other fields contains the "com" word are returned.

Is there any way to prevent that ? Maybe ignoring words containing less than 4 chars from the search ? (but I didn't see this kind of parameter in the doc)

But maybe my use case is too specific.

## Metadata

**Typsense Version**: 0.23.0

**OS**: Debian 11

**Comment by kishorenc** [comment]
> The problem is that all other documents containing "com" in their url field, or in which other fields contains the "com" word are returned.

You can disable dropping of tokens from the query by setting the parameter `drop_tokens_threshold=0` . This will ensure that `com` is not partially matched.

**Comment by mvuidev** [comment]
Hey, thanks for the answer.
Unfortunately i can't do that cause it's not about searching only urls, so i have to keep typo tolerance.

The only way i think would be a new parameter allowing to ignore
- the words with a length < x 
- or a list of words (like stop words on Meilisearch)

in the search query.

Have you ever considered implementing that ?

**Comment by kishorenc** [comment]
We don't have a stop words feature though that's on our long term road map.

Btw, setting drop tokens threshold to zero does not disable typo tolerance. That's a different parameter.

**Comment by mvuidev** [comment]
My bad, i was thinking about "typo tokens threshold"...
So yes, i did already use drop tokens threshold but it didn't fit my particular needs, but for this use case it's indeed the solution.

Thank you !
