### ISSUE TITLE
Highlighting for infix search that matched items in searchbox only

### ISSUE THREAD

**Issue by khaishin1999** [typesense/typesense#654]
## Description

I am currently working on an application that uses Typesense as a search engine together with Algolia React InstantSearch.

While implementing the highlighting feature from Algolia for some infix search, I realised that instead of highlighting the specific characters that matched the items being typed in the search box, the whole item in the result field will be highlighted.

When I checked on the documentation provided by Algolia, under this link [https://www.algolia.com/doc/api-reference/api-parameters/restrictHighlightAndSnippetArrays/](url), they provided a parameter to restrict highlighting to matched items only.

May I know, is there any ways to set the parameter in Typesense? Or is there any other ways to configure the highlighting in Typesense? Please advise, thank you.

## Expected Behavior

 When infix search is turned on, only specific texts that matched texts in search box being highlighted.

## Actual Behavior

When infix search is turned on and some texts are typed in search box, the whole item in the result field will be highlighted.

## Metadata

**Typsense Version**: 0.23.0

**OS**: Windows 10

**Comment by kishorenc** [comment]
@khaishin1999 

Typesense will highlight the word in the field which matches with the search query during infix searching. Can you post a screenshot that shows an example of the whole item getting highlighted?

**Comment by khaishin1999** [comment]
<img width="461" alt="image" src="https://user-images.githubusercontent.com/109172845/178699015-d5b45a9e-8e7e-4b70-9a1e-4bf32d9ab030.png">

**Comment by kishorenc** [comment]
Typesense indexes `MANOHAR_MURADI` as `MANOHARDMURADI` because we ignore symbols like `_` by default. That's why the whole word gets highlighted. If you want to treat the `_` as a separator, please use `token_separators` configuration during collection creation. See this example for handling hyphens in phone numbers here for reference: https://typesense.org/docs/guide/tips-for-searching-common-types-of-data.html#phone-numbers

**Comment by khaishin1999** [comment]
Thanks for the info, Kishore.
