### ISSUE TITLE
Can't run typesense 0.23.1 docker image on M1 Mac

### ISSUE THREAD

**Issue by bbedward** [typesense/typesense#656]
## Description

M1 Macbook Pro, cannot run the `typesense/typesense:0.23.1` image - using docker 4.10.1'

This is a new problem with 0.23.1, the 0.23.0 image works as expected.

## Steps to reproduce

Attempt to start the image:

```
docker run typesense/typesense:0.23.1                                                                                                                                                                         [9:50:11]
/opt/typesense-server: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /opt/typesense-server)
```

## Expected Behavior

Except the typesense server to run

## Actual Behavior

Typesense crashes with the GLIBC error.

## Metadata

**Typsense Version**: 0.23.1

**OS**: MacOS 12.4, M1 max

**Comment by kishorenc** [comment]
I've pushed out a fix for this: can you try to remove the image via `docker rmi typesense/typesense:0.23.1` and then pull it and run it again?
