### ISSUE TITLE
How to retrieve available facet/filter options

### ISSUE THREAD

**Issue by jsinhSolanki** [typesense/typesense#66]
Hello,
First of all amazing work. I really appreciate your hard work. I would like to know how can I get info about how many filter/facet left after searched query.
Let me explain by steps:
Let's say I have eCommerce store and we provide search, product type filter, brand facet etc. Type filter can have Mobile, Laptop, PC, Furniture, Food etc. And facet will have brand names.

Now when someone search apple, I want to remove Furniture & food from my filters(based upon my search filter). Currently I can't find any way to do this. Same goes for facets(If I filter mobile How can I get list of available brands from queried data). Because If I hard-code all filters and If they are not available upon certain search query but still visible in front-end than that will be unexpected behaviour(clicking on filter won't affect at all).

Something like this:
![algolia-filter-auto-hide](https://user-images.githubusercontent.com/31243533/59146693-fe2c4480-8a0e-11e9-9279-1db081665fcf.gif)

It will be plus if I can also show how much data/item/product each facet/filter have.
![algolia-facet](https://user-images.githubusercontent.com/31243533/59146638-544cb800-8a0e-11e9-99b2-6aeb8e2ba5ca.png)

## Metadata

**Typsense Version**: 0.10.0

**OS**: Ubuntu

**Language**: Python

**Comment by kishorenc** [comment]
@jsinhSolanki 

> I want to remove Furniture & food from my filters(based upon my search filter). 

To filter without a specific item, you will remove that item from the filter items and run the filter again. For example, let's say you are filtering with `product_type: [X, Y, Z]` and now want to filter without `Y`, then you just do `product_type: [X, Z]`.

> If I filter mobile How can I get list of available brands from queried data
> It will be plus if I can also show how much data/item/product each facet/filter have

For this you can use the `facet_by` option. See the description for the `facet_by` argument [here](https://typesense.org/0.10.0/api/#search-collection). In this case, you will do something like:

```
client.collections['products'].documents.search({
    'q': 'apple',
    'query_by': 'title, product_type, brand',
    'filter_by': '[product_type: mobile, computer, accessories]'
    'facet_by': 'brand, product_type'
})
```

This would return the brands and product types present in the search results, along with their respective counts. Check the `facet_counts` field in the response to get those values.

**Comment by jsinhSolanki** [comment]
Hello @kishorenc,

Thanks for the response. I am sorry if I was confusing.
Your both answers are correct and I have completely read your docs.

Let me explain what I am building. I have products data and initially, I use `'q' : '*'` which gives me all the results. Along with this I also want to give users ability to filter. e.g. `Categories`

Now the problem is I want list of these categories **dynamically**. This means I want to **get categories from search result** I already have(I don't want to hardcode categories like [x,y,z]). If I have 100 items then I want list of unique categories from that 100 items' data.
e.g. Below is unique categories of 32 items which are dynamic. I don't want to hardcode like [html, wordpress, jumla,.....]
![algolia-facet](https://user-images.githubusercontent.com/31243533/59187275-ba624800-8b92-11e9-82aa-24f20faaf078.png)


Because initially I am getting all data using `'q' : '*'`, I can loop through items and get unique categories but it only gives me categories of first ten items due to pagination.
So, my question is how can I get list of categories from all records. This goes same for facets.

**Comment by kishorenc** [comment]
Using `facet_by` is the correct way to enumerate the unique categories present in a search result. However, there is a limitation:

> but it only gives me categories of first ten items due to pagination

Currently, the counts returned by the `facet_by` response is limited to the top 10 frequently occurring entities. That's the reason why you see only 10 categories being returned. 

I will work on making the number of facet counts being returned as a configurable value. I think it would still be a good idea to have some kind of upper limit though. For e.g. there is no point listing 100+ categories on the sidebar -- nobody would be able to browse though so many.

**Comment by jsinhSolanki** [comment]
That's great. I will wait for the update.
Thanks

**Comment by kishorenc** [comment]
@jsinhSolanki Here's a [pre-release build `10.0.1-alpha`](https://dl.typesense.org/releases/typesense-server-0.10.1-alpha-linux-amd64.tar.gz) that increases the number of facets returned to the top 100 frequently occurring values.

This change will eventually flow into the formal `10.0.1` release.

**Comment by jsinhSolanki** [comment]
@kishorenc,
Thank you so much, buddy.

**Comment by lilouartz** [comment]
How do I return all facets? i.e. even those that had 0 matches
