### ISSUE TITLE
Possible to restrict search based on value with the Firebase extension?

### ISSUE THREAD

**Issue by tom43983** [typesense/typesense#662]
## Description

Hi! I am considering using Typesense with the Firebase extension, for a Firestore app. I would need to restrict the search results so that each user of my app only sees the documents related to their account. Is this possible natively with the Firebase extension? If not, what would be the easiest way to achieve this? Thanks!

## Metadata

**Typsense Version**:

**OS**:

**Comment by jasonbosco** [comment]
You want to add a user_id or account_id field to each record, and then you'll be able to use the Scoped Search API key feature to create API keys that only have access to particular records: https://typesense.org/docs/0.23.1/api/api-keys.html#generate-scoped-search-key

**Comment by jasonbosco** [comment]
You would have to generate scoped API keys in code.
