### ISSUE TITLE
Max search query length in TypeSense

### ISSUE THREAD

**Issue by bonzeu** [typesense/typesense#663]
In Algolia maximum number of characters per query is 512 . If a search query is longer, the API returns an error.

What is the situation with the search query length in TypeSense? Thanks

**Comment by kishorenc** [comment]
We don't have a limit but only the first 10 words in the query are used for computing some parts of the text matching score like proximity of tokens in the text etc. Also the amount of fuzziness in the long queries are limited so while exact searches will work fine, fuzzy searches are limited. 

Let us know if you run into any issues!

**Comment by bonzeu** [comment]
Ok, thanks!
