### ISSUE TITLE
Typesense doesn't find all documents

### ISSUE THREAD

**Issue by frodik** [typesense/typesense#669]
## Description

I have typesense server running and working. However I have found strange behaviour. There are documents in index with string column called "product_number". And there are product numbers in format "BKP001", "BKP002", .... "BKP999". There is 60 such documents.

However, when I query typesense and search for "BKP", it finds only 4 random matching documents. Strange is that if I do more specific search for "BKP01", it returns 4 documents "BKP010", "BKP011", "BKP012" and "BKP013".

And when I search for "BKP03" then it returns 4 documents "BKP031", "BKP032", "BKP033" and "BKP034". So it is clear that all the documents are correctly in index.

What could be the reason why it doesn't find all the documents ?

**Comment by jasonbosco** [comment]
I just responded to your same question on StackOverflow :)
