### ISSUE TITLE
How to update document

### ISSUE THREAD

**Issue by jsinhSolanki** [typesense/typesense#67]
Hello,
Is there any way I can edit my document??

**Comment by kishorenc** [comment]
No, you will just delete it and index it again.

**Comment by jsinhSolanki** [comment]
Hello @kishorenc,
Thanks for your reply. I just want to confirm that should I look for updates for improvement like single field edit or this all we have for document modification.
~ Thanks

**Comment by kishorenc** [comment]
We might add an update option in future. However, given the scope of work and design needed for that, it needs to be prioritized with other planned features.

**Comment by abhalodia** [comment]
I would like to upvote this enhancement. If you are trying to create a shopping experience where you give customers ability to see quantity left vs sold or customers who added it to the cart. It would be great if you can just update attribute on document rather than deleting and recreating it. Even ability to overwrite works too. There is always a small chance of missing the same document in search result between delete --> recreate.

**Comment by goliatone** [comment]
Just to clarify, you actually have to retrieve the document first and if it exists then delete it otherwise you get an error. Seems far from optimal when you have to constantly (re)index thousands of documents.
Also, it would be very helpful to include this in the documentation

**Comment by kishorenc** [comment]
Updates will be the number one priority feature for the release after 0.15 -- 0.15 will be released in the next week.

**Comment by abhalodia** [comment]
@kishorenc is there a newsletter or any announcement system you guys that we can subscribe to

**Comment by kishorenc** [comment]
@abhalodia 

If you're looking for release updates, you can subscribe to Github notifications -- you will get an email for new releases. You can also follow the updates on [Twitter](https://twitter.com/typesense). I also generally post a comment on all relevant Github issues when a particular feature is available as part of a new release.

**Comment by mubibil** [comment]
@kishorenc 
Hi, any progress on this?

**Comment by kishorenc** [comment]
@mubibil Yes, quite close to getting this out as part of next release (~ week away).

**Comment by kishorenc** [comment]
Alright, updates are finally available as part of v0.16.0 just released 🎉 

https://typesense.org/docs/0.16.0/api/#update-document

We've also added upsert support. You can update and upsert both at a per-document level or via imports (bulk operation).

**Comment by OmkarRatnaparkhi** [comment]
I don't want to update whole document, can we just update only single or any particular field of document of typesense.

**Comment by kishorenc** [comment]
@OmkarRatnaparkhi Yes, you can use the `PATCH` operation: https://typesense.org/docs/0.23.1/api/documents.html#update-a-document
