### ISSUE TITLE
import and search are  slow?

### ISSUE THREAD

**Issue by viweei** [typesense/typesense#671]
## Description

I have 6 dataes.  when importing and querying CPU usage 100%

![1658486099717](https://user-images.githubusercontent.com/1762036/180422078-f7e81421-84f0-41d9-bd9f-dff4933f08eb.png)

## Steps to reproduce

1. first, I started docker of typesense.
```shell
  docker run -d \
  --name typesense \
  -p 8108:8108 \
  -v /tmp/data:/data \
  typesense/typesense:0.22.2 \
  --data-dir=/data \
  --api-key=Hu52dwsas2AdxdE \
  --enable-cors
```

2. I created a collection, it was success. 
```json
{
  "name": "file", 
  "fields": [
    { "name": "id", "type": "string" },
    { "name": "hash", "type": "string" },
    { "name": "original", "type": "string", "locale": "zh" },
    { "name": "type", "type": "string", "facet": true },
    { "name": "content", "type": "string", "locale": "zh" },
    { "name": "remark", "type": "string", "locale": "zh" },
    { "name": "size", "type": "int64" },
    { "name": "tags", "type": "string[]" },
    { "name": "owner", "type": "string" },
    { "name": "create_at", "type": "int64" }
  ],
  "default_sorting_field": "create_at"
}
```

3. import data
[data.zip](https://github.com/typesense/typesense/files/9167039/data.zip)

code like below.  it successed too.
```js
import fs from "fs";
import typesense from "typesense";

const client = new typesense.Client({
  nodes: [
    {
      host: "localhost",
      port: 8108,
      protocol: "http",
    },
  ],
  apiKey: "Hu52dwsas2AdxdE",
  connectionTimeoutSeconds: 2,
  cacheSearchResultsForSeconds: 2 * 60,
});

async function main() {
  const data = fs.readFileSync("data.jsonl");
  client.collections("file").documents().import(data, { action: "create" });
}

main();
```

4. I used `typesense-instantsearch-adapter`  and `algoliasearch` to search but always timeout. I check the resource manager, and the CPU usage is 100%. code like below.
```jsx

import algoliasearch from "algoliasearch/lite";
import TypesenseInstantsearchAdapter from "typesense-instantsearch-adapter";
import { Hits, InstantSearch, SearchBox } from "react-instantsearch-dom";

const typesenseAdapter = new TypesenseInstantsearchAdapter({
  server: {
    nodes: [
      {
        host: "localhost",
        port: 8108,
        protocol: "http",
      },
    ],
    apiKey: "Hu52dwsas2AdxdE",
    // connectionTimeoutSeconds: 2,
    // cacheSearchResultsForSeconds: 2 * 60, 
  },
  additionalSearchParameters: {
    query_by: "original,content,remark",
  },
});

const App = () => (
  <div className="App">
    <InstantSearch
      indexName="file"
      searchClient={typesenseAdapter.searchClient}
    >
      <SearchBox />
      <Hits />
    </InstantSearch>
  </div>
);

export default App;
```

## Expected Behavior

It can quickly return results.

## Actual Behavior

always timeout and slowly.

**Typsense Version**:

typesense/typesense   0.22.2

**OS**:

window 10 19044.1826 
Docker version 20.10.17, build 100c701
WSL Debian GNU/Linux 11 (bullseye)

**Comment by kishorenc** [comment]
@viweei 

I was able to index the documents and query them locally using `curl` fast without any issues. Have you tried directly making search request using `curl` or any of our language clients? Is it still slow when you do that. E.g. query that I made:

```
http://localhost:8108/collections/file/documents/search?q=服务协议&query_by=content&x-typesense-api-key=abcd
```

Also, it is better to split the documents into smaller chunks and indexing them as individual documents. Then, during search, you can do a "group_by" on a "document_id" field so that multiple matched sections from within a single document can be shown together in the results. This will improve speed more.

**Comment by kishorenc** [comment]
I tested this on Mac on v0.23.1. Docker also worked fine. I don't know if it could be a Windows/WSL issue.

**Comment by viweei** [comment]
Thanks for your reply.  @kishorenc 
I tried change system to Debian but still slowly, even timeout when imported data. 
I think one of data is too big. according to your suggestion, I cut the data into mutiple pieces then group by hash. It worked~ Thank you agian.
