### ISSUE TITLE
Increase hits limit to 500/1000

### ISSUE THREAD

**Issue by paulsUsername** [typesense/typesense#672]
Would be a really great feature to be able to bring the hits results up to a max 500 or 1000 instead of 250.

Is that possible?

**Comment by kishorenc** [comment]
The reason we restrict it to 250 results is that as a search engine Typesense's goal is to to provide relevant results for a query, so the datastructures under the hood are highly optimized for that. 250 is a sweet spot that we found to balance performance with use. 

Having said that you _can_ fetch past the 250 results, but have to paginate and it could also be slower. You can issue a multi-search query where you can send N requests each doing page=1, page=2, and so on so all pages are fetched at one go and you can have 500-1000 results as you seek.

**Comment by boldtrn** [comment]
Wouldn't this require to know before requesting how many search results there are? Or if there are 250 results returned I would have to send a request for page 2. If that returns 250, I have to request page 3, ... 

Furthermore (and I haven't tested this, so I might be wrong), I had the feeling that for area searches without an enforced order, the order of results was not fixed, so for pagination I would have to add an order as well?
