### ISSUE TITLE
Doing an update in place crashed Typesense

### ISSUE THREAD

**Issue by sergeypodlazov** [typesense/typesense#674]
## Description

When I performed an in-place update deleting and recreating a field in an index, the server crashed.

## Steps to reproduce

Schema:

{
  "name": "outfits",
  "fields": [
    {
      "name": "product_ids",
      "type": "string[]",
      "facet": false,
      "optional": false,
      "index": true
    },
    {
      "name": "product_names",
      "type": "string[]",
      "facet": false,
      "optional": false,
      "index": true
    },
    {
      "name": "product_colors",
      "type": "string[]",
      "facet": true,
      "optional": true,
      "index": true
    },
    {
      "name": "product_categories",
      "type": "string[]",
      "facet": true,
      "optional": true,
      "index": true
    },
    {
      "name": "product_brands",
      "type": "string[]",
      "facet": true,
      "optional": true,
      "index": true
    },
    {
      "name": "product_prices",
      "type": "string[]",
      "facet": false,
      "optional": true,
      "index": false
    },
    {
      "name": "product_retailers",
      "type": "string[]",
      "facet": false,
      "optional": true,
      "index": false
    },
    {
      "name": "product_image_urls",
      "type": "string[]",
      "facet": false,
      "optional": true,
      "index": false
    },
    {
      "name": "product_target_urls",
      "type": "string[]",
      "facet": false,
      "optional": true,
      "index": false
    },
    {
      "name": "story_id",
      "type": "string",
      "facet": false,
      "optional": false,
      "index": true
    },
    {
      "name": "story_name",
      "type": "string",
      "facet": false,
      "optional": false,
      "index": true
    },
    {
      "name": "story_description",
      "type": "string",
      "facet": false,
      "optional": true,
      "index": true
    },
    {
      "name": "tags",
      "type": "string[]",
      "facet": true,
      "optional": true,
      "index": true
    },
    {
      "name": "price",
      "type": "float",
      "facet": false,
      "optional": true,
      "index": true
    },
    {
      "name": "creator",
      "type": "string",
      "facet": true,
      "optional": false,
      "index": true
    },
    {
      "name": "number_of_likes",
      "type": "int32",
      "facet": false,
      "optional": true,
      "index": true
    },
    {
      "name": "number_of_dislikes",
      "type": "int32",
      "facet": false,
      "optional": true,
      "index": true
    },
    {
      "name": "created",
      "type": "int32",
      "facet": false,
      "optional": false,
      "index": true
    },
    {
      "name": "updated",
      "type": "int32",
      "facet": false,
      "optional": false,
      "index": true
    }
  ],
  "default_sorting_field": "created"
}

Executed code (Python 3.9):

    async def test_update_schema(self):
        update_schema = {
			'fields': [
                {
                    "name"  : "product_retailers",
                    "drop"  :  True
                },
                {
					"name" : "product_retailers",
					"type" :  "string[]",
					"facet": True,
					"optional" : True,
					"index" : True
				}
			]}
        resp = await self.search_client.client.collections['outfits'].update(update_schema)
        print (resp)

Error log from my local environment:

ERROR: test_update_schema (test.test_modify_outfits_search_schema.SchemaChangeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/async_case.py", line 64, in _callTestMethod
    self._callMaybeAsync(method)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/async_case.py", line 87, in _callMaybeAsync
    return self._asyncioTestLoop.run_until_complete(fut)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/async_case.py", line 101, in _asyncioLoopRunner
    ret = await awaitable
  File "/Users/sergey/Workspace/story-matcher/src/test/test_modify_outfits_search_schema.py", line 26, in test_update_schema
    resp = await self.search_client.client.collections['outfits'].update(update_schema)
  File "/usr/local/lib/python3.9/site-packages/typesense/collection.py", line 22, in update
    return self.api_call.patch(self._endpoint_path(), schema_change)
  File "/usr/local/lib/python3.9/site-packages/typesense/api_call.py", line 151, in patch
    return self.make_request(requests.patch, endpoint, True,
  File "/usr/local/lib/python3.9/site-packages/typesense/api_call.py", line 127, in make_request
    raise last_exception
  File "/usr/local/lib/python3.9/site-packages/typesense/api_call.py", line 113, in make_request
    raise ApiCall.get_exception(r.status_code)(r.status_code, error_message)
typesense.exceptions.ServiceUnavailable: [Errno 503] Not Ready or Lagging

error log from the server:

I20220725 02:22:14.630314   118 raft_server.h:60] Peer refresh succeeded!
E20220725 02:22:15.001420   109 backward.hpp:4199] Stack trace (most recent call last) in thread 109:
E20220725 02:22:15.001456   109 backward.hpp:4199] #13   Object "", at 0xffffffffffffffff, in
E20220725 02:22:15.001462   109 backward.hpp:4199] #12   Object "/lib/x86_64-linux-gnu/libc-2.23.so", at 0x7fac1c1a251c, in __clone
E20220725 02:22:15.001467   109 backward.hpp:4199] #11   Object "/lib/x86_64-linux-gnu/libpthread-2.23.so", at 0x7fac1cb816b9, in start_thread
E20220725 02:22:15.001474   109 backward.hpp:4199] #10   Source "../../../../../libstdc++-v3/src/c++11/thread.cc", line 80, in execute_native_thread_routine [0x14ac6cf]
E20220725 02:22:15.001479   109 backward.hpp:4199] #9  | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/thread", line 215, in operator()
E20220725 02:22:15.001484   109 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/thread", line 271, in _M_invoke<0>
E20220725 02:22:15.001489   109 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/thread", line 264, in __invoke<ThreadPool::ThreadPool(size_t)::<lambda()> >
E20220725 02:22:15.001494   109 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 95, in __invoke_impl<void, ThreadPool::ThreadPool(size_t)::<lambda()> >
E20220725 02:22:15.001499   109 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 60, in operator()
E20220725 02:22:15.001504   109 backward.hpp:4199]     | Source "/typesense/include/threadpool.h", line 53, in operator()
E20220725 02:22:15.001508   109 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 1560, in _M_run
E20220725 02:22:15.001514   109 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 1427, in _M_set_result
E20220725 02:22:15.001520   109 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 404, in call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*>
E20220725 02:22:15.001525   109 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/mutex", line 729, in __gthread_once
E20220725 02:22:15.001530   109 backward.hpp:4199]       Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/x86_64-linux-gnu/bits/gthr-default.h", line 700, in _M_run [0x513e39]
E20220725 02:22:15.001534   109 backward.hpp:4199] #8    Object "/lib/x86_64-linux-gnu/libpthread-2.23.so", at 0x7fac1cb88a98, in __pthread_once_slow
E20220725 02:22:15.001540   109 backward.hpp:4199] #7  | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 564, in operator()
E20220725 02:22:15.001554   109 backward.hpp:4199]       Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/std_function.h", line 622, in _M_do_set [0x511c7a]
E20220725 02:22:15.001561   109 backward.hpp:4199] #6  | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/std_function.h", line 292, in __invoke_r<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<_Fn, _Alloc, _Res(_Args ...)>::_M_run<std::_Bind<BatchedIndexer::run()::<lambda()>()>, std::allocator<int>, void, {}>::<lambda()>, void>&>
E20220725 02:22:15.001566   109 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 113, in __invoke_impl<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<_Fn, _Alloc, _Res(_Args ...)>::_M_run<std::_Bind<BatchedIndexer::run()::<lambda()>()>, std::allocator<int>, void, {}>::<lambda()>, void>&>
E20220725 02:22:15.001572   109 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 60, in operator()
E20220725 02:22:15.001577   109 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 1365, in operator()
E20220725 02:22:15.001582   109 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 1424, in __invoke_r<void, std::_Bind<BatchedIndexer::run()::<lambda()>()>&>
E20220725 02:22:15.001587   109 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 110, in __invoke_impl<void, std::_Bind<BatchedIndexer::run()::<lambda()>()>&>
E20220725 02:22:15.001592   109 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 60, in operator()<>
E20220725 02:22:15.001597   109 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/functional", line 499, in __call<void>
E20220725 02:22:15.001602   109 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/functional", line 416, in __invoke<BatchedIndexer::run()::<lambda()>&>
E20220725 02:22:15.001607   109 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 95, in __invoke_impl<void, BatchedIndexer::run()::<lambda()>&>
E20220725 02:22:15.001613   109 backward.hpp:4199]       Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 60, in _M_invoke [0x51035c]
E20220725 02:22:15.001618   109 backward.hpp:4199] #5    Source "/typesense/src/batched_indexer.cpp", line 194, in operator() [0x50fc01]
E20220725 02:22:15.001626   109 backward.hpp:4199] #4    Source "/typesense/src/core_api.cpp", line 200, in patch_update_collection [0x5a97d3]
E20220725 02:22:15.001631   109 backward.hpp:4199] #3    Source "/typesense/src/collection.cpp", line 2722, in alter [0x537770]
E20220725 02:22:15.001636   109 backward.hpp:4199] #2    Source "/typesense/src/collection.cpp", line 2681, in batch_alter_data [0x535005]
E20220725 02:22:15.001641   109 backward.hpp:4199] #1    Source "/typesense/src/index.cpp", line 4853, in refresh_schemas [0x5f61fa]
E20220725 02:22:15.001644   109 backward.hpp:4199] #0    Source "/typesense/src/art.cpp", line 204, in art_tree_destroy [0x4d0124]
Segmentation fault (Address not mapped to object [(nil)])
I20220725 02:22:15.536525   109 batched_indexer.cpp:329] Saving currently applying index: 19055909
E20220725 02:22:15.536806   109 typesense_server.cpp:95] Typesense 0.23.0 is terminating abruptly.

## Expected Behavior

the update is performed accordingly

## Actual Behavior

When I performed the step above, the typesense process crashed. it then self-restarted and restored existing collections. during the restore, the CPU was pegged at 100%, and the collections weren't available.  

## Metadata

**Typsense Version**:  0.23.0

**OS**:  Mac

**Comment by jasonbosco** [comment]
@sergeypodlazov Could you try this on 0.23.1 and see if you're able to replicate the crash?

**Comment by kishorenc** [comment]
@sergeypodlazov 

Thank you so much for documenting this issue. I'm able to reproduce it. There is an edge case that we failed to account for when an `index: false` field is updated to become `index: true` field. I will be fixing this issue in a RC build soon.

**Comment by kishorenc** [comment]
No currently there is an issue in dropping non indexed field in the update operation. You have to drop and recreate the collection with new schema or create new collection and reindex.

I'll have a fixed build ready tomorrow in which this will work.

**Comment by kishorenc** [comment]
Fixed in `typesense/typesense:0.24.0.rc24` (Docker image uploaded).

**Comment by jasonbosco** [comment]
v0.24 is now available with this fix.
