### ISSUE TITLE
Adding more values to a filter field returns less results

### ISSUE THREAD

**Issue by ceed36** [typesense/typesense#675]
## Description

When filtering by a single field for two different values, typeA and typeB, I get 33 results for typeA and 1 result for typeB. 34 in total.
If I add a third value, typeC, I get only 28 results for typeA, still 1 for typeB and now 4 for typeC for a total of 33.
Why does the amount of results for one value get reduced if I add a third one?

## Steps to reproduce

First query:
`q=rm&query_by=objectType&filter_by:[typeA,typeB]`

Second query:
`q=rm&query_by=name,objectType&filter_by:[typeA,typeB,typeC]`

## Expected Behavior

Since the first query returns 33 results for typeA the second one should still return the same amount for typeA.

## Actual Behavior

The second query returns 5 results less for typeA.

## Metadata

**Typsense Version**: v0.21.0

**Comment by kishorenc** [comment]
Can you please try on Typesense v0.23.1 which is the latest version?

**Comment by ceed36** [comment]
That seems to have fixed it
Thanks
