### ISSUE TITLE
Flexible definition of geopoint

### ISSUE THREAD

**Issue by boldtrn** [typesense/typesense#676]
## Description

We have an existing document schema in our db and would like to index the DB with typesense. The documents store a location like:

```
{
  location: {
    lat: 1.2,
    lng: 2.4,
    meta : {...}
  }
}
```

Would it be possible to write a schema for this to allow geo queries? Or do we need to create an additional field when syncing our db with typesense to include another property like:

```
typesense_location: [48.86093481609114, 2.33698396872901]
```

**Comment by kishorenc** [comment]
The `geopoint` data type in Typesense requires the filed to be a 2-element array, so you need it as `typesense_location: [48.86093481609114, 2.33698396872901]`.
