### ISSUE TITLE
Multiple Scoped API Keys for different collections in multi-search

### ISSUE THREAD

**Issue by successx** [typesense/typesense#677]
## Description

Hi, thanks for awesome work with Typesense. Quick question on multi-search and scoped API Keys.

Our main search bar allows user to search for both publicly available and private contents from multiple collections. From the document,  it looks like filter_by cannot be used with OR condition; which also limits scoped API Key on single AND condition.

With currently version, is there any ways to perform public and private search without creating multiple clients? Additionally, we also need to perform search in three different collections, any suggestion to reduce the amount of network calls with this requirement?

Not sure if this is a possibility, we would love to have scoped API Key as part of each multi-search argument to override default API Key. It might be a bad idea though.

**Comment by jasonbosco** [comment]
@successx As of v0.23.1, you can now send an `x-typesense-api-key` in each search in a multi-search request with a different scoped API key.

**Comment by successx** [comment]
Thank @jasonbosco , that's great to know. I think typesense-js haven't been updated with this option. Will test it manually then.

**Comment by jasonbosco** [comment]
I've opened a separate issue in typesense-js to add that param to the types.
