### ISSUE TITLE
Performance problem after moderately sized table drop

### ISSUE THREAD

**Issue by rbarabas** [typesense/typesense#679]
## Description

After dropping a moderately sized table with 10M records, inserts time out with `context timeout` and there is heavy CPU utilization on each TypeSense node. Each node has a single thread (out of 100+) that takes an entire CPU core.

## Steps to reproduce

- Enable RAFT if it's not enabled already
- Insert 10M records in a collection.
- Interface with the data (reads, updates) and observe your nominal OPS
- Drop the database
- Try to rerun your workload, observe that OPS have dropped and you get `context timeout` errors.

## Expected Behavior

No `context timeout` errors, CPU is in nominal range across threads with no single thread hot spot, TypeSense is able to process workload like on first run.

## Actual Behavior

Inserts error out with the following error message:
```
Got error:  context deadline exceeded
```

## Metadata

**Typsense Version**: `typesense/typesense:0.23.1`

**OS**: `5.4.176-91.338.amzn2.x86_64 x86_64 GNU/Linux`

**Comment by jasonbosco** [comment]
v0.24 is now available with this fix.
