### ISSUE TITLE
Not possible to include "-" as part of the text that should be searched on

### ISSUE THREAD

**Issue by Nikodym7373** [typesense/typesense#685]
## Description

Not possible to search on "-" sign as part of text search. I.e. when "-" should not be treated as a negative search. 

## Steps to reproduce

1. Add  the document:
wording = "inget $ \mathrm{av} $ $\text { (a) }-(\mathrm{c})$ behöver gälla."
id "= test" 

2. Search on wording field (query by "wording" with q = "inget $ \mathrm{av} $ $\text { (a) }-(\mathrm{c})$ behöver gälla."

## Expected Behavior
It should return document with id = "test"

## Actual Behavior
It returns nothing due to that "-" acts as a negative search

## Metadata

**Typsense Version**:
Using Typesense Cloud Search and Firebase Extension 0.3.0

**OS**:
12.0.1

**Comment by jasonbosco** [comment]
@Nikodym7373 We've addressed this in `0.24.0.rc25`. You can now add `-` to `token_separators` when creating the collection, and it will not trigger negative search. 

You can schedule a version upgrade for your Typesense Cloud cluster by clicking on the "Modify configuration" link in the Overview screen.

**Comment by Nikodym7373** [comment]
Hi Jason!

That sounds great! Thanks. I have chosen an upgrade for tomorrow, but I
assume it will not be the "rc" release? I specified 0.24.0 as the targeted
release. Let me know if I need to change this.

Thanks again!
/peywand

**Comment by jasonbosco** [comment]
That's fine. I'll make an internal note that it should be the latest RC release of 0.24.0, which has this feature.

**Comment by jasonbosco** [comment]
v0.24 is now available with this fix/feature.

**Comment by Nikodym7373** [comment]
Sorry, I dont understand. I said that it works in the typesense cloud gui. It is from Swift it does not work. Please advise. On 31 Jan 2023, at 01:28, Jason Bosco ***@***.***> wrote:﻿
Closed #685 as completed.
