### ISSUE TITLE
do I use PostgreSQL or Typesense? or both? to make an app

### ISSUE THREAD

**Issue by tesla-cat** [typesense/typesense#689]
- I am a beginner and I want to make a standard APP 
- I know the standard approach for APPs is to save data in the database
- But I found that PostgreSQL's full text search functionality sucks, and it is not fuzzy
- so should I use Typesense alone as my database? or combine both? how does an usual app work?

**Comment by jasonbosco** [comment]
Typesense is not designed to be a primary data store where you store the only copy of your data. Instead you want to store your data in a primary datastore like Postgres and then sync a copy of that data into Typesense to enable fast fuzzy search on it.

**Comment by alterEgo123** [comment]
There's support for fuzzy search in PostgreSQL with [pg_trgm](https://www.postgresql.org/docs/current/pgtrgm.html) or [fuzzystrmatch](https://www.postgresql.org/docs/current/fuzzystrmatch.html)

**Comment by barwis00** [comment]
> Typesense is not designed to be a primary data store where you store the only copy of your data. Instead you want to store your data in a primary datastore like Postgres and then sync a copy of that data into Typesense to enable fast fuzzy search on it.

is there any tutorial or documentation about it? thanks in advance

**Comment by kishorenc** [comment]
@barwis00 

Are you looking for documentation on the sync part?

**Comment by barwis00** [comment]
> @barwis00
> 
> Are you looking for documentation on the sync part?

yes, I'm currenty looking for sync postgresql with typesense but I cannot find the tutorial or documentation about it

**Comment by barwis00** [comment]
> > @barwis00
> > Are you looking for documentation on the sync part?
> 
> yes, I'm currenty looking for sync postgresql with typesense but I cannot find the tutorial or documentation about it

@kishorenc

**Comment by kishorenc** [comment]
There are a couple of ways to do it:

a) For data that does not change too often, you can write a cron script that queries the tables periodically using some form of `last_updated_at` field to fetch new records for updates.
b) For real-time streaming updates, you can have to write the changes from your application directly to Typesense or write it into a queue and then have another process that read off the queue and update Typesense.

**Comment by barwis00** [comment]
@kishorenc is there any documentation that explain more about this? I'm still beginner so I didn't understand much about using ORM and cron for sync typesense

**Comment by jasonbosco** [comment]
Here's a guide on this topic: https://typesense.org/docs/guide/syncing-data-into-typesense.html
