### ISSUE TITLE
Is it possible to get facets upon filter

### ISSUE THREAD

**Issue by jsinhSolanki** [typesense/typesense#69]
Hi,
Is it possible I can get facets when I filter rather than search? e.g. Currently For displaying all results I am using `'q': '*'` and upon filter. But until I don't update my `q: 'any_query'` it doesn't give me facets.

## Steps to reproduce

Just pass filter and use `'q': '*'` as query paramter.

## Expected Behavior

Upon filter can I get facets.

## Actual Behavior

It only returns facets upon search_query

## Metadata

**Typsense Version**: 0.10.0

**OS**: Ubuntu

~ Thanks

**Comment by kishorenc** [comment]
@jsinhSolanki Thank you for reporting this issue. There was a bug which has been fixed in the following nightly build:

https://dl.typesense.org/releases/typesense-server-0.10.1-beta-linux-amd64.tar.gz

**Comment by jsinhSolanki** [comment]
hello @kishorenc,
I tested your given release. This works perfectly fine. It gives me facets upon filtering. Great job. :+1:

**Comment by kishorenc** [comment]
Glad to hear!
