### ISSUE TITLE
2 tier tie breaking in sort completely randomizes ordering of result

### ISSUE THREAD

**Issue by adilansari** [typesense/typesense#690]
## Description

Sorting the results is broken when 3 sort fields are specified. However, it works if only 2 sort fields are specified. I was following [this guide](https://typesense.org/docs/guide/ranking-and-relevance.html#tie-breaking-based-ranking) to tie break ranking.

## Steps to reproduce

Consider following schema:
|field name| type | sortable |
|----|----|----|
|item_id|string|false|
|downvotes|int64|true|
|upvotes|int64|true|
|price|float|true|

- Dataset has ~110 documents and less than 1 MB in size
- There are no null/empty values. Numeric fields have values between `[0, 500]`

Will send two search queries as following:

1. `q="",  sortBy="downvotes(missing_values: last):desc, upvotes(missing_values: last):asc"`
2. Same as above with additional field for tie breaking: `q="",  sortBy="downvotes(missing_values: last):desc, upvotes(missing_values: last):asc, price(missing_values: last):asc"`

## Expected Behavior
1. Expected result set using first query:

```json
[
  { "downvotes": 10,  "upvotes": 16, "price": 77},
  { "downvotes": 10,  "upvotes": 19, "price": 182},
  { "downvotes": 8,  "upvotes": 5, "price": 96},
  { "downvotes": 8,  "upvotes": 24, "price": 139},
  { "downvotes": 6,  "upvotes": 0, "price": 175},
  { "downvotes": 6,  "upvotes": 10, "price": 80},
]
```

2. Expected result set using second query:

```json
[
  { "downvotes": 10,  "upvotes": 16, "price": 77},
  { "downvotes": 10,  "upvotes": 19, "price": 182},
  { "downvotes": 8,  "upvotes": 5, "price": 96},
  { "downvotes": 8,  "upvotes": 24, "price": 139},
  { "downvotes": 6,  "upvotes": 0, "price": 175},
  { "downvotes": 6,  "upvotes": 10, "price": 80},
]
```

## Actual Behavior
1. ✅ First query with only 2 sort fields works as expected
2. ❌ Second query adds a 3rd sort field to tie break, it breaks the ordering completely

```json
[
  { "downvotes": 6,  "upvotes": 0, "price": 175},
  { "downvotes": 1,  "upvotes": 0, "price": 183},
  { "downvotes": 1,  "upvotes": 1, "price": 65},
  { "downvotes": 8,  "upvotes": 5, "price": 96},
  { "downvotes": 5,  "upvotes": 9, "price": 170},
  { "downvotes": 6,  "upvotes": 10, "price": 80},
  { "downvotes": 1,  "upvotes": 10, "price": 86},
]
```
It seems like during query parsing, it is ignoring the first sort field, and takes the second sort field as primary and third sort field for tie breaker. Somewhere [here in code](https://github.com/typesense/typesense/blob/main/src/collection_manager.cpp#L511-L554)

## Metadata

**Typsense Version**: `v0.23.0`
**OS**: Linux

**Comment by kishorenc** [comment]
I noticed this issue last week and has been fixed in recent 0.24 RC builds. Can you please check against this Docker build: `typesense/typesense:0.24.0.rc29`

**Comment by adilansari** [comment]
This works in `0.24.0.rc29`, thanks

**Comment by jasonbosco** [comment]
v0.24 is now available with this fix.
