### ISSUE TITLE
Typesense not listen to Firebase DB change

### ISSUE THREAD

**Issue by ngochai9a7** [typesense/typesense#694]
As the title, I use Typesense self-hosted server (using Docker) on my localhost. When I created a new document in Firestore, Typesense did not automatically create a new document in the collection. I follow this guide: https://typesense.org/docs/guide/firebase-full-text-search.html#step-1-run-typesense

Actually, I don't know which files I should write sample code in so I try to add sample code in 2 files (runServer.js - to run Docker and loadData.js - to index existing data). I follow this guide: https://aviyel.com/post/2740/how-to-get-started-with-typesense-and-reactjs

But it didn't work, so how can Typesense listen to Firebase data changes? Which file should I write functions to? (based on folder structure here https://github.com/aviyelverse/Article-project-demo/tree/main/superhero-searchapp-reactjs-typesense).

Using Typesense latest version, Docker, Firebase (no Typesense extension)

Really appreciate your help, I need to complete this task before Aug 24, 2022

**Comment by jasonbosco** [comment]
You would have to place those code snippets in a new cloud function trigger you create. Here's the official Firestore documentation for this: https://firebase.google.com/docs/functions/firestore-events

That said, I'd recommend installing the Typesense Firestore extension, which already does this for you without you having to write additional code: https://github.com/typesense/firestore-typesense-search#%EF%B8%8F-usage

**Comment by ngochai9a7** [comment]
Yeah, I've already used Typesense Cloud with Firebase and it worked (720 hours free as I know), but I am a student and use this for my personal project/ localhost (non-commercial of course) so I prefer to use self-hosted server. I also created cloud function trigger file, but the result is "timeout" or "request to node 0 failed due to econnrefused connect econnrefused 127.0.0.1:443" or something like that.

**Comment by jasonbosco** [comment]
You can indeed use a self-hosted Typesense Server with the Typesense Firestore extension. You'd just need to get an SSL certificate (from say LetsEncrypt which is free) and then use your server's hostname in the extension's configuration, instead of the hostnames you get from Typesense Cloud. 

> I also created cloud function trigger file, but the result is "timeout" or "request to node 0 failed due to econnrefused connect econnrefused 127.0.0.1:443" or something like that.

You want to update 127.0.0.1 to the hostname of the server where you've hosted Typesense.
