### ISSUE TITLE
Replacing Sphinx default search with Typesense

### ISSUE THREAD

**Issue by miohtama** [typesense/typesense#695]
## Description

[Sphinx](https://www.sphinx-doc.org/en/master/) is one of the most popular open source / closed source software development documentation tools, offering Markdown, Restructured Text and other ways to publish technical documentation. [ReadTheDocs](https://readthedocs.org/) is a service for publishing your docs, running on Sphinx and hosting 55 million pages of documentation for OSS projects.

However, due to its static page generator nature, Sphinx default built-in search is horrible to the point it is useless. Because of this, multiple providers address this shortcoming to offer a better search for Sphinx. [Here is an example of "almost" turn key Sphinx search integration using Algolia](https://stackoverflow.com/questions/54872828/sphinx-docs-can-it-support-algolias-doc-search).

In our company, we are already using [Typesense Hosted Search and loving it](https://tradingstrategy.ai/blog/world-fastest-token-search). My question is, what is the easiest way to replace Sphinx built-in search with Typesense and index our [1000+ pages of technical documentation there](https://tradingstrategy.ai/docs/).

My issue is that before I get started to create "homebrew" way to Sphinx and Typesense integration, I would like to ask Typesense authors what would be the cleanest way to do this (check the Algolia example above). Because I feel there are a lot of projects out there who would like to follow the lead and get Typesense search for their Sphinx sites.

## Steps to reproduce

- Install Sphinx
- Learn about the awesomeness of Typesense
- Get complaints from the users your Sphinx documentation search is useless
- Sudden urgent feeling to want to replace Sphinx search with Typesense search

## Expected Behavior

- There is a ready Typesense recipe for Sphinx integration, because Sphinx happens to be the most popular open source tool out there and people really want to have their Typesense

## Actual Behavior

- [I could not find anything useful](https://www.google.com/search?hl=en&q=sphinx%20typesense)

**Comment by jasonbosco** [comment]
We have a forked version of Algolia's DocSearch UI library and DocSearch scraper that works with Typesense. Here's more information on this: https://typesense.org/docs/guide/docsearch.html

The only changes you'd have to make are the ones mentioned in the [StackOverflow answer](https://stackoverflow.com/a/54960623/123545) you shared. You'd also have to change the options passed to `docsearch({ ... })` as mentioned [here](https://typesense.org/docs/guide/docsearch.html#option-c-custom-docs-framework-with-docsearch-js-v3-modal-layout).

**Comment by miohtama** [comment]
Thank you so much @jasonbosco  

I will write a tutorial on this when complete.

**Comment by jasonbosco** [comment]
A tutorial would be great! Please feel free to post a link to it here. Happy to also link to it from the Typesense docs site.

**Comment by kalyantitaniam** [comment]
Thanks for the pointers. I managed to integrate typesense into my documentation site. It is not yet public. But, I got a local copy of typesense server working and integrated the typesense searchbar into my documentation site. The documentation site itself is built using ReadtheDocs template. Our is a self-hosted documentation site. You can read the tutorial here: https://writeexperience.co/integrating-typesense-with-sphinx-readthedocs-template-a-step-by-step-guide/

**Comment by jasonbosco** [comment]
Thank you for putting that guide together! I've linked to it from our docs site: https://typesense.org/docs/guide/docsearch.html#option-e-sphinx-documentation-generator

**Comment by miohtama** [comment]
Thank you @jasonbosco 

We are now live here with Typesense as our doc search engine.

Typesense covers 1000+ narrivate and generated API documentation pages:

https://tradingstrategy.ai/docs/

You can find the integration repo here:

https://github.com/tradingstrategy-ai/docs

Happy to answer any questions.

**Comment by jasonbosco** [comment]
Nice! Thank you for sharing @miohtama.
