### ISSUE TITLE
Is there a not in operator ? 

### ISSUE THREAD

**Issue by baderkha** [typesense/typesense#701]
## Description

for the filter_by query parameter is there any *not in* style of operations . 

IE filter_by=first_name:![person,person2,person3]

i tried looking at the code in case you may have missed something in the documentation , but i could not find anything . 

## Expected Behavior

There should be an inverse of the in operation

## Actual Behavior

There is no Inverse in operator

## Metadata

**Typsense Version**: 0.23.0

**OS**: Pop OS

**Comment by jasonbosco** [comment]
Could you try `first_name:!=[person,person2,person3]`

**Comment by baderkha** [comment]
yes that seems to do the trick . Sorry i couldn't find it anywhere .

**Comment by baderkha** [comment]
closing the issue thanks @jasonbosco

**Comment by polarby** [comment]
@jasonbosco What is the max length of this array? Could this include dozens of elements?

**Comment by jasonbosco** [comment]
@polarby There are no limits to the length of this array.

**Comment by polarby** [comment]
Like a dream 👍
