### ISSUE TITLE
Search result returning wrong word

### ISSUE THREAD

**Issue by kuhlaid** [typesense/typesense#702]
## Description

Running this search [https://dataverse-docusaurus.vercel.app/search?q=toolname](https://dataverse-docusaurus.vercel.app/search?q=toolname) on `toolname` is finding `TOOL_ID` instead. This does not seem like a configuration issue.

## Steps to reproduce

See search result at [https://dataverse-docusaurus.vercel.app/search?q=toolname](https://dataverse-docusaurus.vercel.app/search?q=toolname)

## Expected Behavior

Trying to get the search to find the `toolName` value in the [https://dataverse-docusaurus.vercel.app/docs/admin-guide/external-tools#adding-external-tools-to-a-dataverse-installation](https://dataverse-docusaurus.vercel.app/docs/admin-guide/external-tools#adding-external-tools-to-a-dataverse-installation) section.

## Metadata

**Typsense Version**: 0.23.1

**OS**: Windows 11 API indexing calls to site hosted on Vercel.com

**Comment by jasonbosco** [comment]
@kuhlaid Could you share your docsearch-scraper config file? I suspect that code blocks are not included the scraper config, so the code snippet containing `toolName` is not indexed. 

Separately, `TOOL_ID` gets indexed as `TOOLID` in Typesense (since special characters are removed by default). And then since the search `toolName` doesn't match any records (see above), typo tolerance kicks-in and tries to find a close enough document. The default typo tolerance is 2 characters (including missing characters). So `toolName` returns `TOOLID` which is within two edit distances.

**Comment by kuhlaid** [comment]
The scraper config I used is [https://github.com/kuhlaid/dataverse-docusaurus/blob/7be5813165029866791468c2fbf5a2a5ac15a749/typesense_scraper_config.json](https://github.com/kuhlaid/dataverse-docusaurus/blob/7be5813165029866791468c2fbf5a2a5ac15a749/typesense_scraper_config.json). I added `article code` to the config thinking that might index the code block (it did index a code block but not the one I was wanting to be indexed). I'm guessing TypeSense is ignoring it because there is JSON formatted text within the code block.

How do I tell TypeSense NOT to remove any characters?

**Comment by jasonbosco** [comment]
@kuhlaid Just to be sure, once you've made the change to the docsearch scraper configs, could you delete the collection in Typesense and then re-run the scraper?

**Comment by kuhlaid** [comment]
Ah right, yes I guess I would need to re-run the scraper. I have decided to switch to a simplified search solution for the time being since manually running the scraper is a pain. I will close out this issue. Thank you.

**Comment by jasonbosco** [comment]
For Typesense's docs we run the docsearch scraper on AWS Fargate and trigger it on demand anytime we deploy the docs site. Would it be helpful if I shared the terraform configs we use to set that up?
