### ISSUE TITLE
Running inside a request-based container such as Cloud Run

### ISSUE THREAD

**Issue by brettwillis** [typesense/typesense#703]
This is a question, not an issue. I have managed to get TypeSense running inside a Docker container than runs on Google Cloud Platform's Cloud Run.

What happens with Cloud Run is that typically the CPU is only allocated while responding to a request, then the container goes to sleep between requests. Running inside such a container is quite economic in terms of pricing.

The immediate limitations with this setup are:
- It must be limited to only a single instance, not a cluster. Instances cannot communicate with eachother because they go to sleep between requests.
- Therefore, the solution will be limited to small/medium capacity.
- There is no persistent disk, so the index must be loaded on container startup in some other way (e.g. rebuild from a database).
- The filesystem is an in-memory filesystem, so this limits the size of the index to what will fit within the container's memory.

In my scenarios, these tradeoffs are perfectly fine, and the result is a well-performing and highly economical TypeSense server. And it *seems* to be working just fine!

But I want to ask: is there something in the technical implementation of TypeSense that is going to break in this setup where the container sleeps between requests? Any background tasks will not operate! After serving a request, the container will wake up an indefinite time later to either serve another request or to perform shutdown. If the techincal implementation is going to accumulate a backlog background tasks while sleeping, then this would jam up the CPU when resuming.

Thoughts?

**Comment by kishorenc** [comment]
@brettwillis 

I think the biggest gotcha with this setup is that it relies on Google Cloud not purging the container and keeping it warm. Typically if a given Cloud function is often accessed, Google Cloud keeps that image "warm" and therefore any data indexed into the ephemeral data volume inside the container is preserved. However, if the container is purged for whatever reason, then there will be data loss.

**Comment by brettwillis** [comment]
Thanks @kishorenc, yes this solution relies on reloading the index from the authoritative data source whenever the container starts up (and then staying up-to-date with said data source while it is alive). I've found that if the container is receiving requests every several minutes, it typically stays alive somewhere between half a day and several days.

So no likely technical problems within TypeScript's implementation then?

**Comment by kishorenc** [comment]
Yes this model is fine otherwise.

**Comment by wennals** [comment]
@brettwillis  I'm having some issues running typesense on cloud run. Would you be able to share how you were able to set that up ? When I run it, I can reach the health, metrics, debug, and stats endpoints. However, when I try to connect to it with the client, it times out or refuses the connection. I have the port set as 8108, but I only get a response when I use port 80... which is odd

**Comment by brettwillis** [comment]
@wennals give me a day or so and I'll share a gist. Not sure about changing the port, however refused or timed-out connection sounds like the container may be crashing? Are there any clues in the Cloud Logging logs?

In my case I actually run the TypeSense server behind my own Node.js server (TypeSense is not directly accessible outside the container), because I implement my own authentication, routes etc, not to mention initialisation logic to load up the index from the primary database when the container starts.

**Comment by wennals** [comment]
No clues, the logs were printing out pretty good when I did a health check, metrics, and stats, but if I tried to connect to port 8108 or 443 it would throw and error (i tried with a curl). When I ran the typesense client, the connection would either timeout or say connection refused. However, I noticed that port 80 would give a response.
