### ISSUE TITLE
how to search full text?

### ISSUE THREAD

**Issue by lmessinger** [typesense/typesense#71]
## Description

I'm wondering about searching full text. I'd like to upload real documents and use typesense for search. How do i do that?

thanks
## Steps to reproduce

[Include screenshots, curl commands (please use the -sv flags for curl), etc]

## Expected Behavior

[When you do the steps above, what is the expected behavior?]

## Actual Behavior

[When you do the steps above, what is the actual behavior you see?]

## Metadata

**Typsense Version**:

**OS**:

**Comment by kishorenc** [comment]
@lmessinger When you mean by documents, do you mean webpage contents? You can index the `<p>` paragraph contents as `string[]` (string array) field and then just search against it. 

If you can give me more context or type of document involved, I can help further.

**Comment by jdwillemse** [comment]
Same question here; if I want to index an article with HTML markup is this possible? If not, how would I index the body of the article?

**Comment by jasonbosco** [comment]
> if I want to index an article with HTML markup is this possible?

@jdwillemse Yes, this is possible. Here's an example of how you'd do this: https://github.com/typesense/gatsby-plugin-typesense#-how-it-works

You'd essentially want to parse out the content you want indexed from the markup and create a Typesense document for it. The source code for the Gatsby plugin is a good reference point to use.
