### ISSUE TITLE
Pls add some documentation around backup restore

### ISSUE THREAD

**Issue by zehawki** [typesense/typesense#710]
While there is information about snapshotting in the doc, there does not seem to be any info around restore and best practices or gotchas while restoring.

As an example I did this, and I guess its this straight forward, but would be good to have this documented.

1. Snapshot created on 0.22.1 on running TS
2. New server setup with 0.23.1. TS not running.
3. Copied the snapshot to the new server
4. Replaced the `/var/lib/typesense/state` folder with the corresponding `state` folder found in the snapshot
5. Started TS on new server

**Comment by kishorenc** [comment]
Will do. Btw, you should replace the snapshot directory fully, and not replace only the state directory. Though the latter should work at the moment, it might not work in future if we added other auxiliary files that relied on other directories.

**Comment by zehawki** [comment]
Ah, see, thats exactly why docs would help ;-)

**Comment by jasonbosco** [comment]
Just added docs here: https://typesense.org/docs/guide/backups.html
