### ISSUE TITLE
Major difference in search results between 0.22.1 and 0.23.1

### ISSUE THREAD

**Issue by zehawki** [typesense/typesense#712]
## Description

For the exact same dataset, the search results between 0.22.1 and 0.23.1 are wildly different. What explains this? I am not able to see anything in the [releases notes](https://typesense.org/docs/0.23.1/api/#what-s-new) that might hint at this.

I see 2 types of differences so far:
1. Potential quality of result improvement - more relevant search results are showing and showing earlier in results. Especially searching for multi word strings eg "network site" "delete channel" "malformed tags" throws up all results containing exactly that phrase, before results with only a part of the phrase show up. And rubbish results seem to be a lot lesser.
2. Quantity of results reduction - but the number of search results are (a lot) lesser in (some) all cases

**Comment by zehawki** [comment]
> Improved multi-field matching: much better performance and accuracy when query keywords have to be matched across multiple fields in a document.

I certainly read that, but thats about "multi field" matching, or?

**Comment by zehawki** [comment]
> On 0.23, you can increase the drop_tokens_threshold configuration to get a larger set of results if you want.

I not sure how `drop_tokens_threshold` is supposed to be used - how can one predict that x number of results should be returned, to set this field in advance.

**Comment by kishorenc** [comment]
> I certainly read that, but thats about "multi field" matching, or?

Are you querying a single field or multiple fields in your searches? If you have more than 1 field in `query_by` these changes will impact.

> I not sure how drop_tokens_threshold is supposed to be used

While you can't predict exactly, if you are looking for results that only partially match the tokens in the query, then this is the only flag that will help. Again, the earlier behaviour was not perfect so we had to fix it.

**Comment by zehawki** [comment]
Ok, I think by and large the overall QoR is better with 0.23.
