### ISSUE TITLE
Sorting by date:desc doesn't sort well.

### ISSUE THREAD

**Issue by delzennejc** [typesense/typesense#713]
I use the hosted search version with Typesense v0.22.2.

But lately, when I search using sort by date:desc it doesn't sort it well anymore.

It sorts these 2 objects this way, while it should be the opposite.
![image](https://user-images.githubusercontent.com/8841718/188285315-814b7ac2-3de6-47b6-b7b9-b3e7bf36456d.png)
![image](https://user-images.githubusercontent.com/8841718/188285432-9a82505d-24f7-4300-ab49-066205416d37.png)

**Comment by jasonbosco** [comment]
The `date` field in your example seems like an integer field and both records have identical values: `1662225152`. So when you do `sort_by: date:desc` there is a tie between both records, and then to break the tie, Typesense will use the document insertion order.

**Comment by delzennejc** [comment]
But the insertion order is not respected, one is added like 1h after that.

**Comment by jasonbosco** [comment]
It's sorted on _ascending_ insertion order by default when all other sort fields are a tie. So records inserted earlier show up first, which is what is happening here.
