### ISSUE TITLE
Multiple exact matches for an override?

### ISSUE THREAD

**Issue by Bug-Reaper** [typesense/typesense#714]
## Description

Is there a way to have more than one exact match trigger per override? Something like this where an exact match with either (**Apple** or **Pear** or **Banana**) triggers the same overrides:

```json
{
  "rule": {
    "query": ["apple","banana","pear"],
    "match": "exact"
  },
  "includes": [
    {"id": "420", "position": 1},
    {"id": "69", "position": 2}
  ]
}
```
or
```json
{
  "rule": {
    "query": "apple||banana||pear",
    "match": "exact"
  },
  "includes": [
    {"id": "420", "position": 1},
    {"id": "69", "position": 2}
  ]
}
```
or
```json
{
  "rules": [
    {
      "query": "apple",
      "match": "exact"
    },
    {
      "query": "banana",
      "match": "exact"
    },
    {
      "query": "pear",
      "match": "exact"
    }
  ],
  "includes": [
    {"id": "420", "position": 1},
    {"id": "69", "position": 2}
  ]
}
```

EDIT: So I tried all of the above and none of those work. Curious if there's a way to do this though with some magic in the query string...

**Comment by kishorenc** [comment]
You have to add individual rule: it's not possible to do this with a single rule at the moment because we don't support the `query` being a list or regular expression at the moment.

**Comment by Bug-Reaper** [comment]
Thought so, thanks for the confirmation @kishorenc ! Was able to abstract it on my frontend to achieve the desired effect from a usage standpoint. I manage each override w/ an id that looks like `<GroupUuid> + <Query>` and just sort them into groups on the db management UI/UX.
