### ISSUE TITLE
Curate Results

### ISSUE THREAD

**Issue by francesco-hayes** [typesense/typesense#716]
## Description

I am trying to curate results based upon a list of IDs to place at the end or beginning of the results from instantsearch.js. However, I can't find where to add this within the parameters. I know this is possible with Typesense via [here](https://typesense.org/docs/0.23.1/api/curation.html#including-or-excluding-documents). However, I haven't had any luck.

## Steps to reproduce

No error to return

## Expected Behavior

Return the results with desired documents in front or end as described in the curation methods of Typesense.

## Actual Behavior

No curation.

## Metadata

**Typsense Version**: 0.23.1

**OS**: Mac

**Comment by francesco-hayes** [comment]
> @francesco-hayes Curation / Overrides work independent of instantsearch.js (which is only a UI library).
> 
> Could you share the output of `GET /overrides` and also the search query you're using with all the search parameters?

I see... I haven't made any overrides because I was hoping that I could curate the data based on the client's chosen documents from a WordPress database.

The query is empty.

**Comment by jasonbosco** [comment]
> hoping that I could curate the data based on the client's chosen documents from a WordPress database
> The query is empty.

You can create an override in Typesense when these documents are chosen in Typesense. So something like this:

```json
override = {
  "rule": {
    "query": "*",
    "match": "exact"
  },
  "includes": [
    {"id": "user-chosen-document-id-1", "position": 1},
    {"id": "user-chosen-document-id-2", "position": 2}
  ]
}
```

And then when the search query is made with `q=*` the document with ID `user-chosen-document-id-1` will be pinned at position 1, the document with ID `user-chosen-document-id-2` will be pinned at position 2 and so on.
