### ISSUE TITLE
Wrong order when sort by string with German Umlauts

### ISSUE THREAD

**Issue by JZubero** [typesense/typesense#717]
## Description

When doing [sort by strings](https://typesense.org/docs/0.23.1/api/search.html#sorting-on-strings), the ordering is wrong if (leading) German Umlauts (äÄöÖüÜ) are present. They seem to get pushed to the beginning of the result list. I haven't checked but it could be the same for other Latin non-standard characters like the Spanish Ñ.

## Steps to reproduce

I have created a [gist demoing the described behavior](https://gist.github.com/JZubero/39e8508a8eb92a013080f51db6b25e20). It's based on the basic books example from the Typesense landing page.

## Expected Behavior

Strings with (leading) German Umlauts should be included in a natural language sort order. There is a good [StackExchange thread](https://german.stackexchange.com/questions/52765/ordering-german-special-characters-and-those-from-other-languages-when-sorting) about this topic.

## Actual Behavior

Strings with (leading) German Umlauts are being pushed to the beginning of the result list.

## Metadata

**Typsense Version**: 0.23.1

**OS**: Ubuntu 20.04.1

**Comment by kishorenc** [comment]
The accented characters are not getting normalized like it's done for regular indexing. I'll have a patch for this soon.

**Comment by kishorenc** [comment]
@JZubero Please try against this Docker build: `typesense/typesense:0.24.0.rcn13`.

**Comment by JZubero** [comment]
@kishorenc Confirming that it works with 0.24.0.rcn13 :+1: Tested with the gist and a larger collection (~3k records) from another project. Looking forward to v0.24.0 getting stable.

**Comment by jasonbosco** [comment]
v0.24 is now available with this fix.
