### ISSUE TITLE
Document update limitations

### ISSUE THREAD

**Issue by polarby** [typesense/typesense#720]
I would like to store certain stats (such as likes, followers, etc.) in a typesene document, to be able to retrieve documents with a certain filter to those stats later on. This would mean, I have to update documents.

The question is what the limitations of those updates are? How many updates on one document can I perform per second? What would be a recommended way?

I currently see three options:
- Instantaneously (if within limitations) update document  (Would be the easiest)
- Update document with a distributed counter 
- Store all document ids (that also match the actual database) and mirror saved stats with a scheduled function (let's say every hour)

**Comment by kishorenc** [comment]
👋 @polarby 

Updates are pretty cheap. You can send only the fields that have changed via the `PATCH` operation. Even if you send unmodified fields Typesense will not attempt to index unchanged values. 

We don't have an atomic counter though (primarily because Typesense is not meant to be used a primary data store and always syncs data from your primary store like a DB).

**Comment by polarby** [comment]
@kishorenc Thanks for the quick reply ✌️

To be honest "Updates are pretty cheap." is a too vague and risky statement for me - This kinda freaks me out :)
Especially when potentially having to read the current value of the document first and do a write for thousands of requests to one document per second.

[For people with the same problem] 
I came up with the following solution:

- **Have a counter system on the main database**
_Reason for counter:_ There are usually write limitations to one single document. Meaning that too many updates per second would slow down/crash the server or create incontinuety.
_Solution to write limitations:_ 
Collect updates as documents, meaning there is no writing limitation to a single document. Run a scheduled worker function and add up all documents and write them all at once to the actual document.

- **Listener on the document you want to mirror in the Typesense database**
Usually, you will have access to a cloud function API (when working with database providers often provided) to listen for document changes: such as `.collection("users").onUpdate(...)`. So each time the counter (or other writes) changes the document you can use the `PATCH` operation, as suggested by @kishorenc. This removes the additional need for a counter, as well as lowers the write operations on the Typesense database.

Hope this helps somebody:)
