### ISSUE TITLE
Using typesense on android

### ISSUE THREAD

**Issue by britisharmy** [typesense/typesense#724]
I want to use typesense in my android app. Would it be possible to also use instantsearch for android https://www.algolia.com/doc/guides/building-search-ui/installation/android/

using typesense?. I have seen dart implementation  https://github.com/typesense/typesense-dart   but i am not sure what widgets UI i can use with it.

is there a widgets library for dart that i can use on android and ios?

**Comment by jasonbosco** [comment]
I don't believe Android Instantsearch works with Typesense out of the box. So you would have to use our Java library to talk to Typesense from an Android app and build you own UI widgets.
