### ISSUE TITLE
How to turn of fuzzy matches

### ISSUE THREAD

**Issue by mrraghur** [typesense/typesense#727]
## Description

I am trying to build a personal search engine. Admittedly, the index is small (about 10 blogs). 
http://blogsearchfrontend.interviewblindspots.com/?key=siberia

As you can see, query siberia also highlights liberties, simmering etc. The following is how the query and its options looks like. 
 const blogs = await axios.post(`${process.env.BACKEND_API}`, {        
    searches: [                                                         
      {
        collection: "blogs",
        facet_by: "category,aud,readingtime",                           
        highlight_full_fields: "text,title,imgs,category",
        max_facet_values: 30,                                           
        page: 1,                                                        
        per_page: 200,                                                  
        q: `${key}`,                                                    
        query_by: "text,title,imgs,category",
        query_by_weights: "2,2,2,1",                                    
      },
    ],  
  });             
## Steps to reproduce
Type any search term in the link above. 

## Expected Behavior

I want to know how I can make sure only strict results are returned and not fuzzy matches. In this case, the whole word must be present and not some part of the word. So, only results with words siberia must be present. 

## Actual Behavior

Word match is fuzzy. 

## Metadata

**Typsense Version**:
0.21.0
**OS**:
CentOS

**Comment by kishorenc** [comment]
Set `num_typos: 0` to disable fuzzy matching.
