### ISSUE TITLE
Support string fields for sorting or/and add the feature to the documentation

### ISSUE THREAD

**Issue by AlexanderHofmeister** [typesense/typesense#73]
## Description

[Describe the issue here]

Sorting for fields with type string is not supported

## Steps to reproduce

Add Collection:

`{
         "name": "employees",
         "fields": [
           {"name": "name", "type": "string"},
             {"name": "age","type": "float"}
         ],
         "default_sorting_field": "age"
       }`

Import data: 
`{"name":"Stark", "age": 45} {"name":"Captain Marvel", "age":22}`

Query:  `http://localhost:8108/collections/employees/documents/search?q=stark&query_by=name&sort_by=name:asc`

## Expected Behavior

Either support sorting for string fields or add the hidden feature to the documentation

## Actual Behavior

According to the documentation, it is not discribed how to add fields to sort by to the collection (only the default sort by is documentated, because it is required).  If no sort field was added to a collection, the below error message occurred. 

{
    "message": "Could not find a field named `name` in the schema for sorting."
}

## Metadata

**Typsense Version**: 0.10.1

**OS**: Windows 10

**Comment by kishorenc** [comment]
@AlexanderHofmeister Typesense is not designed to support sorting results on a string field. 

While you might have a genuine need for this, we noticed that for vast majority of search use cases, sorting alphabetically was not needed. It's also a very expensive operation, so it was left out.

**Comment by AlexanderHofmeister** [comment]
Thanks for pointing this out! :)
