### ISSUE TITLE
Get min and max values of a field in the result

### ISSUE THREAD

**Issue by Justin-Jordan** [typesense/typesense#734]
## Description
Hi, I would like to set up a slider on my site and have its minimum value match the minimum search value. I would also like to do the same for the maximum value.
When I looked in the documentation I didn't see any method to do that. The only option I have at the moment is to determine these values myself before returning the search result. But I fear a loss of performance.

## Metadata

**Typsense Version**: 0.23.1

**OS**: zorin os

**Comment by jasonbosco** [comment]
If you include an integer field in the `facet_by` search parameter, you'll get the min, max, avg values for that field in the response.

**Comment by Justin-Jordan** [comment]
thank you very much, i found the values i wanted
