### ISSUE TITLE
Problem with cyrillic symbols in the query text

### ISSUE THREAD

**Issue by Tobishua** [typesense/typesense#74]
## Description

When I trying to search items by field which contain cyrillic symbols, Typesense returns 0 results

## Steps to reproduce
Search with cyrillic symbols in **q** parameter:
`curl -sv -H "X-TYPESENSE-API-KEY: xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx" \
                             "https://my-typesense-host/collections/users/documents/search?q=Роман&query_by=first_name,last_name&per_page=10&sort_by=rating:desc"`

And with URL encoded symbols like this
`curl -sv -H "X-TYPESENSE-API-KEY: xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx" \
                             "https://my-typesense-host/collections/users/documents/search?q=%D0%A0%D0%BE%D0%BC%D0%B0%D0%BD&query_by=first_name,last_name&per_page=10&sort_by=rating:desc"`

## Expected Behavior

Display results from document
```
curl -H "X-TYPESENSE-API-KEY: xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx" -X GET \
                             "https://my-typesense-host/collections/users/documents/2"
```
`{"first_name":"Роман","id":"2","image":"15d38a528d8e524952098c46845ce52a","rating":0,"last_name":"Иванов","login":"userlogin","uid":40}`

## Actual Behavior

No results found

## Metadata

**Typsense Version**: 0.10.1

**OS**: Ubuntu 16.04.6 LTS (Docker 19.03.2)

**Comment by kishorenc** [comment]
@Tobishua Let me look into what's happening here and get back to you soon.

**Comment by kishorenc** [comment]
@Tobishua Can you please try this alpha build: https://dl.typesense.org/releases/typesense-server-0.11.0-alpha-linux-amd64.tar.gz

It has a fix for this issue. Let me know if you are still facing the problem.

**Comment by Tobishua** [comment]
@kishorenc Yes, it works! Problem fixed. Thank you so much :)
