### ISSUE TITLE
Error: self signed certificate

### ISSUE THREAD

**Issue by amamenko** [typesense/typesense#740]
I'm attempting to run a Typesense service in production using HTTPS protocol. I've generated a self-signed key (selfSignedCert.key) and certificate (selfSignedCert.crt) with OpenSSL and I'm providing them as arguments to the Typesense server script in production as such:

`--api-address=0.0.0.0 --api-port=8108 --enable-cors --ssl-certificate=./selfSignedCert.crt --ssl-certificate-key=./selfSignedCert.key`

I'm also using [gatsby-plugin-typesense](https://www.gatsbyjs.com/plugins/gatsby-plugin-typesense/) to index content post-build with a node as such:

```
{
    host: "0.0.0.0",
    port: "8108",
    protocol: "https"
}
```

The Typesense service starts up fine but when it comes to indexing, the following error is raised and the process exits:
```
warn Request #1: Request to Node 0 failed due to "DEPTH_ZERO_SELF_SIGNED_CERT self
 signed certificate"
warn Request #1 Sleeping for 0.1s and then retrying request...
warn Request #1 Request to Node 0 failed due to "DEPTH_ZERO_SELF_SIGNED_CERT self
 signed certificate"
warn Request #1: Sleeping for 0.1s and then retrying request...

 ERROR 

[Typesense] Could not create collection xyz: Error: self signed
certificate
```

Nothing is mentioned in the Typesense docs regarding using self-signed certificates in a production server so I'm not sure why this is not allowed.

I've seen in [this GitHub issue](https://github.com/typesense/typesense/issues/694) that @jasonbosco brought up getting an SSL certificate and using the server's hostname in the configuration. Why is a self-signed certificate throwing errors in this case?

**Comment by jasonbosco** [comment]
That error is coming from the OS. When you use a self-signed certificate, you'd also need to have the OS trust that certificate to prevent HTTP clients from throwing an error.

I wouldn't recommend using self-signed certificates in production. Here's more context on why: https://security.stackexchange.com/questions/112768/why-are-self-signed-certificates-not-trusted-and-is-there-a-way-to-make-them-tru

If you want to use them for testing on just your local machine, here's how to add your self-signed cert to the OS' trusted store: https://betterprogramming.pub/trusted-self-signed-certificate-and-local-domains-for-testing-7c6e6e3f9548

That's one Windows specific, but if you search for "Trust self-signed certificate <your OS>" you'll find other articles that show you how to do this.

**Comment by jasonbosco** [comment]
Here's a tool that helps simplify the process of creating local self-signed SSL certificates: https://github.com/FiloSottile/mkcert
