### ISSUE TITLE
Question: Possibility to search for available periods (dates)?

### ISSUE THREAD

**Issue by aaron5670** [typesense/typesense#746]
**Hi Typesense team,**
**First of all, thanks for this super search engine!**

I have a question regarding a use-case I'm trying to solve...

I have a dataset where there is a need to start searching for available periods. My question is whether this is currently possible with Typesense.
An example is that I want to search for all available accommodations available in the period ``2023-01-07`` to ``2023-01-10``.

Is this possible with Typesense? Or might I need to modify my dataset structure for this?

I would love to hear about it. Thanks in advance!

_**PS:** I am using the Typesense javascript library._

### My current dataset:
```json
[
  {
    "Name": "Villa with pool",
    "MaxPersons": 8,
    "AvailabilityPeriod": [
      {
        "ArrivalDate": "2023-01-05",
        "DepartureDate": "2023-01-08"
      },
      {
        "ArrivalDate": "2023-01-07",
        "DepartureDate": "2023-01-10"
      },
      {
        "ArrivalDate": "2023-01-22",
        "DepartureDate": "2023-01-26"
      },
      {
        "ArrivalDate": "2023-02-07",
        "DepartureDate": "2023-02-13"
      }
    ]
  },
  {
    "Name": "Cottage without wellness",
    "MaxPersons": 5,
    "AvailabilityPeriod": [
      {
        "ArrivalDate": "2023-01-05",
        "DepartureDate": "2023-01-07"
      },
      {
        "ArrivalDate": "2023-01-05",
        "DepartureDate": "2023-01-08"
      }
    ]
  }
]
```

**Comment by jasonbosco** [comment]
@aaron5670 You want to store timestamps as Unix timestamps in int64 fields in Typesense. 

I would also recommend structuring your data like this, so it's efficient to query:

In a collection called say availabilities:

```json
[
  {
    "ReservableId": 1,
    "Name": "Cottage without wellness",
    "MaxPersons": 5,
    "ArrivalDate": 1672898400,
    "DepartureDate": 1673071200
  },
  {
    "ReservableId": 1,
    "Name": "Cottage without wellness",
    "MaxPersons": 5,
    "ArrivalDate": 1672898400,
    "DepartureDate": 1673157600
  },
  {
    "ReservableId": 2,
    "Name": "Villa with pool",
    "MaxPersons": 8,
    "ArrivalDate": 1672898400,
    "DepartureDate": 1673071200
  },
  {
    "ReservableId": 2,
    "Name": "Cottage without wellness",
    "MaxPersons": 8,
    "ArrivalDate": 1672898400,
    "DepartureDate": 1673157600
  }
]
```

You can then use filter_by and numerical comparisons to get all reservations within a timeframe.

**Comment by aaron5670** [comment]
Hi @jasonbosco, 

Thanks for your neat solution!

I just have one more question, since obviously my dataset is made up of much more data...

Is it possible to do some kind of `INNER JOIN` on two different collections?

For example an `availabilities` collection and a `houseDetails` collection.
In the `availabilities` collection is all the available data of different properties and in the `houseDetails` collection are all the other data like swimming pool, the maximum number of people, location, pets allowed, etc...

I know that with Typesense you can perform a Federated / Multi Search, only then the results may differ. Is there by any chance another solution for this?


### Example of the houseDetails collection:
```json
[
  {
    "HouseId": 1,
    "Name": "Cottage without wellness",
    "MaxPersons": 5,
    "NumberOfBedrooms": 1,
    "NumberOfBathrooms": 2,
    "ExceedNumberOfBabies": 4,
    "Pool": true,
    "PetsAllowed": true,
    "EventsAllowed": true,
    "MinimumAge": 18,
    "DimensionM2": null,
    "NumberOfPets": 3,
    "Country": "NL",
    "Region": "wad",
    "HouseType": "Holiday home",
    "SkiArea": false,
    "NumberOfStars": 4,
    "WGS84Latitude": 53.4363,
    "WGS84Longitude": 5.48373,
    "OptionsAllowed": "No",
    "HolidayPark": null,
    "EnqeCount": 24,
    "EnqePoints": 218.9
  }
]
```

**Comment by jasonbosco** [comment]
Typesense doesn't support JOINs (See #229). 

So you would have to essentially "pre-join" the data into a single collection to achieve this. So you would have a single collection like this, with repeated fields:

```json
[
  {
    "ReservableId": 1,
    "Name": "Cottage without wellness",
    "ArrivalDate": 1672898400,
    "DepartureDate": 1673071200,
    "MaxPersons": 5,
    "NumberOfBedrooms": 1,
    "NumberOfBathrooms": 2,
    "ExceedNumberOfBabies": 4,
    "Pool": true,
    "PetsAllowed": true,
    "EventsAllowed": true,
    "MinimumAge": 18,
    "DimensionM2": null,
    "NumberOfPets": 3,
    "Country": "NL",
    "Region": "wad",
    "HouseType": "Holiday home",
    "SkiArea": false,
    "NumberOfStars": 4,
    "WGS84Latitude": 53.4363,
    "WGS84Longitude": 5.48373,
    "OptionsAllowed": "No",
    "HolidayPark": null,
    "EnqeCount": 24,
    "EnqePoints": 218.9
  },
  {
    "ReservableId": 1,
    "Name": "Cottage without wellness",
    "ArrivalDate": 1672898400,
    "DepartureDate": 1673157600,
    "MaxPersons": 5,
    "NumberOfBedrooms": 1,
    "NumberOfBathrooms": 2,
    "ExceedNumberOfBabies": 4,
    "Pool": true,
    "PetsAllowed": true,
    "EventsAllowed": true,
    "MinimumAge": 18,
    "DimensionM2": null,
    "NumberOfPets": 3,
    "Country": "NL",
    "Region": "wad",
    "HouseType": "Holiday home",
    "SkiArea": false,
    "NumberOfStars": 4,
    "WGS84Latitude": 53.4363,
    "WGS84Longitude": 5.48373,
    "OptionsAllowed": "No",
    "HolidayPark": null,
    "EnqeCount": 24,
    "EnqePoints": 218.9
  }
]
```

Even though the data is repeated in the records, in the in-memory index repeated values compress very well, so this wouldn't blow up RAM usage. It would require additional disk space though, since the raw data is store on disk as is.

**Comment by aaron5670** [comment]
Hi @jasonbosco,

Thanks so much for your clear explanation and help!

Is it still possible if there are about 50 million records? If this is possible what are the recommended server specs of this should be?

**Comment by jasonbosco** [comment]
Here's the guide on how to choose server specs: https://typesense.org/docs/guide/system-requirements.html

In your case, since there will be repeated words across records, RAM usage would more likely be towards the lower end of the 2x-3x range mentioned in the guide. 

The best way to estimate RAM usage would be take say 1M records, index them in a test server and see what actual RAM consumption is and extrapolate from there.

**Comment by aaron5670** [comment]
Thanks for the help @jasonbosco! 😃
