### ISSUE TITLE
How to enable Persistent data? 

### ISSUE THREAD

**Issue by mahmudtopu3** [typesense/typesense#748]
## Description

After rebooting the system the data is gone and need to reindex. Is there any way to keep it persistent? 

**Typsense Version**: 0.23.1

**OS**: Windows docker

**Comment by kishorenc** [comment]
I think you might be using `/tmp` as the data directory: this would be deleted by the OS on system restart.

**Comment by mahmudtopu3** [comment]
Thanks for the support. I have mounted it on a docker volume now.
