### ISSUE TITLE
Exact match and postfix search not working

### ISSUE THREAD

**Issue by ketan-hauper** [typesense/typesense#751]
I want to search one field by exact match and other by same as SQL like postfix search e.g 'apple%'  I want all the record which is starting with 'apple' . also want to do both thing in a single query with multiple search field.

I have a four filed to search, one of then is require  exact match and rest of will work based on postfix search, How can I achive it with react instant search with typesence.

**Comment by jasonbosco** [comment]
You can turn off prefix search for a particular field like this:

```
{
   q: "something",
   query_by: "field1,field2,field3,field4",
   prefix: "true,true,false,true"
}
```

This will do an exact match on field3, and a regular prefix search on the other fields.

**Comment by ketan-hauper** [comment]
hii @jasonbosco I already try it but it's not working for me, I am using typesence 0.21 version.

**Comment by jasonbosco** [comment]
Per-field prefix setting only works in the latest version of Typesense. Could you try on 0.23.1?

**Comment by ketan-hauper** [comment]
Yes currently I am doing that, I'll get back to you soon.

**Comment by ketan-hauper** [comment]
I update to 0.23.1 latest vesion but still it's not working, please see attached images one is query request, I am searching on {port} column and also adde prifix:false for it. but not getting the exact match result.
![Screenshot from 2022-10-12 11-48-36](https://user-images.githubusercontent.com/99339660/195265234-e9d641a5-d13a-41d8-8b9c-ca180f304362.png)
![sanboxResult](https://user-images.githubusercontent.com/99339660/195265280-9d6e755f-ea31-447a-84a3-9450c8b97144.png)

**Comment by ketan-hauper** [comment]
I also tried below latest demo from typesence github which is using all the leatst version and also there it's not working at all.
https://github.com/typesense/typesense-instantsearch-demo
![Screenshot from 2022-10-12 12-45-33](https://user-images.githubusercontent.com/99339660/195275250-05f834f2-c465-45b1-9632-d73c34a3f64e.png)

**Comment by jasonbosco** [comment]
Ah, this is actually typo tolerance kicking in. Could you also add these two parameters: 

```
num_typos: 0
typo_tokens_threshold: 0
```

**Comment by ketan-hauper** [comment]
> num_typos: 0
> typo_tokens_threshold: 0

Hey, thanks for sharing it, now exact match is working fine but with this setting I am getting issue with other fields prifix search please see attached images I have search for {192} and I have no of records exits with it but I am getting only 4 records can you please explain why it's happning? is thier any extra settings?
Search query request 
[
    {
        "query_by": "cryptoScoreCoarse,cryptoScore, port, serverAddress, clientAddress",
        "prefix": "true,true,false,true,true",
        "num_typos": "2,2,0,2,2",
        "typo_tokens_threshold": 0,
        "sort_by": "",
        "highlight_full_fields": "cryptoScoreCoarse,cryptoScore, port, serverAddress, clientAddress",
        "collection": "connections",
        "q": "192",
        "facet_by": "cryptoStrength,keyExchange,bulkEncryption,modeOfOperation,signature,hash,mac,protocol,zoneIn,zoneOut,clientos,serveros",
        "max_facet_values": 150,
        "page": 1,
        "per_page": 100
    }
![defaultResult](https://user-images.githubusercontent.com/99339660/195511381-6e346669-4b9a-4ead-b199-f7832ae9e28a.png)
![searchResult](https://user-images.githubusercontent.com/99339660/195511389-ca74512b-360c-495b-8e74-8a7144ccb5e3.png)


]

**Comment by jasonbosco** [comment]
Could you try upgrading to 0.24.0.rcn17 and also set `max_candidates: 1000` as another query parameter?

**Comment by ketan-hauper** [comment]
> 0.24.0.rcn17

Hi, typesence 0.24.0.rcn17 with max_candidates: 1000 setting is working fine for both case, exact match for single field and and prifix seach for rest of field, but typesence 0.24.0.rcn17 version is not availbale in your official doc, so is it reliable to use it?

**Comment by jasonbosco** [comment]
Here's how we plan our releases for more context around versioning and when we do GA releases: https://github.com/typesense/typesense/issues/732

We do have users running RC builds in production.

**Comment by ketan-hauper** [comment]
Okay, thanks. 
I've one more query, if I seatrch for **1.2** then I am getting result of **12** which is practically wrong so is there any setting to  make it work?
![sandbox5](https://user-images.githubusercontent.com/99339660/196331712-4df10d65-9120-4635-9323-15e0608536e3.png)

**Comment by jasonbosco** [comment]
By default, Typesense removes special characters when indexing. So `1.2` is indexed as `12`. If you want particular special characters to be indexed, you want to add it to the `symbols_to_index` setting when creating the collection. This setting is documented in this table [here](https://typesense.org/docs/0.23.1/api/collections.html#schema-parameters).

**Comment by ketan-hauper** [comment]
Thanks @jasonbosco it's working fine with that settings.
