### ISSUE TITLE
Multisearch does not work

### ISSUE THREAD

**Issue by kiloki-official** [typesense/typesense#753]
## Description

Trying to run a multisearch in my flutter app.

## Steps to reproduce

```
params = {
      'searches': [
        {
          'collection': 'messages',
          'filter_by': 'from:' + Prefs.getString("uid"),
        },
        {
          'collection': 'messages',
          'filter_by': 'to:' + Prefs.getString("uid"),
        }
      ],
      'limit_multi_searches': '50',
    };

    final commonSearchParams = {
      'q': '*',
      'page': page.toString(),
      'per_page': perPage.toString(),
      'group_by': 'thread',
      'sort_by': 'date:desc',
    };

    return typesenseClient.multiSearch
        .perform(params!, queryParams: commonSearchParams)
        .then((docs) {
      return docs["results"][0]["grouped_hits"];
    });
```

## Expected Behavior

Should return data that take into account both search parameters (from and to).

## Actual Behavior

It only take into account the first search parameter (from).

## Metadata

Flutter package, typesense: ^0.2.0

Thanks

**Comment by jasonbosco** [comment]
Each `search` inside a `multi_search` request is completely independent. The filters are not automatically combined. So the behavior you're seeing is expected.

You can achieve what you're trying to do in a single search like this:

```
    {
      'searches': [
        {
          'collection': 'messages',
          'filter_by': 'from:value1 && to:value2'
        }
      ],
    }
```

On a side note, you want to embed `limit_multi_searches` in a scoped search API key, so end users can't modify it.

**Comment by kiloki-official** [comment]
Hi, thanks for your quick response. I actually want an OR, not an AND. Your answer uses an AND (&&). How would you write it with an OR? Thanks

**Comment by jasonbosco** [comment]
v0.23.1 of Typesense does not support doing ORs across different fields. But we are actively working on adding support for this in the upcoming version as part of #281. Should hopefully be ready in a week or less, unless we run into any issues.

**Comment by kiloki-official** [comment]
Ok, once again, thanks for your response. I changed the structure of my database. The ability to do an OR query will definitely be super useful. Thanks
