### ISSUE TITLE
Is possible all synonyms delete in one  API?

### ISSUE THREAD

**Issue by dipudey** [typesense/typesense#759]
## Description

I have imported product names to a local instance of TypeSense running on ubuntu 20. I am inserting some synonyms of this collection. I want to delete all synonyms in one API.

## Expected Behavior

Should get all deleted synonyms in one API

## Actual Behavior
Only delete specific synonyms id

## Metadata

**Typsense Version**:

**OS**:
Ubuntu 20 LTS

**Comment by kishorenc** [comment]
We don't have a way to bulk delete synonyms. Will leave this issue open to track as a feature request.

**Comment by dipudey** [comment]
@kishorenc is any easy command for check current  typesense version? 

though I find typesense version by this `typesense-server --data-dir=/tmp/typesense-data --api-key=xyz --enable-cors`  command .

**Comment by kishorenc** [comment]
Yes, hit the /debug endpoint.

**Comment by unclescooby** [comment]
> Yes, hit the /debug endpoint.

Which should be added to the API docs ;)
