### ISSUE TITLE
[QUESTION] Retrieve a document by value

### ISSUE THREAD

**Issue by aaron5670** [typesense/typesense#761]
Hi Typesense,

I was wondering if it is possible to retrieve a single document by value. I know it is possible to retrieve a single document by ID ([see docs](https://typesense.org/docs/0.23.1/api/documents.html#retrieve-a-document)).

But is it also possible to get a single document by another field instead of by ID?

For example with slug?

```javascript
client.collections('companies').documents({slug: 'stark-industries'}).retrieve()
```

```json
{
  "id": "124",
  "company_name": "Stark Industries",
  "slug": "stark-industries",
  "num_employees": 5215,
  "country": "USA"
}
```

Thanks in advance!

**Comment by jasonbosco** [comment]
You can use filter_by to do this:

```javascript
client.collections('companies').documents().search({filter_by: 'slug:=stark-industries'})
```

**Comment by aaron5670** [comment]
Thanks @jasonbosco, I'll try :)
