### ISSUE TITLE
Compiling typesense with `-mno-sse4`

### ISSUE THREAD

**Issue by ianjosephwilson** [typesense/typesense#762]
## Description

Typesense docker container fails to start after receiving SIGILL / 132.  Local docker build also fails.

Instruction appears to be related to AMD's sse4 or greater.

## Steps to reproduce

Either:

- Start the published 0.23.1 docker container
- Build the development docker container and then build the deployment docker container and then start that container

## Expected Behavior

Some way to run typesense locally on amd64 with sse4a OR less.

## Actual Behavior

Typesense docker container fails to start after receiving SIGILL / 132.  Sometimes there is brief logging information before crash but usually there is absolutely no output.

## Metadata

**Typsense Version**:

`0.23.1`

**OS**:

```Linux 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux```

**Processor**:

```AMD Phenom(tm) II X4 955 Processor```

Supports sse4a but not sse4, sse4_1, sse4_2, etc.

**Comment by ianjosephwilson** [comment]
I saw you dropped arm specific flags here but left the amd64 specific flags:

https://github.com/typesense/braft/commit/80d97b2475b3c0afca79c19b64d46bb665d704f4

I think maybe this is the problem.   Is there a more scalable solution to compiling for the optimal arm or optimal amd64 targets as well as supporting a `native` compilation target ?

**Comment by ianjosephwilson** [comment]
I saw you write over the `CMakeLists.txt` in the development.Dockerfile is that the best solution to replace those flags?  Except create such an overwrite for the root `CMakeLists.txt` of braft ?

**Comment by kishorenc** [comment]
@ianjosephwilson 

So far, we have not had a reason to support a non-SSE4 capable X86 processor. If you want to do this, you can fork Typesense and just overwrite Braft's `CMakeLists.txt` to remove the `msse4` flags and rebuild Typesense locally. This should fix the issue you are facing.

**Comment by ianjosephwilson** [comment]
I just made a script to apply patches, ie. Remove flags , seems like brpc and braft both hardcoded sse4 flags, https://github.com/ianjosephwilson/typesense-patch

Starts now and I can connect without SIGILLs.
