### ISSUE TITLE
Synonyms gets deleted after a while

### ISSUE THREAD

**Issue by amine-y** [typesense/typesense#766]
## Description

Create a new synonyms for a while everything works fine
after a few hours the synonyms get's deleted 

## Steps to reproduce

curl --request PUT \
  --url https://localhost/collections/products/synonyms/phone\
  --header 'Content-Type: application/json' \
  --header 'X-TYPESENSE-API-KEY: mysecuretypesensekey' \
  --data '{
	"synonyms": [
		"iphone",
		"android"
	],
	"root": "phone"
}'

Then:
curl --request GET \
  --url https://localhost/collections/products/synonyms \
  --header 'X-TYPESENSE-API-KEY: mysecuretypesensekey'
The list of created synonyms shows as expected

wait a few hours then check 
curl --request GET \
  --url https://localhost/collections/products/synonyms \
  --header 'X-TYPESENSE-API-KEY: mysecuretypesensekey'
The synonyms list is empty

## Expected Behavior

when i call 

curl --request GET \
  --url https://localhost/collections/products/synonyms \
  --header 'X-TYPESENSE-API-KEY: mysecuretypesensekey'

The list should be there until I delete them manually

## Actual Behavior

when i call 

curl --request GET \
  --url https://localhost/collections/products/synonyms \
  --header 'X-TYPESENSE-API-KEY: mysecuretypesensekey'

The list is empty

## Metadata

Typsense Version: 0.23

OS: Linux ARM V8
Running  with 3 ec2 instances one manager and two slaves

**Comment by jasonbosco** [comment]
Could you make sure you're not using `/tmp` as your Typesense data dir? 

Also, do you have a process that deletes and recreates the collection? If so, when a collection is deleted, the synonyms are also deleted along with it. So that could be another reason.

**Comment by amine-y** [comment]
Hello,
@jasonbosco thanks for your quick answer I'm not using tmp dir but do collection sync that deletes the collection and the fill it again

**Comment by jasonbosco** [comment]
Before deleting the collection, you want to also export the synonyms from the old collection, and then recreate them in the new collection.
