### ISSUE TITLE
Typesense crash VM on GCP

### ISSUE THREAD

**Issue by huynv86** [typesense/typesense#768]
## Description

Today, Typesense make our server can't SSH. I restart server and then SSH normally. Then I start Typesense and see live log:
![image](https://user-images.githubusercontent.com/747614/198861495-73454677-fdf0-4e4d-a966-aa8698de7508.png)
when i saw last line log then SSH also die

we use TS in production and this is a nightmare :((

## Metadata

**Typsense Version**: 0.23.1

**OS**: ubuntu 20

**Comment by huynv86** [comment]
![image](https://user-images.githubusercontent.com/747614/198861656-6a741075-f92d-4e03-a3d3-b6246c71cd47.png)

**Comment by huynv86** [comment]
how i can access to rockdb and recovery data

**Comment by irevoire** [comment]
My typesense also stopped working, and I don't know either where are the documents situated in the rocksdb databases.

Currently, I found out that I could access the indexes via the key `$CM_`. I don't know what it means, but here you can see I got my `books` index prefixed by `$CM_` and I was able to find my other indexes as well:
```json
$CM_books: {
  "created_at": 1667121681,
  "default_sorting_field": "ratings",
  "fallback_field_type": "",
  "fields": [
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "title",
      "optional": false,
      "sort": false,
      "type": "string"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "author",
      "optional": false,
      "sort": false,
      "type": "string"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "ratings",
      "optional": false,
      "sort": true,
      "type": "int32"
    }
  ],
  "id": 0,
  "name": "books",
  "num_memory_shards": 4,
  "symbols_to_index": [],
  "token_separators": []
}
```

Hope this helps, I don't know where are the documents tho' 😒

**Comment by huynv86** [comment]
I can’t start Typesense, you can see the log i posted above, Typesense can’t load collection complete. How i can read raw documents in rocksdb then reindex them. I used Typesense as database and search engine @irevoire

**Comment by irevoire** [comment]
Hey @huynv86,
I'm not in the typesense team thus I don't really know what to say.
But from what I noticed when I was trying to restart typesense that it could corrupt your database so maybe the best thing to do right now is to NOT try to restart typesense for now.

If you can wait I'm probably going to release something for you in the next following days that can extract your documents and settings automatically for you 👍

**Comment by huynv86** [comment]
Thank u. I tried to start TS on my MacOS with RAM and CPU larger than Virtual machine GCP and TS start well
I guess one of our users do a query that found a document big size, this make TS crash, i think this is a bug of TS
To fix this: on my MacOS, i do query all documents then check which one is big size and delete it

**Comment by kishorenc** [comment]
@huynv86 

If there is a crash, there will be a stack trace in the logs. If you can share that we can get a sense of what happened. Ensure also that your VM did not run out of memory.

**Comment by huynv86** [comment]
You see last photo, TS writes the same lines log, also eats 100% CPU, that is reason why I can’t SSH. I tried rerun TS many time but doesn’t work 
I started TS and i watch log file in real time by command: tail -f path_to_logfile

**Comment by kishorenc** [comment]
Those log lines indicate that Typesense is loading the collection back into memory. Typesense is an in-memory data store (like Redis) so it will reindex the data back on a restart. That explains the CPU usage as well. Please email me the full log file to: contact@typesense.org and I can take a look at the events leading to the restart.

**Comment by irevoire** [comment]
I don't know if you're still interested @huynv86, but maybe it could help the next one.

I wrote a little tool around the typesense database.
With `cargo run -- typesense ~/data.sense` you can dump your whole db:
<img width="824" alt="image" src="https://user-images.githubusercontent.com/7032172/198899922-581e3bfb-52ab-4c5a-beab-592e56c195c7.png">

And then with 
```
  -i, --index <INDEX>  The index you want to dump
  -d, --documents      Use this flag to dump the document instead of the settings
```

You can select your collections or documents.

**Comment by huynv86** [comment]
Thank u @irevoire 
This is so helpful in case Typesense can’t start
I will remember u in next urgent case :)

**Comment by huynv86** [comment]
@kishorenc unfortunately, our technical deleted VM. close this
