### ISSUE TITLE
How do I migrate an individual project to a team project?

### ISSUE THREAD

**Issue by siman4457** [typesense/typesense#770]
## Description

We are using TypeSense in our project [OpenBeta](https://openbeta.io/). We started out with an individual account, but due to our growing team, we would like to migrate over to a team account. Is there an easy way to do this?

**Comment by jasonbosco** [comment]
@siman4457 I assume you're talking about Typesense Cloud. If so, if you open your cluster dashboard, you'll find an option to "Share access with your team" on the left-side nav bar. If you click on that, you'll be shown instructions to create a new team account and transfer the cluster into the team account and invite additional team members.
