### ISSUE TITLE
Is typesense suited for frequent document updates

### ISSUE THREAD

**Issue by britisharmy** [typesense/typesense#777]
I have a need to fetch documents with a higher rank score and updating document ranks on per minute basis. Is typesense able to handle frequent updates sometimes concurrent updates within a collection.

**Comment by jasonbosco** [comment]
The answer completely depends on the amount of CPU capacity / number of cores you have. You also want to make sure you batch updates into a few documents/import API calls, and not sending updates one at a time, to maximize performance.
