### ISSUE TITLE
peering-address ignored in config file but works using option flag or env variable

### ISSUE THREAD

**Issue by TinLe** [typesense/typesense#778]
## Description

Expected that peering-address=n.n.n.n would work in typesense-server.ini config.  But it does not.  Typesense would only use the value if it is specified as command line flag, e.g. via '--peering-address=n.n.n.n'

Look like using TYPESENSE_PEERING_ADDRESS env var works.

## Steps to reproduce

Add peering-address=192.168.1.1 in typesense-server.ini and start typesense.  The value is completely ignored as show in log file.

Removed the value from config and restarted typesense using '--peering-address=192.168.1.1' at command line and then it works.

## Expected Behavior

Flag options should also work if specified in config file.

## Actual Behavior

The specified value in config file is ignored and only work if specified using CLI flag or env variable.

## Metadata

Typesense version 0.23.1

Ubuntu 20.04.1 x86_64 (also tested on 22.04.1 x86_64)

**Comment by kishorenc** [comment]
@TinLe 

I'm not able to reproduce this issue. I created a fresh `/tmp/data` directory and started Typesense this way:

```
./typesense-server --config=/tmp/config.ini
```

Contents of `/tmp/config.ini`:

```
[server]

peering-address = 127.0.0.1
data-dir = /tmp/data
api-key = abcd
```

I see the following in logs:

```
Typesense peering service is running on 127.0.0.1:8107
```

I then stopped the server, changed the `peering-address` to an internal IP like `172.17.0.3` and then restarted the server again and this time, I correctly see:

```
Typesense peering service is running on 172.17.0.3:8107
```

**Comment by TinLe** [comment]
@kishorenc hmm, you are right. I am unable to reproduce this error again in my test environment.   I'll close this bug, and re-open if I can reliably reproduce it again.

Thank you for looking into it.
