### ISSUE TITLE
Geolocation / Geosearch

### ISSUE THREAD

**Issue by natew** [typesense/typesense#78]
Just curious about plans for support

**Comment by kishorenc** [comment]
@natew Yes, that's on the todo list. What kind of features would you like apart from the ability to sort the results based on a given lat long (i.e. returning search results closest to a given geographical location).

**Comment by natew** [comment]
Beyond that I don't know, yet.

**Comment by hutbert** [comment]
A great addition to this would be to have the ability to define a polygon and then search for items within a polygon. See https://dev.mysql.com/doc/refman/5.7/en/gis-class-polygon.html for this feature in MySQL. That might be a pretty big stretch though.

**Comment by jasonbosco** [comment]
@hutbert Certainly on our radar :) If you'd like, happy to connect live so I can understand your use case and prioritize this feature. Would help ensure that we ship something with proven practical value.

**Comment by hutbert** [comment]
@jasonbosco I don't have a specific use case so I wouldn't prioritize anything on my account. We have run into situations on some projects where our clients want to limit searches within particular boundaries (like within city limits) rather than by a radius around a fixed point. My primary use case would be sorting by distance for sure but thought this might be a good addition.

**Comment by 0xflotus** [comment]
Geo distance queries (with various units) would be a massive feature 🎉

```http
GET /collections/:collection/documents/search?lat=50&lon=12&distance=12%20km HTTP/1.1
```

**Comment by Elliot-Pitts** [comment]
For a project I have coming up, I would love to use Typesense but the lack of geosearch is a hurdle. Just a simple distance query as @0xflotus suggested would be great to start with.

**Comment by rodrigoTrespalacios** [comment]
I was also looking to use a hosted version of Typesense for a new project, but the only thing blocking me is the lack of geosearch which is a main feature of my application. A distance based query would be enough for me too.

**Comment by daamsie** [comment]
Also evaluating Typesense and this is a feature I'd need to see to be able to make the switch.

Particular use case is searching for hotels within a certain geographic area, or near a point of interest. Searching within a bounding polygon is important for this scenario. 

Another thing is to boost the ranking of results based on proximity to a location. 

Specific use case is searching for points of interest. When a user types ie.. "Zoo", I would want the nearest zoo to be returned based on their geolocation. 

I'll keep an eye on this task to see how it progresses.

**Comment by cboothe** [comment]
Hi @jasonbosco I noticed there is a geosearch branch but it hasn't been touched since January. 
Are you still working or planning this feature?

**Comment by jasonbosco** [comment]
Hi @cboothe, geosearch is definitely still planned! In fact we got about 80% of the work done, but some other high priority requests and issues showed up, so we had to put this on pause, while we tackle those.

**Comment by kishorenc** [comment]
I'm excited to announce a preview build for the geo search feature!

Please use this docker image: `typesense/typesense:0.21.0.rc7`

I've put together a quick guide here: https://gist.github.com/kishorenc/1f537c728f89960048272a03d36bad01

I look forward to hearing your feedback.

**Comment by daamsie** [comment]
Looks great! Very close to meeting my needs. Will the geo data be available as a ranking signal as well? Ie, I'd like to search for all results by keyword "park" , but have the ones nearest to me returned first.

**Comment by jasonbosco** [comment]
@daamsie Yes! You can use the sort_by field to rank based on proximity to a given lat/lng: 

```
sort_by=location(48.853, 2.344):ASC
```

**Comment by kishorenc** [comment]
Geosearch has shipped as part of `v0.21.0`. Thank you everyone for your kind feedback and comments.

**Comment by nandorojo** [comment]
Would it be possible to add IP-address-based geofencing, similar to `aroundLatLngViaIP` from Algolia?

**Comment by jasonbosco** [comment]
@nandorojo We're tracking that request as part of #539
