### ISSUE TITLE
[Feature Request] Ability to change maximum page size, beyond 250

### ISSUE THREAD

**Issue by shejal-Hauper-fe** [typesense/typesense#780]
I need to add a feature that downloads the table record in CSV format when I click the export to csv button. I want to retrieve all of the data from the query, not just the first 250 entries. What are my options in this scenario?

This is the screenshot of the  error I'm facing:
![limitation-error](https://user-images.githubusercontent.com/103435307/200739567-31797161-d753-4eef-b18f-9022f88aac54.png)

This is the query string:
"searches": [
      {
        "query_by": "cryptoScoreCoarse,cryptoScore",
        "sort_by": "",
        "highlight_full_fields": "application",
        "collection": collection,
        "q": "*",
        "facet_by": "cryptoStrength,keyExchange,bulkEncryption,modeOfOperation,signature,hash,mac,protocol,zoneIn,zoneOut,clientos,serveros",
        "max_facet_values": 150,
        "page": 1,
        "per_page": 2000
        
      }
    ]

**Comment by shejal-Hauper-fe** [comment]
I found one opened ticket regarding this:
https://github.com/typesense/typesense/issues/672
However, if we have 10M data and receive 250 each time, there would be 4000 requests (1,000,000/250), which could cause the system to crash.

**Comment by jasonbosco** [comment]
You can use the documents export endpoint to export the entire dataset without pagination. But it only supports `filter_by` and not the `q` parameter.

**Comment by shejal-Hauper-fe** [comment]
@jasonbosco thanks for the quick response. Now I want to search data and based on sorted result I want to export it in CSV what I can do for this?

**Comment by mahmudtopu3** [comment]
It will be better if the limit is modifiable so that one can increase even though the performance will get down.

**Comment by Clasyc** [comment]
Yes it would be great to have option on modifying the limit.

**Comment by rahularoradfs** [comment]
+1

**Comment by chrysos** [comment]
+1

**Comment by garygreen** [comment]
## **Algolia** has a max limit of **1,000**

![image](https://github.com/typesense/typesense/assets/1702638/2dd2a55d-3973-4355-958d-36eefb70d8ad)

## **Meilisearch** has a max limit of **1,000**

![image](https://github.com/typesense/typesense/assets/1702638/ca1f9775-5de7-4499-afa6-18e799bdd925)

## **ElasticSearch** has a max limit of **10,000** (with a caution on memory usage, but leaves that in the users court)

![image](https://github.com/typesense/typesense/assets/1702638/db603290-2cc4-4c3d-8f84-e475b7071119)

## **Typesense** is **250** (**-75% less** than the listed search engines)

---

I'd be curious to know how all the other search engines are able to handle 75% more hits, but Typesense has this hard limit in place.

The [suggestion of performing multi http-requests](https://github.com/typesense/typesense/issues/672#issuecomment-1195000554) to fetch more than 250 results is not a solution - the speed is now network bound, will have to be synchronous requests, some queries will be difficult to impossible (e.g. to contextually marry up and match the previous network requests results, sorting, faceted search, etc), and overall be considerably slower more memory intensive than simply upping the limit?

Hopefully Typesense can bring this limit more in line with other search engines.

**Comment by jasonbosco** [comment]
@garygreen To clarify, the limit you mentioned in Algolia and Meilisearch is 1K docs max per search - meaning that _even with pagination_ you cannot fetch more than 1K docs. 

Whereas, in Typesense, if a search query matches 15K docs, you can fetch _ALL_ 15K docs, except that you need to use pagination and fetch 250 per page. 

> The https://github.com/typesense/typesense/issues/672#issuecomment-1195000554 to fetch more than 250 results is not a solution - the speed is now network bound

This is not network bound since it's still just a single http request, with multiple searches inside it - one search for each page. For eg:

```bash
curl "http://localhost:8108/multi_search?query_by=name" \
        -X POST \
        -H "Content-Type: application/json" \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
        -d '{
          "searches": [
            {
              "collection": "products",
              "q": "shoe",
              "page": "1",
              "per_page": "250"
            },
            {
              "collection": "products",
              "q": "shoe",
              "page": "2",
              "per_page": "250"
            },
            {
              "collection": "products",
              "q": "shoe",
              "page": "3",
              "per_page": "250"
            }
          ]
        }'
```

**Comment by garygreen** [comment]
@jasonbosco Thanks for the clarification. Curious to know how the `page` works behind the scenes with Typesense, does it re-use the same data from the existing query, or does it perform the search algorithms again? Also if you were to do `page=6` does it throw away the data for pages 1-5? E.g. a bit like mysql `limit` clause... as the size increases the query gets slower and slower.

**Comment by garygreen** [comment]
It does appear each multi search is handled separately, performing the same search algorithms, sorting, etc - additionally it appears to throw away results during the offset part. This doesn't seem particularly efficient.

https://github.com/typesense/typesense/blob/3bbfe20fcc126fa1a26099ff0022e235e81d1662/src/collection.cpp#L1737-L1776

I did some testing with Typesense multi search (6 multi searches) vs Elastic Search to get the same number of hits (1,500), and Typesense took around 1.5s and Elastic Search 300ms. I suspect the gap would closer significantly if the hits limit wasn't in place and didn't request separate paginated multi-search.

**Comment by phungtranminh** [comment]
Not sure if it is just me but it looks like that using `multi_search` is just a stop-gap option? And we have to merge the results before displaying the results before rendering?

I don't understand typesense enough so it would be very helpful if you guys provide some light why making 250 a configuration so difficult? since the issue has been here for 1 year?

For certain operations/apps, it is really helpful to get more than 250 results.

**Comment by skilljobs** [comment]
I think many users are ready to accept the downside of increasing the limit of 250 per page. 
If the limit is changed, will there be any breaking changes?

**Comment by vivdesign** [comment]
We absolutely are willing to accept the downside of this, please make this configurable!

**Comment by andtii** [comment]
We are currently using meilisearch for a targeting based system where we can find up to 100.000 user ids based on some filtering. And meilisearch easily return 30.000 rows of ids in like 300ms and 100.000 is like about 1 seconds. We where looking into typesense since it has scale out support but we get 30.000 rows of ids using multi request pagination in like 4-5 seconds which is way to slow for us. This is a showstopper for us so we need to stick to meilisearch :(

**Comment by jasonbosco** [comment]
You can now change the max page size in v27.1 and above using the `max-per-page` server-side parameter.
