### ISSUE TITLE
Facet search highlight cuts off for some chars

### ISSUE THREAD

**Issue by flevi29** [typesense/typesense#786]
## Description

Facet search highlight cuts off for `Szabó` right at the end before the special char, resulting in `<mark>Szab</mark>`. I am mainly concerned right now about the [Hungarian alphabet special characters](https://en.wikipedia.org/wiki/Hungarian_alphabet).

## Steps to reproduce

Minimal reproduction repo: https://github.com/flevi29/typesense_facet_counts_bug

## Expected Behavior

I expect these highlights not to cut off.

## Actual Behavior

It cuts off.

## Metadata

**Typsense Version**: 0.23.1

**OS**: Windows 11 (Docker Typesense so N/A really)

**Comment by kishorenc** [comment]
@flevi29 

Thanks, I'm able to reproduce this issue. We're on code freeze for 0.24 release, so will be taking this up right after that and will have the fix available on a 0.25 RC build.

**Comment by kishorenc** [comment]
Fixed in `0.26.0.rc65`.

**Comment by euneuber** [comment]
I can confirm that `0.26.0.rc65` works es expected!

Looking forward to the release!

**Comment by lazka** [comment]
If someone ends up here, I found a similar issue in newer typesense v29: #2440
