### ISSUE TITLE
A search hangs when split_join_tokens is set to always

### ISSUE THREAD

**Issue by Sembiance** [typesense/typesense#788]
When running typesense `0.24.0.rcn25-log1` setting `split_join_tokens : "always"` for a specific search causes the search to hang forever with a specific dataset. The main query is `q : "amanda"`

My current workaround is setting `split_join_tokens : "fallback"` which works great, same search returns fast.

Exact reproducible steps below, including test data.

Create our data dir and run the server:
```
mkdir data
typesense-server --data-dir=./data --api-key=TESTCASEKEY --api-address=127.0.0.1 --api-port=8108 --peering-address=127.0.0.1 --peering-port=8107
```

Create the `twig` collection:
```
curl "http://localhost:8108/collections" -X POST -H "Content-Type: application/json" -H "X-TYPESENSE-API-KEY: TESTCASEKEY" -d '{
"name" : "twig",
"fields" : [
{ "name" : "filename", "type" : "string", "sort" : true },
{ "name" : "size", "type" : "int64" },
{ "name" : "nsfw", "type" : "int32" },
{ "name" : "itemid", "type" : "int32", "facet" : true },
{ "name" : "catid", "type" : "int32", "facet" : true },
{ "name" : "genreid", "type" : "int32", "facet" : true },
{ "name" : "family", "type" : "string", "facet" : true },
{ "name" : "formatid", "type" : "string", "facet" : true, "optional" : true },
{ "name" : "hash", "type" : "string", "optional" : true, "facet" : true, "sort" : true },
{ "name" : "ts", "type" : "int64", "optional" : true },
{ "name" : "content", "type" : "string", "optional" : true },
{ "name" : "ext", "type" : "string", "optional" : true },
{ "name" : "label", "type" : "string[]", "optional" : true },
{ "name" : "duration", "type" : "int32", "optional" : true },
{ "name" : "width", "type" : "int32", "optional" : true },
{ "name" : "height", "type" : "int32", "optional" : true },
{ "name" : "animated", "type" :  "bool", "optional" : true },
{ "name" : "title", "type" : "string", "optional" : true },
{ "name" : "subCount", "type" : "int32", "optional" : true, "index" : false },
{ "name" : "href", "type" : "string", "optional" : true, "index" : false },
{ "name" : "contentURL", "type" : "string", "optional" : true, "index" : false },
{ "name" : "extra", "type" : "string", "optional" : true, "index" : false }
] }'
```

Download the docs and index them, this will take a while.
The zip is 13GB which unpacks to 54GB and Typesense DB uses 26GB on disk and 89GB of RAM.
Sorry it's so big. I tried bisecting it into smaller chunks, but the problem didn't occur in the smaller datasets I tried.
```
wget "https://telparia.com/wip/bugDocs.zip"
unzip bugDocs.zip
cd bugDocs
for i in *.jsonl; do curl --silent "http://127.0.0.1:8108/collections/twig/documents/import" -X POST -H "X-TYPESENSE-API-KEY: TESTCASEKEY" --data-binary @"$i" | sort | uniq -c; done
```

Verify we have `num_documents : 27716368`: `curl "http://127.0.0.1:8108/collections/twig" -X GET -H "X-TYPESENSE-API-KEY: TESTCASEKEY"`

Download and extract the attached search file [split_join_tokens_bug_search.json.zip](https://github.com/typesense/typesense/files/9997716/split_join_tokens_bug_search.json.zip) query:
```
curl --silent "http://127.0.0.1:8108/multi_search?query_by=content,ext,filename,title" -X POST -H "Content-Type: application/json" -H "X-TYPESENSE-API-KEY: TESTCASEKEY" --data-binary @"split_join_tokens_bug_search.json"
```

The search will go forever, or seemingly forever.

If this is deemed not to be a bug, I suggest:
1. Warning in the docs that setting `split_join_tokens : "always"` can cause run-away searches
2. Allow the `search_cutoff_ms` to properly interrupt the `split_join_tokens` operation instead of going forever

**Comment by kishorenc** [comment]
Turned out to be the same issue as https://github.com/typesense/typesense/issues/789
