### ISSUE TITLE
Wrong Facet counts

### ISSUE THREAD

**Issue by jd-0001** [typesense/typesense#79]
## Description

Hello,
Initially when I receive my facets my facets are equal to total items in my TS server(due to no filters).
```
Num of records: 304
```
  
Next, when I type query using `?q=a` it filter it out and shows me correct facets counts
```
Num of records: 174
```

Now if I update query as `?q=ad` it shows me facet counts higher than my total total items
```
Num of records: 539
```

## Steps to reproduce

Try writing query of 2 characters without any filters

## Expected Behavior

It should narrow down result on each character I suppose and should not return more than total items

## Actual Behavior

It shows facet counts more than total items

## Metadata

**Typsense Version**: 0.3.0

**OS**: Ubuntu 18.04

Here's GIF showing issue:
![ts](https://user-images.githubusercontent.com/47495003/69868749-b48f2900-12d0-11ea-8fad-e8c564d2da2e.gif)

**Comment by kishorenc** [comment]
@jd-0001 Happy to investigate what's happening here. Can you please recheck the version of Typesense you are using? You've mentioned it as `0.3.0` while the current stable version is `0.11.0`: https://typesense.org/downloads/

Also, is it possible for you to share a sample dataset that exhibits this issue with me? You can email me at contact at typesense dot org.

**Comment by jd-0001** [comment]
Sorry @kishorenc for late reply actually I was on holidays for couple of days. Yeah, sure current latest version is 0.11.0 and I am using 0.3.0. There's major version gap due to inactive development of this project. When I was workig on this in past latest version was 0.3.0.

I didn't updated it as I thought I have to rewrite some of my code before I actually make it work. But no worries I will update typeSense to latest and get back to you. And also I will share sample dataset if this issue exist.

Regards.

**Comment by jd-0001** [comment]
Hello @kishorenc This issue still exist with latest version of typeSense. I have sent you email please let me know if you received it or not. I used `kishore@kishorelive.com`

**Comment by jd-0001** [comment]
It is solved in 0.12.x

**Comment by bfine9618** [comment]
We are using 0.12.1 and have a 0.19.0 Typesense Server.

We have a query of about 1.3M records, with about 93k in an Arts category. when we query "pets", our facet count returns all 93k Arts category for some unknown reason. 

here is the endpoint. you can pass the `query` and `filters` parameters in the URL.
[Search](http://staging-api.roundupapp.com/institutions/search?query=pets)

It still doesn't seem to be fixed...

**Comment by kishorenc** [comment]
@bfine9618 Happy to help figure out what's going wrong here. Is it possible for you to share this dataset with us? You can just zip the Typesense data directory and email us the link to download it from. We will purge the data once we finish testing it.

We also need the exact query that is sent to Typesense server, e.g. with query and facet fields queried.
