### ISSUE TITLE
Filter_by if field exists

### ISSUE THREAD

**Issue by acleave** [typesense/typesense#798]
## Description
Trying to query a dataset and filter the results to show only the documents that have an optional field present. I have tried filter_by with and without infix:true on the optional field.

## Steps to reproduce

Sample collection

{
    "name": "John",
    "image": "/assets/john.jpg",
},
{
    "name":"Bob"
}

I am trying to query and filter all the results for only documents that contain the optional "image" field

Have tried using infix and filter_by=image:"/assets"

Also tried filter_by=image:!=""

## Expected Behavior
Would expect it to return only documents that have the "image" field

## Actual Behavior
It doesn't return any documents or gives an error on the filter query  when doing something like:

filter:        filter_by=image:!=""
error:        Error parsing additional search parameter. Please enter it as parameter=value one at a time, and press enter.

## Metadata

**Typesense Version**: 0.23.1
**OS**: Typesense hosted

Testing using the Typesense Search dashboard

**Comment by jasonbosco** [comment]
A workaround for this would be to create a new bool field called say `image_exists: true | false` in each document that you compute at indexing time and then you should be able to do:

```
filter_by: image_exists:true
```

**Comment by kishorenc** [comment]
Definitely want to support this in near future. Closing this issue in favor of another issue that's tracking this feature request here: https://github.com/typesense/typesense/issues/790
