### ISSUE TITLE
Getting "typesense.exceptions.RequestUnauthorized: Forbidden - a valid `x-typesense-api-key` header must be sent."

### ISSUE THREAD

**Issue by erlanenazarov** [typesense/typesense#80]
I'm just followed [this tutorial](https://typesense.org/docs/0.11.0/api/) on python and got stalled when starting an example. Catched error:

```
typesense.exceptions.RequestUnauthorized: Forbidden - a valid "x-typesense-api-key" header must be sent.
```

Server running in docker:

```
docker run -p 8108:8108 -v/tmp/data:/data typesense/typesense:0.11.0 --data-dir /data --api-key=cea658ba2d55cf155ab2b920cc14d6d00edd0bf2da21a3aa2163c3d7b57ef592
```

Typesense client config:

```
search_engine_client = typesense.Client({
    'master_node': {
        'host': 'localhost',
        'port': '8108',
        'protocol': 'http',
        'api_key': 'cea658ba2d55cf155ab2b920cc14d6d00edd0bf2da21a3aa2163c3d7b57ef592'
    },
    'timeout_seconds': 2
})
```

```
~# python client.py

Traceback (most recent call last):
  File "client.py", line 33, in <module>
    {"name": "company_name", "type": "string"},
  File ".env/lib/python3.6/site-packages/typesense/collections.py", line 20, in create
    return self.api_call.post(Collections.RESOURCE_PATH, schema)
  File ".env/lib/python3.6/site-packages/typesense/api_call.py", line 69, in post
    raise ApiCall.get_exception(r.status_code)(error_message)
typesense.exceptions.RequestUnauthorized: Forbidden - a valid `x-typesense-api-key` header must be sent.
```

**Typsense Version**: 0.11.0

**OS**: MacOS Mojave 10.14.6

**Comment by kishorenc** [comment]
@erlanenazarov I'm not able to reproduce this issue. Here's the full sequence I tried with:

1. On a fresh virtualenv, ran `pip install typesense`
2. Started Typesense: `docker run -p 8108:8108 -v/tmp/data:/data typesense/typesense:0.11.0 --data-dir /data --api-key=cea658ba2d55cf155ab2b920cc14d6d00edd0bf2da21a3aa2163c3d7b57ef592`
3. Ran the following file: https://gist.github.com/kishorenc/1c0d59262025fdf4dd4f3d8113e9d17c

This worked fine for me. I also looked into the code and for `POST`, the header is being passed along here: https://github.com/typesense/typesense-python/blob/master/typesense/api_call.py#L64

So I am not really sure what's happening. Can you try the above steps on a fresh virtualenv again and let me know what happens?

**Comment by erlanenazarov** [comment]
Seems to be magic. I don't know what happen but after reloading project everything works fine

**Comment by kpost** [comment]
Piggybacking on this.

I'm having the same issue when I use Typesense in docker-compose.

```version: '3'
services:
  typesense:
    command: bash -c "./typesense-server"
    image: typesense/typesense:0.11.2
    volumes:
      - /tmp/typesense-data:/data
    ports:
      - '8108:8108'
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY='myapikey'```
