### ISSUE TITLE
Chinese queries unable to return hits with matched strings unless there is a space at the start

### ISSUE THREAD

**Issue by sezooka2** [typesense/typesense#800]
![20221119_12320](https://user-images.githubusercontent.com/118556288/202765335-9e6aa0c4-0aa3-458c-a7e5-691934cdc3fb.jpg)
![20221119_12339](https://user-images.githubusercontent.com/118556288/202765344-c5421733-f0c8-42c1-8451-fd070581163a.jpg)

**keyword:**
第一篇

**Data:**
`{
  "cat_link": [
    "http://test.anli.news/?cat=1"
  ],
  "category": [
    "未分类"
  ],
  "comment_count": 1,
  "is_sticky": 0,
  "permalink": "http://test.anli.news/?p=1",
  "post_author": "sezooka",
  "post_content": "欢迎使用WordPress。这是您的第一篇文章。编辑或删除它，然后开始写作吧！",
  "post_date": "2022-11-17 02:23:04",
  "post_excerpt": "",
  "post_id": "1",
  "post_modified": "2022-11-17 02:23:04",
  "post_thumbnail": "",
  "post_thumbnail_html": "",
  "post_title": "世界，您好！",
  "post_type": "post",
  "sort_by_date": 1668651784
}`

**Comment by alphatownsman** [comment]
do you have `'locale': 'zh'` for string fields in your schema? e.g. `post_content` in your case

**Comment by alphatownsman** [comment]
> Now, when you search using the query "第一篇", there is no match because that word does not occur in the corpus because of the way the text has been split. Should "第" always prefix any number like "一"?

Not sure it's the case, I just did a quick test, search `第一篇` does return the item with `这是您的第一篇文章`, as long as `locale` is set to `zh`

**Comment by kishorenc** [comment]
My bad, setting `locale` to `zh` in the schema indeed ensures that this works as expected. Thank you for the astute observation @alphatownsman. 

@sezooka2 

Please create your collection with a schema that contains the correct locale. For example, `post_content` should look like this (note the `"locale": "zh",` line.):

```
{
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "zh",
      "name": "post_content",
      "optional": false,
      "sort": false,
      "type": "string"
}
```
