### ISSUE TITLE
Pinned hits don't respect `group_by`

### ISSUE THREAD

**Issue by 527bd5** [typesense/typesense#801]
## Description
Hits aren't correctly grouped together when pinning hits.

## Steps to reproduce

See the [following Python script to reproduce](https://pastebin.com/FdsaEVsb). 

## Expected Behavior

```
Result 0 has group key ['hp']
Result 1 has group key ['lotr']
```

## Actual Behavior

```
Result 0 has group key ['hp']
Result 1 has group key ['lotr']
Result 2 has group key ['hp']
```

## Metadata

**Typsense Version**: 0.23.1, 0.24.0rc20, and 0.24.0rcn32

**OS**: Running Typesense Docker image

**Comment by kishorenc** [comment]
@527bd5 

Thank you for reporting this issue. I can reproduce the behavior -- I will investigate and keep you posted on the fix.

**Comment by kishorenc** [comment]
@527bd5 

Sorry for the delay. There's a fix in this Docker build that you can try: `typesense/typesense:0.25.0.rc25`

Let me know how it works.
