### ISSUE TITLE
Vector search with 300 dimensions gets stuck

### ISSUE THREAD

**Issue by mtruyens** [typesense/typesense#802]
I'm trying the new vector search described in https://gist.github.com/kishorenc/f008c3a60ee58cb084b0c33c0dbce148 

I would like to use semantic vectors with 300 dimensions — quite higher than the 4 dimensions mentioned in the example, but not unusual in the Word2Vec universe. 

Uploading just a few documents works fine, but as soon as the number of documents gets over about 100, TypeSense seems to get stuck and does not finish, with the queue not getting lowered anymore. 

* Running the Docker 0.24.0rnc34
* Documents are fairly light (2KB each)
* I tried both sequential and parallel import calls using the Clojure client, which uses a batch size of 20. 

Relevant part of the log for sequential calls:
I20221122 08:58:46.292029   135 raft_server.cpp:544] Term: 2, last_index index: 26, committed_index: 26, known_applied_index: 26, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 1763
I20221122 08:58:46.292714   170 raft_server.h:60] Peer refresh succeeded!
I20221122 08:58:56.314785   135 raft_server.cpp:544] Term: 2, last_index index: 33, committed_index: 33, known_applied_index: 33, applying_index: 0, queued_writes: 2, pending_queue_size: 0, local_sequence: 2458
I20221122 08:58:56.315157   171 raft_server.h:60] Peer refresh succeeded!
I20221122 08:59:06.337203   135 raft_server.cpp:544] Term: 2, last_index index: 33, committed_index: 33, known_applied_index: 33, applying_index: 0, queued_writes: 2, pending_queue_size: 0, local_sequence: 2458
I20221122 08:59:06.337772   170 raft_server.h:60] Peer refresh succeeded!
I20221122 08:59:08.195047   136 batched_indexer.cpp:264] Running GC for aborted requests, req map size: 1
I20221122 08:59:16.357936   135 raft_server.cpp:544] Term: 2, last_index index: 33, committed_index: 33, known_applied_index: 33, applying_index: 0, queued_writes: 2, pending_queue_size: 0, local_sequence: 2458
I20221122 08:59:16.358584   171 raft_server.h:60] Peer refresh succeeded!

.... it then gets stuck — e.g. 8 minutes later: 

I20221122 09:08:07.719950   170 raft_server.h:60] Peer refresh succeeded!
I20221122 09:08:17.742333   135 raft_server.cpp:544] Term: 2, last_index index: 34, committed_index: 34, known_applied_index: 34, applying_index: 0, queued_writes: 3, pending_queue_size: 0, local_sequence: 2459
I20221122 09:08:17.743017   171 raft_server.h:60] Peer refresh succeeded!
I20221122 09:08:18.426398   136 batched_indexer.cpp:264] Running GC for aborted requests, req map size: 2
I20221122 09:08:27.765873   135 raft_server.cpp:544] Term: 2, last_index index: 34, committed_index: 34, known_applied_index: 34, applying_index: 0, queued_writes: 3, pending_queue_size: 0, local_sequence: 2459
I20221122 09:08:27.766403   170 raft_server.h:60] Peer refresh succeeded!

Log for parallel calls is similar, but what gets stuck in the queue is much higher:
I20221122 08:54:31.374725   135 raft_server.cpp:544] Term: 2, last_index index: 92, committed_index: 92, known_applied_index: 92, applying_index: 0, queued_writes: 36, pending_queue_size: 0, local_sequence: 868
I20221122 08:54:31.375386   171 raft_server.h:60] Peer refresh succeeded!
I20221122 08:54:41.393976   135 raft_server.cpp:544] Term: 2, last_index index: 97, committed_index: 97, known_applied_index: 97, applying_index: 0, queued_writes: 41, pending_queue_size: 0, local_sequence: 873
I20221122 08:54:41.394527   172 raft_server.h:60] Peer refresh succeeded!
I20221122 08:54:51.423941   135 raft_server.cpp:544] Term: 2, last_index index: 97, committed_index: 97, known_applied_index: 97, applying_index: 0, queued_writes: 41, pending_queue_size: 0, local_sequence: 873
I20221122 08:54:51.424808   171 raft_server.h:60] Peer refresh succeeded!
I20221122 08:55:01.445763   135 raft_server.cpp:544] Term: 2, last_index index: 97, committed_index: 97, known_applied_index: 97, applying_index: 0, queued_writes: 41, pending_queue_size: 0, local_sequence: 873
I20221122 08:55:01.445969   172 raft_server.h:60] Peer refresh succeeded!
I20221122 08:55:11.474313   135 raft_server.cpp:544] Term: 2, last_index index: 97, committed_index: 97, known_applied_index: 97, applying_index: 0, queued_writes: 41, pending_queue_size: 0, local_sequence: 873

**Comment by jasonbosco** [comment]
@mtruyens Thank you for reporting this. We've tried with a 100 dimension dataset and it seemed to work fine... 

To debug this further, would you be able to share your dataset with us, along with a set of [curl commands like this](https://gist.github.com/jasonbosco/7c3432713216c378472f13e72246f46b) to replicate the issue? You can email it to contact at typesense dot org referencing this GitHub issue.

**Comment by mtruyens** [comment]
Thanks @jasonbosco. I just privately sent you an email with the files — hope you understand that I do not want to post these semi-confidential files on a public forum!

**Comment by mtruyens** [comment]
By the way, to clarify, "stuck" does not mean that the TypeSense process is looping (eating up CPU cycles). It just idles at the point where it gets stuck.

**Comment by mtruyens** [comment]
Maybe another hint: when I try to Ctrl-C the Docker instance in the Terminal when it got stuck, also the Terminal gets stuck, so the quitting never succeeds (I waited for several minutes)

When I try to Ctrl-C

^CI20221122 19:35:44.444456     1 typesense_server_utils.cpp:48] Stopping Typesense server...
I20221122 19:35:44.660284   135 typesense_server_utils.cpp:338] Typesense peering service is going to quit.
I20221122 19:35:44.660588   135 raft_server.cpp:784] Set shutting_down = true
I20221122 19:35:44.660741   135 raft_server.cpp:788] Waiting for in-flight writes to finish...
I20221122 19:35:44.660882   135 raft_server.cpp:794] Replication state shutdown, store sequence: 1142
I20221122 19:35:44.661182   135 raft_server.cpp:798] node->shutdown
I20221122 19:35:44.661365   135 node.cpp:929] node default_group:172.17.0.2:8107:8108 shutdown, current_term 2 state LEADER
I20221122 19:35:44.665619   135 replicator.cpp:1475] Group default_group Fail to find the next candidate
I20221122 19:35:44.666785   172 raft_server.h:263] Node stepped down : Raft node is going to quit.
I20221122 19:35:44.669342   135 raft_server.cpp:802] node->join
I20221122 19:35:44.669595   171 raft_server.h:267] This node is down
I20221122 19:35:44.671978   135 node.cpp:929] node default_group:172.17.0.2:8107:8108 shutdown, current_term 2 state SHUTDOWN
I20221122 19:35:44.676470   135 typesense_server_utils.cpp:343] raft_server.stop()
I20221122 19:35:44.676679   135 server.cpp:1100] Server[braft::RaftStatImpl+braft::FileServiceImpl+braft::RaftServiceImpl+braft::CliServiceImpl] is going to quit
I20221122 19:35:44.679512   135 typesense_server_utils.cpp:346] raft_server.join()
I20221122 19:35:44.683120   135 typesense_server_utils.cpp:349] Typesense peering service has quit.
I20221122 19:35:44.691893   135 typesense_server_utils.cpp:480] Shutting down batch indexer...
I20221122 19:35:44.692044   135 typesense_server_utils.cpp:483] Waiting for batch indexing thread to be done...
I20221122 19:35:45.478091   136 batched_indexer.cpp:296] Notifying batch indexer threads about shutdown...
I20221122 19:35:45.488898   136 batched_indexer.cpp:304] Batched indexer threadpool shutdown...

**Comment by mtruyens** [comment]
And I just also tried insert a 10 second pause in between each batch call from my Clojure client, but this did not make any difference.

**Comment by kishorenc** [comment]
Fix is part of the just released `0.24.1`.
