### ISSUE TITLE
[QUESTION] Searching by date

### ISSUE THREAD

**Issue by Ra0R** [typesense/typesense#803]
## Description

I would like to index some documents for bookings which contain dates (startDate, endDate). Which I would like to search on.

Similarly as described in this article:
https://beenje.github.io/blog/posts/searching-by-date-in-elasticsearch/

Example:
We have a document `booking`which has the fields  `startDate: Unix Timestamp, endDate: Unix Timestamp`. The user should be able to query (in his own locale) e.g. `12.2.2022` and recieve the matching `booking`.

Is this possible at all?

**Comment by jasonbosco** [comment]
You’d need to convert all time stamps into Unix timestamp both at indexing time and at search time to do date operations.
