### ISSUE TITLE
Curated search with filter_by returns incorrect results

### ISSUE THREAD

**Issue by tugaykaracay** [typesense/typesense#808]
## Description

Hi, we are using overrides to promote results for certain search keywords, but when we use filter_by with a curated search keyword Typesense checks if any curated result is hit by the filter_by filter and returns all curated results.

## Steps to reproduce

Assume that you have the following documents in your collection:
```json
[
  {"id": "1", "name": "Product 1", "categories": ["bags", "handbag"] },
  {"id": "2", "name": "Product 2", "categories": ["bags"] }
]
```

Then we create an override for that documents:
```json
{
  "rule": {
    "query": "test",
    "match": "exact"
  },
  "includes": [
    {"id": "2", "position": 1},
    {"id": "1", "position": 2}
  ]
}
```

if we query `/search?query_by=name&q=test&filter_by=categories:=["bags"]` it returns the correct results
and also if we query `/search?query_by=name&q=test&filter_by=categories:=["socks"]` it returns no results
but when we query `/search?query_by=name&q=test&filter_by=categories:=["handbag"]` the query still returns both documents.

## Expected Behavior

It should only return product id = "1" because only it is matching the filter_by query.

## Actual Behavior

Typesense returns both documents.

## Metadata

**Typesense Version**: 0.23.1

**OS**: Typesense Docker Image

**Comment by jasonbosco** [comment]
@tugaykaracay To get the behavior you're describing you want to set `filter_curated_hits: true` when creating the override, as described in this table here: https://typesense.org/docs/0.23.1/api/curation.html#parameters

This will ensure that Typesense still applies the filter_by clause on top of any overrides.

**Comment by tugaykaracay** [comment]
Thank you so much, somehow we missed that we will try that as soon as possible.

**Comment by tugaykaracay** [comment]
Hi @jasonbosco, we found how we missed that parameter, we are using typesense-js library and `filter_curated_hits` is not defined in `OverrideCreateSchema` interface. If you want I can create an issue for that.

**Comment by jasonbosco** [comment]
Ah! I just pushed out v1.4.4 of `typesense-js` which now has this param.
