### ISSUE TITLE
how to search when use alias

### ISSUE THREAD

**Issue by joan2015** [typesense/typesense#814]
## Description

I use the alias to reindex my data ,but when I search the alias ,I got an error like this

<img width="286" alt="image" src="https://user-images.githubusercontent.com/10558033/205210269-0c48236e-4696-4624-a6e6-6e9a2b838ac8.png">

## Expected Behavior

I can search the alias just like the real collection name

**Typesense Version**:
0.23.1
**OS**:
ubuntu 20.04

**Comment by joan2015** [comment]
get your point ，can not search aliase directly

**Comment by rderocle-gsoi** [comment]
Hello here, I think it would be a wonderful feature to search directly using the alias.
Don't you think ?

**Comment by jasonbosco** [comment]
Could you elaborate on what you mean? You should already be able to search using an alias name instead of the collection name.
