### ISSUE TITLE
Typo correction isn't applied with some combinations of parameters

### ISSUE THREAD

**Issue by 527bd5** [typesense/typesense#815]
## Description
I've come across this very strange bug where some fields aren't typo-tolerant under some specific conditions, even though `num_typos>0` for that particular field.  

## Steps to reproduce

See the [following Python script to reproduce](https://pastebin.com/keyTMdRG) a basic example. In this example, we query on fields `title` and `color` with `query_weights=2,3` and `num_typos=2,0`, so we should have typo tolerance on the `title` field, but we don't.

Note that we **do** get results if we change the query weight for the `color` field such that it is less than or equal to the query weight for the `title` field -- very weird! Similarly, if we set `num_typos=2,2` we get results as well. It is as if it uses the `num_typos` from the field that has a higher query weight.

## Expected Behavior
It should return the document with title `trousers` when you search for `trouzers` because the edit distance is 1 and `num_typos=2` for the matching field.

## Actual Behavior
It doesn't return anything.

## Metadata

**Typsense Version**: 0.24.0.rcn34

**OS**: Running Typesense Docker image

**Comment by kishorenc** [comment]
@527bd5 

This is a great catch. I've fixed it in `typesense/typesense:0.24.0.rcn39`
