### ISSUE TITLE
Numa

### ISSUE THREAD

**Issue by thenitai** [typesense/typesense#818]
Hi,

Not really an issue but merely a question since I don't see anything related to Numa architecture. That said, is Numa supported, i.e., can Typesense take advantage of it? (from what I gather it should :) )

Thx

**Comment by kishorenc** [comment]
@thenitai 

Typesense does not take advantage of Numa. But I agree, yes, this could be useful for large datasets.

**Comment by thenitai** [comment]
We switched all our servers and apps to Numa, and it helped with cutting down on memory usage for some apps. Anyhow, thank you for your answer.
