### ISSUE TITLE
Using * as query string crashes typesense on a certain corrupted collection

### ISSUE THREAD

**Issue by Benjozork** [typesense/typesense#82]
## Description

Typesense crashes with this dump (https://pastie.io/vuqulh.txt) when running the command in the next section on a certain collection

Collection:

`curl -H 'X-Typesense-API-Key: <...>' 'http://localhost:8108/collections/User`
```json
{
    "created_at": 1574820811,
    "default_sorting_field": "_dsf_jank",
    "fields":
    [
        {
            "facet": false,
            "name": "email",
            "type": "string"
        },
        {
            "facet": false,
            "name": "name",
            "type": "string"
        },
        {
            "facet": false,
            "name": "username",
            "type": "string"
        }
    ],
    "name": "User",
    "num_documents": 0
}
```

`_dsf_jank` is generated by my backend due to a bug in the collection generation code on my side. I know this is erroneous and would never work, but I assume crashing the server is not normal.

The collection is empty, as can be seen.

## Steps to reproduce

The curl command used to crash it : 
`curl -H 'X-Typesense-API-Key: <...>' 'http://localhost:8108/collections/User/documents/search?q=*&query_by=name'`

## Expected Behavior

An error message, or the collection never being accepted in the first place.

## Actual Behavior

https://pastie.io/vuqulh.txt

## Metadata

**Typsense Version**:  0.11.0

**OS**: Linux, Running in typesense docker container

I'm happy to provide more details if needed.

**Comment by kishorenc** [comment]
Good catch! This has been fixed here: https://github.com/typesense/typesense/commit/3cf3bd6f2262d6f76b23b9b2b5b4aa7edccd937c

The collection will not be created if the `default_sorting_field` is not present in the schema. This change will be available in the next release. Thank you.

**Comment by Benjozork** [comment]
Thank you for the quick fix !
