### ISSUE TITLE
Scoped API Key return all available collections

### ISSUE THREAD

**Issue by RowPixel** [typesense/typesense#821]
## Description

Scoped API Key with collections:list permission return all available collections.

## Steps to reproduce

1. Create scoped API Key
```
{
  "description": "Key for listing collections.",
  "actions": [
    "collections:list"
  ],
  "collections": [
    "org_.*"
  ]
}
```
2. Make request for collections list.
3. We get all available collections

## Expected Behavior

Scoped API Key should return only collections with "org_" prefix.

## Actual Behavior

Scoped API Key with collections:list permission return all available collections.

## Metadata

Typesense v0.23.1

**Comment by jasonbosco** [comment]
We should probably document this better, but `collections:list` implicitly applies to all collections by design. Typesense doesn't have the ability to restrict that particular action to specific collections.
