### ISSUE TITLE
String field fails when emplacing with null

### ISSUE THREAD

**Issue by madsemildahlgaard** [typesense/typesense#824]
## Description

I get an error when indexing a new document using `action=emplace` with an optional field of type string set to `null`.

## Steps to reproduce

Create a new collection called test.
```sh
curl "http://localhost:8108/collections" \
       -X POST \
       -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
       -d '{
         "name": "test",
         "fields": [
           {"name": "company_name", "type": "string"},
           {"name": "domain", "type": "string", "optional": true}
         ]
       }'
```

Insert a new document with `action=emplace`
```sh
curl "http://localhost:8108/collections/test/documents?action=emplace" -X POST \
        -H "Content-Type: application/json" \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
        -d '{
          "id": "1",
          "company_name": "Stark Industries",
          "domain": null
        }'

>>> {"message": "[json.exception.type_error.302] type must be string, but is null"}
```

## Expected Behavior

I expected the document to be created and the field to be ignored. I would expect it to behave similar to `action=create` when the id doesn't already exist.

## Actual Behavior

An error is returned stating that the type must be a string.

## Metadata

**Typesense Version**: 0.23.1

**Comment by jasonbosco** [comment]
This is a bug in 0.23.1 where when a field is marked as optional, Typesnse expects that field to be completely absent from the document, instead of being set as `null`.

We've already fixed the issue in the latest RC build of 0.24 (`0.24.0.rcn42` as of today) so null values are accepted for optional fields. I'd recommend upgrading to this build. Or if you want to stay on 0.23.1, the workaround would be to remove attributes with null values when you emplace.

**Comment by madsemildahlgaard** [comment]
Thank you for the quick reply!

**Comment by jasonbosco** [comment]
v0.24 is now available with this fix.

**Comment by v-dev-cl** [comment]
I'm testing version 0.25.1 (img typesense/typesense:0.25.1) and got this error when sending the "fieldName" with null value

> W20231111 18:58:25.754402   642 index.cpp:6033] Error while removing field `fieldName` from document, message: [json.exception.type_error.302] type must be number, but is null

and I created the collection with

```
           {
                "name": "fieldName",
                "type": "float",
                "index": true,
                "optional": true
            }
```

**Comment by jasonbosco** [comment]
@v-dev-cl Could you open a separate issue with a set of curl commands [like this](https://gist.github.com/jasonbosco/7c3432713216c378472f13e72246f46b#file-typesense-repro-steps-sh) that replicates the issue?
