### ISSUE TITLE
Facet counts can show incorrect results when combined with `filter_by`

### ISSUE THREAD

**Issue by auburnsummer** [typesense/typesense#832]
## Description

I have a field `tags` which is a string array facet. Using `facet_by` to show the top 10 tags. Output seems to be incorrect when the facets are combined with a filter.

## Steps to reproduce

I've prepared a test dataset that exhibits the issue.

 1. Download the test dataset here: https://gist.github.com/auburnsummer/fa6f456ea34c12914a2c78e8834f9061. The test dataset contains three fields, `id`, `tags`, and `approval`.
 2. Start Typesense using [these instructions](https://typesense.org/docs/guide/install-typesense.html#from-the-docker-image)
 3. Create a collection with a pre-defined schema

```
curl --request POST \
  --url http://localhost:8108/collections \
  --header 'Content-Type: application/json' \
  --header 'x-typesense-api-key: xyz' \
  --data '{
	"name": "aubtest",
	"fields": [
		{
			"name": "id",
			"type": "string",
			"index": false
		},
		{
			"name": "tags",
			"type": "string[]",
			"facet": true
		},
		{
			"name": "approval",
			"type": "int32",
			"facet": false
		}
	]
}'
```

 4. Add the test dataset into the collection

```
curl -H "X-TYPESENSE-API-KEY: xyz" \
      -X POST \
      -T orchard.jsonl \
      "http://localhost:8108/collections/aubtest/documents/import?action=create"
```

 5. Try querying it, without a `filter_by`

```
curl --request GET \
  --url 'http://localhost:8108/collections/aubtest/documents/search?q=&query_by=tags&facet_by=tags&max_facet_values=10' \
  --header 'x-typesense-api-key: xyz' | jq ".facet_counts"
```

Results are as expected.

 6. Try querying it again, but with an additional filter

```
curl --request GET \
  --url 'http://localhost:8108/collections/aubtest/documents/search?q=&query_by=tags&facet_by=tags&max_facet_values=10&filter_by=approval%3A%5B10..20%5D' \
  --header 'x-typesense-api-key: xyz' | jq ".facet_counts"
```

The tag `as you can tell I'm a master at writing relevant tags` shows up and has a count of `148`. However, if you Ctrl-F in the actual dataset, that value only shows up once.

## Expected Behavior

The top 10 facet counts do not show the value `as you can tell I'm a master at writing relevant tags`.

## Actual Behavior

The top 10 facet counts do show the value `as you can tell I'm a master at writing relevant tags`

## Metadata

**Typesense Version**: 0.23.1

**OS**: Linux

**Comment by kishorenc** [comment]
@auburnsummer 

Thank you for creating this wonderfully detailed issue. I was able to reproduce this bug (was not related to filtering but an edge case in facet indexing) and I've a fix for it in a `0.24 RC` build. 

Do you use Docker/DEB/RPM/tar.gz? I can post a fixed build here.

**Comment by auburnsummer** [comment]
hi, thanks for the quick fix! I use the tar.gz Linux binary

**Comment by kishorenc** [comment]
@auburnsummer 

Here's the [tar.gz build](https://dl.typesense.org/releases/0.24.0.rcn49/typesense-server-0.24.0.rcn49-linux-amd64.tar.gz).
