### ISSUE TITLE
How to know typesense indexing status?

### ISSUE THREAD

**Issue by chimd715** [typesense/typesense#833]
## Description

When importing documents, typesene server returns `Not ready or lagging` error. 
Document says it's because typesense server is busy by indexing or writing data.
How can I know if typesense is busy with indexing? Should I just retry until server does not return `Not ready or lagging`?

typesense health is true even when server returns `Not ready or lagging`.

**Comment by jasonbosco** [comment]
> Should I just retry until server does not return `Not ready or lagging`

That's right. When Typesense returns a 503, that is the built-in back-pressure mechanism kicking-in, to prevent searches from being impact. You want to then retry your import with exponential backoff to give Typesense room to catch up. 

If you have sufficient CPU capacity, you could also change the value of healthy-read-lag and healthy-write-lag [server configuration parameters](https://typesense.org/docs/0.23.1/api/server-configuration)

Here's more information: https://typesense.org/docs/guide/syncing-data-into-typesense.html#handling-http-503s

> typesense health is true even when server returns `Not ready or lagging`.

I'm surprised to hear this. The health endpoint for a node should return false when the node is lagging...

**Comment by chimd715** [comment]
This is right url for [server configuration parameters](https://typesense.org/docs/0.23.1/api/server-configuration.html#using-command-line-arguments)
