### ISSUE TITLE
Missing characters in snippet

### ISSUE THREAD

**Issue by tomika** [typesense/typesense#838]
## Description

Snippet is incorrect when using accented charaters

## Steps to reproduce

Create a collection, insert word 'Óceánok' which means 'Oceans' in hungarian then search it back:

curl http://localhost:8108/collections -X POST -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: ${TS_API_KEY}" \
       -d "{\"name\": \"bug\", \"fields\": [{\"name\": \"word\", \"type\": \"string\" }]}"

curl http://localhost:8108/collections/bug/documents  -X POST -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: ${TS_API_KEY}" \
       -d "{ \"id\": \"1\", \"word\": \"\u00d3ce\u00e1nok\"}"

curl -H "X-TYPESENSE-API-KEY: ${TS_API_KEY}" "http://localhost:8108/collections/bug/documents/search?q=ocean&query_by=word"

## Expected Behavior

Part of the expected response
..."highlights":[{"field":"word","matched_tokens":["Óceán"],"snippet":"&lt;mark&gt;Óceán&lt;/mark&gt;ok"}]

or if really only shorter match found
..."highlights":[{"field":"word","matched_tokens":["Óce"],"snippet":"&lt;mark&gt;Óce&lt;/mark&gt;ánok"}]

## Actual Behavior

Part of the response
..."highlights":[{"field":"word","matched_tokens":["Óce"],"snippet":"&lt;mark&gt;Óce&lt;/mark&gt;nok"}]

Clearly visible that character 'á' is missing from snippet.

## Metadata

Typesense Version: 0.23.1
OS: Debian GNU/Linux 11 (bullseye)
Linux build, starting with commandline:

./typesense-server --data-dir=$(pwd)/typesense-data --api-key=${TS_API_KEY} --enable-cors --log-dir=$(pwd)

I tried to use "hu" locale on schema definition, but nothing changed
If I run query with accented characters then it works as expected.

**Comment by kishorenc** [comment]
@tomika 

Can you try on recent 0.24 RC builds (they're available on Docker hub). We've fixed this issue with highlighting on unicode characters.

**Comment by kishorenc** [comment]
We also have a tar gz [here](https://dl.typesense.org/releases/0.24.0.rcn49/typesense-server-0.24.0.rcn49-linux-amd64.tar.gz).

**Comment by tomika** [comment]
Seems to be OK, ty.

**Comment by kishorenc** [comment]
Thank you for confirming!
