### ISSUE TITLE
Change or set default_sorting_field

### ISSUE THREAD

**Issue by hussainb** [typesense/typesense#839]
## Description

The `default_sorting_field` can be passed while creating a Collection, but I was not able to find any docs which mention a way to update or set the `default_sorting_field` later. Is there a way to do it?

Also, the typesense postman collection does not have an Update endpoint.

**Typesense Version**: v0.23.1

**Comment by kishorenc** [comment]
It's not possible to update it later on. This is primarily because the value of the default sorting field is embedded into the index that Typesense uses for every word in the dataset. So changing this field requires reindexing.
