### ISSUE TITLE
"invalid configuration" message suggests using environment variables without the "TYPESENSE_" prefix

### ISSUE THREAD

**Issue by JaredReisinger** [typesense/typesense#84]
## Description

When following the guide and using environment variables to configure typesense, you end up using `DATA_DIR` and `API_KEY`, leading to an "invalid configuration" message that doesn't help.

(For reference, the message text is at https://github.com/typesense/typesense/blob/master/src/main/typesense_server.cpp#L66)

## Steps to reproduce

Run `docker run --rm -ti -e DATA_DIR=/tmp -e API_KEY=secret typesense/typesense:0.11.1`.

## Expected Behavior

The actual environment variables need to be prefixed with `TYPESENSE_`, so the error output should read:

> You can also pass these arguments as environment variables such as **TYPESENSE_DATA_DIR**, **TYPESENSE_API_KEY**, etc.

## Actual Behavior

```text
Invalid configuration: Data directory is not specified.
Command line usage: ./typesense-server --data-dir=string --api-key=string [options] ...
options:
  -d, --data-dir               Directory where data will be stored. (string)
  -a, --api-key                API key that allows all operations. (string)
  -s, --search-only-api-key    API key that allows only searches. (string [=])
  -h, --listen-address         Address to which Typesense server binds. (string [=0.0.0.0])
  -p, --listen-port            Port on which Typesense server listens. (unsigned int [=8108])
  -m, --master                 To start the server as read-only replica, provide the master's address in http(s)://<master_address>:<master_port> format. (string [=])
  -c, --ssl-certificate        Path to the SSL certificate file. (string [=])
  -k, --ssl-certificate-key    Path to the SSL certificate key file. (string [=])
      --enable-cors            Enable CORS requests.
      --log-dir                Path to the log directory. (string [=])
      --config                 Path to the configuration file. (string [=])

You can also pass these arguments as environment variables such as DATA_DIR, API_KEY, etc.
```
Looking at the last line in particular, it suggests:

> You can also pass these arguments as environment variables such as **DATA_DIR**, **API_KEY**, etc.

## Metadata

**Typsense Version**: 0.11.1

**OS**: Docker on Windows 10 (run via Ubuntu on WSL)

**Comment by kishorenc** [comment]
Thank you for reporting this. Fixed it here: https://github.com/typesense/typesense/commit/589802aff806dd9d4929633c9b3177c1fae5de51
