### ISSUE TITLE
Similar query returning different results

### ISSUE THREAD

**Issue by wishabhilash** [typesense/typesense#840]
## Description

I have created a demo to search Stock Market scrips. However, when i search with `nifty call 18000` and `nifty 18000 call`, I get different results.

## Steps to reproduce

Go to [https://typesensesearch.abhilashnanda.repl.co/](https://typesensesearch.abhilashnanda.repl.co/) and search for `nifty call 18000` and `nifty 18000 call`.

## Expected Behavior

Both queries should return result same as we get for `nifty call 18000`.

## Actual Behavior

We see different results for `nifty call 18000` and `nifty 18000 call`.

## Metadata

**Typesense Version**: 0.23.1

**OS**: Ubuntu 22.04

## Extra info
`additionalSearchParameters: {
        query_by: "symbol, instType, optType, exseg, readableExpiryDate, strikePrice",
        query_by_weights: "1,2,3,4,5,6",
        sort_by: "_text_match:desc,instGroupScore:asc,score:asc"
}`

**Examples:**
- symbol - nifty
- instType - STK, FUT, OPT
- optType - CALL, PUT
- exseg - CASH, COMM, OPT-NFO, CUR
- readableExpiryDate - 15-DEC-2022
- strikePrice - 18000

**Comment by kishorenc** [comment]
The last word of the query is treated as a prefix search, so the two queries are actually different because of the change in the last word. You can disable prefix searching via `prefix: false`.
