### ISSUE TITLE
Integration with a Search UI

### ISSUE THREAD

**Issue by Charuru** [typesense/typesense#85]
Mentioned on Hacker News this is going to happen, just want a place to discuss it and follow the progress.

**Comment by kvz** [comment]
I'd also be interested, i remember reading the thread, but not the intended project to maybe integrate with, was it InstantSearch?

**Comment by jasonbosco** [comment]
@Charuru @kvz We just released our integration with InstantSearch: https://github.com/typesense/typesense-instantsearch-adapter.
