### ISSUE TITLE
Is there a way to import data directly instead of REST API for large batches

### ISSUE THREAD

**Issue by akamil-etsy** [typesense/typesense#851]
For a large number of records batch import via REST interface likely adds significant overhead, especially when there are multiple large collections and frequent imports/syncs.  
Is there a cli utility that calls indexer functions in cpp directly, i.e. streaming jsonl file from disk (on typesense server host), building and saving the index to rocksdb, without the whole http loop and throttling

**Comment by kishorenc** [comment]
@akamil-etsy 

There's no other way to import documents into Typesense apart from using the import end-point. In the future we plan to allow consuming large POST bodies in a gzip compressed format to decrease I/O and improve performance. That's on our roadmap but haven't gotten around to prioritizing that yet.
