### ISSUE TITLE
How does multi request works with cluster setup?

### ISSUE THREAD

**Issue by chimd715** [typesense/typesense#860]
## Description
When multi search is requested to typesense clusters, how does it work?
Does one cluster handles all multi request or does typesenes clusters are smart enough to divide requests and each clusters handle multi request synchronously

https://typesense.org/docs/0.23.1/api/federated-multi-search.html#multi-search-parameters
https://typesense.org/docs/guide/high-availability.html#high-availability-in-typesense-cloud

## Metadata

**Typesense Version**:

**OS**:

**Comment by jasonbosco** [comment]
One node in the cluster handles all searches inside a multi-search request.
