### ISSUE TITLE
Facet property display label?

### ISSUE THREAD

**Issue by Clasyc** [typesense/typesense#863]
What is best approach to handle facet labels in front-end. Let's say we have constantly changing dynamic amount of facets.
Let's say one of the property name is `"processors"`, I want to display it as `"CPU"`, (I can't just hardcode the mapping, because there might be new facets with different labels).

Is there something that would work out of the box (something like property display name attribute)? Or I just need to manually map those values and handle it by myself?

**Comment by jasonbosco** [comment]
@Clasyc The best way would be to put the display values inside each document and facet on that field. 

Another alternative would be to maintain a mapping of internal values to display values in say a headless CMS or a hard-coded JSON on the FE, and then dynamically switch out the facet values coming from Typesense at display time.

**Comment by Clasyc** [comment]
@jasonbosco thank you!
