### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by frederic-aube** [typesense/typesense#865]
## Description

Typesense Cloud displays "TypeError: Cannot convert undefined or null to object" when we try to search.

## Steps to reproduce

- Configure some fields with optional = true.
- Set values to null.

![image](https://user-images.githubusercontent.com/123898493/215349564-f418b1e1-5f8a-483c-9c85-731c1e296d19.png)
## Expected Behavior

**Typesense Version**: Typesense Cloud 23.1

**Comment by kishorenc** [comment]
@frederic-aube 

Can you please email us at: contact@typesense.org with your cluster details? Happy to help you over email. I will close this issue for now since it's related to Typesense Cloud and not the server.
