### ISSUE TITLE
What does state 5 mean?

### ISSUE THREAD

**Issue by chimd715** [typesense/typesense#866]
When sending a GET request to `/debug` endpoint, I get `state: 5` from one of my typesense instance. Document says 1 is leader, 4 is follower, and others mean error. I want to know which error state 5 is.

```Shell
curl "http://${TYPESENSE_HOST}/debug/" \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}"
```

**Comment by kishorenc** [comment]
5 is `STATE_ERROR`.  You can see the list of states here: https://github.com/baidu/braft/blob/master/src/braft/raft.h#L270
