### ISSUE TITLE
Error starting typesense-server@0.24.0 on Mac M1/M2

### ISSUE THREAD

**Issue by xinxin001** [typesense/typesense#868]
## Description

When starting typesense-server@0.24.0 with brew services on Mac M1, it shows error and does not start.

## Steps to reproduce

Steps performed on Mac M1:
1. `brew install typesense-server@0.24.0`
2. `brew services start typesense-server@0.24.0`

## Expected Behavior

When running `curl http://localhost:8108/health`, it shoulder return {"ok":true}

## Actual Behavior

`curl http://localhost:8108/health` -> Connection refused
`brew services` will show that the typesense-server status is "error"

## Metadata

**Typesense Version**: 0.24.0

**OS**: Mac M1

I downgraded to v0.23.1 and everything worked well.

**Comment by DalenW** [comment]
I figured out why. There's a missing file

```Referenced from: <46D69D13-481B-330E-8AAF-FE93C6BAB76A> /opt/homebrew/Cellar/typesense-server@0.24.0/0.24.0/bin/typesense-server
  Reason: tried: 'libbraft.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibbraft.dylib' (no such file), 'libbraft.dylib' (no such file), '/usr/local/lib/libbraft.dylib' (no such file), '/usr/lib/libbraft.dylib' (no such file, not in dyld cache), '/opt/homebrew/var/lib/typesense/libbraft.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/var/lib/typesense/libbraft.dylib' (no such file), '/opt/homebrew/var/lib/typesense/libbraft.dylib' (no such file), '/usr/local/lib/libbraft.dylib' (no such file), '/usr/lib/libbraft.dylib' (no such file, not in dyld cache)
```

As far as I can tell this file is not in macOS.

**Comment by kishorenc** [comment]
@DalenW @xinxin001 

This is fixed now. Can you please try directly with the binary [here](https://dl.typesense.org/releases/0.24.0/typesense-server-0.24.0-darwin-amd64.tar.gz)?

**Comment by DalenW** [comment]
Seems to be working now. I replaced my 23.1 binary with that one, and brew services was able to successfully start.
