### ISSUE TITLE
Typesense@0.24.0 Homebrew tap has mismatched SHA256 hashes

### ISSUE THREAD

**Issue by wmcb91** [typesense/typesense#872]
## Description

The Typesense@0.24.0 Homebrew tap has mismatched SHA256 hashes, preventing its installation. I was able to install `typesense/tap/typesense-server@0.23.0` as a workaround.

## Steps to reproduce

`brew install typesense/tap/typesense-server@0.24.0`

## Expected Behavior

Homebrew installs Typesense@0.24.0

## Actual Behavior

When running the install command from the docs, the following is the error output:

```
$ brew install typesense/tap/typesense-server@0.24.0
==> Fetching typesense/tap/typesense-server@0.24.0
==> Downloading https://dl.typesense.org/releases/0.24.0/typesense-server-0.24.0-darwin-amd64.tar.gz
######################################################################## 100.0%
Error: typesense-server@0.24.0: SHA256 mismatch
Expected: 1f59c281afe88f3d34511613082547bf2201b0710a0d538152a3391ca99434ec
  Actual: 396b3f876648cd35cd0c9ee29f5f6be90e18a4ca4e40d0e91640afa29220c6b9
    File: /Users/<user>/Library/Caches/Homebrew/downloads/2d95f1fed863ff4e03cbb7f14af40bffbd1dd0f9ff403f8e892bbd9269ea706f--typesense-server-0.24.0-darwin-amd64.tar.gz
To retry an incomplete download, remove the file above.
```

## Metadata

**Typesense Version**: 0.24.0

**OS**: macOS Monterey 12.2.1 on 2019 MacBook Pro with an Intel chip

```
$ brew --version
Homebrew 3.6.20
Homebrew/homebrew-core (git revision 8577bfee0fa; last commit 2023-02-01)
Homebrew/homebrew-cask (git revision b28a0f4ff2; last commit 2023-02-01)
```

**Comment by jasonbosco** [comment]
We had to publish a new binary to address #868. Just updated the homebrew tap to use the new SHA. So this should be fixed now.

**Comment by wmcb91** [comment]
Thanks @jasonbosco!
