### ISSUE TITLE
Field 'XYZ' does not have a vector query index. (400 error)

### ISSUE THREAD

**Issue by Bug-Reaper** [typesense/typesense#877]
## Description
Get this error on vector query attempt.
![Thu Feb  2 06:12:20 PST 2023](https://user-images.githubusercontent.com/31227781/216348041-38487c0c-0a6c-48d7-b53a-7de8633ab00f.png)

The `vector` field exists and is of type `float[]`. My search is with a vector of equal length the the vectors on documents in the DB. This field `vector` was added to our schema in an earlier version of typesense so did not have `num_dim` set at the time of creation.

The error message left me a little unclear on how to proceed. Any help appreciated.

**Typesense Version**:
0.34.0

**OS**:
Arch Linux

**Comment by Bug-Reaper** [comment]
Looks to [almost certainly](https://github.com/typesense/typesense/blob/bf0f7430a0b9732a797c8331e74492f536962300/src/collection.cpp#L931) be related to the fact `num_dim` is not set for that field.

We've only ever stored vectors of a fixed size in the field. Is it possible to set `num_dim` on an already in-use field?

**Comment by Bug-Reaper** [comment]
For anyone here from google/etc... I did find some info about in-place schema updates that was useful and not in the main typesense docs I think?

[update or alter a collection](https://github.com/typesense/typesense-website/blob/v0.23.0/docs-site/content/0.23.0/api/collections.md#update-or-alter-a-collection)

--- 
### solution

1. Created a new field named `resnet18` with `num_dims` set via the js client and above docs instruction. Code looked roughly like:
```javascript
const updateSchema = {
  "fields":[
    {"name":"resnet18", "type":"float[]","num_dim":512,"optional": true},
  ]
}
client.collections('collectionNameHere').update(updateSchema)
```
***IMPORTANT NOTE:***- Running the above update may cause downtime on sufficiently large collections. Instead of the expected/documented response, I got:
```
Request #1675393238260: Request to Node 0 failed due to "undefined Request failed with HTTP code 504"
Request #1675393238260: Sleeping for 0.1s and then retrying request...
^C
```
At which point I killed the script that had sent the request. Than after that, all calls to the database for searches/queries took a long time and eventually timed out with 504. After about 10mins, the database came back with the new field added to the collection. 

For reference our collection is approx 2.4 million records and ~10gb when saved to ljson. So while the above code did work to add a new field, you can expect some downtime and probably best practice to snapshot backup your database before you attempt any schema updates.

2. Wrote a script to iterate over each record and copy data from the original `vector` field over to the new `resnet18` field that has `num_dim` set properly.

3. Now able to search properly on the new field `resnet18` via `vector_query` parameter.

**Comment by kishorenc** [comment]
@Bug-Reaper 

Thanks for the detailed follow-up comments. You've to specify `num_dim` to a float field to enabled vector indexing. Since vector indices consume memory we can't enable it for default on all float array fields. 

As for schema alter, yes, that takes some time on large datasets. If you run it using a client with a small timeout, the API request will timeout and the client will retry it, which would cause another alter being queued. So, run alter only from `curl` which doesn't have a default timeout. 

We're also working on making alter non-blocking for read operations. That should help going forward.

**Comment by kishorenc** [comment]
We already have done an initial round of exploration on not blocking searches during schema changes. In the next month or so, this should be available on a RC build, so hopefully this anxiety had an expiry date soon :)
