### ISSUE TITLE
Possibility to Sort by Number of Hits for Grouped Results

### ISSUE THREAD

**Issue by digamber89** [typesense/typesense#879]
## Description

I would like to request a possibility to sort the results/group by number of hits within that when grouping is done. 
When group_by parameter is set - I would like to have the possibility to show the results based on number of hits on a particular group.

So lets say I have a group :
Group A : [H1, H2, H3]
Group B: [H4, H5]

So if the search query matches All results in both group Group A has 3 total hits, and Group B has 2 total hits.
By our definition: Group A would be shown first and Group B would be shown second.

This issue would be related to my previous issue : [https://github.com/typesense/typesense/issues/870](https://github.com/typesense/typesense/issues/870)

## Metadata

**Typesense Version**: 0.24.0

**OS**: Mac OS Monterey

**Comment by kishorenc** [comment]
Available in 0.25.0. You can do `"sort_by": "_group_count:desc" `
