### ISSUE TITLE
Docker build | icu4c-61_1 source 

### ISSUE THREAD

**Issue by karlhendrik** [typesense/typesense#88]
Current developement.Dockerfile cannot build because it returns 404 when pulling icu source. 
I changed icu source download with this link: https://ftp.osuosl.org/pub/blfs/conglomeration/icu/icu4c-61_1-src.tgz 

Now it builds.

**Comment by kishorenc** [comment]
Thanks, I will fix this soon.

**Comment by kishorenc** [comment]
Fixed via https://github.com/typesense/typesense/commit/35b2f0475834b750ca7942706acbd004a070f520
