### ISSUE TITLE
Healthcheck endpoint fails - Unable to install cleanly Typesense v0.24.0 on K8s | Please share latest working template

### ISSUE THREAD

**Issue by sagungargs15** [typesense/typesense#881]
## Description

Unable to hit heathcheck endpoint: https://my.domain:8108/health Please help if possible @kishorenc 

## Steps to reproduce

I have used the template offered in github https://github.com/typesense/typesense-kubernetes

```
code of yaml files for ingress shared by you in the repo

```

## Expected Behavior

Healthcheck endpoint should work

## Actual Behavior

Working typesense on self hosted K8s

## Metadata

**Typesense Version**: v0.24.0

**OS**: Kubernetes Containerization

**Comment by kishorenc** [comment]
Due to various issues which has been discussed [on a related issue](https://github.com/typesense/typesense/issues/465#issuecomment-1407576059) we can't reliably support Kubernetes. You've to host it on stand-alone nodes.

**Comment by kishorenc** [comment]
Due to various issues which has been discussed [on a related issue](https://github.com/typesense/typesense/issues/465#issuecomment-1407576059) we can't reliably support Kubernetes. You've to host it on stand-alone nodes.
