### ISSUE TITLE
Helm Chart for K8s missing for typesense installation on self hosted environment v0.24.0

### ISSUE THREAD

**Issue by sagungargs15** [typesense/typesense#882]
## Description

Need a standard clean way to install typesense on K8s. Please help @kishorenc 

## Metadata

**Typesense Version**: v0.24.0

**OS**:

**Comment by kishorenc** [comment]
Due to various issues which has been discussed [on a related issue](https://github.com/typesense/typesense/issues/465#issuecomment-1407576059) we can't reliably support Kubernetes. You've to host it on stand-alone nodes.

**Comment by extrasalt** [comment]
Can this be explicitly mentioned in  [typesense/typesense-kubernetes](https://github.com/typesense/typesense-kubernetes)
