### ISSUE TITLE
Can't import collection with geopoint inside nested object

### ISSUE THREAD

**Issue by aponski** [typesense/typesense#888]
## Description

Hi, I cant import collection with geopoint inside nested object. 

## Steps to reproduce

**My collection schema in typesense:** 

{
  "created_at": 1675682248,
  "default_sorting_field": "",
  "enable_nested_fields": true,
  "fields": [
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "addresses",
      "optional": false,
      "sort": false,
      "type": "object[]"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "addresses.zipCode",
      "optional": true,
      "sort": false,
      "type": "string[]"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "addresses.website",
      "optional": true,
      "sort": false,
      "type": "string[]"
    },
    {
      "facet": false,
      "index": true,
      "infix": false,
      "locale": "",
      "name": "addresses.geoPoint",
      "optional": true,
      "sort": true,
      "type": "geopoint[]"
    },
    {
      "facet": true,
      "index": true,
      "infix": true,
      "locale": "",
      "name": "addresses.city",
      "optional": true,
      "sort": false,
      "type": "string[]"
    },
    {
      "facet": false,
      "index": true,
      "infix": true,
      "locale": "",
      "name": "addresses.name",
      "optional": true,
      "sort": false,
      "type": "string[]"
    },
    {
      "facet": false,
      "index": true,
      "infix": true,
      "locale": "",
      "name": "addresses.street",
      "optional": true,
      "sort": false,
      "type": "string[]"
    }
  ],
  "name": "queues_v4",
  "num_documents": 0,
  "symbols_to_index": [],
  "token_separators": []
}

**Document data that I'm trying to import** 

{
	"id": "udpuV5uNOsD1GNzaCHgt",
	"addresses": [{
		"name": "Name 1",
		"street": "Street 1",
		"zipCode": "01-000",
		"city": "City 1",
		"geoPoint": [51.26506, 22.58299],
		"website": ""
	}, {
		"name": "Name 2",
		"street": "Street 1",
		"zipCode": "02-000",
		"city": "City 2",
		"geoPoint": [51.7400062410712, 19.620644614931905],
		"website": ""
	}]
}

## Expected Behavior

Document should be imported into Typesense. 

## Actual Behavior

I'm getting error 

` error: 'Field `addresses.geoPoint` must contain 2 element arrays: [ [lat, lng],... ].'`
## Metadata

**Typesense Version**:

Typesense Cloud v0.24

**Comment by kishorenc** [comment]
Since you've defined `addresses.geoPoint` an **array of geo points** (`geopoint[]`) you have to give it an array of lat longs like this:

```
"geoPoint": [
   [lat_1, lat_2],
   [lat_3, lat_4],   
]
```

If you want to index a single lat/lng pair like `[51.7400062410712, 19.620644614931905]` then define the type in the schema as just `geopoint` and NOT `geopoint[]`.

**Comment by aponski** [comment]
@kishorenc but all other nested field types in schema are defined as arrays even if data in imported document is not an array e.g. addresses.name :
{
"facet": false,
"index": true,
"infix": true,
"locale": "",
"name": "addresses.name",
"optional": true,
"sort": false,
"type": "**string[]**"
},

I found this solution in this thread https://github.com/typesense/typesense/issues/227#issuecomment-1364072388

I also tried to define as `geopoint` and NOT `geopoint[]` but when I import document with two addresses in an array: 

{
"id": "udpuV5uNOsD1GNzaCHgt",
"addresses": [{
"name": "Name 1",
"street": "Street 1",
"zipCode": "01-000",
"city": "City 1",
"geoPoint": [51.26506, 22.58299],
"website": ""
}, {
"name": "Name 2",
"street": "Street 1",
"zipCode": "02-000",
"city": "City 2",
"geoPoint": [51.7400062410712, 19.620644614931905],
"website": ""
}]
}

I get error
`error: 'Field `addresses.geoPoint` must be a 2 element array: [lat, lng].
`

Definition as `geopoint` in schema only works for importing document with only one address in an array: 
{
"id": "udpuV5uNOsD1GNzaCHgt",
"addresses": [{
"name": "Name 1",
"street": "Street 1",
"zipCode": "01-000",
"city": "City 1",
"geoPoint": [51.26506, 22.58299],
"website": ""
}]
}

**Comment by aponski** [comment]
This problem seems to be only with `geopoint` type. If I remove `geopoint` from schema everything works ok with other fields in address. I can import documents with multiple addresses.

**Comment by kishorenc** [comment]
Ah ok I got it. Let me investigate and get back to you!

**Comment by kishorenc** [comment]
Thank you for reporting this issue. I was able to identify what's going wrong here, and have a fix for it. Can you please email us your Typesense Cloud cluster ID? We can upgrade your cluster.

**Comment by armanp79** [comment]
I am also facing this issue

**Comment by jsutaria** [comment]
> I am also facing this issue

Fix is in `0.24.1.rc12`

**Comment by kishorenc** [comment]
I've a proper fix for this and related issues in `typesense/typesense:0.25.0.rc21`.
