### ISSUE TITLE
Feature Req: filter_by `<field>:!=<number>` numeric operator

### ISSUE THREAD

**Issue by Bug-Reaper** [typesense/typesense#900]
## Description

I have a use-case where `!=` would be really useful to use in a filter_by query on a numeric field.

`<field>:!=<value>`

## Steps to reproduce

Try to filter_by a numeric field with the `!=` operator

## Expected Behavior

Response would filter out any documents that exactly matched the filtered numeric value

## Actual Behavior

![Mon Feb 20 19:09:06 PST 2023](https://user-images.githubusercontent.com/31227781/220237888-c4b0d3c0-9438-4eb7-848b-1ec52d9e8711.png)

## Metadata

**Typesense Version**:
0.24.0

**OS**:
Arch Linux

---

I can still kinda do accomplish the operation via something like
```javascript
let filter_by = "(size:>"+excludeSize+"||size:<"+excludeSize+")"
```

However, as I need to exclude several specific values, the complication to create a proper filter string becomes very high.

**Comment by kishorenc** [comment]
This is available on the 0.25 RC builds. You can check those Docker build: `typesense/typesense:0.25.0.rc12`

**Comment by Bug-Reaper** [comment]
> This is available on the 0.25 RC builds. You can check this Docker build: `typesense/typesense:0.25.0.rc12`

You guys are always one step ahead :100: !

That's sick! Do you know if I could do something like `size:!=[0,50,100]` where it will filter out any records where (size == 0 OR size == 50 OR size == 100).

Also is there a binary download for latest 25 pre-release version EX:
```
curl -O https://dl.typesense.org/releases/0.24.0/typesense-server-0.24.0-linux-amd64.tar.gz
```

**Comment by kishorenc** [comment]
Yes, `!=` should work for OR as well. 

RC binary is [here](https://dl.typesense.org/releases/0.25.0.rc12/typesense-server-0.25.0.rc12-linux-amd64.tar.gz).

**Comment by Bug-Reaper** [comment]
Thanks @kishorenc !
