### ISSUE TITLE
Optional field or default value ?

### ISSUE THREAD

**Issue by geoffreyp** [typesense/typesense#91]
## Description
I have a collection with 10 fields but I have 2 optional fields so when I want create a document I have the error : 

> Field `field_name` has been declared in the schema, but is not found in the document.

Is it possible to add a parameter "default_value" when we create a collection for specific fields to avoid this error? Or add a parameter "optional" ? 

## Steps to reproduce

```
books_schema = {
  'name' => 'books',
  'fields' => [
    {'name' => 'title', 'type' => 'string' },
    {'name' => 'author', 'type' => 'string' },
    {'name' => 'ratings_count', 'type' => 'int32' },
  ],
  'default_sorting_field' => 'ratings_count'
}

client.collections.create(schema)

book_document = {
  'title': 'Harry potter',
  'ratings_count': '4'
}
client.collections['books'].documents.create(book_document)

```

## Expected Behavior

Create the document without error with a None value in the field author or with a default value

## Actual Behavior

Raise the error: 

> typesense.exceptions.RequestMalformed: Field `author` has been declared in the schema, but is not found in the document.

## Metadata

**Typsense Version**: 0.11.2

**OS**: Macos 10.15.2

**Comment by kishorenc** [comment]
I like the idea of having some fields marked as `optional`. Will consider adding this feature 👍

**Comment by kishorenc** [comment]
@geoffreyp v0.12.0 has landed and it has support for optional fields. You can mark a field as `"optional": true` during declaration. You can read more here: https://typesense.org/docs/0.12.0/api/#create-collection

**Comment by skipjack** [comment]
Possible to allow `null` values in `optional` fields? I get...

``` bash
RequestMalformed [Error]: Request failed with HTTP code 400 | Server said: Field `title` must be a string.
```

This kind of relates to #180. Seems a little odd that we _must_ populate it with an empty version of the given type but maybe I'm missing something with strict typing that boosts performance?

**Comment by skipjack** [comment]
Thanks for your response, and yea that's what I'm doing for now. Can you elaborate on the rationale for that?

**Comment by jasonbosco** [comment]
@skipjack No particular reason, it was an oversight when we implemented this :) Mind opening a new issue for this, so it's easier to track and I can ping you when it's addressed?

**Comment by skipjack** [comment]
Of course! See #266, thanks again for your quick responses.
