### ISSUE TITLE
typesense - Indexing nested fields(not searching automatically???)

### ISSUE THREAD

**Issue by BekaArabidze98** [typesense/typesense#911]
If I understand correctly, enable_nested_fields=true, would index the nested arrays or object arrays by 

`
```
const schema = {
name: 'published_section',
enable_nested_fields: true,
fields: [
    { name: 'projectId', type: 'string', facet: false },
    { name: 'name', type: 'string', facet: false, infix: true },
    { name: 'description', type: 'string', facet: false, infix: true },
    { name: 'request', type: 'object', facet: true, optinal: false },
    { name: 'responses', type: 'auto', facet: true, optinal: false },
    { name: 'createdAt', type: 'string', facet: false, sort: true },
],
default_sorting_field: 'createdAt',
```
`

request and responses are nested arrays and object arrays, So when I upload the document, typesense will search for all sub-fields. Actually Typesense created lots of sub-fields after importing documents. Does this mean when I search something on frontend, which is deep nested, It would search automatically, right? and I just need to pass request and responses on frontend?

```
`fields: [
{
  facet: false,
  index: true,
  infix: false,
  locale: '',
  name: 'projectId',
  optional: false,
  sort: false,
  type: 'string'
},
{
  facet: false,
  index: true,
  infix: true,
  locale: '',
  name: 'name',
  optional: false,
  sort: false,
  type: 'string'
},
{
  facet: false,
  index: true,
  infix: true,
  locale: '',
  name: 'description',
  optional: false,
  sort: false,
  type: 'string'
},
{
  facet: true,
  index: true,
  infix: false,
  locale: '',
  name: 'request',
  optional: false,
  sort: false,
  type: 'object'
},
{
  facet: true,
  index: true,
  infix: false,
  locale: '',
  name: 'responses',
  optional: true,
  sort: false,
  type: 'auto'
},
{
  facet: false,
  index: true,
  infix: false,
  locale: '',
  name: 'createdAt',
  optional: false,
  sort: true,
  type: 'string'
},
{
  facet: true,
  index: true,
  infix: false,
  locale: '',
  name: 'responses',
  optional: true,
  sort: false,
  type: 'object[]'
},
{
  facet: true,
  index: true,
  infix: false,
  locale: '',
  name: 'responses.statusCode',
  optional: true,
  sort: false,
  type: 'int64[]'
},
{
  facet: true,
  index: true,
  infix: false,
  locale: '',
  name: 'responses.raw',
  optional: true,
  sort: false,
  type: 'string[]'
},
{
  facet: true,
  index: true,
  infix: false,
  locale: '',
  name: 'responses.body.valueType',
  optional: true,
  sort: false,
  type: 'string[]'
},
{
  facet: true,
  index: true,
  infix: false,
  locale: '',
  name: 'request.body._id',
  optional: true,
  sort: false,
  type: 'string[]'
},
{
  facet: true,
  index: true,
  infix: false,
  locale: '',
  name: 'request.body.isRequired',
  optional: true,
  sort: false,
  type: 'bool[]'
},
{
  facet: true,
  index: true,
  infix: false,
  locale: '',
  name: 'request.body.name',
  optional: true,
  sort: false,
  type: 'string[]'
},
`
```
This is how schema looks after importing documents

```
`const { data, isLoading } = useSearch({
query: `?q=${query}&query_by=name,description,request,responses,(...other subfields)`,
enabled: !!query,
});`
```
This is front-end side.

Thing is, It does not work like that, when I search. I just want validate If I understand the concept right. It still searching only for the name and the description.

Should I add all the subfields to query_by?
[stackowerflow](https://stackoverflow.com/questions/75543056/typesense-indexing-nested-fields/75552841#75552841)
I am not saying this really an issue, might be my foult. Just wanna ask community, what they think.

**Comment by kishorenc** [comment]
@BekaArabidze98 

Are you sure you are using Typesense 0.24? Here's a simple example that I tried which seems to work without any issues:

https://gist.github.com/kishorenc/111d223254252dd5066505a5dbbe17ee

Please post a similar snippet that shows the problem you are facing, so that I can reproduce the issue.

**Comment by BekaArabidze98** [comment]
I have this version installed "typesense": "^1.4.4". But I dont know If this is a version 0.24

**Comment by BekaArabidze98** [comment]
@kishorenc 
https://gist.github.com/BekaArabidze98/37510ce63c5cac824e3f567f4ef2547e
I hope It somehow right snippet. I took request from my document.

**Comment by kishorenc** [comment]
I don't follow you. I ran the commands in your gist. When you query by `request`, the child fields are already being searched automatically. See here:

<img width="945" alt="Screenshot 2023-02-25 at 8 45 25 PM" src="https://user-images.githubusercontent.com/782073/221364825-a33a7e58-f5b1-4dd2-b003-d8144f3cbbdd.png">

**Comment by BekaArabidze98** [comment]
Thanks for the help again. I will run some tests and update you.

**Comment by BekaArabidze98** [comment]
Hey, I got an update. It seems nothing is being written in replica or someting, change stream is the foult I thinkg
`const publishedSectionModel = model('v2_published_section_new', publishedSectionSchema);

const schema = {
    name: 'v2_published_section_new',
    enable_nested_fields: true,
    fields: [
        { name: 'id', type: 'string', facet: false },
        { name: 'projectId', type: 'string', facet: false },
        { name: 'name', type: 'string', facet: false, infix: true },
        { name: 'description', type: 'string', facet: false, infix: true },
        // { name: 'request', type: 'object', facet: true },
        // { name: 'responses', type: 'object[]', facet: true },
        { name: 'createdAt', type: 'string', facet: false, sort: true },
    ],
    default_sorting_field: 'createdAt',
};

createSchema(schema);
const changeStream = publishedSectionModel.watch();
monitorListingsUsingEventEmitter({
    changeStream,
    schema,
    excludeFields: ['descriptionTextEditor', 'showBaseUrl', 'showLanguageBox', '__v'],
});`

should I listen to publishedSectionModel changes right?

**Comment by BekaArabidze98** [comment]
thanks for the help. You can close the issue
