### ISSUE TITLE
Incorrect facets typesense 0.25.0.rc12 (facetBy: "*")

### ISSUE THREAD

**Issue by pixelkoduje** [typesense/typesense#913]
Hello - I am using typesense 0.25.0.rc12.
When I query with facetBy: "*" I get the correct results however:
I also get a guy with the name "attribute" - which, as you know, is empty, because such properties do not exist.
![image](https://user-images.githubusercontent.com/102321542/221583402-2611dd4d-264b-4ff9-ab58-391a7b0b79b0.png)
This is how I create a collection. And that's where I get the guy - "attribute". However, I am using enable_nested_fields. And I don't really understand why this is happening. This consumes server resources unnecessarily and slows down queries.

![image](https://user-images.githubusercontent.com/102321542/221582889-6b8e6bcc-5670-4455-984f-083a9c27cb4f.png)

Why?

**Comment by pixelkoduje** [comment]
This creates a structure like this:
![image](https://user-images.githubusercontent.com/102321542/221584317-a42ab82c-ab64-483e-8698-8b28bd6f5311.png)

It's an invalid structure. It should create these attribute.upper, attribute.nose_type but not "attribute" itself. I have several hundred thousand items in my collection and it counts and spits "attribute" unnecessarily.

**Comment by kishorenc** [comment]
If I follow you correctly, we should not be returning the `attribute` object itself as a facet count value, correct? We will fix this.

**Comment by pixelkoduje** [comment]
Can you give me an example from TypeSense (InstantSearch)? I suggest introducing dynamic limits so that they automatically place them as standard - so that everyone is shocked by speed.

**Comment by jasonbosco** [comment]
Released in v26
