### ISSUE TITLE
Shifted highlight for words with non-alphabetical symbols inside (?)

### ISSUE THREAD

**Issue by b0g3r** [typesense/typesense#918]
## Description

For some reason when word contains some non-alphabetical symbol it then has shifted highlighting. For example, if content is var(--icon) if will be found by q: varicon but the highlight will be <mark>var(--i</mark> instead of <mark>var(--icon</mark>.

## Steps to reproduce

```bash
curl "http://localhost:8108/collections" \
       -X POST \
       -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
       -d '{
         "name": "test",
         "fields": [
           {"name": "content", "type": "string" }
         ]
       }'
       
curl "http://localhost:8108/collections/test/documents/import?action=create" \
        -X POST \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
        -H "Content-Type: text/plain" \
        -d '{"id": "124","content": "M size, color: var(--icon-secondary-neutral); For components with"}'

curl "http://localhost:8108/collections/test/documents/search?query_by=content&q=favicon" \
        -X GET \
        -H "Content-Type: application/json" \
        -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}"
```

## Expected Behavior

No found results (because `var(--icon` is so far from `favicon`)

```json
{"facet_counts":[],"found":0,"hits":[],"out_of":1,"page":1,"request_params":{"collection_name":"test","per_page":10,"q":"favicon"},"search_cutoff":false,"search_time_ms":2}
```

Or proper highlighting

```json
{"facet_counts":[],"found":1,"hits":[{"document":{"content":"M size, color: var(--icon-secondary-neutral); For components with","id":"124"},"highlights":[{"field":"content","matched_tokens":["var(--icon"],"snippet":"M size, color: <mark>var(--icon</mark>-secondary-neutral); For components with"}],"text_match":72341243945811969}],"out_of":1,"page":1,"request_params":{"collection_name":"test","per_page":10,"q":"favicon"},"search_cutoff":false,"search_time_ms":4}
```

## Actual Behavior

Shifted highlighting

```json
{"facet_counts":[],"found":1,"hits":[{"document":{"content":"M size, color: var(--icon-secondary-neutral); For components with","id":"124"},"highlights":[{"field":"content","matched_tokens":["var(--i"],"snippet":"M size, color: <mark>var(--i</mark>con-secondary-neutral); For components with"}],"text_match":72341243945811969}],"out_of":1,"page":1,"request_params":{"collection_name":"test","per_page":10,"q":"favicon"},"search_cutoff":false,"search_time_ms":4}
```

## Metadata

**Typesense Version**: 0.24.0 and 0.25.0.rc12

**OS**: x64

**Comment by kishorenc** [comment]
Fix available in `typesense/typesense:0.25.0.rc21`

**Comment by b0g3r** [comment]
Thank you Kishore! Do you have any eta for 0.25.0 public release? Even rough one, like "in 3-4 month" would be great

**Comment by kishorenc** [comment]
In 4-8 weeks. But I will be happy to share a stable 0.25 RC build for you to use if you wish (on Typesense Cloud as well as self hosting).

**Comment by b0g3r** [comment]
.tar.gz would be great 🙏

**Comment by kishorenc** [comment]
Here you go -- [tar.gz of 0.25.0.rc21](https://dl.typesense.org/releases/0.25.0.rc21/typesense-server-0.25.0.rc21-linux-amd64.tar.gz)

**Comment by b0g3r** [comment]
Do you have any pre-existing documentation for upgrade to 0.25.0? I upgraded and then downgraded back to 0.24.1, and got `Corruption: unknown checksum type 4 from footer of /app/data/db/005807.sst, while checking block at offset 2334 size 60`. Or it is better to create new issue?
