### ISSUE TITLE
Run typesense without a "data-dir" option?

### ISSUE THREAD

**Issue by chambers-y** [typesense/typesense#92]
General question: can the "data-dir" be made optional, so as to  to enable transient database startups / teardowns?

For my workflow, upserting / importing all the documents on every `docker start` is easier than persisting the data directory. Right now, I have to `mkdir ./tmp/typesense-data/` on start and then `rm -rf ./tmp/typesense-data` on cleanup, which is a bit tricky given the tools at my disposal.

What are your thoughts? 

I'm running typesense 0.11.2 on Ubuntu using the prebuilt docker image.

**Comment by kishorenc** [comment]
It's not possible to run Typesense without the `data-dir` as the documents are stored and fetched from disk. 

Instead of running `rm -rf` in the clean up, can you run it in the startup itself?

```
rm -rf /tmp/typesense-data
mkdir /tmp/typesense-data
```

This should be much easier (everything happens only in the start up).

**Comment by chambers-y** [comment]
Thank you for the fast response.

To be clear, my problem is not managing  the startup / cleanup. My problem is persistence-- but upon further digging, I realize that Docker containers are designed to be stateless, which is an architectural decision that is out of the scope of this project. 

I'll try to solve my particular problem with Docker volumes. Fingers crossed!
