### ISSUE TITLE
with std::unique_lock replace  std::shared_lock

### ISSUE THREAD

**Issue by jiayunwei** [typesense/typesense#925]
## Metadata

**Typesense Version**:

**OS**:

uint32_t Collection::get_next_seq_id() {
    std::shared_lock lock(mutex);
    store->increment(get_next_seq_id_key(name), 1);
    return next_seq_id++;
}

**Comment by kishorenc** [comment]
The shared lock protects access to the `store` object. You don't need a unique lock for the underlying increment operations on rocksdb since that's guaranteed to be thread safe by the rocksdb library.

**Comment by jiayunwei** [comment]
next_seq_id++ has thread safe problem, i++ not atomic

**Comment by kishorenc** [comment]
It is thread safe, because `next_seq_id` is an `atomic` type.

**Comment by jiayunwei** [comment]
oh, you are right, thank you for your reply. I want ask a question,  while adding document, these has a lock, this results search performence,  why adopt lucene method.
