### ISSUE TITLE
Improvement - Delete document should be idempotent 

### ISSUE THREAD

**Issue by mwawrusch** [typesense/typesense#929]
## Description

A document delete operation against an id returns an error when the document does not exist. This is not great, as the general behavior for delete is being idempotent, as with the delete only the outcome is important, not the action.

## Steps to reproduce

n/a

## Expected Behavior

It should do nothing

## Actual Behavior

It produces this error:

```
ObjectNotFound: Request failed with HTTP code 404 | Server said: Could not find a document with id: 1:test1
```
## Metadata

**Typesense Version**:

**OS**:

**Comment by kishorenc** [comment]
Thanks for creating this issue. I agree that it's useful to be able to ignore this error -- so we can add an option to do that.

**Comment by kishorenc** [comment]
In v26, there's a parameter `ignore_not_found` which can be set to `true`.
