### ISSUE TITLE
Large integer values are prohibited in the `default_sorting_field` even if that field is marked as "float"

### ISSUE THREAD

**Issue by JaredReisinger** [typesense/typesense#94]
## Description

I have a collection for which the most natural default sorting field is a timestamp.  Because current times (in milliseconds since the epoch) exceed the int32 range, I've defined the field as a "float".  Nevertheless, attempting to create a document in this collection gives me the error `Default sorting field 'date' exceeds maximum value of an int32.`.

The error is coming from https://github.com/typesense/typesense/blob/master/src/index.cpp#L160-L163, which I _think_ is using only the inferred type of the JSON value without checking the collection schema.  Since the value _can be_ an integer (there's no fractional part), it assumes that it _is_ one, but too large for a 32-bit value.

> Note: I am currently working around this problem by adding 0.1 to the timestamps when creating the document.  It's enough to bypass the "is it an integer" check, but it's kind of gross.

## Steps to reproduce

Define a collection such as:
```javascript
{
  name: 'test',
  fields: [
    { name: 'text', type: 'string' },
    { name: 'date', type: 'float' },  // current dates are too large for int32, so we use floats
  ],
  default_sorting_field: 'date',
}
```

Attempt to add a simple document (using typesense-js library):
```javascript
await client.collections('test').documents.create({
  text: 'here is some text',
  date: Date.now(),
});
```

## Expected Behavior

Since the field is defined as a float, I expect creating the document to succeed.

## Actual Behavior

You get the error `Default sorting field 'date' exceeds maximum value of an int32.`.

## Metadata

**Typsense Version**: 0.11.1

**OS**: Linux (Docker container running on Ubuntu on WSL/Windows)

**Comment by kishorenc** [comment]
Thank you for the detailed issue report. 

Certainly shouldn't be relying on the inference from the JSON value here. I also noticed that there are a few other places where this is being done, so will have to fix those as well.

As an aside, I wish the default sorting field could be of type int64 but that add be an additional 20% overhead in memory since that field is stored in all the tree nodes. Given that a timestamp is not very often a good fit as a measure of popularity, it's probably a decent trade-off. Storing millisecond precision timestamps in a float will result in a loss of precision though. Better to store it as seconds (until 2038!).

**Comment by JaredReisinger** [comment]
I had considered seconds-since-the-epoch, and decided against it specifically because of the Y2038 problem!  😄   Since we don't need this as true date fidelity--it's really just a tie-breaker for equal-similarity results--I had also considered (a) using seconds, and (b) rebasing to a different "zero" date, like 01-Jan-2000.  For my initial use-case, adding 0.1 was a quick and easy workaround.

As far as using 64-bit integers as the default sorting field... you _could_ leave it to your consumers to decide whether the 20% memory overhead is worth it or not, but it's good to know what kind o an impact it would have.

**Comment by edervishaj** [comment]
@kishorenc any planned int64 support for default sorting field?

**Comment by kishorenc** [comment]
Yup this is already fixed and will.be available next release for which a release candidate will be available next week!

**Comment by kishorenc** [comment]
@edervishaj `v0.15.0` has just been released and it allows you to use an int64 field as the default sorting field.
