### ISSUE TITLE
Feature request: Support faceting entire objects

### ISSUE THREAD

**Issue by 527bd5** [typesense/typesense#943]
## Feature Request

I would like support for faceting entire objects, not only subfields. For example, suppose you have a field `color` with objects like
```
{
  "name": "Forest Green",
  "h": 95,
  "s": 100,
  "l": 43
}
```
and you would like to display a search filter with colors. Currently it is only possible to facet by subfields, e.g., `facet_by=color.*`, which loses the structure and returns facet data like `{"value": 95, count: 13}` for `color.h`. Instead, I'd like to be able to get
```
{
  "value": {
    "name": "Forest Green",
    "h": 95,
    "s": 100,
    "l": 43
  },
  "count": 3
}
```

## Use Case
Color filters, or other filters where there's some metadata associated with the values.

**Comment by cpouldev** [comment]
+1 For that feature, as I applied some very hacky workarounds to add more payload to each facet

**Comment by hasanaktas** [comment]
Will any steps be taken in this regard?  Instead of making an additional database query, I want to trust the data returned directly from Typesense.

**Comment by kishorenc** [comment]
We're working in this at the moment and will be able to share a build that contains this feature in a week.

**Comment by kishorenc** [comment]
This feature is available on `0.26.0.rc20`. 

When you facet on a filed like `color.name` you can now do:

```
"facet_return_parent": "color.name"
```

This will return the parent `color` object as `parent` property in the facet response.

**Comment by hasanaktas** [comment]
@kishorenc
Isn't this feature added to the javascript library?

The version I use: 1.8.0-0

facet_return_parent does not exist.

**Comment by hasanaktas** [comment]
@kishorenc 
Can you help with this?
Version 1.8.0-1 has been released on npm and it looks like this feature hasn't been added.

**Comment by jasonbosco** [comment]
Just added this in `1.8.0-2` of typesense-js. Could you give it a shot now?

**Comment by Yaps551** [comment]
Is there an estimation on when this feature will be added for the python client of Typesense?

**Comment by jasonbosco** [comment]
The python client doesn't have types, so it should already work in the current version.

**Comment by dynamitesushi** [comment]
I'm using `1.8.0-2`  and `1.8.0-6` and it doesn't seem like it's working for me. @jasonbosco

**Comment by jasonbosco** [comment]
Released in v26
