### ISSUE TITLE
Add option to transform dots/periods to spaces in "query_by" fields

### ISSUE THREAD

**Issue by chambers-y** [typesense/typesense#95]
## Description

typesense does not correctly return results for query fields that store dot-based values. I am not sure if this is a bug or a design decision. 

## Steps to reproduce

Using a fresh install of typesense:

1. Add a document with a string field that stores dot-based values, e.g.
```
"java_lib": "com.nux.opensource.enterprise"
```
2. Attempt to search for that document based one part of the word, e.g.:
```
curl localhost:8108/collections/companies/documents/search/?q=opensource\&query_by=java_lib -H "X-TYPESENSE-API-KEY: api"
```
3. No hits are returned.

## Commands used
```
curl "http://localhost:8108/collections" -X POST -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: api" -d '{
         "name": "companies",
         "fields": [
           {"name": "java_lib", "type": "string" },
           {"name": "hello", "type": "int32" }
         ],
         "default_sorting_field": "hello"
       }'

curl "http://localhost:8108/collections/companies/documents" -X POST \
        -H "Content-Type: application/json" \
        -H "X-TYPESENSE-API-KEY: api" \
        -d '{
          "java_lib": "com.crump.opensource.enterprise",
          "hello": 1
        }'

curl "http://localhost:8108/collections/companies/documents/search?q=opensource&query_by=java_lib"
        -H "X-TYPESENSE-API-KEY: api"
```

## Expected Behavior

I expected for the document with the queried word to be returned.
Currently my workaround is to store a separate field just for querying, with dots replaced with spaces.

```
"java_lib": java_lib_name,
"java_lib_query": java_lib_name.replace(".", " ")
```
which compiles to
```
"java_lib": "com.nux.opensource.enterprise",
"java_lib_query": "com nux opensource enterprise"
```

This approach also forces the "q" query param to replace all dots with spaces.
Note that this bug does not affect the "filter_by" query param, which handles `.` as expected

## Suggested Fix

Have a per-field configuration option that allows queries to treat certain fields `.` characters as spaces, e.g.,
```
{
     fields: [
        { "name":  "java_lib", "type": "string", "space_dots": true }
     ]
}
```
## Metadata

**Typsense Version**: 0.11.2

**OS**: Ubuntu 16.04 Xenial

**Comment by kishorenc** [comment]
Thanks for the detailed issue report.

Typesense currently just removes all non-alphanumeric characters from the input string. So, `com.nux.opensource.enterprise` becomes just `comnuxopensourceenterprise`. Now, when you try to search for `opensource` since it exists in the middle of the indexed string, neither prefix search nor typo tolerance will not help.

We need to add a way to configure which special characters should be treated as "spaces". 

In the mean time, the work around you are using seems good.

**Comment by chambers-y** [comment]
Thanks for the quick response. Removing all non-alphanumeric characters from the input string is an interesting approach.

Does that mean the same behavior will be encountered with underscores or dashes? For example, `q=business_debt` becomes `businessdebt` and `?open-source-libb` becomes `opensourcelib`?

If that's the case, what do you think about replacing certain special characters by default to be spaces instead of stripping from the input string? In the context of a query string, I feel like "-", ".", and "_" are often intended to be word separators, which might mean that they don't have to be a configuration option.

**Comment by kishorenc** [comment]
Sorry I missed replying to this @chambers-y 

> Does that mean the same behavior will be encountered with underscores or dashes?

Definitely need to make this configurable. I think there are cases when treating hyphen as "nothing" or as a "space" both makes sense depending on context, so have to introduce a configuration at a field level to handle this.

**Comment by jasonbosco** [comment]
As v0.23.1 you can now customize the `token_separators` when creating the collection: https://typesense.org/docs/0.23.1/api/collections.html#schema-parameters
