### ISSUE TITLE
How to fetch hits on the second page?

### ISSUE THREAD

**Issue by kakalaWang** [typesense/typesense#955]
## Description

I use the following swift code to fetch hits from "companies" collection: 

let searchParameters = SearchParameters(q: "\\(searchText)", queryBy: "description", page: 3, perPage: 3)
let (searchData, _) = try await client.collection(name: "companies").documents().search(searchParameters, for: companyData.self)

When I print "searchData" out, it shows it can fetch data (3 pages with 3 hits on each page). However, in "searchData" there are only 3 hits from the first page. No more hits shown in "searchData". I use the following code to get access to hits on the first page: 

for index in 0...2 {
      searchData?.hits?[index].document?
}

My question is how to get access to hits on other pages? e.g., 3 hits on the second or third page?

**Comment by jasonbosco** [comment]
In this method call:

```
let searchParameters = SearchParameters(q: "\(searchText)", queryBy: "description", page: 3, perPage: 3)
let (searchData, _) = try await client.collection(name: "companies").documents().search(searchParameters, for: companyData.self)
```

You need to change the value of `page` to `page: 1` in the first API call to get the first page, then change it to `page: 2` in the second API call to get the 2nd page and finally `page: 3` in a separate API call to get the 3rd page.

**Comment by kakalaWang** [comment]
Thank you for the quick response. It is very helpful!
