### ISSUE TITLE
Collection schema migrations

### ISSUE THREAD

**Issue by sradevski** [typesense/typesense#96]
## Description

I wanted to make some schema changes, and as it is now, I can't see an easy way to do that, even if it is adding a new field to the schema. What is the expected approach for migrations?

**Typsense Version**: 0.11.2

**Comment by kishorenc** [comment]
For now, you will have to create another collection with the new field(s), reindex the data and swap the frontend to use the new collection.

**Comment by sonic182** [comment]
Hi @kishorenc, where I could see the format where data is saved, in datafiles, something like this I mean https://lucene.apache.org/core/5_1_0/core/org/apache/lucene/codecs/lucene50/Lucene50StoredFieldsFormat.html

I think it is the way data is stored, what makes difficult to allow collection migrations? would be nice to have the capability to add new fields without it implying a file data migration

**Comment by kishorenc** [comment]
The data is stored in rocksdb and you can see it in the `db` directory inside the data directory that you specify while starting the server. On start up, the data is indexed into memory based on the schema. 

> would be nice to have, at least, the ability to add new fields without it implying a file data migration

**Comment by kishorenc** [comment]
The data is stored in rocksdb and you can see it in the db directory inside the data directory that you specify while starting the server. On start up, the data is indexed into memory based on the schema.

> would be nice to have, at least, the ability to add new fields without it implying a file data migration

It's certainly possible to support adding new indices by allowing a modification of the schema + a restart (on the fly addition of schema would be harder since that would involve background indexing and catching up with new records being ingested). So, just a matter of implementing it :)

**Comment by zehawki** [comment]
Guys as mentioned in #361 - do you have an estimate of when you would release this feature? Note that I'm not requesting on-the-fly migration, but just a way to trigger a new migration on the existing data. 

Assuming that the data has already been imported, and the new or changed field etc can be accommodated by the existing data, eg a specific case that I have now where I just have to change a created_at field from float to int64. For this, and similar cases, one can save on massive time and effort in reimporting the data.

**Comment by kishorenc** [comment]
Next major feature I plan to pick up once I wrap up some ongoing tasks. So top of our list.

**Comment by digamber89** [comment]
+1 on this - Changing and Re-indexing is a pain when we have a lot of documents in a collection.

**Comment by ishnmu** [comment]
+1 badly need this feature

**Comment by huynv86** [comment]
+1 hope this come true soon

**Comment by adfdev** [comment]
+1 need this feature

**Comment by Meghabm07** [comment]
+1 need this feature

**Comment by vandres** [comment]
+1

**Comment by seowzhenjun0126** [comment]
Hi, would you be able to publish this version to DockerHub?

Thank you very much!

**Comment by jasonbosco** [comment]
@seowzhenjun0126 You should now see `0.23.0.rc70` in Docker Hub.

**Comment by kishorenc** [comment]
This is available in `v0.23`.
