### ISSUE TITLE
zsh: bad CPU type in executable: ./typesense-server on M2 Apple silicon

### ISSUE THREAD

**Issue by Neophen** [typesense/typesense#966]
## Description

Installed typesense-server 0.24.1 through brew. But after starting the service the health check, it always times out. Running brew services list shows error, but looking at the logs there are no errors.

only running the manual command you can see the error `zsh: bad CPU type in executable: ./typesense-server`

## Steps to reproduce

- Run on laptop with an `Apple M2 Pro` chip
- brew install typesense/tap/typesense-server@0.24.1
- brew services restart typesense-server@0.24.1

note: the error

## Expected Behavior

The executable should work without the `softwareupdate --install-rosetta` package. Or at least show a warning in brew, or a side note in docs that it's required.

## Actual Behavior

The executable needs `softwareupdate --install-rosetta` to be present to work

## Metadata

**Typesense Version**: 0.24.1

**OS**: Ventura 13.3

**Chip**: Apple M2 Pro

<img width="480" alt="Screenshot 2023-04-08 at 05 39 17" src="https://user-images.githubusercontent.com/6092928/230699864-27b4ae6b-791c-444f-9a6e-6e613bf28661.png">

**Comment by kishorenc** [comment]
From the next release (0.25), we will be able to support both native Intel and ARM mac builds. Right now, the build only targets Intel arch, so requires rosetta to be present.

**Comment by jasonbosco** [comment]
M1/M2 support is now available in v26
