### ISSUE TITLE
License incompatibilities

### ISSUE THREAD

**Issue by QuLogic** [typesense/typesense#98]
According to your [LICENSE.txt](https://github.com/typesense/typesense/blob/master/LICENSE.txt), it appears your project is under GPLv2. You don't seem to have any license notices in the files, so I assume it is not GPLv2 _or later_.

But [libfor](https://github.com/cruppstahl/libfor) is [Apache 2.0](https://github.com/cruppstahl/libfor/blob/master/LICENSE). The ASL 2.0 is not compatible with GPLv2, only GPLv3.

And OpenSSL is under the OpenSSL license. I can't quite figure out where you're linking with this, but it's also incompatible with the GPL.

See [this list maintained by GNU](https://www.gnu.org/licenses/license-list.html) or [the compatibility column of Fedora's table](https://fedoraproject.org/wiki/Licensing:Main#Good_Licenses).

**Comment by kishorenc** [comment]
Thank you for pointing this out. We will move to a compatible license in the next release.

**Comment by kishorenc** [comment]
Fixed in https://github.com/typesense/typesense/commit/fe1b188d47daa5bd2fca2d9498e93940f1e32bd9 -- next release will released on GPL v3.
