### ISSUE TITLE
What's new in typesense

### ISSUE THREAD

**Issue by pixelkoduje** [typesense/typesense#984]
I think this will be an interesting thread, before adding a new version, and going into beta to inform about what's new.  I have to admit that I have been behind for 2 months.  Did you introduce anything new in 0.25?  Do I see correctly in the commits that you want to automate content vectorization out of the box, or is this a mistake?

**Comment by kishorenc** [comment]
A change log for the RC builds will be useful, we will add that. 

> Do I see correctly in the commits that you want to automate content vectorization out of the box, or is this a mistake?

Correct. For English, we now support a model that can automatically vectorize a given set of fields during indexing.

**Comment by KULTI1995** [comment]
@kishorenc And why in English? If it's supposed to be for vector search and search for similar documents, then what does language matter?

**Comment by kishorenc** [comment]
Work in progress. We will support more models, we have begun with a model that's state of the art for English.

**Comment by KULTI1995** [comment]
But a very nice job, because there is no such thing anywhere else. Be sure to introduce the Polish language. You are the first, keep it up gentlemen! It's best to create a similarTo(id) function to fetch similar documents. That would be beautiful. @kishorenc

**Comment by vp-walter** [comment]
that's fantastic guys. keep up the good work.
