### ISSUE TITLE
Is there a way to normalize text match score?

### ISSUE THREAD

**Issue by alexandrulesi** [typesense/typesense#988]
## Description

Roughly speaking we are using typesense to match an entity to a user query, perform some calculations, and then return the result to the user. For now we want to return single results to the user and so we want to givem them an accuracy score for their result.

The text match scores we get from typesense are very large numbers which would not be meaningful to the user in the absence of other matches to compare to. Is there a way to normalize these numbers say to a scale of 0 - 100? Even if there is some loss of precision. We just want our users to know if this is more the ballpark of 50% or 80%.

**Comment by kishorenc** [comment]
We expose some of the matching information in the `text_match_info` attribute in the response. You can use that to define a similarity metric that's relevant for your application.

**Comment by alexandrulesi** [comment]
Indeed, that's the conclusion we're coming to as well. Is there documentation on the `text_match_info` object regarding what each of these fields represent?

**Comment by kishorenc** [comment]
The `text_match_info` object contains the following components:

- `tokens_matched`: number of query words that are found in the document
- `best_field_score`: text match score of the best field (this becomes the representative score for the document)
- `best_field_weight`: weight of the best matched field
- `fields_matched`: number of fields that contained atleast one token from the query

**Comment by alexandrulesi** [comment]
Alright, thanks!
