### ISSUE TITLE
Feature: Boosting fields

### ISSUE THREAD

**Issue by cboothe** [typesense/typesense#99]
## Description

Assuming there is an option to search across multiple fields. Is there also an option to boost / rank one field higher than another?

Example:

Search across fields: model_no, part_no, title, description

A match on model_no or part_no would be an exact match because it matches a SKU. Can those fields be weighted higher?

**Comment by kishorenc** [comment]
@cboothe 

The order of the fields in the `query_by` parameter is important: a record that matches on a field earlier in the list is considered more relevant than a record matched on a field later in the list. 

So, if you have `query_by=model_no,part_no,title,description` documents that match on the `model_no` field are ranked above documents matched on the `part_no` and so on.

**Comment by joeyfromnijmegen** [comment]
It will be awesome if you are more control over the boosting parameters. Taking your above example `query_by=model_no,part_no,title,description ` to query_by=model_no^3,part_no^2,title^1,description ^0.5

**Comment by jasonbosco** [comment]
@joeyfromnijmegen This is now possible using the query_by_weights parameter. More info here: https://github.com/typesense/typesense/issues/165#issuecomment-751958056
