### ISSUE TITLE
Sort tie breaker

### ISSUE THREAD

**Issue by phungtranminh** [typesense/typesense#995]
## Description

The document is a bit scattered in this topic so I will gather based on my knowledge of typesense so far:

Default sort order is: `_text_match:desc,default_sorting_field:desc`

When I specify sort like `field_x:asc,field_y:desc` (3 fields max) and the tie-breaker is order of insertion.

I would like to specify tie-breaker as order of insertion, but first insertion goes first (i.e. `asc`) not default `desc`.

How would I do so? thanks!

## Steps to reproduce

Mentioned in description.

## Expected Behavior

It would be nice to have to a way to specify tie breaker field and order clearly and uniformly.

## Actual Behavior

The idea of order of insertion and default sorting field currently are somewhat conflated, since they are doing the same thing, i.e. tie breaking.

Maybe we just need a section like this

```
Default tie breaker is insertion time, you can change order from `desc` to `asc` like this `...`

You can change tie breaker field to other field like this `...`
```

## Metadata

**Typesense Version**:

0.24.1

**OS**:

masOS

**Comment by kishorenc** [comment]
Every document inserted into Typesense gets a unique auto incrementing `id`. This internal `id` is always used as the last sorting field (this is in addition to the 3 fields exposed outside). This ensures that the sorting is always "stable" when the sort field values are the same. There is no way to modify this final tie breaking order. 

If you want to sort ascending by insertion time, have a  `inserted_at` timestamp field and then you can sort it as you need it as the third sorting field.

**Comment by phungtranminh** [comment]
Thanks, does it mean that the default sort order is either

`_text_match:desc,default_sorting_field:desc,id:desc`

Or `field_x:asc,field_y:desc,id:desc`

**Comment by kishorenc** [comment]
Correct. The `id:desc` is always added last, implicitly.
