### ISSUE TITLE
Allow i64 to be default sorting field

### ISSUE THREAD

**Issue by phungtranminh** [typesense/typesense#996]
## Description

From the document `The name of an int32 / float field that determines the order..` it looks like only int32 or float can be default sorting field.

I haven't ventured to try it out but it would be nice to use i64 as default sorting field.

Thanks!

## Steps to reproduce

N/A

## Expected Behavior

N/A

## Actual Behavior

N/A

## Metadata

0.24.1

macOS

**Comment by kishorenc** [comment]
This is not possible and is a design decision. Default sorting field is meant primarily as a popularity metric. Since it's used in all core in-memory data structures, the size of this field has impact on memory usage. So we restrict it to 4 bytes (int32 or float).

**Comment by phungtranminh** [comment]
Okay, thanks for the explanation!
